items:
- uid: client._application_management
  id: _application_management
  parent: client
  children:
  - client._application_management.main(String[])
  href: client._application_management.yml
  langs:
  - java
  name: ApplicationManagement
  fullName: client.ApplicationManagement
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/sample/ManagedAPIs/ApplicationManagement1/ApplicationManagement/src/client/ApplicationManagement.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/sample/ManagedAPIs/ApplicationManagement1/ApplicationManagement/src/client/ApplicationManagement.java
    startLine: 15
  package: client
  syntax:
    content: public class ApplicationManagement
  inheritance:
  - java.lang.Object
- uid: client._application_management.main(String[])
  id: main(String[])
  parent: client._application_management
  href: client._application_management.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void client.ApplicationManagement.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/sample/ManagedAPIs/ApplicationManagement1/ApplicationManagement/src/client/ApplicationManagement.java
    startLine: 23
  package: client
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
      description: <p>the command line arguments </p>
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
