items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c
  id: _windows_performance_counter_as_p_c
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.getId()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.report(TelemetryClient)
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.WindowsPerformanceCounterAsPC()
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.yml
  langs:
  - java
  name: WindowsPerformanceCounterAsPC
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsPC
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>Built-in Windows performance counters that are sent as <xref href="com.microsoft.applicationinsights.telemetry._performance_counter_telemetry" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterAsPC extends AbstractWindowsPerformanceCounter
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.AbstractWindowsPerformanceCounter()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.reportError(double,String)
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsPC.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
    startLine: 85
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String getId()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.report(TelemetryClient)
  id: report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.yml
  langs:
  - java
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsPC.report(TelemetryClient telemetryClient)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.WindowsPerformanceCounterAsPC()
  id: WindowsPerformanceCounterAsPC()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.yml
  langs:
  - java
  name: WindowsPerformanceCounterAsPC()
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsPC.WindowsPerformanceCounterAsPC()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>Registers the 'built-in' Windows performance counters that are not fetched from the JVM JMX.</p>

    <p></p>
  syntax:
    content: public WindowsPerformanceCounterAsPC()
  exceptions:
  - type: b7c46b4b
    description: <p>The constructor might throw an Error if the <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> is not able to properly connect to the native code. or Exception if the constructor is not called under Windows OS. </p>
references:
- uid: b7c46b4b
  spec.java:
  - name: java.lang.Throwable
    fullName: java.lang.Throwable
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.AbstractWindowsPerformanceCounter()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: AbstractWindowsPerformanceCounter()
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter.AbstractWindowsPerformanceCounter()
  type: Constructor
  syntax:
    content: protected AbstractWindowsPerformanceCounter()
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.reportError(double,String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: reportError(double value, String displayName)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter.reportError(double value, String displayName)
  type: Method
  syntax:
    content: protected void reportError(double value, String displayName)
    parameters:
    - id: value
      type: a07dcde8
    - id: displayName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: AbstractWindowsPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter
  type: Class
  summary: <p>Created by gupele on 4/29/2015. </p>
  syntax:
    content: public class AbstractWindowsPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  name: WindowsPerformanceCounterData
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterData
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  name: JniPCConnector
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector
  type: Class
  summary: >-
    <p>This class serves as the connection to the native code that does the work with Windows.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class JniPCConnector
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry.yml
  name: PerformanceCounterTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetry
  type: Class
  summary: <p>The class that represents information about performance counters. </p>
  syntax:
    content: public class PerformanceCounterTelemetry extends BaseTelemetry<PerformanceCounterData>
