items:
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  id: _telemetry_processor_creator_test
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testBadClass()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testNullInput()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorThatFailsInCtor()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorThatThrowsInSetter()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorValidProcessorsWithSetters()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorWithoutSetters()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorWithWrongSetterActivatedSetters()
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: TelemetryProcessorCreatorTest
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TelemetryProcessorCreatorTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testBadClass()
  id: testBadClass()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testBadClass()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testBadClass()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 90
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testBadClass()
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testNullInput()
  id: testNullInput()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testNullInput()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testNullInput()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testNullInput()
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorThatFailsInCtor()
  id: testProcessorThatFailsInCtor()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testProcessorThatFailsInCtor()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testProcessorThatFailsInCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 100
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testProcessorThatFailsInCtor()
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorThatThrowsInSetter()
  id: testProcessorThatThrowsInSetter()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testProcessorThatThrowsInSetter()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testProcessorThatThrowsInSetter()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 110
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testProcessorThatThrowsInSetter()
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorValidProcessorsWithSetters()
  id: testProcessorValidProcessorsWithSetters()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testProcessorValidProcessorsWithSetters()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testProcessorValidProcessorsWithSetters()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testProcessorValidProcessorsWithSetters()
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorWithoutSetters()
  id: testProcessorWithoutSetters()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testProcessorWithoutSetters()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testProcessorWithoutSetters()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testProcessorWithoutSetters()
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.testProcessorWithWrongSetterActivatedSetters()
  id: testProcessorWithWrongSetterActivatedSetters()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  langs:
  - java
  name: testProcessorWithWrongSetterActivatedSetters()
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest.testProcessorWithWrongSetterActivatedSetters()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
    startLine: 69
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void testProcessorWithWrongSetterActivatedSetters()
references: []
