items:
- uid: com.microsoft.applicationinsights.internal.util._thread_pool_utils
  id: _thread_pool_utils
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._thread_pool_utils.newLimitedThreadPool(int,int,long,int)
  - com.microsoft.applicationinsights.internal.util._thread_pool_utils.stop(ThreadPoolExecutor,long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.util._thread_pool_utils.yml
  langs:
  - java
  name: ThreadPoolUtils
  fullName: com.microsoft.applicationinsights.internal.util.ThreadPoolUtils
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadPoolUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadPoolUtils.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public class ThreadPoolUtils
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._thread_pool_utils.newLimitedThreadPool(int,int,long,int)
  id: newLimitedThreadPool(int,int,long,int)
  parent: com.microsoft.applicationinsights.internal.util._thread_pool_utils
  href: com.microsoft.applicationinsights.internal.util._thread_pool_utils.yml
  langs:
  - java
  name: newLimitedThreadPool(int minNumberOfThreads, int maxNumberOfThreads, long defaultRemoveIdleThread, int bufferSize)
  fullName: static ThreadPoolExecutor com.microsoft.applicationinsights.internal.util.ThreadPoolUtils.newLimitedThreadPool(int minNumberOfThreads, int maxNumberOfThreads, long defaultRemoveIdleThread, int bufferSize)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadPoolUtils.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static ThreadPoolExecutor newLimitedThreadPool(int minNumberOfThreads, int maxNumberOfThreads, long defaultRemoveIdleThread, int bufferSize)
    parameters:
    - id: minNumberOfThreads
      type: f75371fa
    - id: maxNumberOfThreads
      type: f75371fa
    - id: defaultRemoveIdleThread
      type: 0364520f
    - id: bufferSize
      type: f75371fa
    return:
      type: 8faef6a4
- uid: com.microsoft.applicationinsights.internal.util._thread_pool_utils.stop(ThreadPoolExecutor,long,TimeUnit)
  id: stop(ThreadPoolExecutor,long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.util._thread_pool_utils
  href: com.microsoft.applicationinsights.internal.util._thread_pool_utils.yml
  langs:
  - java
  name: stop(ThreadPoolExecutor threadPool, long timeout, TimeUnit timeUnit)
  fullName: static void com.microsoft.applicationinsights.internal.util.ThreadPoolUtils.stop(ThreadPoolExecutor threadPool, long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadPoolUtils.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static void stop(ThreadPoolExecutor threadPool, long timeout, TimeUnit timeUnit)
    parameters:
    - id: threadPool
      type: 8faef6a4
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 8faef6a4
  spec.java:
  - name: ThreadPoolExecutor
    fullName: ThreadPoolExecutor
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
