items:
- uid: com.microsoft.applicationinsights.internal.system._system_information
  id: _system_information
  parent: com.microsoft.applicationinsights.internal.system
  children:
  - com.microsoft.applicationinsights.internal.system._system_information.getProcessId()
  - com.microsoft.applicationinsights.internal.system._system_information.isUnix()
  - com.microsoft.applicationinsights.internal.system._system_information.isWindows()
  href: com.microsoft.applicationinsights.internal.system._system_information.yml
  langs:
  - java
  name: SystemInformation
  fullName: com.microsoft.applicationinsights.internal.system.SystemInformation
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.system
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public enum SystemInformation
  inheritance:
  - java.lang.Object
  - java.lang.Enum<SystemInformation>
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.system._system_information_1ad3e742a2d61ca37a481e401717ed89b0
- uid: com.microsoft.applicationinsights.internal.system._system_information.getProcessId()
  id: getProcessId()
  parent: com.microsoft.applicationinsights.internal.system._system_information
  href: com.microsoft.applicationinsights.internal.system._system_information.yml
  langs:
  - java
  name: getProcessId()
  fullName: String com.microsoft.applicationinsights.internal.system.SystemInformation.getProcessId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.system
  syntax:
    content: public String getProcessId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.system._system_information.isUnix()
  id: isUnix()
  parent: com.microsoft.applicationinsights.internal.system._system_information
  href: com.microsoft.applicationinsights.internal.system._system_information.yml
  langs:
  - java
  name: isUnix()
  fullName: boolean com.microsoft.applicationinsights.internal.system.SystemInformation.isUnix()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.system
  syntax:
    content: public boolean isUnix()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.system._system_information.isWindows()
  id: isWindows()
  parent: com.microsoft.applicationinsights.internal.system._system_information
  href: com.microsoft.applicationinsights.internal.system._system_information.yml
  langs:
  - java
  name: isWindows()
  fullName: boolean com.microsoft.applicationinsights.internal.system.SystemInformation.isWindows()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.system
  syntax:
    content: public boolean isWindows()
    return:
      type: 4fc6e284
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.internal.system._system_information_1ad3e742a2d61ca37a481e401717ed89b0
