items:
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  id: _application_insights_log_event_test
  parent: com.microsoft.applicationinsights.logback.internal
  children:
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testAllSeverityLevel()
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testDebugSeverityLevel()
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testErrorSeverityLevel()
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testInfoSeverityLevel()
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testTraceSeverityLevel()
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testWarningSeverityLevel()
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: ApplicationInsightsLogEventTest
  fullName: com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest
  type: Class
  source:
    remote: &o0
      path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public class ApplicationInsightsLogEventTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testAllSeverityLevel()
  id: testAllSeverityLevel()
  parent: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: testAllSeverityLevel()
  fullName: void com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest.testAllSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 62
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public void testAllSeverityLevel()
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testDebugSeverityLevel()
  id: testDebugSeverityLevel()
  parent: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: testDebugSeverityLevel()
  fullName: void com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest.testDebugSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 52
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public void testDebugSeverityLevel()
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testErrorSeverityLevel()
  id: testErrorSeverityLevel()
  parent: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: testErrorSeverityLevel()
  fullName: void com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest.testErrorSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 37
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public void testErrorSeverityLevel()
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testInfoSeverityLevel()
  id: testInfoSeverityLevel()
  parent: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: testInfoSeverityLevel()
  fullName: void com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest.testInfoSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 42
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public void testInfoSeverityLevel()
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testTraceSeverityLevel()
  id: testTraceSeverityLevel()
  parent: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: testTraceSeverityLevel()
  fullName: void com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest.testTraceSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 57
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public void testTraceSeverityLevel()
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.testWarningSeverityLevel()
  id: testWarningSeverityLevel()
  parent: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  langs:
  - java
  name: testWarningSeverityLevel()
  fullName: void com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest.testWarningSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEventTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.logback.internal
  syntax:
    content: public void testWarningSeverityLevel()
references:
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
