items:
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry
  id: _trace_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.additionalSanitize()
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.getData()
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.getMessage()
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.getSeverityLevel()
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.setMessage(String)
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.setSeverityLevel(SeverityLevel)
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.TraceTelemetry()
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.TraceTelemetry(String)
  - com.microsoft.applicationinsights.telemetry._trace_telemetry.TraceTelemetry(String,SeverityLevel)
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: TraceTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.TraceTelemetry
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 29
  package: com.microsoft.applicationinsights.telemetry
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used for log messages. </p>
  syntax:
    content: public class TraceTelemetry extends BaseTelemetry<MessageData>
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._base_telemetry
  inheritedMembers:
  - com.microsoft.applicationinsights.telemetry._base_telemetry.BaseTelemetry()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getContext()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getProperties()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getSequence()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getTimestamp()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.initialize(ConcurrentMap<String, String>)
  - com.microsoft.applicationinsights.telemetry._base_telemetry.sanitize()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.telemetry._base_telemetry.setSequence(String)
  - com.microsoft.applicationinsights.telemetry._base_telemetry.setTimestamp(Date)
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.additionalSanitize()
  id: additionalSanitize()
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: additionalSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.TraceTelemetry.additionalSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 75
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected void additionalSanitize()
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: getData()
  fullName: MessageData com.microsoft.applicationinsights.telemetry.TraceTelemetry.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 80
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected MessageData getData()
    return:
      type: 85cfc473
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.getMessage()
  id: getMessage()
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: getMessage()
  fullName: String com.microsoft.applicationinsights.telemetry.TraceTelemetry.getMessage()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 62
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the message text. For example, the text that would normally be written to a log file line. </p>
  syntax:
    content: public String getMessage()
    return:
      type: "26831127"
      description: <p>The message. </p>
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.getSeverityLevel()
  id: getSeverityLevel()
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: getSeverityLevel()
  fullName: SeverityLevel com.microsoft.applicationinsights.telemetry.TraceTelemetry.getSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 88
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public SeverityLevel getSeverityLevel()
    return:
      type: com.microsoft.applicationinsights.telemetry._severity_level
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.setMessage(String)
  id: setMessage(String)
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: setMessage(String message)
  fullName: void com.microsoft.applicationinsights.telemetry.TraceTelemetry.setMessage(String message)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 70
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the message text. For example, the text that would normally be written to a log file line. </p>
  syntax:
    content: public void setMessage(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message. </p>
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.setSeverityLevel(SeverityLevel)
  id: setSeverityLevel(SeverityLevel)
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: setSeverityLevel(SeverityLevel severityLevel)
  fullName: void com.microsoft.applicationinsights.telemetry.TraceTelemetry.setSeverityLevel(SeverityLevel severityLevel)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 84
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setSeverityLevel(SeverityLevel severityLevel)
    parameters:
    - id: severityLevel
      type: com.microsoft.applicationinsights.telemetry._severity_level
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.TraceTelemetry()
  id: TraceTelemetry()
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: TraceTelemetry()
  fullName: com.microsoft.applicationinsights.telemetry.TraceTelemetry.TraceTelemetry()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 35
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Default Ctor </p>
  syntax:
    content: public TraceTelemetry()
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.TraceTelemetry(String)
  id: TraceTelemetry(String)
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: TraceTelemetry(String message)
  fullName: com.microsoft.applicationinsights.telemetry.TraceTelemetry.TraceTelemetry(String message)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 39
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public TraceTelemetry(String message)
    parameters:
    - id: message
      type: "26831127"
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry.TraceTelemetry(String,SeverityLevel)
  id: TraceTelemetry(String,SeverityLevel)
  parent: com.microsoft.applicationinsights.telemetry._trace_telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  langs:
  - java
  name: TraceTelemetry(String message, SeverityLevel severityLevel)
  fullName: com.microsoft.applicationinsights.telemetry.TraceTelemetry.TraceTelemetry(String message, SeverityLevel severityLevel)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
    startLine: 48
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Initializes a new instance of the class with the specified parameter 'message'. </p>
  syntax:
    content: public TraceTelemetry(String message, SeverityLevel severityLevel)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message. </p>
    - id: severityLevel
      type: com.microsoft.applicationinsights.telemetry._severity_level
      description: <p>The severity level. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 85cfc473
  spec.java:
  - name: MessageData
    fullName: MessageData
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.BaseTelemetry()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: BaseTelemetry()
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.BaseTelemetry()
  type: Constructor
  syntax:
    content: protected BaseTelemetry()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getContext()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getContext()
  fullName: TelemetryContext com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getContext()
  type: Method
  summary: <p>Gets the context associated with the current telemetry item. </p>
  syntax:
    content: public TelemetryContext getContext()
    return:
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>The context </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getProperties()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getProperties()
  fullName: Map<String, String> com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getProperties()
  type: Method
  summary: <p>Gets a dictionary of application-defined property names and values providing additional information about this event. </p>
  syntax:
    content: public Map<String, String> getProperties()
    return:
      type: 689c8cb5
      description: <p>The properties </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getSequence()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getSequence()
  fullName: String com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getSequence()
  type: Method
  summary: >-
    <p>Sequence field used to track absolute order of uploaded events. It is a two-part value that includes a stable identifier for the current boot session and an incrementing identifier for each event added to the upload queue</p>

    <p>The Sequence helps track how many events were fired and how many events were uploaded and enables identification of data lost during upload and de-duplication of events on the ingress server.</p>

    <p>Gets the value that defines absolute order of the telemetry item. </p>
  syntax:
    content: public String getSequence()
    return:
      type: "26831127"
      description: <p>The sequence of the <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>. </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getTimestamp()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getTimestamp()
  fullName: Date com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getTimestamp()
  type: Method
  summary: <p>Gets date and time when event was recorded. </p>
  syntax:
    content: public Date getTimestamp()
    return:
      type: "12977444"
      description: <p>The timestamp as Date </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.initialize(ConcurrentMap<String, String>)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: initialize(ConcurrentMap<String, String> properties)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.initialize(ConcurrentMap<String, String> properties)
  type: Method
  summary: <p>Initializes the instance with the context properties </p>
  syntax:
    content: protected void initialize(ConcurrentMap<String, String> properties)
    parameters:
    - id: properties
      type: bc7a2f3a
      description: <p>The context properties </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.sanitize()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: sanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.sanitize()
  type: Method
  summary: <p>Makes sure the data to send is sanitized from bad chars, proper length etc. </p>
  syntax:
    content: public void sanitize()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  summary: <p>Serializes this object in JSON format. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer that helps with serializing into Json format </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.setSequence(String)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: setSequence(String sequence)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.setSequence(String sequence)
  type: Method
  summary: <p>Sets the value that defines absolute order of the telemetry item. </p>
  syntax:
    content: public void setSequence(String sequence)
    parameters:
    - id: sequence
      type: "26831127"
      description: <p>The sequence of the <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>. </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.setTimestamp(Date)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: setTimestamp(Date date)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.setTimestamp(Date date)
  type: Method
  summary: <p>Sets date and time when event was recorded. </p>
  syntax:
    content: public void setTimestamp(Date date)
    parameters:
    - id: date
      type: "12977444"
      description: <p>The timestamp as Date. </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: BaseTelemetry<T>
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetry<T>
  type: Class
  summary: <p>Superclass for all telemetry data classes. </p>
  syntax:
    content: public class BaseTelemetry<T extends SendableData> implements Telemetry
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
