items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  id: _transmission_file_system_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.fetchOldestFile()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.send(Transmission)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.setCapacity(int)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.stop(long,TimeUnit)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.TransmissionFileSystemOutput()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.TransmissionFileSystemOutput(String)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.TransmissionFileSystemOutput(String,String)
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: TransmissionFileSystemOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The class knows how to manage <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> that needs to be saved to the file system.</p>

    <p>The class works on a pre-defined folder and should know the size of disk it can use.</p>

    <p>With that data it knows how to store incoming Transmissions and store them into files that can be later be read back into Transmissions.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class TransmissionFileSystemOutput implements TransmissionOutput
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.channel._transmission_output
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.capacityEnforcer()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.fetchOldestFile()
  id: fetchOldestFile()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: fetchOldestFile()
  fullName: Transmission com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.fetchOldestFile()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 160
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public Transmission fetchOldestFile()
    return:
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.send(Transmission)
  id: send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.send(Transmission transmission)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 135
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.setCapacity(int)
  id: setCapacity(int)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: setCapacity(int suggestedCapacity)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.setCapacity(int suggestedCapacity)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 203
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void setCapacity(int suggestedCapacity)
    parameters:
    - id: suggestedCapacity
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 157
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.TransmissionFileSystemOutput()
  id: TransmissionFileSystemOutput()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: TransmissionFileSystemOutput()
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.TransmissionFileSystemOutput()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 126
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public TransmissionFileSystemOutput()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.TransmissionFileSystemOutput(String)
  id: TransmissionFileSystemOutput(String)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: TransmissionFileSystemOutput(String folderPath)
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.TransmissionFileSystemOutput(String folderPath)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 130
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public TransmissionFileSystemOutput(String folderPath)
    parameters:
    - id: folderPath
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.TransmissionFileSystemOutput(String,String)
  id: TransmissionFileSystemOutput(String,String)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  langs:
  - java
  name: TransmissionFileSystemOutput(String folderPath, String maxTransmissionStorageCapacity)
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.TransmissionFileSystemOutput(String folderPath, String maxTransmissionStorageCapacity)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
    startLine: 100
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public TransmissionFileSystemOutput(String folderPath, String maxTransmissionStorageCapacity)
    parameters:
    - id: folderPath
      type: "26831127"
    - id: maxTransmissionStorageCapacity
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.capacityEnforcer()
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: TransmissionOutput
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionOutput
  type: Interface
  summary: >-
    <p>Defines the interface of classes that get a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and can 'send' it.</p>

    <p>Concrete classes can 'send' the data to remote server, to disk, database etc.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  name: LimitsEnforcer
  fullName: com.microsoft.applicationinsights.internal.util.LimitsEnforcer
  type: Class
  summary: <p>Created by gupele on 5/10/2015. </p>
  syntax:
    content: public class LimitsEnforcer
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TransmissionOutput.send(Transmission transmission)
  type: Method
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
