items:
- uid: com.microsoft.applicationinsights.internal.shutdown
  id: shutdown
  children:
  - com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity
  - com.microsoft.applicationinsights.internal.shutdown._stoppable
  href: com.microsoft.applicationinsights.internal.shutdown.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.shutdown
  fullName: com.microsoft.applicationinsights.internal.shutdown
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
    startLine: 21
  syntax:
    content: namespace shutdown
references:
- uid: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity
  parent: com.microsoft.applicationinsights.internal.shutdown
  href: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.yml
  name: SDKShutdownActivity
  fullName: com.microsoft.applicationinsights.internal.shutdown.SDKShutdownActivity
  type: Enum
  summary: >-
    <p>The class is responsible for all shutdown activities done in the SDK.</p>

    <p>Created by gupele on 2/2/2015. </p>
  syntax:
    content: public enum SDKShutdownActivity
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable
  parent: com.microsoft.applicationinsights.internal.shutdown
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: Stoppable
  fullName: com.microsoft.applicationinsights.internal.shutdown.Stoppable
  type: Interface
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface Stoppable
