items:
- uid: com.microsoft.applicationinsights.channel._telemetry_channel
  id: _telemetry_channel
  parent: com.microsoft.applicationinsights.channel
  children:
  - com.microsoft.applicationinsights.channel._telemetry_channel.flush()
  - com.microsoft.applicationinsights.channel._telemetry_channel.isDeveloperMode()
  - com.microsoft.applicationinsights.channel._telemetry_channel.send(Telemetry)
  - com.microsoft.applicationinsights.channel._telemetry_channel.setDeveloperMode(boolean)
  - com.microsoft.applicationinsights.channel._telemetry_channel.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  langs:
  - java
  name: TelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.TelemetryChannel
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 30
  package: com.microsoft.applicationinsights.channel
  summary: <p>Represents a communication channel for sending telemetry to application insights. </p>
  syntax:
    content: public interface TelemetryChannel
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.flush()
  id: flush()
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  langs:
  - java
  name: flush()
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.flush()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 60
  package: com.microsoft.applicationinsights.channel
  summary: <p>Flushes the data that the channel might have internally. </p>
  syntax:
    content: public void flush()
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.isDeveloperMode()
  id: isDeveloperMode()
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  langs:
  - java
  name: isDeveloperMode()
  fullName: boolean com.microsoft.applicationinsights.channel.TelemetryChannel.isDeveloperMode()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 36
  package: com.microsoft.applicationinsights.channel
  summary: <p>Gets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public boolean isDeveloperMode()
    return:
      type: 4fc6e284
      description: <p>The developer mode. </p>
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.send(Telemetry)
  id: send(Telemetry)
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  langs:
  - java
  name: send(Telemetry item)
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.send(Telemetry item)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 48
  package: com.microsoft.applicationinsights.channel
  summary: <p>Sends a Telemetry instance through the channel. </p>
  syntax:
    content: public void send(Telemetry item)
    parameters:
    - id: item
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The Telemetry item to send. </p>
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.setDeveloperMode(boolean)
  id: setDeveloperMode(boolean)
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  langs:
  - java
  name: setDeveloperMode(boolean value)
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.setDeveloperMode(boolean value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 42
  package: com.microsoft.applicationinsights.channel
  summary: <p>Sets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public void setDeveloperMode(boolean value)
    parameters:
    - id: value
      type: 4fc6e284
      description: <p>True for applying develoer mode </p>
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 55
  package: com.microsoft.applicationinsights.channel
  summary: <p>Stops on going work </p>
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>Time to try and stop </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The units of the 'timeout' parameter </p>
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: InProcessTelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel
  type: Class
  summary: >-
    <p>An implementation of <xref href="com.microsoft.applicationinsights.channel._telemetry_channel" data-throw-if-not-resolved="false"></xref></p>

    <p>The channel holds two main entities:</p>

    <p>A buffer for incoming <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances A transmitter</p>

    <p>The buffer is stores incoming telemetry instances. Every new buffer starts a timer. When the timer expires, or when the buffer is 'full' (whichever happens first), the transmitter will pick up that buffer and will handle its sending to the server. For example, a transmitter will be responsible for compressing, sending and activate a policy in case of failures.</p>

    <p>The model here is:</p>

    <p>Use application threads to populate the buffer Use channel's threads to send buffers to the server</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class InProcessTelemetryChannel implements TelemetryChannel
- uid: com.microsoft.applicationinsights.internal.channel.simplehttp._simple_http_channel
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  parent: com.microsoft.applicationinsights.internal.channel.stdout
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: StdOutChannel
  fullName: com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel
  type: Class
  summary: <p>A telemetry channel routing information to stdout. </p>
  syntax:
    content: public class StdOutChannel implements TelemetryChannel
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.isDeveloperMode()
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: isDeveloperMode()
  fullName: boolean com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.isDeveloperMode()
  type: Method
  summary: <p>Gets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public boolean isDeveloperMode()
    return:
      type: 4fc6e284
      description: <p>The developer mode. </p>
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.isDeveloperMode()
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: isDeveloperMode()
  fullName: boolean com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.isDeveloperMode()
  type: Method
  summary: <p>Gets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public boolean isDeveloperMode()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.setDeveloperMode(boolean)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: setDeveloperMode(boolean value)
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.setDeveloperMode(boolean value)
  type: Method
  summary: <p>Sets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public void setDeveloperMode(boolean value)
    parameters:
    - id: value
      type: 4fc6e284
      description: <p>True for applying develoer mode </p>
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.setDeveloperMode(boolean)
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: setDeveloperMode(boolean developerMode)
  fullName: void com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.setDeveloperMode(boolean developerMode)
  type: Method
  summary: <p>Sets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public void setDeveloperMode(boolean developerMode)
    parameters:
    - id: developerMode
      type: 4fc6e284
      description: <p>True or false </p>
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.send(Telemetry)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: send(Telemetry item)
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.send(Telemetry item)
  type: Method
  summary: <p>Sends a Telemetry instance through the channel. </p>
  syntax:
    content: public void send(Telemetry item)
    parameters:
    - id: item
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The Telemetry item to send. </p>
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.send(Telemetry)
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: send(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.send(Telemetry telemetry)
  type: Method
  summary: <p>Sends a Telemetry instance through the channel. </p>
  syntax:
    content: public void send(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.stop(long timeout, TimeUnit timeUnit)
  type: Method
  summary: <p>Stops on going work </p>
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>Time to try and stop </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The units of the 'timeout' parameter </p>
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: synchronized void com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.stop(long timeout, TimeUnit timeUnit)
  type: Method
  summary: <p>Stops on going work </p>
  syntax:
    content: public synchronized void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.flush()
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: flush()
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.flush()
  type: Method
  summary: <p>Flushes the data that the channel might have internally. </p>
  syntax:
    content: public void flush()
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.flush()
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: flush()
  fullName: void com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.flush()
  type: Method
  summary: <p>Flushes the data that the channel might have internally. </p>
  syntax:
    content: public void flush()
