items:
- uid: com.microsoft.azure.management.network._application_gateway_backend
  id: _application_gateway_backend
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend.addresses()
  href: com.microsoft.azure.management.network._application_gateway_backend.yml
  langs:
  - java
  name: ApplicationGatewayBackend
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackend
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 21
  package: com.microsoft.azure.management.network
  summary: <p>An immutable client-side representation of an application gateway backend. </p>
  syntax:
    content: public interface ApplicationGatewayBackend extends Wrapper<ApplicationGatewayBackendAddressPoolInner>,ChildResource<ApplicationGateway>,HasBackendNics
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_backend_nics.backendNicIpConfigurationNames()
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  - com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.name()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.parent()
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
- uid: com.microsoft.azure.management.network._application_gateway_backend.addresses()
  id: addresses()
  parent: com.microsoft.azure.management.network._application_gateway_backend
  href: com.microsoft.azure.management.network._application_gateway_backend.yml
  langs:
  - java
  name: addresses()
  fullName: List<ApplicationGatewayBackendAddress> com.microsoft.azure.management.network.ApplicationGatewayBackend.addresses()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackend.java
    startLine: 29
  package: com.microsoft.azure.management.network
  syntax:
    content: public List<ApplicationGatewayBackendAddress> addresses()
    return:
      type: 5618da2dcom.microsoft.azure.management.network._application_gateway_backend_addressa08ddfce
      description: <p>addresses on the backend of the application gateway, indexed by their FQDN </p>
references:
- uid: 5618da2dcom.microsoft.azure.management.network._application_gateway_backend_addressa08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.network._application_gateway_backend_address
    name: ApplicationGatewayBackendAddress
    fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
    href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.network.model._has_backend_nics.backendNicIpConfigurationNames()
  parent: com.microsoft.azure.management.network.model._has_backend_nics
  href: com.microsoft.azure.management.network.model._has_backend_nics.yml
  name: backendNicIpConfigurationNames()
  fullName: Map<String, String> com.microsoft.azure.management.network.model.HasBackendNics.backendNicIpConfigurationNames()
  type: Method
  syntax:
    content: public Map<String, String> backendNicIpConfigurationNames()
    return:
      type: 689c8cb5
      description: <p>a map of names of the IP configurations of network interfaces assigned to this backend, indexed by their NIC's resource id </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.name()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.yml
  name: name()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasName.name()
  type: Method
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.parent()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource<ParentT>.parent()
  type: Method
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the parent of this child object </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: setInner(T inner)
  fullName: void com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>.setInner(T inner)
  type: Method
  summary: >-
    <p>Set the wrapped inner model. (For internal use only)</p>

    <p></p>
  syntax:
    content: public void setInner(T inner)
    parameters:
    - id: inner
      type: 8ce1ecb9
      description: <p>the new inner model </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: Wrapper<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>
  type: Interface
  summary: >-
    <p>The wrapper around an inner object providing extended functionalities.</p>

    <p></p>
  syntax:
    content: public interface Wrapper<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the inner object. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: ChildResource<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource<ParentT>
  type: Interface
  summary: <p>Base interface used by child resources. </p>
  syntax:
    content: public interface ChildResource<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>parent interface </p>
- uid: com.microsoft.azure.management.network.model._has_backend_nics
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_backend_nics.yml
  name: HasBackendNics
  fullName: com.microsoft.azure.management.network.model.HasBackendNics
  type: Interface
  summary: <p>An interface representing a backend's ability to reference a list of associated network interfaces. </p>
  syntax:
    content: public interface HasBackendNics
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_impl
- uid: com.microsoft.azure.management.network._application_gateway_backend_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  name: ApplicationGatewayBackendAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
  type: Class
  summary: <p>Backend Address of application gateway. </p>
  syntax:
    content: public class ApplicationGatewayBackendAddress
