items:
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  id: _args_formatter_test
  parent: com.microsoft.applicationinsights.internal.agent
  children:
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.arrayTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.collectionAndTwoObjectsTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.collectionTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.mapOfCollectionsTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.mapTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.nullObjectAndObjectTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.nullObjectTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.oneObjectTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoNullsObjectTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoObjectsAndCollectionTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoObjectsAndMapTest()
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoObjectsTest()
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: ArgsFormatterTest
  fullName: com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public class ArgsFormatterTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.arrayTest()
  id: arrayTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: arrayTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.arrayTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void arrayTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.collectionAndTwoObjectsTest()
  id: collectionAndTwoObjectsTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: collectionAndTwoObjectsTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.collectionAndTwoObjectsTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 97
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void collectionAndTwoObjectsTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.collectionTest()
  id: collectionTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: collectionTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.collectionTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 140
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void collectionTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.mapOfCollectionsTest()
  id: mapOfCollectionsTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: mapOfCollectionsTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.mapOfCollectionsTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 123
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void mapOfCollectionsTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.mapTest()
  id: mapTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: mapTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.mapTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 151
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void mapTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.nullObjectAndObjectTest()
  id: nullObjectAndObjectTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: nullObjectAndObjectTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.nullObjectAndObjectTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void nullObjectAndObjectTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.nullObjectTest()
  id: nullObjectTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: nullObjectTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.nullObjectTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void nullObjectTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.oneObjectTest()
  id: oneObjectTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: oneObjectTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.oneObjectTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void oneObjectTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoNullsObjectTest()
  id: twoNullsObjectTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: twoNullsObjectTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.twoNullsObjectTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void twoNullsObjectTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoObjectsAndCollectionTest()
  id: twoObjectsAndCollectionTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: twoObjectsAndCollectionTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.twoObjectsAndCollectionTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 84
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void twoObjectsAndCollectionTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoObjectsAndMapTest()
  id: twoObjectsAndMapTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: twoObjectsAndMapTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.twoObjectsAndMapTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 110
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void twoObjectsAndMapTest()
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test.twoObjectsTest()
  id: twoObjectsTest()
  parent: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  langs:
  - java
  name: twoObjectsTest()
  fullName: void com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest.twoObjectsTest()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatterTest.java
    startLine: 65
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public void twoObjectsTest()
references: []
