items:
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  id: _severity_level
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._severity_level.Critical()
  - com.microsoft.applicationinsights.telemetry._severity_level.Error()
  - com.microsoft.applicationinsights.telemetry._severity_level.getValue()
  - com.microsoft.applicationinsights.telemetry._severity_level.Information()
  - com.microsoft.applicationinsights.telemetry._severity_level.SeverityLevel(int)
  - com.microsoft.applicationinsights.telemetry._severity_level.Verbose()
  - com.microsoft.applicationinsights.telemetry._severity_level.Warning()
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 26
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum SeverityLevel
  inheritance:
  - java.lang.Object
  - java.lang.Enum<SeverityLevel>
- uid: com.microsoft.applicationinsights.telemetry._severity_level.Critical()
  id: Critical()
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: Critical
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel.Critical
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 31
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Critical=(4)
- uid: com.microsoft.applicationinsights.telemetry._severity_level.Error()
  id: Error()
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: Error
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel.Error
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 30
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Error=(3)
- uid: com.microsoft.applicationinsights.telemetry._severity_level.getValue()
  id: getValue()
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: getValue()
  fullName: int com.microsoft.applicationinsights.telemetry.SeverityLevel.getValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 35
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public int getValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.telemetry._severity_level.Information()
  id: Information()
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: Information
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel.Information
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 28
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Information=(1)
- uid: com.microsoft.applicationinsights.telemetry._severity_level.SeverityLevel(int)
  id: SeverityLevel(int)
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: SeverityLevel(int id)
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel.SeverityLevel(int id)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 39
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public SeverityLevel(int id)
    parameters:
    - id: id
      type: f75371fa
- uid: com.microsoft.applicationinsights.telemetry._severity_level.Verbose()
  id: Verbose()
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: Verbose
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel.Verbose
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 27
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Verbose=(0)
- uid: com.microsoft.applicationinsights.telemetry._severity_level.Warning()
  id: Warning()
  parent: com.microsoft.applicationinsights.telemetry._severity_level
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  langs:
  - java
  name: Warning
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel.Warning
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/SeverityLevel.java
    startLine: 29
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Warning=(2)
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
