items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httad1b57df786ff4419244f24ec046c6ff
  id: _application_gateway_frontend_httad1b57df786ff4419244f24ec046c6ff
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_httad1b57df786ff4419244f24ec046c6ff.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.UpdateDefinitionStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.UpdateDefinitionStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 198
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of application gateway HTTP listener definition stages applicable as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinitionStages
references: []
