items:
- uid: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  id: _web_request_tracking_filter
  parent: com.microsoft.applicationinsights.web.internal
  children:
  - com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.destroy()
  - com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.doFilter(ServletRequest,ServletResponse,FilterChain)
  - com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.init(FilterConfig)
  - com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.WebRequestTrackingFilter()
  href: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.yml
  langs:
  - java
  name: WebRequestTrackingFilter
  fullName: com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
    startLine: 50
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class WebRequestTrackingFilter
  inheritance:
  - java.lang.Object
  - Filter
- uid: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.destroy()
  id: destroy()
  parent: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  href: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.yml
  langs:
  - java
  name: destroy()
  fullName: void com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.destroy()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
    startLine: 149
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Destroy the filter by releases resources. </p>
  syntax:
    content: public void destroy()
- uid: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.doFilter(ServletRequest,ServletResponse,FilterChain)
  id: doFilter(ServletRequest,ServletResponse,FilterChain)
  parent: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  href: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.yml
  langs:
  - java
  name: doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
  fullName: void com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
    startLine: 73
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Processing the given request and response. </p>
  syntax:
    content: public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The servlet request. </p>
    - id: res
      type: 0dcfeead
      description: <p>The servlet response. </p>
    - id: chain
      type: 64bdd24a
      description: <p>The filters chain </p>
  exceptions:
  - type: cbf33bbe
    description: <p>Exception that can be thrown from invoking the filters chain. </p>
  - type: 30d455ad
    description: <p>Exception that can be thrown from invoking the filters chain. </p>
- uid: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.init(FilterConfig)
  id: init(FilterConfig)
  parent: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  href: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.yml
  langs:
  - java
  name: init(FilterConfig config)
  fullName: void com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.init(FilterConfig config)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
    startLine: 122
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Initializes the filter from the given config. </p>
  syntax:
    content: public void init(FilterConfig config)
    parameters:
    - id: config
      type: 46ef9a45
      description: <p>The filter configuration. </p>
- uid: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.WebRequestTrackingFilter()
  id: WebRequestTrackingFilter()
  parent: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  href: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.yml
  langs:
  - java
  name: WebRequestTrackingFilter()
  fullName: com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.WebRequestTrackingFilter()
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
    startLine: 205
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public WebRequestTrackingFilter()
references:
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: 30d455ad
  spec.java:
  - name: ServletException
    fullName: ServletException
- uid: b0deafe7
  spec.java:
  - name: ServletRequest
    fullName: ServletRequest
- uid: 0dcfeead
  spec.java:
  - name: ServletResponse
    fullName: ServletResponse
- uid: 64bdd24a
  spec.java:
  - name: FilterChain
    fullName: FilterChain
- uid: 46ef9a45
  spec.java:
  - name: FilterConfig
    fullName: FilterConfig
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  name: WebModulesContainer
  fullName: com.microsoft.applicationinsights.web.internal.WebModulesContainer
  type: Class
  summary: <p>Created by yonisha on 2/3/2015. </p>
  syntax:
    content: public class WebModulesContainer
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
- uid: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._thread_local_cleaner.yml
  name: ThreadLocalCleaner
  fullName: com.microsoft.applicationinsights.internal.util.ThreadLocalCleaner
  type: Interface
  summary: <p>Created by gupele on 7/8/2015. </p>
  syntax:
    content: public interface ThreadLocalCleaner
