items:
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  id: _mock_telemetry_module
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._mock_telemetry_module.getParam1()
  - com.microsoft.applicationinsights.internal.config._mock_telemetry_module.initialize(TelemetryConfiguration)
  - com.microsoft.applicationinsights.internal.config._mock_telemetry_module.MockTelemetryModule()
  - com.microsoft.applicationinsights.internal.config._mock_telemetry_module.MockTelemetryModule(Map<String, String>)
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  langs:
  - java
  name: MockTelemetryModule
  fullName: com.microsoft.applicationinsights.internal.config.MockTelemetryModule
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/config/MockTelemetryModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/MockTelemetryModule.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class MockTelemetryModule implements TelemetryModule
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_module
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.getParam1()
  id: getParam1()
  parent: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  langs:
  - java
  name: getParam1()
  fullName: String com.microsoft.applicationinsights.internal.config.MockTelemetryModule.getParam1()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/MockTelemetryModule.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getParam1()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.initialize(TelemetryConfiguration)
  id: initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  langs:
  - java
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.config.MockTelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/MockTelemetryModule.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Initializes the telemetry module.</p>

    <p></p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.MockTelemetryModule()
  id: MockTelemetryModule()
  parent: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  langs:
  - java
  name: MockTelemetryModule()
  fullName: com.microsoft.applicationinsights.internal.config.MockTelemetryModule.MockTelemetryModule()
  type: Constructor
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/MockTelemetryModule.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public MockTelemetryModule()
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.MockTelemetryModule(Map<String, String>)
  id: MockTelemetryModule(Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  langs:
  - java
  name: MockTelemetryModule(Map<String, String> argumentsMap)
  fullName: com.microsoft.applicationinsights.internal.config.MockTelemetryModule.MockTelemetryModule(Map<String, String> argumentsMap)
  type: Constructor
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/MockTelemetryModule.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public MockTelemetryModule(Map<String, String> argumentsMap)
    parameters:
    - id: argumentsMap
      type: 689c8cb5
references:
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: TelemetryModule
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface TelemetryModule
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_module
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>Initializes the telemetry module. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
