items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  id: _jmx_connector_m_x_bean
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.getQueryPlanThresholdInMS()
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.getRedisThresholdInMS()
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.setQueryPlanThresholdInMS(long)
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.setRedisThresholdInMS(long)
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  langs:
  - java
  name: JmxConnectorMXBean
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean
  type: Interface
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorMXBean.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorMXBean.java
    startLine: 26
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public interface JmxConnectorMXBean
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.getQueryPlanThresholdInMS()
  id: getQueryPlanThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  langs:
  - java
  name: getQueryPlanThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean.getQueryPlanThresholdInMS()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorMXBean.java
    startLine: 27
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  syntax:
    content: public long getQueryPlanThresholdInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.getRedisThresholdInMS()
  id: getRedisThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  langs:
  - java
  name: getRedisThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean.getRedisThresholdInMS()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorMXBean.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  syntax:
    content: public long getRedisThresholdInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.setQueryPlanThresholdInMS(long)
  id: setQueryPlanThresholdInMS(long)
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  langs:
  - java
  name: setQueryPlanThresholdInMS(long thresholdInMS)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean.setQueryPlanThresholdInMS(long thresholdInMS)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorMXBean.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  syntax:
    content: public void setQueryPlanThresholdInMS(long thresholdInMS)
    parameters:
    - id: thresholdInMS
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.setRedisThresholdInMS(long)
  id: setRedisThresholdInMS(long)
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  langs:
  - java
  name: setRedisThresholdInMS(long thresholdInMS)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean.setRedisThresholdInMS(long thresholdInMS)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorMXBean.java
    startLine: 33
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  syntax:
    content: public void setRedisThresholdInMS(long thresholdInMS)
    parameters:
    - id: thresholdInMS
      type: 0364520f
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.yml
  name: JmxConnectorMXBeanImpl
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBeanImpl
  type: Class
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JmxConnectorMXBeanImpl
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.getQueryPlanThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.yml
  name: getQueryPlanThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBeanImpl.getQueryPlanThresholdInMS()
  type: Method
  syntax:
    content: public long getQueryPlanThresholdInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.setQueryPlanThresholdInMS(long)
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.yml
  name: setQueryPlanThresholdInMS(long thresholdInMS)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBeanImpl.setQueryPlanThresholdInMS(long thresholdInMS)
  type: Method
  syntax:
    content: public void setQueryPlanThresholdInMS(long thresholdInMS)
    parameters:
    - id: thresholdInMS
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.getRedisThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.yml
  name: getRedisThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBeanImpl.getRedisThresholdInMS()
  type: Method
  syntax:
    content: public long getRedisThresholdInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.setRedisThresholdInMS(long)
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.yml
  name: setRedisThresholdInMS(long thresholdInMS)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBeanImpl.setRedisThresholdInMS(long thresholdInMS)
  type: Method
  syntax:
    content: public void setRedisThresholdInMS(long thresholdInMS)
    parameters:
    - id: thresholdInMS
      type: 0364520f
