items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  id: _docker_context_initializer_tests
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.classInit()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testDockerContextNotAccessedIfPollerNotCompleted()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testIfSDKInfoFileWrittenOnlyOnce()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testInit()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testInitializerNotThrowWhenContextIsNull()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testSDKInfoFileIsWrittenWithInstrumentationKey()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testTelemetryInitializedWhenContextAvailable()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testTelemetryPropertiesNotInitializedWhenAlreadyPopulated()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testWhenTelemetryPropertiesAlreadyPopulatedDeviceIdStillSet()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testWritingOfSdkInfoFileIsSynchonizedAndWrittenOnlyOnce()
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: DockerContextInitializerTests
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 43
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextInitializerTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.classInit()
  id: classInit()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: classInit()
  fullName: static void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.classInit()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 57
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public static void classInit()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testDockerContextNotAccessedIfPollerNotCompleted()
  id: testDockerContextNotAccessedIfPollerNotCompleted()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testDockerContextNotAccessedIfPollerNotCompleted()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testDockerContextNotAccessedIfPollerNotCompleted()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 113
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testDockerContextNotAccessedIfPollerNotCompleted()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testIfSDKInfoFileWrittenOnlyOnce()
  id: testIfSDKInfoFileWrittenOnlyOnce()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testIfSDKInfoFileWrittenOnlyOnce()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testIfSDKInfoFileWrittenOnlyOnce()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 136
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testIfSDKInfoFileWrittenOnlyOnce()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testInit()
  id: testInit()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testInit()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testInit()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 64
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testInit()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testInitializerNotThrowWhenContextIsNull()
  id: testInitializerNotThrowWhenContextIsNull()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testInitializerNotThrowWhenContextIsNull()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testInitializerNotThrowWhenContextIsNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 102
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testInitializerNotThrowWhenContextIsNull()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testSDKInfoFileIsWrittenWithInstrumentationKey()
  id: testSDKInfoFileIsWrittenWithInstrumentationKey()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testSDKInfoFileIsWrittenWithInstrumentationKey()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testSDKInfoFileIsWrittenWithInstrumentationKey()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 122
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testSDKInfoFileIsWrittenWithInstrumentationKey()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testTelemetryInitializedWhenContextAvailable()
  id: testTelemetryInitializedWhenContextAvailable()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testTelemetryInitializedWhenContextAvailable()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testTelemetryInitializedWhenContextAvailable()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 72
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testTelemetryInitializedWhenContextAvailable()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testTelemetryPropertiesNotInitializedWhenAlreadyPopulated()
  id: testTelemetryPropertiesNotInitializedWhenAlreadyPopulated()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testTelemetryPropertiesNotInitializedWhenAlreadyPopulated()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testTelemetryPropertiesNotInitializedWhenAlreadyPopulated()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 83
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testTelemetryPropertiesNotInitializedWhenAlreadyPopulated()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testWhenTelemetryPropertiesAlreadyPopulatedDeviceIdStillSet()
  id: testWhenTelemetryPropertiesAlreadyPopulatedDeviceIdStillSet()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testWhenTelemetryPropertiesAlreadyPopulatedDeviceIdStillSet()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testWhenTelemetryPropertiesAlreadyPopulatedDeviceIdStillSet()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 92
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testWhenTelemetryPropertiesAlreadyPopulatedDeviceIdStillSet()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.testWritingOfSdkInfoFileIsSynchonizedAndWrittenOnlyOnce()
  id: testWritingOfSdkInfoFileIsSynchonizedAndWrittenOnlyOnce()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  langs:
  - java
  name: testWritingOfSdkInfoFileIsSynchonizedAndWrittenOnlyOnce()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testWritingOfSdkInfoFileIsSynchonizedAndWrittenOnlyOnce()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
    startLine: 149
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public void testWritingOfSdkInfoFileIsSynchonizedAndWrittenOnlyOnce()
references:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.yml
  name: DockerContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>This initializer is required for Docker awareness. The initializer has two goals: 1) Identify Docker context file injected by Application Insight for Docker container and initialize telemetries with Docker context. 2) Write SDK context file which enables the Application Insights for Docker container to discover containers with integrated SDK, and stop sending performance counters in that case (SDK provides OOB performance counters). </p>
  syntax:
    content: public class DockerContextInitializer implements TelemetryInitializer
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  name: DockerContextPoller
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPoller
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.yml
  name: FileFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.FileFactory
  type: Class
  summary: <p>Created by yonisha on 8/3/2015. </p>
  syntax:
    content: public class FileFactory
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  name: DockerContext
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>Represents the Docker context, which includes the host name, image name, container name and container ID. The Docker context file is written in the following structure: Docker host=host_name,Docker image=image_name,Docker container id=con_id,Docker container name=con_name </p>
  syntax:
    content: public class DockerContext
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
