items:
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  id: _implem5c143b42abb037284b18876ba8b7170a
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl
  children:
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.classLoader()
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.handler()
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.key()
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.RegistrationData(ClassLoader,AgentNotificationsHandler,String)
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.yml
  langs:
  - java
  name: ImplementationsCoordinator.RegistrationData
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.RegistrationData
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
    startLine: 69
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  summary: <p>The data we expect to have for every thread </p>
  syntax:
    content: public class RegistrationData
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.classLoader()
  id: classLoader()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.yml
  langs:
  - java
  name: classLoader
  fullName: final ClassLoader com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.RegistrationData.classLoader
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
    startLine: 70
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  syntax:
    content: public final ClassLoader classLoader
    return:
      type: 1ae7550b
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.handler()
  id: handler()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.yml
  langs:
  - java
  name: handler
  fullName: final AgentNotificationsHandler com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.RegistrationData.handler
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
    startLine: 71
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  syntax:
    content: public final AgentNotificationsHandler handler
    return:
      type: 93de0ef9com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.key()
  id: key()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.yml
  langs:
  - java
  name: key
  fullName: final String com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.RegistrationData.key
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
    startLine: 72
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  syntax:
    content: public final String key
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.RegistrationData(ClassLoader,AgentNotificationsHandler,String)
  id: RegistrationData(ClassLoader,AgentNotificationsHandler,String)
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.yml
  langs:
  - java
  name: RegistrationData(ClassLoader classLoader, AgentNotificationsHandler handler, String key)
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.RegistrationData.RegistrationData(ClassLoader classLoader, AgentNotificationsHandler handler, String key)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
    startLine: 74
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  syntax:
    content: public RegistrationData(ClassLoader classLoader, AgentNotificationsHandler handler, String key)
    parameters:
    - id: classLoader
      type: 5d46207c
    - id: handler
      type: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
    - id: key
      type: "26831127"
references:
- uid: 1ae7550b
  spec.java:
  - name: final ClassLoader
    fullName: final ClassLoader
- uid: 93de0ef9com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
    name: AgentNotificationsHandler
    fullName: com.microsoft.applicationinsights.agent.internal.coresync.AgentNotificationsHandler
    href: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler.yml
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: 5d46207c
  spec.java:
  - name: ClassLoader
    fullName: ClassLoader
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
  parent: com.microsoft.applicationinsights.agent.internal.coresync
  href: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler.yml
  name: AgentNotificationsHandler
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.AgentNotificationsHandler
  type: Interface
  summary: >-
    <p>The Agent will inject code in the user's code that will be activated on predefined methods. Those methods will be directed to the Agent that will need to work with that information by delegating the calls to 'clients', those clients will need to implement the following interface.</p>

    <p>Created by gupele on 5/6/2015. </p>
  syntax:
    content: public interface AgentNotificationsHandler
