items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  id: _docker_context_poller
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.DockerContextPoller(File,DockerContextFactory)
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.DockerContextPoller(String)
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.getDockerContext()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.isCompleted()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.run()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.THREAD_POLLING_INTERVAL_MS()
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: DockerContextPoller
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 29
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPoller
  inheritance:
  - java.lang.Object
  - Thread
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.DockerContextPoller(File,DockerContextFactory)
  id: DockerContextPoller(File,DockerContextFactory)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: DockerContextPoller(File contextFile, DockerContextFactory dockerContextFactory)
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller.DockerContextPoller(File contextFile, DockerContextFactory dockerContextFactory)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 36
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: protected DockerContextPoller(File contextFile, DockerContextFactory dockerContextFactory)
    parameters:
    - id: contextFile
      type: 8291270b
    - id: dockerContextFactory
      type: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.DockerContextPoller(String)
  id: DockerContextPoller(String)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: DockerContextPoller(String contextFileDirectory)
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller.DockerContextPoller(String contextFileDirectory)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 41
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public DockerContextPoller(String contextFileDirectory)
    parameters:
    - id: contextFileDirectory
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.getDockerContext()
  id: getDockerContext()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: getDockerContext()
  fullName: DockerContext com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller.getDockerContext()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 80
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public DockerContext getDockerContext()
    return:
      type: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.isCompleted()
  id: isCompleted()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: isCompleted()
  fullName: boolean com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller.isCompleted()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 76
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public boolean isCompleted()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.run()
  id: run()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: run()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller.run()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 48
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public void run()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.THREAD_POLLING_INTERVAL_MS()
  id: THREAD_POLLING_INTERVAL_MS()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  langs:
  - java
  name: THREAD_POLLING_INTERVAL_MS
  fullName: int com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller.THREAD_POLLING_INTERVAL_MS
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
    startLine: 34
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: protected int THREAD_POLLING_INTERVAL_MS= 2 * 1000
    return:
      type: f75371fa
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 8291270b
  spec.java:
  - name: File
    fullName: File
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.yml
  name: DockerContextFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextFactory
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextFactory
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  name: DockerContext
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>Represents the Docker context, which includes the host name, image name, container name and container ID. The Docker context file is written in the following structure: Docker host=host_name,Docker image=image_name,Docker container id=con_id,Docker container name=con_name </p>
  syntax:
    content: public class DockerContext
