items:
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  id: _request_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  children:
  - com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testDuration()
  - com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testErrorCodes()
  - com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testNoRequestTelemetry()
  - com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testNullTelemetry()
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.yml
  langs:
  - java
  name: RequestTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilterTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilterTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilterTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.processor
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class RequestTelemetryFilterTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testDuration()
  id: testDuration()
  parent: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.yml
  langs:
  - java
  name: testDuration()
  fullName: void com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilterTest.testDuration()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilterTest.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testDuration()
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testErrorCodes()
  id: testErrorCodes()
  parent: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.yml
  langs:
  - java
  name: testErrorCodes()
  fullName: void com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilterTest.testErrorCodes()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilterTest.java
    startLine: 78
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testErrorCodes()
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testNoRequestTelemetry()
  id: testNoRequestTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.yml
  langs:
  - java
  name: testNoRequestTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilterTest.testNoRequestTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilterTest.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNoRequestTelemetry()
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.testNullTelemetry()
  id: testNullTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.yml
  langs:
  - java
  name: testNullTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilterTest.testNullTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilterTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNullTelemetry()
references: []
