items:
- uid: com.microsoft.applicationinsights.internal.agent
  id: agent
  children:
  - com.microsoft.applicationinsights.internal.agent._agent_connector
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  - com.microsoft.applicationinsights.internal.agent._agent_self_connector
  - com.microsoft.applicationinsights.internal.agent._args_formatter_test
  href: com.microsoft.applicationinsights.internal.agent.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.agent
  fullName: com.microsoft.applicationinsights.internal.agent
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 21
  syntax:
    content: namespace agent
references:
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector
  parent: com.microsoft.applicationinsights.internal.agent
  href: com.microsoft.applicationinsights.internal.agent._agent_connector.yml
  name: AgentConnector
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector
  type: Enum
  summary: >-
    <p>The class is responsible for connecting the Agent and register there for future calls</p>

    <p>Created by gupele on 5/7/2015. </p>
  syntax:
    content: public enum AgentConnector
- uid: com.microsoft.applicationinsights.internal.agent._agent_self_connector
  parent: com.microsoft.applicationinsights.internal.agent
  href: com.microsoft.applicationinsights.internal.agent._agent_self_connector.yml
  name: AgentSelfConnector
  fullName: com.microsoft.applicationinsights.internal.agent.AgentSelfConnector
  type: Class
  summary: >-
    <p>A utility class to load the core SDK into the Agent This is an internal class that should only used by the Agent</p>

    <p>Created by gupele on 9/11/2016. </p>
  syntax:
    content: public class AgentSelfConnector
- uid: com.microsoft.applicationinsights.internal.agent._args_formatter_test
  parent: com.microsoft.applicationinsights.internal.agent
  href: com.microsoft.applicationinsights.internal.agent._args_formatter_test.yml
  name: ArgsFormatterTest
  fullName: com.microsoft.applicationinsights.internal.agent.ArgsFormatterTest
  type: Class
  syntax:
    content: public class ArgsFormatterTest
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result
  parent: com.microsoft.applicationinsights.internal.agent
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.yml
  name: AgentConnector.RegistrationResult
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationResult
  type: Class
  syntax:
    content: public class RegistrationResult
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  parent: com.microsoft.applicationinsights.internal.agent
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.yml
  name: AgentConnector.RegistrationType
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationType
  type: Enum
  syntax:
    content: public enum RegistrationType
