items:
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test
  id: _git_build_info_context_initializer_test
  parent: com.microsoft.applicationinsights.sample.plugins
  children:
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test.loadSourcePropertiesTest()
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test.yml
  langs:
  - java
  name: GitBuildInfoContextInitializerTest
  fullName: com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializerTest
  type: Class
  source:
    remote: &o0
      path: samples/src/test/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializerTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/test/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializerTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.sample.plugins
  syntax:
    content: public class GitBuildInfoContextInitializerTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test.loadSourcePropertiesTest()
  id: loadSourcePropertiesTest()
  parent: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test.yml
  langs:
  - java
  name: loadSourcePropertiesTest()
  fullName: void com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializerTest.loadSourcePropertiesTest()
  type: Method
  source:
    remote: *o0
    path: samples/src/test/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializerTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.sample.plugins
  syntax:
    content: public void loadSourcePropertiesTest()
references:
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry_context.yml
  name: TelemetryContext
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContext
  type: Class
  summary: <p>Represents a context for sending telemetry to the Application Insights service. </p>
  syntax:
    content: public class TelemetryContext
