items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  id: _byte_code_transformer
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.transform(byte[])
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.yml
  langs:
  - java
  name: ByteCodeTransformer
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ByteCodeTransformer
  type: Interface
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeTransformer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeTransformer.java
    startLine: 26
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public interface ByteCodeTransformer
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.transform(byte[])
  id: transform(byte[])
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.yml
  langs:
  - java
  name: transform(byte[] originalBuffer)
  fullName: byte [] com.microsoft.applicationinsights.agent.internal.agent.ByteCodeTransformer.transform(byte[] originalBuffer)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeTransformer.java
    startLine: 27
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public byte[] transform(byte[] originalBuffer)
    parameters:
    - id: originalBuffer
      type: bc819c2f
    return:
      type: bc819c2f
references:
- uid: bc819c2f
  spec.java:
  - name: byte[]
    fullName: byte[]
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_byte_code_transformer
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.yml
  name: PreparedStatementByteCodeTransformer
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementByteCodeTransformer
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementByteCodeTransformer
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.transform(byte[])
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.yml
  name: transform(byte[] originalBuffer)
  fullName: byte [] com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementByteCodeTransformer.transform(byte[] originalBuffer)
  type: Method
  syntax:
    content: public byte[] transform(byte[] originalBuffer)
    parameters:
    - id: originalBuffer
      type: bc819c2f
    return:
      type: bc819c2f
