items:
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe
  id: _runtimaa439f2788e6087ab312a283f4b80dbe
  children:
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.createNonValidResult()
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.createValidResult(int)
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.stackSize()
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.valid()
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.coresync.impl.RuntimeExceptionDecider.ValidationResult
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.RuntimeExceptionDecider.ValidationResult
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/RuntimeExceptionDecider.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/RuntimeExceptionDecider.java
    startLine: 34
  syntax:
    content: public class ValidationResult
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.createNonValidResult()
  id: createNonValidResult()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.yml
  langs:
  - java
  name: createNonValidResult()
  fullName: static ValidationResult com.microsoft.applicationinsights.agent.internal.coresync.impl.RuntimeExceptionDecider.ValidationResult.createNonValidResult()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/RuntimeExceptionDecider.java
    startLine: 42
  syntax:
    content: public static ValidationResult createNonValidResult()
    return:
      type: 4ef0c618
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.createValidResult(int)
  id: createValidResult(int)
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.yml
  langs:
  - java
  name: createValidResult(int stackSize)
  fullName: static ValidationResult com.microsoft.applicationinsights.agent.internal.coresync.impl.RuntimeExceptionDecider.ValidationResult.createValidResult(int stackSize)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/RuntimeExceptionDecider.java
    startLine: 38
  syntax:
    content: public static ValidationResult createValidResult(int stackSize)
    parameters:
    - id: stackSize
      type: f75371fa
    return:
      type: 4ef0c618
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.stackSize()
  id: stackSize()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.yml
  langs:
  - java
  name: stackSize
  fullName: final int com.microsoft.applicationinsights.agent.internal.coresync.impl.RuntimeExceptionDecider.ValidationResult.stackSize
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/RuntimeExceptionDecider.java
    startLine: 36
  syntax:
    content: public final int stackSize
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.valid()
  id: valid()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._runtimaa439f2788e6087ab312a283f4b80dbe.yml
  langs:
  - java
  name: valid
  fullName: final boolean com.microsoft.applicationinsights.agent.internal.coresync.impl.RuntimeExceptionDecider.ValidationResult.valid
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/RuntimeExceptionDecider.java
    startLine: 35
  syntax:
    content: public final boolean valid
    return:
      type: 4dda0764
references:
- uid: 4dda0764
  spec.java:
  - name: final boolean
    fullName: final boolean
- uid: cd225469
  spec.java:
  - name: final int
    fullName: final int
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 4ef0c618
  spec.java:
  - name: ValidationResult
    fullName: ValidationResult
