items:
- uid: com.microsoft.applicationinsights.channel
  id: channel
  children:
  - com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.channel
  fullName: com.microsoft.applicationinsights.channel
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java
    startLine: 21
  syntax:
    content: package com.microsoft.applicationinsights.channel
references:
- uid: com.microsoft.applicationinsights.channel._telemetry_channel
  parent: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: TelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.TelemetryChannel
  type: Interface
  summary: <p>Represents a communication channel for sending telemetry to application insights. </p>
  syntax:
    content: public interface TelemetryChannel
