items:
- uid: com.microsoft.applicationinsights.internal.config._configuration_file_locator
  id: _configuration_file_locator
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._configuration_file_locator.ConfigurationFileLocator(String)
  - com.microsoft.applicationinsights.internal.config._configuration_file_locator.getConfigurationFile()
  href: com.microsoft.applicationinsights.internal.config._configuration_file_locator.yml
  langs:
  - java
  name: ConfigurationFileLocator
  fullName: com.microsoft.applicationinsights.internal.config.ConfigurationFileLocator
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 5/25/2015. </p>
  syntax:
    content: public class ConfigurationFileLocator
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._configuration_file_locator.ConfigurationFileLocator(String)
  id: ConfigurationFileLocator(String)
  parent: com.microsoft.applicationinsights.internal.config._configuration_file_locator
  href: com.microsoft.applicationinsights.internal.config._configuration_file_locator.yml
  langs:
  - java
  name: ConfigurationFileLocator(String configurationFileName)
  fullName: com.microsoft.applicationinsights.internal.config.ConfigurationFileLocator.ConfigurationFileLocator(String configurationFileName)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ConfigurationFileLocator(String configurationFileName)
    parameters:
    - id: configurationFileName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._configuration_file_locator.getConfigurationFile()
  id: getConfigurationFile()
  parent: com.microsoft.applicationinsights.internal.config._configuration_file_locator
  href: com.microsoft.applicationinsights.internal.config._configuration_file_locator.yml
  langs:
  - java
  name: getConfigurationFile()
  fullName: InputStream com.microsoft.applicationinsights.internal.config.ConfigurationFileLocator.getConfigurationFile()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public InputStream getConfigurationFile()
    return:
      type: 76fcb9b7
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 76fcb9b7
  spec.java:
  - name: InputStream
    fullName: InputStream
