items:
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  id: _active_transmission_loader
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.ActiveTransmissionLoader(final TransmissionFileSystemOutput,final TransmissionDispatcher,final TransmissionPolicyStateFetcher,int)
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.ActiveTransmissionLoader(TransmissionFileSystemOutput,TransmissionPolicyStateFetcher,TransmissionDispatcher)
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.load(boolean)
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.MAX_THREADS_ALLOWED()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  langs:
  - java
  name: ActiveTransmissionLoader
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The class is responsible for loading transmission files that were saved to the disk</p>

    <p>The class will ask for the oldest transmission file and will hand it to the dispatcher</p>

    <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public class ActiveTransmissionLoader implements TransmissionsLoader
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.shutdown._stoppable
  - com.microsoft.applicationinsights.internal.channel._transmissions_loader
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.ActiveTransmissionLoader(final TransmissionFileSystemOutput,final TransmissionDispatcher,final TransmissionPolicyStateFetcher,int)
  id: ActiveTransmissionLoader(final TransmissionFileSystemOutput,final TransmissionDispatcher,final TransmissionPolicyStateFetcher,int)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  langs:
  - java
  name: ActiveTransmissionLoader(final TransmissionFileSystemOutput fileSystem, final TransmissionDispatcher dispatcher, final TransmissionPolicyStateFetcher transmissionPolicy, int numberOfThreads)
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.ActiveTransmissionLoader(final TransmissionFileSystemOutput fileSystem, final TransmissionDispatcher dispatcher, final TransmissionPolicyStateFetcher transmissionPolicy, int numberOfThreads)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
    startLine: 72
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public ActiveTransmissionLoader(final TransmissionFileSystemOutput fileSystem, final TransmissionDispatcher dispatcher, final TransmissionPolicyStateFetcher transmissionPolicy, int numberOfThreads)
    parameters:
    - id: fileSystem
      type: 93de0ef9com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
    - id: dispatcher
      type: 93de0ef9com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
    - id: transmissionPolicy
      type: 93de0ef9com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
    - id: numberOfThreads
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.ActiveTransmissionLoader(TransmissionFileSystemOutput,TransmissionPolicyStateFetcher,TransmissionDispatcher)
  id: ActiveTransmissionLoader(TransmissionFileSystemOutput,TransmissionPolicyStateFetcher,TransmissionDispatcher)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  langs:
  - java
  name: ActiveTransmissionLoader(TransmissionFileSystemOutput fileSystem, TransmissionPolicyStateFetcher transmissionPolicy, TransmissionDispatcher dispatcher)
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.ActiveTransmissionLoader(TransmissionFileSystemOutput fileSystem, TransmissionPolicyStateFetcher transmissionPolicy, TransmissionDispatcher dispatcher)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public ActiveTransmissionLoader(TransmissionFileSystemOutput fileSystem, TransmissionPolicyStateFetcher transmissionPolicy, TransmissionDispatcher dispatcher)
    parameters:
    - id: fileSystem
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
    - id: transmissionPolicy
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
    - id: dispatcher
      type: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.load(boolean)
  id: load(boolean)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  langs:
  - java
  name: load(boolean waitForThreadsToStart)
  fullName: synchronized boolean com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.load(boolean waitForThreadsToStart)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
    startLine: 137
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public synchronized boolean load(boolean waitForThreadsToStart)
    parameters:
    - id: waitForThreadsToStart
      type: 4fc6e284
    return:
      type: 85b427c6
  overridden: com.microsoft.applicationinsights.internal.channel._transmissions_loader.load(boolean)
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.MAX_THREADS_ALLOWED()
  id: MAX_THREADS_ALLOWED()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  langs:
  - java
  name: MAX_THREADS_ALLOWED
  fullName: final int com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.MAX_THREADS_ALLOWED
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public static final int MAX_THREADS_ALLOWED= 10
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
    startLine: 161
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
  overridden: com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
references:
- uid: cd225469
  spec.java:
  - name: final int
    fullName: final int
- uid: 93de0ef9com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
    name: TransmissionFileSystemOutput
    fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput
    href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
- uid: 93de0ef9com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
    name: TransmissionDispatcher
    fullName: com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher
    href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
- uid: 93de0ef9com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
    name: TransmissionPolicyStateFetcher
    fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher
    href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 85b427c6
  spec.java:
  - name: synchronized boolean
    fullName: synchronized boolean
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.internal.channel._transmissions_loader
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmissions_loader.yml
  name: TransmissionsLoader
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionsLoader
  type: Interface
  summary: <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public interface TransmissionsLoader
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  name: TransmissionFileSystemOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput
  type: Class
  summary: >-
    <p>The class knows how to manage <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> that needs to be saved to the file system.</p>

    <p>The class works on a pre-defined folder and should know the size of disk it can use.</p>

    <p>With that data it knows how to store incoming Transmissions and store them into files that can be later be read back into Transmissions.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class TransmissionFileSystemOutput
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  name: TransmissionDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher
  type: Interface
  summary: >-
    <p>A dispatcher should know how and to whom to dispatch a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionDispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
  name: TransmissionPolicyStateFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher
  type: Interface
  summary: <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public interface TransmissionPolicyStateFetcher
- uid: com.microsoft.applicationinsights.internal.channel._transmissions_loader.load(boolean)
  parent: com.microsoft.applicationinsights.internal.channel._transmissions_loader
  href: com.microsoft.applicationinsights.internal.channel._transmissions_loader.yml
  name: load(boolean waitForThreadsToStart)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TransmissionsLoader.load(boolean waitForThreadsToStart)
  type: Method
  syntax:
    content: public boolean load(boolean waitForThreadsToStart)
    parameters:
    - id: waitForThreadsToStart
      type: 4fc6e284
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.shutdown._stoppable
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.shutdown.Stoppable.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
