items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  id: _exception_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.byteCodeForMethodExit(int)
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.ExceptionMethodVisitor(boolean,int,String,String,String,MethodVisitor)
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.onMethodExit(int)
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.yml
  langs:
  - java
  name: ExceptionMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.ExceptionMethodVisitor
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
    startLine: 32
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  summary: <p>Created by gupele on 8/1/2016. </p>
  syntax:
    content: public class ExceptionMethodVisitor extends AdvancedAdviceAdapter
  inheritance:
  - java.lang.Object
  - AdviceAdapter
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  inheritedMembers:
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.activateEnumMethod(Class<?>,String,String,Object...)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.AdvancedAdviceAdapter(boolean,int,MethodVisitor,int,String,String,String)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTop(Type)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTopStackToTempVariable(Type)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getMethodName()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getReturnType()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.reportExecutionTime()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.translateExitCode(int)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitCode()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitMaxs(int,int)
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.byteCodeForMethodExit(int)
  id: byteCodeForMethodExit(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.yml
  langs:
  - java
  name: byteCodeForMethodExit(int opcode)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.exceptions.ExceptionMethodVisitor.byteCodeForMethodExit(int opcode)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
    startLine: 55
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  syntax:
    content: protected void byteCodeForMethodExit(int opcode)
    parameters:
    - id: opcode
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.ExceptionMethodVisitor(boolean,int,String,String,String,MethodVisitor)
  id: ExceptionMethodVisitor(boolean,int,String,String,String,MethodVisitor)
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.yml
  langs:
  - java
  name: ExceptionMethodVisitor(boolean reportExecutionTime, int access, String desc, String owner, String methodName, MethodVisitor methodVisitor)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.ExceptionMethodVisitor.ExceptionMethodVisitor(boolean reportExecutionTime, int access, String desc, String owner, String methodName, MethodVisitor methodVisitor)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
    startLine: 36
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  syntax:
    content: protected ExceptionMethodVisitor(boolean reportExecutionTime, int access, String desc, String owner, String methodName, MethodVisitor methodVisitor)
    parameters:
    - id: reportExecutionTime
      type: 4fc6e284
    - id: access
      type: f75371fa
    - id: desc
      type: "26831127"
    - id: owner
      type: "26831127"
    - id: methodName
      type: "26831127"
    - id: methodVisitor
      type: dd525b3c
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.onMethodExit(int)
  id: onMethodExit(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.yml
  langs:
  - java
  name: onMethodExit(int opcode)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.exceptions.ExceptionMethodVisitor.onMethodExit(int opcode)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
    startLine: 47
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  syntax:
    content: protected void onMethodExit(int opcode)
    parameters:
    - id: opcode
      type: f75371fa
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: dd525b3c
  spec.java:
  - name: MethodVisitor
    fullName: MethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.activateEnumMethod(Class<?>,String,String,Object...)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: activateEnumMethod(Class<?> clazz, String methodName, String methodSignature, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.activateEnumMethod(Class<?> clazz, String methodName, String methodSignature, Object...args)
  type: Method
  summary: <p>This method calls a Java enum method with its expected argumentes </p>
  syntax:
    content: protected void activateEnumMethod(Class<?> clazz, String methodName, String methodSignature, Object...args)
    parameters:
    - id: clazz
      type: a19781f8
      description: <p>The enum class to activate </p>
    - id: methodName
      type: "26831127"
      description: <p>The method of the class to activate </p>
    - id: methodSignature
      type: "26831127"
      description: <p>The method signature </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments to pass to the method </p>
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.AdvancedAdviceAdapter(boolean,int,MethodVisitor,int,String,String,String)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: AdvancedAdviceAdapter(boolean reportExecutionTime, int api, MethodVisitor methodVisitor, int access, String owner, String methodName, String desc)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.AdvancedAdviceAdapter(boolean reportExecutionTime, int api, MethodVisitor methodVisitor, int access, String owner, String methodName, String desc)
  type: Constructor
  syntax:
    content: protected AdvancedAdviceAdapter(boolean reportExecutionTime, int api, MethodVisitor methodVisitor, int access, String owner, String methodName, String desc)
    parameters:
    - id: reportExecutionTime
      type: 4fc6e284
    - id: api
      type: f75371fa
    - id: methodVisitor
      type: dd525b3c
    - id: access
      type: f75371fa
    - id: owner
      type: "26831127"
    - id: methodName
      type: "26831127"
    - id: desc
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTop(Type)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: duplicateTop(Type type)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.duplicateTop(Type type)
  type: Method
  syntax:
    content: protected void duplicateTop(Type type)
    parameters:
    - id: type
      type: 7727faa1
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTopStackToTempVariable(Type)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: duplicateTopStackToTempVariable(Type typeOfTopElementInStack)
  fullName: TempVar com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.duplicateTopStackToTempVariable(Type typeOfTopElementInStack)
  type: Method
  syntax:
    content: protected TempVar duplicateTopStackToTempVariable(Type typeOfTopElementInStack)
    parameters:
    - id: typeOfTopElementInStack
      type: 7727faa1
    return:
      type: b543022f
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getMethodName()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: getMethodName()
  fullName: String com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.getMethodName()
  type: Method
  syntax:
    content: protected String getMethodName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getReturnType()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: getReturnType()
  fullName: Type com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.getReturnType()
  type: Method
  syntax:
    content: protected Type getReturnType()
    return:
      type: 7727faa1
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.reportExecutionTime()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: reportExecutionTime
  fullName: final boolean com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.reportExecutionTime
  type: Field
  syntax:
    content: protected final boolean reportExecutionTime
    return:
      type: 4dda0764
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.translateExitCode(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: translateExitCode(int opcode)
  fullName: ExitStatus com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.translateExitCode(int opcode)
  type: Method
  syntax:
    content: protected ExitStatus translateExitCode(int opcode)
    parameters:
    - id: opcode
      type: f75371fa
    return:
      type: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitCode()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: visitCode()
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.visitCode()
  type: Method
  syntax:
    content: public void visitCode()
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitMaxs(int,int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: visitMaxs(int maxStack, int maxLocals)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.visitMaxs(int maxStack, int maxLocals)
  type: Method
  syntax:
    content: public void visitMaxs(int maxStack, int maxLocals)
    parameters:
    - id: maxStack
      type: f75371fa
    - id: maxLocals
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: AdvancedAdviceAdapter
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter
  type: Class
  summary: >-
    <p>A base class that lets its derived classes to enjoy utilities like creating temporary variables, managing methods points, method names etc.</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class AdvancedAdviceAdapter
