items:
- uid: com.microsoft.applicationinsights.web.spring
  id: spring
  children:
  - com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter
  href: com.microsoft.applicationinsights.web.spring.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.spring
  fullName: com.microsoft.applicationinsights.web.spring
  type: Namespace
  source:
    remote:
      path: '[generated]'
    path: '[generated]'
  syntax:
    content: namespace spring
references:
- uid: com.microsoft.applicationinsights.web.spring.internal
  href: com.microsoft.applicationinsights.web.spring.internal.yml
  name: com.microsoft.applicationinsights.web.spring.internal
  fullName: com.microsoft.applicationinsights.web.spring.internal
  type: Namespace
  syntax:
    content: namespace internal
- uid: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter
  parent: com.microsoft.applicationinsights.web.spring
  href: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter.yml
  name: RequestNameHandlerInterceptorAdapter
  fullName: com.microsoft.applicationinsights.web.spring.RequestNameHandlerInterceptorAdapter
  type: Class
  summary: >-
    <p>Created by yonisha on 3/1/2015.</p>

    <p>This class intercepts all requests before forwarded to the relevant handler. It extracts the relevant controller and method names and updates the request telemetry name. This class should never throw exceptions to avoid blocking request processing. </p>
  syntax:
    content: public class RequestNameHandlerInterceptorAdapter
