items:
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory
  id: _agent_configuration_builder_factory
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.createBuilder(String)
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.createDefaultBuilder()
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.yml
  langs:
  - java
  name: AgentConfigurationBuilderFactory
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilderFactory
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilderFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilderFactory.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: >-
    <p>The factory is responsible for creating the correct <xref href="com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class AgentConfigurationBuilderFactory
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.createBuilder(String)
  id: createBuilder(String)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.yml
  langs:
  - java
  name: createBuilder(String builderClassName)
  fullName: AgentConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilderFactory.createBuilder(String builderClassName)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilderFactory.java
    startLine: 32
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentConfigurationBuilder createBuilder(String builderClassName)
    parameters:
    - id: builderClassName
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.createDefaultBuilder()
  id: createDefaultBuilder()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.yml
  langs:
  - java
  name: createDefaultBuilder()
  fullName: AgentConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilderFactory.createDefaultBuilder()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilderFactory.java
    startLine: 48
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentConfigurationBuilder createDefaultBuilder()
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder.yml
  name: AgentConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilder
  type: Interface
  summary: <p>Defines the interface for builders that know how to create <xref href="com.microsoft.applicationinsights.agent.internal.config._agent_configuration" data-throw-if-not-resolved="false"></xref> Created by gupele on 5/19/2015. </p>
  syntax:
    content: public interface AgentConfigurationBuilder
