items:
- uid: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner
  id: _annotation_package_scanner
  parent: com.microsoft.applicationinsights.internal.annotation
  children:
  - com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner.scanForClassAnnotations(final Class<?extends Annotation>[],String)
  href: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner.yml
  langs:
  - java
  name: AnnotationPackageScanner
  fullName: com.microsoft.applicationinsights.internal.annotation.AnnotationPackageScanner
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.annotation
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AnnotationPackageScanner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner.scanForClassAnnotations(final Class<?extends Annotation>[],String)
  id: scanForClassAnnotations(final Class<?extends Annotation>[],String)
  parent: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner
  href: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner.yml
  langs:
  - java
  name: scanForClassAnnotations(final Class<?extends Annotation>[] annotationsToSearch, String packageToScan)
  fullName: List<String> com.microsoft.applicationinsights.internal.annotation.AnnotationPackageScanner.scanForClassAnnotations(final Class<?extends Annotation>[] annotationsToSearch, String packageToScan)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.annotation
  summary: <p>The method will scan packages searching for classes that have the needed annotations. </p>
  syntax:
    content: public List<String> scanForClassAnnotations(final Class<?extends Annotation>[] annotationsToSearch, String packageToScan)
    parameters:
    - id: annotationsToSearch
      type: d0d16918
      description: <p>The annotations we need. </p>
    - id: packageToScan
      type: "26831127"
      description: <p>The packages to scan from, note that all sub packages will be scanned too. </p>
    return:
      type: 7d60c20e
      description: <p>A list of class names that are under the package we asked and that carry the needed annotations </p>
references:
- uid: d0d16918
  spec.java:
  - name: final Class<?extends Annotation>[]
    fullName: final Class<?extends Annotation>[]
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
