items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  id: _exit_status
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_UNKNOWN()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_VOID()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_WITH_EXCEPTION()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_WITH_RETURN_VALUE()
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  langs:
  - java
  name: AdvancedAdviceAdapter.ExitStatus
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus
  type: Enum
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 37
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected enum ExitStatus
  inheritance:
  - java.lang.Object
  - java.lang.Enum<AdvancedAdviceAdapter.ExitStatus>
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_UNKNOWN()
  id: EXIT_UNKNOWN()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  langs:
  - java
  name: EXIT_UNKNOWN
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus.EXIT_UNKNOWN
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 41
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public EXIT_UNKNOWN
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_VOID()
  id: EXIT_VOID()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  langs:
  - java
  name: EXIT_VOID
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus.EXIT_VOID
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 40
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public EXIT_VOID
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_WITH_EXCEPTION()
  id: EXIT_WITH_EXCEPTION()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  langs:
  - java
  name: EXIT_WITH_EXCEPTION
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus.EXIT_WITH_EXCEPTION
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 38
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public EXIT_WITH_EXCEPTION
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.EXIT_WITH_RETURN_VALUE()
  id: EXIT_WITH_RETURN_VALUE()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  langs:
  - java
  name: EXIT_WITH_RETURN_VALUE
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus.EXIT_WITH_RETURN_VALUE
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 39
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public EXIT_WITH_RETURN_VALUE
references: []
