items:
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry
  id: _event_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._event_telemetry.additionalSanitize()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry(String)
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getData()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getMetrics()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getName()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getSamplingPercentage()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.setName(String)
  - com.microsoft.applicationinsights.telemetry._event_telemetry.setSamplingPercentage(Double)
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: EventTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 34
  package: com.microsoft.applicationinsights.telemetry
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track events. </p>
  syntax:
    content: public class EventTelemetry extends BaseSampleSourceTelemetry<EventData>
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  inheritedMembers:
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.reset()
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.setSampleRate(Envelope)
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.additionalSanitize()
  id: additionalSanitize()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: additionalSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetry.additionalSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 88
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sanitize additional stuff besides the common </p>
  syntax:
    content: protected void additionalSanitize()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry()
  id: EventTelemetry()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: EventTelemetry()
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry.EventTelemetry()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 41
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Default initialization for a new instance. </p>
  syntax:
    content: public EventTelemetry()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry(String)
  id: EventTelemetry(String)
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: EventTelemetry(String name)
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry.EventTelemetry(String name)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 51
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Initializes a new instance. </p>
  syntax:
    content: public EventTelemetry(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>The event's name. </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getData()
  fullName: EventData com.microsoft.applicationinsights.telemetry.EventTelemetry.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 98
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Fetches the data structure the instance works with </p>
  syntax:
    content: protected EventData getData()
    return:
      type: 9310f39a
      description: <p>The inner data structure. </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getMetrics()
  id: getMetrics()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getMetrics()
  fullName: ConcurrentMap<String, Double> com.microsoft.applicationinsights.telemetry.EventTelemetry.getMetrics()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 60
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets a map of application-defined event metrics. </p>
  syntax:
    content: public ConcurrentMap<String, Double> getMetrics()
    return:
      type: 5f392589
      description: <p>The map of metrics </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.telemetry.EventTelemetry.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 68
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the name of the event. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>The name </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getSamplingPercentage()
  id: getSamplingPercentage()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getSamplingPercentage()
  fullName: Double com.microsoft.applicationinsights.telemetry.EventTelemetry.getSamplingPercentage()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 104
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Double getSamplingPercentage()
    return:
      type: 8dd309d9
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: setName(String name)
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetry.setName(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 76
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the name of the event. </p>
  syntax:
    content: public void setName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>Name of the event </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.setSamplingPercentage(Double)
  id: setSamplingPercentage(Double)
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: setSamplingPercentage(Double samplingPercentage)
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetry.setSamplingPercentage(Double samplingPercentage)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 109
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setSamplingPercentage(Double samplingPercentage)
    parameters:
    - id: samplingPercentage
      type: 8dd309d9
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 5f392589
  spec.java:
  - name: ConcurrentMap<String, Double>
    fullName: ConcurrentMap<String, Double>
- uid: 8dd309d9
  spec.java:
  - name: Double
    fullName: Double
- uid: 9310f39a
  spec.java:
  - name: EventData
    fullName: EventData
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.reset()
  parent: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: reset()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T extends SendableData>.reset()
  type: Method
  syntax:
    content: public void reset()
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.setSampleRate(Envelope)
  parent: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: setSampleRate(Envelope envelope)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T extends SendableData>.setSampleRate(Envelope envelope)
  type: Method
  syntax:
    content: protected void setSampleRate(Envelope envelope)
    parameters:
    - id: envelope
      type: ec5c4d5a
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: BaseSampleSourceTelemetry<T>
  fullName: com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T>
  type: Class
  summary: <p>Created by gupele on 12/4/2016. </p>
  syntax:
    content: public class BaseSampleSourceTelemetry<T extends SendableData> extends BaseTelemetry<T> implements SupportSampling
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
