items:
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger
  id: _internal_logger
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._internal_logger.error(String,Object...)
  - com.microsoft.applicationinsights.internal.logger._internal_logger.info(String,Object...)
  - com.microsoft.applicationinsights.internal.logger._internal_logger.initialize(String,Map<String, String>)
  - com.microsoft.applicationinsights.internal.logger._internal_logger.isErrorEnabled()
  - com.microsoft.applicationinsights.internal.logger._internal_logger.isInfoEnabled()
  - com.microsoft.applicationinsights.internal.logger._internal_logger.isTraceEnabled()
  - com.microsoft.applicationinsights.internal.logger._internal_logger.isWarnEnabled()
  - com.microsoft.applicationinsights.internal.logger._internal_logger.logAlways(LoggingLevel,String,Object...)
  - com.microsoft.applicationinsights.internal.logger._internal_logger.stop()
  - com.microsoft.applicationinsights.internal.logger._internal_logger.trace(String,Object...)
  - com.microsoft.applicationinsights.internal.logger._internal_logger.warn(String,Object...)
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: InternalLogger
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.logger
  summary: >-
    <p>A first, very simple version of an internal logger</p>

    <p>Note: this class is for the SDK internal use only, and therefore should ONLY be used by SDK classes.</p>

    <p>By default the logger will not log messages since it will use the 'NullLoggerOutput' and LoggerLevel of 'OFF' which both deny the output</p>

    <p>Created by gupele on 1/13/2015. </p>
  syntax:
    content: public enum InternalLogger
  inheritance:
  - java.lang.Object
  - java.lang.Enum<InternalLogger>
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.logger._internal_logger_1ac511b34cb54aa4fc9182ece4d0a4493d
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.error(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: error(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLogger.error(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 152
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for errors, will not allow any exception thrown </p>
  syntax:
    content: public void error(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.info(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: info(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLogger.info(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 178
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for info messages, will not allow any exception thrown </p>
  syntax:
    content: public void info(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.initialize(String,Map<String, String>)
  id: initialize(String,Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: initialize(String loggerOutputType, Map<String, String> loggerData)
  fullName: synchronized void com.microsoft.applicationinsights.internal.logger.InternalLogger.initialize(String loggerOutputType, Map<String, String> loggerData)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 85
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>The method will first try to find the logger level and then the logger type. Note that if there are problems initializing the data the internal logger will move to its default state which is LoggerLevel.OFF and no logger output (loggerOutput = null). </p>
  syntax:
    content: public synchronized void initialize(String loggerOutputType, Map<String, String> loggerData)
    parameters:
    - id: loggerOutputType
      type: "26831127"
      description: <p>The requested logger type </p>
    - id: loggerData
      type: 689c8cb5
      description: <p>The data for the internal logger </p>
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.isErrorEnabled()
  id: isErrorEnabled()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: isErrorEnabled()
  fullName: boolean com.microsoft.applicationinsights.internal.logger.InternalLogger.isErrorEnabled()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 142
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public boolean isErrorEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.isInfoEnabled()
  id: isInfoEnabled()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: isInfoEnabled()
  fullName: boolean com.microsoft.applicationinsights.internal.logger.InternalLogger.isInfoEnabled()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 134
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public boolean isInfoEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.isTraceEnabled()
  id: isTraceEnabled()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: isTraceEnabled()
  fullName: boolean com.microsoft.applicationinsights.internal.logger.InternalLogger.isTraceEnabled()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 130
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public boolean isTraceEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.isWarnEnabled()
  id: isWarnEnabled()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: isWarnEnabled()
  fullName: boolean com.microsoft.applicationinsights.internal.logger.InternalLogger.isWarnEnabled()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 138
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public boolean isWarnEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.logAlways(LoggingLevel,String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: logAlways(LoggingLevel requestLevel, String message, Object...args)
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLogger.logAlways(LoggingLevel requestLevel, String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 207
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>The method will log the message in any case. It the logger is not initialized it will print to the console Otherwise the method will use the current logger but will print the message regardless of the logging level. The method is needed for publishing messages when the logger initialization data is unknown Either, before reading the file, or when there was error reading that configuration file, use with care! </p>
  syntax:
    content: public void logAlways(LoggingLevel requestLevel, String message, Object...args)
    parameters:
    - id: requestLevel
      type: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
      description: <p>- The level of the message </p>
    - id: message
      type: "26831127"
      description: <p>- The message to print </p>
    - id: args
      type: 1355eaf1
      description: <p>- The arguments that are part of the message </p>
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.stop()
  id: stop()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: stop()
  fullName: synchronized void com.microsoft.applicationinsights.internal.logger.InternalLogger.stop()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 114
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>Closes the Internal Logger for messages. This method should only be called when the internal logger is not needed which is currently prior to the process exits, i.e. prior to shutdown of the process </p>
  syntax:
    content: public synchronized void stop()
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.trace(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: trace(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLogger.trace(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 191
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for at least trace level, will not allow any exception thrown </p>
  syntax:
    content: public void trace(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger.warn(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger.yml
  langs:
  - java
  name: warn(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLogger.warn(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 165
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for warnings, will not allow any exception thrown </p>
  syntax:
    content: public void warn(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: 5c0b90ca
  spec.java:
  - name: synchronized void
    fullName: synchronized void
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 1355eaf1
  spec.java:
  - name: Object...
    fullName: Object...
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_1ac511b34cb54aa4fc9182ece4d0a4493d
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  name: InternalLogger.LoggingLevel
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel
  type: Enum
  syntax:
    content: public enum LoggingLevel
- uid: com.microsoft.applicationinsights.internal.logger._logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._logger_output.yml
  name: LoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.LoggerOutput
  type: Interface
  summary: <p>Created by gupele on 1/14/2015. </p>
  syntax:
    content: public interface LoggerOutput
