items:
- uid: com.microsoft.applicationinsights.web.spring.internal
  id: internal
  children:
  - com.microsoft.applicationinsights.web.spring.internal._interceptor_registry
  href: com.microsoft.applicationinsights.web.spring.internal.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.spring.internal
  fullName: com.microsoft.applicationinsights.web.spring.internal
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/spring/internal/InterceptorRegistry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/spring/internal/InterceptorRegistry.java
    startLine: 21
  syntax:
    content: namespace internal
references:
- uid: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry
  parent: com.microsoft.applicationinsights.web.spring.internal
  href: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry.yml
  name: InterceptorRegistry
  fullName: com.microsoft.applicationinsights.web.spring.internal.InterceptorRegistry
  type: Class
  summary: <p>This class registers the <xref href="com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter" data-throw-if-not-resolved="false"></xref> to the interceptors registry. The registration enables the interceptor to extract the http request's controller and action names. </p>
  syntax:
    content: public class InterceptorRegistry
