items:
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  id: _synthetic_source_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  children:
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testEmptySources()
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testNullSources()
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testNullTelemetry()
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testOneSourceThatIsFound()
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testSourcesThatIsDeclaredAndFound()
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testSourcesThatIsDeclaredAndNOTFound()
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: SyntheticSourceFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.processor
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class SyntheticSourceFilterTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testEmptySources()
  id: testEmptySources()
  parent: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: testEmptySources()
  fullName: void com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest.testEmptySources()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testEmptySources()
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testNullSources()
  id: testNullSources()
  parent: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: testNullSources()
  fullName: void com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest.testNullSources()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNullSources()
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testNullTelemetry()
  id: testNullTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: testNullTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest.testNullTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNullTelemetry()
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testOneSourceThatIsFound()
  id: testOneSourceThatIsFound()
  parent: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: testOneSourceThatIsFound()
  fullName: void com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest.testOneSourceThatIsFound()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 60
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testOneSourceThatIsFound()
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testSourcesThatIsDeclaredAndFound()
  id: testSourcesThatIsDeclaredAndFound()
  parent: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: testSourcesThatIsDeclaredAndFound()
  fullName: void com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest.testSourcesThatIsDeclaredAndFound()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testSourcesThatIsDeclaredAndFound()
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.testSourcesThatIsDeclaredAndNOTFound()
  id: testSourcesThatIsDeclaredAndNOTFound()
  parent: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  langs:
  - java
  name: testSourcesThatIsDeclaredAndNOTFound()
  fullName: void com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest.testSourcesThatIsDeclaredAndNOTFound()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilterTest.java
    startLine: 81
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testSourcesThatIsDeclaredAndNOTFound()
references: []
