items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker
  id: docker
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker._constants
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.extensibility.initializer.docker
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
    startLine: 21
  syntax:
    content: namespace docker
references:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.yml
  name: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  type: Namespace
  syntax:
    content: namespace internal
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._constants
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._constants.yml
  name: Constants
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.Constants
  type: Class
  summary: <p>Created by yonisha on 8/2/2015. </p>
  syntax:
    content: public class Constants
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.yml
  name: DockerContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>This initializer is required for Docker awareness. The initializer has two goals: 1) Identify Docker context file injected by Application Insight for Docker container and initialize telemetries with Docker context. 2) Write SDK context file which enables the Application Insights for Docker container to discover containers with integrated SDK, and stop sending performance counters in that case (SDK provides OOB performance counters). </p>
  syntax:
    content: public class DockerContextInitializer implements TelemetryInitializer
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer_tests.yml
  name: DockerContextInitializerTests
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextInitializerTests
