items:
- uid: com.microsoft.applicationinsights.logback._application_insights_appender_tests
  id: _application_insights_appender_tests
  parent: com.microsoft.applicationinsights.logback
  children:
  - com.microsoft.applicationinsights.logback._application_insights_appender_tests.setup()
  - com.microsoft.applicationinsights.logback._application_insights_appender_tests.testAppenderSendsGivenEvent()
  - com.microsoft.applicationinsights.logback._application_insights_appender_tests.testInstrumentationKeyIsLoadedFromConfiguration()
  href: com.microsoft.applicationinsights.logback._application_insights_appender_tests.yml
  langs:
  - java
  name: ApplicationInsightsAppenderTests
  fullName: com.microsoft.applicationinsights.logback.ApplicationInsightsAppenderTests
  type: Class
  source:
    remote: &o0
      path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java
    startLine: 36
  package: com.microsoft.applicationinsights.logback
  syntax:
    content: public class ApplicationInsightsAppenderTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.logback._application_insights_appender_tests.setup()
  id: setup()
  parent: com.microsoft.applicationinsights.logback._application_insights_appender_tests
  href: com.microsoft.applicationinsights.logback._application_insights_appender_tests.yml
  langs:
  - java
  name: setup()
  fullName: void com.microsoft.applicationinsights.logback.ApplicationInsightsAppenderTests.setup()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java
    startLine: 47
  package: com.microsoft.applicationinsights.logback
  syntax:
    content: public void setup()
- uid: com.microsoft.applicationinsights.logback._application_insights_appender_tests.testAppenderSendsGivenEvent()
  id: testAppenderSendsGivenEvent()
  parent: com.microsoft.applicationinsights.logback._application_insights_appender_tests
  href: com.microsoft.applicationinsights.logback._application_insights_appender_tests.yml
  langs:
  - java
  name: testAppenderSendsGivenEvent()
  fullName: void com.microsoft.applicationinsights.logback.ApplicationInsightsAppenderTests.testAppenderSendsGivenEvent()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java
    startLine: 64
  package: com.microsoft.applicationinsights.logback
  syntax:
    content: public void testAppenderSendsGivenEvent()
- uid: com.microsoft.applicationinsights.logback._application_insights_appender_tests.testInstrumentationKeyIsLoadedFromConfiguration()
  id: testInstrumentationKeyIsLoadedFromConfiguration()
  parent: com.microsoft.applicationinsights.logback._application_insights_appender_tests
  href: com.microsoft.applicationinsights.logback._application_insights_appender_tests.yml
  langs:
  - java
  name: testInstrumentationKeyIsLoadedFromConfiguration()
  fullName: void com.microsoft.applicationinsights.logback.ApplicationInsightsAppenderTests.testInstrumentationKeyIsLoadedFromConfiguration()
  type: Method
  source:
    remote: *o0
    path: logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java
    startLine: 56
  package: com.microsoft.applicationinsights.logback
  syntax:
    content: public void testInstrumentationKeyIsLoadedFromConfiguration()
references:
- uid: com.microsoft.applicationinsights.logback._application_insights_appender
  parent: com.microsoft.applicationinsights.logback
  href: com.microsoft.applicationinsights.logback._application_insights_appender.yml
  name: ApplicationInsightsAppender
  fullName: com.microsoft.applicationinsights.logback.ApplicationInsightsAppender
  type: Class
  summary: <p>LOGBack appender. </p>
  syntax:
    content: public class ApplicationInsightsAppender
