items:
- uid: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62
  id: _definiti750c1f4b453968d46a6ffd8fb8db1d62
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62.withoutPrivateFrontend()
  href: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 184
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an internal application gateway definition allowing to optionally define a private, or internal, frontend IP configuration. </p>
  syntax:
    content: public interface WithPrivateFrontendOptional extends ApplicationGateway.DefinitionStages.WithPrivateFrontend
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5.withPrivateFrontend()
- uid: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62.withoutPrivateFrontend()
  id: withoutPrivateFrontend()
  parent: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62
  href: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62.yml
  langs:
  - java
  name: withoutPrivateFrontend()
  fullName: WithHttpListener com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional.withoutPrivateFrontend()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 190
  package: com.microsoft.azure.management.network
  summary: <p>Specifies that no private, or internal, frontend should be enabled. </p>
  syntax:
    content: public WithHttpListener withoutPrivateFrontend()
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
      description: <p>the next stage of the definition </p>
references:
- uid: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5.withPrivateFrontend()
  parent: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5
  href: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5.yml
  name: withPrivateFrontend()
  fullName: WithHttpListener com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontend.withPrivateFrontend()
  type: Method
  summary: "<p>Begins the definition of a private, or internal, application gateway frontend IP configuration. \r\nA frontend with the name \"default\" will be created if needed. </p>"
  syntax:
    content: public WithHttpListener withPrivateFrontend()
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
      description: <p>the first stage of a private frontend IP configuration definition Enables a private default frontend in the subnet containing the application gateway. </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5.yml
  name: ApplicationGateway.DefinitionStages.WithPrivateFrontend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontend
  type: Interface
  summary: <p>The stage of an internal application gateway definition allowing to define a private frontend. </p>
  syntax:
    content: public interface WithPrivateFrontend
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
- uid: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.yml
  name: ApplicationGateway.DefinitionStages.WithHttpListener
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListener
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add an HTTP listener. </p>
  syntax:
    content: public interface WithHttpListener
