items:
- uid: com.microsoft.applicationinsights.internal.jmx
  id: jmx
  children:
  - com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.jmx
  fullName: com.microsoft.applicationinsights.internal.jmx
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 21
  syntax:
    content: namespace jmx
references:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  name: JmxAttributeData
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
  type: Class
  summary: >-
    <p>Represents JMX data of an Attribute The display name The name of the attribute The type of the attribute</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxAttributeData
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher.yml
  name: JmxDataFetcher
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcher
  type: Class
  summary: >-
    <p>A utility class that knows how to fetch JMX data.</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxDataFetcher
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.yml
  name: JmxDataFetcherTest
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest
  type: Class
  syntax:
    content: public class JmxDataFetcherTest
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.yml
  name: JmxDataFetcherTest.StubMXBean
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.StubMXBean
  type: Interface
  syntax:
    content: public interface StubMXBean
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  name: JmxDataFetcherTest.TestStub
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub
  type: Class
  syntax:
    content: public class TestStub implements JmxDataFetcherTest.StubMXBean
