items:
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  id: _dependency_kind
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._dependency_kind.DependencyKind(int)
  - com.microsoft.applicationinsights.internal.schemav2._dependency_kind.getValue()
  - com.microsoft.applicationinsights.internal.schemav2._dependency_kind.Http()
  - com.microsoft.applicationinsights.internal.schemav2._dependency_kind.Other()
  - com.microsoft.applicationinsights.internal.schemav2._dependency_kind.SQL()
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  langs:
  - java
  name: DependencyKind
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencyKind
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.internal.schemav2._dependency_kind" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum DependencyKind
  inheritance:
  - java.lang.Object
  - java.lang.Enum<DependencyKind>
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.DependencyKind(int)
  id: DependencyKind(int)
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  langs:
  - java
  name: DependencyKind(int id)
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencyKind.DependencyKind(int id)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public DependencyKind(int id)
    parameters:
    - id: id
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.getValue()
  id: getValue()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  langs:
  - java
  name: getValue()
  fullName: int com.microsoft.applicationinsights.internal.schemav2.DependencyKind.getValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public int getValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.Http()
  id: Http()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  langs:
  - java
  name: Http
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencyKind.Http
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Http=(1)
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.Other()
  id: Other()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  langs:
  - java
  name: Other
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencyKind.Other
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Other=(2)
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.SQL()
  id: SQL()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  langs:
  - java
  name: SQL
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencyKind.SQL
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencyKind.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public SQL=(0)
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_kind
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_kind.yml
  name: DependencyKind
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencyKind
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.internal.schemav2._dependency_kind" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
