items:
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  id: _log_file_proxy
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy.close()
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy.delete()
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy.flush()
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy.isFull()
  - com.microsoft.applicationinsights.internal.logger._log_file_proxy.writeLine(String)
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  langs:
  - java
  name: LogFileProxy
  fullName: com.microsoft.applicationinsights.internal.logger.LogFileProxy
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>Created by gupele on 2/1/2015. </p>
  syntax:
    content: public interface LogFileProxy
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy.close()
  id: close()
  parent: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  langs:
  - java
  name: close()
  fullName: void com.microsoft.applicationinsights.internal.logger.LogFileProxy.close()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void close()
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy.delete()
  id: delete()
  parent: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  langs:
  - java
  name: delete()
  fullName: void com.microsoft.applicationinsights.internal.logger.LogFileProxy.delete()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void delete()
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy.flush()
  id: flush()
  parent: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  langs:
  - java
  name: flush()
  fullName: void com.microsoft.applicationinsights.internal.logger.LogFileProxy.flush()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void flush()
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy.isFull()
  id: isFull()
  parent: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  langs:
  - java
  name: isFull()
  fullName: boolean com.microsoft.applicationinsights.internal.logger.LogFileProxy.isFull()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public boolean isFull()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy.writeLine(String)
  id: writeLine(String)
  parent: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  langs:
  - java
  name: writeLine(String line)
  fullName: void com.microsoft.applicationinsights.internal.logger.LogFileProxy.writeLine(String line)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/LogFileProxy.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void writeLine(String line)
    parameters:
    - id: line
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: DefaultLogFileProxy
  fullName: com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy
  type: Class
  summary: <p>The class is responsible for doing the work with the log files. </p>
  syntax:
    content: public class DefaultLogFileProxy implements LogFileProxy
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.close()
  parent: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: close()
  fullName: void com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy.close()
  type: Method
  syntax:
    content: public void close()
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.delete()
  parent: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: delete()
  fullName: void com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy.delete()
  type: Method
  syntax:
    content: public void delete()
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.writeLine(String)
  parent: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: writeLine(String line)
  fullName: void com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy.writeLine(String line)
  type: Method
  syntax:
    content: public void writeLine(String line)
    parameters:
    - id: line
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.isFull()
  parent: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: isFull()
  fullName: boolean com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy.isFull()
  type: Method
  syntax:
    content: public boolean isFull()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.flush()
  parent: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy
  href: com.microsoft.applicationinsights.internal.logger._default_log_file_proxy.yml
  name: flush()
  fullName: void com.microsoft.applicationinsights.internal.logger.DefaultLogFileProxy.flush()
  type: Method
  syntax:
    content: public void flush()
