items:
- uid: com.microsoft.applicationinsights.sample._ai_custom_context_initializer
  id: _ai_custom_context_initializer
  parent: com.microsoft.applicationinsights.sample
  children:
  - com.microsoft.applicationinsights.sample._ai_custom_context_initializer.main(String[])
  href: com.microsoft.applicationinsights.sample._ai_custom_context_initializer.yml
  langs:
  - java
  name: AiCustomContextInitializer
  fullName: com.microsoft.applicationinsights.sample.AiCustomContextInitializer
  type: Class
  source:
    remote: &o0
      path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiCustomContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiCustomContextInitializer.java
    startLine: 32
  package: com.microsoft.applicationinsights.sample
  summary: <p>Created by gupele on 7/15/2015. </p>
  syntax:
    content: public class AiCustomContextInitializer
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.sample._ai_custom_context_initializer.main(String[])
  id: main(String[])
  parent: com.microsoft.applicationinsights.sample._ai_custom_context_initializer
  href: com.microsoft.applicationinsights.sample._ai_custom_context_initializer.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void com.microsoft.applicationinsights.sample.AiCustomContextInitializer.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiCustomContextInitializer.java
    startLine: 33
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
