items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  id: _method_instrumentation_info
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.addAllMethods(boolean,boolean,MethodVisitorFactory)
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.addMethod(MethodInstrumentationRequest)
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.addMethod(MethodInstrumentationRequest,MethodVisitorFactory)
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.getDecision(String,String)
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.isEmpty()
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  langs:
  - java
  name: MethodInstrumentationInfo
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
    startLine: 39
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: >-
    <p>The class holds the data for methods. The class should collect data for methods of one class.</p>

    <p>For each method the class holds a <xref href="com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision" data-throw-if-not-resolved="false"></xref> that will be used later on if the method of the class is found in runtime.</p>

    <p>The class knows how to 'merge' the information of methods so methods without signatures mean that all methods with that name qualify. to mark all the methods, set priority between methods</p>

    <p>Created by gupele on 5/29/2015. </p>
  syntax:
    content: public class MethodInstrumentationInfo
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.addAllMethods(boolean,boolean,MethodVisitorFactory)
  id: addAllMethods(boolean,boolean,MethodVisitorFactory)
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  langs:
  - java
  name: addAllMethods(boolean reportCaughtExceptions, boolean reportExecutionTime, MethodVisitorFactory methodVisitorFactory)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo.addAllMethods(boolean reportCaughtExceptions, boolean reportExecutionTime, MethodVisitorFactory methodVisitorFactory)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
    startLine: 125
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public void addAllMethods(boolean reportCaughtExceptions, boolean reportExecutionTime, MethodVisitorFactory methodVisitorFactory)
    parameters:
    - id: reportCaughtExceptions
      type: 4fc6e284
    - id: reportExecutionTime
      type: 4fc6e284
    - id: methodVisitorFactory
      type: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.addMethod(MethodInstrumentationRequest)
  id: addMethod(MethodInstrumentationRequest)
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  langs:
  - java
  name: addMethod(MethodInstrumentationRequest methodInstrumentationRequest)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo.addMethod(MethodInstrumentationRequest methodInstrumentationRequest)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
    startLine: 78
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public void addMethod(MethodInstrumentationRequest methodInstrumentationRequest)
    parameters:
    - id: methodInstrumentationRequest
      type: 6adb880f
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.addMethod(MethodInstrumentationRequest,MethodVisitorFactory)
  id: addMethod(MethodInstrumentationRequest,MethodVisitorFactory)
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  langs:
  - java
  name: addMethod(MethodInstrumentationRequest methodInstrumentationRequest, MethodVisitorFactory methodVisitorFactory)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo.addMethod(MethodInstrumentationRequest methodInstrumentationRequest, MethodVisitorFactory methodVisitorFactory)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
    startLine: 82
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public void addMethod(MethodInstrumentationRequest methodInstrumentationRequest, MethodVisitorFactory methodVisitorFactory)
    parameters:
    - id: methodInstrumentationRequest
      type: 6adb880f
    - id: methodVisitorFactory
      type: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.getDecision(String,String)
  id: getDecision(String,String)
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  langs:
  - java
  name: getDecision(String methodName, String methodSignature)
  fullName: MethodInstrumentationDecision com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo.getDecision(String methodName, String methodSignature)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
    startLine: 104
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public MethodInstrumentationDecision getDecision(String methodName, String methodSignature)
    parameters:
    - id: methodName
      type: "26831127"
    - id: methodSignature
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.isEmpty()
  id: isEmpty()
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  langs:
  - java
  name: isEmpty()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo.isEmpty()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationInfo.java
    startLine: 145
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public boolean isEmpty()
    return:
      type: 4fc6e284
references:
- uid: 6adb880f
  spec.java:
  - name: MethodInstrumentationRequest
    fullName: MethodInstrumentationRequest
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  name: MethodInstrumentationDecision
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision
  type: Class
  summary: >-
    <p>The class holds the type of actions that should be done on an instrumented method The class is the 'decision' for the method after taking into consideration init/configuration data</p>

    <p>Note, it is recommended to build an instance with <ref refid="" kindref="compound">com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecisionBuilder</ref></p>

    <p>Created by gupele on 5/31/2015. </p>
  syntax:
    content: public class MethodInstrumentationDecision
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.yml
  name: MethodVisitorFactory
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodVisitorFactory
  type: Interface
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface MethodVisitorFactory
