items:
- uid: com.microsoft.applicationinsights.log4j.v1__2
  id: v1__2
  children:
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v1__2.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.log4j.v1_2
  fullName: com.microsoft.applicationinsights.log4j.v1_2
  type: Namespace
  source:
    remote:
      path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 21
  syntax:
    content: namespace v1_2
references:
- uid: com.microsoft.applicationinsights.log4j.v1__2.internal
  href: com.microsoft.applicationinsights.log4j.v1__2.internal.yml
  name: com.microsoft.applicationinsights.log4j.v1_2.internal
  fullName: com.microsoft.applicationinsights.log4j.v1_2.internal
  type: Namespace
  syntax:
    content: namespace internal
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  parent: com.microsoft.applicationinsights.log4j.v1__2
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  name: ApplicationInsightsAppender
  fullName: com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender
  type: Class
  syntax:
    content: public class ApplicationInsightsAppender
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests
  parent: com.microsoft.applicationinsights.log4j.v1__2
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.yml
  name: ApplicationInsightsAppenderTests
  fullName: com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests
  type: Class
  syntax:
    content: public class ApplicationInsightsAppenderTests
