items:
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result
  id: _registration_result
  parent: com.microsoft.applicationinsights.internal.agent
  children:
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.getCleaner()
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.getKey()
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.RegistrationResult(String,ThreadLocalCleaner)
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.yml
  langs:
  - java
  name: AgentConnector.RegistrationResult
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationResult
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public class RegistrationResult
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.getCleaner()
  id: getCleaner()
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.yml
  langs:
  - java
  name: getCleaner()
  fullName: ThreadLocalCleaner com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationResult.getCleaner()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public ThreadLocalCleaner getCleaner()
    return:
      type: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.getKey()
  id: getKey()
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.yml
  langs:
  - java
  name: getKey()
  fullName: String com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationResult.getKey()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public String getKey()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.RegistrationResult(String,ThreadLocalCleaner)
  id: RegistrationResult(String,ThreadLocalCleaner)
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_result.yml
  langs:
  - java
  name: RegistrationResult(String key, ThreadLocalCleaner cleaner)
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationResult.RegistrationResult(String key, ThreadLocalCleaner cleaner)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public RegistrationResult(String key, ThreadLocalCleaner cleaner)
    parameters:
    - id: key
      type: "26831127"
    - id: cleaner
      type: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._thread_local_cleaner.yml
  name: ThreadLocalCleaner
  fullName: com.microsoft.applicationinsights.internal.util.ThreadLocalCleaner
  type: Interface
  summary: <p>Created by gupele on 7/8/2015. </p>
  syntax:
    content: public interface ThreadLocalCleaner
