items:
- uid: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry
  id: _interceptor_registry
  parent: com.microsoft.applicationinsights.web.spring.internal
  children:
  - com.microsoft.applicationinsights.web.spring.internal._interceptor_registry.addInterceptors(org.springframework.web.servlet.config.annotation.InterceptorRegistry)
  href: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry.yml
  langs:
  - java
  name: InterceptorRegistry
  fullName: com.microsoft.applicationinsights.web.spring.internal.InterceptorRegistry
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/spring/internal/InterceptorRegistry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/spring/internal/InterceptorRegistry.java
    startLine: 34
  package: com.microsoft.applicationinsights.web.spring.internal
  summary: <p>This class registers the <xref href="com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter" data-throw-if-not-resolved="false"></xref> to the interceptors registry. The registration enables the interceptor to extract the http request's controller and action names. </p>
  syntax:
    content: public class InterceptorRegistry
  inheritance:
  - java.lang.Object
  - WebMvcConfigurerAdapter
- uid: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry.addInterceptors(org.springframework.web.servlet.config.annotation.InterceptorRegistry)
  id: InterceptorRegistry)
  parent: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry
  href: com.microsoft.applicationinsights.web.spring.internal._interceptor_registry.yml
  langs:
  - java
  name: addInterceptors(org.springframework.web.servlet.config.annotation.InterceptorRegistry registry)
  fullName: void com.microsoft.applicationinsights.web.spring.internal.InterceptorRegistry.addInterceptors(org.springframework.web.servlet.config.annotation.InterceptorRegistry registry)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/spring/internal/InterceptorRegistry.java
    startLine: 37
  package: com.microsoft.applicationinsights.web.spring.internal
  syntax:
    content: public void addInterceptors(org.springframework.web.servlet.config.annotation.InterceptorRegistry registry)
    parameters:
    - id: registry
      type: 739ece62
references:
- uid: 739ece62
  spec.java:
  - name: org.springframework.web.servlet.config.annotation.InterceptorRegistry
    fullName: org.springframework.web.servlet.config.annotation.InterceptorRegistry
- uid: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter
  parent: com.microsoft.applicationinsights.web.spring
  href: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter.yml
  name: RequestNameHandlerInterceptorAdapter
  fullName: com.microsoft.applicationinsights.web.spring.RequestNameHandlerInterceptorAdapter
  type: Class
  summary: >-
    <p>Created by yonisha on 3/1/2015.</p>

    <p>This class intercepts all requests before forwarded to the relevant handler. It extracts the relevant controller and method names and updates the request telemetry name. This class should never throw exceptions to avoid blocking request processing. </p>
  syntax:
    content: public class RequestNameHandlerInterceptorAdapter
