items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  id: _byte_code_utils
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isAbstract(int)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isAnyConstructor(String)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isConstructor(String)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isInterface(int)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isLargeType(Type)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isPrivate(int)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isStatic(int)
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isStaticInitializer(String)
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: ByteCodeUtils
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class ByteCodeUtils
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isAbstract(int)
  id: isAbstract(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isAbstract(int access)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isAbstract(int access)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 37
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isAbstract(int access)
    parameters:
    - id: access
      type: f75371fa
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isAnyConstructor(String)
  id: isAnyConstructor(String)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isAnyConstructor(String methodName)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isAnyConstructor(String methodName)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 49
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isAnyConstructor(String methodName)
    parameters:
    - id: methodName
      type: "26831127"
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isConstructor(String)
  id: isConstructor(String)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isConstructor(String methodName)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isConstructor(String methodName)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 57
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isConstructor(String methodName)
    parameters:
    - id: methodName
      type: "26831127"
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isInterface(int)
  id: isInterface(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isInterface(int access)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isInterface(int access)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 33
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isInterface(int access)
    parameters:
    - id: access
      type: f75371fa
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isLargeType(Type)
  id: isLargeType(Type)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isLargeType(Type type)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isLargeType(Type type)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 61
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isLargeType(Type type)
    parameters:
    - id: type
      type: 7727faa1
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isPrivate(int)
  id: isPrivate(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isPrivate(int access)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isPrivate(int access)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 41
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isPrivate(int access)
    parameters:
    - id: access
      type: f75371fa
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isStatic(int)
  id: isStatic(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isStatic(int access)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isStatic(int access)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 45
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isStatic(int access)
    parameters:
    - id: access
      type: f75371fa
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.isStaticInitializer(String)
  id: isStaticInitializer(String)
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  langs:
  - java
  name: isStaticInitializer(String methodName)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils.isStaticInitializer(String methodName)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ByteCodeUtils.java
    startLine: 53
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public static boolean isStaticInitializer(String methodName)
    parameters:
    - id: methodName
      type: "26831127"
    return:
      type: 4fc6e284
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 7727faa1
  spec.java:
  - name: Type
    fullName: Type
