items:
- uid: com.microsoft.applicationinsights.web.internal.perfcounter
  id: perfcounter
  children:
  - com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module
  href: com.microsoft.applicationinsights.web.internal.perfcounter.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.internal.perfcounter
  fullName: com.microsoft.applicationinsights.web.internal.perfcounter
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/perfcounter/DefaultWebPerformanceCountersFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/perfcounter/DefaultWebPerformanceCountersFactory.java
  syntax:
    content: namespace perfcounter
references:
- uid: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module
  parent: com.microsoft.applicationinsights.web.internal.perfcounter
  href: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.yml
  name: WebPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
  type: Class
  summary: <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class WebPerformanceCounterModule extends AbstractPerformanceCounterModule
