items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b
  id: _application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b.withBackendPort(int)
  href: com.microsoft.azure.management.network._application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b.yml
  langs:
  - java
  name: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithPort<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithPort<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 57
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the port number. </p>
  syntax:
    content: public interface WithPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b.withBackendPort(int)
  id: withBackendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b
  href: com.microsoft.azure.management.network._application_gateway_backend_http14b9904a584ca2c606b3bd3c4253996b.yml
  langs:
  - java
  name: withBackendPort(int portNumber)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithPort<ParentT>.withBackendPort(int portNumber)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 63
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the port number for this configuration that the backend is listening on. </p>
  syntax:
    content: public WithAttach<ParentT> withBackendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_httpb9e4e68579e1fc3254f1583caee09ca0da8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpb9e4e68579e1fc3254f1583caee09ca0da8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_backend_httpb9e4e68579e1fc3254f1583caee09ca0
    name: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._application_gateway_backend_httpb9e4e68579e1fc3254f1583caee09ca0.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpb9e4e68579e1fc3254f1583caee09ca0
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_httpb9e4e68579e1fc3254f1583caee09ca0.yml
  name: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway backend HTTP configuration. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition,ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithPort<ParentT>,ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithAffinity<ParentT>,ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithProtocol<ParentT>,ApplicationGatewayBackendHttpConfiguration.DefinitionStages.WithRequestTimeout<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
