items:
- uid: com.microsoft.applicationinsights.sample._sample_p_c_plugin
  id: _sample_p_c_plugin
  parent: com.microsoft.applicationinsights.sample
  children:
  - com.microsoft.applicationinsights.sample._sample_p_c_plugin.postCollection()
  - com.microsoft.applicationinsights.sample._sample_p_c_plugin.preCollection()
  href: com.microsoft.applicationinsights.sample._sample_p_c_plugin.yml
  langs:
  - java
  name: SamplePCPlugin
  fullName: com.microsoft.applicationinsights.sample.SamplePCPlugin
  type: Class
  source:
    remote: &o0
      path: samples/src/main/java/com/microsoft/applicationinsights/sample/SamplePCPlugin.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/SamplePCPlugin.java
    startLine: 20
  package: com.microsoft.applicationinsights.sample
  summary: >-
    <p>A sample for creating a concrete plugin that will be called before and after Performance Counters are collected.</p>

    <p>To activate this class you need to add it to the ApplicationInsights.xml configuration file with the 'Plugin' tag:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Plugin&gt;full.path.to.your.Plugin&lt;/Plugin&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>Created by gupele on 9/13/2016. </p>
  syntax:
    content: public class SamplePCPlugin implements PerformanceCountersCollectionPlugin
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
- uid: com.microsoft.applicationinsights.sample._sample_p_c_plugin.postCollection()
  id: postCollection()
  parent: com.microsoft.applicationinsights.sample._sample_p_c_plugin
  href: com.microsoft.applicationinsights.sample._sample_p_c_plugin.yml
  langs:
  - java
  name: postCollection()
  fullName: void com.microsoft.applicationinsights.sample.SamplePCPlugin.postCollection()
  type: Method
  source:
    remote: *o0
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/SamplePCPlugin.java
    startLine: 27
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public void postCollection()
  overridden: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.postCollection()
- uid: com.microsoft.applicationinsights.sample._sample_p_c_plugin.preCollection()
  id: preCollection()
  parent: com.microsoft.applicationinsights.sample._sample_p_c_plugin
  href: com.microsoft.applicationinsights.sample._sample_p_c_plugin.yml
  langs:
  - java
  name: preCollection()
  fullName: void com.microsoft.applicationinsights.sample.SamplePCPlugin.preCollection()
  type: Method
  source:
    remote: *o0
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/SamplePCPlugin.java
    startLine: 22
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public void preCollection()
  overridden: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.preCollection()
references:
- uid: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.yml
  name: PerformanceCountersCollectionPlugin
  fullName: com.microsoft.applicationinsights.extensibility.PerformanceCountersCollectionPlugin
  type: Interface
  summary: <p>Created by gupele on 9/13/2016. </p>
  syntax:
    content: public interface PerformanceCountersCollectionPlugin
- uid: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.preCollection()
  parent: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
  href: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.yml
  name: preCollection()
  fullName: void com.microsoft.applicationinsights.extensibility.PerformanceCountersCollectionPlugin.preCollection()
  type: Method
  syntax:
    content: public void preCollection()
- uid: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.postCollection()
  parent: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
  href: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.yml
  name: postCollection()
  fullName: void com.microsoft.applicationinsights.extensibility.PerformanceCountersCollectionPlugin.postCollection()
  type: Method
  syntax:
    content: public void postCollection()
