items:
- uid: com.microsoft.applicationinsights.web.struts._request_name_interceptor
  id: _request_name_interceptor
  parent: com.microsoft.applicationinsights.web.struts
  children:
  - com.microsoft.applicationinsights.web.struts._request_name_interceptor.destroy()
  - com.microsoft.applicationinsights.web.struts._request_name_interceptor.init()
  - com.microsoft.applicationinsights.web.struts._request_name_interceptor.intercept(ActionInvocation)
  href: com.microsoft.applicationinsights.web.struts._request_name_interceptor.yml
  langs:
  - java
  name: RequestNameInterceptor
  fullName: com.microsoft.applicationinsights.web.struts.RequestNameInterceptor
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
    startLine: 33
  package: com.microsoft.applicationinsights.web.struts
  summary: <p>Created by yonisha on 3/10/2015. </p>
  syntax:
    content: public class RequestNameInterceptor
  inheritance:
  - java.lang.Object
  - Interceptor
- uid: com.microsoft.applicationinsights.web.struts._request_name_interceptor.destroy()
  id: destroy()
  parent: com.microsoft.applicationinsights.web.struts._request_name_interceptor
  href: com.microsoft.applicationinsights.web.struts._request_name_interceptor.yml
  langs:
  - java
  name: destroy()
  fullName: void com.microsoft.applicationinsights.web.struts.RequestNameInterceptor.destroy()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
    startLine: 67
  package: com.microsoft.applicationinsights.web.struts
  summary: <p>Called to let an interceptor clean up any resources it has allocated. </p>
  syntax:
    content: public void destroy()
- uid: com.microsoft.applicationinsights.web.struts._request_name_interceptor.init()
  id: init()
  parent: com.microsoft.applicationinsights.web.struts._request_name_interceptor
  href: com.microsoft.applicationinsights.web.struts._request_name_interceptor.yml
  langs:
  - java
  name: init()
  fullName: void com.microsoft.applicationinsights.web.struts.RequestNameInterceptor.init()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
    startLine: 43
  package: com.microsoft.applicationinsights.web.struts
  summary: <p>Called after an interceptor is created, but before any requests are processed using <ref refid="" kindref="compound">intercept</ref> , giving the Interceptor a chance to initialize any needed resources. </p>
  syntax:
    content: public void init()
- uid: com.microsoft.applicationinsights.web.struts._request_name_interceptor.intercept(ActionInvocation)
  id: intercept(ActionInvocation)
  parent: com.microsoft.applicationinsights.web.struts._request_name_interceptor
  href: com.microsoft.applicationinsights.web.struts._request_name_interceptor.yml
  langs:
  - java
  name: intercept(ActionInvocation invocation)
  fullName: String com.microsoft.applicationinsights.web.struts.RequestNameInterceptor.intercept(ActionInvocation invocation)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
    startLine: 55
  package: com.microsoft.applicationinsights.web.struts
  summary: >-
    <p>Allows the Interceptor to do some processing on the request before and/or after the rest of the processing of the request by the <ref refid="" kindref="compound">com.opensymphony.xwork2.ActionInvocation</ref> or to short-circuit the processing and just return a String return code.</p>

    <p></p>
  syntax:
    content: public String intercept(ActionInvocation invocation)
    parameters:
    - id: invocation
      type: 969f85f3
      description: <p>The action invocation. </p>
    return:
      type: "26831127"
      description: <p>the return code, either returned from <ref refid="" kindref="compound">com.opensymphony.xwork2.ActionInvocation#invoke()</ref>, or from the interceptor itself. </p>
  exceptions:
  - type: 8a99d4b0
    description: <p>any system-level error, as defined in <ref refid="" kindref="compound">com.opensymphony.xwork2.Action#execute()</ref>. </p>
references:
- uid: 8a99d4b0
  spec.java:
  - name: Exception
    fullName: Exception
- uid: 969f85f3
  spec.java:
  - name: ActionInvocation
    fullName: ActionInvocation
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
