items:
- uid: com.microsoft.applicationinsights.common
  id: common
  children:
  - com.microsoft.applicationinsights.common._common_utils
  href: com.microsoft.applicationinsights.common.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.common
  fullName: com.microsoft.applicationinsights.common
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java
    startLine: 21
  syntax:
    content: namespace common
references:
- uid: com.microsoft.applicationinsights.common._common_utils
  parent: com.microsoft.applicationinsights.common
  href: com.microsoft.applicationinsights.common._common_utils.yml
  name: CommonUtils
  fullName: com.microsoft.applicationinsights.common.CommonUtils
  type: Class
  summary: <p>Created by oriy on 11/2/2016. </p>
  syntax:
    content: public class CommonUtils
