items:
- uid: com.microsoft.applicationinsights.agent.internal.config
  id: config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  - com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder
  href: com.microsoft.applicationinsights.agent.internal.config.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.config
  fullName: com.microsoft.applicationinsights.agent.internal.config
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 21
  syntax:
    content: namespace config
references:
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  name: AgentBuiltInConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration
  type: Class
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax:
    content: public class AgentBuiltInConfiguration
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  name: AgentBuiltInConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder
  type: Class
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax:
    content: public class AgentBuiltInConfigurationBuilder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  name: AgentConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration
  type: Interface
  summary: <p>Defines the interface for concrete classes that represent configuration data for the Agent Created by gupele on 5/17/2015. </p>
  syntax:
    content: public interface AgentConfiguration
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder.yml
  name: AgentConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilder
  type: Interface
  summary: <p>Defines the interface for builders that know how to create <xref href="com.microsoft.applicationinsights.agent.internal.config._agent_configuration" data-throw-if-not-resolved="false"></xref> Created by gupele on 5/19/2015. </p>
  syntax:
    content: public interface AgentConfigurationBuilder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder_factory.yml
  name: AgentConfigurationBuilderFactory
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilderFactory
  type: Class
  summary: >-
    <p>The factory is responsible for creating the correct <xref href="com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class AgentConfigurationBuilderFactory
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder.yml
  name: BuiltInInstrumentedClassesBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClassesBuilder
  type: Class
  summary: <p>Created by gupele on 9/5/2016. </p>
  syntax:
    content: public class BuiltInInstrumentedClassesBuilder
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  name: DataOfConfigurationForException
  fullName: com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException
  type: Class
  summary: <p>Created by gupele on 8/18/2016. </p>
  syntax:
    content: public class DataOfConfigurationForException
- uid: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder.yml
  name: SelfCoreRegistrationModeBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.SelfCoreRegistrationModeBuilder
  type: Class
  summary: <p>Created by gupele on 9/11/2016. </p>
  syntax:
    content: public class SelfCoreRegistrationModeBuilder
