items:
- uid: com.microsoft.applicationinsights.internal.schemav2._application
  id: _application
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._application.addToHashMap(HashMap<String, String>)
  - com.microsoft.applicationinsights.internal.schemav2._application.Application()
  - com.microsoft.applicationinsights.internal.schemav2._application.getVer()
  - com.microsoft.applicationinsights.internal.schemav2._application.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._application.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._application.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._application.setVer(String)
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: Application
  fullName: com.microsoft.applicationinsights.internal.schemav2.Application
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._application" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class Application implements JsonSerializable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
- uid: com.microsoft.applicationinsights.internal.schemav2._application.addToHashMap(HashMap<String, String>)
  id: addToHashMap(HashMap<String, String>)
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: addToHashMap(HashMap<String, String> map)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Application.addToHashMap(HashMap<String, String> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 60
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Adds all members of this class to a hashmap </p>
  syntax:
    content: public void addToHashMap(HashMap<String, String> map)
    parameters:
    - id: map
      type: 3970a053
      description: <p>to which the members of this class will be added. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._application.Application()
  id: Application()
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: Application()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Application.Application()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Application()
- uid: com.microsoft.applicationinsights.internal.schemav2._application.getVer()
  id: getVer()
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: getVer()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Application.getVer()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getVer()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._application.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Application.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._application.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Application.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 73
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  exceptions:
  - type: cbf33bbe
    description: <p>Might be throw during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._application.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Application.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
- uid: com.microsoft.applicationinsights.internal.schemav2._application.setVer(String)
  id: setVer(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._application
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  langs:
  - java
  name: setVer(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Application.setVer(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Application.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setVer(String value)
    parameters:
    - id: value
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 3970a053
  spec.java:
  - name: HashMap<String, String>
    fullName: HashMap<String, String>
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData>
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._application
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._application.yml
  name: Application
  fullName: com.microsoft.applicationinsights.internal.schemav2.Application
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._application" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
