items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  id: _jmx_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.getId()
  - com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.JmxPerformanceCounter(String,String,final String,final Collection<JmxAttributeData>)
  - com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.JmxPerformanceCounter(String,String,Map<String, Collection<JmxAttributeData>>)
  - com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.report(TelemetryClient)
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  langs:
  - java
  name: JmxPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>A performance counter that sends <xref href="com.microsoft.applicationinsights.telemetry._performance_counter_telemetry" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxPerformanceCounter implements PerformanceCounter
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
    startLine: 67
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String getId()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.JmxPerformanceCounter(String,String,final String,final Collection<JmxAttributeData>)
  id: JmxPerformanceCounter(String,String,final String,final Collection<JmxAttributeData>)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  langs:
  - java
  name: JmxPerformanceCounter(String categoryName, String counterName, final String objectName, final Collection<JmxAttributeData> attributes)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter.JmxPerformanceCounter(String categoryName, String counterName, final String objectName, final Collection<JmxAttributeData> attributes)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public JmxPerformanceCounter(String categoryName, String counterName, final String objectName, final Collection<JmxAttributeData> attributes)
    parameters:
    - id: categoryName
      type: "26831127"
    - id: counterName
      type: "26831127"
    - id: objectName
      type: 3d93591e
    - id: attributes
      type: c28b35ebcom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.JmxPerformanceCounter(String,String,Map<String, Collection<JmxAttributeData>>)
  id: JmxPerformanceCounter(String,String,Map<String, Collection<JmxAttributeData>>)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  langs:
  - java
  name: JmxPerformanceCounter(String categoryName, String counterName, Map<String, Collection<JmxAttributeData>> objectToAttributes)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter.JmxPerformanceCounter(String categoryName, String counterName, Map<String, Collection<JmxAttributeData>> objectToAttributes)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public JmxPerformanceCounter(String categoryName, String counterName, Map<String, Collection<JmxAttributeData>> objectToAttributes)
    parameters:
    - id: categoryName
      type: "26831127"
    - id: counterName
      type: "26831127"
    - id: objectToAttributes
      type: ff2d2cf6com.microsoft.applicationinsights.internal.jmx._jmx_attribute_datae7daa122
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.report(TelemetryClient)
  id: report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  langs:
  - java
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
    startLine: 72
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: c28b35ebcom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
  spec.java:
  - name: final Collection<
    fullName: final Collection<
  - uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
    name: JmxAttributeData
    fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
    href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  - name: '>'
    fullName: '>'
- uid: ff2d2cf6com.microsoft.applicationinsights.internal.jmx._jmx_attribute_datae7daa122
  spec.java:
  - name: Map<String, Collection<
    fullName: Map<String, Collection<
  - uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
    name: JmxAttributeData
    fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
    href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  - name: '>>'
    fullName: '>>'
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: PerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.perfcounter._performance_counter" data-throw-if-not-resolved="false"></xref> interface.</p>

    <p>Every concrete class should have a unique id and it should be able to collect data send that data using a <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface PerformanceCounter
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry.yml
  name: PerformanceCounterTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetry
  type: Class
  summary: <p>The class that represents information about performance counters. </p>
  syntax:
    content: public class PerformanceCounterTelemetry
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  name: JmxAttributeData
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
  type: Class
  summary: >-
    <p>Represents JMX data of an Attribute The display name The name of the attribute The type of the attribute</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxAttributeData
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
