items:
- uid: com.microsoft.applicationinsights.internal.annotation._built_in_processor
  id: _built_in_processor
  parent: com.microsoft.applicationinsights.internal.annotation
  children:
  - com.microsoft.applicationinsights.internal.annotation._built_in_processor.value()
  href: com.microsoft.applicationinsights.internal.annotation._built_in_processor.yml
  langs:
  - java
  name: BuiltInProcessor
  fullName: com.microsoft.applicationinsights.internal.annotation.BuiltInProcessor
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/BuiltInProcessor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/BuiltInProcessor.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.annotation
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public interface BuiltInProcessor
- uid: com.microsoft.applicationinsights.internal.annotation._built_in_processor.value()
  id: value()
  parent: com.microsoft.applicationinsights.internal.annotation._built_in_processor
  href: com.microsoft.applicationinsights.internal.annotation._built_in_processor.yml
  langs:
  - java
  name: value()
  fullName: String com.microsoft.applicationinsights.internal.annotation.BuiltInProcessor.value()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/BuiltInProcessor.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.annotation
  syntax:
    content: public String value()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
