items:
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  id: _exception_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testCtor()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testError()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testExceptions()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testFirstValueIsNull()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testGetThrowableOnException()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetException()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetExceptionHandledAt()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetSeverityLevel()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetSeverityLevelWithNull()
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: ExceptionTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class ExceptionTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testCtor()
  id: testCtor()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 46
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtor()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testError()
  id: testError()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testError()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testError()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 99
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testError()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testExceptions()
  id: testExceptions()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testExceptions()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testExceptions()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 66
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testExceptions()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testFirstValueIsNull()
  id: testFirstValueIsNull()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testFirstValueIsNull()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testFirstValueIsNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 84
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testFirstValueIsNull()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testGetThrowableOnException()
  id: testGetThrowableOnException()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testGetThrowableOnException()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testGetThrowableOnException()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 90
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testGetThrowableOnException()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetException()
  id: testSetException()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testSetException()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testSetException()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetException()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetExceptionHandledAt()
  id: testSetExceptionHandledAt()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testSetExceptionHandledAt()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testSetExceptionHandledAt()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 57
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetExceptionHandledAt()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetSeverityLevel()
  id: testSetSeverityLevel()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testSetSeverityLevel()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testSetSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 74
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetSeverityLevel()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.testSetSeverityLevelWithNull()
  id: testSetSeverityLevelWithNull()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  langs:
  - java
  name: testSetSeverityLevelWithNull()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest.testSetSeverityLevelWithNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetryTest.java
    startLine: 79
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetSeverityLevelWithNull()
references:
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
