items:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test
  id: _jmx_data_fetcher_test
  parent: com.microsoft.applicationinsights.internal.jmx
  children:
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.testBadAttributeName()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.testBadName()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.testWithChange()
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.yml
  langs:
  - java
  name: JmxDataFetcherTest
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 13
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public class JmxDataFetcherTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.testBadAttributeName()
  id: testBadAttributeName()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.yml
  langs:
  - java
  name: testBadAttributeName()
  fullName: void com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.testBadAttributeName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public void testBadAttributeName()
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.testBadName()
  id: testBadName()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.yml
  langs:
  - java
  name: testBadName()
  fullName: void com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.testBadName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 60
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public void testBadName()
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.testWithChange()
  id: testWithChange()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test.yml
  langs:
  - java
  name: testWithChange()
  fullName: void com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.testWithChange()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public void testWithChange()
references:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  name: JmxAttributeData
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
  type: Class
  summary: >-
    <p>Represents JMX data of an Attribute The display name The name of the attribute The type of the attribute</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxAttributeData
