items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
  id: _method_visitor_factory
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.create(MethodInstrumentationDecision,int,String,String,String,MethodVisitor,ClassToMethodTransformationData)
  href: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.yml
  langs:
  - java
  name: MethodVisitorFactory
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodVisitorFactory
  type: Interface
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodVisitorFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodVisitorFactory.java
    startLine: 28
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface MethodVisitorFactory
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.create(MethodInstrumentationDecision,int,String,String,String,MethodVisitor,ClassToMethodTransformationData)
  id: create(MethodInstrumentationDecision,int,String,String,String,MethodVisitor,ClassToMethodTransformationData)
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
  href: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.yml
  langs:
  - java
  name: create(MethodInstrumentationDecision decision, int access, String desc, String owner, String methodName, MethodVisitor methodVisitor, ClassToMethodTransformationData additionalData)
  fullName: MethodVisitor com.microsoft.applicationinsights.agent.internal.agent.MethodVisitorFactory.create(MethodInstrumentationDecision decision, int access, String desc, String owner, String methodName, MethodVisitor methodVisitor, ClassToMethodTransformationData additionalData)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodVisitorFactory.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public MethodVisitor create(MethodInstrumentationDecision decision, int access, String desc, String owner, String methodName, MethodVisitor methodVisitor, ClassToMethodTransformationData additionalData)
    parameters:
    - id: decision
      type: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
    - id: access
      type: f75371fa
    - id: desc
      type: "26831127"
    - id: owner
      type: "26831127"
    - id: methodName
      type: "26831127"
    - id: methodVisitor
      type: dd525b3c
    - id: additionalData
      type: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
    return:
      type: dd525b3c
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: dd525b3c
  spec.java:
  - name: MethodVisitor
    fullName: MethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  name: MethodInstrumentationDecision
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision
  type: Class
  summary: >-
    <p>The class holds the type of actions that should be done on an instrumented method The class is the 'decision' for the method after taking into consideration init/configuration data</p>

    <p>Note, it is recommended to build an instance with <ref refid="" kindref="compound">com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecisionBuilder</ref></p>

    <p>Created by gupele on 5/31/2015. </p>
  syntax:
    content: public class MethodInstrumentationDecision
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data.yml
  name: ClassToMethodTransformationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassToMethodTransformationData
  type: Interface
  summary: >-
    <p>A marker to allow Class Visitors to pass data to Method Visitors</p>

    <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface ClassToMethodTransformationData
