items:
- uid: com.microsoft.applicationinsights.internal.processor
  id: processor
  children:
  - com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter
  - com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  - com.microsoft.applicationinsights.internal.processor._request_telemetry_filter
  - com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter
  - com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  - com.microsoft.applicationinsights.internal.processor._telemetry_event_filter
  - com.microsoft.applicationinsights.internal.processor._telemetry_event_filter_test
  - com.microsoft.applicationinsights.internal.processor._trace_telemetry_filter
  - com.microsoft.applicationinsights.internal.processor._trace_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.processor
  fullName: com.microsoft.applicationinsights.internal.processor
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilter.java
    startLine: 21
  syntax:
    content: namespace processor
references:
- uid: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter.yml
  name: MetricTelemetryFilter
  fullName: com.microsoft.applicationinsights.internal.processor.MetricTelemetryFilter
  type: Class
  summary: >-
    <p>The class can filter out MetricTelemetries with configurable names</p>

    <p>Invalid values would prevent the filter from being used.</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class MetricTelemetryFilter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.yml
  name: MetricTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.MetricTelemetryFilterTest
  type: Class
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class MetricTelemetryFilterTest
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  name: PageViewTelemetryFilter
  fullName: com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter
  type: Class
  summary: >-
    <p>The class can filter out PageViewTelemetries that have a duration which is less than a predefined value have URLs that has parts that are not needed, i.e. telemetries that will not be sent, based on configuration have unneeded page names i.e. telemetries that will not be sent, that were predefined in configuration</p>

    <p>Invalid values would prevent the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class PageViewTelemetryFilter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  name: PageViewTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class PageViewTelemetryFilterTest
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter.yml
  name: RequestTelemetryFilter
  fullName: com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilter
  type: Class
  summary: >-
    <p>The class can filter out RequestTelemetries that have a duration which is less than a predefined value have http codes that are not needed based on configuration</p>

    <p>Illegal value will prevent from the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class RequestTelemetryFilter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._request_telemetry_filter_test.yml
  name: RequestTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.RequestTelemetryFilterTest
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class RequestTelemetryFilterTest
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter.yml
  name: SyntheticSourceFilter
  fullName: com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilter
  type: Class
  summary: >-
    <p>The class will filter out telemetries that come from 'unneeded' configured list of source names</p>

    <p>Illegal value will prevent from the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class SyntheticSourceFilter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._synthetic_source_filter_test.yml
  name: SyntheticSourceFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.SyntheticSourceFilterTest
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class SyntheticSourceFilterTest
- uid: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.yml
  name: TelemetryEventFilter
  fullName: com.microsoft.applicationinsights.internal.processor.TelemetryEventFilter
  type: Class
  summary: >-
    <p>The class will filter out Event Telemetries with unneeded values</p>

    <p>Illegal value will prevent from the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryEventFilter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter_test.yml
  name: TelemetryEventFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.TelemetryEventFilterTest
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryEventFilterTest
- uid: com.microsoft.applicationinsights.internal.processor._trace_telemetry_filter
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._trace_telemetry_filter.yml
  name: TraceTelemetryFilter
  fullName: com.microsoft.applicationinsights.internal.processor.TraceTelemetryFilter
  type: Class
  summary: >-
    <p>The class can filter out TraceTelemetries ('LOG' telemetries) that have 'lower' severity level than needed The possible values are: OFF - Filter out ALL traces TRACE - No filtering. equals to Trace level INFO - Filter out TRACE level WARN - Filter out TRACE and INFO ERROR - Filter out WARN, INFO, TRACE CRITICAL - filter out all but CRITICAL</p>

    <p>Illegal value will prevent from the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TraceTelemetryFilter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.processor._trace_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  href: com.microsoft.applicationinsights.internal.processor._trace_telemetry_filter_test.yml
  name: TraceTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.TraceTelemetryFilterTest
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TraceTelemetryFilterTest
