items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  id: _constants
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.AI_SDK_DIRECTORY()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.AI_SDK_INFO_FILE_CONTENT_TEMPLATE()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.AI_SDK_INFO_FILENAME()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_CONTAINER_ID_PROPERTY_KEY()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_CONTAINER_NAME_PROPERTY_KEY()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_HOST_PROPERTY_KEY()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_IMAGE_PROPERTY_KEY()
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: Constants
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 26
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class Constants
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.AI_SDK_DIRECTORY()
  id: AI_SDK_DIRECTORY()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: AI_SDK_DIRECTORY
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.AI_SDK_DIRECTORY
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 27
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String AI_SDK_DIRECTORY= "/usr/appinsights/docker"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.AI_SDK_INFO_FILE_CONTENT_TEMPLATE()
  id: AI_SDK_INFO_FILE_CONTENT_TEMPLATE()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: AI_SDK_INFO_FILE_CONTENT_TEMPLATE
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.AI_SDK_INFO_FILE_CONTENT_TEMPLATE
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 29
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String AI_SDK_INFO_FILE_CONTENT_TEMPLATE= "InstrumentationKey=%s"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.AI_SDK_INFO_FILENAME()
  id: AI_SDK_INFO_FILENAME()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: AI_SDK_INFO_FILENAME
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.AI_SDK_INFO_FILENAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 28
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String AI_SDK_INFO_FILENAME= "sdk.info"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_CONTAINER_ID_PROPERTY_KEY()
  id: DOCKER_CONTAINER_ID_PROPERTY_KEY()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: DOCKER_CONTAINER_ID_PROPERTY_KEY
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.DOCKER_CONTAINER_ID_PROPERTY_KEY
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 34
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String DOCKER_CONTAINER_ID_PROPERTY_KEY= "Docker container id"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_CONTAINER_NAME_PROPERTY_KEY()
  id: DOCKER_CONTAINER_NAME_PROPERTY_KEY()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: DOCKER_CONTAINER_NAME_PROPERTY_KEY
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.DOCKER_CONTAINER_NAME_PROPERTY_KEY
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 33
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String DOCKER_CONTAINER_NAME_PROPERTY_KEY= "Docker container name"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_HOST_PROPERTY_KEY()
  id: DOCKER_HOST_PROPERTY_KEY()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: DOCKER_HOST_PROPERTY_KEY
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.DOCKER_HOST_PROPERTY_KEY
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 31
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String DOCKER_HOST_PROPERTY_KEY= "Docker host"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.DOCKER_IMAGE_PROPERTY_KEY()
  id: DOCKER_IMAGE_PROPERTY_KEY()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  langs:
  - java
  name: DOCKER_IMAGE_PROPERTY_KEY
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants.DOCKER_IMAGE_PROPERTY_KEY
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 32
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public static final String DOCKER_IMAGE_PROPERTY_KEY= "Docker image"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
