items:
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  id: _logging_level
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.ALL()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.ERROR()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.getValue()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.INFO()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.LoggingLevel(int)
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.OFF()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.TRACE()
  - com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.WARN()
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: InternalLogger.LoggingLevel
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public enum LoggingLevel
  inheritance:
  - java.lang.Object
  - java.lang.Enum<InternalLogger.LoggingLevel>
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.ALL()
  id: ALL()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: ALL
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.ALL
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public ALL=(Integer.MIN_VALUE)
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.ERROR()
  id: ERROR()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: ERROR
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.ERROR
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public ERROR=(40000)
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.getValue()
  id: getValue()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: getValue()
  fullName: int com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.getValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public int getValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.INFO()
  id: INFO()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: INFO
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.INFO
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public INFO=(20000)
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.LoggingLevel(int)
  id: LoggingLevel(int)
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: LoggingLevel(int value)
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.LoggingLevel(int value)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public LoggingLevel(int value)
    parameters:
    - id: value
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.OFF()
  id: OFF()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: OFF
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.OFF
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public OFF=(50000)
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.TRACE()
  id: TRACE()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: TRACE
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.TRACE
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public TRACE=(10000)
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.WARN()
  id: WARN()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level
  href: com.microsoft.applicationinsights.internal.logger._internal_logger._logging_level.yml
  langs:
  - java
  name: WARN
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLogger.LoggingLevel.WARN
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public WARN=(30000)
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
