items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  id: _transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission.getContent()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.getNumberOfPersistence()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.getNumberOfSends()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.getVersion()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.getWebContentEncodingType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.getWebContentType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.incrementNumberOfPersistence()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.incrementNumberOfSends()
  - com.microsoft.applicationinsights.internal.channel.common._transmission.setNumberOfPersistence(int)
  - com.microsoft.applicationinsights.internal.channel.common._transmission.setNumberOfSends(int)
  - com.microsoft.applicationinsights.internal.channel.common._transmission.Transmission(byte[],String,String)
  - com.microsoft.applicationinsights.internal.channel.common._transmission.Transmission(byte[],String,String,int)
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
  inheritance:
  - java.lang.Object
  - Serializable
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.getContent()
  id: getContent()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: getContent()
  fullName: byte [] com.microsoft.applicationinsights.internal.channel.common.Transmission.getContent()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public byte[] getContent()
    return:
      type: bc819c2f
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.getNumberOfPersistence()
  id: getNumberOfPersistence()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: getNumberOfPersistence()
  fullName: int com.microsoft.applicationinsights.internal.channel.common.Transmission.getNumberOfPersistence()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public int getNumberOfPersistence()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.getNumberOfSends()
  id: getNumberOfSends()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: getNumberOfSends()
  fullName: int com.microsoft.applicationinsights.internal.channel.common.Transmission.getNumberOfSends()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public int getNumberOfSends()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.getVersion()
  id: getVersion()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: getVersion()
  fullName: int com.microsoft.applicationinsights.internal.channel.common.Transmission.getVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 99
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public int getVersion()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.getWebContentEncodingType()
  id: getWebContentEncodingType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: getWebContentEncodingType()
  fullName: String com.microsoft.applicationinsights.internal.channel.common.Transmission.getWebContentEncodingType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public String getWebContentEncodingType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.getWebContentType()
  id: getWebContentType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: getWebContentType()
  fullName: String com.microsoft.applicationinsights.internal.channel.common.Transmission.getWebContentType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 67
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public String getWebContentType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.incrementNumberOfPersistence()
  id: incrementNumberOfPersistence()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: incrementNumberOfPersistence()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.Transmission.incrementNumberOfPersistence()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void incrementNumberOfPersistence()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.incrementNumberOfSends()
  id: incrementNumberOfSends()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: incrementNumberOfSends()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.Transmission.incrementNumberOfSends()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void incrementNumberOfSends()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.setNumberOfPersistence(int)
  id: setNumberOfPersistence(int)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: setNumberOfPersistence(int numberOfPersistence)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.Transmission.setNumberOfPersistence(int numberOfPersistence)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void setNumberOfPersistence(int numberOfPersistence)
    parameters:
    - id: numberOfPersistence
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.setNumberOfSends(int)
  id: setNumberOfSends(int)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: setNumberOfSends(int numberOfSends)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.Transmission.setNumberOfSends(int numberOfSends)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 87
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void setNumberOfSends(int numberOfSends)
    parameters:
    - id: numberOfSends
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.Transmission(byte[],String,String)
  id: Transmission(byte[],String,String)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: Transmission(byte[] content, String webContentType, String webContentEncodingType)
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission.Transmission(byte[] content, String webContentType, String webContentEncodingType)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public Transmission(byte[] content, String webContentType, String webContentEncodingType)
    parameters:
    - id: content
      type: bc819c2f
    - id: webContentType
      type: "26831127"
    - id: webContentEncodingType
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission.Transmission(byte[],String,String,int)
  id: Transmission(byte[],String,String,int)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  langs:
  - java
  name: Transmission(byte[] content, String webContentType, String webContentEncodingType, int version)
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission.Transmission(byte[] content, String webContentType, String webContentEncodingType, int version)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/Transmission.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public Transmission(byte[] content, String webContentType, String webContentEncodingType, int version)
    parameters:
    - id: content
      type: bc819c2f
    - id: webContentType
      type: "26831127"
    - id: webContentEncodingType
      type: "26831127"
    - id: version
      type: f75371fa
references:
- uid: bc819c2f
  spec.java:
  - name: byte[]
    fullName: byte[]
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
