items:
- uid: com.microsoft.applicationinsights.web.internal._thread_context
  id: _thread_context
  parent: com.microsoft.applicationinsights.web.internal
  children:
  - com.microsoft.applicationinsights.web.internal._thread_context.getRequestTelemetryContext()
  - com.microsoft.applicationinsights.web.internal._thread_context.remove()
  - com.microsoft.applicationinsights.web.internal._thread_context.setRequestTelemetryContext(RequestTelemetryContext)
  href: com.microsoft.applicationinsights.web.internal._thread_context.yml
  langs:
  - java
  name: ThreadContext
  fullName: com.microsoft.applicationinsights.web.internal.ThreadContext
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
    startLine: 26
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class ThreadContext
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.web.internal._thread_context.getRequestTelemetryContext()
  id: getRequestTelemetryContext()
  parent: com.microsoft.applicationinsights.web.internal._thread_context
  href: com.microsoft.applicationinsights.web.internal._thread_context.yml
  langs:
  - java
  name: getRequestTelemetryContext()
  fullName: static RequestTelemetryContext com.microsoft.applicationinsights.web.internal.ThreadContext.getRequestTelemetryContext()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
    startLine: 33
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public static RequestTelemetryContext getRequestTelemetryContext()
    return:
      type: com.microsoft.applicationinsights.web.internal._request_telemetry_context
- uid: com.microsoft.applicationinsights.web.internal._thread_context.remove()
  id: remove()
  parent: com.microsoft.applicationinsights.web.internal._thread_context
  href: com.microsoft.applicationinsights.web.internal._thread_context.yml
  langs:
  - java
  name: remove()
  fullName: static void com.microsoft.applicationinsights.web.internal.ThreadContext.remove()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
    startLine: 37
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public static void remove()
- uid: com.microsoft.applicationinsights.web.internal._thread_context.setRequestTelemetryContext(RequestTelemetryContext)
  id: setRequestTelemetryContext(RequestTelemetryContext)
  parent: com.microsoft.applicationinsights.web.internal._thread_context
  href: com.microsoft.applicationinsights.web.internal._thread_context.yml
  langs:
  - java
  name: setRequestTelemetryContext(RequestTelemetryContext telemetryContext)
  fullName: static void com.microsoft.applicationinsights.web.internal.ThreadContext.setRequestTelemetryContext(RequestTelemetryContext telemetryContext)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
    startLine: 29
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public static void setRequestTelemetryContext(RequestTelemetryContext telemetryContext)
    parameters:
    - id: telemetryContext
      type: com.microsoft.applicationinsights.web.internal._request_telemetry_context
references:
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  name: RequestTelemetryContext
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class RequestTelemetryContext
