items:
- uid: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element
  id: _context_initializers_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.getAdds()
  - com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.setAdds(ArrayList<AddTypeXmlElement>)
  href: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.yml
  langs:
  - java
  name: ContextInitializersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ContextInitializersXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ContextInitializersXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ContextInitializersXmlElement.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class ContextInitializersXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.getAdds()
  id: getAdds()
  parent: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element
  href: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.yml
  langs:
  - java
  name: getAdds()
  fullName: ArrayList<AddTypeXmlElement> com.microsoft.applicationinsights.internal.config.ContextInitializersXmlElement.getAdds()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ContextInitializersXmlElement.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<AddTypeXmlElement> getAdds()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._add_type_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.setAdds(ArrayList<AddTypeXmlElement>)
  id: setAdds(ArrayList<AddTypeXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element
  href: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.yml
  langs:
  - java
  name: setAdds(ArrayList<AddTypeXmlElement> adds)
  fullName: void com.microsoft.applicationinsights.internal.config.ContextInitializersXmlElement.setAdds(ArrayList<AddTypeXmlElement> adds)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ContextInitializersXmlElement.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setAdds(ArrayList<AddTypeXmlElement> adds)
    parameters:
    - id: adds
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._add_type_xml_elementa08ddfce
references:
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._add_type_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element
    name: AddTypeXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.AddTypeXmlElement
    href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  name: AddTypeXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.AddTypeXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AddTypeXmlElement
