items:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d
  id: _web_syn39c08b36af698d33adfd7054fe60983d
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  children:
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.onInitializeTelemetry(Telemetry)
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.yml
  langs:
  - java
  name: WebSyntheticRequestTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebSyntheticRequestTelemetryInitializer
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebSyntheticRequestTelemetryInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebSyntheticRequestTelemetryInitializer.java
    startLine: 36
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  summary: <p>Created by gupele on 8/17/2015. </p>
  syntax:
    content: public class WebSyntheticRequestTelemetryInitializer extends WebTelemetryInitializerBase
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_initializer
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  inheritedMembers:
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.initialize(Telemetry)
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_SOURCE_NAME()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_LOCATION()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_OPERATION_ID()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_RUN_ID()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_SESSION_ID()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_SOURCE()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_TEST_NAME()
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_USER_ID()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.onInitializeTelemetry(Telemetry)
  id: onInitializeTelemetry(Telemetry)
  parent: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.yml
  langs:
  - java
  name: onInitializeTelemetry(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.web.extensibility.initializers.WebSyntheticRequestTelemetryInitializer.onInitializeTelemetry(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebSyntheticRequestTelemetryInitializer.java
    startLine: 47
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  syntax:
    content: protected void onInitializeTelemetry(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
references:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.initialize(Telemetry)
  parent: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase.initialize(Telemetry telemetry)
  type: Method
  summary: <p>Initializes properties of the given telemetry. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_SOURCE_NAME()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_LOCATION()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_OPERATION_ID()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_RUN_ID()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_SESSION_ID()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_SOURCE()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_TEST_NAME()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.SYNTHETIC_TEST_USER_ID()
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  name: WebTelemetryInitializerBase
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase
  type: Class
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
