items:
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  id: _back_off_times_container_factory_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testEmptyString()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testExponentialDifferentCase()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testExponentialLowerCase()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testExponentialUpperCase()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testNullString()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testStaticDifferentCase()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testStaticLowerCase()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testStaticUpperCase()
  - com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testWrongString()
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: BackOffTimesContainerFactoryTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class BackOffTimesContainerFactoryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testEmptyString()
  id: testEmptyString()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testEmptyString()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testEmptyString()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testEmptyString()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testExponentialDifferentCase()
  id: testExponentialDifferentCase()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testExponentialDifferentCase()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testExponentialDifferentCase()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testExponentialDifferentCase()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testExponentialLowerCase()
  id: testExponentialLowerCase()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testExponentialLowerCase()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testExponentialLowerCase()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testExponentialLowerCase()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testExponentialUpperCase()
  id: testExponentialUpperCase()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testExponentialUpperCase()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testExponentialUpperCase()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 53
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testExponentialUpperCase()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testNullString()
  id: testNullString()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testNullString()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testNullString()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNullString()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testStaticDifferentCase()
  id: testStaticDifferentCase()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testStaticDifferentCase()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testStaticDifferentCase()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 77
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStaticDifferentCase()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testStaticLowerCase()
  id: testStaticLowerCase()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testStaticLowerCase()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testStaticLowerCase()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 65
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStaticLowerCase()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testStaticUpperCase()
  id: testStaticUpperCase()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testStaticUpperCase()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testStaticUpperCase()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStaticUpperCase()
- uid: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.testWrongString()
  id: testWrongString()
  parent: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test
  href: com.microsoft.applicationinsights.internal.channel.common._back_off_times_container_factory_test.yml
  langs:
  - java
  name: testWrongString()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.BackOffTimesContainerFactoryTest.testWrongString()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/BackOffTimesContainerFactoryTest.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testWrongString()
references: []
