items:
- uid: com.microsoft.applicationinsights.internal.schemav2._session
  id: _session
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._session.addToHashMap(HashMap<String, String>)
  - com.microsoft.applicationinsights.internal.schemav2._session.getId()
  - com.microsoft.applicationinsights.internal.schemav2._session.getIsFirst()
  - com.microsoft.applicationinsights.internal.schemav2._session.getIsNew()
  - com.microsoft.applicationinsights.internal.schemav2._session.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._session.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._session.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._session.Session()
  - com.microsoft.applicationinsights.internal.schemav2._session.setId(String)
  - com.microsoft.applicationinsights.internal.schemav2._session.setIsFirst(String)
  - com.microsoft.applicationinsights.internal.schemav2._session.setIsNew(String)
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: Session
  fullName: com.microsoft.applicationinsights.internal.schemav2.Session
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._session" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class Session implements JsonSerializable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
- uid: com.microsoft.applicationinsights.internal.schemav2._session.addToHashMap(HashMap<String, String>)
  id: addToHashMap(HashMap<String, String>)
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: addToHashMap(HashMap<String, String> map)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.addToHashMap(HashMap<String, String> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void addToHashMap(HashMap<String, String> map)
    parameters:
    - id: map
      type: 3970a053
- uid: com.microsoft.applicationinsights.internal.schemav2._session.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Session.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._session.getIsFirst()
  id: getIsFirst()
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: getIsFirst()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Session.getIsFirst()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getIsFirst()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._session.getIsNew()
  id: getIsNew()
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: getIsNew()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Session.getIsNew()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 74
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getIsNew()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._session.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 113
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._session.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 101
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  exceptions:
  - type: cbf33bbe
    description: <p>Might be thrown during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._session.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 107
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
- uid: com.microsoft.applicationinsights.internal.schemav2._session.Session()
  id: Session()
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: Session()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Session.Session()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 53
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public Session()
- uid: com.microsoft.applicationinsights.internal.schemav2._session.setId(String)
  id: setId(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: setId(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.setId(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 62
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setId(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._session.setIsFirst(String)
  id: setIsFirst(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: setIsFirst(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.setIsFirst(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setIsFirst(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._session.setIsNew(String)
  id: setIsNew(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._session
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  langs:
  - java
  name: setIsNew(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Session.setIsNew(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Session.java
    startLine: 78
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setIsNew(String value)
    parameters:
    - id: value
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 3970a053
  spec.java:
  - name: HashMap<String, String>
    fullName: HashMap<String, String>
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._session
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._session.yml
  name: Session
  fullName: com.microsoft.applicationinsights.internal.schemav2.Session
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._session" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
