items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httd139af086e505570c7167593f191fb91
  id: _application_gateway_frontend_httd139af086e505570c7167593f191fb91
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_httd139af086e505570c7167593f191fb91.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 57
  package: com.microsoft.azure.management.network
  summary: <p>The first stage of an application gateway HTTP listener. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(String)
  - com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(int)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb
  href: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.yml
  name: withFrontendPort(String name)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>.withFrontendPort(String name)
  type: Method
  summary: <p>Enables the listener to listen on the specified existing frontend port. </p>
  syntax:
    content: public WithAttach<ParentT> withFrontendPort(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing frontend port </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb
  href: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.yml
  name: withFrontendPort(int portNumber)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>.withFrontendPort(int portNumber)
  type: Method
  summary: <p>Enables the listener to listen on the specified port number, creating a new automatically-named port for it if needed, or associating it with an existing frontend port that is already configured to listen on this port number. </p>
  syntax:
    content: public WithAttach<ParentT> withFrontendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the frontend port to associate the listener with. </p>
  syntax:
    content: public interface WithFrontendPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._definition.yml
  name: ApplicationGatewayFrontendHttpListener.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway HTTP listener definition. </p>
  syntax:
    content: public interface Definition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
