items:
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  id: _performance_counter_jvm_section_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.getJvmXmlElements()
  - com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.getJvmXmlElementsMap()
  - com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.isEnabled()
  - com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.setEnabled(boolean)
  - com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.setJvmXmlElements(ArrayList<JvmXmlElement>)
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  langs:
  - java
  name: PerformanceCounterJvmSectionXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class PerformanceCounterJvmSectionXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.getJvmXmlElements()
  id: getJvmXmlElements()
  parent: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  langs:
  - java
  name: getJvmXmlElements()
  fullName: ArrayList<JvmXmlElement> com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement.getJvmXmlElements()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<JvmXmlElement> getJvmXmlElements()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._jvm_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.getJvmXmlElementsMap()
  id: getJvmXmlElementsMap()
  parent: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  langs:
  - java
  name: getJvmXmlElementsMap()
  fullName: HashMap<String, JvmXmlElement> com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement.getJvmXmlElementsMap()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public HashMap<String, JvmXmlElement> getJvmXmlElementsMap()
    return:
      type: 292b5718com.microsoft.applicationinsights.internal.config._jvm_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.isEnabled()
  id: isEnabled()
  parent: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  langs:
  - java
  name: isEnabled()
  fullName: boolean com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement.isEnabled()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public boolean isEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.setEnabled(boolean)
  id: setEnabled(boolean)
  parent: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  langs:
  - java
  name: setEnabled(boolean enabled)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement.setEnabled(boolean enabled)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setEnabled(boolean enabled)
    parameters:
    - id: enabled
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.setJvmXmlElements(ArrayList<JvmXmlElement>)
  id: setJvmXmlElements(ArrayList<JvmXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  langs:
  - java
  name: setJvmXmlElements(ArrayList<JvmXmlElement> jvmXmlElements)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement.setJvmXmlElements(ArrayList<JvmXmlElement> jvmXmlElements)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setJvmXmlElements(ArrayList<JvmXmlElement> jvmXmlElements)
    parameters:
    - id: jvmXmlElements
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._jvm_xml_elementa08ddfce
references:
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._jvm_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element
    name: JvmXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.JvmXmlElement
    href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 292b5718com.microsoft.applicationinsights.internal.config._jvm_xml_elementa08ddfce
  spec.java:
  - name: 'HashMap<String, '
    fullName: 'HashMap<String, '
  - uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element
    name: JvmXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.JvmXmlElement
    href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  name: JvmXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JvmXmlElement
  type: Class
  summary: <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class JvmXmlElement
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  name: WindowsPerformanceCounterXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterXmlElement
