items:
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  id: _server_disaster_recovery_configuration_inner
  parent: com.microsoft.azure.management.sql.implementation
  children:
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.autoFailover()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.failoverPolicy()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.partnerLogicalServerName()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.partnerServerId()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.role()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.type()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withAutoFailover(String)
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withFailoverPolicy(String)
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withPartnerLogicalServerName(String)
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withPartnerServerId(String)
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withRole(String)
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withType(String)
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: ServerDisasterRecoveryConfigurationInner
  fullName: com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 18
  package: com.microsoft.azure.management.sql.implementation
  summary: <p>Represents a server disaster recovery configuration. </p>
  syntax: &o1
    content: public class ServerDisasterRecoveryConfigurationInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.autoFailover()
  id: autoFailover()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: autoFailover()
  fullName: String com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.autoFailover()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 60
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the autoFailover value.</p>

    <p></p>
  syntax:
    content: public String autoFailover()
    return:
      type: "26831127"
      description: <p>the autoFailover value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.failoverPolicy()
  id: failoverPolicy()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: failoverPolicy()
  fullName: String com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.failoverPolicy()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 80
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the failoverPolicy value.</p>

    <p></p>
  syntax:
    content: public String failoverPolicy()
    return:
      type: "26831127"
      description: <p>the failoverPolicy value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.partnerLogicalServerName()
  id: partnerLogicalServerName()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: partnerLogicalServerName()
  fullName: String com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.partnerLogicalServerName()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 100
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the partnerLogicalServerName value.</p>

    <p></p>
  syntax:
    content: public String partnerLogicalServerName()
    return:
      type: "26831127"
      description: <p>the partnerLogicalServerName value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.partnerServerId()
  id: partnerServerId()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: partnerServerId()
  fullName: String com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.partnerServerId()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 120
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the partnerServerId value.</p>

    <p></p>
  syntax:
    content: public String partnerServerId()
    return:
      type: "26831127"
      description: <p>the partnerServerId value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.role()
  id: role()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: role()
  fullName: String com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.role()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 140
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the role value.</p>

    <p></p>
  syntax:
    content: public String role()
    return:
      type: "26831127"
      description: <p>the role value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.type()
  id: type()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: type()
  fullName: String com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.type()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 160
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public String type()
    return:
      type: "26831127"
      description: <p>the type value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withAutoFailover(String)
  id: withAutoFailover(String)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: withAutoFailover(String autoFailover)
  fullName: ServerDisasterRecoveryConfigurationInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.withAutoFailover(String autoFailover)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 70
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the autoFailover value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationInner withAutoFailover(String autoFailover)
    parameters:
    - id: autoFailover
      type: "26831127"
      description: <p>the autoFailover value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withFailoverPolicy(String)
  id: withFailoverPolicy(String)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: withFailoverPolicy(String failoverPolicy)
  fullName: ServerDisasterRecoveryConfigurationInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.withFailoverPolicy(String failoverPolicy)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 90
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the failoverPolicy value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationInner withFailoverPolicy(String failoverPolicy)
    parameters:
    - id: failoverPolicy
      type: "26831127"
      description: <p>the failoverPolicy value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withPartnerLogicalServerName(String)
  id: withPartnerLogicalServerName(String)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: withPartnerLogicalServerName(String partnerLogicalServerName)
  fullName: ServerDisasterRecoveryConfigurationInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.withPartnerLogicalServerName(String partnerLogicalServerName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 110
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the partnerLogicalServerName value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationInner withPartnerLogicalServerName(String partnerLogicalServerName)
    parameters:
    - id: partnerLogicalServerName
      type: "26831127"
      description: <p>the partnerLogicalServerName value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withPartnerServerId(String)
  id: withPartnerServerId(String)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: withPartnerServerId(String partnerServerId)
  fullName: ServerDisasterRecoveryConfigurationInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.withPartnerServerId(String partnerServerId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 130
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the partnerServerId value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationInner withPartnerServerId(String partnerServerId)
    parameters:
    - id: partnerServerId
      type: "26831127"
      description: <p>the partnerServerId value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withRole(String)
  id: withRole(String)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: withRole(String role)
  fullName: ServerDisasterRecoveryConfigurationInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.withRole(String role)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 150
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the role value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationInner withRole(String role)
    parameters:
    - id: role
      type: "26831127"
      description: <p>the role value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.withType(String)
  id: withType(String)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  langs:
  - java
  name: withType(String type)
  fullName: ServerDisasterRecoveryConfigurationInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner.withType(String type)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationInner.java
    startLine: 170
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the type value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationInner withType(String type)
    parameters:
    - id: type
      type: "26831127"
      description: <p>the type value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  parent: com.microsoft.azure.management.sql.implementation
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  name: ServerDisasterRecoveryConfigurationInner
  fullName: com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner
  type: Class
  summary: <p>Represents a server disaster recovery configuration. </p>
  syntax: *o1
