items:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers
  id: initializers
  children:
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_opec65b298f6d19b44fff0fd6008f6a1f75
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_operation_id_telemetry_initializer
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_session_telemetry_initializer
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_user_agent_telemetry_initializer
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer
  href: com.microsoft.applicationinsights.web.extensibility.initializers.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.extensibility.initializers
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebOperationIdTelemetryInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebOperationIdTelemetryInitializer.java
    startLine: 21
  syntax:
    content: namespace initializers
references:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_operation_id_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_operation_id_telemetry_initializer.yml
  name: WebOperationIdTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationIdTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class WebOperationIdTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_opec65b298f6d19b44fff0fd6008f6a1f75
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_opec65b298f6d19b44fff0fd6008f6a1f75.yml
  name: WebOperationNameTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationNameTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 2/17/2015. </p>
  syntax:
    content: public class WebOperationNameTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_session_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_session_telemetry_initializer.yml
  name: WebSessionTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebSessionTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 3/5/2015. </p>
  syntax:
    content: public class WebSessionTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.yml
  name: WebSyntheticRequestTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebSyntheticRequestTelemetryInitializer
  type: Class
  summary: <p>Created by gupele on 8/17/2015. </p>
  syntax:
    content: public class WebSyntheticRequestTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  name: WebTelemetryInitializerBase
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase
  type: Class
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class WebTelemetryInitializerBase implements TelemetryInitializer
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_agent_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_agent_telemetry_initializer.yml
  name: WebUserAgentTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebUserAgentTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 3/9/2015. </p>
  syntax:
    content: public class WebUserAgentTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer.yml
  name: WebUserTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 3/5/2015. </p>
  syntax:
    content: public class WebUserTelemetryInitializer extends WebTelemetryInitializerBase
