items:
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  id: _performance_counters_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getCollectionFrequencyInSec()
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getJmxXmlElements()
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getJvmSection()
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getPlugin()
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getWindowsPCs()
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.isUseBuiltIn()
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setCollectionFrequencyInSec(long)
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setJmxXmlElements(ArrayList<JmxXmlElement>)
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setJvmSection(PerformanceCounterJvmSectionXmlElement)
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setPlugin(String)
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setUseBuiltIn(boolean)
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setWindowsPCs(ArrayList<WindowsPerformanceCounterXmlElement>)
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: PerformanceCountersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class PerformanceCountersXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getCollectionFrequencyInSec()
  id: getCollectionFrequencyInSec()
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: getCollectionFrequencyInSec()
  fullName: long com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.getCollectionFrequencyInSec()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public long getCollectionFrequencyInSec()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getJmxXmlElements()
  id: getJmxXmlElements()
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: getJmxXmlElements()
  fullName: ArrayList<JmxXmlElement> com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.getJmxXmlElements()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<JmxXmlElement> getJmxXmlElements()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._jmx_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getJvmSection()
  id: getJvmSection()
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: getJvmSection()
  fullName: PerformanceCounterJvmSectionXmlElement com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.getJvmSection()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 77
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public PerformanceCounterJvmSectionXmlElement getJvmSection()
    return:
      type: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getPlugin()
  id: getPlugin()
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: getPlugin()
  fullName: String com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.getPlugin()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 86
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getPlugin()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.getWindowsPCs()
  id: getWindowsPCs()
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: getWindowsPCs()
  fullName: ArrayList<WindowsPerformanceCounterXmlElement> com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.getWindowsPCs()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<WindowsPerformanceCounterXmlElement> getWindowsPCs()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.isUseBuiltIn()
  id: isUseBuiltIn()
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: isUseBuiltIn()
  fullName: boolean com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.isUseBuiltIn()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public boolean isUseBuiltIn()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setCollectionFrequencyInSec(long)
  id: setCollectionFrequencyInSec(long)
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: setCollectionFrequencyInSec(long collectionFrequencyInSec)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.setCollectionFrequencyInSec(long collectionFrequencyInSec)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 73
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setCollectionFrequencyInSec(long collectionFrequencyInSec)
    parameters:
    - id: collectionFrequencyInSec
      type: 0364520f
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setJmxXmlElements(ArrayList<JmxXmlElement>)
  id: setJmxXmlElements(ArrayList<JmxXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: setJmxXmlElements(ArrayList<JmxXmlElement> jmxXmlElements)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.setJmxXmlElements(ArrayList<JmxXmlElement> jmxXmlElements)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setJmxXmlElements(ArrayList<JmxXmlElement> jmxXmlElements)
    parameters:
    - id: jmxXmlElements
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._jmx_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setJvmSection(PerformanceCounterJvmSectionXmlElement)
  id: setJvmSection(PerformanceCounterJvmSectionXmlElement)
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: setJvmSection(PerformanceCounterJvmSectionXmlElement jvmSection)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.setJvmSection(PerformanceCounterJvmSectionXmlElement jvmSection)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setJvmSection(PerformanceCounterJvmSectionXmlElement jvmSection)
    parameters:
    - id: jvmSection
      type: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setPlugin(String)
  id: setPlugin(String)
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: setPlugin(String plugin)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.setPlugin(String plugin)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setPlugin(String plugin)
    parameters:
    - id: plugin
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setUseBuiltIn(boolean)
  id: setUseBuiltIn(boolean)
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: setUseBuiltIn(boolean useBuiltIn)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.setUseBuiltIn(boolean useBuiltIn)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setUseBuiltIn(boolean useBuiltIn)
    parameters:
    - id: useBuiltIn
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.setWindowsPCs(ArrayList<WindowsPerformanceCounterXmlElement>)
  id: setWindowsPCs(ArrayList<WindowsPerformanceCounterXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  langs:
  - java
  name: setWindowsPCs(ArrayList<WindowsPerformanceCounterXmlElement> windowsPCs)
  fullName: void com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement.setWindowsPCs(ArrayList<WindowsPerformanceCounterXmlElement> windowsPCs)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setWindowsPCs(ArrayList<WindowsPerformanceCounterXmlElement> windowsPCs)
    parameters:
    - id: windowsPCs
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_elementa08ddfce
references:
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._jmx_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
    name: JmxXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
    href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
    name: WindowsPerformanceCounterXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement
    href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  name: PerformanceCounterJvmSectionXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement
  type: Class
  summary: <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class PerformanceCounterJvmSectionXmlElement
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  name: JmxXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxXmlElement
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  name: WindowsPerformanceCounterXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterXmlElement
