items:
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils
  id: _local_strings_utils
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._local_strings_utils.generateRandomId(boolean)
  - com.microsoft.applicationinsights.internal.util._local_strings_utils.generateRandomIntegerId()
  - com.microsoft.applicationinsights.internal.util._local_strings_utils.getDateFormatter()
  - com.microsoft.applicationinsights.internal.util._local_strings_utils.isNullOrEmpty(String)
  - com.microsoft.applicationinsights.internal.util._local_strings_utils.populateRequiredStringWithNullValue(String,String,String)
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  langs:
  - java
  name: LocalStringsUtils
  fullName: com.microsoft.applicationinsights.internal.util.LocalStringsUtils
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public class LocalStringsUtils
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils.generateRandomId(boolean)
  id: generateRandomId(boolean)
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  langs:
  - java
  name: generateRandomId(boolean removeDashes)
  fullName: static String com.microsoft.applicationinsights.internal.util.LocalStringsUtils.generateRandomId(boolean removeDashes)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String generateRandomId(boolean removeDashes)
    parameters:
    - id: removeDashes
      type: 4fc6e284
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils.generateRandomIntegerId()
  id: generateRandomIntegerId()
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  langs:
  - java
  name: generateRandomIntegerId()
  fullName: static String com.microsoft.applicationinsights.internal.util.LocalStringsUtils.generateRandomIntegerId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String generateRandomIntegerId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils.getDateFormatter()
  id: getDateFormatter()
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  langs:
  - java
  name: getDateFormatter()
  fullName: static DateFormat com.microsoft.applicationinsights.internal.util.LocalStringsUtils.getDateFormatter()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
    startLine: 62
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static DateFormat getDateFormatter()
    return:
      type: 92617a0f
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils.isNullOrEmpty(String)
  id: isNullOrEmpty(String)
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  langs:
  - java
  name: isNullOrEmpty(String value)
  fullName: static boolean com.microsoft.applicationinsights.internal.util.LocalStringsUtils.isNullOrEmpty(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Determine whether a string is null or empty. </p>
  syntax:
    content: public static boolean isNullOrEmpty(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>The string value </p>
    return:
      type: 4fc6e284
      description: <p>True if the string is either null or empty. </p>
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils.populateRequiredStringWithNullValue(String,String,String)
  id: populateRequiredStringWithNullValue(String,String,String)
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  langs:
  - java
  name: populateRequiredStringWithNullValue(String value, String parameterName, String telemetryType)
  fullName: static String com.microsoft.applicationinsights.internal.util.LocalStringsUtils.populateRequiredStringWithNullValue(String value, String parameterName, String telemetryType)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String populateRequiredStringWithNullValue(String value, String parameterName, String telemetryType)
    parameters:
    - id: value
      type: "26831127"
    - id: parameterName
      type: "26831127"
    - id: telemetryType
      type: "26831127"
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 92617a0f
  spec.java:
  - name: DateFormat
    fullName: DateFormat
