items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx
  id: jmx
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.agent.jmx
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
    startLine: 21
  syntax:
    content: namespace jmx
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.yml
  name: JmxConnectorLoader
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorLoader
  type: Class
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JmxConnectorLoader
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  name: JmxConnectorMXBean
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean
  type: Interface
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public interface JmxConnectorMXBean
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean_impl.yml
  name: JmxConnectorMXBeanImpl
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBeanImpl
  type: Class
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JmxConnectorMXBeanImpl implements JmxConnectorMXBean
