items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
  id: _class_to_method_transformation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data.yml
  langs:
  - java
  name: ClassToMethodTransformationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassToMethodTransformationData
  type: Interface
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ClassToMethodTransformationData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ClassToMethodTransformationData.java
    startLine: 28
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: >-
    <p>A marker to allow Class Visitors to pass data to Method Visitors</p>

    <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface ClassToMethodTransformationData
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_to_method_transformation_data
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  name: PreparedStatementMetaData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementMetaData
