items:
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  id: _active_transmission_loader_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testNegativeNumberOfThreads()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testNullDispatcher()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testNullFileSystem()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testOneFileOnDiskAfterLoaderStarted()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testOneFileOnDiskBeforeLoaderStarted()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testTooManyThreads()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testTwoFilesOnDiskAfterLoaderStarted()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testTwoFilesOnDiskBeforeLoaderStarted()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testZeroThreads()
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: ActiveTransmissionLoaderTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class ActiveTransmissionLoaderTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testNegativeNumberOfThreads()
  id: testNegativeNumberOfThreads()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testNegativeNumberOfThreads()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testNegativeNumberOfThreads()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNegativeNumberOfThreads()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testNullDispatcher()
  id: testNullDispatcher()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testNullDispatcher()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testNullDispatcher()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNullDispatcher()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testNullFileSystem()
  id: testNullFileSystem()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testNullFileSystem()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testNullFileSystem()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNullFileSystem()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testOneFileOnDiskAfterLoaderStarted()
  id: testOneFileOnDiskAfterLoaderStarted()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testOneFileOnDiskAfterLoaderStarted()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testOneFileOnDiskAfterLoaderStarted()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 76
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testOneFileOnDiskAfterLoaderStarted()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testOneFileOnDiskBeforeLoaderStarted()
  id: testOneFileOnDiskBeforeLoaderStarted()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testOneFileOnDiskBeforeLoaderStarted()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testOneFileOnDiskBeforeLoaderStarted()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testOneFileOnDiskBeforeLoaderStarted()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testTooManyThreads()
  id: testTooManyThreads()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testTooManyThreads()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testTooManyThreads()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 61
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testTooManyThreads()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testTwoFilesOnDiskAfterLoaderStarted()
  id: testTwoFilesOnDiskAfterLoaderStarted()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testTwoFilesOnDiskAfterLoaderStarted()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testTwoFilesOnDiskAfterLoaderStarted()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 81
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testTwoFilesOnDiskAfterLoaderStarted()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testTwoFilesOnDiskBeforeLoaderStarted()
  id: testTwoFilesOnDiskBeforeLoaderStarted()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testTwoFilesOnDiskBeforeLoaderStarted()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testTwoFilesOnDiskBeforeLoaderStarted()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testTwoFilesOnDiskBeforeLoaderStarted()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.testZeroThreads()
  id: testZeroThreads()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader_test.yml
  langs:
  - java
  name: testZeroThreads()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoaderTest.testZeroThreads()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testZeroThreads()
references:
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  name: TransmissionDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher
  type: Interface
  summary: >-
    <p>A dispatcher should know how and to whom to dispatch a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionDispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
  name: TransmissionPolicyStateFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher
  type: Interface
  summary: <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public interface TransmissionPolicyStateFetcher
