items:
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  id: _class_data_verifier_impl_tests
  parent: com.microsoft.applicationinsights.internal.reflect
  children:
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testClassDoesNotExist()
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testClassExists()
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testMethodExistingPublicMethod()
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testMethodNotExistingPublicMethod()
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.yml
  langs:
  - java
  name: ClassDataVerifierImplTests
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataVerifierImplTests
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifierImplTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifierImplTests.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public class ClassDataVerifierImplTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testClassDoesNotExist()
  id: testClassDoesNotExist()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.yml
  langs:
  - java
  name: testClassDoesNotExist()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataVerifierImplTests.testClassDoesNotExist()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifierImplTests.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testClassDoesNotExist()
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testClassExists()
  id: testClassExists()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.yml
  langs:
  - java
  name: testClassExists()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataVerifierImplTests.testClassExists()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifierImplTests.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testClassExists()
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testMethodExistingPublicMethod()
  id: testMethodExistingPublicMethod()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.yml
  langs:
  - java
  name: testMethodExistingPublicMethod()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataVerifierImplTests.testMethodExistingPublicMethod()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifierImplTests.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testMethodExistingPublicMethod()
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.testMethodNotExistingPublicMethod()
  id: testMethodNotExistingPublicMethod()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.yml
  langs:
  - java
  name: testMethodNotExistingPublicMethod()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataVerifierImplTests.testMethodNotExistingPublicMethod()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifierImplTests.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testMethodNotExistingPublicMethod()
references: []
