items:
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector
  id: _agent_connector
  parent: com.microsoft.applicationinsights.internal.agent
  children:
  - com.microsoft.applicationinsights.internal.agent._agent_connector.register(ClassLoader,String)
  - com.microsoft.applicationinsights.internal.agent._agent_connector.registerSelf()
  href: com.microsoft.applicationinsights.internal.agent._agent_connector.yml
  langs:
  - java
  name: AgentConnector
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.agent
  summary: >-
    <p>The class is responsible for connecting the Agent and register there for future calls</p>

    <p>Created by gupele on 5/7/2015. </p>
  syntax:
    content: public enum AgentConnector
  inheritance:
  - java.lang.Object
  - java.lang.Enum<AgentConnector>
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.agent._agent_connector_1a9b4d92bf1a41a8b7fd08d72d7f2c3620
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector.register(ClassLoader,String)
  id: register(ClassLoader,String)
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector
  href: com.microsoft.applicationinsights.internal.agent._agent_connector.yml
  langs:
  - java
  name: register(ClassLoader classLoader, String name)
  fullName: synchronized RegistrationResult com.microsoft.applicationinsights.internal.agent.AgentConnector.register(ClassLoader classLoader, String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 73
  package: com.microsoft.applicationinsights.internal.agent
  summary: >-
    <p>Registers the caller, and returning a key to represent that data. The method should not throw!</p>

    <p>The method is basically delegating the call to the relevant Agent class.</p>

    <p></p>
  syntax:
    content: public synchronized RegistrationResult register(ClassLoader classLoader, String name)
    parameters:
    - id: classLoader
      type: 5d46207c
      description: <p>The class loader that is associated with the caller. </p>
    - id: name
      type: "26831127"
      description: <p>The name that is associated with the caller </p>
    return:
      type: e58a2131
      description: <p>The key that will represent the caller, null if the registration failed. </p>
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector.registerSelf()
  id: registerSelf()
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector
  href: com.microsoft.applicationinsights.internal.agent._agent_connector.yml
  langs:
  - java
  name: registerSelf()
  fullName: synchronized boolean com.microsoft.applicationinsights.internal.agent.AgentConnector.registerSelf()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 107
  package: com.microsoft.applicationinsights.internal.agent
  summary: >-
    <p>Registers the caller, and returning a key to represent that data. The method should not throw!</p>

    <p>The method is basically delegating the call to the relevant Agent class. </p>
  syntax:
    content: public synchronized boolean registerSelf()
    return:
      type: 85b427c6
      description: <p>A boolean value representing the agent registration </p>
references:
- uid: 5d46207c
  spec.java:
  - name: ClassLoader
    fullName: ClassLoader
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: e58a2131
  spec.java:
  - name: synchronized RegistrationResult
    fullName: synchronized RegistrationResult
- uid: 85b427c6
  spec.java:
  - name: synchronized boolean
    fullName: synchronized boolean
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector_1a9b4d92bf1a41a8b7fd08d72d7f2c3620
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  parent: com.microsoft.applicationinsights.internal.agent
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.yml
  name: AgentConnector.RegistrationType
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationType
  type: Enum
  syntax:
    content: public enum RegistrationType
