items:
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  id: _page_view_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  children:
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testProcessNotPageViewTelemetry()
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testProcessWithNull()
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetBadDuration()
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetDuration()
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetNotNeededNames()
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetNotNeededUrls()
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: PageViewTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.processor
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class PageViewTelemetryFilterTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testProcessNotPageViewTelemetry()
  id: testProcessNotPageViewTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: testProcessNotPageViewTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest.testProcessNotPageViewTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testProcessNotPageViewTelemetry()
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testProcessWithNull()
  id: testProcessWithNull()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: testProcessWithNull()
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest.testProcessWithNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testProcessWithNull()
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetBadDuration()
  id: testSetBadDuration()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: testSetBadDuration()
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest.testSetBadDuration()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 112
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testSetBadDuration()
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetDuration()
  id: testSetDuration()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: testSetDuration()
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest.testSetDuration()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 92
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testSetDuration()
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetNotNeededNames()
  id: testSetNotNeededNames()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: testSetNotNeededNames()
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest.testSetNotNeededNames()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testSetNotNeededNames()
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.testSetNotNeededUrls()
  id: testSetNotNeededUrls()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter_test.yml
  langs:
  - java
  name: testSetNotNeededUrls()
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilterTest.testSetNotNeededUrls()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilterTest.java
    startLine: 65
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testSetNotNeededUrls()
references: []
