items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  id: _transmission_network_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.create(String,TransmissionPolicyManager)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.create(TransmissionPolicyManager)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.send(Transmission)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.setTransmissionDispatcher(TransmissionDispatcher)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  langs:
  - java
  name: TransmissionNetworkOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The class is responsible for the actual sending of <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>The class uses Apache's HttpClient framework for that.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax: &o1
    content: public class TransmissionNetworkOutput implements TransmissionOutput
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.channel._transmission_output
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.create(String,TransmissionPolicyManager)
  id: create(String,TransmissionPolicyManager)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  langs:
  - java
  name: create(String endpoint, TransmissionPolicyManager transmissionPolicyManager)
  fullName: static TransmissionNetworkOutput com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.create(String endpoint, TransmissionPolicyManager transmissionPolicyManager)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public static TransmissionNetworkOutput create(String endpoint, TransmissionPolicyManager transmissionPolicyManager)
    parameters:
    - id: endpoint
      type: "26831127"
    - id: transmissionPolicyManager
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
    return:
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.create(TransmissionPolicyManager)
  id: create(TransmissionPolicyManager)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  langs:
  - java
  name: create(TransmissionPolicyManager transmissionPolicyManager)
  fullName: static TransmissionNetworkOutput com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.create(TransmissionPolicyManager transmissionPolicyManager)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
    startLine: 78
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public static TransmissionNetworkOutput create(TransmissionPolicyManager transmissionPolicyManager)
    parameters:
    - id: transmissionPolicyManager
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
    return:
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.send(Transmission)
  id: send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  langs:
  - java
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(Transmission transmission)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
    startLine: 126
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Tries to send a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> The thread that calls that method might be suspended if there is a throttling issues, in any case the thread that enters this method is responsive for 'stop' request that might be issued by the application. </p>
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
      description: <p>The data to send </p>
    return:
      type: 4fc6e284
      description: <p>True when done. </p>
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.setTransmissionDispatcher(TransmissionDispatcher)
  id: setTransmissionDispatcher(TransmissionDispatcher)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  langs:
  - java
  name: setTransmissionDispatcher(TransmissionDispatcher transmissionDispatcher)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.setTransmissionDispatcher(TransmissionDispatcher transmissionDispatcher)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
    startLine: 99
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void setTransmissionDispatcher(TransmissionDispatcher transmissionDispatcher)
    parameters:
    - id: transmissionDispatcher
      type: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: synchronized void com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
    startLine: 109
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Stops all threads from sending data. </p>
  syntax:
    content: public synchronized void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>The timeout to wait, which is not relevant here. </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The time unit, which is not relevant in this method. </p>
    return:
      type: 5c0b90ca
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: 5c0b90ca
  spec.java:
  - name: synchronized void
    fullName: synchronized void
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: TransmissionOutput
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionOutput
  type: Interface
  summary: >-
    <p>Defines the interface of classes that get a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and can 'send' it.</p>

    <p>Concrete classes can 'send' the data to remote server, to disk, database etc.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  name: TransmissionDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher
  type: Interface
  summary: >-
    <p>A dispatcher should know how and to whom to dispatch a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionDispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  name: TransmissionPolicyManager
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager
  type: Class
  summary: >-
    <p>This class is responsible for managing the transmission state.</p>

    <p>The class might be told to suspend transmission for the next 'X' seconds where the state is set to be one of the states defined in <ref refid="" kindref="compound">com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicy</ref></p>

    <p>The class will keep that state for the requested amount of time and will release it, i.e. reset to 'unblock' when the timeout expires.</p>

    <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public class TransmissionPolicyManager
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  name: TransmissionNetworkOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput
  type: Class
  summary: >-
    <p>The class is responsible for the actual sending of <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>The class uses Apache's HttpClient framework for that.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax: *o1
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TransmissionOutput.send(Transmission transmission)
  type: Method
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
