items:
- uid: com.microsoft.applicationinsights.agent.internal.common._string_utils
  id: _string_utils
  parent: com.microsoft.applicationinsights.agent.internal.common
  children:
  - com.microsoft.applicationinsights.agent.internal.common._string_utils.isNullOrEmpty(String)
  href: com.microsoft.applicationinsights.agent.internal.common._string_utils.yml
  langs:
  - java
  name: StringUtils
  fullName: com.microsoft.applicationinsights.agent.internal.common.StringUtils
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/common/StringUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/common/StringUtils.java
    startLine: 26
  package: com.microsoft.applicationinsights.agent.internal.common
  summary: <p>Created by gupele on 5/31/2015. </p>
  syntax:
    content: public class StringUtils
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.common._string_utils.isNullOrEmpty(String)
  id: isNullOrEmpty(String)
  parent: com.microsoft.applicationinsights.agent.internal.common._string_utils
  href: com.microsoft.applicationinsights.agent.internal.common._string_utils.yml
  langs:
  - java
  name: isNullOrEmpty(String string)
  fullName: static boolean com.microsoft.applicationinsights.agent.internal.common.StringUtils.isNullOrEmpty(String string)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/common/StringUtils.java
    startLine: 27
  package: com.microsoft.applicationinsights.agent.internal.common
  syntax:
    content: public static boolean isNullOrEmpty(String string)
    parameters:
    - id: string
      type: "26831127"
    return:
      type: 4fc6e284
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
