items:
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  id: _application_insights_log_event
  parent: com.microsoft.applicationinsights.log4j.v2.internal
  children:
  - com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.ApplicationInsightsLogEvent(LogEvent)
  - com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getCustomParameters()
  - com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getException()
  - com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getMessage()
  - com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getNormalizedSeverityLevel()
  - com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.isException()
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: ApplicationInsightsLogEvent
  fullName: com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent
  type: Class
  source:
    remote: &o0
      path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 31
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public class ApplicationInsightsLogEvent extends ApplicationInsightsEvent
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.common._application_insights_event
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.common._application_insights_event.addLogEventProperty(String,String,Map<String, String>)
  - com.microsoft.applicationinsights.internal.common._application_insights_event.getFormattedDate(long)
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.ApplicationInsightsLogEvent(LogEvent)
  id: ApplicationInsightsLogEvent(LogEvent)
  parent: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: ApplicationInsightsLogEvent(LogEvent logEvent)
  fullName: com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent.ApplicationInsightsLogEvent(LogEvent logEvent)
  type: Constructor
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 35
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public ApplicationInsightsLogEvent(LogEvent logEvent)
    parameters:
    - id: logEvent
      type: 93a18e44
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getCustomParameters()
  id: getCustomParameters()
  parent: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: getCustomParameters()
  fullName: Map<String, String> com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent.getCustomParameters()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 66
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public Map<String, String> getCustomParameters()
    return:
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getException()
  id: getException()
  parent: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: getException()
  fullName: Exception com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent.getException()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 54
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public Exception getException()
    return:
      type: 8a99d4b0
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getMessage()
  id: getMessage()
  parent: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: getMessage()
  fullName: String com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent.getMessage()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 40
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public String getMessage()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.getNormalizedSeverityLevel()
  id: getNormalizedSeverityLevel()
  parent: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: getNormalizedSeverityLevel()
  fullName: SeverityLevel com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent.getNormalizedSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 97
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public SeverityLevel getNormalizedSeverityLevel()
    return:
      type: com.microsoft.applicationinsights.telemetry._severity_level
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.isException()
  id: isException()
  parent: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  langs:
  - java
  name: isException()
  fullName: boolean com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent.isException()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
    startLine: 49
  package: com.microsoft.applicationinsights.log4j.v2.internal
  syntax:
    content: public boolean isException()
    return:
      type: 4fc6e284
references:
- uid: 93a18e44
  spec.java:
  - name: LogEvent
    fullName: LogEvent
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 8a99d4b0
  spec.java:
  - name: Exception
    fullName: Exception
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.addLogEventProperty(String,String,Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  name: addLogEventProperty(String key, String value, Map<String, String> metaData)
  fullName: static void com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.addLogEventProperty(String key, String value, Map<String, String> metaData)
  type: Method
  syntax:
    content: protected static void addLogEventProperty(String key, String value, Map<String, String> metaData)
    parameters:
    - id: key
      type: "26831127"
    - id: value
      type: "26831127"
    - id: metaData
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.getFormattedDate(long)
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  name: getFormattedDate(long dateInMilliseconds)
  fullName: static String com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.getFormattedDate(long dateInMilliseconds)
  type: Method
  syntax:
    content: protected static String getFormattedDate(long dateInMilliseconds)
    parameters:
    - id: dateInMilliseconds
      type: 0364520f
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  name: ApplicationInsightsEvent
  fullName: com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent
  type: Class
  summary: <p>Interface for </p>
  syntax:
    content: public class ApplicationInsightsEvent
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
