items:
- uid: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter
  id: _telemetry_event_filter
  parent: com.microsoft.applicationinsights.internal.processor
  children:
  - com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.process(Telemetry)
  - com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.setNotNeededNames(String)
  - com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.TelemetryEventFilter()
  href: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.yml
  langs:
  - java
  name: TelemetryEventFilter
  fullName: com.microsoft.applicationinsights.internal.processor.TelemetryEventFilter
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.processor
  summary: >-
    <p>The class will filter out Event Telemetries with unneeded values</p>

    <p>Illegal value will prevent from the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryEventFilter implements TelemetryProcessor
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_processor
- uid: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.process(Telemetry)
  id: process(Telemetry)
  parent: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter
  href: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.yml
  langs:
  - java
  name: process(Telemetry telemetry)
  fullName: boolean com.microsoft.applicationinsights.internal.processor.TelemetryEventFilter.process(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public boolean process(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
    return:
      type: 4fc6e284
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_processor.process(Telemetry)
- uid: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.setNotNeededNames(String)
  id: setNotNeededNames(String)
  parent: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter
  href: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.yml
  langs:
  - java
  name: setNotNeededNames(String notNeededNames)
  fullName: void com.microsoft.applicationinsights.internal.processor.TelemetryEventFilter.setNotNeededNames(String notNeededNames)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void setNotNeededNames(String notNeededNames)
    parameters:
    - id: notNeededNames
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.TelemetryEventFilter()
  id: TelemetryEventFilter()
  parent: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter
  href: com.microsoft.applicationinsights.internal.processor._telemetry_event_filter.yml
  langs:
  - java
  name: TelemetryEventFilter()
  fullName: com.microsoft.applicationinsights.internal.processor.TelemetryEventFilter.TelemetryEventFilter()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public TelemetryEventFilter()
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: TelemetryProcessor
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryProcessor
  type: Interface
  summary: "<p>The method gets a <ref refid=\"\" kindref=\"compound\">Telemetry</ref> instance that is ready to be sent. This is your chance to approve or deny it. Returning 'false' means that the Telemetry will not be sent while 'true' means you approve it.</p>\r\n<p>The Telemetry might go through other filters though, that might deny its sending.</p>\r\n<p>To enable this processor you need to add it in the ApplicationInsights.xml like this:</p>\r\n<p>\r\n  <preformatted>\r\n    <programlisting>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Processor<sp></sp>type=\"full.path.to.Filter\"&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Add<sp></sp>name=\"Property\"<sp></sp>value=\"stringValue\"/&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/Processor&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;/TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n    </programlisting> \r\n*</preformatted>\r\n</p>\r\n<p>Note that the class defines a property named 'Property' which is configured too. Every property that you wish to configure needs to have a 'setX' public method like 'setProperty' in this example <bold>Exceptions thrown from the 'setX' methods will be caught by the framework that will ignore the filter</bold></p>\r\n<p>Created by gupele on 7/26/2016. </p>"
  syntax:
    content: public interface TelemetryProcessor
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor.process(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_processor
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: process(Telemetry telemetry)
  fullName: boolean com.microsoft.applicationinsights.extensibility.TelemetryProcessor.process(Telemetry telemetry)
  type: Method
  syntax:
    content: public boolean process(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
