items:
- uid: com.microsoft.applicationinsights.telemetry
  id: telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._base_telemetry
  - com.microsoft.applicationinsights.telemetry._base_telemetry_test
  - com.microsoft.applicationinsights.telemetry._duration
  - com.microsoft.applicationinsights.telemetry._duration_test
  - com.microsoft.applicationinsights.telemetry._event_telemetry
  - com.microsoft.applicationinsights.telemetry._event_telemetry_test
  - com.microsoft.applicationinsights.telemetry._exception_handled_at
  - com.microsoft.applicationinsights.telemetry._exception_telemetry
  - com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  - com.microsoft.applicationinsights.telemetry._http_request_telemetry_test
  - com.microsoft.applicationinsights.telemetry._json_serializable
  - com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  - com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer_test
  - com.microsoft.applicationinsights.telemetry._metric_telemetry
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  - com.microsoft.applicationinsights.telemetry._request_telemetry
  - com.microsoft.applicationinsights.telemetry._sanitizer_test
  - com.microsoft.applicationinsights.telemetry._session_state
  - com.microsoft.applicationinsights.telemetry._session_state_telemetry
  - com.microsoft.applicationinsights.telemetry._session_state_telemetry_test
  - com.microsoft.applicationinsights.telemetry._severity_level
  - com.microsoft.applicationinsights.telemetry._telemetry
  - com.microsoft.applicationinsights.telemetry._telemetry_context
  - com.microsoft.applicationinsights.telemetry._telemetry_context_test
  - com.microsoft.applicationinsights.telemetry._trace_telemetry
  - com.microsoft.applicationinsights.telemetry._trace_telemetry_test
  href: com.microsoft.applicationinsights.telemetry.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.telemetry
  fullName: com.microsoft.applicationinsights.telemetry
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java
    startLine: 21
  syntax:
    content: namespace telemetry
references:
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: BaseTelemetry<T>
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetry<T>
  type: Class
  summary: <p>Superclass for all telemetry data classes. </p>
  syntax:
    content: public class BaseTelemetry<T extends SendableData> implements Telemetry
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  name: BaseTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetryTest
  type: Class
  syntax:
    content: public class BaseTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._duration
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._duration.yml
  name: Duration
  fullName: com.microsoft.applicationinsights.telemetry.Duration
  type: Class
  summary: >-
    <p>This class lets its users to define an interval of time which can be defined in terms of days, hours, minutes, seconds and milliseconds.</p>

    <p>It has various constructors to let the user easily define an interval of time. </p>
  syntax:
    content: public class Duration
- uid: com.microsoft.applicationinsights.telemetry._duration_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._duration_test.yml
  name: DurationTest
  fullName: com.microsoft.applicationinsights.telemetry.DurationTest
  type: Class
  syntax:
    content: public class DurationTest
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  name: EventTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track events. </p>
  syntax:
    content: public class EventTelemetry extends BaseTelemetry<EventData>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry_test.yml
  name: EventTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetryTest
  type: Class
  syntax:
    content: public class EventTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._exception_handled_at
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_handled_at.yml
  name: ExceptionHandledAt
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionHandledAt
  type: Enum
  summary: <p>This enumeration is used by <xref href="com.microsoft.applicationinsights.telemetry._exception_telemetry" data-throw-if-not-resolved="false"></xref> to identify if and where exception was handled. </p>
  syntax:
    content: public enum ExceptionHandledAt
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  name: ExceptionTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track exceptions. </p>
  syntax:
    content: public class ExceptionTelemetry extends BaseTelemetry<ExceptionData>
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry_test.yml
  name: ExceptionTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionTelemetryTest
  type: Class
  syntax:
    content: public class ExceptionTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.yml
  name: HttpRequestTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.HttpRequestTelemetryTest
  type: Class
  syntax:
    content: public class HttpRequestTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer_test.yml
  name: JsonTelemetryDataSerializerTest
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializerTest
  type: Class
  syntax:
    content: public class JsonTelemetryDataSerializerTest
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry.yml
  name: MetricTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.MetricTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track metrics. </p>
  syntax:
    content: public class MetricTelemetry extends BaseTelemetry<MetricData>
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  name: MetricTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.MetricTelemetryTest
  type: Class
  syntax:
    content: public class MetricTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry.yml
  name: PageViewTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.PageViewTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track page views.</p>

    <p>You can send information about pages viewed by your application to Application Insights by passing an instance of this class to the 'trackPageView' method of the <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public class PageViewTelemetry extends BaseTelemetry<PageViewData>
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  name: PageViewTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest
  type: Class
  syntax:
    content: public class PageViewTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry.yml
  name: PerformanceCounterTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetry
  type: Class
  summary: <p>The class that represents information about performance counters. </p>
  syntax:
    content: public class PerformanceCounterTelemetry extends BaseTelemetry<PerformanceCounterData>
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  name: PerformanceCounterTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest
  type: Class
  syntax:
    content: public class PerformanceCounterTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry.yml
  name: RemoteDependencyTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetry
  type: Class
  summary: <p>The class that represents information about collected RDD. </p>
  syntax:
    content: public class RemoteDependencyTelemetry extends BaseTelemetry<RemoteDependencyData>
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  name: RemoteDependencyTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest
  type: Class
  syntax:
    content: public class RemoteDependencyTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._request_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._request_telemetry.yml
  name: RequestTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.RequestTelemetry
  type: Class
  summary: >-
    <p>Encapsulates information about a web request handled by the application.</p>

    <p>You can send information about requests processed by your web application to Application Insights by passing an instance of this class to the 'trackRequest' method of the <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public class RequestTelemetry extends BaseTelemetry<RequestData>
- uid: com.microsoft.applicationinsights.telemetry._sanitizer_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._sanitizer_test.yml
  name: SanitizerTest
  fullName: com.microsoft.applicationinsights.telemetry.SanitizerTest
  type: Class
  syntax:
    content: public class SanitizerTest
- uid: com.microsoft.applicationinsights.telemetry._session_state
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._session_state.yml
  name: SessionState
  fullName: com.microsoft.applicationinsights.telemetry.SessionState
  type: Enum
  summary: <p>Session states. </p>
  syntax:
    content: public enum SessionState
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry.yml
  name: SessionStateTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.SessionStateTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track user sessions. </p>
  syntax:
    content: public class SessionStateTelemetry extends BaseTelemetry<SessionStateData>
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.yml
  name: SessionStateTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.SessionStateTelemetryTest
  type: Class
  syntax:
    content: public class SessionStateTelemetryTest
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry_context.yml
  name: TelemetryContext
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContext
  type: Class
  summary: <p>Represents a context for sending telemetry to the Application Insights service. </p>
  syntax:
    content: public class TelemetryContext
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry_context_test.yml
  name: TelemetryContextTest
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContextTest
  type: Class
  syntax:
    content: public class TelemetryContextTest
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry.yml
  name: TraceTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.TraceTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used for log messages. </p>
  syntax:
    content: public class TraceTelemetry extends BaseTelemetry<MessageData>
- uid: com.microsoft.applicationinsights.telemetry._trace_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._trace_telemetry_test.yml
  name: TraceTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.TraceTelemetryTest
  type: Class
  syntax:
    content: public class TraceTelemetryTest
