items:
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  id: _page_view_telemetry_filter
  parent: com.microsoft.applicationinsights.internal.processor
  children:
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.PageViewTelemetryFilter()
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.process(Telemetry)
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.setDurationThresholdInMS(String)
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.setNotNeededNames(String)
  - com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.setNotNeededUrls(String)
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  langs:
  - java
  name: PageViewTelemetryFilter
  fullName: com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.processor
  summary: >-
    <p>The class can filter out PageViewTelemetries that have a duration which is less than a predefined value have URLs that has parts that are not needed, i.e. telemetries that will not be sent, based on configuration have unneeded page names i.e. telemetries that will not be sent, that were predefined in configuration</p>

    <p>Invalid values would prevent the filter from being used.</p>

    <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class PageViewTelemetryFilter implements TelemetryProcessor
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_processor
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.PageViewTelemetryFilter()
  id: PageViewTelemetryFilter()
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  langs:
  - java
  name: PageViewTelemetryFilter()
  fullName: com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter.PageViewTelemetryFilter()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
    startLine: 53
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public PageViewTelemetryFilter()
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.process(Telemetry)
  id: process(Telemetry)
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  langs:
  - java
  name: process(Telemetry telemetry)
  fullName: boolean com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter.process(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public boolean process(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
    return:
      type: 4fc6e284
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_processor.process(Telemetry)
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.setDurationThresholdInMS(String)
  id: setDurationThresholdInMS(String)
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  langs:
  - java
  name: setDurationThresholdInMS(String durationThresholdInMS)
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter.setDurationThresholdInMS(String durationThresholdInMS)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void setDurationThresholdInMS(String durationThresholdInMS)
    parameters:
    - id: durationThresholdInMS
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.setNotNeededNames(String)
  id: setNotNeededNames(String)
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  langs:
  - java
  name: setNotNeededNames(String notNeededNames)
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter.setNotNeededNames(String notNeededNames)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
    startLine: 101
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void setNotNeededNames(String notNeededNames)
    parameters:
    - id: notNeededNames
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.setNotNeededUrls(String)
  id: setNotNeededUrls(String)
  parent: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter
  href: com.microsoft.applicationinsights.internal.processor._page_view_telemetry_filter.yml
  langs:
  - java
  name: setNotNeededUrls(String notNeededUrls)
  fullName: void com.microsoft.applicationinsights.internal.processor.PageViewTelemetryFilter.setNotNeededUrls(String notNeededUrls)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
    startLine: 119
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void setNotNeededUrls(String notNeededUrls)
    parameters:
    - id: notNeededUrls
      type: "26831127"
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: TelemetryProcessor
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryProcessor
  type: Interface
  summary: "<p>The method gets a <ref refid=\"\" kindref=\"compound\">Telemetry</ref> instance that is ready to be sent. This is your chance to approve or deny it. Returning 'false' means that the Telemetry will not be sent while 'true' means you approve it.</p>\r\n<p>The Telemetry might go through other filters though, that might deny its sending.</p>\r\n<p>To enable this processor you need to add it in the ApplicationInsights.xml like this:</p>\r\n<p>\r\n  <preformatted>\r\n    <programlisting>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Processor<sp></sp>type=\"full.path.to.Filter\"&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Add<sp></sp>name=\"Property\"<sp></sp>value=\"stringValue\"/&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/Processor&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;/TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n    </programlisting> \r\n*</preformatted>\r\n</p>\r\n<p>Note that the class defines a property named 'Property' which is configured too. Every property that you wish to configure needs to have a 'setX' public method like 'setProperty' in this example <bold>Exceptions thrown from the 'setX' methods will be caught by the framework that will ignore the filter</bold></p>\r\n<p>Created by gupele on 7/26/2016. </p>"
  syntax:
    content: public interface TelemetryProcessor
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor.process(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_processor
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: process(Telemetry telemetry)
  fullName: boolean com.microsoft.applicationinsights.extensibility.TelemetryProcessor.process(Telemetry telemetry)
  type: Method
  syntax:
    content: public boolean process(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
