items:
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  id: _std_out_channel
  parent: com.microsoft.applicationinsights.internal.channel.stdout
  children:
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.flush()
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.isDeveloperMode()
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.send(Telemetry)
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.setDeveloperMode(boolean)
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.StdOutChannel()
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.StdOutChannel(Map<String, String>)
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: StdOutChannel
  fullName: com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.channel.stdout
  summary: <p>A telemetry channel routing information to stdout. </p>
  syntax:
    content: public class StdOutChannel implements TelemetryChannel
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.channel._telemetry_channel
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.flush()
  id: flush()
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: flush()
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.flush()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.channel.stdout
  summary: <p>Flushes the data that the channel might have internally. </p>
  syntax:
    content: public void flush()
  overridden: com.microsoft.applicationinsights.channel._telemetry_channel.flush()
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.isDeveloperMode()
  id: isDeveloperMode()
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: isDeveloperMode()
  fullName: boolean com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.isDeveloperMode()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.channel.stdout
  summary: <p>Gets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public boolean isDeveloperMode()
    return:
      type: 4fc6e284
      description: <p>The developer mode. </p>
  overridden: com.microsoft.applicationinsights.channel._telemetry_channel.isDeveloperMode()
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.send(Telemetry)
  id: send(Telemetry)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: send(Telemetry item)
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.send(Telemetry item)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.channel.stdout
  summary: <p>Sends a Telemetry instance through the channel. </p>
  syntax:
    content: public void send(Telemetry item)
    parameters:
    - id: item
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The Telemetry item to send. </p>
  overridden: com.microsoft.applicationinsights.channel._telemetry_channel.send(Telemetry)
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.setDeveloperMode(boolean)
  id: setDeveloperMode(boolean)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: setDeveloperMode(boolean value)
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.setDeveloperMode(boolean value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.channel.stdout
  summary: <p>Sets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public void setDeveloperMode(boolean value)
    parameters:
    - id: value
      type: 4fc6e284
      description: <p>True for applying develoer mode </p>
  overridden: com.microsoft.applicationinsights.channel._telemetry_channel.setDeveloperMode(boolean)
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.StdOutChannel()
  id: StdOutChannel()
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: StdOutChannel()
  fullName: com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.StdOutChannel()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.channel.stdout
  syntax:
    content: public StdOutChannel()
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.StdOutChannel(Map<String, String>)
  id: StdOutChannel(Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: StdOutChannel(Map<String, String> namesAndValues)
  fullName: com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.StdOutChannel(Map<String, String> namesAndValues)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.channel.stdout
  syntax:
    content: public StdOutChannel(Map<String, String> namesAndValues)
    parameters:
    - id: namesAndValues
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.channel.stdout
  summary: <p>Stops on going work </p>
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>Time to try and stop </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The units of the 'timeout' parameter </p>
  overridden: com.microsoft.applicationinsights.channel._telemetry_channel.stop(long,TimeUnit)
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.channel._telemetry_channel
  parent: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: TelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.TelemetryChannel
  type: Interface
  summary: <p>Represents a communication channel for sending telemetry to application insights. </p>
  syntax:
    content: public interface TelemetryChannel
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.isDeveloperMode()
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: isDeveloperMode()
  fullName: boolean com.microsoft.applicationinsights.channel.TelemetryChannel.isDeveloperMode()
  type: Method
  summary: <p>Gets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public boolean isDeveloperMode()
    return:
      type: 4fc6e284
      description: <p>The developer mode. </p>
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.setDeveloperMode(boolean)
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: setDeveloperMode(boolean value)
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.setDeveloperMode(boolean value)
  type: Method
  summary: <p>Sets value indicating whether this channel is in developer mode. </p>
  syntax:
    content: public void setDeveloperMode(boolean value)
    parameters:
    - id: value
      type: 4fc6e284
      description: <p>True for applying develoer mode </p>
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.send(Telemetry)
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: send(Telemetry item)
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.send(Telemetry item)
  type: Method
  summary: <p>Sends a Telemetry instance through the channel. </p>
  syntax:
    content: public void send(Telemetry item)
    parameters:
    - id: item
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The Telemetry item to send. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.stop(long timeout, TimeUnit timeUnit)
  type: Method
  summary: <p>Stops on going work </p>
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>Time to try and stop </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The units of the 'timeout' parameter </p>
- uid: com.microsoft.applicationinsights.channel._telemetry_channel.flush()
  parent: com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: flush()
  fullName: void com.microsoft.applicationinsights.channel.TelemetryChannel.flush()
  type: Method
  summary: <p>Flushes the data that the channel might have internally. </p>
  syntax:
    content: public void flush()
