items:
- uid: com.microsoft.azure.management.network._application_gateway_private_fronbaa3765a02c8b31fcbf30911238f0d8f
  id: _application_gateway_private_fronbaa3765a02c8b31fcbf30911238f0d8f
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_fronbaa3765a02c8b31fcbf30911238f0d8f.yml
  langs:
  - java
  name: ApplicationGatewayPrivateFrontend.UpdateDefinitionStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.UpdateDefinitionStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
    startLine: 99
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of private frontend definition stages applicable as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinitionStages
references: []
