items:
- uid: com.microsoft.applicationinsights.sample.plugins
  id: plugins
  children:
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test
  href: com.microsoft.applicationinsights.sample.plugins.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.sample.plugins
  fullName: com.microsoft.applicationinsights.sample.plugins
  type: Namespace
  source:
    remote:
      path: samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
    startLine: 21
  syntax:
    content: namespace plugins
references:
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  parent: com.microsoft.applicationinsights.sample.plugins
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.yml
  name: GitBuildInfoContextInitializer
  fullName: com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer
  type: Class
  summary: '<p>An initializer to fetch Git data from a properties file Note: the file with its full package name should appear in the ''ApplicationInsights.xml'': <programlisting><codeline><highlight class="normal">&lt;ContextInitializers&gt;</highlight></codeline><codeline><highlight class="normal"><sp></sp><sp></sp>&lt;Add<sp></sp>type="com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer"<sp></sp>/&gt;</highlight></codeline><codeline><highlight class="normal">&lt;/ContextInitializers&gt;</highlight></codeline></programlisting></p>'
  syntax:
    content: public class GitBuildInfoContextInitializer implements ContextInitializer
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test
  parent: com.microsoft.applicationinsights.sample.plugins
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer_test.yml
  name: GitBuildInfoContextInitializerTest
  fullName: com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializerTest
  type: Class
  syntax:
    content: public class GitBuildInfoContextInitializerTest
