items:
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test
  id: _gzip_telemetry_serializer_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testNoData()
  - com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testNull()
  - com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testSerializeOfOne()
  - com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testSerializeOfTen()
  - com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testSerializeOfTwo()
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.yml
  langs:
  - java
  name: GzipTelemetrySerializerTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializerTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class GzipTelemetrySerializerTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testNoData()
  id: testNoData()
  parent: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.yml
  langs:
  - java
  name: testNoData()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializerTest.testNoData()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
    startLine: 128
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNoData()
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testNull()
  id: testNull()
  parent: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.yml
  langs:
  - java
  name: testNull()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializerTest.testNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
    startLine: 122
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNull()
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testSerializeOfOne()
  id: testSerializeOfOne()
  parent: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.yml
  langs:
  - java
  name: testSerializeOfOne()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializerTest.testSerializeOfOne()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
    startLine: 134
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSerializeOfOne()
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testSerializeOfTen()
  id: testSerializeOfTen()
  parent: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.yml
  langs:
  - java
  name: testSerializeOfTen()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializerTest.testSerializeOfTen()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
    startLine: 144
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSerializeOfTen()
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.testSerializeOfTwo()
  id: testSerializeOfTwo()
  parent: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer_test.yml
  langs:
  - java
  name: testSerializeOfTwo()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializerTest.testSerializeOfTwo()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializerTest.java
    startLine: 139
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSerializeOfTwo()
references: []
