items:
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  id: _log_telemetry_client_proxy
  parent: com.microsoft.applicationinsights.internal.common
  children:
  - com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.getTelemetryClient()
  - com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.isInitialized()
  - com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.LogTelemetryClientProxy(String)
  - com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.LogTelemetryClientProxy(TelemetryClient,String)
  - com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.sendEvent(ApplicationInsightsEvent)
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  langs:
  - java
  name: LogTelemetryClientProxy
  fullName: com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy
  type: Class
  source:
    remote: &o0
      path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.common
  summary: <p>This class encapsulates all the common logic for sending AI telemetry. This class is used by all Appenders, Listeners etc and therefore keeping them without any logic. </p>
  syntax:
    content: public class LogTelemetryClientProxy implements TelemetryClientProxy
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.getTelemetryClient()
  id: getTelemetryClient()
  parent: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  langs:
  - java
  name: getTelemetryClient()
  fullName: TelemetryClient com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy.getTelemetryClient()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
    startLine: 114
  package: com.microsoft.applicationinsights.internal.common
  summary: >-
    <p>Gets the telemetry client.</p>

    <p></p>
  syntax:
    content: public TelemetryClient getTelemetryClient()
    return:
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>Telemetry client </p>
  overridden: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.getTelemetryClient()
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.isInitialized()
  id: isInitialized()
  parent: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  langs:
  - java
  name: isInitialized()
  fullName: boolean com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy.isInitialized()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
    startLine: 78
  package: com.microsoft.applicationinsights.internal.common
  summary: <p>Gets a value indicating whether the proxy has been initialized. </p>
  syntax:
    content: public boolean isInitialized()
    return:
      type: 4fc6e284
      description: <p>True if initialized, false otherwise. </p>
  overridden: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.isInitialized()
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.LogTelemetryClientProxy(String)
  id: LogTelemetryClientProxy(String)
  parent: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  langs:
  - java
  name: LogTelemetryClientProxy(String instrumentationKey)
  fullName: com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy.LogTelemetryClientProxy(String instrumentationKey)
  type: Constructor
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.common
  summary: <p>Constructs new telemetry client proxy instance. </p>
  syntax:
    content: public LogTelemetryClientProxy(String instrumentationKey)
    parameters:
    - id: instrumentationKey
      type: "26831127"
      description: <p>The instrumentation key for sending the events. </p>
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.LogTelemetryClientProxy(TelemetryClient,String)
  id: LogTelemetryClientProxy(TelemetryClient,String)
  parent: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  langs:
  - java
  name: LogTelemetryClientProxy(TelemetryClient telemetryClient, String instrumentationKey)
  fullName: com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy.LogTelemetryClientProxy(TelemetryClient telemetryClient, String instrumentationKey)
  type: Constructor
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.common
  summary: <p>Constructs new telemetry client proxy instance with the given client. </p>
  syntax:
    content: public LogTelemetryClientProxy(TelemetryClient telemetryClient, String instrumentationKey)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The telemetry client. </p>
    - id: instrumentationKey
      type: "26831127"
      description: <p>The instrumentation key. </p>
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.sendEvent(ApplicationInsightsEvent)
  id: sendEvent(ApplicationInsightsEvent)
  parent: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  langs:
  - java
  name: sendEvent(ApplicationInsightsEvent event)
  fullName: void com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy.sendEvent(ApplicationInsightsEvent event)
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java
    startLine: 87
  package: com.microsoft.applicationinsights.internal.common
  summary: >-
    <p>Sends the given event to AI.</p>

    <p></p>
  syntax:
    content: public void sendEvent(ApplicationInsightsEvent event)
    parameters:
    - id: event
      type: com.microsoft.applicationinsights.internal.common._application_insights_event
      description: <p>The event to send. </p>
  overridden: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.sendEvent(ApplicationInsightsEvent)
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.yml
  name: TelemetryClientProxy
  fullName: com.microsoft.applicationinsights.internal.common.TelemetryClientProxy
  type: Interface
  syntax:
    content: public interface TelemetryClientProxy
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
- uid: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.isInitialized()
  parent: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.yml
  name: isInitialized()
  fullName: boolean com.microsoft.applicationinsights.internal.common.TelemetryClientProxy.isInitialized()
  type: Method
  summary: <p>Gets a value indicating whether the proxy has been initialized. </p>
  syntax:
    content: public boolean isInitialized()
    return:
      type: 4fc6e284
      description: <p>True if initialized, false otherwise. </p>
- uid: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.sendEvent(ApplicationInsightsEvent)
  parent: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.yml
  name: sendEvent(ApplicationInsightsEvent event)
  fullName: void com.microsoft.applicationinsights.internal.common.TelemetryClientProxy.sendEvent(ApplicationInsightsEvent event)
  type: Method
  summary: >-
    <p>Sends the given event to AI.</p>

    <p></p>
  syntax:
    content: public void sendEvent(ApplicationInsightsEvent event)
    parameters:
    - id: event
      type: com.microsoft.applicationinsights.internal.common._application_insights_event
      description: <p>Event to send. </p>
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  name: ApplicationInsightsEvent
  fullName: com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent
  type: Class
  summary: <p>Interface for </p>
  syntax:
    content: public class ApplicationInsightsEvent
- uid: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.getTelemetryClient()
  parent: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.yml
  name: getTelemetryClient()
  fullName: TelemetryClient com.microsoft.applicationinsights.internal.common.TelemetryClientProxy.getTelemetryClient()
  type: Method
  summary: <p>Gets the telemetry client. </p>
  syntax:
    content: public TelemetryClient getTelemetryClient()
    return:
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The telemetry client. </p>
