items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b
  id: _application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b.yml
  langs:
  - java
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 260
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of an application gateway backend HTTP configuration definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithRequestTimeout<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  - com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.withBackendPort(int)
  - com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.withCookieBasedAffinity()
  - com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.withoutCookieBasedAffinity()
  - com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.withProtocol(ProtocolT)
  - com.microsoft.azure.management.network._application_gateway_backend_http7ccaa6407ed14eaaf4092e888b8695ec.withRequestTimeout(int)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdate<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.withBackendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775
  href: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.yml
  name: withBackendPort(int portNumber)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>.withBackendPort(int portNumber)
  type: Method
  summary: <p>Specifies the port number for this configuration that the backend is listening on. </p>
  syntax:
    content: public WithAttach<ParentT> withBackendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910decda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.withCookieBasedAffinity()
  parent: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03
  href: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.yml
  name: withCookieBasedAffinity()
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>.withCookieBasedAffinity()
  type: Method
  summary: <p>Enables cookie based affinity. </p>
  syntax:
    content: public WithAttach<ParentT> withCookieBasedAffinity()
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910decda8a2936
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.withoutCookieBasedAffinity()
  parent: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03
  href: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.yml
  name: withoutCookieBasedAffinity()
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>.withoutCookieBasedAffinity()
  type: Method
  summary: <p>Disables cookie based affinity. </p>
  syntax:
    content: public WithAttach<ParentT> withoutCookieBasedAffinity()
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910decda8a2936
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.withProtocol(ProtocolT)
  parent: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef
  href: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.yml
  name: withProtocol(ProtocolT protocol)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasProtocol<ProtocolT>.UpdateDefinitionStages.WithProtocol<ReturnT, ProtocolT>.withProtocol(ProtocolT protocol)
  type: Method
  summary: <p>Specifies the transport protocol. </p>
  syntax:
    content: public ReturnT withProtocol(ProtocolT protocol)
    parameters:
    - id: protocol
      type: b528dcf3
      description: <p>a transport protocol </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http7ccaa6407ed14eaaf4092e888b8695ec.withRequestTimeout(int)
  parent: com.microsoft.azure.management.network._application_gateway_backend_http7ccaa6407ed14eaaf4092e888b8695ec
  href: com.microsoft.azure.management.network._application_gateway_backend_http7ccaa6407ed14eaaf4092e888b8695ec.yml
  name: withRequestTimeout(int seconds)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithRequestTimeout<ParentT>.withRequestTimeout(int seconds)
  type: Method
  summary: <p>Specifies the request timeout. </p>
  syntax:
    content: public WithAttach<ParentT> withRequestTimeout(int seconds)
    parameters:
    - id: seconds
      type: f75371fa
      description: <p>a number of seconds </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910decda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpe32c71918b7cadcba11b031d001d2a9d
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_httpe32c71918b7cadcba11b031d001d2a9d.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of an application gateway backend HTTP configuration definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910dec
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910dec.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway backend HTTP configuration definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the port number. </p>
  syntax:
    content: public interface WithPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http67d0ab1ae35bf9987d5f2d6965f8ed03.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to enable or disable cookie based affinity. </p>
  syntax:
    content: public interface WithAffinity<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpceb6ddd8ba7135b94add62a3c389433b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_httpceb6ddd8ba7135b94add62a3c389433b.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the protocol. </p>
  syntax:
    content: public interface WithProtocol<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http7ccaa6407ed14eaaf4092e888b8695ec
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http7ccaa6407ed14eaaf4092e888b8695ec.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithRequestTimeout<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithRequestTimeout<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the request timeout. </p>
  syntax:
    content: public interface WithRequestTimeout<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
