items:
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher
  id: _telemetries_fetcher
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher.fetch()
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher.yml
  langs:
  - java
  name: TelemetriesTransmitter.TelemetriesFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter.TelemetriesFetcher
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public interface TelemetriesFetcher
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher.fetch()
  id: fetch()
  parent: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher.yml
  langs:
  - java
  name: fetch()
  fullName: Collection<String> com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter.TelemetriesFetcher.fetch()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public Collection<String> fetch()
    return:
      type: 0248867e
references:
- uid: 0248867e
  spec.java:
  - name: Collection<String>
    fullName: Collection<String>
