items:
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context_test
  id: _telemetry_context_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._telemetry_context_test.testCtor()
  - com.microsoft.applicationinsights.telemetry._telemetry_context_test.testEmptyInstrumentationKeyOverridenWhenContextInitialized()
  - com.microsoft.applicationinsights.telemetry._telemetry_context_test.testInstrumentationKeyNotOverridenWhenContextInitialized()
  - com.microsoft.applicationinsights.telemetry._telemetry_context_test.testSetInstrumentationKey()
  href: com.microsoft.applicationinsights.telemetry._telemetry_context_test.yml
  langs:
  - java
  name: TelemetryContextTest
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContextTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/TelemetryContextTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/TelemetryContextTest.java
    startLine: 30
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class TelemetryContextTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context_test.testCtor()
  id: testCtor()
  parent: com.microsoft.applicationinsights.telemetry._telemetry_context_test
  href: com.microsoft.applicationinsights.telemetry._telemetry_context_test.yml
  langs:
  - java
  name: testCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.TelemetryContextTest.testCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/TelemetryContextTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtor()
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context_test.testEmptyInstrumentationKeyOverridenWhenContextInitialized()
  id: testEmptyInstrumentationKeyOverridenWhenContextInitialized()
  parent: com.microsoft.applicationinsights.telemetry._telemetry_context_test
  href: com.microsoft.applicationinsights.telemetry._telemetry_context_test.yml
  langs:
  - java
  name: testEmptyInstrumentationKeyOverridenWhenContextInitialized()
  fullName: void com.microsoft.applicationinsights.telemetry.TelemetryContextTest.testEmptyInstrumentationKeyOverridenWhenContextInitialized()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/TelemetryContextTest.java
    startLine: 51
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyInstrumentationKeyOverridenWhenContextInitialized()
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context_test.testInstrumentationKeyNotOverridenWhenContextInitialized()
  id: testInstrumentationKeyNotOverridenWhenContextInitialized()
  parent: com.microsoft.applicationinsights.telemetry._telemetry_context_test
  href: com.microsoft.applicationinsights.telemetry._telemetry_context_test.yml
  langs:
  - java
  name: testInstrumentationKeyNotOverridenWhenContextInitialized()
  fullName: void com.microsoft.applicationinsights.telemetry.TelemetryContextTest.testInstrumentationKeyNotOverridenWhenContextInitialized()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/TelemetryContextTest.java
    startLine: 63
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testInstrumentationKeyNotOverridenWhenContextInitialized()
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context_test.testSetInstrumentationKey()
  id: testSetInstrumentationKey()
  parent: com.microsoft.applicationinsights.telemetry._telemetry_context_test
  href: com.microsoft.applicationinsights.telemetry._telemetry_context_test.yml
  langs:
  - java
  name: testSetInstrumentationKey()
  fullName: void com.microsoft.applicationinsights.telemetry.TelemetryContextTest.testSetInstrumentationKey()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/TelemetryContextTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetInstrumentationKey()
references: []
