items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.http
  id: http
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.http._http_class_data_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.http.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.agent.http
  fullName: com.microsoft.applicationinsights.agent.internal.agent.http
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/http/HttpClassDataProvider.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/http/HttpClassDataProvider.java
    startLine: 21
  syntax:
    content: namespace http
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent.http._http_class_data_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.http
  href: com.microsoft.applicationinsights.agent.internal.agent.http._http_class_data_provider.yml
  name: HttpClassDataProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.http.HttpClassDataProvider
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class HttpClassDataProvider
