items:
- uid: com.microsoft.applicationinsights.web.extensibility.modules
  id: modules
  children:
  - com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  - com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  - com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  - com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.extensibility.modules
  fullName: com.microsoft.applicationinsights.web.extensibility.modules
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
    startLine: 21
  syntax:
    content: namespace modules
references:
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.yml
  name: WebRequestTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class WebRequestTrackingTelemetryModule implements WebTelemetryModule,TelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  name: WebSessionTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax:
    content: public class WebSessionTrackingTelemetryModule implements WebTelemetryModule,TelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  name: WebTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface WebTelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.yml
  name: WebUserTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/7/2015. </p>
  syntax:
    content: public class WebUserTrackingTelemetryModule implements WebTelemetryModule,TelemetryModule
