items:
- uid: com.microsoft.azure.management.network._application_gateway_public_front4f0f57ecdff11046267b601039503ce7
  id: _application_gateway_public_front4f0f57ecdff11046267b601039503ce7
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_front4f0f57ecdff11046267b601039503ce7.yml
  langs:
  - java
  name: ApplicationGatewayPublicFrontend.UpdateDefinitionStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.UpdateDefinitionStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPublicFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPublicFrontend.java
    startLine: 81
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of public frontend definition stages applicable as part of an Internet-facing application gateway update. </p>
  syntax:
    content: public interface UpdateDefinitionStages
references: []
