items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  id: _windows_performance_counter_data
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.categoryName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.counterName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.displayName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.instanceName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setCategoryName(String)
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setCounterName(String)
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setDisplayName(String)
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setInstanceName(String)
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: WindowsPerformanceCounterData
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax: &o1
    content: public class WindowsPerformanceCounterData
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.categoryName()
  id: categoryName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: categoryName
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.categoryName
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String categoryName
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.counterName()
  id: counterName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: counterName
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.counterName
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String counterName
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.displayName()
  id: displayName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: displayName
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.displayName
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String displayName
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.instanceName()
  id: instanceName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: instanceName
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.instanceName
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String instanceName
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setCategoryName(String)
  id: setCategoryName(String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: setCategoryName(String categoryName)
  fullName: WindowsPerformanceCounterData com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.setCategoryName(String categoryName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public WindowsPerformanceCounterData setCategoryName(String categoryName)
    parameters:
    - id: categoryName
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setCounterName(String)
  id: setCounterName(String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: setCounterName(String counterName)
  fullName: WindowsPerformanceCounterData com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.setCounterName(String counterName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public WindowsPerformanceCounterData setCounterName(String counterName)
    parameters:
    - id: counterName
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setDisplayName(String)
  id: setDisplayName(String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: setDisplayName(String displayName)
  fullName: WindowsPerformanceCounterData com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.setDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public WindowsPerformanceCounterData setDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.setInstanceName(String)
  id: setInstanceName(String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  langs:
  - java
  name: setInstanceName(String instanceName)
  fullName: WindowsPerformanceCounterData com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData.setInstanceName(String instanceName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
    startLine: 61
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Sets the instance name, the method will consult the <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> for the proper instance name. </p>
  syntax:
    content: public WindowsPerformanceCounterData setInstanceName(String instanceName)
    parameters:
    - id: instanceName
      type: "26831127"
      description: <p>The requested instance name. </p>
    return:
      type: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
      description: <p>'this'. </p>
  exceptions:
  - type: a04fafd7
    description: <p>The method might throw an Error if the <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> is not able to properly connect to the native code. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: a04fafd7
  spec.java:
  - name: Throwable
    fullName: Throwable
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  name: WindowsPerformanceCounterData
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax: *o1
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  name: JniPCConnector
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector
  type: Class
  summary: >-
    <p>This class serves as the connection to the native code that does the work with Windows.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class JniPCConnector
