items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  id: _transmitter_impl_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testCtorWithNullTelemetrySerializer()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testCtorWithNullTransmissionDispatcher()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testCtorWithNullTransmissionsLoader()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testScheduleSendWith100Telemetries()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testScheduleSendWith1Telemetry()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testScheduleSendWithNoTelemetries()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testSendNowWith100Telemetries()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testSendNowWith1Telemetry()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testSendNowWithNoTelemetries()
  - com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testValidCtor()
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: TransmitterImplTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class TransmitterImplTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testCtorWithNullTelemetrySerializer()
  id: testCtorWithNullTelemetrySerializer()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testCtorWithNullTelemetrySerializer()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testCtorWithNullTelemetrySerializer()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testCtorWithNullTelemetrySerializer()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testCtorWithNullTransmissionDispatcher()
  id: testCtorWithNullTransmissionDispatcher()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testCtorWithNullTransmissionDispatcher()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testCtorWithNullTransmissionDispatcher()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testCtorWithNullTransmissionDispatcher()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testCtorWithNullTransmissionsLoader()
  id: testCtorWithNullTransmissionsLoader()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testCtorWithNullTransmissionsLoader()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testCtorWithNullTransmissionsLoader()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 62
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testCtorWithNullTransmissionsLoader()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testScheduleSendWith100Telemetries()
  id: testScheduleSendWith100Telemetries()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testScheduleSendWith100Telemetries()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testScheduleSendWith100Telemetries()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 98
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testScheduleSendWith100Telemetries()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testScheduleSendWith1Telemetry()
  id: testScheduleSendWith1Telemetry()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testScheduleSendWith1Telemetry()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testScheduleSendWith1Telemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 92
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testScheduleSendWith1Telemetry()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testScheduleSendWithNoTelemetries()
  id: testScheduleSendWithNoTelemetries()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testScheduleSendWithNoTelemetries()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testScheduleSendWithNoTelemetries()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 86
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testScheduleSendWithNoTelemetries()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testSendNowWith100Telemetries()
  id: testSendNowWith100Telemetries()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testSendNowWith100Telemetries()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testSendNowWith100Telemetries()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 116
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSendNowWith100Telemetries()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testSendNowWith1Telemetry()
  id: testSendNowWith1Telemetry()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testSendNowWith1Telemetry()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testSendNowWith1Telemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 110
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSendNowWith1Telemetry()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testSendNowWithNoTelemetries()
  id: testSendNowWithNoTelemetries()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testSendNowWithNoTelemetries()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testSendNowWithNoTelemetries()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 104
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSendNowWithNoTelemetries()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.testValidCtor()
  id: testValidCtor()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl_test.yml
  langs:
  - java
  name: testValidCtor()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImplTest.testValidCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImplTest.java
    startLine: 69
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testValidCtor()
references:
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
