items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775
  id: _application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.withBackendPort(int)
  href: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.yml
  langs:
  - java
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 209
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the port number. </p>
  syntax:
    content: public interface WithPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.withBackendPort(int)
  id: withBackendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775
  href: com.microsoft.azure.management.network._application_gateway_backend_httpaf57f3cc910473d76ee1017c39f90775.yml
  langs:
  - java
  name: withBackendPort(int portNumber)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>.withBackendPort(int portNumber)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 215
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the port number for this configuration that the backend is listening on. </p>
  syntax:
    content: public WithAttach<ParentT> withBackendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910decda8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910decda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910dec
    name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910dec.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway backend HTTP configuration definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithRequestTimeout<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910dec
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http9f4f1f4594ee8c5cc5737b4510910dec.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway backend HTTP configuration definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
