items:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  id: _test_stub
  parent: com.microsoft.applicationinsights.internal.jmx
  children:
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.d()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.getDoubleSample()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.getIntSample()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.getLongSample()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.i()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.l()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.TestStub(int,double,long)
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: JmxDataFetcherTest.TestStub
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 20
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public class TestStub implements JmxDataFetcherTest.StubMXBean
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.d()
  id: d()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: d
  fullName: double com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.d
  type: Field
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 22
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public double d
    return:
      type: a07dcde8
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.getDoubleSample()
  id: getDoubleSample()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: getDoubleSample()
  fullName: double com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.getDoubleSample()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public double getDoubleSample()
    return:
      type: a07dcde8
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.getIntSample()
  id: getIntSample()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: getIntSample()
  fullName: int com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.getIntSample()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public int getIntSample()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.getLongSample()
  id: getLongSample()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: getLongSample()
  fullName: long com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.getLongSample()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public long getLongSample()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.i()
  id: i()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: i
  fullName: int com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.i
  type: Field
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 21
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public int i
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.l()
  id: l()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: l
  fullName: long com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.l
  type: Field
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 23
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public long l
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.TestStub(int,double,long)
  id: TestStub(int,double,long)
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  langs:
  - java
  name: TestStub(int i, double d, long l)
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub.TestStub(int i, double d, long l)
  type: Constructor
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 24
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public TestStub(int i, double d, long l)
    parameters:
    - id: i
      type: f75371fa
    - id: d
      type: a07dcde8
    - id: l
      type: 0364520f
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: a07dcde8
  spec.java:
  - name: double
    fullName: double
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.yml
  name: JmxDataFetcherTest.StubMXBean
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.StubMXBean
  type: Interface
  syntax:
    content: public interface StubMXBean
