items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5
  id: _application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5.withBackendPort(int)
  href: com.microsoft.azure.management.network._application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5.yml
  langs:
  - java
  name: ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithPort
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithPort
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 128
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the port number. </p>
  syntax:
    content: public interface WithPort
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5.withBackendPort(int)
  id: withBackendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5
  href: com.microsoft.azure.management.network._application_gateway_backend_httpd12da0b5d3f4b5e36e92ebb29ac034f5.yml
  langs:
  - java
  name: withBackendPort(int portNumber)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithPort.withBackendPort(int portNumber)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 134
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the port number for this configuration that the backend is listening on. </p>
  syntax:
    content: public Update withBackendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_http_configuration._update
      description: <p>the next stage of the update </p>
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway_backend_http_configuration._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http_configuration._update.yml
  name: ApplicationGatewayBackendHttpConfiguration.Update
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.Update
  type: Interface
  summary: <p>The entirety of an application gateway backend HTTP configuration update as part of an application gateway update. </p>
  syntax:
    content: public interface Update extends Settable<ApplicationGateway.Update>,ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithPort,ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithAffinity,ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithProtocol,ApplicationGatewayBackendHttpConfiguration.UpdateStages.WithRequestTimeout
