items:
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  id: _remote_dependency_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testCommandName()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testCtorWithAllParameter()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testCtorWithNameParameter()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testDependencyKind()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testDuration()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testEmptyCtor()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetCount()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetDependencySource()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetMax()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetMin()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetName()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetStdDev()
  - com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSuccess()
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: RemoteDependencyTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class RemoteDependencyTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testCommandName()
  id: testCommandName()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testCommandName()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testCommandName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 84
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCommandName()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testCtorWithAllParameter()
  id: testCtorWithAllParameter()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testCtorWithAllParameter()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testCtorWithAllParameter()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 62
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtorWithAllParameter()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testCtorWithNameParameter()
  id: testCtorWithNameParameter()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testCtorWithNameParameter()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testCtorWithNameParameter()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtorWithNameParameter()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testDependencyKind()
  id: testDependencyKind()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testDependencyKind()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testDependencyKind()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 151
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testDependencyKind()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testDuration()
  id: testDuration()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testDuration()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testDuration()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 93
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testDuration()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testEmptyCtor()
  id: testEmptyCtor()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testEmptyCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testEmptyCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyCtor()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetCount()
  id: testSetCount()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSetCount()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSetCount()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 119
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetCount()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetDependencySource()
  id: testSetDependencySource()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSetDependencySource()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSetDependencySource()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 159
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetDependencySource()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetMax()
  id: testSetMax()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSetMax()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSetMax()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 135
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetMax()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetMin()
  id: testSetMin()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSetMin()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSetMin()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 127
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetMin()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetName()
  id: testSetName()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSetName()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSetName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 111
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetName()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSetStdDev()
  id: testSetStdDev()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSetStdDev()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSetStdDev()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 143
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetStdDev()
- uid: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.testSuccess()
  id: testSuccess()
  parent: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._remote_dependency_telemetry_test.yml
  langs:
  - java
  name: testSuccess()
  fullName: void com.microsoft.applicationinsights.telemetry.RemoteDependencyTelemetryTest.testSuccess()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
    startLine: 102
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSuccess()
references: []
