items:
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test
  id: _performance_counter_data_test
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testCategoryName()
  - com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testCounterName()
  - com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testInstanceName()
  - com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testStateAfterEmptyCtor()
  - com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testValue()
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.yml
  langs:
  - java
  name: PerformanceCounterDataTest
  fullName: com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterDataTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public class PerformanceCounterDataTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testCategoryName()
  id: testCategoryName()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.yml
  langs:
  - java
  name: testCategoryName()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterDataTest.testCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void testCategoryName()
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testCounterName()
  id: testCounterName()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.yml
  langs:
  - java
  name: testCounterName()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterDataTest.testCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void testCounterName()
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testInstanceName()
  id: testInstanceName()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.yml
  langs:
  - java
  name: testInstanceName()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterDataTest.testInstanceName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void testInstanceName()
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testStateAfterEmptyCtor()
  id: testStateAfterEmptyCtor()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.yml
  langs:
  - java
  name: testStateAfterEmptyCtor()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterDataTest.testStateAfterEmptyCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void testStateAfterEmptyCtor()
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.testValue()
  id: testValue()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data_test.yml
  langs:
  - java
  name: testValue()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterDataTest.testValue()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterDataTest.java
    startLine: 72
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void testValue()
references: []
