items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test
  id: _windows_performance_counter_as_metric_test
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.testNoNativeCodeActivated()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.testNull()
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.yml
  langs:
  - java
  name: WindowsPerformanceCounterAsMetricTest
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetricTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetricTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetricTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public class WindowsPerformanceCounterAsMetricTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.testNoNativeCodeActivated()
  id: testNoNativeCodeActivated()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.yml
  langs:
  - java
  name: testNoNativeCodeActivated()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetricTest.testNoNativeCodeActivated()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetricTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testNoNativeCodeActivated()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.testNull()
  id: testNull()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric_test.yml
  langs:
  - java
  name: testNull()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetricTest.testNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetricTest.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testNull()
references: []
