items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f
  id: _application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttp()
  - com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttps()
  href: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 155
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the protocol. </p>
  syntax:
    content: public interface WithProtocol<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttp()
  id: withHttp()
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f
  href: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.yml
  langs:
  - java
  name: withHttp()
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>.withHttp()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 160
  package: com.microsoft.azure.management.network
  summary: <p>Specifies that the listener is for the HTTP protocol. </p>
  syntax:
    content: public WithAttach<ParentT> withHttp()
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttps()
  id: withHttps()
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f
  href: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.yml
  langs:
  - java
  name: withHttps()
  fullName: WithSslCertificate<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>.withHttps()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 166
  package: com.microsoft.azure.management.network
  summary: <p>Specifies that the listener is for the HTTPS protocol. </p>
  syntax:
    content: public WithSslCertificate<ParentT> withHttps()
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67da8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20
    name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67da8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67
    name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate
    fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate
    href: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway HTTP listener. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the SSL certificate to associate with the listener. </p>
  syntax:
    content: public interface WithSslCertificate<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
