items:
- uid: com.microsoft.applicationinsights.internal.schemav2._domain
  id: _domain
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._domain.Domain()
  - com.microsoft.applicationinsights.internal.schemav2._domain.getBaseTypeName()
  - com.microsoft.applicationinsights.internal.schemav2._domain.getEnvelopName()
  - com.microsoft.applicationinsights.internal.schemav2._domain.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._domain.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._domain.serializeContent(JsonTelemetryDataSerializer)
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: Domain
  fullName: com.microsoft.applicationinsights.internal.schemav2.Domain
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._domain" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class Domain implements SendableData
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
  - com.microsoft.applicationinsights.internal.schemav2._sendable_data
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.Domain()
  id: Domain()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: Domain()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Domain.Domain()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public Domain()
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.getBaseTypeName()
  id: getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Domain.getBaseTypeName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 80
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.getEnvelopName()
  id: getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Domain.getEnvelopName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Domain.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Domain.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Domain.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Domain.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  exceptions:
  - type: cbf33bbe
    description: <p>Might be throw during serialization. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: SendableData
  fullName: com.microsoft.applicationinsights.internal.schemav2.SendableData
  type: Interface
  summary: <p>Defines the interface for data that might be sent to the Server. </p>
  syntax:
    content: public interface SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  name: EventData
  fullName: com.microsoft.applicationinsights.internal.schemav2.EventData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._event_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class EventData
- uid: com.microsoft.applicationinsights.internal.schemav2._exception_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._exception_data.yml
  name: ExceptionData
  fullName: com.microsoft.applicationinsights.internal.schemav2.ExceptionData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._exception_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ExceptionData
- uid: com.microsoft.applicationinsights.internal.schemav2._message_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._message_data.yml
  name: MessageData
  fullName: com.microsoft.applicationinsights.internal.schemav2.MessageData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._message_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class MessageData
- uid: com.microsoft.applicationinsights.internal.schemav2._metric_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._metric_data.yml
  name: MetricData
  fullName: com.microsoft.applicationinsights.internal.schemav2.MetricData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._metric_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class MetricData
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data.yml
  name: PerformanceCounterData
  fullName: com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterData
  type: Class
  summary: <p>Created by gupele on 3/1/2015. </p>
  syntax:
    content: public class PerformanceCounterData
- uid: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data.yml
  name: RemoteDependencyData
  fullName: com.microsoft.applicationinsights.internal.schemav2.RemoteDependencyData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class RemoteDependencyData
- uid: com.microsoft.applicationinsights.internal.schemav2._request_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._request_data.yml
  name: RequestData
  fullName: com.microsoft.applicationinsights.internal.schemav2.RequestData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._request_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class RequestData
- uid: com.microsoft.applicationinsights.internal.schemav2._session_state_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._session_state_data.yml
  name: SessionStateData
  fullName: com.microsoft.applicationinsights.internal.schemav2.SessionStateData
  type: Class
  summary: <p>Created by gupele on 2/19/2015. </p>
  syntax:
    content: public class SessionStateData
- uid: com.microsoft.applicationinsights.internal.schemav2._envelope
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._envelope.yml
  name: Envelope
  fullName: com.microsoft.applicationinsights.internal.schemav2.Envelope
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._envelope" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Envelope
- uid: com.microsoft.applicationinsights.internal.schemav2._base
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  name: Base
  fullName: com.microsoft.applicationinsights.internal.schemav2.Base
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._base" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Base implements JsonSerializable,SendableData
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._domain
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: Domain
  fullName: com.microsoft.applicationinsights.internal.schemav2.Domain
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._domain" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
