items:
- uid: com.microsoft.applicationinsights.internal.schemav2._location
  id: _location
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._location.addToHashMap(HashMap<String, String>)
  - com.microsoft.applicationinsights.internal.schemav2._location.getIp()
  - com.microsoft.applicationinsights.internal.schemav2._location.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._location.Location()
  - com.microsoft.applicationinsights.internal.schemav2._location.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._location.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._location.setIp(String)
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: Location
  fullName: com.microsoft.applicationinsights.internal.schemav2.Location
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._location" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class Location implements JsonSerializable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
- uid: com.microsoft.applicationinsights.internal.schemav2._location.addToHashMap(HashMap<String, String>)
  id: addToHashMap(HashMap<String, String>)
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: addToHashMap(HashMap<String, String> map)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Location.addToHashMap(HashMap<String, String> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void addToHashMap(HashMap<String, String> map)
    parameters:
    - id: map
      type: 3970a053
- uid: com.microsoft.applicationinsights.internal.schemav2._location.getIp()
  id: getIp()
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: getIp()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Location.getIp()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getIp()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._location.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Location.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 74
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._location.Location()
  id: Location()
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: Location()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Location.Location()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public Location()
- uid: com.microsoft.applicationinsights.internal.schemav2._location.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Location.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  exceptions:
  - type: cbf33bbe
    description: <p>The exception that might be thrown during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._location.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Location.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
- uid: com.microsoft.applicationinsights.internal.schemav2._location.setIp(String)
  id: setIp(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._location
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  langs:
  - java
  name: setIp(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Location.setIp(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Location.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setIp(String value)
    parameters:
    - id: value
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 3970a053
  spec.java:
  - name: HashMap<String, String>
    fullName: HashMap<String, String>
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._location
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._location.yml
  name: Location
  fullName: com.microsoft.applicationinsights.internal.schemav2.Location
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._location" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
