items:
- uid: com.microsoft.applicationinsights.internal.util._map_util
  id: _map_util
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._map_util.copy(Map<String, Value>,Map<String, Value>)
  - com.microsoft.applicationinsights.internal.util._map_util.getBoolValueOrNull(Map<String, String>,String)
  - com.microsoft.applicationinsights.internal.util._map_util.getDateValueOrNull(Map<String, String>,String)
  - com.microsoft.applicationinsights.internal.util._map_util.getValueOrNull(Map<Key, Value>,Key)
  - com.microsoft.applicationinsights.internal.util._map_util.setBoolValueOrRemove(Map<String, String>,String,Boolean)
  - com.microsoft.applicationinsights.internal.util._map_util.setDateValueOrRemove(Map<String, String>,String,Date)
  - com.microsoft.applicationinsights.internal.util._map_util.setStringValueOrRemove(Map<String, String>,String,String)
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: MapUtil
  fullName: com.microsoft.applicationinsights.internal.util.MapUtil
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Methods that would have been great to have on maps. </p>
  syntax:
    content: public class MapUtil
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._map_util.copy(Map<String, Value>,Map<String, Value>)
  id: copy(Map<String, Value>,Map<String, Value>)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: copy(Map<String, Value> source, Map<String, Value> target)
  fullName: static <Value> void com.microsoft.applicationinsights.internal.util.MapUtil.copy(Map<String, Value> source, Map<String, Value> target)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static static<Value> void copy(Map<String, Value> source, Map<String, Value> target)
    parameters:
    - id: source
      type: 18c555a4
    - id: target
      type: 18c555a4
    return:
      type: 7a2a8397
- uid: com.microsoft.applicationinsights.internal.util._map_util.getBoolValueOrNull(Map<String, String>,String)
  id: getBoolValueOrNull(Map<String, String>,String)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: getBoolValueOrNull(Map<String, String> map, String key)
  fullName: static Boolean com.microsoft.applicationinsights.internal.util.MapUtil.getBoolValueOrNull(Map<String, String> map, String key)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static Boolean getBoolValueOrNull(Map<String, String> map, String key)
    parameters:
    - id: map
      type: 689c8cb5
    - id: key
      type: "26831127"
    return:
      type: 866c2227
- uid: com.microsoft.applicationinsights.internal.util._map_util.getDateValueOrNull(Map<String, String>,String)
  id: getDateValueOrNull(Map<String, String>,String)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: getDateValueOrNull(Map<String, String> map, String key)
  fullName: static Date com.microsoft.applicationinsights.internal.util.MapUtil.getDateValueOrNull(Map<String, String> map, String key)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static Date getDateValueOrNull(Map<String, String> map, String key)
    parameters:
    - id: map
      type: 689c8cb5
    - id: key
      type: "26831127"
    return:
      type: "12977444"
- uid: com.microsoft.applicationinsights.internal.util._map_util.getValueOrNull(Map<Key, Value>,Key)
  id: getValueOrNull(Map<Key, Value>,Key)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: getValueOrNull(Map<Key, Value> map, Key key)
  fullName: static <Key, Value> Value com.microsoft.applicationinsights.internal.util.MapUtil.getValueOrNull(Map<Key, Value> map, Key key)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static static<Key, Value> Value getValueOrNull(Map<Key, Value> map, Key key)
    parameters:
    - id: map
      type: 4d360ac7
    - id: key
      type: "95567389"
    return:
      type: dfa840f7
- uid: com.microsoft.applicationinsights.internal.util._map_util.setBoolValueOrRemove(Map<String, String>,String,Boolean)
  id: setBoolValueOrRemove(Map<String, String>,String,Boolean)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: setBoolValueOrRemove(Map<String, String> map, String key, Boolean value)
  fullName: static void com.microsoft.applicationinsights.internal.util.MapUtil.setBoolValueOrRemove(Map<String, String> map, String key, Boolean value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static void setBoolValueOrRemove(Map<String, String> map, String key, Boolean value)
    parameters:
    - id: map
      type: 689c8cb5
    - id: key
      type: "26831127"
    - id: value
      type: 866c2227
- uid: com.microsoft.applicationinsights.internal.util._map_util.setDateValueOrRemove(Map<String, String>,String,Date)
  id: setDateValueOrRemove(Map<String, String>,String,Date)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: setDateValueOrRemove(Map<String, String> map, String key, Date value)
  fullName: static void com.microsoft.applicationinsights.internal.util.MapUtil.setDateValueOrRemove(Map<String, String> map, String key, Date value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static void setDateValueOrRemove(Map<String, String> map, String key, Date value)
    parameters:
    - id: map
      type: 689c8cb5
    - id: key
      type: "26831127"
    - id: value
      type: "12977444"
- uid: com.microsoft.applicationinsights.internal.util._map_util.setStringValueOrRemove(Map<String, String>,String,String)
  id: setStringValueOrRemove(Map<String, String>,String,String)
  parent: com.microsoft.applicationinsights.internal.util._map_util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  langs:
  - java
  name: setStringValueOrRemove(Map<String, String> map, String key, String value)
  fullName: static void com.microsoft.applicationinsights.internal.util.MapUtil.setStringValueOrRemove(Map<String, String> map, String key, String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static void setStringValueOrRemove(Map<String, String> map, String key, String value)
    parameters:
    - id: map
      type: 689c8cb5
    - id: key
      type: "26831127"
    - id: value
      type: "26831127"
references:
- uid: 18c555a4
  spec.java:
  - name: Map<String, Value>
    fullName: Map<String, Value>
- uid: 7a2a8397
  spec.java:
  - name: static<Value> void
    fullName: static<Value> void
- uid: 4d360ac7
  spec.java:
  - name: Map<Key, Value>
    fullName: Map<Key, Value>
- uid: "95567389"
  spec.java:
  - name: Key
    fullName: Key
- uid: dfa840f7
  spec.java:
  - name: static<Key, Value> Value
    fullName: static<Key, Value> Value
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: "12977444"
  spec.java:
  - name: Date
    fullName: Date
