items:
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable
  id: _stoppable
  parent: com.microsoft.applicationinsights.internal.shutdown
  children:
  - com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  langs:
  - java
  name: Stoppable
  fullName: com.microsoft.applicationinsights.internal.shutdown.Stoppable
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/Stoppable.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/Stoppable.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.shutdown
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface Stoppable
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.shutdown._stoppable
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.shutdown.Stoppable.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/Stoppable.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.shutdown
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  name: TransmissionPolicyManager
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager
  type: Class
  summary: >-
    <p>This class is responsible for managing the transmission state.</p>

    <p>The class might be told to suspend transmission for the next 'X' seconds where the state is set to be one of the states defined in <ref refid="" kindref="compound">com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicy</ref></p>

    <p>The class will keep that state for the requested amount of time and will release it, i.e. reset to 'unblock' when the timeout expires.</p>

    <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public class TransmissionPolicyManager
- uid: com.microsoft.applicationinsights.internal.channel._transmissions_loader
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmissions_loader.yml
  name: TransmissionsLoader
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionsLoader
  type: Interface
  summary: <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public interface TransmissionsLoader
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container.yml
  name: PerformanceCounterContainer
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer
  type: Enum
  summary: >-
    <p>The class serves as the container of all <xref href="com.microsoft.applicationinsights.internal.perfcounter._performance_counter" data-throw-if-not-resolved="false"></xref></p>

    <p>If there is a need for a performance counter, the user of this class should create an implementation of that interface and then register it in this container.</p>

    <p>Note that the container will only start working after the first registration of a Performance Counter. That means that setting the timeouts is only relevant if done before the first registration of a Performance Counter.</p>

    <p>The container will go through all the registered Performance Counters and will trigger their 'report' method. By default the container will start reporting after 5 minutes and will continue doing so every 1 minute.</p>

    <p>The user of this class can add (register), remove (unregister) a performance counter while the container is working.</p>

    <p>The container will be stopped automatically when the application exists.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public enum PerformanceCounterContainer implements Stoppable
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: synchronized void com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public synchronized void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: synchronized void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer.stop(long timeout, TimeUnit timeUnit)
  type: Method
  summary: <p>Stopping the collection of performance data. </p>
  syntax:
    content: public synchronized void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>The timeout to wait for the stop to happen. </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The time unit to use when waiting for the stop to happen. </p>
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
