items:
- uid: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test
  id: _http_request_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.testDefaultCtor()
  - com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.testParameterizedCtor()
  - com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.testSetCode()
  href: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.yml
  langs:
  - java
  name: HttpRequestTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.HttpRequestTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/HttpRequestTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/HttpRequestTelemetryTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class HttpRequestTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.testDefaultCtor()
  id: testDefaultCtor()
  parent: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.yml
  langs:
  - java
  name: testDefaultCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.HttpRequestTelemetryTest.testDefaultCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/HttpRequestTelemetryTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testDefaultCtor()
- uid: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.testParameterizedCtor()
  id: testParameterizedCtor()
  parent: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.yml
  langs:
  - java
  name: testParameterizedCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.HttpRequestTelemetryTest.testParameterizedCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/HttpRequestTelemetryTest.java
    startLine: 41
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testParameterizedCtor()
- uid: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.testSetCode()
  id: testSetCode()
  parent: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._http_request_telemetry_test.yml
  langs:
  - java
  name: testSetCode()
  fullName: void com.microsoft.applicationinsights.telemetry.HttpRequestTelemetryTest.testSetCode()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/HttpRequestTelemetryTest.java
    startLine: 53
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetCode()
references: []
