items:
- uid: com.microsoft.applicationinsights.internal.annotation
  id: annotation
  children:
  - com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner
  - com.microsoft.applicationinsights.internal.annotation._built_in_processor
  - com.microsoft.applicationinsights.internal.annotation._performance_module
  href: com.microsoft.applicationinsights.internal.annotation.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.annotation
  fullName: com.microsoft.applicationinsights.internal.annotation
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
    startLine: 21
  syntax:
    content: namespace annotation
references:
- uid: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner
  parent: com.microsoft.applicationinsights.internal.annotation
  href: com.microsoft.applicationinsights.internal.annotation._annotation_package_scanner.yml
  name: AnnotationPackageScanner
  fullName: com.microsoft.applicationinsights.internal.annotation.AnnotationPackageScanner
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AnnotationPackageScanner
- uid: com.microsoft.applicationinsights.internal.annotation._built_in_processor
  parent: com.microsoft.applicationinsights.internal.annotation
  href: com.microsoft.applicationinsights.internal.annotation._built_in_processor.yml
  name: BuiltInProcessor
  fullName: com.microsoft.applicationinsights.internal.annotation.BuiltInProcessor
  type: Interface
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public interface BuiltInProcessor
- uid: com.microsoft.applicationinsights.internal.annotation._performance_module
  parent: com.microsoft.applicationinsights.internal.annotation
  href: com.microsoft.applicationinsights.internal.annotation._performance_module.yml
  name: PerformanceModule
  fullName: com.microsoft.applicationinsights.internal.annotation.PerformanceModule
  type: Interface
  syntax:
    content: public interface PerformanceModule
