items:
- uid: com.microsoft.applicationinsights.internal.channel._telemetry_serializer
  id: _telemetry_serializer
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._telemetry_serializer.serialize(Collection<String>)
  href: com.microsoft.applicationinsights.internal.channel._telemetry_serializer.yml
  langs:
  - java
  name: TelemetrySerializer
  fullName: com.microsoft.applicationinsights.internal.channel.TelemetrySerializer
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetrySerializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetrySerializer.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.channel
  summary: >-
    <p>Created by gupele on 12/17/2014.</p>

    <p>An interface for serializing container of telemetries Concrete classes should be able to create a compressed byte array that represents at collection of Telemetry instances </p>
  syntax:
    content: public interface TelemetrySerializer
- uid: com.microsoft.applicationinsights.internal.channel._telemetry_serializer.serialize(Collection<String>)
  id: serialize(Collection<String>)
  parent: com.microsoft.applicationinsights.internal.channel._telemetry_serializer
  href: com.microsoft.applicationinsights.internal.channel._telemetry_serializer.yml
  langs:
  - java
  name: serialize(Collection<String> telemetries)
  fullName: Optional<Transmission> com.microsoft.applicationinsights.internal.channel.TelemetrySerializer.serialize(Collection<String> telemetries)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetrySerializer.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public Optional<Transmission> serialize(Collection<String> telemetries)
    parameters:
    - id: telemetries
      type: 0248867e
      description: <p>A collection of Telemetry instances </p>
    return:
      type: e1a2fe4dcom.microsoft.applicationinsights.internal.channel.common._transmissiona08ddfce
      description: <p>byte array that is a compressed version of the input </p>
references:
- uid: 0248867e
  spec.java:
  - name: Collection<String>
    fullName: Collection<String>
- uid: e1a2fe4dcom.microsoft.applicationinsights.internal.channel.common._transmissiona08ddfce
  spec.java:
  - name: Optional<
    fullName: Optional<
  - uid: com.microsoft.applicationinsights.internal.channel.common._transmission
    name: Transmission
    fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
    href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer.yml
  name: GzipTelemetrySerializer
  fullName: com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializer
  type: Class
  summary: >-
    <p>The class is an implementation of the <xref href="com.microsoft.applicationinsights.internal.channel._telemetry_serializer" data-throw-if-not-resolved="false"></xref> where the <ref refid="" kindref="compound">Telemetry</ref> instances are compressed by Gzip after converted to Json format</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class GzipTelemetrySerializer implements TelemetrySerializer
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer.serialize(Collection<String>)
  parent: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer
  href: com.microsoft.applicationinsights.internal.channel.common._gzip_telemetry_serializer.yml
  name: serialize(Collection<String> telemetries)
  fullName: Optional<Transmission> com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializer.serialize(Collection<String> telemetries)
  type: Method
  syntax:
    content: public Optional<Transmission> serialize(Collection<String> telemetries)
    parameters:
    - id: telemetries
      type: 0248867e
      description: <p>A collection of Telemetry instances </p>
    return:
      type: e1a2fe4dcom.microsoft.applicationinsights.internal.channel.common._transmissiona08ddfce
      description: <p>byte array that is a compressed version of the input </p>
