items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor
  id: _ok_http_class_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.getMethodVisitor(int,String,String,MethodVisitor)
  - com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.OkHttpClassVisitor(ClassInstrumentationData,ClassWriter)
  - com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.visitField(int,String,String,String,Object)
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.yml
  langs:
  - java
  name: OkHttpClassVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.OkHttpClassVisitor
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/OkHttpClassVisitor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/OkHttpClassVisitor.java
    startLine: 30
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public class OkHttpClassVisitor extends DefaultClassVisitor
  inheritance:
  - java.lang.Object
  - ClassVisitor
  - com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  inheritedMembers:
  - com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.DefaultClassVisitor(ClassInstrumentationData,ClassWriter)
  - com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.instrumentationData()
  - com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.visit(int,int,String,String,String,String[])
  - com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.visitMethod(int,String,String,String,String[])
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.getMethodVisitor(int,String,String,MethodVisitor)
  id: getMethodVisitor(int,String,String,MethodVisitor)
  parent: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.yml
  langs:
  - java
  name: getMethodVisitor(int access, String name, String desc, MethodVisitor originalMV)
  fullName: MethodVisitor com.microsoft.applicationinsights.agent.internal.agent.OkHttpClassVisitor.getMethodVisitor(int access, String name, String desc, MethodVisitor originalMV)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/OkHttpClassVisitor.java
    startLine: 49
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected MethodVisitor getMethodVisitor(int access, String name, String desc, MethodVisitor originalMV)
    parameters:
    - id: access
      type: f75371fa
    - id: name
      type: "26831127"
    - id: desc
      type: "26831127"
    - id: originalMV
      type: dd525b3c
    return:
      type: dd525b3c
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.OkHttpClassVisitor(ClassInstrumentationData,ClassWriter)
  id: OkHttpClassVisitor(ClassInstrumentationData,ClassWriter)
  parent: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.yml
  langs:
  - java
  name: OkHttpClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.OkHttpClassVisitor.OkHttpClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/OkHttpClassVisitor.java
    startLine: 35
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public OkHttpClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter)
    parameters:
    - id: instrumentationData
      type: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    - id: classWriter
      type: 80ad7f6d
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.visitField(int,String,String,String,Object)
  id: visitField(int,String,String,String,Object)
  parent: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.yml
  langs:
  - java
  name: visitField(int access, String name, String desc, String signature, Object value)
  fullName: FieldVisitor com.microsoft.applicationinsights.agent.internal.agent.OkHttpClassVisitor.visitField(int access, String name, String desc, String signature, Object value)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/OkHttpClassVisitor.java
    startLine: 40
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public FieldVisitor visitField(int access, String name, String desc, String signature, Object value)
    parameters:
    - id: access
      type: f75371fa
    - id: name
      type: "26831127"
    - id: desc
      type: "26831127"
    - id: signature
      type: "26831127"
    - id: value
      type: "79317049"
    return:
      type: a4b8ddb9
references:
- uid: 80ad7f6d
  spec.java:
  - name: ClassWriter
    fullName: ClassWriter
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: a4b8ddb9
  spec.java:
  - name: FieldVisitor
    fullName: FieldVisitor
- uid: dd525b3c
  spec.java:
  - name: MethodVisitor
    fullName: MethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.DefaultClassVisitor(ClassInstrumentationData,ClassWriter)
  parent: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.yml
  name: DefaultClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.DefaultClassVisitor.DefaultClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter)
  type: Constructor
  syntax:
    content: public DefaultClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter)
    parameters:
    - id: instrumentationData
      type: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    - id: classWriter
      type: 80ad7f6d
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.instrumentationData()
  parent: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.yml
  name: instrumentationData
  fullName: final ClassInstrumentationData com.microsoft.applicationinsights.agent.internal.agent.DefaultClassVisitor.instrumentationData
  type: Field
  syntax:
    content: protected final ClassInstrumentationData instrumentationData
    return:
      type: 93de0ef9com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.visit(int,int,String,String,String,String[])
  parent: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.yml
  name: visit(int version, int access, String name, String signature, String superName, String[] interfaces)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.DefaultClassVisitor.visit(int version, int access, String name, String signature, String superName, String[] interfaces)
  type: Method
  syntax:
    content: public void visit(int version, int access, String name, String signature, String superName, String[] interfaces)
    parameters:
    - id: version
      type: f75371fa
    - id: access
      type: f75371fa
    - id: name
      type: "26831127"
    - id: signature
      type: "26831127"
    - id: superName
      type: "26831127"
    - id: interfaces
      type: 30d59cf1
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.visitMethod(int,String,String,String,String[])
  parent: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.yml
  name: visitMethod(int access, String name, String desc, String signature, String[] exceptions)
  fullName: MethodVisitor com.microsoft.applicationinsights.agent.internal.agent.DefaultClassVisitor.visitMethod(int access, String name, String desc, String signature, String[] exceptions)
  type: Method
  syntax:
    content: public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions)
    parameters:
    - id: access
      type: f75371fa
    - id: name
      type: "26831127"
    - id: desc
      type: "26831127"
    - id: signature
      type: "26831127"
    - id: exceptions
      type: 30d59cf1
    return:
      type: dd525b3c
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.yml
  name: DefaultClassVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.DefaultClassVisitor
  type: Class
  summary: >-
    <p>The class is responsible for identifying public methods on non-interface classes. When a method is found the class will call the <xref href="com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class DefaultClassVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
