items:
- uid: com.microsoft.applicationinsights.internal.channel._transmitter_factory
  id: _transmitter_factory
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._transmitter_factory.create(String,String,boolean)
  href: com.microsoft.applicationinsights.internal.channel._transmitter_factory.yml
  langs:
  - java
  name: TransmitterFactory
  fullName: com.microsoft.applicationinsights.internal.channel.TransmitterFactory
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmitterFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmitterFactory.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.channel
  summary: <p>Created by gupele on 12/21/2014. </p>
  syntax:
    content: public interface TransmitterFactory
- uid: com.microsoft.applicationinsights.internal.channel._transmitter_factory.create(String,String,boolean)
  id: create(String,String,boolean)
  parent: com.microsoft.applicationinsights.internal.channel._transmitter_factory
  href: com.microsoft.applicationinsights.internal.channel._transmitter_factory.yml
  langs:
  - java
  name: create(String endpoint, String maxTransmissionStorageCapacity, boolean throttlingIsEnabled)
  fullName: TelemetriesTransmitter com.microsoft.applicationinsights.internal.channel.TransmitterFactory.create(String endpoint, String maxTransmissionStorageCapacity, boolean throttlingIsEnabled)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmitterFactory.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public TelemetriesTransmitter create(String endpoint, String maxTransmissionStorageCapacity, boolean throttlingIsEnabled)
    parameters:
    - id: endpoint
      type: "26831127"
    - id: maxTransmissionStorageCapacity
      type: "26831127"
    - id: throttlingIsEnabled
      type: 4fc6e284
    return:
      type: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel_factory
- uid: com.microsoft.applicationinsights.core.volume._throughput_test_transmitter_factory
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.yml
  name: TelemetriesTransmitter
  fullName: com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter
  type: Interface
  summary: >-
    <p>The class is responsible for getting containers of <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>, transform them into <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and then initiate the sending process.</p>

    <p>Containers of Telemetry instances are populated by application threads. This class use the 'channel's' threads for the rest of the process. In other words, the de-coupling of user and channel threads happens here.</p>

    <p>The class lets its users to schedule a 'send', where a channel thread will be sent to 'pick up' the container of Telemetries. Or, it also lets the caller to initiate a 'send now' call where the caller passes the container and this class will continue, again, using a channel thread while releasing the calling thread.</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public interface TelemetriesTransmitter
