items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory
  id: _class_visitor_factory
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory.create(ClassInstrumentationData,ClassWriter)
  href: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory.yml
  langs:
  - java
  name: ClassVisitorFactory
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassVisitorFactory
  type: Interface
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ClassVisitorFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ClassVisitorFactory.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface ClassVisitorFactory
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory.create(ClassInstrumentationData,ClassWriter)
  id: create(ClassInstrumentationData,ClassWriter)
  parent: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory
  href: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory.yml
  langs:
  - java
  name: create(ClassInstrumentationData classInstrumentationData, ClassWriter classWriter)
  fullName: ClassVisitor com.microsoft.applicationinsights.agent.internal.agent.ClassVisitorFactory.create(ClassInstrumentationData classInstrumentationData, ClassWriter classWriter)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/ClassVisitorFactory.java
    startLine: 30
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public ClassVisitor create(ClassInstrumentationData classInstrumentationData, ClassWriter classWriter)
    parameters:
    - id: classInstrumentationData
      type: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    - id: classWriter
      type: 80ad7f6d
    return:
      type: 1296644b
references:
- uid: 80ad7f6d
  spec.java:
  - name: ClassWriter
    fullName: ClassWriter
- uid: 1296644b
  spec.java:
  - name: ClassVisitor
    fullName: ClassVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
