items:
- uid: com.microsoft.applicationinsights.agent.internal.coresync
  id: coresync
  children:
  - com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
  - com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type
  href: com.microsoft.applicationinsights.agent.internal.coresync.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.coresync
  fullName: com.microsoft.applicationinsights.agent.internal.coresync
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler.java
    startLine: 21
  syntax:
    content: namespace coresync
references:
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl.yml
  name: com.microsoft.applicationinsights.agent.internal.coresync.impl
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl
  type: Namespace
  syntax:
    content: namespace impl
- uid: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler
  parent: com.microsoft.applicationinsights.agent.internal.coresync
  href: com.microsoft.applicationinsights.agent.internal.coresync._agent_notifications_handler.yml
  name: AgentNotificationsHandler
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.AgentNotificationsHandler
  type: Interface
  summary: >-
    <p>The Agent will inject code in the user's code that will be activated on predefined methods. Those methods will be directed to the Agent that will need to work with that information by delegating the calls to 'clients', those clients will need to implement the following interface.</p>

    <p>Created by gupele on 5/6/2015. </p>
  syntax:
    content: public interface AgentNotificationsHandler
- uid: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type
  parent: com.microsoft.applicationinsights.agent.internal.coresync
  href: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.yml
  name: InstrumentedClassType
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.InstrumentedClassType
  type: Enum
  summary: <p>Created by gupele on 5/17/2015. </p>
  syntax:
    content: public enum InstrumentedClassType
