items:
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  id: _agent_built_in_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.create()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setDataOfConfigurationForException(DataOfConfigurationForException)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setEnabled(boolean)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setHibernateEnabled(boolean)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setHttpEnabled(boolean)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setJdbcEnabled(boolean)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setJedisValues(boolean,long)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setJmxEnabled(boolean)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setSimpleBuiltInClasses(List<ClassInstrumentationData>)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setSqlMaxQueryLimitInMS(Long)
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: AgentBuiltInConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 30
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax: &o1
    content: public class AgentBuiltInConfigurationBuilder
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.create()
  id: create()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: create()
  fullName: AgentBuiltInConfiguration com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.create()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 42
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfiguration create()
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setDataOfConfigurationForException(DataOfConfigurationForException)
  id: setDataOfConfigurationForException(DataOfConfigurationForException)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setDataOfConfigurationForException(DataOfConfigurationForException dataOfConfigurationForException)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setDataOfConfigurationForException(DataOfConfigurationForException dataOfConfigurationForException)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 98
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void setDataOfConfigurationForException(DataOfConfigurationForException dataOfConfigurationForException)
    parameters:
    - id: dataOfConfigurationForException
      type: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setEnabled(boolean)
  id: setEnabled(boolean)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setEnabled(boolean enabled)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setEnabled(boolean enabled)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 58
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setEnabled(boolean enabled)
    parameters:
    - id: enabled
      type: 4fc6e284
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setHibernateEnabled(boolean)
  id: setHibernateEnabled(boolean)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setHibernateEnabled(boolean hibernateEnabled)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setHibernateEnabled(boolean hibernateEnabled)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 73
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setHibernateEnabled(boolean hibernateEnabled)
    parameters:
    - id: hibernateEnabled
      type: 4fc6e284
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setHttpEnabled(boolean)
  id: setHttpEnabled(boolean)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setHttpEnabled(boolean httpEnabled)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setHttpEnabled(boolean httpEnabled)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 63
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setHttpEnabled(boolean httpEnabled)
    parameters:
    - id: httpEnabled
      type: 4fc6e284
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setJdbcEnabled(boolean)
  id: setJdbcEnabled(boolean)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setJdbcEnabled(boolean jdbcEnabled)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setJdbcEnabled(boolean jdbcEnabled)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 68
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setJdbcEnabled(boolean jdbcEnabled)
    parameters:
    - id: jdbcEnabled
      type: 4fc6e284
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setJedisValues(boolean,long)
  id: setJedisValues(boolean,long)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setJedisValues(boolean jedisEnabled, long jedisThresholdInMS)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setJedisValues(boolean jedisEnabled, long jedisThresholdInMS)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 92
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setJedisValues(boolean jedisEnabled, long jedisThresholdInMS)
    parameters:
    - id: jedisEnabled
      type: 4fc6e284
    - id: jedisThresholdInMS
      type: 0364520f
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setJmxEnabled(boolean)
  id: setJmxEnabled(boolean)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setJmxEnabled(boolean jmxEnabled)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setJmxEnabled(boolean jmxEnabled)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 78
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setJmxEnabled(boolean jmxEnabled)
    parameters:
    - id: jmxEnabled
      type: 4fc6e284
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setSimpleBuiltInClasses(List<ClassInstrumentationData>)
  id: setSimpleBuiltInClasses(List<ClassInstrumentationData>)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setSimpleBuiltInClasses(List<ClassInstrumentationData> simpleBuiltInClasses)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setSimpleBuiltInClasses(List<ClassInstrumentationData> simpleBuiltInClasses)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 104
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void setSimpleBuiltInClasses(List<ClassInstrumentationData> simpleBuiltInClasses)
    parameters:
    - id: simpleBuiltInClasses
      type: 5618da2dcom.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.setSqlMaxQueryLimitInMS(Long)
  id: setSqlMaxQueryLimitInMS(Long)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  langs:
  - java
  name: setSqlMaxQueryLimitInMS(Long maxSqlQueryLimitInMS)
  fullName: AgentBuiltInConfigurationBuilder com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder.setSqlMaxQueryLimitInMS(Long maxSqlQueryLimitInMS)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
    startLine: 83
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfigurationBuilder setSqlMaxQueryLimitInMS(Long maxSqlQueryLimitInMS)
    parameters:
    - id: maxSqlQueryLimitInMS
      type: 34f09483
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 34f09483
  spec.java:
  - name: Long
    fullName: Long
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 5618da2dcom.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    name: ClassInstrumentationData
    fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
    href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  name: DataOfConfigurationForException
  fullName: com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException
  type: Class
  summary: <p>Created by gupele on 8/18/2016. </p>
  syntax:
    content: public class DataOfConfigurationForException
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  name: AgentBuiltInConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration
  type: Class
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax:
    content: public class AgentBuiltInConfiguration
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  name: AgentBuiltInConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder
  type: Class
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax: *o1
