items:
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_group
  id: _with_group
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_group.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithGroup
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithGroup
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 121
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to specify the resource group. </p>
  syntax:
    content: public interface WithGroup extends GroupableResource.DefinitionStages.WithGroup<WithSku>
references:
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.79156392b6c7de52796e84f59ad1464d
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.79156392b6c7de52796e84f59ad1464d.yml
  name: GroupableResource.DefinitionStages.WithGroup<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.GroupableResource.DefinitionStages.WithGroup<T>
  type: Interface
  summary: >-
    <p>A resource definition allowing a resource group to be selected. </p>

    <p>

      <xref href="com.microsoft.azure.management.resources.fluentcore.arm._region" data-throw-if-not-resolved="false"></xref> of the groupable resource will be used for new resource group</p>

    <p></p>
  syntax:
    content: public interface WithGroup<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
