items:
- uid: com.microsoft.applicationinsights.internal.config._reflection_utils
  id: _reflection_utils
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._reflection_utils.activateMethod(Object,String,V,A)
  - com.microsoft.applicationinsights.internal.config._reflection_utils.createInstance(String,Class<T>)
  - com.microsoft.applicationinsights.internal.config._reflection_utils.createInstance(String,Class<T>,Class<A>,A)
  - com.microsoft.applicationinsights.internal.config._reflection_utils.loadComponents(Class<T>,List<T>,Collection<AddTypeXmlElement>)
  href: com.microsoft.applicationinsights.internal.config._reflection_utils.yml
  langs:
  - java
  name: ReflectionUtils
  fullName: com.microsoft.applicationinsights.internal.config.ReflectionUtils
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Utililty methods for dealing with reflection</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class ReflectionUtils
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._reflection_utils.activateMethod(Object,String,V,A)
  id: activateMethod(Object,String,V,A)
  parent: com.microsoft.applicationinsights.internal.config._reflection_utils
  href: com.microsoft.applicationinsights.internal.config._reflection_utils.yml
  langs:
  - java
  name: activateMethod(Object object, String methodName, V value, A argumentClass)
  fullName: static <V, A> boolean com.microsoft.applicationinsights.internal.config.ReflectionUtils.activateMethod(Object object, String methodName, V value, A argumentClass)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
    startLine: 127
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public static static<V, A> boolean activateMethod(Object object, String methodName, V value, A argumentClass)
    parameters:
    - id: object
      type: "79317049"
      description: <p>- The instance we work with </p>
    - id: methodName
      type: "26831127"
      description: <p>- The method to activate </p>
    - id: value
      type: 0a560652
      description: <p>- The value to pass to the method </p>
    - id: argumentClass
      type: 7062c57f
      description: <p>- The argument class </p>
    return:
      type: 37cc55a3
      description: <p>- True if method found and activation was ok, otherwise false. </p>
- uid: com.microsoft.applicationinsights.internal.config._reflection_utils.createInstance(String,Class<T>)
  id: createInstance(String,Class<T>)
  parent: com.microsoft.applicationinsights.internal.config._reflection_utils
  href: com.microsoft.applicationinsights.internal.config._reflection_utils.yml
  langs:
  - java
  name: createInstance(String className, Class<T> interfaceClass)
  fullName: static <T> T com.microsoft.applicationinsights.internal.config.ReflectionUtils.createInstance(String className, Class<T> interfaceClass)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Creates an instance from its name. We suppress Java compiler warnings for Generic casting</p>

    <p>Note that currently we 'swallow' all exceptions and simply return null if we fail</p>

    <p></p>
  syntax:
    content: public static static<T> T createInstance(String className, Class<T> interfaceClass)
    parameters:
    - id: className
      type: "26831127"
      description: <p>The class we create an instance of </p>
    - id: interfaceClass
      type: ffb09d2d
      description: <p>The class' parent interface we wish to work with </p>
    return:
      type: 2cb01ffb
      description: <p>The instance or null if failed </p>
- uid: com.microsoft.applicationinsights.internal.config._reflection_utils.createInstance(String,Class<T>,Class<A>,A)
  id: createInstance(String,Class<T>,Class<A>,A)
  parent: com.microsoft.applicationinsights.internal.config._reflection_utils
  href: com.microsoft.applicationinsights.internal.config._reflection_utils.yml
  langs:
  - java
  name: createInstance(String className, Class<T> interfaceClass, Class<A> argumentClass, A argument)
  fullName: static <T, A> T com.microsoft.applicationinsights.internal.config.ReflectionUtils.createInstance(String className, Class<T> interfaceClass, Class<A> argumentClass, A argument)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Creates an instance from its name. We suppress Java compiler warnings for Generic casting The class is created by using a constructor that has one parameter which is sent to the method</p>

    <p>Note that currently we 'swallow' all exceptions and simply return null if we fail</p>

    <p></p>
  syntax:
    content: public static static<T, A> T createInstance(String className, Class<T> interfaceClass, Class<A> argumentClass, A argument)
    parameters:
    - id: className
      type: "26831127"
      description: <p>The class we create an instance of </p>
    - id: interfaceClass
      type: ffb09d2d
      description: <p>The class' parent interface we wish to work with </p>
    - id: argumentClass
      type: 68184f3d
      description: <p>Type of class to use as argument for Ctor </p>
    - id: argument
      type: 7062c57f
      description: <p>The argument to pass the Ctor </p>
    return:
      type: 0985bbc9
      description: <p>The instance or null if failed </p>
- uid: com.microsoft.applicationinsights.internal.config._reflection_utils.loadComponents(Class<T>,List<T>,Collection<AddTypeXmlElement>)
  id: loadComponents(Class<T>,List<T>,Collection<AddTypeXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._reflection_utils
  href: com.microsoft.applicationinsights.internal.config._reflection_utils.yml
  langs:
  - java
  name: loadComponents(Class<T> clazz, List<T> list, Collection<AddTypeXmlElement> classNames)
  fullName: static <T> void com.microsoft.applicationinsights.internal.config.ReflectionUtils.loadComponents(Class<T> clazz, List<T> list, Collection<AddTypeXmlElement> classNames)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
    startLine: 158
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Generic method that creates instances based on their names and adds them to a Collection</p>

    <p>Note that the class does its 'best effort' to create an instance and will not fail the method if an instance (or more) was failed to create. This is naturally, a policy we can easily replace</p>

    <p></p>
  syntax:
    content: public static static<T> void loadComponents(Class<T> clazz, List<T> list, Collection<AddTypeXmlElement> classNames)
    parameters:
    - id: clazz
      type: ffb09d2d
      description: <p>The class all instances should have </p>
    - id: list
      type: 18ad973c
      description: <p>The container of instances, this is where we store our instances that we create </p>
    - id: classNames
      type: 12ebb11acom.microsoft.applicationinsights.internal.config._add_type_xml_elementa08ddfce
      description: <p>Classes to create. </p>
    return:
      type: ae032643
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: ffb09d2d
  spec.java:
  - name: Class<T>
    fullName: Class<T>
- uid: 2cb01ffb
  spec.java:
  - name: static<T> T
    fullName: static<T> T
- uid: 68184f3d
  spec.java:
  - name: Class<A>
    fullName: Class<A>
- uid: 7062c57f
  spec.java:
  - name: A
    fullName: A
- uid: 0985bbc9
  spec.java:
  - name: static<T, A> T
    fullName: static<T, A> T
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 0a560652
  spec.java:
  - name: V
    fullName: V
- uid: 37cc55a3
  spec.java:
  - name: static<V, A> boolean
    fullName: static<V, A> boolean
- uid: 18ad973c
  spec.java:
  - name: List<T>
    fullName: List<T>
- uid: 12ebb11acom.microsoft.applicationinsights.internal.config._add_type_xml_elementa08ddfce
  spec.java:
  - name: Collection<
    fullName: Collection<
  - uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element
    name: AddTypeXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.AddTypeXmlElement
    href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: ae032643
  spec.java:
  - name: static<T> void
    fullName: static<T> void
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  name: AddTypeXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.AddTypeXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AddTypeXmlElement
