items:
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  id: _request_telemetry_context
  parent: com.microsoft.applicationinsights.web.internal
  children:
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.getHttpRequestTelemetry()
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.getHttpServletRequest()
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.getIsNewSession()
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.getRequestStartTimeTicks()
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.getSessionCookie()
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.getUserCookie()
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.RequestTelemetryContext(long)
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.RequestTelemetryContext(long,HttpServletRequest)
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.setIsNewSession(boolean)
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.setSessionCookie(SessionCookie)
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context.setUserCookie(UserCookie)
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: RequestTelemetryContext
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 32
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax: &o1
    content: public class RequestTelemetryContext
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.getHttpRequestTelemetry()
  id: getHttpRequestTelemetry()
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: getHttpRequestTelemetry()
  fullName: RequestTelemetry com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.getHttpRequestTelemetry()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 63
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets the http request telemetry associated with the context. </p>
  syntax:
    content: public RequestTelemetry getHttpRequestTelemetry()
    return:
      type: com.microsoft.applicationinsights.telemetry._request_telemetry
      description: <p>The http request telemetry. </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.getHttpServletRequest()
  id: getHttpServletRequest()
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: getHttpServletRequest()
  fullName: HttpServletRequest com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.getHttpServletRequest()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 123
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public HttpServletRequest getHttpServletRequest()
    return:
      type: 81123e1c
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.getIsNewSession()
  id: getIsNewSession()
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: getIsNewSession()
  fullName: boolean com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.getIsNewSession()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 119
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets a value indicating whether the session is new or not. </p>
  syntax:
    content: public boolean getIsNewSession()
    return:
      type: 4fc6e284
      description: <p>True if the session is new, false otherwise. </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.getRequestStartTimeTicks()
  id: getRequestStartTimeTicks()
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: getRequestStartTimeTicks()
  fullName: long com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.getRequestStartTimeTicks()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 71
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets the request start time in ticks </p>
  syntax:
    content: public long getRequestStartTimeTicks()
    return:
      type: 0364520f
      description: <p>Request start time in ticks </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.getSessionCookie()
  id: getSessionCookie()
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: getSessionCookie()
  fullName: SessionCookie com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.getSessionCookie()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 87
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets the session cookie. </p>
  syntax:
    content: public SessionCookie getSessionCookie()
    return:
      type: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
      description: <p>Session cookie. </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.getUserCookie()
  id: getUserCookie()
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: getUserCookie()
  fullName: UserCookie com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.getUserCookie()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 103
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets the user cookie. </p>
  syntax:
    content: public UserCookie getUserCookie()
    return:
      type: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
      description: <p>The user cookie. </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.RequestTelemetryContext(long)
  id: RequestTelemetryContext(long)
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: RequestTelemetryContext(long ticks)
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.RequestTelemetryContext(long ticks)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 44
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Constructs new <xref href="com.microsoft.applicationinsights.web.internal._request_telemetry_context" data-throw-if-not-resolved="false"></xref> object. </p>
  syntax:
    content: public RequestTelemetryContext(long ticks)
    parameters:
    - id: ticks
      type: 0364520f
      description: <p>The time in ticks </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.RequestTelemetryContext(long,HttpServletRequest)
  id: RequestTelemetryContext(long,HttpServletRequest)
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: RequestTelemetryContext(long ticks, HttpServletRequest servletRequest)
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.RequestTelemetryContext(long ticks, HttpServletRequest servletRequest)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 53
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Constructs new <xref href="com.microsoft.applicationinsights.web.internal._request_telemetry_context" data-throw-if-not-resolved="false"></xref> object. </p>
  syntax:
    content: public RequestTelemetryContext(long ticks, HttpServletRequest servletRequest)
    parameters:
    - id: ticks
      type: 0364520f
      description: <p>The time in ticks </p>
    - id: servletRequest
      type: 81123e1c
      description: <p>The servlet request </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.setIsNewSession(boolean)
  id: setIsNewSession(boolean)
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: setIsNewSession(boolean isNewSession)
  fullName: void com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.setIsNewSession(boolean isNewSession)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 111
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Sets if the session is new or not. </p>
  syntax:
    content: public void setIsNewSession(boolean isNewSession)
    parameters:
    - id: isNewSession
      type: 4fc6e284
      description: <p>Indicates whether the session is new or not. </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.setSessionCookie(SessionCookie)
  id: setSessionCookie(SessionCookie)
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: setSessionCookie(SessionCookie sessionCookie)
  fullName: void com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.setSessionCookie(SessionCookie sessionCookie)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 79
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Sets the session cookie. </p>
  syntax:
    content: public void setSessionCookie(SessionCookie sessionCookie)
    parameters:
    - id: sessionCookie
      type: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
      description: <p>The session cookie. </p>
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context.setUserCookie(UserCookie)
  id: setUserCookie(UserCookie)
  parent: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  langs:
  - java
  name: setUserCookie(UserCookie userCookie)
  fullName: void com.microsoft.applicationinsights.web.internal.RequestTelemetryContext.setUserCookie(UserCookie userCookie)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
    startLine: 95
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Sets the user cookie. </p>
  syntax:
    content: public void setUserCookie(UserCookie userCookie)
    parameters:
    - id: userCookie
      type: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
      description: <p>The user cookie. </p>
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 81123e1c
  spec.java:
  - name: HttpServletRequest
    fullName: HttpServletRequest
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.telemetry._request_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._request_telemetry.yml
  name: RequestTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.RequestTelemetry
  type: Class
  summary: >-
    <p>Encapsulates information about a web request handled by the application.</p>

    <p>You can send information about requests processed by your web application to Application Insights by passing an instance of this class to the 'trackRequest' method of the <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public class RequestTelemetry extends BaseTelemetry<RequestData>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  name: SessionCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.SessionCookie
  type: Class
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax:
    content: public class SessionCookie
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  name: UserCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.UserCookie
  type: Class
  summary: <p>Created by yonisha on 2/7/2015. </p>
  syntax:
    content: public class UserCookie
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  name: RequestTelemetryContext
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax: *o1
