items:
- uid: com.microsoft.azure.documentdb.internal._database_account_configuration_provider
  id: _database_account_configuration_provider
  parent: com.microsoft.azure.documentdb.internal
  children:
  - com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getMaxReplicaSetSize()
  - com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getStoreConsistencyPolicy()
  href: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.yml
  langs:
  - java
  name: DatabaseAccountConfigurationProvider
  fullName: com.microsoft.azure.documentdb.internal.DatabaseAccountConfigurationProvider
  type: Interface
  source:
    remote: &o0
      path: src/main/java/com/microsoft/azure/documentdb/internal/DatabaseAccountConfigurationProvider.java
      branch: master
      repo: https://github.com/Azure/azure-documentdb-java
    path: src/main/java/com/microsoft/azure/documentdb/internal/DatabaseAccountConfigurationProvider.java
    startLine: 4
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public interface DatabaseAccountConfigurationProvider
- uid: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getMaxReplicaSetSize()
  id: getMaxReplicaSetSize()
  parent: com.microsoft.azure.documentdb.internal._database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.yml
  langs:
  - java
  name: getMaxReplicaSetSize()
  fullName: int com.microsoft.azure.documentdb.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize()
  type: Method
  source:
    remote: *o0
    path: src/main/java/com/microsoft/azure/documentdb/internal/DatabaseAccountConfigurationProvider.java
    startLine: 7
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public int getMaxReplicaSetSize()
    return:
      type: f75371fa
- uid: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getStoreConsistencyPolicy()
  id: getStoreConsistencyPolicy()
  parent: com.microsoft.azure.documentdb.internal._database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.yml
  langs:
  - java
  name: getStoreConsistencyPolicy()
  fullName: ConsistencyLevel com.microsoft.azure.documentdb.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()
  type: Method
  source:
    remote: *o0
    path: src/main/java/com/microsoft/azure/documentdb/internal/DatabaseAccountConfigurationProvider.java
    startLine: 5
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public ConsistencyLevel getStoreConsistencyPolicy()
    return:
      type: com.microsoft.azure.documentdb._consistency_level
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  parent: com.microsoft.azure.documentdb.internal
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  name: BaseDatabaseAccountConfigurationProvider
  fullName: com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider
  type: Class
  syntax:
    content: public class BaseDatabaseAccountConfigurationProvider implements DatabaseAccountConfigurationProvider
- uid: com.microsoft.azure.documentdb._consistency_level
  parent: com.microsoft.azure.documentdb
  href: com.microsoft.azure.documentdb._consistency_level.yml
  name: ConsistencyLevel
  fullName: com.microsoft.azure.documentdb.ConsistencyLevel
  type: Enum
  summary: >-
    <p>Represents the consistency levels supported for DocumentDB client operations. </p>

    <p>The requested <xref href="com.microsoft.azure.documentdb._consistency_level" data-throw-if-not-resolved="false"></xref> must match or be weaker than that provisioned for the database account. Consistency levels by order of strength are Strong, BoundedStaleness, Session and Eventual. </p>
  syntax:
    content: public enum ConsistencyLevel
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.getStoreConsistencyPolicy()
  parent: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  name: getStoreConsistencyPolicy()
  fullName: ConsistencyLevel com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()
  type: Method
  syntax:
    content: public ConsistencyLevel getStoreConsistencyPolicy()
    return:
      type: com.microsoft.azure.documentdb._consistency_level
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.getMaxReplicaSetSize()
  parent: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  name: getMaxReplicaSetSize()
  fullName: int com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize()
  type: Method
  syntax:
    content: public int getMaxReplicaSetSize()
    return:
      type: f75371fa
