items:
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests
  id: _application_insights_appender_tests
  parent: com.microsoft.applicationinsights.log4j.v1__2
  children:
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.setup()
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.testAppenderSendsGivenEvent()
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.testInstrumentationKeyIsLoadedFromConfiguration()
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.yml
  langs:
  - java
  name: ApplicationInsightsAppenderTests
  fullName: com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests
  type: Class
  source:
    remote: &o0
      path: logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java
    startLine: 31
  package: com.microsoft.applicationinsights.log4j.v1__2
  syntax:
    content: public class ApplicationInsightsAppenderTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.setup()
  id: setup()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.yml
  langs:
  - java
  name: setup()
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests.setup()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java
    startLine: 42
  package: com.microsoft.applicationinsights.log4j.v1__2
  syntax:
    content: public void setup()
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.testAppenderSendsGivenEvent()
  id: testAppenderSendsGivenEvent()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.yml
  langs:
  - java
  name: testAppenderSendsGivenEvent()
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests.testAppenderSendsGivenEvent()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java
    startLine: 59
  package: com.microsoft.applicationinsights.log4j.v1__2
  syntax:
    content: public void testAppenderSendsGivenEvent()
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.testInstrumentationKeyIsLoadedFromConfiguration()
  id: testInstrumentationKeyIsLoadedFromConfiguration()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender_tests.yml
  langs:
  - java
  name: testInstrumentationKeyIsLoadedFromConfiguration()
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests.testInstrumentationKeyIsLoadedFromConfiguration()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java
    startLine: 51
  package: com.microsoft.applicationinsights.log4j.v1__2
  syntax:
    content: public void testInstrumentationKeyIsLoadedFromConfiguration()
references:
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  parent: com.microsoft.applicationinsights.log4j.v1__2
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  name: ApplicationInsightsAppender
  fullName: com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender
  type: Class
  syntax:
    content: public class ApplicationInsightsAppender
