items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  id: _windows_performance_counter_data_test
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testAllAreOk()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testEmptyCategoryName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testEmptyCounterName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testEmptyDisplayName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testNullCategoryName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testNullCDisplayName()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testNullCounterName()
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: WindowsPerformanceCounterDataTest
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public class WindowsPerformanceCounterDataTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testAllAreOk()
  id: testAllAreOk()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testAllAreOk()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testAllAreOk()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testAllAreOk()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testEmptyCategoryName()
  id: testEmptyCategoryName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testEmptyCategoryName()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testEmptyCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testEmptyCategoryName()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testEmptyCounterName()
  id: testEmptyCounterName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testEmptyCounterName()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testEmptyCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testEmptyCounterName()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testEmptyDisplayName()
  id: testEmptyDisplayName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testEmptyDisplayName()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testEmptyDisplayName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 93
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testEmptyDisplayName()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testNullCategoryName()
  id: testNullCategoryName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testNullCategoryName()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testNullCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testNullCategoryName()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testNullCDisplayName()
  id: testNullCDisplayName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testNullCDisplayName()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testNullCDisplayName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 84
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testNullCDisplayName()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.testNullCounterName()
  id: testNullCounterName()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data_test.yml
  langs:
  - java
  name: testNullCounterName()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterDataTest.testNullCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testNullCounterName()
references: []
