items:
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  id: _agent_built_in_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.AgentBuiltInConfiguration(List<ClassInstrumentationData>,boolean,boolean,boolean,boolean,boolean,Long,long,DataOfConfigurationForException)
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getDataOfConfigurationForException()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getRedisThresholdInMS()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getSimpleBuiltInClasses()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getSqlMaxQueryLimitInMS()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isEnabled()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isHibernateEnabled()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isHttpEnabled()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isJdbcEnabled()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isJmxEnabled()
  - com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isRedisEnabled()
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: AgentBuiltInConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 30
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax:
    content: public class AgentBuiltInConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.AgentBuiltInConfiguration(List<ClassInstrumentationData>,boolean,boolean,boolean,boolean,boolean,Long,long,DataOfConfigurationForException)
  id: AgentBuiltInConfiguration(List<ClassInstrumentationData>,boolean,boolean,boolean,boolean,boolean,Long,long,DataOfConfigurationForException)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: AgentBuiltInConfiguration(List<ClassInstrumentationData> simpleBuiltInClasses, boolean httpEnabled, boolean jdbcEnabled, boolean hibernateEnabled, boolean jedisEnabled, boolean jmxEnabled, Long maxSqlQueryLimitInMS, long redisThresholdInMS, DataOfConfigurationForException dataOfConfigurationForException)
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.AgentBuiltInConfiguration(List<ClassInstrumentationData> simpleBuiltInClasses, boolean httpEnabled, boolean jdbcEnabled, boolean hibernateEnabled, boolean jedisEnabled, boolean jmxEnabled, Long maxSqlQueryLimitInMS, long redisThresholdInMS, DataOfConfigurationForException dataOfConfigurationForException)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 42
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfiguration(List<ClassInstrumentationData> simpleBuiltInClasses, boolean httpEnabled, boolean jdbcEnabled, boolean hibernateEnabled, boolean jedisEnabled, boolean jmxEnabled, Long maxSqlQueryLimitInMS, long redisThresholdInMS, DataOfConfigurationForException dataOfConfigurationForException)
    parameters:
    - id: simpleBuiltInClasses
      type: 5618da2dcom.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
    - id: httpEnabled
      type: 4fc6e284
    - id: jdbcEnabled
      type: 4fc6e284
    - id: hibernateEnabled
      type: 4fc6e284
    - id: jedisEnabled
      type: 4fc6e284
    - id: jmxEnabled
      type: 4fc6e284
    - id: maxSqlQueryLimitInMS
      type: 34f09483
    - id: redisThresholdInMS
      type: 0364520f
    - id: dataOfConfigurationForException
      type: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getDataOfConfigurationForException()
  id: getDataOfConfigurationForException()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: getDataOfConfigurationForException()
  fullName: DataOfConfigurationForException com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.getDataOfConfigurationForException()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 98
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public DataOfConfigurationForException getDataOfConfigurationForException()
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getRedisThresholdInMS()
  id: getRedisThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: getRedisThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.getRedisThresholdInMS()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 90
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public long getRedisThresholdInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getSimpleBuiltInClasses()
  id: getSimpleBuiltInClasses()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: getSimpleBuiltInClasses()
  fullName: List<ClassInstrumentationData> com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.getSimpleBuiltInClasses()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 102
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public List<ClassInstrumentationData> getSimpleBuiltInClasses()
    return:
      type: 5618da2dcom.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.getSqlMaxQueryLimitInMS()
  id: getSqlMaxQueryLimitInMS()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: getSqlMaxQueryLimitInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.getSqlMaxQueryLimitInMS()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 82
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public long getSqlMaxQueryLimitInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isEnabled()
  id: isEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: isEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.isEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 66
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isHibernateEnabled()
  id: isHibernateEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: isHibernateEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.isHibernateEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 78
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isHibernateEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isHttpEnabled()
  id: isHttpEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: isHttpEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.isHttpEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 70
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isHttpEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isJdbcEnabled()
  id: isJdbcEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: isJdbcEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.isJdbcEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 74
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isJdbcEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isJmxEnabled()
  id: isJmxEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: isJmxEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.isJmxEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 94
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isJmxEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.isRedisEnabled()
  id: isRedisEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  langs:
  - java
  name: isRedisEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration.isRedisEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
    startLine: 86
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isRedisEnabled()
    return:
      type: 4fc6e284
references:
- uid: 5618da2dcom.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    name: ClassInstrumentationData
    fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
    href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  - name: '>'
    fullName: '>'
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 34f09483
  spec.java:
  - name: Long
    fullName: Long
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  name: DataOfConfigurationForException
  fullName: com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException
  type: Class
  summary: <p>Created by gupele on 8/18/2016. </p>
  syntax:
    content: public class DataOfConfigurationForException
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
