items:
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer
  id: _application_insights_writer
  parent: com.microsoft.applicationinsights.collectd
  children:
  - com.microsoft.applicationinsights.collectd._application_insights_writer.ApplicationInsightsWriter()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.ApplicationInsightsWriter(TelemetryClient,ApplicationInsightsWriterLogger)
  - com.microsoft.applicationinsights.collectd._application_insights_writer.config(OConfigItem)
  - com.microsoft.applicationinsights.collectd._application_insights_writer.generateMetricName(ValueList,DataSource)
  - com.microsoft.applicationinsights.collectd._application_insights_writer.init()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.METRIC_SOURCE_TAG_KEY()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.METRIC_SOURCE_TAG_VALUE()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.shutdown()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.TELEMETRY_HOST_PROPERTY_NAME()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.UNDEFINED_HOST()
  - com.microsoft.applicationinsights.collectd._application_insights_writer.write(ValueList)
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: ApplicationInsightsWriter
  fullName: com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter
  type: Class
  source:
    remote: &o0
      path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 48
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Created by yonisha on 4/26/2015. </p>
  syntax:
    content: public class ApplicationInsightsWriter
  inheritance:
  - java.lang.Object
  - CollectdConfigInterface
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.ApplicationInsightsWriter()
  id: ApplicationInsightsWriter()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: ApplicationInsightsWriter()
  fullName: com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.ApplicationInsightsWriter()
  type: Constructor
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 84
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Constructs new  object. </p>
  syntax:
    content: public ApplicationInsightsWriter()
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.ApplicationInsightsWriter(TelemetryClient,ApplicationInsightsWriterLogger)
  id: ApplicationInsightsWriter(TelemetryClient,ApplicationInsightsWriterLogger)
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: ApplicationInsightsWriter(TelemetryClient telemetryClient, ApplicationInsightsWriterLogger logger)
  fullName: com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.ApplicationInsightsWriter(TelemetryClient telemetryClient, ApplicationInsightsWriterLogger logger)
  type: Constructor
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 100
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Constructs new  object. </p>
  syntax:
    content: protected ApplicationInsightsWriter(TelemetryClient telemetryClient, ApplicationInsightsWriterLogger logger)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The telemetry client to use. </p>
    - id: logger
      type: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
      description: <p>The logger to use. </p>
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.config(OConfigItem)
  id: config(OConfigItem)
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: config(OConfigItem configuration)
  fullName: int com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.config(OConfigItem configuration)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 115
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Reads the configuration provided for the writer plugin. </p>
  syntax:
    content: public int config(OConfigItem configuration)
    parameters:
    - id: configuration
      type: 910efc2e
      description: <p>The configuration. </p>
    return:
      type: f75371fa
      description: <p>Zero on success, non-zero otherwise. Non-zero values will disable the plugin entirely. </p>
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.generateMetricName(ValueList,DataSource)
  id: generateMetricName(ValueList,DataSource)
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: generateMetricName(ValueList valueList, DataSource dataSource)
  fullName: static String com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.generateMetricName(ValueList valueList, DataSource dataSource)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 275
  package: com.microsoft.applicationinsights.collectd
  syntax:
    content: protected static String generateMetricName(ValueList valueList, DataSource dataSource)
    parameters:
    - id: valueList
      type: 6649f32d
    - id: dataSource
      type: 00b5de54
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.init()
  id: init()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: init()
  fullName: int com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.init()
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 142
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Initializes the writer plugin. </p>
  syntax:
    content: public int init()
    return:
      type: f75371fa
      description: <p>Zero on success, non-zero otherwise. Non-zero values will disable the plugin entirely. </p>
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.METRIC_SOURCE_TAG_KEY()
  id: METRIC_SOURCE_TAG_KEY()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: METRIC_SOURCE_TAG_KEY
  fullName: final String com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.METRIC_SOURCE_TAG_KEY
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 57
  package: com.microsoft.applicationinsights.collectd
  syntax:
    content: protected static final String METRIC_SOURCE_TAG_KEY= "MetricSource"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.METRIC_SOURCE_TAG_VALUE()
  id: METRIC_SOURCE_TAG_VALUE()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: METRIC_SOURCE_TAG_VALUE
  fullName: final String com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.METRIC_SOURCE_TAG_VALUE
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 58
  package: com.microsoft.applicationinsights.collectd
  syntax:
    content: protected static final String METRIC_SOURCE_TAG_VALUE= "CollectD-Plugin"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.shutdown()
  id: shutdown()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: shutdown()
  fullName: int com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.shutdown()
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 162
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Shutting down the writer plugin and flushes the telemetries from memory. </p>
  syntax:
    content: public int shutdown()
    return:
      type: f75371fa
      description: <p>Zero on success, non-zero otherwise. </p>
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.TELEMETRY_HOST_PROPERTY_NAME()
  id: TELEMETRY_HOST_PROPERTY_NAME()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: TELEMETRY_HOST_PROPERTY_NAME
  fullName: final String com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.TELEMETRY_HOST_PROPERTY_NAME
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 59
  package: com.microsoft.applicationinsights.collectd
  syntax:
    content: protected static final String TELEMETRY_HOST_PROPERTY_NAME= "CollectD-Host"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.UNDEFINED_HOST()
  id: UNDEFINED_HOST()
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: UNDEFINED_HOST
  fullName: final String com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.UNDEFINED_HOST
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 56
  package: com.microsoft.applicationinsights.collectd
  syntax:
    content: protected static final String UNDEFINED_HOST= "N/A"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer.write(ValueList)
  id: write(ValueList)
  parent: com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  langs:
  - java
  name: write(ValueList valueList)
  fullName: int com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter.write(ValueList valueList)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 174
  package: com.microsoft.applicationinsights.collectd
  summary: <p>Writes the given values to Application Insights. </p>
  syntax:
    content: public int write(ValueList valueList)
    parameters:
    - id: valueList
      type: 6649f32d
      description: <p>The values to be sent. </p>
    return:
      type: f75371fa
      description: <p>Zero on success, non-zero otherwise. </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: 910efc2e
  spec.java:
  - name: OConfigItem
    fullName: OConfigItem
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 6649f32d
  spec.java:
  - name: ValueList
    fullName: ValueList
- uid: 00b5de54
  spec.java:
  - name: DataSource
    fullName: DataSource
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  parent: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  name: PluginExclusion
  fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion
  type: Class
  summary: >-
    <p>Created by yonisha on 5/5/2015.</p>

    <p>This class represents a plugin and its data source to be excluded. </p>
  syntax:
    content: public class PluginExclusion
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  parent: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  name: ApplicationInsightsWriterLogger
  fullName: com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger
  type: Class
  summary: <p>Created by yonisha on 5/4/2015. </p>
  syntax:
    content: public class ApplicationInsightsWriterLogger
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry.yml
  name: MetricTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.MetricTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track metrics. </p>
  syntax:
    content: public class MetricTelemetry
