items:
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element
  id: _channel_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getData()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getDeveloperMode()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getEndpointAddress()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getFlushIntervalInSeconds()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getMaxTelemetryBufferCapacity()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getThrottling()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.getType()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.isMaxTransmissionStorageFilesCapacityInMB()
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setDeveloperMode(boolean)
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setEndpointAddress(String)
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setFlushIntervalInSeconds(String)
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setMaxTelemetryBufferCapacity(String)
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setMaxTransmissionStorageFilesCapacityInMB(String)
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setThrottling(boolean)
  - com.microsoft.applicationinsights.internal.config._channel_xml_element.setType(String)
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: ChannelXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ChannelXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class ChannelXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getData()
  fullName: Map<String, String> com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 108
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public Map<String, String> getData()
    return:
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getDeveloperMode()
  id: getDeveloperMode()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getDeveloperMode()
  fullName: boolean com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getDeveloperMode()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 72
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public boolean getDeveloperMode()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getEndpointAddress()
  id: getEndpointAddress()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getEndpointAddress()
  fullName: String com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getEndpointAddress()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getEndpointAddress()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getFlushIntervalInSeconds()
  id: getFlushIntervalInSeconds()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getFlushIntervalInSeconds()
  fullName: String com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getFlushIntervalInSeconds()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 90
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getFlushIntervalInSeconds()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getMaxTelemetryBufferCapacity()
  id: getMaxTelemetryBufferCapacity()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getMaxTelemetryBufferCapacity()
  fullName: String com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getMaxTelemetryBufferCapacity()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 81
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getMaxTelemetryBufferCapacity()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getThrottling()
  id: getThrottling()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getThrottling()
  fullName: boolean com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getThrottling()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public boolean getThrottling()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: getType()
  fullName: String com.microsoft.applicationinsights.internal.config.ChannelXmlElement.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.isMaxTransmissionStorageFilesCapacityInMB()
  id: isMaxTransmissionStorageFilesCapacityInMB()
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: isMaxTransmissionStorageFilesCapacityInMB()
  fullName: String com.microsoft.applicationinsights.internal.config.ChannelXmlElement.isMaxTransmissionStorageFilesCapacityInMB()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 99
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String isMaxTransmissionStorageFilesCapacityInMB()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setDeveloperMode(boolean)
  id: setDeveloperMode(boolean)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setDeveloperMode(boolean developerMode)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setDeveloperMode(boolean developerMode)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 77
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setDeveloperMode(boolean developerMode)
    parameters:
    - id: developerMode
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setEndpointAddress(String)
  id: setEndpointAddress(String)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setEndpointAddress(String endpointAddress)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setEndpointAddress(String endpointAddress)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setEndpointAddress(String endpointAddress)
    parameters:
    - id: endpointAddress
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setFlushIntervalInSeconds(String)
  id: setFlushIntervalInSeconds(String)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setFlushIntervalInSeconds(String flushIntervalInSeconds)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setFlushIntervalInSeconds(String flushIntervalInSeconds)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setFlushIntervalInSeconds(String flushIntervalInSeconds)
    parameters:
    - id: flushIntervalInSeconds
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setMaxTelemetryBufferCapacity(String)
  id: setMaxTelemetryBufferCapacity(String)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setMaxTelemetryBufferCapacity(String maxTelemetryBufferCapacity)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setMaxTelemetryBufferCapacity(String maxTelemetryBufferCapacity)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 86
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setMaxTelemetryBufferCapacity(String maxTelemetryBufferCapacity)
    parameters:
    - id: maxTelemetryBufferCapacity
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setMaxTransmissionStorageFilesCapacityInMB(String)
  id: setMaxTransmissionStorageFilesCapacityInMB(String)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setMaxTransmissionStorageFilesCapacityInMB(String maxTransmissionStorageFilesCapacityInMB)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setMaxTransmissionStorageFilesCapacityInMB(String maxTransmissionStorageFilesCapacityInMB)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 104
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setMaxTransmissionStorageFilesCapacityInMB(String maxTransmissionStorageFilesCapacityInMB)
    parameters:
    - id: maxTransmissionStorageFilesCapacityInMB
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setThrottling(boolean)
  id: setThrottling(boolean)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setThrottling(boolean throttling)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setThrottling(boolean throttling)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setThrottling(boolean throttling)
    parameters:
    - id: throttling
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.internal.config._channel_xml_element
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.internal.config.ChannelXmlElement.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
