items:
- uid: com.microsoft.applicationinsights.internal.channel.common._apache_sender42_test
  id: _apache_sender42_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._apache_sender42_test.testHttpClientType()
  href: com.microsoft.applicationinsights.internal.channel.common._apache_sender42_test.yml
  langs:
  - java
  name: ApacheSender42Test
  fullName: com.microsoft.applicationinsights.internal.channel.common.ApacheSender42Test
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender42Test.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender42Test.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class ApacheSender42Test
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._apache_sender42_test.testHttpClientType()
  id: testHttpClientType()
  parent: com.microsoft.applicationinsights.internal.channel.common._apache_sender42_test
  href: com.microsoft.applicationinsights.internal.channel.common._apache_sender42_test.yml
  langs:
  - java
  name: testHttpClientType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ApacheSender42Test.testHttpClientType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender42Test.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testHttpClientType()
references: []
