items:
- uid: com.microsoft.applicationinsights.internal.agent._agent_self_connector
  id: _agent_self_connector
  parent: com.microsoft.applicationinsights.internal.agent
  children:
  - com.microsoft.applicationinsights.internal.agent._agent_self_connector.AgentSelfConnector()
  href: com.microsoft.applicationinsights.internal.agent._agent_self_connector.yml
  langs:
  - java
  name: AgentSelfConnector
  fullName: com.microsoft.applicationinsights.internal.agent.AgentSelfConnector
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentSelfConnector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentSelfConnector.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.agent
  summary: >-
    <p>A utility class to load the core SDK into the Agent This is an internal class that should only used by the Agent</p>

    <p>Created by gupele on 9/11/2016. </p>
  syntax:
    content: public class AgentSelfConnector
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.agent._agent_self_connector.AgentSelfConnector()
  id: AgentSelfConnector()
  parent: com.microsoft.applicationinsights.internal.agent._agent_self_connector
  href: com.microsoft.applicationinsights.internal.agent._agent_self_connector.yml
  langs:
  - java
  name: AgentSelfConnector()
  fullName: com.microsoft.applicationinsights.internal.agent.AgentSelfConnector.AgentSelfConnector()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentSelfConnector.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public AgentSelfConnector()
references: []
