items:
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  id: _s_d_k_logger_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getBaseFolder()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getData()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getLevel()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getNumberOfFiles()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getNumberOfTotalSizeInMB()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getType()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getUniquePrefix()
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setBaseFolder(String)
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setLevel(String)
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setNumberOfFiles(String)
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setNumberOfTotalSizeInMB(String)
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setType(String)
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setUniquePrefix(String)
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: SDKLoggerXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class SDKLoggerXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getBaseFolder()
  id: getBaseFolder()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getBaseFolder()
  fullName: String com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getBaseFolder()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getBaseFolder()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getData()
  fullName: Map<String, String> com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public Map<String, String> getData()
    return:
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getLevel()
  id: getLevel()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getLevel()
  fullName: String com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getLevel()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getLevel()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getNumberOfFiles()
  id: getNumberOfFiles()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getNumberOfFiles()
  fullName: String com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getNumberOfFiles()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 77
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getNumberOfFiles()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getNumberOfTotalSizeInMB()
  id: getNumberOfTotalSizeInMB()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getNumberOfTotalSizeInMB()
  fullName: String com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getNumberOfTotalSizeInMB()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 86
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getNumberOfTotalSizeInMB()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getType()
  fullName: String com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.getUniquePrefix()
  id: getUniquePrefix()
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: getUniquePrefix()
  fullName: String com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.getUniquePrefix()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getUniquePrefix()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setBaseFolder(String)
  id: setBaseFolder(String)
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: setBaseFolder(String baseFolder)
  fullName: void com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.setBaseFolder(String baseFolder)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 73
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setBaseFolder(String baseFolder)
    parameters:
    - id: baseFolder
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setLevel(String)
  id: setLevel(String)
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: setLevel(String level)
  fullName: void com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.setLevel(String level)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setLevel(String level)
    parameters:
    - id: level
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setNumberOfFiles(String)
  id: setNumberOfFiles(String)
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: setNumberOfFiles(String numberOfFiles)
  fullName: void com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.setNumberOfFiles(String numberOfFiles)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setNumberOfFiles(String numberOfFiles)
    parameters:
    - id: numberOfFiles
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setNumberOfTotalSizeInMB(String)
  id: setNumberOfTotalSizeInMB(String)
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: setNumberOfTotalSizeInMB(String numberOfTotalSizeInMB)
  fullName: void com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.setNumberOfTotalSizeInMB(String numberOfTotalSizeInMB)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setNumberOfTotalSizeInMB(String numberOfTotalSizeInMB)
    parameters:
    - id: numberOfTotalSizeInMB
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.setUniquePrefix(String)
  id: setUniquePrefix(String)
  parent: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  langs:
  - java
  name: setUniquePrefix(String uniquePrefix)
  fullName: void com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement.setUniquePrefix(String uniquePrefix)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setUniquePrefix(String uniquePrefix)
    parameters:
    - id: uniquePrefix
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
