items:
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config
  id: _encryption_config
  parent: com.microsoft.azure.management.datalake.store.models
  children:
  - com.microsoft.azure.management.datalake.store.models._encryption_config.keyVaultMetaInfo()
  - com.microsoft.azure.management.datalake.store.models._encryption_config.type()
  - com.microsoft.azure.management.datalake.store.models._encryption_config.withKeyVaultMetaInfo(KeyVaultMetaInfo)
  - com.microsoft.azure.management.datalake.store.models._encryption_config.withType(EncryptionConfigType)
  href: com.microsoft.azure.management.datalake.store.models._encryption_config.yml
  langs:
  - java
  name: EncryptionConfig
  fullName: com.microsoft.azure.management.datalake.store.models.EncryptionConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-datalake-store/src/main/java/com/microsoft/azure/management/datalake/store/models/EncryptionConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-datalake-store/src/main/java/com/microsoft/azure/management/datalake/store/models/EncryptionConfig.java
    startLine: 14
  package: com.microsoft.azure.management.datalake.store.models
  summary: <p>The <xref href="com.microsoft.azure.management.datalake.store.models._encryption_config" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: &o1
    content: public class EncryptionConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config.keyVaultMetaInfo()
  id: keyVaultMetaInfo()
  parent: com.microsoft.azure.management.datalake.store.models._encryption_config
  href: com.microsoft.azure.management.datalake.store.models._encryption_config.yml
  langs:
  - java
  name: keyVaultMetaInfo()
  fullName: KeyVaultMetaInfo com.microsoft.azure.management.datalake.store.models.EncryptionConfig.keyVaultMetaInfo()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-datalake-store/src/main/java/com/microsoft/azure/management/datalake/store/models/EncryptionConfig.java
    startLine: 53
  package: com.microsoft.azure.management.datalake.store.models
  summary: >-
    <p>Get the keyVaultMetaInfo value.</p>

    <p></p>
  syntax:
    content: public KeyVaultMetaInfo keyVaultMetaInfo()
    return:
      type: com.microsoft.azure.management.datalake.store.models._key_vault_meta_info
      description: <p>the keyVaultMetaInfo value </p>
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config.type()
  id: type()
  parent: com.microsoft.azure.management.datalake.store.models._encryption_config
  href: com.microsoft.azure.management.datalake.store.models._encryption_config.yml
  langs:
  - java
  name: type()
  fullName: EncryptionConfigType com.microsoft.azure.management.datalake.store.models.EncryptionConfig.type()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-datalake-store/src/main/java/com/microsoft/azure/management/datalake/store/models/EncryptionConfig.java
    startLine: 33
  package: com.microsoft.azure.management.datalake.store.models
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public EncryptionConfigType type()
    return:
      type: com.microsoft.azure.management.datalake.store.models._encryption_config_type
      description: <p>the type value </p>
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config.withKeyVaultMetaInfo(KeyVaultMetaInfo)
  id: withKeyVaultMetaInfo(KeyVaultMetaInfo)
  parent: com.microsoft.azure.management.datalake.store.models._encryption_config
  href: com.microsoft.azure.management.datalake.store.models._encryption_config.yml
  langs:
  - java
  name: withKeyVaultMetaInfo(KeyVaultMetaInfo keyVaultMetaInfo)
  fullName: EncryptionConfig com.microsoft.azure.management.datalake.store.models.EncryptionConfig.withKeyVaultMetaInfo(KeyVaultMetaInfo keyVaultMetaInfo)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-datalake-store/src/main/java/com/microsoft/azure/management/datalake/store/models/EncryptionConfig.java
    startLine: 63
  package: com.microsoft.azure.management.datalake.store.models
  summary: >-
    <p>Set the keyVaultMetaInfo value.</p>

    <p></p>
  syntax:
    content: public EncryptionConfig withKeyVaultMetaInfo(KeyVaultMetaInfo keyVaultMetaInfo)
    parameters:
    - id: keyVaultMetaInfo
      type: com.microsoft.azure.management.datalake.store.models._key_vault_meta_info
      description: <p>the keyVaultMetaInfo value to set </p>
    return:
      type: com.microsoft.azure.management.datalake.store.models._encryption_config
      description: <p>the <xref href="com.microsoft.azure.management.datalake.store.models._encryption_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config.withType(EncryptionConfigType)
  id: withType(EncryptionConfigType)
  parent: com.microsoft.azure.management.datalake.store.models._encryption_config
  href: com.microsoft.azure.management.datalake.store.models._encryption_config.yml
  langs:
  - java
  name: withType(EncryptionConfigType type)
  fullName: EncryptionConfig com.microsoft.azure.management.datalake.store.models.EncryptionConfig.withType(EncryptionConfigType type)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-datalake-store/src/main/java/com/microsoft/azure/management/datalake/store/models/EncryptionConfig.java
    startLine: 43
  package: com.microsoft.azure.management.datalake.store.models
  summary: >-
    <p>Set the type value.</p>

    <p></p>
  syntax:
    content: public EncryptionConfig withType(EncryptionConfigType type)
    parameters:
    - id: type
      type: com.microsoft.azure.management.datalake.store.models._encryption_config_type
      description: <p>the type value to set </p>
    return:
      type: com.microsoft.azure.management.datalake.store.models._encryption_config
      description: <p>the <xref href="com.microsoft.azure.management.datalake.store.models._encryption_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config_type
  parent: com.microsoft.azure.management.datalake.store.models
  href: com.microsoft.azure.management.datalake.store.models._encryption_config_type.yml
  name: EncryptionConfigType
  fullName: com.microsoft.azure.management.datalake.store.models.EncryptionConfigType
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.datalake.store.models._encryption_config_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum EncryptionConfigType
- uid: com.microsoft.azure.management.datalake.store.models._key_vault_meta_info
  parent: com.microsoft.azure.management.datalake.store.models
  href: com.microsoft.azure.management.datalake.store.models._key_vault_meta_info.yml
  name: KeyVaultMetaInfo
  fullName: com.microsoft.azure.management.datalake.store.models.KeyVaultMetaInfo
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.datalake.store.models._key_vault_meta_info" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class KeyVaultMetaInfo
- uid: com.microsoft.azure.management.datalake.store.models._encryption_config
  parent: com.microsoft.azure.management.datalake.store.models
  href: com.microsoft.azure.management.datalake.store.models._encryption_config.yml
  name: EncryptionConfig
  fullName: com.microsoft.azure.management.datalake.store.models.EncryptionConfig
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.datalake.store.models._encryption_config" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: *o1
