items:
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner
  id: _push_settings_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._push_settings_inner.dynamicTagsJson()
  - com.microsoft.azure.management.website.implementation._push_settings_inner.isPushEnabled()
  - com.microsoft.azure.management.website.implementation._push_settings_inner.tagsRequiringAuth()
  - com.microsoft.azure.management.website.implementation._push_settings_inner.tagWhitelistJson()
  - com.microsoft.azure.management.website.implementation._push_settings_inner.withDynamicTagsJson(String)
  - com.microsoft.azure.management.website.implementation._push_settings_inner.withIsPushEnabled(Boolean)
  - com.microsoft.azure.management.website.implementation._push_settings_inner.withTagsRequiringAuth(String)
  - com.microsoft.azure.management.website.implementation._push_settings_inner.withTagWhitelistJson(String)
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: PushSettingsInner
  fullName: com.microsoft.azure.management.website.implementation.PushSettingsInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 14
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Push settings for the Web App. </p>
  syntax: &o1
    content: public class PushSettingsInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.dynamicTagsJson()
  id: dynamicTagsJson()
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: dynamicTagsJson()
  fullName: String com.microsoft.azure.management.website.implementation.PushSettingsInner.dynamicTagsJson()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 103
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the dynamicTagsJson value.</p>

    <p></p>
  syntax:
    content: public String dynamicTagsJson()
    return:
      type: "26831127"
      description: <p>the dynamicTagsJson value </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.isPushEnabled()
  id: isPushEnabled()
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: isPushEnabled()
  fullName: Boolean com.microsoft.azure.management.website.implementation.PushSettingsInner.isPushEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 43
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the isPushEnabled value.</p>

    <p></p>
  syntax:
    content: public Boolean isPushEnabled()
    return:
      type: 866c2227
      description: <p>the isPushEnabled value </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.tagsRequiringAuth()
  id: tagsRequiringAuth()
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: tagsRequiringAuth()
  fullName: String com.microsoft.azure.management.website.implementation.PushSettingsInner.tagsRequiringAuth()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 83
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the tagsRequiringAuth value.</p>

    <p></p>
  syntax:
    content: public String tagsRequiringAuth()
    return:
      type: "26831127"
      description: <p>the tagsRequiringAuth value </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.tagWhitelistJson()
  id: tagWhitelistJson()
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: tagWhitelistJson()
  fullName: String com.microsoft.azure.management.website.implementation.PushSettingsInner.tagWhitelistJson()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 63
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the tagWhitelistJson value.</p>

    <p></p>
  syntax:
    content: public String tagWhitelistJson()
    return:
      type: "26831127"
      description: <p>the tagWhitelistJson value </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.withDynamicTagsJson(String)
  id: withDynamicTagsJson(String)
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: withDynamicTagsJson(String dynamicTagsJson)
  fullName: PushSettingsInner com.microsoft.azure.management.website.implementation.PushSettingsInner.withDynamicTagsJson(String dynamicTagsJson)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 113
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the dynamicTagsJson value.</p>

    <p></p>
  syntax:
    content: public PushSettingsInner withDynamicTagsJson(String dynamicTagsJson)
    parameters:
    - id: dynamicTagsJson
      type: "26831127"
      description: <p>the dynamicTagsJson value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._push_settings_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._push_settings_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.withIsPushEnabled(Boolean)
  id: withIsPushEnabled(Boolean)
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: withIsPushEnabled(Boolean isPushEnabled)
  fullName: PushSettingsInner com.microsoft.azure.management.website.implementation.PushSettingsInner.withIsPushEnabled(Boolean isPushEnabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 53
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the isPushEnabled value.</p>

    <p></p>
  syntax:
    content: public PushSettingsInner withIsPushEnabled(Boolean isPushEnabled)
    parameters:
    - id: isPushEnabled
      type: 866c2227
      description: <p>the isPushEnabled value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._push_settings_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._push_settings_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.withTagsRequiringAuth(String)
  id: withTagsRequiringAuth(String)
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: withTagsRequiringAuth(String tagsRequiringAuth)
  fullName: PushSettingsInner com.microsoft.azure.management.website.implementation.PushSettingsInner.withTagsRequiringAuth(String tagsRequiringAuth)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 93
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the tagsRequiringAuth value.</p>

    <p></p>
  syntax:
    content: public PushSettingsInner withTagsRequiringAuth(String tagsRequiringAuth)
    parameters:
    - id: tagsRequiringAuth
      type: "26831127"
      description: <p>the tagsRequiringAuth value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._push_settings_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._push_settings_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner.withTagWhitelistJson(String)
  id: withTagWhitelistJson(String)
  parent: com.microsoft.azure.management.website.implementation._push_settings_inner
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  langs:
  - java
  name: withTagWhitelistJson(String tagWhitelistJson)
  fullName: PushSettingsInner com.microsoft.azure.management.website.implementation.PushSettingsInner.withTagWhitelistJson(String tagWhitelistJson)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/PushSettingsInner.java
    startLine: 73
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the tagWhitelistJson value.</p>

    <p></p>
  syntax:
    content: public PushSettingsInner withTagWhitelistJson(String tagWhitelistJson)
    parameters:
    - id: tagWhitelistJson
      type: "26831127"
      description: <p>the tagWhitelistJson value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._push_settings_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._push_settings_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website.implementation._push_settings_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._push_settings_inner.yml
  name: PushSettingsInner
  fullName: com.microsoft.azure.management.website.implementation.PushSettingsInner
  type: Class
  summary: <p>Push settings for the Web App. </p>
  syntax: *o1
