items:
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  id: _base_database_account_configuration_provider
  parent: com.microsoft.azure.documentdb.internal
  children:
  - com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.BaseDatabaseAccountConfigurationProvider(DatabaseAccount,ConsistencyLevel)
  - com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.getMaxReplicaSetSize()
  - com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.getStoreConsistencyPolicy()
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  langs:
  - java
  name: BaseDatabaseAccountConfigurationProvider
  fullName: com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider
  type: Class
  source:
    remote: &o0
      path: src/main/java/com/microsoft/azure/documentdb/internal/BaseDatabaseAccountConfigurationProvider.java
      branch: master
      repo: https://github.com/Azure/azure-documentdb-java
    path: src/main/java/com/microsoft/azure/documentdb/internal/BaseDatabaseAccountConfigurationProvider.java
    startLine: 5
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public class BaseDatabaseAccountConfigurationProvider implements DatabaseAccountConfigurationProvider
  inheritance:
  - java.lang.Object
  - com.microsoft.azure.documentdb.internal._database_account_configuration_provider
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.BaseDatabaseAccountConfigurationProvider(DatabaseAccount,ConsistencyLevel)
  id: BaseDatabaseAccountConfigurationProvider(DatabaseAccount,ConsistencyLevel)
  parent: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  langs:
  - java
  name: BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)
  fullName: com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)
  type: Constructor
  source:
    remote: *o0
    path: src/main/java/com/microsoft/azure/documentdb/internal/BaseDatabaseAccountConfigurationProvider.java
    startLine: 9
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)
    parameters:
    - id: databaseAccount
      type: com.microsoft.azure.documentdb._database_account
    - id: desiredConsistencyLevel
      type: com.microsoft.azure.documentdb._consistency_level
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.getMaxReplicaSetSize()
  id: getMaxReplicaSetSize()
  parent: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  langs:
  - java
  name: getMaxReplicaSetSize()
  fullName: int com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize()
  type: Method
  source:
    remote: *o0
    path: src/main/java/com/microsoft/azure/documentdb/internal/BaseDatabaseAccountConfigurationProvider.java
    startLine: 28
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public int getMaxReplicaSetSize()
    return:
      type: f75371fa
  overridden: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getMaxReplicaSetSize()
- uid: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.getStoreConsistencyPolicy()
  id: getStoreConsistencyPolicy()
  parent: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._base_database_account_configuration_provider.yml
  langs:
  - java
  name: getStoreConsistencyPolicy()
  fullName: ConsistencyLevel com.microsoft.azure.documentdb.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()
  type: Method
  source:
    remote: *o0
    path: src/main/java/com/microsoft/azure/documentdb/internal/BaseDatabaseAccountConfigurationProvider.java
    startLine: 14
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public ConsistencyLevel getStoreConsistencyPolicy()
    return:
      type: com.microsoft.azure.documentdb._consistency_level
  overridden: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getStoreConsistencyPolicy()
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.documentdb.internal._database_account_configuration_provider
  parent: com.microsoft.azure.documentdb.internal
  href: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.yml
  name: DatabaseAccountConfigurationProvider
  fullName: com.microsoft.azure.documentdb.internal.DatabaseAccountConfigurationProvider
  type: Interface
  syntax:
    content: public interface DatabaseAccountConfigurationProvider
- uid: com.microsoft.azure.documentdb._consistency_level
  parent: com.microsoft.azure.documentdb
  href: com.microsoft.azure.documentdb._consistency_level.yml
  name: ConsistencyLevel
  fullName: com.microsoft.azure.documentdb.ConsistencyLevel
  type: Enum
  summary: >-
    <p>Represents the consistency levels supported for DocumentDB client operations. </p>

    <p>The requested <xref href="com.microsoft.azure.documentdb._consistency_level" data-throw-if-not-resolved="false"></xref> must match or be weaker than that provisioned for the database account. Consistency levels by order of strength are Strong, BoundedStaleness, Session and Eventual. </p>
  syntax:
    content: public enum ConsistencyLevel
- uid: com.microsoft.azure.documentdb._database_account
  parent: com.microsoft.azure.documentdb
  href: com.microsoft.azure.documentdb._database_account.yml
  name: DatabaseAccount
  fullName: com.microsoft.azure.documentdb.DatabaseAccount
  type: Class
  summary: <p>The database account information. </p>
  syntax:
    content: public class DatabaseAccount
- uid: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getStoreConsistencyPolicy()
  parent: com.microsoft.azure.documentdb.internal._database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.yml
  name: getStoreConsistencyPolicy()
  fullName: ConsistencyLevel com.microsoft.azure.documentdb.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()
  type: Method
  syntax:
    content: public ConsistencyLevel getStoreConsistencyPolicy()
    return:
      type: com.microsoft.azure.documentdb._consistency_level
- uid: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.getMaxReplicaSetSize()
  parent: com.microsoft.azure.documentdb.internal._database_account_configuration_provider
  href: com.microsoft.azure.documentdb.internal._database_account_configuration_provider.yml
  name: getMaxReplicaSetSize()
  fullName: int com.microsoft.azure.documentdb.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize()
  type: Method
  syntax:
    content: public int getMaxReplicaSetSize()
    return:
      type: f75371fa
