items:
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl
  id: impl
  children:
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._implementations_coordinator
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.coresync.impl
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/AgentTLS.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/AgentTLS.java
    startLine: 21
  syntax:
    content: namespace impl
references:
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.yml
  name: AgentTLS
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.AgentTLS
  type: Class
  summary: >-
    <p>The class is used to set and get a name on application thread. The name can be used to fetch information on the part of the application, typically a WebApp, that owns that thread</p>

    <p>Created by gupele on 5/6/2015. </p>
  syntax:
    content: public class AgentTLS
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implementations_coordinator
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implementations_coordinator.yml
  name: ImplementationsCoordinator
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator
  type: Enum
  summary: >-
    <p>The class serves as the contact point between injected code and its real implementation. Injected code will notify on various events in the class, calling this class, the class will then delegate the call to the relevant 'client' by consulting the data on the Thread's TLS</p>

    <p>Note that the called methods should not throw any exception or error otherwise that might affect user's code</p>

    <p>Created by gupele on 5/6/2015. </p>
  syntax:
    content: public enum ImplementationsCoordinator implements AgentNotificationsHandler
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._implem5c143b42abb037284b18876ba8b7170a.yml
  name: ImplementationsCoordinator.RegistrationData
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.RegistrationData
  type: Class
  summary: <p>The data we expect to have for every thread </p>
  syntax:
    content: public class RegistrationData
