items:
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  id: _web_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  children:
  - com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  - com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  langs:
  - java
  name: WebTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule
  type: Interface
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java
    startLine: 29
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface WebTelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  id: onBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  langs:
  - java
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java
    startLine: 35
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: <p>Begin request processing. </p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  id: onEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  langs:
  - java
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java
    startLine: 42
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: <p>End request processing. </p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
references:
- uid: b0deafe7
  spec.java:
  - name: ServletRequest
    fullName: ServletRequest
- uid: 0dcfeead
  spec.java:
  - name: ServletResponse
    fullName: ServletResponse
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.yml
  name: WebRequestTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class WebRequestTrackingTelemetryModule implements WebTelemetryModule,TelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  name: WebSessionTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax:
    content: public class WebSessionTrackingTelemetryModule implements WebTelemetryModule,TelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.yml
  name: WebUserTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/7/2015. </p>
  syntax:
    content: public class WebUserTrackingTelemetryModule
- uid: com.springapp.mvc.extensions._web_request_run_id_telemetry_module
  parent: com.springapp.mvc.extensions
  href: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.yml
  name: WebRequestRunIdTelemetryModule
  fullName: com.springapp.mvc.extensions.WebRequestRunIdTelemetryModule
  type: Class
  summary: >-
    <p>Created by yonisha on 6/21/2015.</p>

    <p>This module reads teh 'runid' query parameter, if exists, from the incoming http request and adds it as a property to the RequestTelemetry sent to AI. This run ID is then used to identify requests sent as part of a test suite. </p>
  syntax:
    content: public class WebRequestRunIdTelemetryModule implements WebTelemetryModule,TelemetryModule
- uid: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  parent: com.springapp.mvc.extensions._web_request_run_id_telemetry_module
  href: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.yml
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.springapp.mvc.extensions.WebRequestRunIdTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: <p>Begin request processing. </p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.yml
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: >-
    <p>Begin request processing.</p>

    <p></p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: >-
    <p>Begin request processing.</p>

    <p></p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.yml
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: <p>Begin request processing. </p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: >-
    <p>End request processing. This method checks if the session cookie should be updated before sent back to the client. The session cookie is updated when the session is new or current session already expired.</p>

    <p></p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.yml
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: >-
    <p>End request processing.</p>

    <p></p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  parent: com.springapp.mvc.extensions._web_request_run_id_telemetry_module
  href: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.yml
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.springapp.mvc.extensions.WebRequestRunIdTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: <p>End request processing. </p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.yml
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: <p>End request processing. </p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
