items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider
  id: _runtime_exception_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.add()
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.RuntimeExceptionProvider(Map<String, ClassInstrumentationData>)
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.yml
  langs:
  - java
  name: RuntimeExceptionProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.RuntimeExceptionProvider
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/RuntimeExceptionProvider.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/RuntimeExceptionProvider.java
    startLine: 33
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  summary: <p>Created by gupele on 7/31/2016. </p>
  syntax:
    content: public class RuntimeExceptionProvider
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.add()
  id: add()
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.yml
  langs:
  - java
  name: add()
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.exceptions.RuntimeExceptionProvider.add()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/RuntimeExceptionProvider.java
    startLine: 42
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  syntax:
    content: public void add()
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.RuntimeExceptionProvider(Map<String, ClassInstrumentationData>)
  id: RuntimeExceptionProvider(Map<String, ClassInstrumentationData>)
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.yml
  langs:
  - java
  name: RuntimeExceptionProvider(Map<String, ClassInstrumentationData> classesToInstrument)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.RuntimeExceptionProvider.RuntimeExceptionProvider(Map<String, ClassInstrumentationData> classesToInstrument)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/RuntimeExceptionProvider.java
    startLine: 38
  package: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  syntax:
    content: public RuntimeExceptionProvider(Map<String, ClassInstrumentationData> classesToInstrument)
    parameters:
    - id: classesToInstrument
      type: 2108f1f4com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
references:
- uid: 2108f1f4com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
  spec.java:
  - name: 'Map<String, '
    fullName: 'Map<String, '
  - uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    name: ClassInstrumentationData
    fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
    href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
