items:
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder
  id: _built_in_instrumented_classes_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder.setSimpleBuiltInClasses(AgentBuiltInConfigurationBuilder,Element)
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder.yml
  langs:
  - java
  name: BuiltInInstrumentedClassesBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClassesBuilder
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClassesBuilder.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClassesBuilder.java
    startLine: 35
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Created by gupele on 9/5/2016. </p>
  syntax:
    content: public class BuiltInInstrumentedClassesBuilder
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder.setSimpleBuiltInClasses(AgentBuiltInConfigurationBuilder,Element)
  id: setSimpleBuiltInClasses(AgentBuiltInConfigurationBuilder,Element)
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrumented_classes_builder.yml
  langs:
  - java
  name: setSimpleBuiltInClasses(AgentBuiltInConfigurationBuilder builtInConfigurationBuilder, Element builtInElement)
  fullName: static void com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClassesBuilder.setSimpleBuiltInClasses(AgentBuiltInConfigurationBuilder builtInConfigurationBuilder, Element builtInElement)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClassesBuilder.java
    startLine: 44
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>The method will go through the classes defined in <ref refid="" kindref="compound">BuiltInInstrumentedClasses</ref> and will try to add them and the methods that are define for them to the instrumentation classes </p>
  syntax:
    content: public static void setSimpleBuiltInClasses(AgentBuiltInConfigurationBuilder builtInConfigurationBuilder, Element builtInElement)
    parameters:
    - id: builtInConfigurationBuilder
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
      description: <p>- The builder that will later build the reflection of the configuration </p>
    - id: builtInElement
      type: 47fe1a23
      description: <p>- The built in element where built in instrumentation is declared </p>
references:
- uid: 47fe1a23
  spec.java:
  - name: Element
    fullName: Element
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration_builder.yml
  name: AgentBuiltInConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfigurationBuilder
  type: Class
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax:
    content: public class AgentBuiltInConfigurationBuilder
