items:
- uid: com.microsoft.azure.batch._application_operations
  id: _application_operations
  parent: com.microsoft.azure.batch
  children:
  - com.microsoft.azure.batch._application_operations.customBehaviors()
  - com.microsoft.azure.batch._application_operations.getApplication(String)
  - com.microsoft.azure.batch._application_operations.getApplication(String,Iterable<BatchClientBehavior>)
  - com.microsoft.azure.batch._application_operations.listApplications()
  - com.microsoft.azure.batch._application_operations.listApplications(Iterable<BatchClientBehavior>)
  - com.microsoft.azure.batch._application_operations.withCustomBehaviors(Collection<BatchClientBehavior>)
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: ApplicationOperations
  fullName: com.microsoft.azure.batch.ApplicationOperations
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 24
  package: com.microsoft.azure.batch
  summary: <p>Performs application related operations on an Azure Batch account. </p>
  syntax:
    content: public class ApplicationOperations implements IInheritedBehaviors
  inheritance:
  - java.lang.Object
  - com.microsoft.azure.batch._i_inherited_behaviors
  inheritedMembers:
  - com.microsoft.azure.batch._application_operations.ApplicationOperations(BatchClient,Collection<BatchClientBehavior>)
- uid: com.microsoft.azure.batch._application_operations.customBehaviors()
  id: customBehaviors()
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: customBehaviors()
  fullName: Collection<BatchClientBehavior> com.microsoft.azure.batch.ApplicationOperations.customBehaviors()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 43
  package: com.microsoft.azure.batch
  summary: >-
    <p>Gets a list of behaviors that modify or customize requests to the Batch service.</p>

    <p></p>
  syntax:
    content: public Collection<BatchClientBehavior> customBehaviors()
    return:
      type: 12ebb11acom.microsoft.azure.batch._batch_client_behaviora08ddfce
      description: <p>A list of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref></p>
  overridden: com.microsoft.azure.batch._i_inherited_behaviors.customBehaviors()
- uid: com.microsoft.azure.batch._application_operations.getApplication(String)
  id: getApplication(String)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: getApplication(String applicationId)
  fullName: ApplicationSummary com.microsoft.azure.batch.ApplicationOperations.getApplication(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 96
  package: com.microsoft.azure.batch
  summary: >-
    <p>Gets information about the specified application.</p>

    <p></p>
  syntax:
    content: public ApplicationSummary getApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>The ID of the application to get. </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
      description: <p>An <ref refid="" kindref="compound">ApplicationSummary</ref> containing information about the specified application. </p>
  exceptions:
  - type: c8683d81
    description: <p>Exception thrown from REST call </p>
  - type: cbf33bbe
    description: <p>Exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.batch._application_operations.getApplication(String,Iterable<BatchClientBehavior>)
  id: getApplication(String,Iterable<BatchClientBehavior>)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: getApplication(String applicationId, Iterable<BatchClientBehavior> additionalBehaviors)
  fullName: ApplicationSummary com.microsoft.azure.batch.ApplicationOperations.getApplication(String applicationId, Iterable<BatchClientBehavior> additionalBehaviors)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 109
  package: com.microsoft.azure.batch
  summary: >-
    <p>Gets information about the specified application.</p>

    <p></p>
  syntax:
    content: public ApplicationSummary getApplication(String applicationId, Iterable<BatchClientBehavior> additionalBehaviors)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>The ID of the application to get. </p>
    - id: additionalBehaviors
      type: 2a13b5a5com.microsoft.azure.batch._batch_client_behaviora08ddfce
      description: <p>A collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref> instances that are applied to the Batch service request. </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
      description: <p>An <ref refid="" kindref="compound">ApplicationSummary</ref> containing information about the specified application. </p>
  exceptions:
  - type: c8683d81
    description: <p>Exception thrown from REST call </p>
  - type: cbf33bbe
    description: <p>Exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.batch._application_operations.listApplications()
  id: listApplications()
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: listApplications()
  fullName: List<ApplicationSummary> com.microsoft.azure.batch.ApplicationOperations.listApplications()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 66
  package: com.microsoft.azure.batch
  summary: >-
    <p>Enumerates the <ref refid="" kindref="compound">applications</ref> in the Batch account.</p>

    <p></p>
  syntax:
    content: public List<ApplicationSummary> listApplications()
    return:
      type: 5618da2dcom.microsoft.azure.batch.protocol.models._application_summarya08ddfce
      description: <p>A collection of <ref refid="" kindref="compound">ApplicationSummary</ref></p>
  exceptions:
  - type: c8683d81
    description: <p>Exception thrown from REST call </p>
  - type: cbf33bbe
    description: <p>Exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.batch._application_operations.listApplications(Iterable<BatchClientBehavior>)
  id: listApplications(Iterable<BatchClientBehavior>)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: listApplications(Iterable<BatchClientBehavior> additionalBehaviors)
  fullName: List<ApplicationSummary> com.microsoft.azure.batch.ApplicationOperations.listApplications(Iterable<BatchClientBehavior> additionalBehaviors)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 78
  package: com.microsoft.azure.batch
  summary: >-
    <p>Enumerates the <ref refid="" kindref="compound">applications</ref> in the Batch account.</p>

    <p></p>
  syntax:
    content: public List<ApplicationSummary> listApplications(Iterable<BatchClientBehavior> additionalBehaviors)
    parameters:
    - id: additionalBehaviors
      type: 2a13b5a5com.microsoft.azure.batch._batch_client_behaviora08ddfce
      description: <p>A collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref> instances that are applied to the Batch service request. </p>
    return:
      type: 5618da2dcom.microsoft.azure.batch.protocol.models._application_summarya08ddfce
      description: <p>A collection of <ref refid="" kindref="compound">ApplicationSummary</ref></p>
  exceptions:
  - type: c8683d81
    description: <p>Exception thrown from REST call </p>
  - type: cbf33bbe
    description: <p>Exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.batch._application_operations.withCustomBehaviors(Collection<BatchClientBehavior>)
  id: withCustomBehaviors(Collection<BatchClientBehavior>)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: withCustomBehaviors(Collection<BatchClientBehavior> behaviors)
  fullName: IInheritedBehaviors com.microsoft.azure.batch.ApplicationOperations.withCustomBehaviors(Collection<BatchClientBehavior> behaviors)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 54
  package: com.microsoft.azure.batch
  summary: >-
    <p>Sets a list of behaviors that modify or customize requests to the Batch service.</p>

    <p></p>
  syntax:
    content: public IInheritedBehaviors withCustomBehaviors(Collection<BatchClientBehavior> behaviors)
    parameters:
    - id: behaviors
      type: 12ebb11acom.microsoft.azure.batch._batch_client_behaviora08ddfce
      description: <p>The collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref> classes </p>
    return:
      type: com.microsoft.azure.batch._i_inherited_behaviors
      description: <p>The current instance </p>
  overridden: com.microsoft.azure.batch._i_inherited_behaviors.withCustomBehaviors(Collection<BatchClientBehavior>)
references:
- uid: 12ebb11acom.microsoft.azure.batch._batch_client_behaviora08ddfce
  spec.java:
  - name: Collection<
    fullName: Collection<
  - uid: com.microsoft.azure.batch._batch_client_behavior
    name: BatchClientBehavior
    fullName: com.microsoft.azure.batch.BatchClientBehavior
    href: com.microsoft.azure.batch._batch_client_behavior.yml
  - name: '>'
    fullName: '>'
- uid: c8683d81
  spec.java:
  - name: BatchErrorException
    fullName: BatchErrorException
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: 5618da2dcom.microsoft.azure.batch.protocol.models._application_summarya08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.batch.protocol.models._application_summary
    name: ApplicationSummary
    fullName: com.microsoft.azure.batch.protocol.models.ApplicationSummary
    href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  - name: '>'
    fullName: '>'
- uid: 2a13b5a5com.microsoft.azure.batch._batch_client_behaviora08ddfce
  spec.java:
  - name: Iterable<
    fullName: Iterable<
  - uid: com.microsoft.azure.batch._batch_client_behavior
    name: BatchClientBehavior
    fullName: com.microsoft.azure.batch.BatchClientBehavior
    href: com.microsoft.azure.batch._batch_client_behavior.yml
  - name: '>'
    fullName: '>'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch._application_operations.ApplicationOperations(BatchClient,Collection<BatchClientBehavior>)
- uid: com.microsoft.azure.batch._i_inherited_behaviors
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._i_inherited_behaviors.yml
  name: IInheritedBehaviors
  fullName: com.microsoft.azure.batch.IInheritedBehaviors
  type: Interface
  summary: <p>Methods and properties that are inherited from the instantiating parent object. This collection is initially populated by instantiation or by copying from the instantiating parent object (inheritance). In this model, the collections are independent but the members are shared references. Members of this collection alter or customize various behaviors of Azure Batch Service client objects. These behaviors are generally inherited by any child class instances. Modifications are applied in the order of the collection. The last write wins. </p>
  syntax:
    content: public interface IInheritedBehaviors
- uid: com.microsoft.azure.batch._batch_client_behavior
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._batch_client_behavior.yml
  name: BatchClientBehavior
  fullName: com.microsoft.azure.batch.BatchClientBehavior
  type: Class
  summary: <p>Derived classes modify operational behaviors of a Azure Batch Service client. </p>
  syntax:
    content: public class BatchClientBehavior
- uid: com.microsoft.azure.batch._batch_client
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._batch_client.yml
  name: BatchClient
  fullName: com.microsoft.azure.batch.BatchClient
  type: Class
  summary: <p>A client for an Azure Batch account, used to access the Batch service. </p>
  syntax:
    content: public class BatchClient
- uid: com.microsoft.azure.batch._i_inherited_behaviors.customBehaviors()
  parent: com.microsoft.azure.batch._i_inherited_behaviors
  href: com.microsoft.azure.batch._i_inherited_behaviors.yml
  name: customBehaviors()
  fullName: Collection<BatchClientBehavior> com.microsoft.azure.batch.IInheritedBehaviors.customBehaviors()
  type: Method
  summary: >-
    <p>Gets the collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref></p>

    <p></p>
  syntax:
    content: public Collection<BatchClientBehavior> customBehaviors()
    return:
      type: 12ebb11acom.microsoft.azure.batch._batch_client_behaviora08ddfce
      description: <p>The collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref> classes </p>
- uid: com.microsoft.azure.batch._i_inherited_behaviors.withCustomBehaviors(Collection<BatchClientBehavior>)
  parent: com.microsoft.azure.batch._i_inherited_behaviors
  href: com.microsoft.azure.batch._i_inherited_behaviors.yml
  name: withCustomBehaviors(Collection<BatchClientBehavior> behaviors)
  fullName: IInheritedBehaviors com.microsoft.azure.batch.IInheritedBehaviors.withCustomBehaviors(Collection<BatchClientBehavior> behaviors)
  type: Method
  summary: >-
    <p>Sets the collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref></p>

    <p></p>
  syntax:
    content: public IInheritedBehaviors withCustomBehaviors(Collection<BatchClientBehavior> behaviors)
    parameters:
    - id: behaviors
      type: 12ebb11acom.microsoft.azure.batch._batch_client_behaviora08ddfce
      description: <p>The collection of <xref href="com.microsoft.azure.batch._batch_client_behavior" data-throw-if-not-resolved="false"></xref> classes </p>
    return:
      type: com.microsoft.azure.batch._i_inherited_behaviors
      description: <p>The original instance </p>
- uid: com.microsoft.azure.batch.protocol.models._application_summary
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  name: ApplicationSummary
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationSummary
  type: Class
  summary: <p>Contains information about an application in an Azure Batch account. </p>
  syntax:
    content: public class ApplicationSummary
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  name: BatchErrorException
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
  type: Class
  summary: <p>Exception thrown for an invalid response with <xref href="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false"></xref> information. </p>
  syntax:
    content: public class BatchErrorException
