items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
  id: _file_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.create(String,String)
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.yml
  langs:
  - java
  name: FileFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.FileFactory
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/FileFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/FileFactory.java
    startLine: 31
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  summary: <p>Created by yonisha on 8/3/2015. </p>
  syntax:
    content: public class FileFactory
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.create(String,String)
  id: create(String,String)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.yml
  langs:
  - java
  name: create(String filePath, String data)
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.internal.FileFactory.create(String filePath, String data)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/FileFactory.java
    startLine: 32
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public void create(String filePath, String data)
    parameters:
    - id: filePath
      type: "26831127"
    - id: data
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
