items:
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output
  id: _active_transmission_file_system_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.ActiveTransmissionFileSystemOutput(TransmissionOutput,TransmissionPolicyStateFetcher)
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.send(final Transmission)
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.yml
  langs:
  - java
  name: ActiveTransmissionFileSystemOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionFileSystemOutput
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionFileSystemOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionFileSystemOutput.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The class is responsible for de-coupling the file persist activity.</p>

    <p>When this class is called it will use a thread pool's thread to do the persistence</p>

    <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public class ActiveTransmissionFileSystemOutput implements TransmissionOutput
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.channel._transmission_output
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.ActiveTransmissionFileSystemOutput(TransmissionOutput,TransmissionPolicyStateFetcher)
  id: ActiveTransmissionFileSystemOutput(TransmissionOutput,TransmissionPolicyStateFetcher)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.yml
  langs:
  - java
  name: ActiveTransmissionFileSystemOutput(TransmissionOutput actualOutput, TransmissionPolicyStateFetcher transmissionPolicy)
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionFileSystemOutput.ActiveTransmissionFileSystemOutput(TransmissionOutput actualOutput, TransmissionPolicyStateFetcher transmissionPolicy)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionFileSystemOutput.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public ActiveTransmissionFileSystemOutput(TransmissionOutput actualOutput, TransmissionPolicyStateFetcher transmissionPolicy)
    parameters:
    - id: actualOutput
      type: com.microsoft.applicationinsights.internal.channel._transmission_output
    - id: transmissionPolicy
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.send(final Transmission)
  id: send(final Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.yml
  langs:
  - java
  name: send(final Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionFileSystemOutput.send(final Transmission transmission)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionFileSystemOutput.java
    startLine: 65
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public boolean send(final Transmission transmission)
    parameters:
    - id: transmission
      type: 93de0ef9com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionFileSystemOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionFileSystemOutput.java
    startLine: 96
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
references:
- uid: 93de0ef9com.microsoft.applicationinsights.internal.channel.common._transmission
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.internal.channel.common._transmission
    name: Transmission
    fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
    href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TransmissionOutput.send(Transmission transmission)
  type: Method
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: TransmissionOutput
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionOutput
  type: Interface
  summary: >-
    <p>Defines the interface of classes that get a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and can 'send' it.</p>

    <p>Concrete classes can 'send' the data to remote server, to disk, database etc.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
  name: TransmissionPolicyStateFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher
  type: Interface
  summary: <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public interface TransmissionPolicyStateFetcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
