items:
- uid: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e
  id: _application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e.yml
  langs:
  - java
  name: ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
    startLine: 125
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The final stage of an application gateway IP configuration definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdate<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: Attachable.InUpdate<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InUpdate<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configuration._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configuration._update_definition.yml
  name: ApplicationGatewayIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway IP configuration definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayIpConfiguration.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithContainingSubnet<ParentT>,ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent type </p>
