items:
- uid: com.microsoft.azure.management.network._application_gateway._definiti71c4ae773f713c0a38df862000e61f64
  id: _definiti71c4ae773f713c0a38df862000e61f64
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti71c4ae773f713c0a38df862000e61f64.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 332
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to continue adding more request routing rules, or start specifying optional settings, or create the resource. </p>
  syntax:
    content: public interface WithRequestRoutingRuleOrCreate extends ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithCreate
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._creatable.create()
  - com.microsoft.azure.management.resources.fluentcore.model._creatable.createAsync(final ServiceCallback<T>)
  - com.microsoft.azure.management.resources.fluentcore.model._creatable.createAsync()
  - com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.defineRequestRoutingRule(String)
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_ssl_cert.defineSslCertificate(String)
  - com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.name()
  - com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1.withFrontendPort(int)
  - com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1.withFrontendPort(int,String)
  - com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09.withTag(String,String)
  - com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09.withTags(Map<String, String>)
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable.create()
  parent: com.microsoft.azure.management.resources.fluentcore.model._creatable
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: create()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>.create()
  type: Method
  summary: >-
    <p>Execute the create request.</p>

    <p></p>
  syntax:
    content: public T create()
    return:
      type: 8ce1ecb9
      description: <p>the create resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable.createAsync(final ServiceCallback<T>)
  parent: com.microsoft.azure.management.resources.fluentcore.model._creatable
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: createAsync(final ServiceCallback<T> callback)
  fullName: ServiceCall<T> com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>.createAsync(final ServiceCallback<T> callback)
  type: Method
  summary: >-
    <p>Puts the request into the queue and allow the HTTP client to execute it when system resources are available.</p>

    <p></p>
  syntax:
    content: public ServiceCall<T> createAsync(final ServiceCallback<T> callback)
    parameters:
    - id: callback
      type: fe95c2b0
      description: <p>the callback to handle success and failure </p>
    return:
      type: cac0d934
      description: <p>a handle to cancel the request </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable.createAsync()
  parent: com.microsoft.azure.management.resources.fluentcore.model._creatable
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: createAsync()
  fullName: Observable<T> com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>.createAsync()
  type: Method
  summary: >-
    <p>Puts the request into the queue and allow the HTTP client to execute it when system resources are available.</p>

    <p></p>
  syntax:
    content: public Observable<T> createAsync()
    return:
      type: c4094ba1
      description: <p>an observable of the request </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.defineRequestRoutingRule(String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2
  href: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.yml
  name: defineRequestRoutingRule(String name)
  fullName: ApplicationGatewayRequestRoutingRule.DefinitionStages.Blank<WithRequestRoutingRuleOrCreate> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithRequestRoutingRule.defineRequestRoutingRule(String name)
  type: Method
  summary: <p>Begins the definition of a new application gateway request routing rule to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayRequestRoutingRule.DefinitionStages.Blank<WithRequestRoutingRuleOrCreate> defineRequestRoutingRule(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the request routing rule </p>
    return:
      type: 964ff059com.microsoft.azure.management.network._application_gateway._definiti71c4ae773f713c0a38df862000e61f64a08ddfce
      description: <p>the first stage of the request routing rule </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_ssl_cert.defineSslCertificate(String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_ssl_cert
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_ssl_cert.yml
  name: defineSslCertificate(String name)
  fullName: ApplicationGatewaySslCertificate.DefinitionStages.Blank<WithCreate> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithSslCert.defineSslCertificate(String name)
  type: Method
  summary: <p>Begins the definition of a new application gateway SSL certificate to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewaySslCertificate.DefinitionStages.Blank<WithCreate> defineSslCertificate(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the certificate </p>
    return:
      type: ba46146acom.microsoft.azure.management.network._application_gateway._definition_stages._with_createa08ddfce
      description: <p>the first stage of the certificate definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.name()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.yml
  name: name()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasName.name()
  type: Method
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name of the resource </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1.withFrontendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1
  href: com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1.yml
  name: withFrontendPort(int portNumber)
  fullName: WithCreate com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithFrontendPort.withFrontendPort(int portNumber)
  type: Method
  summary: <p>Creates a port with an autogenerated name. </p>
  syntax:
    content: public WithCreate withFrontendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definition_stages._with_create
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1.withFrontendPort(int,String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1
  href: com.microsoft.azure.management.network._application_gateway._definiti3bb82a2fa916d9dba82024806e9d4fc1.yml
  name: withFrontendPort(int portNumber, String name)
  fullName: WithCreate com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithFrontendPort.withFrontendPort(int portNumber, String name)
  type: Method
  summary: <p>Creates a port. </p>
  syntax:
    content: public WithCreate withFrontendPort(int portNumber, String name)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    - id: name
      type: "26831127"
      description: <p>the name to assign to the port </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definition_stages._with_create
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09.withTag(String,String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09.yml
  name: withTag(String key, String value)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.models.Resource.DefinitionWithTags<T>.withTag(String key, String value)
  type: Method
  summary: <p>Adds a tag to the resource. </p>
  syntax:
    content: public T withTag(String key, String value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key for the tag </p>
    - id: value
      type: "26831127"
      description: <p>the value for the tag </p>
    return:
      type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09.withTags(Map<String, String>)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.720b3efb4062edecc50de4ad58dc1c09.yml
  name: withTags(Map<String, String> tags)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.models.Resource.DefinitionWithTags<T>.withTags(Map<String, String> tags)
  type: Method
  summary: <p>Specifies tags for the resource as a <ref refid="" kindref="compound">Map</ref>. </p>
  syntax:
    content: public T withTags(Map<String, String> tags)
    parameters:
    - id: tags
      type: 689c8cb5
      description: <p>a <ref refid="" kindref="compound">Map</ref> of tags </p>
    return:
      type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.yml
  name: ApplicationGateway.DefinitionStages.WithRequestRoutingRule
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithRequestRoutingRule
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add a request routing rule. </p>
  syntax:
    content: public interface WithRequestRoutingRule
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_create
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_create.yml
  name: ApplicationGateway.DefinitionStages.WithCreate
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithCreate
  type: Interface
  summary: <p>The stage of an application gateway definition containing all the required inputs for the resource to be created (via <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable.create()" data-throw-if-not-resolved="false"></xref>), but also allowing for any other optional settings to be specified. </p>
  syntax:
    content: public interface WithCreate extends Creatable<ApplicationGateway>,Resource.DefinitionWithTags<WithCreate>,ApplicationGateway.DefinitionStages.WithSslCert,ApplicationGateway.DefinitionStages.WithFrontendPort
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
