items:
- uid: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests
  id: _application_insights_appender_tests
  parent: com.microsoft.applicationinsights.log4j.v2
  children:
  - com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.setup()
  - com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.testAppenderSendsGivenEvent()
  - com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.testInstrumentationKeyIsLoadedFromConfiguration()
  href: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.yml
  langs:
  - java
  name: ApplicationInsightsAppenderTests
  fullName: com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppenderTests
  type: Class
  source:
    remote: &o0
      path: logging/log4j2/appenderSrc/test/appender/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/log4j2/appenderSrc/test/appender/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java
    startLine: 34
  package: com.microsoft.applicationinsights.log4j.v2
  syntax:
    content: public class ApplicationInsightsAppenderTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.setup()
  id: setup()
  parent: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.yml
  langs:
  - java
  name: setup()
  fullName: void com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppenderTests.setup()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/test/appender/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java
    startLine: 51
  package: com.microsoft.applicationinsights.log4j.v2
  syntax:
    content: public void setup()
- uid: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.testAppenderSendsGivenEvent()
  id: testAppenderSendsGivenEvent()
  parent: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.yml
  langs:
  - java
  name: testAppenderSendsGivenEvent()
  fullName: void com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppenderTests.testAppenderSendsGivenEvent()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/test/appender/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java
    startLine: 68
  package: com.microsoft.applicationinsights.log4j.v2
  syntax:
    content: public void testAppenderSendsGivenEvent()
- uid: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.testInstrumentationKeyIsLoadedFromConfiguration()
  id: testInstrumentationKeyIsLoadedFromConfiguration()
  parent: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests
  href: com.microsoft.applicationinsights.log4j.v2._application_insights_appender_tests.yml
  langs:
  - java
  name: testInstrumentationKeyIsLoadedFromConfiguration()
  fullName: void com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppenderTests.testInstrumentationKeyIsLoadedFromConfiguration()
  type: Method
  source:
    remote: *o0
    path: logging/log4j2/appenderSrc/test/appender/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java
    startLine: 60
  package: com.microsoft.applicationinsights.log4j.v2
  syntax:
    content: public void testInstrumentationKeyIsLoadedFromConfiguration()
references:
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
- uid: com.microsoft.applicationinsights.log4j.v2._application_insights_appender
  parent: com.microsoft.applicationinsights.log4j.v2
  href: com.microsoft.applicationinsights.log4j.v2._application_insights_appender.yml
  name: ApplicationInsightsAppender
  fullName: com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppender
  type: Class
  syntax:
    content: public class ApplicationInsightsAppender
