items:
- uid: com.microsoft.applicationinsights.internal.config
  id: config
  children:
  - com.microsoft.applicationinsights.internal.config._add_type_xml_element
  - com.microsoft.applicationinsights.internal.config._application_insights_xml_configuration
  - com.microsoft.applicationinsights.internal.config._channel_xml_element
  - com.microsoft.applicationinsights.internal.config._configuration_file_locator
  - com.microsoft.applicationinsights.internal.config._configuration_file_locator_test
  - com.microsoft.applicationinsights.internal.config._context_initializers_initializer_test
  - com.microsoft.applicationinsights.internal.config._context_initializers_xml_element
  - com.microsoft.applicationinsights.internal.config._jmx_list_xml_element
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element
  - com.microsoft.applicationinsights.internal.config._jvm_xml_element
  - com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  - com.microsoft.applicationinsights.internal.config._param_xml_element
  - com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  - com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  - com.microsoft.applicationinsights.internal.config._reflection_utils
  - com.microsoft.applicationinsights.internal.config._remove_type_xml_element
  - com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory_test
  - com.microsoft.applicationinsights.internal.config._telemetry_initializers_xml_element
  - com.microsoft.applicationinsights.internal.config._telemetry_modules_xml_element
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  - com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  - com.microsoft.applicationinsights.internal.config._test_processor_that_fails_on_ctor
  - com.microsoft.applicationinsights.internal.config._test_processor_that_throws_on_setter
  - com.microsoft.applicationinsights.internal.config._test_processor_without_setters
  - com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.config
  fullName: com.microsoft.applicationinsights.internal.config
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 21
  syntax:
    content: namespace config
references:
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  name: AddTypeXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.AddTypeXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AddTypeXmlElement
- uid: com.microsoft.applicationinsights.internal.config._application_insights_xml_configuration
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._application_insights_xml_configuration.yml
  name: ApplicationInsightsXmlConfiguration
  fullName: com.microsoft.applicationinsights.internal.config.ApplicationInsightsXmlConfiguration
  type: Class
  summary: <p>Created by gupele on 3/13/2015. </p>
  syntax:
    content: public class ApplicationInsightsXmlConfiguration
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  name: ChannelXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ChannelXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class ChannelXmlElement
- uid: com.microsoft.applicationinsights.internal.config._configuration_file_locator
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._configuration_file_locator.yml
  name: ConfigurationFileLocator
  fullName: com.microsoft.applicationinsights.internal.config.ConfigurationFileLocator
  type: Class
  summary: <p>Created by gupele on 5/25/2015. </p>
  syntax:
    content: public class ConfigurationFileLocator
- uid: com.microsoft.applicationinsights.internal.config._configuration_file_locator_test
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._configuration_file_locator_test.yml
  name: ConfigurationFileLocatorTest
  fullName: com.microsoft.applicationinsights.internal.config.ConfigurationFileLocatorTest
  type: Class
  syntax:
    content: public class ConfigurationFileLocatorTest
- uid: com.microsoft.applicationinsights.internal.config._context_initializers_initializer_test
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._context_initializers_initializer_test.yml
  name: ContextInitializersInitializerTest
  fullName: com.microsoft.applicationinsights.internal.config.ContextInitializersInitializerTest
  type: Class
  summary: <p>Created by gupele on 9/8/2016. </p>
  syntax:
    content: public class ContextInitializersInitializerTest
- uid: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.yml
  name: ContextInitializersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ContextInitializersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class ContextInitializersXmlElement
- uid: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.yml
  name: JmxListXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxListXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxListXmlElement
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  name: JmxXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxXmlElement
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  name: JvmXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JvmXmlElement
  type: Class
  summary: <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class JvmXmlElement
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  name: MockTelemetryModule
  fullName: com.microsoft.applicationinsights.internal.config.MockTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class MockTelemetryModule implements TelemetryModule
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  name: ParamXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ParamXmlElement
  type: Class
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class ParamXmlElement
- uid: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counter_jvm_section_xml_element.yml
  name: PerformanceCounterJvmSectionXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCounterJvmSectionXmlElement
  type: Class
  summary: <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class PerformanceCounterJvmSectionXmlElement
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  name: PerformanceCountersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class PerformanceCountersXmlElement
- uid: com.microsoft.applicationinsights.internal.config._reflection_utils
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._reflection_utils.yml
  name: ReflectionUtils
  fullName: com.microsoft.applicationinsights.internal.config.ReflectionUtils
  type: Class
  summary: >-
    <p>Utililty methods for dealing with reflection</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class ReflectionUtils
- uid: com.microsoft.applicationinsights.internal.config._remove_type_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._remove_type_xml_element.yml
  name: RemoveTypeXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.RemoveTypeXmlElement
  type: Class
  summary: <p>Created by gupele on 3/16/2015. </p>
  syntax:
    content: public class RemoveTypeXmlElement
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  name: SDKLoggerXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class SDKLoggerXmlElement
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  name: TelemetryConfigurationFactory
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory
  type: Enum
  summary: <p>Initializer class for configuration instances. </p>
  syntax:
    content: public enum TelemetryConfigurationFactory
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory_test
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory_test.yml
  name: TelemetryConfigurationFactoryTest
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactoryTest
  type: Class
  syntax:
    content: public class TelemetryConfigurationFactoryTest
- uid: com.microsoft.applicationinsights.internal.config._telemetry_initializers_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_initializers_xml_element.yml
  name: TelemetryInitializersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryInitializersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class TelemetryInitializersXmlElement
- uid: com.microsoft.applicationinsights.internal.config._telemetry_modules_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_modules_xml_element.yml
  name: TelemetryModulesXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryModulesXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class TelemetryModulesXmlElement
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator.yml
  name: TelemetryProcessorCreator
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreator
  type: Class
  summary: >-
    <p>The class will try to create the <ref refid="" kindref="compound">TelemetryProcessor</ref> and will activate any 'setXXX' method based on the configuration</p>

    <p>Any exception thrown, or any setter method returns false will cause the processor to be ignored.</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TelemetryProcessorCreator
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator_test.yml
  name: TelemetryProcessorCreatorTest
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreatorTest
  type: Class
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TelemetryProcessorCreatorTest
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.yml
  name: TelemetryProcessorsXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorsXmlElement
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorsXmlElement
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  name: TelemetryProcessorXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorXmlElement
- uid: com.microsoft.applicationinsights.internal.config._test_processor_that_fails_on_ctor
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._test_processor_that_fails_on_ctor.yml
  name: TestProcessorThatFailsOnCtor
  fullName: com.microsoft.applicationinsights.internal.config.TestProcessorThatFailsOnCtor
  type: Class
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TestProcessorThatFailsOnCtor implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.config._test_processor_that_throws_on_setter
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._test_processor_that_throws_on_setter.yml
  name: TestProcessorThatThrowsOnSetter
  fullName: com.microsoft.applicationinsights.internal.config.TestProcessorThatThrowsOnSetter
  type: Class
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TestProcessorThatThrowsOnSetter implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.config._test_processor_without_setters
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._test_processor_without_setters.yml
  name: TestProcessorWithoutSetters
  fullName: com.microsoft.applicationinsights.internal.config.TestProcessorWithoutSetters
  type: Class
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TestProcessorWithoutSetters implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  name: ValidProcessorsWithSetters
  fullName: com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters
  type: Class
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class ValidProcessorsWithSetters implements TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  name: WindowsPerformanceCounterXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterXmlElement
