items:
- uid: com.microsoft.azure.management.network._application_gateway_request_rout3e0bbdd99717652faa3ad70abe0a4277
  id: _application_gateway_request_rout3e0bbdd99717652faa3ad70abe0a4277
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_rout3e0bbdd99717652faa3ad70abe0a4277.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 118
  package: com.microsoft.azure.management.network
  summary: <p>The first stage of an application gateway request routing rule definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdate<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_routfbca5ae42f2538dfe039c4c7774a6e46
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routfbca5ae42f2538dfe039c4c7774a6e46.yml
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway request routing rule definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule._update_definition.yml
  name: ApplicationGatewayRequestRoutingRule.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway request routing rule definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
