items:
- uid: com.microsoft.applicationinsights.internal.channel._transmissions_loader
  id: _transmissions_loader
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._transmissions_loader.load(boolean)
  href: com.microsoft.applicationinsights.internal.channel._transmissions_loader.yml
  langs:
  - java
  name: TransmissionsLoader
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionsLoader
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionsLoader.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionsLoader.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.channel
  summary: <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public interface TransmissionsLoader extends Stoppable
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
- uid: com.microsoft.applicationinsights.internal.channel._transmissions_loader.load(boolean)
  id: load(boolean)
  parent: com.microsoft.applicationinsights.internal.channel._transmissions_loader
  href: com.microsoft.applicationinsights.internal.channel._transmissions_loader.yml
  langs:
  - java
  name: load(boolean waitForThreadsToStart)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TransmissionsLoader.load(boolean waitForThreadsToStart)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionsLoader.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public boolean load(boolean waitForThreadsToStart)
    parameters:
    - id: waitForThreadsToStart
      type: 4fc6e284
    return:
      type: 4fc6e284
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.shutdown._stoppable
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.shutdown.Stoppable.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable
  parent: com.microsoft.applicationinsights.internal.shutdown
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: Stoppable
  fullName: com.microsoft.applicationinsights.internal.shutdown.Stoppable
  type: Interface
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface Stoppable
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  name: ActiveTransmissionLoader
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader
  type: Class
  summary: >-
    <p>The class is responsible for loading transmission files that were saved to the disk</p>

    <p>The class will ask for the oldest transmission file and will hand it to the dispatcher</p>

    <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public class ActiveTransmissionLoader implements TransmissionsLoader
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.load(boolean)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_loader.yml
  name: load(boolean waitForThreadsToStart)
  fullName: synchronized boolean com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.load(boolean waitForThreadsToStart)
  type: Method
  syntax:
    content: public synchronized boolean load(boolean waitForThreadsToStart)
    parameters:
    - id: waitForThreadsToStart
      type: 4fc6e284
    return:
      type: 85b427c6
