items:
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output
  id: _transmission_output
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
  - com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  langs:
  - java
  name: TransmissionOutput
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionOutput
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionOutput.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.channel
  summary: >-
    <p>Defines the interface of classes that get a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and can 'send' it.</p>

    <p>Concrete classes can 'send' the data to remote server, to disk, database etc.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.send(Transmission)
  id: send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  langs:
  - java
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TransmissionOutput.send(Transmission transmission)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionOutput.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_output
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionOutput.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.core.volume._fake_transmission_output
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.yml
  name: ActiveTransmissionFileSystemOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionFileSystemOutput
  type: Class
  summary: >-
    <p>The class is responsible for de-coupling the file persist activity.</p>

    <p>When this class is called it will use a thread pool's thread to do the persistence</p>

    <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public class ActiveTransmissionFileSystemOutput implements TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output.yml
  name: ActiveTransmissionNetworkOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput
  type: Class
  summary: <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class ActiveTransmissionNetworkOutput implements TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  name: TransmissionFileSystemOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput
  type: Class
  summary: >-
    <p>The class knows how to manage <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> that needs to be saved to the file system.</p>

    <p>The class works on a pre-defined folder and should know the size of disk it can use.</p>

    <p>With that data it knows how to store incoming Transmissions and store them into files that can be later be read back into Transmissions.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class TransmissionFileSystemOutput implements TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  name: TransmissionNetworkOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput
  type: Class
  summary: >-
    <p>The class is responsible for the actual sending of <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>The class uses Apache's HttpClient framework for that.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class TransmissionNetworkOutput implements TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(Transmission transmission)
  type: Method
  summary: <p>Tries to send a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> The thread that calls that method might be suspended if there is a throttling issues, in any case the thread that enters this method is responsive for 'stop' request that might be issued by the application. </p>
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
      description: <p>The data to send </p>
    return:
      type: 4fc6e284
      description: <p>True when done. </p>
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.send(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  name: send(Transmission transmission)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.send(Transmission transmission)
  type: Method
  syntax:
    content: public boolean send(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_file_system_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionFileSystemOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_network_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: synchronized void com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  summary: <p>Stops all threads from sending data. </p>
  syntax:
    content: public synchronized void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>The timeout to wait, which is not relevant here. </p>
    - id: timeUnit
      type: 02b8628b
      description: <p>The time unit, which is not relevant in this method. </p>
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_file_system_output.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
