items:
- uid: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity
  id: _s_d_k_shutdown_activity
  parent: com.microsoft.applicationinsights.internal.shutdown
  children:
  - com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.register(ChannelFetcher)
  - com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.register(Stoppable)
  href: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.yml
  langs:
  - java
  name: SDKShutdownActivity
  fullName: com.microsoft.applicationinsights.internal.shutdown.SDKShutdownActivity
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.shutdown
  summary: >-
    <p>The class is responsible for all shutdown activities done in the SDK.</p>

    <p>Created by gupele on 2/2/2015. </p>
  syntax:
    content: public enum SDKShutdownActivity
  inheritance:
  - java.lang.Object
  - java.lang.Enum<SDKShutdownActivity>
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity_1aa896ce8e120517b76a6d03de8398fbbf
- uid: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.register(ChannelFetcher)
  id: register(ChannelFetcher)
  parent: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity
  href: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.yml
  langs:
  - java
  name: register(ChannelFetcher fetcher)
  fullName: void com.microsoft.applicationinsights.internal.shutdown.SDKShutdownActivity.register(ChannelFetcher fetcher)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
    startLine: 121
  package: com.microsoft.applicationinsights.internal.shutdown
  syntax:
    content: public void register(ChannelFetcher fetcher)
    parameters:
    - id: fetcher
      type: com.microsoft.applicationinsights.internal.util._channel_fetcher
- uid: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.register(Stoppable)
  id: register(Stoppable)
  parent: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity
  href: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity.yml
  langs:
  - java
  name: register(Stoppable stoppable)
  fullName: void com.microsoft.applicationinsights.internal.shutdown.SDKShutdownActivity.register(Stoppable stoppable)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
    startLine: 125
  package: com.microsoft.applicationinsights.internal.shutdown
  syntax:
    content: public void register(Stoppable stoppable)
    parameters:
    - id: stoppable
      type: com.microsoft.applicationinsights.internal.shutdown._stoppable
references:
- uid: com.microsoft.applicationinsights.internal.shutdown._s_d_k_shutdown_activity_1aa896ce8e120517b76a6d03de8398fbbf
- uid: com.microsoft.applicationinsights.internal.util._channel_fetcher
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._channel_fetcher.yml
  name: ChannelFetcher
  fullName: com.microsoft.applicationinsights.internal.util.ChannelFetcher
  type: Interface
  summary: <p>Created by gupele on 2/2/2015. </p>
  syntax:
    content: public interface ChannelFetcher
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable
  parent: com.microsoft.applicationinsights.internal.shutdown
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: Stoppable
  fullName: com.microsoft.applicationinsights.internal.shutdown.Stoppable
  type: Interface
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface Stoppable
