items:
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  id: _dependency_source_type
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.Aic()
  - com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.Apmc()
  - com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.DependencySourceType(int)
  - com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.getValue()
  - com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.Undefined()
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  langs:
  - java
  name: DependencySourceType
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencySourceType
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.internal.schemav2._dependency_source_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum DependencySourceType
  inheritance:
  - java.lang.Object
  - java.lang.Enum<DependencySourceType>
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.Aic()
  id: Aic()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  langs:
  - java
  name: Aic
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencySourceType.Aic
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Aic=(1)
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.Apmc()
  id: Apmc()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  langs:
  - java
  name: Apmc
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencySourceType.Apmc
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Apmc=(2)
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.DependencySourceType(int)
  id: DependencySourceType(int)
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  langs:
  - java
  name: DependencySourceType(int id)
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencySourceType.DependencySourceType(int id)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public DependencySourceType(int id)
    parameters:
    - id: id
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.getValue()
  id: getValue()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  langs:
  - java
  name: getValue()
  fullName: int com.microsoft.applicationinsights.internal.schemav2.DependencySourceType.getValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public int getValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.Undefined()
  id: Undefined()
  parent: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  langs:
  - java
  name: Undefined
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencySourceType.Undefined
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DependencySourceType.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Undefined=(0)
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._dependency_source_type.yml
  name: DependencySourceType
  fullName: com.microsoft.applicationinsights.internal.schemav2.DependencySourceType
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.internal.schemav2._dependency_source_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
