items:
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  id: _plugin_exclusion
  parent: com.microsoft.applicationinsights.collectd.internal
  children:
  - com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.buildPluginExclusion(String)
  - com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.getPluginName()
  - com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.isDataSourceExcluded(String)
  - com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.PluginExclusion(String)
  - com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.PluginExclusion(String,List<String>)
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  langs:
  - java
  name: PluginExclusion
  fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion
  type: Class
  source:
    remote: &o0
      path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
    startLine: 34
  package: com.microsoft.applicationinsights.collectd.internal
  summary: >-
    <p>Created by yonisha on 5/5/2015.</p>

    <p>This class represents a plugin and its data source to be excluded. </p>
  syntax: &o1
    content: public class PluginExclusion
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.buildPluginExclusion(String)
  id: buildPluginExclusion(String)
  parent: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  langs:
  - java
  name: buildPluginExclusion(String exclusionString)
  fullName: static PluginExclusion com.microsoft.applicationinsights.collectd.internal.PluginExclusion.buildPluginExclusion(String exclusionString)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
    startLine: 89
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Builds  from the given configuration string. </p>
  syntax:
    content: public static PluginExclusion buildPluginExclusion(String exclusionString)
    parameters:
    - id: exclusionString
      type: "26831127"
      description: <p>The exclusion string from the configuration. </p>
    return:
      type: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
      description: <p>A new  object. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.getPluginName()
  id: getPluginName()
  parent: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  langs:
  - java
  name: getPluginName()
  fullName: String com.microsoft.applicationinsights.collectd.internal.PluginExclusion.getPluginName()
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
    startLine: 60
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Gets the plugin name. </p>
  syntax:
    content: public String getPluginName()
    return:
      type: "26831127"
      description: <p>The plugin name. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.isDataSourceExcluded(String)
  id: isDataSourceExcluded(String)
  parent: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  langs:
  - java
  name: isDataSourceExcluded(String dataSource)
  fullName: boolean com.microsoft.applicationinsights.collectd.internal.PluginExclusion.isDataSourceExcluded(String dataSource)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
    startLine: 69
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Gets a value indicating whether the given data source is excluded. </p>
  syntax:
    content: public boolean isDataSourceExcluded(String dataSource)
    parameters:
    - id: dataSource
      type: "26831127"
      description: <p>The data source to check if excluded. </p>
    return:
      type: 4fc6e284
      description: <p>True if the data source is excluded, false otherwise. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.PluginExclusion(String)
  id: PluginExclusion(String)
  parent: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  langs:
  - java
  name: PluginExclusion(String pluginName)
  fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion.PluginExclusion(String pluginName)
  type: Constructor
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
    startLine: 42
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Constructs new . </p>
  syntax:
    content: public PluginExclusion(String pluginName)
    parameters:
    - id: pluginName
      type: "26831127"
      description: <p>The plugin name. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.PluginExclusion(String,List<String>)
  id: PluginExclusion(String,List<String>)
  parent: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  langs:
  - java
  name: PluginExclusion(String pluginName, List<String> pluginDataSources)
  fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion.PluginExclusion(String pluginName, List<String> pluginDataSources)
  type: Constructor
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/PluginExclusion.java
    startLine: 51
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Constructs new . </p>
  syntax:
    content: public PluginExclusion(String pluginName, List<String> pluginDataSources)
    parameters:
    - id: pluginName
      type: "26831127"
      description: <p>The plugin name. </p>
    - id: pluginDataSources
      type: 7d60c20e
      description: <p>The data source to exclude. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  parent: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  name: PluginExclusion
  fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion
  type: Class
  summary: >-
    <p>Created by yonisha on 5/5/2015.</p>

    <p>This class represents a plugin and its data source to be excluded. </p>
  syntax: *o1
