items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.redis
  id: redis
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.redis.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.agent.redis
  fullName: com.microsoft.applicationinsights.agent.internal.agent.redis
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
    startLine: 21
  syntax:
    content: namespace redis
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.redis
  href: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.yml
  name: JedisClassDataProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.redis.JedisClassDataProvider
  type: Class
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JedisClassDataProvider
