items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend.b92473a9f5988c07d773b703a40e2ac8
  id: b92473a9f5988c07d773b703a40e2ac8
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.b92473a9f5988c07d773b703a40e2ac8.yml
  langs:
  - java
  name: ApplicationGatewayFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
    startLine: 167
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway frontend definition allowing to specify an existing public IP address to make the application gateway available at as Internet-facing. </p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT> extends HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<WithAttach<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(PublicIpAddress)
  - com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(PublicIpAddress)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
    parameters:
    - id: publicIpAddress
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(String)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: withExistingPublicIpAddress(String resourceId)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(String resourceId)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(String resourceId)
    parameters:
    - id: resourceId
      type: "26831127"
      description: <p>the resource ID of an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>
  type: Interface
  summary: >-
    <p>The stage of the definition allowing to associate the resource with an existing public IP address.</p>

    <p></p>
  syntax:
    content: public interface WithExistingPublicIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend.de475454f5ff9cd6ae153a9776ed4043
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.de475454f5ff9cd6ae153a9776ed4043.yml
  name: ApplicationGatewayFrontend.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway frontend definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the frontend definition can be attached to the parent application gateway definition. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdateAlt,ApplicationGatewayFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>,ApplicationGatewayFrontend.UpdateDefinitionStages.WithSubnet<ParentT>,ApplicationGatewayFrontend.UpdateDefinitionStages.WithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdateAlt<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
