items:
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module
  id: _telemetry_module
  parent: com.microsoft.applicationinsights.extensibility
  children:
  - com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  langs:
  - java
  name: TelemetryModule
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryModule
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java
    startLine: 28
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface TelemetryModule
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  id: initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_module
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  langs:
  - java
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java
    startLine: 34
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Initializes the telemetry module. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
references:
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
