items:
- uid: com.microsoft.applicationinsights.channel
  id: channel
  children:
  - com.microsoft.applicationinsights.channel._telemetry_channel
  href: com.microsoft.applicationinsights.channel.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.channel
  fullName: com.microsoft.applicationinsights.channel
  type: Namespace
  source:
    remote:
      path: '[generated]'
    path: '[generated]'
  syntax:
    content: namespace channel
references:
- uid: com.microsoft.applicationinsights.channel.concrete
- uid: com.microsoft.applicationinsights.channel._telemetry_channel
  parent: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: TelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.TelemetryChannel
  type: Interface
  summary: <p>Represents a communication channel for sending telemetry to application insights. </p>
  syntax:
    content: public interface TelemetryChannel
