items:
- uid: com.microsoft.applicationinsights.extensibility.context._device_context
  id: _device_context
  parent: com.microsoft.applicationinsights.extensibility.context
  children:
  - com.microsoft.applicationinsights.extensibility.context._device_context.DeviceContext(ConcurrentMap<String, String>)
  - com.microsoft.applicationinsights.extensibility.context._device_context.getId()
  - com.microsoft.applicationinsights.extensibility.context._device_context.setId(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setLanguage(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setLocale(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setModel(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setNetworkType(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setOemName(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setOperatingSystem(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setOperatingSystemVersion(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setRoleInstance(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setRoleName(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setScreenResolution(String)
  - com.microsoft.applicationinsights.extensibility.context._device_context.setType(String)
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: DeviceContext
  fullName: com.microsoft.applicationinsights.extensibility.context.DeviceContext
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 27
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public class DeviceContext
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - com.microsoft.applicationinsights.extensibility.context._device_context.getLanguage()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getLocale()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getModel()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getNetworkType()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getOemName()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getOperatingSystem()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getOperatingSystemVersion()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getRoleInstance()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getRoleName()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getScreenResolution()
  - com.microsoft.applicationinsights.extensibility.context._device_context.getType()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.DeviceContext(ConcurrentMap<String, String>)
  id: DeviceContext(ConcurrentMap<String, String>)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: DeviceContext(ConcurrentMap<String, String> tags)
  fullName: com.microsoft.applicationinsights.extensibility.context.DeviceContext.DeviceContext(ConcurrentMap<String, String> tags)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 129
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public DeviceContext(ConcurrentMap<String, String> tags)
    parameters:
    - id: tags
      type: bc7a2f3a
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.extensibility.context.DeviceContext.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 39
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setId(String)
  id: setId(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setId(String id)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setId(String id)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 43
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setId(String id)
    parameters:
    - id: id
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setLanguage(String)
  id: setLanguage(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setLanguage(String language)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setLanguage(String language)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 107
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setLanguage(String language)
    parameters:
    - id: language
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setLocale(String)
  id: setLocale(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setLocale(String locale)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setLocale(String locale)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 99
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setLocale(String locale)
    parameters:
    - id: locale
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setModel(String)
  id: setModel(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setModel(String model)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setModel(String model)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 75
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setModel(String model)
    parameters:
    - id: model
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setNetworkType(String)
  id: setNetworkType(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setNetworkType(String networkType)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setNetworkType(String networkType)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 83
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setNetworkType(String networkType)
    parameters:
    - id: networkType
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setOemName(String)
  id: setOemName(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setOemName(String oemName)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setOemName(String oemName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 67
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setOemName(String oemName)
    parameters:
    - id: oemName
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setOperatingSystem(String)
  id: setOperatingSystem(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setOperatingSystem(String operatingSystem)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setOperatingSystem(String operatingSystem)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 51
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setOperatingSystem(String operatingSystem)
    parameters:
    - id: operatingSystem
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setOperatingSystemVersion(String)
  id: setOperatingSystemVersion(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setOperatingSystemVersion(String operatingSystemVersion)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setOperatingSystemVersion(String operatingSystemVersion)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 59
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setOperatingSystemVersion(String operatingSystemVersion)
    parameters:
    - id: operatingSystemVersion
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setRoleInstance(String)
  id: setRoleInstance(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setRoleInstance(String roleInstance)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setRoleInstance(String roleInstance)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 125
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setRoleInstance(String roleInstance)
    parameters:
    - id: roleInstance
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setRoleName(String)
  id: setRoleName(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setRoleName(String roleName)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setRoleName(String roleName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 116
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setRoleName(String roleName)
    parameters:
    - id: roleName
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setScreenResolution(String)
  id: setScreenResolution(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setScreenResolution(String screenResolution)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setScreenResolution(String screenResolution)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 91
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setScreenResolution(String screenResolution)
    parameters:
    - id: screenResolution
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.extensibility.context._device_context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContext.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/DeviceContext.java
    startLine: 35
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: bc7a2f3a
  spec.java:
  - name: ConcurrentMap<String, String>
    fullName: ConcurrentMap<String, String>
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getLanguage()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getLocale()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getModel()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getNetworkType()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getOemName()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getOperatingSystem()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getOperatingSystemVersion()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getRoleInstance()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getRoleName()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getScreenResolution()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context.getType()
