items:
- uid: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element
  id: _jmx_list_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.getJmx()
  - com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.setJmx(ArrayList<JmxXmlElement>)
  href: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.yml
  langs:
  - java
  name: JmxListXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxListXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxListXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxListXmlElement.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxListXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.getJmx()
  id: getJmx()
  parent: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.yml
  langs:
  - java
  name: getJmx()
  fullName: ArrayList<JmxXmlElement> com.microsoft.applicationinsights.internal.config.JmxListXmlElement.getJmx()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxListXmlElement.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<JmxXmlElement> getJmx()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._jmx_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.setJmx(ArrayList<JmxXmlElement>)
  id: setJmx(ArrayList<JmxXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_list_xml_element.yml
  langs:
  - java
  name: setJmx(ArrayList<JmxXmlElement> jmx)
  fullName: void com.microsoft.applicationinsights.internal.config.JmxListXmlElement.setJmx(ArrayList<JmxXmlElement> jmx)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxListXmlElement.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setJmx(ArrayList<JmxXmlElement> jmx)
    parameters:
    - id: jmx
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._jmx_xml_elementa08ddfce
references:
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._jmx_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
    name: JmxXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
    href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  name: JmxXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxXmlElement
