items:
- uid: com.microsoft.applicationinsights.internal.common
  id: common
  children:
  - com.microsoft.applicationinsights.internal.common._application_insights_event
  - com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  - com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  href: com.microsoft.applicationinsights.internal.common.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.common
  fullName: com.microsoft.applicationinsights.internal.common
  type: Namespace
  source:
    remote:
      path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 21
  syntax:
    content: namespace common
references:
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  name: ApplicationInsightsEvent
  fullName: com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent
  type: Class
  summary: <p>Interface for </p>
  syntax:
    content: public class ApplicationInsightsEvent
- uid: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._log_telemetry_client_proxy.yml
  name: LogTelemetryClientProxy
  fullName: com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy
  type: Class
  summary: <p>This class encapsulates all the common logic for sending AI telemetry. This class is used by all Appenders, Listeners etc and therefore keeping them without any logic. </p>
  syntax:
    content: public class LogTelemetryClientProxy implements TelemetryClientProxy
- uid: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.yml
  name: TelemetryClientProxy
  fullName: com.microsoft.applicationinsights.internal.common.TelemetryClientProxy
  type: Interface
  syntax:
    content: public interface TelemetryClientProxy
