items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  id: internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_tests
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
  - com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java
    startLine: 21
  syntax:
    content: namespace internal
references:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._constants.yml
  name: Constants
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.Constants
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class Constants
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  name: DockerContext
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>Represents the Docker context, which includes the host name, image name, container name and container ID. The Docker context file is written in the following structure: Docker host=host_name,Docker image=image_name,Docker container id=con_id,Docker container name=con_name </p>
  syntax:
    content: public class DockerContext
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.yml
  name: DockerContextFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextFactory
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextFactory
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  name: DockerContextPoller
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPoller
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.yml
  name: DockerContextPollerTests
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPollerTests
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPollerTests
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_tests
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_tests.yml
  name: DockerContextTests
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextTests
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextTests
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.yml
  name: FileFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.FileFactory
  type: Class
  summary: <p>Created by yonisha on 8/3/2015. </p>
  syntax:
    content: public class FileFactory
