items:
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config
  id: _with_http_config
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.defineBackendHttpConfiguration(String)
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithHttpConfig
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfig
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 293
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to add a backend HTTP configuration. </p>
  syntax:
    content: public interface WithHttpConfig
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.defineBackendHttpConfiguration(String)
  id: defineBackendHttpConfiguration(String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.yml
  langs:
  - java
  name: defineBackendHttpConfiguration(String name)
  fullName: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.Blank<WithHttpConfigOrRequestRoutingRule> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfig.defineBackendHttpConfiguration(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 299
  package: com.microsoft.azure.management.network
  summary: <p>Begins the definition of a new application gateway backend HTTP configuration to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayBackendHttpConfiguration.DefinitionStages.Blank<WithHttpConfigOrRequestRoutingRule> defineBackendHttpConfiguration(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the backend HTTP configuration </p>
    return:
      type: 87765286com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06a08ddfce
      description: <p>the first stage of the backend HTTP configuration definition </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 87765286com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06a08ddfce
  spec.java:
  - name: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.Blank<
    fullName: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.Blank<
  - uid: com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06
    name: ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule
    fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule
    href: com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
- uid: com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333a
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333a.yml
  name: ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to continue adding more backends or start defining backend HTTP configurations. </p>
  syntax:
    content: public interface WithBackendOrHttpConfig extends ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithHttpConfig
- uid: com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06.yml
  name: ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to continue adding more backend HTTP configurations or start adding request routing rules. </p>
  syntax:
    content: public interface WithHttpConfigOrRequestRoutingRule
