items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._definition
  id: _definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._definition.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.Definition<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 173
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of an application gateway HTTP listener definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontend<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  - com.microsoft.azure.management.network._application_gateway_frontend_htt6865b22bfe5fdb49a979d145bfb87936.withFrontend(String)
  - com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(String)
  - com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(int)
  - com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttp()
  - com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttps()
  - com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.withSslCertificate(String)
  - com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.withSslCertificateFromPfxFile(File)
  - com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.withSslCertificateFromPfxFile(File,String)
  - com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.withSslCertificatePassword(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt6865b22bfe5fdb49a979d145bfb87936.withFrontend(String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_htt6865b22bfe5fdb49a979d145bfb87936
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt6865b22bfe5fdb49a979d145bfb87936.yml
  name: withFrontend(String name)
  fullName: WithFrontendPort<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontend<ParentT>.withFrontend(String name)
  type: Method
  summary: <p>Associates the HTTP listener with a frontend existing on this application gateway. </p>
  syntax:
    content: public WithFrontendPort<ParentT> withFrontend(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing frontend </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cbda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb
  href: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.yml
  name: withFrontendPort(String name)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>.withFrontendPort(String name)
  type: Method
  summary: <p>Enables the listener to listen on the specified existing frontend port. </p>
  syntax:
    content: public WithAttach<ParentT> withFrontendPort(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing frontend port </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.withFrontendPort(int)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb
  href: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.yml
  name: withFrontendPort(int portNumber)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>.withFrontendPort(int portNumber)
  type: Method
  summary: <p>Enables the listener to listen on the specified port number, creating a new automatically-named port for it if needed, or associating it with an existing frontend port that is already configured to listen on this port number. </p>
  syntax:
    content: public WithAttach<ParentT> withFrontendPort(int portNumber)
    parameters:
    - id: portNumber
      type: f75371fa
      description: <p>a port number </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttp()
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f
  href: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.yml
  name: withHttp()
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>.withHttp()
  type: Method
  summary: <p>Specifies that the listener is for the HTTP protocol. </p>
  syntax:
    content: public WithAttach<ParentT> withHttp()
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.withHttps()
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f
  href: com.microsoft.azure.management.network._application_gateway_frontend_httcb04b63f9811a9fcbc10be21f8a4ac3f.yml
  name: withHttps()
  fullName: WithSslCertificate<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>.withHttps()
  type: Method
  summary: <p>Specifies that the listener is for the HTTPS protocol. </p>
  syntax:
    content: public WithSslCertificate<ParentT> withHttps()
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.withSslCertificate(String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.yml
  name: withSslCertificate(String name)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>.withSslCertificate(String name)
  type: Method
  summary: <p>Specifies an SSL certificate to associate with this listener, if its protocol is HTTPS. </p>
  syntax:
    content: public WithAttach<ParentT> withSslCertificate(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing SSL certificate associated with this application gateway </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.withSslCertificateFromPfxFile(File)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.yml
  name: withSslCertificateFromPfxFile(File pfxFile)
  fullName: WithSslPassword<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>.withSslCertificateFromPfxFile(File pfxFile)
  type: Method
  summary: >-
    <p>Specifies the PFX file to import the SSL certificate from to associate with this listener to enable HTTPS. </p>

    <p>The certificate will be named using an auto-generated name. </p>
  syntax:
    content: public WithSslPassword<ParentT> withSslCertificateFromPfxFile(File pfxFile)
    parameters:
    - id: pfxFile
      type: 8291270b
      description: <p>an existing PFX file </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.withSslCertificateFromPfxFile(File,String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.yml
  name: withSslCertificateFromPfxFile(File pfxFile, String name)
  fullName: WithSslPassword<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>.withSslCertificateFromPfxFile(File pfxFile, String name)
  type: Method
  summary: <p>Specifies the PFX file to import the SSL certificate from to associate with this listener to enable HTTPS. </p>
  syntax:
    content: public WithSslPassword<ParentT> withSslCertificateFromPfxFile(File pfxFile, String name)
    parameters:
    - id: pfxFile
      type: 8291270b
      description: <p>an existing PFX file </p>
    - id: name
      type: "26831127"
      description: <p>a new name for the certificate that will be used to reference this certificate </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.withSslCertificatePassword(String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39
  href: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.yml
  name: withSslCertificatePassword(String password)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>.withSslCertificatePassword(String password)
  type: Method
  summary: <p>Specifies the password for the specified PFX file containing the private key of the imported SSL certificate. </p>
  syntax:
    content: public WithAttach<ParentT> withSslCertificatePassword(String password)
    parameters:
    - id: password
      type: "26831127"
      description: <p>the password of the imported PFX file </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httd139af086e505570c7167593f191fb91
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_httd139af086e505570c7167593f191fb91.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of an application gateway HTTP listener. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway HTTP listener. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt6865b22bfe5fdb49a979d145bfb87936
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt6865b22bfe5fdb49a979d145bfb87936.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontend<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontend<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the frontend IP configuration to associate the listener with. </p>
  syntax:
    content: public interface WithFrontend<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_httca402858f06c4f16875a6f30257076cb.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the frontend port to associate the listener with. </p>
  syntax:
    content: public interface WithFrontendPort<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt624928659082e3758026909bc0885f67.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the SSL certificate to associate with the listener. </p>
  syntax:
    content: public interface WithSslCertificate<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the password for the private key of the imported SSL certificate. </p>
  syntax:
    content: public interface WithSslPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
