items:
- uid: com.microsoft.applicationinsights.internal.annotation._performance_module
  id: _performance_module
  parent: com.microsoft.applicationinsights.internal.annotation
  children:
  - com.microsoft.applicationinsights.internal.annotation._performance_module.value()
  href: com.microsoft.applicationinsights.internal.annotation._performance_module.yml
  langs:
  - java
  name: PerformanceModule
  fullName: com.microsoft.applicationinsights.internal.annotation.PerformanceModule
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/PerformanceModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/PerformanceModule.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.annotation
  syntax:
    content: public interface PerformanceModule
- uid: com.microsoft.applicationinsights.internal.annotation._performance_module.value()
  id: value()
  parent: com.microsoft.applicationinsights.internal.annotation._performance_module
  href: com.microsoft.applicationinsights.internal.annotation._performance_module.yml
  langs:
  - java
  name: value()
  fullName: String com.microsoft.applicationinsights.internal.annotation.PerformanceModule.value()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/annotation/PerformanceModule.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.annotation
  syntax:
    content: public String value() default"BuiltIn"
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
