items:
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  id: _internal_agent_logger
  parent: com.microsoft.applicationinsights.agent.internal.logger
  children:
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.error(String,Object...)
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.info(String,Object...)
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.initialize(String)
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isErrorEnabled()
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isInfoEnabled()
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isTraceEnabled()
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isWarnEnabled()
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.logAlways(LoggingLevel,String,Object...)
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.trace(String,Object...)
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.warn(String,Object...)
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: InternalAgentLogger
  fullName: com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger
  type: Enum
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.logger
  summary: <p>Created by gupele on 6/3/2015. </p>
  syntax:
    content: public enum InternalAgentLogger
  inheritance:
  - java.lang.Object
  - java.lang.Enum<InternalAgentLogger>
  inheritedMembers:
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger_1a3b1ce0d51d6227dff2dcf1ceba4a7158
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.error(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: error(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.error(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 99
  package: com.microsoft.applicationinsights.agent.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for errors, will not allow any exception thrown </p>
  syntax:
    content: public void error(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.info(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: info(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.info(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 125
  package: com.microsoft.applicationinsights.agent.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for info messages, will not allow any exception thrown </p>
  syntax:
    content: public void info(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.initialize(String)
  id: initialize(String)
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: initialize(String loggerLevel)
  fullName: synchronized void com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.initialize(String loggerLevel)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 74
  package: com.microsoft.applicationinsights.agent.internal.logger
  syntax:
    content: public synchronized void initialize(String loggerLevel)
    parameters:
    - id: loggerLevel
      type: "26831127"
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isErrorEnabled()
  id: isErrorEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: isErrorEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.isErrorEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 70
  package: com.microsoft.applicationinsights.agent.internal.logger
  syntax:
    content: public boolean isErrorEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isInfoEnabled()
  id: isInfoEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: isInfoEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.isInfoEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 62
  package: com.microsoft.applicationinsights.agent.internal.logger
  syntax:
    content: public boolean isInfoEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isTraceEnabled()
  id: isTraceEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: isTraceEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.isTraceEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 58
  package: com.microsoft.applicationinsights.agent.internal.logger
  syntax:
    content: public boolean isTraceEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.isWarnEnabled()
  id: isWarnEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: isWarnEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.isWarnEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 66
  package: com.microsoft.applicationinsights.agent.internal.logger
  syntax:
    content: public boolean isWarnEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.logAlways(LoggingLevel,String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: logAlways(LoggingLevel requestLevel, String message, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.logAlways(LoggingLevel requestLevel, String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 145
  package: com.microsoft.applicationinsights.agent.internal.logger
  syntax:
    content: public void logAlways(LoggingLevel requestLevel, String message, Object...args)
    parameters:
    - id: requestLevel
      type: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger._logging_level
    - id: message
      type: "26831127"
    - id: args
      type: 1355eaf1
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.trace(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: trace(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.trace(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 138
  package: com.microsoft.applicationinsights.agent.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for at least trace level, will not allow any exception thrown </p>
  syntax:
    content: public void trace(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.warn(String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  langs:
  - java
  name: warn(String message, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.warn(String message, Object...args)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 112
  package: com.microsoft.applicationinsights.agent.internal.logger
  summary: <p>The main method, will delegate the call to the output only if the logger is enabled for warnings, will not allow any exception thrown </p>
  syntax:
    content: public void warn(String message, Object...args)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log with possible placeholders. </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments that should be formatted into the placeholders. </p>
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 5c0b90ca
  spec.java:
  - name: synchronized void
    fullName: synchronized void
- uid: 1355eaf1
  spec.java:
  - name: Object...
    fullName: Object...
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger_1a3b1ce0d51d6227dff2dcf1ceba4a7158
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger._logging_level
  parent: com.microsoft.applicationinsights.agent.internal.logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger._logging_level.yml
  name: InternalAgentLogger.LoggingLevel
  fullName: com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.LoggingLevel
  type: Enum
  syntax:
    content: public enum LoggingLevel
