items:
- uid: com.microsoft.azure.management.network._application_gateway_public_front6a4ca36a34bc7cf04abec8aab61524a5
  id: _application_gateway_public_front6a4ca36a34bc7cf04abec8aab61524a5
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_front6a4ca36a34bc7cf04abec8aab61524a5.yml
  langs:
  - java
  name: ApplicationGatewayPublicFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPublicFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPublicFrontend.java
    startLine: 93
  package: com.microsoft.azure.management.network
  summary: <p>The stage of a public frontend definition allowing to specify an existing public IP address. </p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT> extends HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<WithAttach<ParentT>>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(PublicIpAddress)
  - com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(PublicIpAddress)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
    parameters:
    - id: publicIpAddress
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(String)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: withExistingPublicIpAddress(String resourceId)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(String resourceId)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(String resourceId)
    parameters:
    - id: resourceId
      type: "26831127"
      description: <p>the resource ID of an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>
  type: Interface
  summary: >-
    <p>The stage of the definition allowing to associate the resource with an existing public IP address.</p>

    <p></p>
  syntax:
    content: public interface WithExistingPublicIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_public_frontend._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_frontend._update_definition.yml
  name: ApplicationGatewayPublicFrontend.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a public frontend definition as part of an Internet-facing application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayPublicFrontend.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayPublicFrontend.UpdateDefinitionStages.WithAttach<ParentT>,ApplicationGatewayPublicFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_public_front2166d99eb970c6867dc118077de16032
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_front2166d99eb970c6867dc118077de16032.yml
  name: ApplicationGatewayPublicFrontend.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of a public frontend definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayPublicFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdate<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
