items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider
  id: _jedis_class_data_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.redis
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.add()
  - com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.JedisClassDataProvider(Map<String, ClassInstrumentationData>)
  href: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.yml
  langs:
  - java
  name: JedisClassDataProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.redis.JedisClassDataProvider
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
    startLine: 36
  package: com.microsoft.applicationinsights.agent.internal.agent.redis
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JedisClassDataProvider
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.add()
  id: add()
  parent: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.yml
  langs:
  - java
  name: add()
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.redis.JedisClassDataProvider.add()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
    startLine: 45
  package: com.microsoft.applicationinsights.agent.internal.agent.redis
  syntax:
    content: public void add()
- uid: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.JedisClassDataProvider(Map<String, ClassInstrumentationData>)
  id: JedisClassDataProvider(Map<String, ClassInstrumentationData>)
  parent: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.redis._jedis_class_data_provider.yml
  langs:
  - java
  name: JedisClassDataProvider(Map<String, ClassInstrumentationData> classesToInstrument)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.redis.JedisClassDataProvider.JedisClassDataProvider(Map<String, ClassInstrumentationData> classesToInstrument)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
    startLine: 41
  package: com.microsoft.applicationinsights.agent.internal.agent.redis
  syntax:
    content: public JedisClassDataProvider(Map<String, ClassInstrumentationData> classesToInstrument)
    parameters:
    - id: classesToInstrument
      type: 2108f1f4com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
references:
- uid: 2108f1f4com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
  spec.java:
  - name: 'Map<String, '
    fullName: 'Map<String, '
  - uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    name: ClassInstrumentationData
    fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
    href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
