items:
- uid: com.microsoft.applicationinsights.extensibility.context
  id: context
  children:
  - com.microsoft.applicationinsights.extensibility.context._component_context
  - com.microsoft.applicationinsights.extensibility.context._component_context_test
  - com.microsoft.applicationinsights.extensibility.context._context_tag_keys
  - com.microsoft.applicationinsights.extensibility.context._device_context
  - com.microsoft.applicationinsights.extensibility.context._device_context_test
  - com.microsoft.applicationinsights.extensibility.context._internal_context
  - com.microsoft.applicationinsights.extensibility.context._internal_context_test
  - com.microsoft.applicationinsights.extensibility.context._location_context
  - com.microsoft.applicationinsights.extensibility.context._location_context_test
  - com.microsoft.applicationinsights.extensibility.context._operation_context
  - com.microsoft.applicationinsights.extensibility.context._operation_context_test
  - com.microsoft.applicationinsights.extensibility.context._session_context
  - com.microsoft.applicationinsights.extensibility.context._session_context_test
  - com.microsoft.applicationinsights.extensibility.context._user_context
  - com.microsoft.applicationinsights.extensibility.context._user_context_test
  href: com.microsoft.applicationinsights.extensibility.context.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.extensibility.context
  fullName: com.microsoft.applicationinsights.extensibility.context
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/ComponentContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/ComponentContext.java
    startLine: 21
  syntax:
    content: namespace context
references:
- uid: com.microsoft.applicationinsights.extensibility.context._component_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._component_context.yml
  name: ComponentContext
  fullName: com.microsoft.applicationinsights.extensibility.context.ComponentContext
  type: Class
  syntax:
    content: public class ComponentContext
- uid: com.microsoft.applicationinsights.extensibility.context._component_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._component_context_test.yml
  name: ComponentContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.ComponentContextTest
  type: Class
  syntax:
    content: public class ComponentContextTest
- uid: com.microsoft.applicationinsights.extensibility.context._context_tag_keys
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._context_tag_keys.yml
  name: ContextTagKeys
  fullName: com.microsoft.applicationinsights.extensibility.context.ContextTagKeys
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.extensibility.context._context_tag_keys" data-throw-if-not-resolved="false"></xref>

    </p>
  syntax:
    content: public class ContextTagKeys
- uid: com.microsoft.applicationinsights.extensibility.context._device_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._device_context.yml
  name: DeviceContext
  fullName: com.microsoft.applicationinsights.extensibility.context.DeviceContext
  type: Class
  syntax:
    content: public class DeviceContext
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  name: DeviceContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.DeviceContextTest
  type: Class
  syntax:
    content: public class DeviceContextTest
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  name: InternalContext
  fullName: com.microsoft.applicationinsights.extensibility.context.InternalContext
  type: Class
  syntax:
    content: public class InternalContext
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context_test.yml
  name: InternalContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.InternalContextTest
  type: Class
  syntax:
    content: public class InternalContextTest
- uid: com.microsoft.applicationinsights.extensibility.context._location_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._location_context.yml
  name: LocationContext
  fullName: com.microsoft.applicationinsights.extensibility.context.LocationContext
  type: Class
  syntax:
    content: public class LocationContext
- uid: com.microsoft.applicationinsights.extensibility.context._location_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._location_context_test.yml
  name: LocationContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.LocationContextTest
  type: Class
  syntax:
    content: public class LocationContextTest
- uid: com.microsoft.applicationinsights.extensibility.context._operation_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._operation_context.yml
  name: OperationContext
  fullName: com.microsoft.applicationinsights.extensibility.context.OperationContext
  type: Class
  syntax:
    content: public class OperationContext
- uid: com.microsoft.applicationinsights.extensibility.context._operation_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._operation_context_test.yml
  name: OperationContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.OperationContextTest
  type: Class
  syntax:
    content: public class OperationContextTest
- uid: com.microsoft.applicationinsights.extensibility.context._session_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._session_context.yml
  name: SessionContext
  fullName: com.microsoft.applicationinsights.extensibility.context.SessionContext
  type: Class
  syntax:
    content: public class SessionContext
- uid: com.microsoft.applicationinsights.extensibility.context._session_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._session_context_test.yml
  name: SessionContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.SessionContextTest
  type: Class
  syntax:
    content: public class SessionContextTest
- uid: com.microsoft.applicationinsights.extensibility.context._user_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._user_context.yml
  name: UserContext
  fullName: com.microsoft.applicationinsights.extensibility.context.UserContext
  type: Class
  syntax:
    content: public class UserContext
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  name: UserContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.UserContextTest
  type: Class
  syntax:
    content: public class UserContextTest
