items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  id: _abstract_performance_counter_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  langs:
  - java
  name: AbstractPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractPerformanceCounterModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractPerformanceCounterModule.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>A base class for performance modules.</p>

    <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class AbstractPerformanceCounterModule implements TelemetryModule
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_module
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  id: AbstractPerformanceCounterModule(PerformanceCountersFactory)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  langs:
  - java
  name: AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractPerformanceCounterModule.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: protected AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
    parameters:
    - id: factory
      type: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  id: factory()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  langs:
  - java
  name: factory
  fullName: final PerformanceCountersFactory com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.factory
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractPerformanceCounterModule.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: protected final PerformanceCountersFactory factory
    return:
      type: 93de0ef9com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  id: initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  langs:
  - java
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(TelemetryConfiguration configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractPerformanceCounterModule.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>The main method will use the factory to fetch the performance counters and register them for work. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
references:
- uid: 93de0ef9com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
    name: PerformanceCountersFactory
    fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCountersFactory
    href: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory.yml
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: TelemetryModule
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface TelemetryModule
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  name: JvmPerformanceCountersModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule
  type: Class
  summary: >-
    <p>The class loads the relevant Jvm PCs</p>

    <p>By default the class will create all the JVM PC</p>

    <p>The class will not be activated if the enclosing XML tag will have the 'UseBuiltIn' tag set to false:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;UseBuiltIn&gt;false&lt;/UseBuiltIn&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>All Jvm PCs can be disabled like this, without disabling the other built in performance counters:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline></codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Jvm<sp></sp>enabled="false"/&gt;</highlight>

          </codeline>

          <codeline></codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>A specific Jvm counter can be disabled like this:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Jvm&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;JvmPC<sp></sp>name="ThreadDeadLockDetector"<sp></sp>enabled="false"/&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;/Jvm&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class JvmPerformanceCountersModule
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  name: ProcessPerformanceCountersModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule
  type: Class
  summary: >-
    <p>The class will be used when the SDK needs to add the 'built-in' performance counters.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public class ProcessPerformanceCountersModule
- uid: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module
  parent: com.microsoft.applicationinsights.web.internal.perfcounter
  href: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.yml
  name: WebPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
  type: Class
  summary: <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class WebPerformanceCounterModule
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory.yml
  name: PerformanceCountersFactory
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCountersFactory
  type: Interface
  summary: >-
    <p>Defines the interface that concrete factories should follow. The major method is the one that will be able create the needed Performance Counters.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface PerformanceCountersFactory
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_module
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>Initializes the telemetry module. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
