items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state
  id: _unix_parsing_state
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.doneCounter()
  - com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.returnValue()
  - com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.UnixParsingState(int)
  href: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.yml
  langs:
  - java
  name: UnixParsingState
  fullName: com.microsoft.applicationinsights.internal.perfcounter.UnixParsingState
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixParsingState.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixParsingState.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Created by gupele on 3/16/2015. </p>
  syntax:
    content: public class UnixParsingState
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.doneCounter()
  id: doneCounter()
  parent: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state
  href: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.yml
  langs:
  - java
  name: doneCounter
  fullName: int com.microsoft.applicationinsights.internal.perfcounter.UnixParsingState.doneCounter
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixParsingState.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public int doneCounter
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.returnValue()
  id: returnValue()
  parent: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state
  href: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.yml
  langs:
  - java
  name: returnValue
  fullName: double com.microsoft.applicationinsights.internal.perfcounter.UnixParsingState.returnValue
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixParsingState.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public double returnValue
    return:
      type: a07dcde8
- uid: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.UnixParsingState(int)
  id: UnixParsingState(int)
  parent: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state
  href: com.microsoft.applicationinsights.internal.perfcounter._unix_parsing_state.yml
  langs:
  - java
  name: UnixParsingState(int doneCounter)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.UnixParsingState.UnixParsingState(int doneCounter)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixParsingState.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public UnixParsingState(int doneCounter)
    parameters:
    - id: doneCounter
      type: f75371fa
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: a07dcde8
  spec.java:
  - name: double
    fullName: double
