items:
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data
  id: _event_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._event_data.EventData()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.getBaseTypeName()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.getEnvelopName()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.getMeasurements()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.getName()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.getProperties()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.getVer()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._event_data.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._event_data.setMeasurements(ConcurrentMap<String, Double>)
  - com.microsoft.applicationinsights.internal.schemav2._event_data.setName(String)
  - com.microsoft.applicationinsights.internal.schemav2._event_data.setProperties(ConcurrentMap<String, String>)
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: EventData
  fullName: com.microsoft.applicationinsights.internal.schemav2.EventData
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._event_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class EventData extends Domain
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
  - com.microsoft.applicationinsights.internal.schemav2._sendable_data
  - com.microsoft.applicationinsights.internal.schemav2._domain
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.schemav2._domain.Domain()
  - com.microsoft.applicationinsights.internal.schemav2._domain.serialize(JsonTelemetryDataSerializer)
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.EventData()
  id: EventData()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: EventData()
  fullName: com.microsoft.applicationinsights.internal.schemav2.EventData.EventData()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public EventData()
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getBaseTypeName()
  id: getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.EventData.getBaseTypeName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 121
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getEnvelopName()
  id: getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.EventData.getEnvelopName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 116
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getMeasurements()
  id: getMeasurements()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: getMeasurements()
  fullName: ConcurrentMap<String, Double> com.microsoft.applicationinsights.internal.schemav2.EventData.getMeasurements()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public ConcurrentMap<String, Double> getMeasurements()
    return:
      type: 5f392589
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.EventData.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 76
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getProperties()
  id: getProperties()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: getProperties()
  fullName: ConcurrentMap<String, String> com.microsoft.applicationinsights.internal.schemav2.EventData.getProperties()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 84
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public ConcurrentMap<String, String> getProperties()
    return:
      type: bc7a2f3a
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getVer()
  id: getVer()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: getVer()
  fullName: int com.microsoft.applicationinsights.internal.schemav2.EventData.getVer()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 72
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public int getVer()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.EventData.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 125
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.EventData.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 106
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.setMeasurements(ConcurrentMap<String, Double>)
  id: setMeasurements(ConcurrentMap<String, Double>)
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: setMeasurements(ConcurrentMap<String, Double> value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.EventData.setMeasurements(ConcurrentMap<String, Double> value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 102
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setMeasurements(ConcurrentMap<String, Double> value)
    parameters:
    - id: value
      type: 5f392589
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: setName(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.EventData.setName(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 80
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setName(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.setProperties(ConcurrentMap<String, String>)
  id: setProperties(ConcurrentMap<String, String>)
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  langs:
  - java
  name: setProperties(ConcurrentMap<String, String> value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.EventData.setProperties(ConcurrentMap<String, String> value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/EventData.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setProperties(ConcurrentMap<String, String> value)
    parameters:
    - id: value
      type: bc7a2f3a
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: bc7a2f3a
  spec.java:
  - name: ConcurrentMap<String, String>
    fullName: ConcurrentMap<String, String>
- uid: 5f392589
  spec.java:
  - name: ConcurrentMap<String, Double>
    fullName: ConcurrentMap<String, Double>
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.Domain()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: Domain()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Domain.Domain()
  type: Constructor
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public Domain()
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Domain.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._domain
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: Domain
  fullName: com.microsoft.applicationinsights.internal.schemav2.Domain
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._domain" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Domain implements SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._page_view_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._page_view_data.yml
  name: PageViewData
  fullName: com.microsoft.applicationinsights.internal.schemav2.PageViewData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._page_view_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class PageViewData
- uid: com.microsoft.applicationinsights.internal.schemav2._envelope
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._envelope.yml
  name: Envelope
  fullName: com.microsoft.applicationinsights.internal.schemav2.Envelope
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._envelope" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Envelope implements JsonSerializable
- uid: com.microsoft.applicationinsights.internal.schemav2._base
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  name: Base
  fullName: com.microsoft.applicationinsights.internal.schemav2.Base
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._base" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Base implements JsonSerializable,SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  name: EventData
  fullName: com.microsoft.applicationinsights.internal.schemav2.EventData
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._event_data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
