items:
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context
  id: _internal_context
  parent: com.microsoft.applicationinsights.extensibility.context
  children:
  - com.microsoft.applicationinsights.extensibility.context._internal_context.getAgentVersion()
  - com.microsoft.applicationinsights.extensibility.context._internal_context.getNodeName()
  - com.microsoft.applicationinsights.extensibility.context._internal_context.getSdkVersion()
  - com.microsoft.applicationinsights.extensibility.context._internal_context.InternalContext(ConcurrentMap<String, String>)
  - com.microsoft.applicationinsights.extensibility.context._internal_context.setAgentVersion(String)
  - com.microsoft.applicationinsights.extensibility.context._internal_context.setNodeName(String)
  - com.microsoft.applicationinsights.extensibility.context._internal_context.setSdkVersion(String)
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: InternalContext
  fullName: com.microsoft.applicationinsights.extensibility.context.InternalContext
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 27
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public class InternalContext
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.getAgentVersion()
  id: getAgentVersion()
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: getAgentVersion()
  fullName: String com.microsoft.applicationinsights.extensibility.context.InternalContext.getAgentVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 42
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public String getAgentVersion()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.getNodeName()
  id: getNodeName()
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: getNodeName()
  fullName: String com.microsoft.applicationinsights.extensibility.context.InternalContext.getNodeName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 50
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public String getNodeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.getSdkVersion()
  id: getSdkVersion()
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: getSdkVersion()
  fullName: String com.microsoft.applicationinsights.extensibility.context.InternalContext.getSdkVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 34
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public String getSdkVersion()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.InternalContext(ConcurrentMap<String, String>)
  id: InternalContext(ConcurrentMap<String, String>)
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: InternalContext(ConcurrentMap<String, String> tags)
  fullName: com.microsoft.applicationinsights.extensibility.context.InternalContext.InternalContext(ConcurrentMap<String, String> tags)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 30
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public InternalContext(ConcurrentMap<String, String> tags)
    parameters:
    - id: tags
      type: bc7a2f3a
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.setAgentVersion(String)
  id: setAgentVersion(String)
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: setAgentVersion(String version)
  fullName: void com.microsoft.applicationinsights.extensibility.context.InternalContext.setAgentVersion(String version)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 46
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setAgentVersion(String version)
    parameters:
    - id: version
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.setNodeName(String)
  id: setNodeName(String)
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: setNodeName(String nodeName)
  fullName: void com.microsoft.applicationinsights.extensibility.context.InternalContext.setNodeName(String nodeName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 54
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setNodeName(String nodeName)
    parameters:
    - id: nodeName
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context.setSdkVersion(String)
  id: setSdkVersion(String)
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context
  href: com.microsoft.applicationinsights.extensibility.context._internal_context.yml
  langs:
  - java
  name: setSdkVersion(String version)
  fullName: void com.microsoft.applicationinsights.extensibility.context.InternalContext.setSdkVersion(String version)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/InternalContext.java
    startLine: 38
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void setSdkVersion(String version)
    parameters:
    - id: version
      type: "26831127"
references:
- uid: bc7a2f3a
  spec.java:
  - name: ConcurrentMap<String, String>
    fullName: ConcurrentMap<String, String>
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
