items:
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  id: _data_of_configuration_for_exception
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.getStackSize()
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.getSuppressedExceptions()
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.getValidPathForExceptions()
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.isEnabled()
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setEnabled(boolean)
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setStackSize(int)
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setSuppressedExceptions(HashSet<String>)
  - com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setValidPathForExceptions(HashSet<String>)
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: DataOfConfigurationForException
  fullName: com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 28
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Created by gupele on 8/18/2016. </p>
  syntax:
    content: public class DataOfConfigurationForException
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.getStackSize()
  id: getStackSize()
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: getStackSize()
  fullName: int com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.getStackSize()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 34
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public int getStackSize()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.getSuppressedExceptions()
  id: getSuppressedExceptions()
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: getSuppressedExceptions()
  fullName: HashSet<String> com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.getSuppressedExceptions()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 42
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public HashSet<String> getSuppressedExceptions()
    return:
      type: 7240edcf
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.getValidPathForExceptions()
  id: getValidPathForExceptions()
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: getValidPathForExceptions()
  fullName: HashSet<String> com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.getValidPathForExceptions()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 50
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public HashSet<String> getValidPathForExceptions()
    return:
      type: 7240edcf
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.isEnabled()
  id: isEnabled()
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: isEnabled()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.isEnabled()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 58
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setEnabled(boolean)
  id: setEnabled(boolean)
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: setEnabled(boolean enabled)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.setEnabled(boolean enabled)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 62
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void setEnabled(boolean enabled)
    parameters:
    - id: enabled
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setStackSize(int)
  id: setStackSize(int)
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: setStackSize(int stackSize)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.setStackSize(int stackSize)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 38
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void setStackSize(int stackSize)
    parameters:
    - id: stackSize
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setSuppressedExceptions(HashSet<String>)
  id: setSuppressedExceptions(HashSet<String>)
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: setSuppressedExceptions(HashSet<String> suppressedExceptions)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.setSuppressedExceptions(HashSet<String> suppressedExceptions)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 46
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void setSuppressedExceptions(HashSet<String> suppressedExceptions)
    parameters:
    - id: suppressedExceptions
      type: 7240edcf
- uid: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.setValidPathForExceptions(HashSet<String>)
  id: setValidPathForExceptions(HashSet<String>)
  parent: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception
  href: com.microsoft.applicationinsights.agent.internal.config._data_of_configuration_for_exception.yml
  langs:
  - java
  name: setValidPathForExceptions(HashSet<String> validPathForExceptions)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.DataOfConfigurationForException.setValidPathForExceptions(HashSet<String> validPathForExceptions)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/DataOfConfigurationForException.java
    startLine: 54
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void setValidPathForExceptions(HashSet<String> validPathForExceptions)
    parameters:
    - id: validPathForExceptions
      type: 7240edcf
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 7240edcf
  spec.java:
  - name: HashSet<String>
    fullName: HashSet<String>
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
