items:
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  id: _valid_processors_with_setters
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.process(Telemetry)
  - com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.propertyA()
  - com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.propertyB()
  - com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.setPropertyA(String)
  - com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.setPropertyB(String)
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  langs:
  - java
  name: ValidProcessorsWithSetters
  fullName: com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class ValidProcessorsWithSetters implements TelemetryProcessor
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_processor
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.process(Telemetry)
  id: process(Telemetry)
  parent: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  langs:
  - java
  name: process(Telemetry telemetry)
  fullName: boolean com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters.process(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public boolean process(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
    return:
      type: 4fc6e284
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_processor.process(Telemetry)
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.propertyA()
  id: propertyA()
  parent: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  langs:
  - java
  name: propertyA
  fullName: String com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters.propertyA
  type: Field
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String propertyA
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.propertyB()
  id: propertyB()
  parent: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  langs:
  - java
  name: propertyB
  fullName: String com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters.propertyB
  type: Field
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String propertyB
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.setPropertyA(String)
  id: setPropertyA(String)
  parent: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  langs:
  - java
  name: setPropertyA(String propertyA)
  fullName: void com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters.setPropertyA(String propertyA)
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setPropertyA(String propertyA)
    parameters:
    - id: propertyA
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.setPropertyB(String)
  id: setPropertyB(String)
  parent: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters
  href: com.microsoft.applicationinsights.internal.config._valid_processors_with_setters.yml
  langs:
  - java
  name: setPropertyB(String propertyB)
  fullName: void com.microsoft.applicationinsights.internal.config.ValidProcessorsWithSetters.setPropertyB(String propertyB)
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorsWithSetters.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setPropertyB(String propertyB)
    parameters:
    - id: propertyB
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: TelemetryProcessor
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryProcessor
  type: Interface
  summary: "<p>The method gets a <ref refid=\"\" kindref=\"compound\">Telemetry</ref> instance that is ready to be sent. This is your chance to approve or deny it. Returning 'false' means that the Telemetry will not be sent while 'true' means you approve it.</p>\r\n<p>The Telemetry might go through other filters though, that might deny its sending.</p>\r\n<p>To enable this processor you need to add it in the ApplicationInsights.xml like this:</p>\r\n<p>\r\n  <preformatted>\r\n    <programlisting>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Processor<sp></sp>type=\"full.path.to.Filter\"&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Add<sp></sp>name=\"Property\"<sp></sp>value=\"stringValue\"/&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/Processor&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;/TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n    </programlisting> \r\n*</preformatted>\r\n</p>\r\n<p>Note that the class defines a property named 'Property' which is configured too. Every property that you wish to configure needs to have a 'setX' public method like 'setProperty' in this example <bold>Exceptions thrown from the 'setX' methods will be caught by the framework that will ignore the filter</bold></p>\r\n<p>Created by gupele on 7/26/2016. </p>"
  syntax:
    content: public interface TelemetryProcessor
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor.process(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_processor
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: process(Telemetry telemetry)
  fullName: boolean com.microsoft.applicationinsights.extensibility.TelemetryProcessor.process(Telemetry telemetry)
  type: Method
  syntax:
    content: public boolean process(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
