items:
- uid: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type
  id: _instrumented_class_type
  parent: com.microsoft.applicationinsights.agent.internal.coresync
  children:
  - com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.HTTP()
  - com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.OTHER()
  - com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.SQL()
  href: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.yml
  langs:
  - java
  name: InstrumentedClassType
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.InstrumentedClassType
  type: Enum
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/InstrumentedClassType.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/InstrumentedClassType.java
    startLine: 26
  package: com.microsoft.applicationinsights.agent.internal.coresync
  summary: <p>Created by gupele on 5/17/2015. </p>
  syntax:
    content: public enum InstrumentedClassType
  inheritance:
  - java.lang.Object
  - java.lang.Enum<InstrumentedClassType>
- uid: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.HTTP()
  id: HTTP()
  parent: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type
  href: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.yml
  langs:
  - java
  name: HTTP
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.InstrumentedClassType.HTTP
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/InstrumentedClassType.java
    startLine: 28
  package: com.microsoft.applicationinsights.agent.internal.coresync
  syntax:
    content: public HTTP
- uid: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.OTHER()
  id: OTHER()
  parent: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type
  href: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.yml
  langs:
  - java
  name: OTHER
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.InstrumentedClassType.OTHER
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/InstrumentedClassType.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.coresync
  syntax:
    content: public OTHER
- uid: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.SQL()
  id: SQL()
  parent: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type
  href: com.microsoft.applicationinsights.agent.internal.coresync._instrumented_class_type.yml
  langs:
  - java
  name: SQL
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.InstrumentedClassType.SQL
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/InstrumentedClassType.java
    startLine: 27
  package: com.microsoft.applicationinsights.agent.internal.coresync
  syntax:
    content: public SQL
references: []
