items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  id: _transmission_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testEmptyContentEncodingType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testEmptyContentType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testGetContent()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testGetWebContentEncodingType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testGetWebContentType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testIncrementNumberOfPersistence()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testIncrementNumberOfSends()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNullContent()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNullContentEncodingType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNullContentType()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNumberOfPersistence()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNumberOfSends()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_test.testVersion()
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: TransmissionTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class TransmissionTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testEmptyContentEncodingType()
  id: testEmptyContentEncodingType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testEmptyContentEncodingType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testEmptyContentEncodingType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testEmptyContentEncodingType()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testEmptyContentType()
  id: testEmptyContentType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testEmptyContentType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testEmptyContentType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testEmptyContentType()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testGetContent()
  id: testGetContent()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testGetContent()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testGetContent()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 98
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testGetContent()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testGetWebContentEncodingType()
  id: testGetWebContentEncodingType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testGetWebContentEncodingType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testGetWebContentEncodingType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 113
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testGetWebContentEncodingType()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testGetWebContentType()
  id: testGetWebContentType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testGetWebContentType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testGetWebContentType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 106
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testGetWebContentType()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testIncrementNumberOfPersistence()
  id: testIncrementNumberOfPersistence()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testIncrementNumberOfPersistence()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testIncrementNumberOfPersistence()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 90
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testIncrementNumberOfPersistence()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testIncrementNumberOfSends()
  id: testIncrementNumberOfSends()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testIncrementNumberOfSends()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testIncrementNumberOfSends()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testIncrementNumberOfSends()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNullContent()
  id: testNullContent()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testNullContent()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testNullContent()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNullContent()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNullContentEncodingType()
  id: testNullContentEncodingType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testNullContentEncodingType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testNullContentEncodingType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNullContentEncodingType()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNullContentType()
  id: testNullContentType()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testNullContentType()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testNullContentType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNullContentType()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNumberOfPersistence()
  id: testNumberOfPersistence()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testNumberOfPersistence()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testNumberOfPersistence()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNumberOfPersistence()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testNumberOfSends()
  id: testNumberOfSends()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testNumberOfSends()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testNumberOfSends()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNumberOfSends()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_test.testVersion()
  id: testVersion()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_test.yml
  langs:
  - java
  name: testVersion()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionTest.testVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionTest.java
    startLine: 61
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testVersion()
references:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
