items:
- uid: com.microsoft.applicationinsights.agent.internal.common
  id: common
  children:
  - com.microsoft.applicationinsights.agent.internal.common._string_utils
  href: com.microsoft.applicationinsights.agent.internal.common.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.common
  fullName: com.microsoft.applicationinsights.agent.internal.common
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/common/StringUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/common/StringUtils.java
    startLine: 21
  syntax:
    content: namespace common
references:
- uid: com.microsoft.applicationinsights.agent.internal.common._string_utils
  parent: com.microsoft.applicationinsights.agent.internal.common
  href: com.microsoft.applicationinsights.agent.internal.common._string_utils.yml
  name: StringUtils
  fullName: com.microsoft.applicationinsights.agent.internal.common.StringUtils
  type: Class
  summary: <p>Created by gupele on 5/31/2015. </p>
  syntax:
    content: public class StringUtils
