items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter
  id: _jmx_metric_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.JmxMetricPerformanceCounter(String,String,Collection<JmxAttributeData>)
  - com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.send(TelemetryClient,String,double)
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.yml
  langs:
  - java
  name: JmxMetricPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JmxMetricPerformanceCounter
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>A performance counter that sends <xref href="com.microsoft.applicationinsights.telemetry._metric_telemetry" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxMetricPerformanceCounter extends AbstractJmxPerformanceCounter
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.AbstractJmxPerformanceCounter(String,String,Collection<JmxAttributeData>)
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.getId()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.report(TelemetryClient)
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.JmxMetricPerformanceCounter(String,String,Collection<JmxAttributeData>)
  id: JmxMetricPerformanceCounter(String,String,Collection<JmxAttributeData>)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.yml
  langs:
  - java
  name: JmxMetricPerformanceCounter(String id, String objectName, Collection<JmxAttributeData> attributes)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JmxMetricPerformanceCounter.JmxMetricPerformanceCounter(String id, String objectName, Collection<JmxAttributeData> attributes)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public JmxMetricPerformanceCounter(String id, String objectName, Collection<JmxAttributeData> attributes)
    parameters:
    - id: id
      type: "26831127"
    - id: objectName
      type: "26831127"
    - id: attributes
      type: 12ebb11acom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.send(TelemetryClient,String,double)
  id: send(TelemetryClient,String,double)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_metric_performance_counter.yml
  langs:
  - java
  name: send(TelemetryClient telemetryClient, String displayName, double value)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.JmxMetricPerformanceCounter.send(TelemetryClient telemetryClient, String displayName, double value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: protected void send(TelemetryClient telemetryClient, String displayName, double value)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
    - id: displayName
      type: "26831127"
    - id: value
      type: a07dcde8
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 12ebb11acom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
  spec.java:
  - name: Collection<
    fullName: Collection<
  - uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
    name: JmxAttributeData
    fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
    href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  - name: '>'
    fullName: '>'
- uid: a07dcde8
  spec.java:
  - name: double
    fullName: double
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.AbstractJmxPerformanceCounter(String,String,Collection<JmxAttributeData>)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: AbstractJmxPerformanceCounter(String id, String objectName, Collection<JmxAttributeData> attributes)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter.AbstractJmxPerformanceCounter(String id, String objectName, Collection<JmxAttributeData> attributes)
  type: Constructor
  syntax:
    content: protected AbstractJmxPerformanceCounter(String id, String objectName, Collection<JmxAttributeData> attributes)
    parameters:
    - id: id
      type: "26831127"
    - id: objectName
      type: "26831127"
    - id: attributes
      type: 12ebb11acom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: synchronized void com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  summary: <p>The main method. The method will fetch the data and send it. The method will not do anything if there was a major problem accessing the needed counter. </p>
  syntax:
    content: public synchronized void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The telemetry client to send events. </p>
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: AbstractJmxPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter
  type: Class
  summary: >-
    <p>The class is a base class for JMX performance counters. It knows how to fetch the needed information from JMX and then relies on its derived classes to send the data.</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AbstractJmxPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry.yml
  name: MetricTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.MetricTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track metrics. </p>
  syntax:
    content: public class MetricTelemetry
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  name: JmxAttributeData
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
  type: Class
  summary: >-
    <p>Represents JMX data of an Attribute The display name The name of the attribute The type of the attribute</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxAttributeData
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
