items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._update_stages
  id: _update_stages
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._update_stages.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.UpdateStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.UpdateStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 185
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of application gateway HTTP listener update stages. </p>
  syntax:
    content: public interface UpdateStages
references: []
