items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._constants
  id: _constants
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker._constants.CONTEXT_FILE_PATTERN()
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._constants.yml
  langs:
  - java
  name: Constants
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.Constants
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/Constants.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/Constants.java
    startLine: 26
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  summary: <p>Created by yonisha on 8/2/2015. </p>
  syntax:
    content: public class Constants
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._constants.CONTEXT_FILE_PATTERN()
  id: CONTEXT_FILE_PATTERN()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._constants
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._constants.yml
  langs:
  - java
  name: CONTEXT_FILE_PATTERN
  fullName: final String com.microsoft.applicationinsights.extensibility.initializer.docker.Constants.CONTEXT_FILE_PATTERN
  type: Field
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/Constants.java
    startLine: 27
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: public static final String CONTEXT_FILE_PATTERN= "Docker host=%s,Docker image=%s,Docker container name=%s,Docker container id=%s"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
