items:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  id: _web_telemetry_initializer_base
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  children:
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.initialize(Telemetry)
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.onInitializeTelemetry(Telemetry)
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  langs:
  - java
  name: WebTelemetryInitializerBase
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebTelemetryInitializerBase.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebTelemetryInitializerBase.java
    startLine: 30
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class WebTelemetryInitializerBase implements TelemetryInitializer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_initializer
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.initialize(Telemetry)
  id: initialize(Telemetry)
  parent: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  langs:
  - java
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase.initialize(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebTelemetryInitializerBase.java
    startLine: 37
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  summary: <p>Initializes properties of the given telemetry. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_initializer.initialize(Telemetry)
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.onInitializeTelemetry(Telemetry)
  id: onInitializeTelemetry(Telemetry)
  parent: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  langs:
  - java
  name: onInitializeTelemetry(Telemetry telemetry)
  fullName: abstract void com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase.onInitializeTelemetry(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebTelemetryInitializerBase.java
    startLine: 51
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  summary: <p>Initializes the properties of the given telemetry. </p>
  syntax:
    content: protected abstract void onInitializeTelemetry(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
    return:
      type: 5beb11ad
references:
- uid: 5beb11ad
  spec.java:
  - name: abstract void
    fullName: abstract void
- uid: com.microsoft.applicationinsights.extensibility._telemetry_initializer
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_initializer.yml
  name: TelemetryInitializer
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryInitializer
  type: Interface
  summary: <p>Created by gupele on 12/30/2014. </p>
  syntax:
    content: public interface TelemetryInitializer
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_operation_id_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_operation_id_telemetry_initializer.yml
  name: WebOperationIdTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationIdTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class WebOperationIdTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_opec65b298f6d19b44fff0fd6008f6a1f75
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_opec65b298f6d19b44fff0fd6008f6a1f75.yml
  name: WebOperationNameTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationNameTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 2/17/2015. </p>
  syntax:
    content: public class WebOperationNameTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_session_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_session_telemetry_initializer.yml
  name: WebSessionTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebSessionTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 3/5/2015. </p>
  syntax:
    content: public class WebSessionTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_syn39c08b36af698d33adfd7054fe60983d.yml
  name: WebSyntheticRequestTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebSyntheticRequestTelemetryInitializer
  type: Class
  summary: <p>Created by gupele on 8/17/2015. </p>
  syntax:
    content: public class WebSyntheticRequestTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_agent_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_agent_telemetry_initializer.yml
  name: WebUserAgentTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebUserAgentTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 3/9/2015. </p>
  syntax:
    content: public class WebUserAgentTelemetryInitializer
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer.yml
  name: WebUserTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 3/5/2015. </p>
  syntax:
    content: public class WebUserTelemetryInitializer
- uid: com.springapp.mvc.extensions._web_request_run_id_telemetry_initializer
  parent: com.springapp.mvc.extensions
  href: com.springapp.mvc.extensions._web_request_run_id_telemetry_initializer.yml
  name: WebRequestRunIdTelemetryInitializer
  fullName: com.springapp.mvc.extensions.WebRequestRunIdTelemetryInitializer
  type: Class
  summary: <p>Created by yonisha on 6/21/2015. </p>
  syntax:
    content: public class WebRequestRunIdTelemetryInitializer extends WebTelemetryInitializerBase
- uid: com.microsoft.applicationinsights.extensibility._telemetry_initializer.initialize(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_initializer
  href: com.microsoft.applicationinsights.extensibility._telemetry_initializer.yml
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryInitializer.initialize(Telemetry telemetry)
  type: Method
  summary: <p>Initializes properties of the specified object. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
