items:
- uid: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
  id: _definiti4c458a21f70dc3da33496a7511bf042c
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.definePublicFrontend(String)
  - com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.withoutPublicFrontend()
  href: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithPublicFrontend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPublicFrontend
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 135
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to define one or more public, or Internet-facing, frontends. </p>
  syntax:
    content: public interface WithPublicFrontend extends ApplicationGateway.DefinitionStages.WithPublicIpAddress<WithPrivateFrontendOptional>
- uid: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.definePublicFrontend(String)
  id: definePublicFrontend(String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
  href: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.yml
  langs:
  - java
  name: definePublicFrontend(String name)
  fullName: ApplicationGatewayPublicFrontend.DefinitionStages.Blank<WithPrivateFrontendOptional> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPublicFrontend.definePublicFrontend(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 141
  package: com.microsoft.azure.management.network
  summary: <p>Begins the definition of a new public, or Internet-facing, frontend. </p>
  syntax:
    content: public ApplicationGatewayPublicFrontend.DefinitionStages.Blank<WithPrivateFrontendOptional> definePublicFrontend(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name for the frontend </p>
    return:
      type: 5fb0ce71com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62a08ddfce
      description: <p>the first stage of the new frontend definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.withoutPublicFrontend()
  id: withoutPublicFrontend()
  parent: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
  href: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.yml
  langs:
  - java
  name: withoutPublicFrontend()
  fullName: WithPrivateFrontend com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPublicFrontend.withoutPublicFrontend()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 148
  package: com.microsoft.azure.management.network
  summary: <p>Specifies that the application gateway should not be Internet-facing. </p>
  syntax:
    content: public WithPrivateFrontend withoutPublicFrontend()
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5
      description: <p>the next stage of the definition </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 5fb0ce71com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62a08ddfce
  spec.java:
  - name: ApplicationGatewayPublicFrontend.DefinitionStages.Blank<
    fullName: ApplicationGatewayPublicFrontend.DefinitionStages.Blank<
  - uid: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62
    name: ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional
    fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional
    href: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.network._application_gateway._definiti3ea6b7ec5fb4f9c02123fac24e8128a7
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti3ea6b7ec5fb4f9c02123fac24e8128a7.yml
  name: ApplicationGateway.DefinitionStages.WithPublicIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPublicIpAddress<ReturnT>
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add a public IP address as the default public frontend. </p>
  syntax:
    content: public interface WithPublicIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
- uid: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti750c1f4b453968d46a6ffd8fb8db1d62.yml
  name: ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional
  type: Interface
  summary: <p>The stage of an internal application gateway definition allowing to optionally define a private, or internal, frontend IP configuration. </p>
  syntax:
    content: public interface WithPrivateFrontendOptional extends ApplicationGateway.DefinitionStages.WithPrivateFrontend
- uid: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti4311f076afc807f2ec83b131b2d539c5.yml
  name: ApplicationGateway.DefinitionStages.WithPrivateFrontend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPrivateFrontend
  type: Interface
  summary: <p>The stage of an internal application gateway definition allowing to define a private frontend. </p>
  syntax:
    content: public interface WithPrivateFrontend
