items:
- uid: com.microsoft.azure.management.network._application_gateway_request_rout3d3026297b614f57e6531820fd64f7c0
  id: _application_gateway_request_rout3d3026297b614f57e6531820fd64f7c0
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_rout3d3026297b614f57e6531820fd64f7c0.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRule.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.DefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRule.java
    startLine: 31
  package: com.microsoft.azure.management.network
  summary: <p>The first stage of an application gateway request routing rule definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayRequestRoutingRule.DefinitionStages.WithListener<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway_request_rout34be5b32e72c42970b4422ca2ad82586.withListener(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._application_gateway_request_rout34be5b32e72c42970b4422ca2ad82586.withListener(String)
  parent: com.microsoft.azure.management.network._application_gateway_request_rout34be5b32e72c42970b4422ca2ad82586
  href: com.microsoft.azure.management.network._application_gateway_request_rout34be5b32e72c42970b4422ca2ad82586.yml
  name: withListener(String name)
  fullName: WithBackend<ParentT> com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.DefinitionStages.WithListener<ParentT>.withListener(String name)
  type: Method
  summary: <p>Associates the request routing rule with an existing HTTP listener on this application gateway. </p>
  syntax:
    content: public WithBackend<ParentT> withListener(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing listener </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_request_rout46473c5a2a0d347e9cbb0df00e6f420dda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_rout34be5b32e72c42970b4422ca2ad82586
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_rout34be5b32e72c42970b4422ca2ad82586.yml
  name: ApplicationGatewayRequestRoutingRule.DefinitionStages.WithListener<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.DefinitionStages.WithListener<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway request routing rule definition allowing to specify the listener to associate the routing rule with. </p>
  syntax:
    content: public interface WithListener<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule._definition.yml
  name: ApplicationGatewayRequestRoutingRule.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRule.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway request routing rule definition. </p>
  syntax:
    content: public interface Definition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
