items:
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  id: _telemetry_processor_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.getAdds()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.getType()
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.setAdds(ArrayList<ParamXmlElement>)
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.setType(String)
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  langs:
  - java
  name: TelemetryProcessorXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.getAdds()
  id: getAdds()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  langs:
  - java
  name: getAdds()
  fullName: ArrayList<ParamXmlElement> com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement.getAdds()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<ParamXmlElement> getAdds()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._param_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  langs:
  - java
  name: getType()
  fullName: String com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.setAdds(ArrayList<ParamXmlElement>)
  id: setAdds(ArrayList<ParamXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  langs:
  - java
  name: setAdds(ArrayList<ParamXmlElement> adds)
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement.setAdds(ArrayList<ParamXmlElement> adds)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setAdds(ArrayList<ParamXmlElement> adds)
    parameters:
    - id: adds
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._param_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
references:
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._param_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._param_xml_element
    name: ParamXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.ParamXmlElement
    href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  name: ParamXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ParamXmlElement
  type: Class
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class ParamXmlElement
