items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  id: exceptions
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  - com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/ExceptionMethodVisitor.java
    startLine: 21
  syntax:
    content: namespace exceptions
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.yml
  name: ExceptionMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.ExceptionMethodVisitor
  type: Class
  summary: <p>Created by gupele on 8/1/2016. </p>
  syntax:
    content: public class ExceptionMethodVisitor extends AdvancedAdviceAdapter
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._runtime_exception_provider.yml
  name: RuntimeExceptionProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.RuntimeExceptionProvider
  type: Class
  summary: <p>Created by gupele on 7/31/2016. </p>
  syntax:
    content: public class RuntimeExceptionProvider
