items:
- uid: com.microsoft.applicationinsights.extensibility._context_initializer
  id: _context_initializer
  parent: com.microsoft.applicationinsights.extensibility
  children:
  - com.microsoft.applicationinsights.extensibility._context_initializer.initialize(TelemetryContext)
  href: com.microsoft.applicationinsights.extensibility._context_initializer.yml
  langs:
  - java
  name: ContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.ContextInitializer
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/ContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/ContextInitializer.java
    startLine: 29
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Represents an object that implements supporting logic for TelemetryContext. <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public interface ContextInitializer
- uid: com.microsoft.applicationinsights.extensibility._context_initializer.initialize(TelemetryContext)
  id: initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility._context_initializer
  href: com.microsoft.applicationinsights.extensibility._context_initializer.yml
  langs:
  - java
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.extensibility.ContextInitializer.initialize(TelemetryContext context)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/ContextInitializer.java
    startLine: 35
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
references:
- uid: com.microsoft.applicationinsights.extensibility.initializer._device_info_context_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._device_info_context_initializer.yml
  name: DeviceInfoContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer
  type: Class
  summary: <p>Initializer class for device context information. </p>
  syntax:
    content: public class DeviceInfoContextInitializer
- uid: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.yml
  name: SdkVersionContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.SdkVersionContextInitializer
  type: Class
  summary: <p>Initializer for SDK version. </p>
  syntax:
    content: public class SdkVersionContextInitializer
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  parent: com.microsoft.applicationinsights.sample.plugins
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.yml
  name: GitBuildInfoContextInitializer
  fullName: com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer
  type: Class
  summary: '<p>An initializer to fetch Git data from a properties file Note: the file with its full package name should appear in the ''ApplicationInsights.xml'': <programlisting><codeline><highlight class="normal">&lt;ContextInitializers&gt;</highlight></codeline><codeline><highlight class="normal"><sp></sp><sp></sp>&lt;Add<sp></sp>type="com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer"<sp></sp>/&gt;</highlight></codeline><codeline><highlight class="normal">&lt;/ContextInitializers&gt;</highlight></codeline></programlisting></p>'
  syntax:
    content: public class GitBuildInfoContextInitializer
- uid: com.springapp.mvc._my_context_initializer
  parent: com.springapp.mvc
  href: com.springapp.mvc._my_context_initializer.yml
  name: MyContextInitializer
  fullName: com.springapp.mvc.MyContextInitializer
  type: Class
  syntax:
    content: public class MyContextInitializer
- uid: com.microsoft.applicationinsights.extensibility.initializer._device_info_context_initializer.initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility.initializer._device_info_context_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._device_info_context_initializer.yml
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
- uid: com.springapp.mvc._my_context_initializer.initialize(TelemetryContext)
  parent: com.springapp.mvc._my_context_initializer
  href: com.springapp.mvc._my_context_initializer.yml
  name: initialize(TelemetryContext context)
  fullName: void com.springapp.mvc.MyContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
- uid: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._sdk_version_context_initializer.yml
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SdkVersionContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.yml
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry_context.yml
  name: TelemetryContext
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContext
  type: Class
  summary: <p>Represents a context for sending telemetry to the Application Insights service. </p>
  syntax:
    content: public class TelemetryContext
