items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  id: _prepared_statement_meta_data
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.ctorSignatures()
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.fieldName()
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.PreparedStatementMetaData(Set<String>)
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.sqlStringInCtor()
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  langs:
  - java
  name: PreparedStatementMetaData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementMetaData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementMetaData.java
    startLine: 30
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementMetaData implements ClassToMethodTransformationData
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.ctorSignatures()
  id: ctorSignatures()
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  langs:
  - java
  name: ctorSignatures
  fullName: final Set<String> com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData.ctorSignatures
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementMetaData.java
    startLine: 32
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public final Set<String> ctorSignatures
    return:
      type: 04c36f7e
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.fieldName()
  id: fieldName()
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  langs:
  - java
  name: fieldName
  fullName: final String com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData.fieldName
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementMetaData.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public final String fieldName= SqlConstants.AI_SDK_SQL_STRING
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.PreparedStatementMetaData(Set<String>)
  id: PreparedStatementMetaData(Set<String>)
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  langs:
  - java
  name: PreparedStatementMetaData(Set<String> ctorSignatures)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData.PreparedStatementMetaData(Set<String> ctorSignatures)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementMetaData.java
    startLine: 35
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public PreparedStatementMetaData(Set<String> ctorSignatures)
    parameters:
    - id: ctorSignatures
      type: df32358c
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.sqlStringInCtor()
  id: sqlStringInCtor()
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  langs:
  - java
  name: sqlStringInCtor
  fullName: int com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData.sqlStringInCtor
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementMetaData.java
    startLine: 33
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public int sqlStringInCtor
    return:
      type: f75371fa
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: 04c36f7e
  spec.java:
  - name: final Set<String>
    fullName: final Set<String>
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: df32358c
  spec.java:
  - name: Set<String>
    fullName: Set<String>
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data.yml
  name: ClassToMethodTransformationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassToMethodTransformationData
  type: Interface
  summary: >-
    <p>A marker to allow Class Visitors to pass data to Method Visitors</p>

    <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface ClassToMethodTransformationData
