items:
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test
  id: _sequence_property_initializer_test
  parent: com.microsoft.applicationinsights.extensibility.initializer
  children:
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testDifferentTelemetries()
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryNotUpdatesAfterInitialization()
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryNotUpdatesAfterSet()
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryUpdatesAfterCtor()
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryUpdatesTwoTelemetries()
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.yml
  langs:
  - java
  name: SequencePropertyInitializerTest
  fullName: com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializerTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public class SequencePropertyInitializerTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testDifferentTelemetries()
  id: testDifferentTelemetries()
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.yml
  langs:
  - java
  name: testDifferentTelemetries()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializerTest.testDifferentTelemetries()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
    startLine: 133
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testDifferentTelemetries()
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryNotUpdatesAfterInitialization()
  id: testTelemetryNotUpdatesAfterInitialization()
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.yml
  langs:
  - java
  name: testTelemetryNotUpdatesAfterInitialization()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializerTest.testTelemetryNotUpdatesAfterInitialization()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
    startLine: 88
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testTelemetryNotUpdatesAfterInitialization()
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryNotUpdatesAfterSet()
  id: testTelemetryNotUpdatesAfterSet()
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.yml
  langs:
  - java
  name: testTelemetryNotUpdatesAfterSet()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializerTest.testTelemetryNotUpdatesAfterSet()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
    startLine: 101
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testTelemetryNotUpdatesAfterSet()
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryUpdatesAfterCtor()
  id: testTelemetryUpdatesAfterCtor()
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.yml
  langs:
  - java
  name: testTelemetryUpdatesAfterCtor()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializerTest.testTelemetryUpdatesAfterCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
    startLine: 73
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testTelemetryUpdatesAfterCtor()
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.testTelemetryUpdatesTwoTelemetries()
  id: testTelemetryUpdatesTwoTelemetries()
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer_test.yml
  langs:
  - java
  name: testTelemetryUpdatesTwoTelemetries()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializerTest.testTelemetryUpdatesTwoTelemetries()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializerTest.java
    startLine: 112
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testTelemetryUpdatesTwoTelemetries()
references: []
