items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  id: _jni_p_c_connector
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.addPerformanceCounter(String,String,String)
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.AI_BASE_FOLDER()
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.AI_NATIVE_FOLDER()
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.getValueOfPerformanceCounter(String)
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.initialize()
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.PROCESS_SELF_INSTANCE_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.translateInstanceName(String)
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: JniPCConnector
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>This class serves as the connection to the native code that does the work with Windows.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class JniPCConnector
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.addPerformanceCounter(String,String,String)
  id: addPerformanceCounter(String,String,String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: addPerformanceCounter(String category, String counter, String instance)
  fullName: static String com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.addPerformanceCounter(String category, String counter, String instance)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Adding a performance counter </p>
  syntax:
    content: public static String addPerformanceCounter(String category, String counter, String instance)
    parameters:
    - id: category
      type: "26831127"
      description: <p>The category must be non null non empty value. </p>
    - id: counter
      type: "26831127"
      description: <p>The counter must be non null non empty value. </p>
    - id: instance
      type: "26831127"
      description: <p>The instance. </p>
    return:
      type: "26831127"
      description: <p>True on success. </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.AI_BASE_FOLDER()
  id: AI_BASE_FOLDER()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: AI_BASE_FOLDER
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.AI_BASE_FOLDER
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String AI_BASE_FOLDER= "AISDK"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.AI_NATIVE_FOLDER()
  id: AI_NATIVE_FOLDER()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: AI_NATIVE_FOLDER
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.AI_NATIVE_FOLDER
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String AI_NATIVE_FOLDER= "native"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.getValueOfPerformanceCounter(String)
  id: getValueOfPerformanceCounter(String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: getValueOfPerformanceCounter(String name)
  fullName: static double com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.getValueOfPerformanceCounter(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 127
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>This method will delegate the call to the native code after the proper sanity checks. </p>
  syntax:
    content: public static double getValueOfPerformanceCounter(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>The logical name of the performance counter as was fetched during the 'addPerformanceCounter' call. </p>
    return:
      type: a07dcde8
      description: <p>The current value. </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.initialize()
  id: initialize()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: initialize()
  fullName: static boolean com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.initialize()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 69
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>This method must be called before any other method. All other methods are relevant only if this method was successful.</p>

    <p>Note that the method should not throw and should gracefully return the boolean value. </p>
  syntax:
    content: public static boolean initialize()
    return:
      type: 4fc6e284
      description: <p>True on success. </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.PROCESS_SELF_INSTANCE_NAME()
  id: PROCESS_SELF_INSTANCE_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: PROCESS_SELF_INSTANCE_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.PROCESS_SELF_INSTANCE_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_SELF_INSTANCE_NAME= "__SELF__"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.translateInstanceName(String)
  id: translateInstanceName(String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  langs:
  - java
  name: translateInstanceName(String instanceName)
  fullName: static String com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector.translateInstanceName(String instanceName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
    startLine: 110
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Process instance name is only known at runtime, therefore process level performance counters should use the 'PROCESS_SELF_INSTANCE_NAME' as the requested process name and then call this method to translate that logical name into the actual name that is fetched from the native code. </p>
  syntax:
    content: public static String translateInstanceName(String instanceName)
    parameters:
    - id: instanceName
      type: "26831127"
      description: <p>The raw instance name </p>
    return:
      type: "26831127"
      description: <p>The actual instance name. </p>
  exceptions:
  - type: 8a99d4b0
    description: <p>If instanceName equals PROCESS_SELF_INSTANCE_NAME but the actual instance name is unknown. </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 8a99d4b0
  spec.java:
  - name: Exception
    fullName: Exception
- uid: a07dcde8
  spec.java:
  - name: double
    fullName: double
