items:
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner
  id: _server_disaster_recovery_configuration_list_inner
  parent: com.microsoft.azure.management.sql.implementation
  children:
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.value()
  - com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.withValue(List< ServerDisasterRecoveryConfigurationInner >)
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.yml
  langs:
  - java
  name: ServerDisasterRecoveryConfigurationListInner
  fullName: com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationListInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationListInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationListInner.java
    startLine: 16
  package: com.microsoft.azure.management.sql.implementation
  summary: <p>Represents the response to a List <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Sql Server disaster recovery configuration request. </p>
  syntax: &o1
    content: public class ServerDisasterRecoveryConfigurationListInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.value()
  id: value()
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.yml
  langs:
  - java
  name: value()
  fullName: List<ServerDisasterRecoveryConfigurationInner> com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationListInner.value()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationListInner.java
    startLine: 28
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Get the value value.</p>

    <p></p>
  syntax:
    content: public List< ServerDisasterRecoveryConfigurationInner > value()
    return:
      type: f6a6204dcom.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner9ec3e006
      description: <p>the value value </p>
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.withValue(List< ServerDisasterRecoveryConfigurationInner >)
  id: withValue(List< ServerDisasterRecoveryConfigurationInner >)
  parent: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.yml
  langs:
  - java
  name: withValue(List< ServerDisasterRecoveryConfigurationInner > value)
  fullName: ServerDisasterRecoveryConfigurationListInner com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationListInner.withValue(List< ServerDisasterRecoveryConfigurationInner > value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ServerDisasterRecoveryConfigurationListInner.java
    startLine: 38
  package: com.microsoft.azure.management.sql.implementation
  summary: >-
    <p>Set the value value.</p>

    <p></p>
  syntax:
    content: public ServerDisasterRecoveryConfigurationListInner withValue(List< ServerDisasterRecoveryConfigurationInner > value)
    parameters:
    - id: value
      type: f6a6204dcom.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner9ec3e006
      description: <p>the value value to set </p>
    return:
      type: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner
      description: <p>the <xref href="com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
    name: ServerDisasterRecoveryConfigurationInner
    fullName: com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner
    href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  - name: " >"
    fullName: " >"
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner
  parent: com.microsoft.azure.management.sql.implementation
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_inner.yml
  name: ServerDisasterRecoveryConfigurationInner
  fullName: com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationInner
  type: Class
  summary: <p>Represents a server disaster recovery configuration. </p>
  syntax:
    content: public class ServerDisasterRecoveryConfigurationInner
- uid: com.microsoft.azure.management._azure
  parent: com.microsoft.azure.management
  href: com.microsoft.azure.management._azure.yml
  name: Azure
  fullName: com.microsoft.azure.management.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner
  parent: com.microsoft.azure.management.sql.implementation
  href: com.microsoft.azure.management.sql.implementation._server_disaster_recovery_configuration_list_inner.yml
  name: ServerDisasterRecoveryConfigurationListInner
  fullName: com.microsoft.azure.management.sql.implementation.ServerDisasterRecoveryConfigurationListInner
  type: Class
  summary: <p>Represents the response to a List <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> Sql Server disaster recovery configuration request. </p>
  syntax: *o1
