items:
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  id: _class_data_utils_test
  parent: com.microsoft.applicationinsights.internal.reflect
  children:
  - com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testClassDoesNotExist()
  - com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testClassExists()
  - com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testMethodExistingPublicMethod()
  - com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testMethodNotExistingPublicMethod()
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.yml
  langs:
  - java
  name: ClassDataUtilsTest
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataUtilsTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtilsTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtilsTest.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public class ClassDataUtilsTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testClassDoesNotExist()
  id: testClassDoesNotExist()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.yml
  langs:
  - java
  name: testClassDoesNotExist()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataUtilsTest.testClassDoesNotExist()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtilsTest.java
    startLine: 55
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testClassDoesNotExist()
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testClassExists()
  id: testClassExists()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.yml
  langs:
  - java
  name: testClassExists()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataUtilsTest.testClassExists()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtilsTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testClassExists()
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testMethodExistingPublicMethod()
  id: testMethodExistingPublicMethod()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.yml
  langs:
  - java
  name: testMethodExistingPublicMethod()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataUtilsTest.testMethodExistingPublicMethod()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtilsTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testMethodExistingPublicMethod()
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.testMethodNotExistingPublicMethod()
  id: testMethodNotExistingPublicMethod()
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.yml
  langs:
  - java
  name: testMethodNotExistingPublicMethod()
  fullName: void com.microsoft.applicationinsights.internal.reflect.ClassDataUtilsTest.testMethodNotExistingPublicMethod()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtilsTest.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public void testMethodNotExistingPublicMethod()
references: []
