items:
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test
  id: _active_transmission_network_output_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testBufferIsFull()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testSendOneTransmission()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testSendTenTransmission()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testSendTwoTransmission()
  - com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testStop()
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.yml
  langs:
  - java
  name: ActiveTransmissionNetworkOutputTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutputTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class ActiveTransmissionNetworkOutputTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testBufferIsFull()
  id: testBufferIsFull()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.yml
  langs:
  - java
  name: testBufferIsFull()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutputTest.testBufferIsFull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testBufferIsFull()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testSendOneTransmission()
  id: testSendOneTransmission()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.yml
  langs:
  - java
  name: testSendOneTransmission()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutputTest.testSendOneTransmission()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSendOneTransmission()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testSendTenTransmission()
  id: testSendTenTransmission()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.yml
  langs:
  - java
  name: testSendTenTransmission()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutputTest.testSendTenTransmission()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSendTenTransmission()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testSendTwoTransmission()
  id: testSendTwoTransmission()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.yml
  langs:
  - java
  name: testSendTwoTransmission()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutputTest.testSendTwoTransmission()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSendTwoTransmission()
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.testStop()
  id: testStop()
  parent: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output_test.yml
  langs:
  - java
  name: testStop()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutputTest.testStop()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutputTest.java
    startLine: 150
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStop()
references:
- uid: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._active_transmission_network_output.yml
  name: ActiveTransmissionNetworkOutput
  fullName: com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput
  type: Class
  summary: <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class ActiveTransmissionNetworkOutput implements TransmissionOutput
