items:
- uid: com.springapp.mvc._application_insights
  id: _application_insights
  parent: com.springapp.mvc
  children:
  - com.springapp.mvc._application_insights.getTelemetryClient()
  href: com.springapp.mvc._application_insights.yml
  langs:
  - java
  name: ApplicationInsights
  fullName: com.springapp.mvc.ApplicationInsights
  type: Enum
  source:
    remote: &o0
      path: test/webapps/bookstore-spring/src/main/java/com/springapp/mvc/ApplicationInsights.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: test/webapps/bookstore-spring/src/main/java/com/springapp/mvc/ApplicationInsights.java
    startLine: 4
  package: com.springapp.mvc
  syntax:
    content: public enum ApplicationInsights
  inheritance:
  - java.lang.Object
  - java.lang.Enum<ApplicationInsights>
  inheritedMembers:
  - com.springapp.mvc._application_insights_1acd2c120bf1adce013996be6c9c626358
- uid: com.springapp.mvc._application_insights.getTelemetryClient()
  id: getTelemetryClient()
  parent: com.springapp.mvc._application_insights
  href: com.springapp.mvc._application_insights.yml
  langs:
  - java
  name: getTelemetryClient()
  fullName: TelemetryClient com.springapp.mvc.ApplicationInsights.getTelemetryClient()
  type: Method
  source:
    remote: *o0
    path: test/webapps/bookstore-spring/src/main/java/com/springapp/mvc/ApplicationInsights.java
    startLine: 10
  package: com.springapp.mvc
  syntax:
    content: public TelemetryClient getTelemetryClient()
    return:
      type: com.microsoft.applicationinsights._telemetry_client
references:
- uid: com.springapp.mvc._application_insights_1acd2c120bf1adce013996be6c9c626358
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
