items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  id: _transmission_policy_state_fetcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.getCurrentState()
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
  langs:
  - java
  name: TransmissionPolicyStateFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateFetcher.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateFetcher.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public interface TransmissionPolicyStateFetcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.getCurrentState()
  id: getCurrentState()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
  langs:
  - java
  name: getCurrentState()
  fullName: TransmissionPolicy com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher.getCurrentState()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateFetcher.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public TransmissionPolicy getCurrentState()
    return:
      type: defdcfa6
references:
- uid: defdcfa6
  spec.java:
  - name: TransmissionPolicy
    fullName: TransmissionPolicy
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state
