items:
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module
  id: _telemetry_module
  parent: com.microsoft.applicationinsights.extensibility
  children:
  - com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  langs:
  - java
  name: TelemetryModule
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryModule
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java
    startLine: 28
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface TelemetryModule
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  id: initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_module
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  langs:
  - java
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java
    startLine: 34
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Initializes the telemetry module. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
references:
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  name: MockTelemetryModule
  fullName: com.microsoft.applicationinsights.internal.config.MockTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class MockTelemetryModule implements TelemetryModule
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_f3ddd60991bc37760f0025adbba6a6b8e
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule
  type: Class
  summary: >-
    <p>A base class for performance modules.</p>

    <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class AbstractPerformanceCounterModule implements TelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.yml
  name: WebRequestTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class WebRequestTrackingTelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  name: WebSessionTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax:
    content: public class WebSessionTrackingTelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.yml
  name: WebUserTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule
  type: Class
  summary: <p>Created by yonisha on 2/7/2015. </p>
  syntax:
    content: public class WebUserTrackingTelemetryModule
- uid: com.springapp.mvc.extensions._web_request_run_id_telemetry_module
  parent: com.springapp.mvc.extensions
  href: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.yml
  name: WebRequestRunIdTelemetryModule
  fullName: com.springapp.mvc.extensions.WebRequestRunIdTelemetryModule
  type: Class
  summary: >-
    <p>Created by yonisha on 6/21/2015.</p>

    <p>This module reads teh 'runid' query parameter, if exists, from the incoming http request and adds it as a property to the RequestTelemetry sent to AI. This run ID is then used to identify requests sent as part of a test suite. </p>
  syntax:
    content: public class WebRequestRunIdTelemetryModule
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_user_tracking_telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: >-
    <p>Initializes the telemetry module.</p>

    <p></p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.initialize(TelemetryConfiguration)
  parent: com.springapp.mvc.extensions._web_request_run_id_telemetry_module
  href: com.springapp.mvc.extensions._web_request_run_id_telemetry_module.yml
  name: initialize(TelemetryConfiguration telemetryConfiguration)
  fullName: void com.springapp.mvc.extensions.WebRequestRunIdTelemetryModule.initialize(TelemetryConfiguration telemetryConfiguration)
  type: Method
  summary: <p>Initializes the telemetry module. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration telemetryConfiguration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>The main method will use the factory to fetch the performance counters and register them for work. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: >-
    <p>Initializes the telemetry module.</p>

    <p></p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.config._mock_telemetry_module
  href: com.microsoft.applicationinsights.internal.config._mock_telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.config.MockTelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: >-
    <p>Initializes the telemetry module.</p>

    <p></p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_request_tracking_telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>Initializes the telemetry module with the given telemetry configuration. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The telemetry configuration. </p>
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
