items:
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  id: _internal_logger_test
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test.prepare()
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test.testInitializeTwice()
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test.testLogAlwaysWithLoggerLevelOff()
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test.testNoLoggerLevelData()
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test.testWrongLoggerLevelName()
  - com.microsoft.applicationinsights.internal.logger._internal_logger_test.testWrongLoggerOutputName()
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: InternalLoggerTest
  fullName: com.microsoft.applicationinsights.internal.logger.InternalLoggerTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public class InternalLoggerTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test.prepare()
  id: prepare()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: prepare()
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLoggerTest.prepare()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void prepare()
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test.testInitializeTwice()
  id: testInitializeTwice()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: testInitializeTwice()
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLoggerTest.testInitializeTwice()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testInitializeTwice()
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test.testLogAlwaysWithLoggerLevelOff()
  id: testLogAlwaysWithLoggerLevelOff()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: testLogAlwaysWithLoggerLevelOff()
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLoggerTest.testLogAlwaysWithLoggerLevelOff()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 92
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testLogAlwaysWithLoggerLevelOff()
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test.testNoLoggerLevelData()
  id: testNoLoggerLevelData()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: testNoLoggerLevelData()
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLoggerTest.testNoLoggerLevelData()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 53
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testNoLoggerLevelData()
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test.testWrongLoggerLevelName()
  id: testWrongLoggerLevelName()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: testWrongLoggerLevelName()
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLoggerTest.testWrongLoggerLevelName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 61
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testWrongLoggerLevelName()
- uid: com.microsoft.applicationinsights.internal.logger._internal_logger_test.testWrongLoggerOutputName()
  id: testWrongLoggerOutputName()
  parent: com.microsoft.applicationinsights.internal.logger._internal_logger_test
  href: com.microsoft.applicationinsights.internal.logger._internal_logger_test.yml
  langs:
  - java
  name: testWrongLoggerOutputName()
  fullName: void com.microsoft.applicationinsights.internal.logger.InternalLoggerTest.testWrongLoggerOutputName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testWrongLoggerOutputName()
references: []
