items:
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  id: _telemetry_buffer
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.add(String)
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.flush()
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.getMaxTelemetriesInBatch()
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.getTransmitBufferTimeoutInSeconds()
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.setMaxTelemetriesInBatch(int)
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.setTransmitBufferTimeoutInSeconds(int)
  - com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.TelemetryBuffer(TelemetriesTransmitter,LimitsEnforcer,LimitsEnforcer)
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: TelemetryBuffer
  fullName: com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The class is responsible for getting instances of <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref></p>

    <p>It is responsible for managing the buffers. Once a new buffer is created it will schedule a call to pick up the buffer.</p>

    <p>If the buffer is full before the timeout expired, it will initiate a 'send now' activity to send the buffer asap.</p>

    <p>The class is responsible for handing the corner cases that might rise</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class TelemetryBuffer
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.add(String)
  id: add(String)
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: add(String telemetry)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.add(String telemetry)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 176
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The method will add the incoming <ref refid="" kindref="compound">Telemetry</ref> to its internal container of Telemetries</p>

    <p>If that is the first instance in the container, we schedule a 'pick-up' in a configurable amount of time If by adding that item we exceeded the maximum number of instances, we trigger a send request now.</p>

    <p>Note that a lock is used to make sure we avoid race conditions and to make sure that we cleanly move from a ready to send buffer to a new one </p>
  syntax:
    content: public void add(String telemetry)
    parameters:
    - id: telemetry
      type: "26831127"
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to add to the buffer. </p>
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.flush()
  id: flush()
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: flush()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.flush()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 205
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>The method will flush the telemetries currently in the buffer to the <xref href="com.microsoft.applicationinsights.internal.channel._telemetries_transmitter" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public void flush()
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.getMaxTelemetriesInBatch()
  id: getMaxTelemetriesInBatch()
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: getMaxTelemetriesInBatch()
  fullName: int com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.getMaxTelemetriesInBatch()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 139
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Gets the maximum number of telemetries in a batch </p>
  syntax:
    content: public int getMaxTelemetriesInBatch()
    return:
      type: f75371fa
      description: <p>The maximum number of telemetries in a batch </p>
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.getTransmitBufferTimeoutInSeconds()
  id: getTransmitBufferTimeoutInSeconds()
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: getTransmitBufferTimeoutInSeconds()
  fullName: int com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.getTransmitBufferTimeoutInSeconds()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 162
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Gets the transmit buffer timeout in seconds </p>
  syntax:
    content: public int getTransmitBufferTimeoutInSeconds()
    return:
      type: f75371fa
      description: <p>The transmit buffer timeout in seconds </p>
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.setMaxTelemetriesInBatch(int)
  id: setMaxTelemetriesInBatch(int)
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: setMaxTelemetriesInBatch(int value)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.setMaxTelemetriesInBatch(int value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 125
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Sets the maximum number of telemetries in a batch </p>
  syntax:
    content: public void setMaxTelemetriesInBatch(int value)
    parameters:
    - id: value
      type: f75371fa
      description: <p>The max amount of Telemetries that are allowed in a batch. </p>
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.setTransmitBufferTimeoutInSeconds(int)
  id: setTransmitBufferTimeoutInSeconds(int)
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: setTransmitBufferTimeoutInSeconds(int value)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.setTransmitBufferTimeoutInSeconds(int value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 147
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>Sets the transmit buffer timeout in seconds </p>
  syntax:
    content: public void setTransmitBufferTimeoutInSeconds(int value)
    parameters:
    - id: value
      type: f75371fa
      description: <p>The amount of time to wait before sending the buffer. </p>
- uid: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.TelemetryBuffer(TelemetriesTransmitter,LimitsEnforcer,LimitsEnforcer)
  id: TelemetryBuffer(TelemetriesTransmitter,LimitsEnforcer,LimitsEnforcer)
  parent: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer
  href: com.microsoft.applicationinsights.internal.channel.common._telemetry_buffer.yml
  langs:
  - java
  name: TelemetryBuffer(TelemetriesTransmitter sender, LimitsEnforcer maxTelemetriesInBatchEnforcer, LimitsEnforcer transmitBufferTimeoutInSecondsEnforcer)
  fullName: com.microsoft.applicationinsights.internal.channel.common.TelemetryBuffer.TelemetryBuffer(TelemetriesTransmitter sender, LimitsEnforcer maxTelemetriesInBatchEnforcer, LimitsEnforcer transmitBufferTimeoutInSecondsEnforcer)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TelemetryBuffer.java
    startLine: 105
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: <p>The constructor needs to get the 'sender' we work with </p>
  syntax:
    content: public TelemetryBuffer(TelemetriesTransmitter sender, LimitsEnforcer maxTelemetriesInBatchEnforcer, LimitsEnforcer transmitBufferTimeoutInSecondsEnforcer)
    parameters:
    - id: sender
      type: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
      description: <p>The sender object for transmitting the telemetries </p>
    - id: maxTelemetriesInBatchEnforcer
      type: com.microsoft.applicationinsights.internal.util._limits_enforcer
      description: <p>For getting the number of maximum number of telemetries in a batch within limits </p>
    - id: transmitBufferTimeoutInSecondsEnforcer
      type: com.microsoft.applicationinsights.internal.util._limits_enforcer
      description: <p>For getting the number of transmit buffer timeout in seconds within limits </p>
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.yml
  name: TelemetriesTransmitter
  fullName: com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter
  type: Interface
  summary: >-
    <p>The class is responsible for getting containers of <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>, transform them into <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and then initiate the sending process.</p>

    <p>Containers of Telemetry instances are populated by application threads. This class use the 'channel's' threads for the rest of the process. In other words, the de-coupling of user and channel threads happens here.</p>

    <p>The class lets its users to schedule a 'send', where a channel thread will be sent to 'pick up' the container of Telemetries. Or, it also lets the caller to initiate a 'send now' call where the caller passes the container and this class will continue, again, using a channel thread while releasing the calling thread.</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public interface TelemetriesTransmitter
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  name: LimitsEnforcer
  fullName: com.microsoft.applicationinsights.internal.util.LimitsEnforcer
  type: Class
  summary: <p>Created by gupele on 5/10/2015. </p>
  syntax:
    content: public class LimitsEnforcer
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
