items:
- uid: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test
  id: _metric_telemetry_filter_test
  parent: com.microsoft.applicationinsights.internal.processor
  children:
  - com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.testNeededTelemetry()
  - com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.testNonMetricTelemetry()
  - com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.testNotNeededTelemetry()
  href: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.yml
  langs:
  - java
  name: MetricTelemetryFilterTest
  fullName: com.microsoft.applicationinsights.internal.processor.MetricTelemetryFilterTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilterTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilterTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.processor
  summary: <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class MetricTelemetryFilterTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.testNeededTelemetry()
  id: testNeededTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.yml
  langs:
  - java
  name: testNeededTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.MetricTelemetryFilterTest.testNeededTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilterTest.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNeededTelemetry()
- uid: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.testNonMetricTelemetry()
  id: testNonMetricTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.yml
  langs:
  - java
  name: testNonMetricTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.MetricTelemetryFilterTest.testNonMetricTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilterTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNonMetricTelemetry()
- uid: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.testNotNeededTelemetry()
  id: testNotNeededTelemetry()
  parent: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test
  href: com.microsoft.applicationinsights.internal.processor._metric_telemetry_filter_test.yml
  langs:
  - java
  name: testNotNeededTelemetry()
  fullName: void com.microsoft.applicationinsights.internal.processor.MetricTelemetryFilterTest.testNotNeededTelemetry()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilterTest.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.processor
  syntax:
    content: public void testNotNeededTelemetry()
references: []
