items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  id: _jvm_performance_counters_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.addConfigurationData(PerformanceCountersXmlElement)
  - com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.JvmPerformanceCountersModule()
  - com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.JvmPerformanceCountersModule(PerformanceCountersFactory)
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  langs:
  - java
  name: JvmPerformanceCountersModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersModule.java
    startLine: 76
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>The class loads the relevant Jvm PCs</p>

    <p>By default the class will create all the JVM PC</p>

    <p>The class will not be activated if the enclosing XML tag will have the 'UseBuiltIn' tag set to false:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;UseBuiltIn&gt;false&lt;/UseBuiltIn&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>All Jvm PCs can be disabled like this, without disabling the other built in performance counters:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline></codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Jvm<sp></sp>enabled="false"/&gt;</highlight>

          </codeline>

          <codeline></codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>A specific Jvm counter can be disabled like this:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Jvm&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;JvmPC<sp></sp>name="ThreadDeadLockDetector"<sp></sp>enabled="false"/&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;/Jvm&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class JvmPerformanceCountersModule extends AbstractPerformanceCounterModule implements PerformanceCounterConfigurationAware
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_module
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.addConfigurationData(PerformanceCountersXmlElement)
  id: addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  langs:
  - java
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersModule.java
    startLine: 97
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.addConfigurationData(PerformanceCountersXmlElement)
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.JvmPerformanceCountersModule()
  id: JvmPerformanceCountersModule()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  langs:
  - java
  name: JvmPerformanceCountersModule()
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule.JvmPerformanceCountersModule()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersModule.java
    startLine: 84
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public JvmPerformanceCountersModule()
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.JvmPerformanceCountersModule(PerformanceCountersFactory)
  id: JvmPerformanceCountersModule(PerformanceCountersFactory)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  langs:
  - java
  name: JvmPerformanceCountersModule(PerformanceCountersFactory factory)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule.JvmPerformanceCountersModule(PerformanceCountersFactory factory)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersModule.java
    startLine: 88
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public JvmPerformanceCountersModule(PerformanceCountersFactory factory)
    parameters:
    - id: factory
      type: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
references:
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  type: Constructor
  syntax:
    content: protected AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
    parameters:
    - id: factory
      type: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: factory
  fullName: final PerformanceCountersFactory com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.factory
  type: Field
  syntax:
    content: protected final PerformanceCountersFactory factory
    return:
      type: 93de0ef9com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>The main method will use the factory to fetch the performance counters and register them for work. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule
  type: Class
  summary: >-
    <p>A base class for performance modules.</p>

    <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class AbstractPerformanceCounterModule implements TelemetryModule
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.yml
  name: PerformanceCounterConfigurationAware
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterConfigurationAware
  type: Interface
  summary: >-
    <p>This class should by performance modules who wish to work with the configuration data.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public interface PerformanceCounterConfigurationAware
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory.yml
  name: PerformanceCountersFactory
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCountersFactory
  type: Interface
  summary: >-
    <p>Defines the interface that concrete factories should follow. The major method is the one that will be able create the needed Performance Counters.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface PerformanceCountersFactory
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.yml
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterConfigurationAware.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  name: PerformanceCountersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class PerformanceCountersXmlElement
