items:
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils
  id: _date_time_utils
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._date_time_utils.addToDate(Date,int,int)
  - com.microsoft.applicationinsights.internal.util._date_time_utils.formatAsRoundTripDate(Date)
  - com.microsoft.applicationinsights.internal.util._date_time_utils.getDateDiff(Date,Date,TimeUnit)
  - com.microsoft.applicationinsights.internal.util._date_time_utils.getDateTimeNow()
  - com.microsoft.applicationinsights.internal.util._date_time_utils.parseRoundTripDateString(String)
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  langs:
  - java
  name: DateTimeUtils
  fullName: com.microsoft.applicationinsights.internal.util.DateTimeUtils
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by yonisha on 2/5/2015. </p>
  syntax:
    content: public class DateTimeUtils
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils.addToDate(Date,int,int)
  id: addToDate(Date,int,int)
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  langs:
  - java
  name: addToDate(Date date, int field, int amount)
  fullName: static Date com.microsoft.applicationinsights.internal.util.DateTimeUtils.addToDate(Date date, int field, int amount)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static Date addToDate(Date date, int field, int amount)
    parameters:
    - id: date
      type: "12977444"
    - id: field
      type: f75371fa
    - id: amount
      type: f75371fa
    return:
      type: "12977444"
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils.formatAsRoundTripDate(Date)
  id: formatAsRoundTripDate(Date)
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  langs:
  - java
  name: formatAsRoundTripDate(Date date)
  fullName: static String com.microsoft.applicationinsights.internal.util.DateTimeUtils.formatAsRoundTripDate(Date date)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Formats the given date as round-trip date string </p>
  syntax:
    content: public static String formatAsRoundTripDate(Date date)
    parameters:
    - id: date
      type: "12977444"
      description: <p>Round-trip date string </p>
    return:
      type: "26831127"
      description: <p>Round-trip date string </p>
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils.getDateDiff(Date,Date,TimeUnit)
  id: getDateDiff(Date,Date,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  langs:
  - java
  name: getDateDiff(Date laterDate, Date date, TimeUnit timeUnit)
  fullName: static long com.microsoft.applicationinsights.internal.util.DateTimeUtils.getDateDiff(Date laterDate, Date date, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static long getDateDiff(Date laterDate, Date date, TimeUnit timeUnit)
    parameters:
    - id: laterDate
      type: "12977444"
    - id: date
      type: "12977444"
    - id: timeUnit
      type: 02b8628b
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils.getDateTimeNow()
  id: getDateTimeNow()
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  langs:
  - java
  name: getDateTimeNow()
  fullName: static Date com.microsoft.applicationinsights.internal.util.DateTimeUtils.getDateTimeNow()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static Date getDateTimeNow()
    return:
      type: "12977444"
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils.parseRoundTripDateString(String)
  id: parseRoundTripDateString(String)
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  langs:
  - java
  name: parseRoundTripDateString(String roundTripString)
  fullName: static Date com.microsoft.applicationinsights.internal.util.DateTimeUtils.parseRoundTripDateString(String roundTripString)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DateTimeUtils.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Parses the given round-trip date string (e.g. '2015-05-26T07') into Date object. </p>
  syntax:
    content: public static Date parseRoundTripDateString(String roundTripString)
    parameters:
    - id: roundTripString
      type: "26831127"
      description: <p>The string to parse. </p>
    return:
      type: "12977444"
      description: <p>Date represents the string. </p>
  exceptions:
  - type: eb479292
    description: <p>Thrown when failed to parse the given string. </p>
references:
- uid: "12977444"
  spec.java:
  - name: Date
    fullName: Date
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: eb479292
  spec.java:
  - name: java.text.ParseException
    fullName: java.text.ParseException
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
