items:
- uid: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder
  id: _self_core_registration_mode_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder.create(AgentConfigurationDefaultImpl,Element)
  href: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder.yml
  langs:
  - java
  name: SelfCoreRegistrationModeBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.SelfCoreRegistrationModeBuilder
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/SelfCoreRegistrationModeBuilder.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/SelfCoreRegistrationModeBuilder.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Created by gupele on 9/11/2016. </p>
  syntax:
    content: public class SelfCoreRegistrationModeBuilder
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder.create(AgentConfigurationDefaultImpl,Element)
  id: create(AgentConfigurationDefaultImpl,Element)
  parent: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder
  href: com.microsoft.applicationinsights.agent.internal.config._self_core_registration_mode_builder.yml
  langs:
  - java
  name: create(AgentConfigurationDefaultImpl agentConfiguration, Element enclosingTag)
  fullName: void com.microsoft.applicationinsights.agent.internal.config.SelfCoreRegistrationModeBuilder.create(AgentConfigurationDefaultImpl agentConfiguration, Element enclosingTag)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/SelfCoreRegistrationModeBuilder.java
    startLine: 33
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public void create(AgentConfigurationDefaultImpl agentConfiguration, Element enclosingTag)
    parameters:
    - id: agentConfiguration
      type: 2dbf7c20
    - id: enclosingTag
      type: 47fe1a23
references:
- uid: 2dbf7c20
  spec.java:
  - name: AgentConfigurationDefaultImpl
    fullName: AgentConfigurationDefaultImpl
- uid: 47fe1a23
  spec.java:
  - name: Element
    fullName: Element
