items:
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry_test
  id: _event_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._event_telemetry_test.testDefaultCtor()
  - com.microsoft.applicationinsights.telemetry._event_telemetry_test.testSanitize()
  - com.microsoft.applicationinsights.telemetry._event_telemetry_test.testSetName()
  - com.microsoft.applicationinsights.telemetry._event_telemetry_test.testSetTimestamp()
  href: com.microsoft.applicationinsights.telemetry._event_telemetry_test.yml
  langs:
  - java
  name: EventTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/EventTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/EventTelemetryTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class EventTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry_test.testDefaultCtor()
  id: testDefaultCtor()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._event_telemetry_test.yml
  langs:
  - java
  name: testDefaultCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetryTest.testDefaultCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/EventTelemetryTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testDefaultCtor()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry_test.testSanitize()
  id: testSanitize()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._event_telemetry_test.yml
  langs:
  - java
  name: testSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetryTest.testSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/EventTelemetryTest.java
    startLine: 55
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSanitize()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry_test.testSetName()
  id: testSetName()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._event_telemetry_test.yml
  langs:
  - java
  name: testSetName()
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetryTest.testSetName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/EventTelemetryTest.java
    startLine: 38
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetName()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry_test.testSetTimestamp()
  id: testSetTimestamp()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._event_telemetry_test.yml
  langs:
  - java
  name: testSetTimestamp()
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetryTest.testSetTimestamp()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/EventTelemetryTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetTimestamp()
references: []
