items:
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output
  id: _file_logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._file_logger_output.close()
  - com.microsoft.applicationinsights.internal.logger._file_logger_output.FileLoggerOutput(Map<String, String>)
  - com.microsoft.applicationinsights.internal.logger._file_logger_output.log(String)
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output.yml
  langs:
  - java
  name: FileLoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutput
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.logger
  summary: >-
    <p>The class is responsible for write log messages into log files. The class will write to a file until the file max size is reached.</p>

    <p>When that happens it will create close that file and open a new file.</p>

    <p>When the maximum amount of log files is reached, the oldest one will be deleted.</p>

    <p>The class does a 'best effort' to work with files, if there is a problem, the class will try to write into a <xref href="com.microsoft.applicationinsights.internal.logger._console_logger_output" data-throw-if-not-resolved="false"></xref> but will not fail the process under any scenario. </p>
  syntax:
    content: public class FileLoggerOutput implements LoggerOutput
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.logger._logger_output
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.logger._file_logger_output.setLogProxyFactory(LogFileProxyFactory)
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output.close()
  id: close()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output.yml
  langs:
  - java
  name: close()
  fullName: void com.microsoft.applicationinsights.internal.logger.FileLoggerOutput.close()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java
    startLine: 163
  package: com.microsoft.applicationinsights.internal.logger
  summary: <p>After this method is called the instance should not be called again for logging messages </p>
  syntax:
    content: public void close()
  overridden: com.microsoft.applicationinsights.internal.logger._logger_output.close()
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output.FileLoggerOutput(Map<String, String>)
  id: FileLoggerOutput(Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output.yml
  langs:
  - java
  name: FileLoggerOutput(Map<String, String> loggerData)
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutput.FileLoggerOutput(Map<String, String> loggerData)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java
    startLine: 86
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public FileLoggerOutput(Map<String, String> loggerData)
    parameters:
    - id: loggerData
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output.log(String)
  id: log(String)
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output.yml
  langs:
  - java
  name: log(String message)
  fullName: synchronized void com.microsoft.applicationinsights.internal.logger.FileLoggerOutput.log(String message)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java
    startLine: 148
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public synchronized void log(String message)
    parameters:
    - id: message
      type: "26831127"
    return:
      type: 5c0b90ca
  overridden: com.microsoft.applicationinsights.internal.logger._logger_output.log(String)
references:
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 5c0b90ca
  spec.java:
  - name: synchronized void
    fullName: synchronized void
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output.setLogProxyFactory(LogFileProxyFactory)
- uid: com.microsoft.applicationinsights.internal.logger._logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._logger_output.yml
  name: LoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.LoggerOutput
  type: Interface
  summary: <p>Created by gupele on 1/14/2015. </p>
  syntax:
    content: public interface LoggerOutput
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy.yml
  name: LogFileProxy
  fullName: com.microsoft.applicationinsights.internal.logger.LogFileProxy
  type: Interface
  summary: <p>Created by gupele on 2/1/2015. </p>
  syntax:
    content: public interface LogFileProxy
- uid: com.microsoft.applicationinsights.internal.logger._log_file_proxy_factory
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._log_file_proxy_factory.yml
  name: LogFileProxyFactory
  fullName: com.microsoft.applicationinsights.internal.logger.LogFileProxyFactory
  type: Interface
  summary: <p>Created by gupele on 2/1/2015. </p>
  syntax:
    content: public interface LogFileProxyFactory
- uid: com.microsoft.applicationinsights.internal.logger._console_logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._console_logger_output.yml
  name: ConsoleLoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.ConsoleLoggerOutput
  type: Class
  summary: <p>Created by gupele on 1/14/2015. </p>
  syntax:
    content: public class ConsoleLoggerOutput implements LoggerOutput
- uid: com.microsoft.applicationinsights.internal.logger._logger_output.log(String)
  parent: com.microsoft.applicationinsights.internal.logger._logger_output
  href: com.microsoft.applicationinsights.internal.logger._logger_output.yml
  name: log(String message)
  fullName: void com.microsoft.applicationinsights.internal.logger.LoggerOutput.log(String message)
  type: Method
  syntax:
    content: public void log(String message)
    parameters:
    - id: message
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.logger._logger_output.close()
  parent: com.microsoft.applicationinsights.internal.logger._logger_output
  href: com.microsoft.applicationinsights.internal.logger._logger_output.yml
  name: close()
  fullName: void com.microsoft.applicationinsights.internal.logger.LoggerOutput.close()
  type: Method
  syntax:
    content: public void close()
