items:
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  id: _application_insights_appender
  parent: com.microsoft.applicationinsights.log4j.v1__2
  children:
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.activateOptions()
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.append(LoggingEvent)
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.close()
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.getTelemetryClientProxy()
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.requiresLayout()
  - com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.setInstrumentationKey(String)
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: ApplicationInsightsAppender
  fullName: com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender
  type: Class
  source:
    remote: &o0
      path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 30
  package: com.microsoft.applicationinsights.log4j.v1__2
  syntax:
    content: public class ApplicationInsightsAppender
  inheritance:
  - java.lang.Object
  - AppenderSkeleton
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.activateOptions()
  id: activateOptions()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: activateOptions()
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender.activateOptions()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 98
  package: com.microsoft.applicationinsights.log4j.v1__2
  summary: <p>This method is being called on object initialization. </p>
  syntax:
    content: public void activateOptions()
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.append(LoggingEvent)
  id: append(LoggingEvent)
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: append(LoggingEvent event)
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender.append(LoggingEvent event)
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 61
  package: com.microsoft.applicationinsights.log4j.v1__2
  summary: <p>Subclasses of  should implement this method to perform actual logging. See also <ref refid="" kindref="compound">AppenderSkeleton.doAppend</ref> method. </p>
  syntax:
    content: protected void append(LoggingEvent event)
    parameters:
    - id: event
      type: e7d35b9c
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.close()
  id: close()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: close()
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender.close()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 81
  package: com.microsoft.applicationinsights.log4j.v1__2
  summary: <p>Release any allocated resources. </p>
  syntax:
    content: public void close()
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.getTelemetryClientProxy()
  id: getTelemetryClientProxy()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: getTelemetryClientProxy()
  fullName: TelemetryClientProxy com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender.getTelemetryClientProxy()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 42
  package: com.microsoft.applicationinsights.log4j.v1__2
  syntax:
    content: public TelemetryClientProxy getTelemetryClientProxy()
    return:
      type: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.requiresLayout()
  id: requiresLayout()
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: requiresLayout()
  fullName: boolean com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender.requiresLayout()
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 90
  package: com.microsoft.applicationinsights.log4j.v1__2
  summary: <p>This Appender converts the LoggingEvent it receives into a text string and requires the layout format string to do so. </p>
  syntax:
    content: public boolean requiresLayout()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.setInstrumentationKey(String)
  id: setInstrumentationKey(String)
  parent: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender
  href: com.microsoft.applicationinsights.log4j.v1__2._application_insights_appender.yml
  langs:
  - java
  name: setInstrumentationKey(String key)
  fullName: void com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender.setInstrumentationKey(String key)
  type: Method
  source:
    remote: *o0
    path: logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppender.java
    startLine: 51
  package: com.microsoft.applicationinsights.log4j.v1__2
  summary: <p>Sets the instrumentation key. This method is used by Log4j system initializer when reading configuration. </p>
  syntax:
    content: public void setInstrumentationKey(String key)
    parameters:
    - id: key
      type: "26831127"
      description: <p>The instrumentation key. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: e7d35b9c
  spec.java:
  - name: LoggingEvent
    fullName: LoggingEvent
- uid: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy
  parent: com.microsoft.applicationinsights.internal.common
  href: com.microsoft.applicationinsights.internal.common._telemetry_client_proxy.yml
  name: TelemetryClientProxy
  fullName: com.microsoft.applicationinsights.internal.common.TelemetryClientProxy
  type: Interface
  syntax:
    content: public interface TelemetryClientProxy
