items:
- uid: com.microsoft.applicationinsights.sample._ai_logging
  id: _ai_logging
  parent: com.microsoft.applicationinsights.sample
  children:
  - com.microsoft.applicationinsights.sample._ai_logging.main(String[])
  href: com.microsoft.applicationinsights.sample._ai_logging.yml
  langs:
  - java
  name: AiLogging
  fullName: com.microsoft.applicationinsights.sample.AiLogging
  type: Class
  source:
    remote: &o0
      path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiLogging.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiLogging.java
    startLine: 29
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public class AiLogging
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.sample._ai_logging.main(String[])
  id: main(String[])
  parent: com.microsoft.applicationinsights.sample._ai_logging
  href: com.microsoft.applicationinsights.sample._ai_logging.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void com.microsoft.applicationinsights.sample.AiLogging.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiLogging.java
    startLine: 30
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
