items:
- uid: com.microsoft.applicationinsights.internal.system
  id: system
  children:
  - com.microsoft.applicationinsights.internal.system._system_information
  - com.microsoft.applicationinsights.internal.system._system_information_test
  href: com.microsoft.applicationinsights.internal.system.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.system
  fullName: com.microsoft.applicationinsights.internal.system
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
    startLine: 21
  syntax:
    content: namespace system
references:
- uid: com.microsoft.applicationinsights.internal.system._system_information
  parent: com.microsoft.applicationinsights.internal.system
  href: com.microsoft.applicationinsights.internal.system._system_information.yml
  name: SystemInformation
  fullName: com.microsoft.applicationinsights.internal.system.SystemInformation
  type: Enum
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public enum SystemInformation
- uid: com.microsoft.applicationinsights.internal.system._system_information_test
  parent: com.microsoft.applicationinsights.internal.system
  href: com.microsoft.applicationinsights.internal.system._system_information_test.yml
  name: SystemInformationTest
  fullName: com.microsoft.applicationinsights.internal.system.SystemInformationTest
  type: Class
  syntax:
    content: public class SystemInformationTest
