items:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher
  id: _jmx_data_fetcher
  parent: com.microsoft.applicationinsights.internal.jmx
  children:
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher.fetch(String,Collection<JmxAttributeData>)
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher.yml
  langs:
  - java
  name: JmxDataFetcher
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcher
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.jmx
  summary: >-
    <p>A utility class that knows how to fetch JMX data.</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxDataFetcher
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher.fetch(String,Collection<JmxAttributeData>)
  id: fetch(String,Collection<JmxAttributeData>)
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher.yml
  langs:
  - java
  name: fetch(String objectName, Collection<JmxAttributeData> attributes)
  fullName: static Map<String, Collection<Object>> com.microsoft.applicationinsights.internal.jmx.JmxDataFetcher.fetch(String objectName, Collection<JmxAttributeData> attributes)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.jmx
  summary: <p>Gets an object name and its attributes to fetch and will return the data. </p>
  syntax:
    content: public static Map<String, Collection<Object>> fetch(String objectName, Collection<JmxAttributeData> attributes)
    parameters:
    - id: objectName
      type: "26831127"
      description: <p>The object name to search. </p>
    - id: attributes
      type: 12ebb11acom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
      description: <p>The attributes that 'belong' to the object name. </p>
    return:
      type: 08e6ca1e
      description: '<p>A map that represent each attribute: the key is the displayed name for that attribute and the value is a list of values found </p>'
  exceptions:
  - type: 8a99d4b0
    description: <p>In case the object name is not found. </p>
references:
- uid: 8a99d4b0
  spec.java:
  - name: Exception
    fullName: Exception
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 12ebb11acom.microsoft.applicationinsights.internal.jmx._jmx_attribute_dataa08ddfce
  spec.java:
  - name: Collection<
    fullName: Collection<
  - uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
    name: JmxAttributeData
    fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
    href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  - name: '>'
    fullName: '>'
- uid: 08e6ca1e
  spec.java:
  - name: Map<String, Collection<Object>>
    fullName: Map<String, Collection<Object>>
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  name: JmxAttributeData
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
  type: Class
  summary: >-
    <p>Represents JMX data of an Attribute The display name The name of the attribute The type of the attribute</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxAttributeData
