items:
- uid: com.microsoft.applicationinsights.extensibility.context._location_context_test
  id: _location_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  children:
  - com.microsoft.applicationinsights.extensibility.context._location_context_test.testSetBadIp()
  - com.microsoft.applicationinsights.extensibility.context._location_context_test.testSetIp()
  href: com.microsoft.applicationinsights.extensibility.context._location_context_test.yml
  langs:
  - java
  name: LocationContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.LocationContextTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/LocationContextTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/LocationContextTest.java
    startLine: 30
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public class LocationContextTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.context._location_context_test.testSetBadIp()
  id: testSetBadIp()
  parent: com.microsoft.applicationinsights.extensibility.context._location_context_test
  href: com.microsoft.applicationinsights.extensibility.context._location_context_test.yml
  langs:
  - java
  name: testSetBadIp()
  fullName: void com.microsoft.applicationinsights.extensibility.context.LocationContextTest.testSetBadIp()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/LocationContextTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetBadIp()
- uid: com.microsoft.applicationinsights.extensibility.context._location_context_test.testSetIp()
  id: testSetIp()
  parent: com.microsoft.applicationinsights.extensibility.context._location_context_test
  href: com.microsoft.applicationinsights.extensibility.context._location_context_test.yml
  langs:
  - java
  name: testSetIp()
  fullName: void com.microsoft.applicationinsights.extensibility.context.LocationContextTest.testSetIp()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/LocationContextTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetIp()
references: []
