items:
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  id: _add_type_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._add_type_xml_element.getData()
  - com.microsoft.applicationinsights.internal.config._add_type_xml_element.getParameters()
  - com.microsoft.applicationinsights.internal.config._add_type_xml_element.getType()
  - com.microsoft.applicationinsights.internal.config._add_type_xml_element.setParameters(ArrayList<ParamXmlElement>)
  - com.microsoft.applicationinsights.internal.config._add_type_xml_element.setType(String)
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  langs:
  - java
  name: AddTypeXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.AddTypeXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AddTypeXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  langs:
  - java
  name: getData()
  fullName: Map<String, String> com.microsoft.applicationinsights.internal.config.AddTypeXmlElement.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public Map<String, String> getData()
    return:
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element.getParameters()
  id: getParameters()
  parent: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  langs:
  - java
  name: getParameters()
  fullName: ArrayList<ParamXmlElement> com.microsoft.applicationinsights.internal.config.AddTypeXmlElement.getParameters()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<ParamXmlElement> getParameters()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._param_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  langs:
  - java
  name: getType()
  fullName: String com.microsoft.applicationinsights.internal.config.AddTypeXmlElement.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element.setParameters(ArrayList<ParamXmlElement>)
  id: setParameters(ArrayList<ParamXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  langs:
  - java
  name: setParameters(ArrayList<ParamXmlElement> paramElements)
  fullName: void com.microsoft.applicationinsights.internal.config.AddTypeXmlElement.setParameters(ArrayList<ParamXmlElement> paramElements)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setParameters(ArrayList<ParamXmlElement> paramElements)
    parameters:
    - id: paramElements
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._param_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._add_type_xml_element.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.internal.config._add_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._add_type_xml_element.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.internal.config.AddTypeXmlElement.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._param_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._param_xml_element
    name: ParamXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.ParamXmlElement
    href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  name: ParamXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ParamXmlElement
  type: Class
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class ParamXmlElement
