items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  id: _transmission_policy_manager
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.getTransmissionPolicyState()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.stop(long,TimeUnit)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.suspendInSeconds(TransmissionPolicy,long)
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.TransmissionPolicyManager(boolean)
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  langs:
  - java
  name: TransmissionPolicyManager
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>This class is responsible for managing the transmission state.</p>

    <p>The class might be told to suspend transmission for the next 'X' seconds where the state is set to be one of the states defined in <ref refid="" kindref="compound">com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicy</ref></p>

    <p>The class will keep that state for the requested amount of time and will release it, i.e. reset to 'unblock' when the timeout expires.</p>

    <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public class TransmissionPolicyManager implements Stoppable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.shutdown._stoppable
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.getTransmissionPolicyState()
  id: getTransmissionPolicyState()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  langs:
  - java
  name: getTransmissionPolicyState()
  fullName: TransmissionPolicyStateFetcher com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager.getTransmissionPolicyState()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
    startLine: 104
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public TransmissionPolicyStateFetcher getTransmissionPolicyState()
    return:
      type: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: synchronized void com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
    startLine: 100
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public synchronized void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
    return:
      type: 5c0b90ca
  overridden: com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.suspendInSeconds(TransmissionPolicy,long)
  id: suspendInSeconds(TransmissionPolicy,long)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  langs:
  - java
  name: suspendInSeconds(TransmissionPolicy policy, long suspendInSeconds)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager.suspendInSeconds(TransmissionPolicy policy, long suspendInSeconds)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
    startLine: 87
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void suspendInSeconds(TransmissionPolicy policy, long suspendInSeconds)
    parameters:
    - id: policy
      type: defdcfa6
    - id: suspendInSeconds
      type: 0364520f
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.TransmissionPolicyManager(boolean)
  id: TransmissionPolicyManager(boolean)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_manager.yml
  langs:
  - java
  name: TransmissionPolicyManager(boolean throttlingIsEnabled)
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyManager.TransmissionPolicyManager(boolean throttlingIsEnabled)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public TransmissionPolicyManager(boolean throttlingIsEnabled)
    parameters:
    - id: throttlingIsEnabled
      type: 4fc6e284
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: defdcfa6
  spec.java:
  - name: TransmissionPolicy
    fullName: TransmissionPolicy
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: 5c0b90ca
  spec.java:
  - name: synchronized void
    fullName: synchronized void
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable
  parent: com.microsoft.applicationinsights.internal.shutdown
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: Stoppable
  fullName: com.microsoft.applicationinsights.internal.shutdown.Stoppable
  type: Interface
  summary: <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface Stoppable
- uid: com.microsoft.applicationinsights.internal.shutdown._stoppable.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.shutdown._stoppable
  href: com.microsoft.applicationinsights.internal.shutdown._stoppable.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.shutdown.Stoppable.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_fetcher.yml
  name: TransmissionPolicyStateFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateFetcher
  type: Interface
  summary: <p>Created by gupele on 6/29/2015. </p>
  syntax:
    content: public interface TransmissionPolicyStateFetcher
