items:
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  id: _application_insights_writer_logger
  parent: com.microsoft.applicationinsights.collectd.internal
  children:
  - com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.ApplicationInsightsWriterLogger()
  - com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.ApplicationInsightsWriterLogger(boolean)
  - com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logDebug(String)
  - com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logError(String)
  - com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logInfo(String)
  - com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logWarning(String)
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: ApplicationInsightsWriterLogger
  fullName: com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger
  type: Class
  source:
    remote: &o0
      path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 28
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Created by yonisha on 5/4/2015. </p>
  syntax:
    content: public class ApplicationInsightsWriterLogger
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.ApplicationInsightsWriterLogger()
  id: ApplicationInsightsWriterLogger()
  parent: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: ApplicationInsightsWriterLogger()
  fullName: com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger.ApplicationInsightsWriterLogger()
  type: Constructor
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 36
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Constructs new instance of  </p>
  syntax:
    content: public ApplicationInsightsWriterLogger()
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.ApplicationInsightsWriterLogger(boolean)
  id: ApplicationInsightsWriterLogger(boolean)
  parent: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: ApplicationInsightsWriterLogger(boolean enabled)
  fullName: com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger.ApplicationInsightsWriterLogger(boolean enabled)
  type: Constructor
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 44
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Constructs new instance of  </p>
  syntax:
    content: public ApplicationInsightsWriterLogger(boolean enabled)
    parameters:
    - id: enabled
      type: 4fc6e284
      description: <p>True to enable the plugin, false otherwise. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logDebug(String)
  id: logDebug(String)
  parent: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: logDebug(String message)
  fullName: void com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger.logDebug(String message)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 52
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Log message in debug level. </p>
  syntax:
    content: public void logDebug(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logError(String)
  id: logError(String)
  parent: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: logError(String message)
  fullName: void com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger.logError(String message)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 88
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Log message in error level. </p>
  syntax:
    content: public void logError(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logInfo(String)
  id: logInfo(String)
  parent: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: logInfo(String message)
  fullName: void com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger.logInfo(String message)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 64
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Log message in info level. </p>
  syntax:
    content: public void logInfo(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.logWarning(String)
  id: logWarning(String)
  parent: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  langs:
  - java
  name: logWarning(String message)
  fullName: void com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger.logWarning(String message)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/ApplicationInsightsWriterLogger.java
    startLine: 76
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Log message in warning level. </p>
  syntax:
    content: public void logWarning(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The message to log. </p>
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
