items:
- uid: com.microsoft.applicationinsights.logback.internal
  id: internal
  children:
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event
  - com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  href: com.microsoft.applicationinsights.logback.internal.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.logback.internal
  fullName: com.microsoft.applicationinsights.logback.internal
  type: Namespace
  source:
    remote:
      path: logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEvent.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEvent.java
    startLine: 21
  syntax:
    content: namespace internal
references:
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event
  parent: com.microsoft.applicationinsights.logback.internal
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event.yml
  name: ApplicationInsightsLogEvent
  fullName: com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEvent
  type: Class
  syntax:
    content: public class ApplicationInsightsLogEvent extends ApplicationInsightsEvent
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test
  parent: com.microsoft.applicationinsights.logback.internal
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event_test.yml
  name: ApplicationInsightsLogEventTest
  fullName: com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEventTest
  type: Class
  syntax:
    content: public class ApplicationInsightsLogEventTest
