items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var
  id: _temp_var
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.TempVar(int)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.tempVarIndex()
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.yml
  langs:
  - java
  name: AdvancedAdviceAdapter.TempVar
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempVar
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 44
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected class TempVar
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.TempVar(int)
  id: TempVar(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.yml
  langs:
  - java
  name: TempVar(int tempVarIndex)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempVar.TempVar(int tempVarIndex)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 47
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public TempVar(int tempVarIndex)
    parameters:
    - id: tempVarIndex
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.tempVarIndex()
  id: tempVarIndex()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.yml
  langs:
  - java
  name: tempVarIndex
  fullName: final int com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempVar.tempVarIndex
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 45
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public final int tempVarIndex
    return:
      type: cd225469
references:
- uid: cd225469
  spec.java:
  - name: final int
    fullName: final int
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
