items:
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry
  id: _event_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._event_telemetry.additionalSanitize()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry(String)
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getData()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getMetrics()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.getName()
  - com.microsoft.applicationinsights.telemetry._event_telemetry.setName(String)
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: EventTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 33
  package: com.microsoft.applicationinsights.telemetry
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track events. </p>
  syntax:
    content: public class EventTelemetry extends BaseTelemetry<EventData>
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._base_telemetry
  inheritedMembers:
  - com.microsoft.applicationinsights.telemetry._base_telemetry.BaseTelemetry()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getContext()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getProperties()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getSequence()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.getTimestamp()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.initialize(ConcurrentMap<String, String>)
  - com.microsoft.applicationinsights.telemetry._base_telemetry.sanitize()
  - com.microsoft.applicationinsights.telemetry._base_telemetry.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.telemetry._base_telemetry.setSequence(String)
  - com.microsoft.applicationinsights.telemetry._base_telemetry.setTimestamp(Date)
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.additionalSanitize()
  id: additionalSanitize()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: additionalSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetry.additionalSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 86
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sanitize additional stuff besides the common </p>
  syntax:
    content: protected void additionalSanitize()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry()
  id: EventTelemetry()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: EventTelemetry()
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry.EventTelemetry()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 39
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Default initialization for a new instance. </p>
  syntax:
    content: public EventTelemetry()
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.EventTelemetry(String)
  id: EventTelemetry(String)
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: EventTelemetry(String name)
  fullName: com.microsoft.applicationinsights.telemetry.EventTelemetry.EventTelemetry(String name)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 49
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Initializes a new instance. </p>
  syntax:
    content: public EventTelemetry(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>The event's name. </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getData()
  fullName: EventData com.microsoft.applicationinsights.telemetry.EventTelemetry.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 96
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Fetches the data structure the instance works with </p>
  syntax:
    content: protected EventData getData()
    return:
      type: 9310f39a
      description: <p>The inner data structure. </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getMetrics()
  id: getMetrics()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getMetrics()
  fullName: ConcurrentMap<String, Double> com.microsoft.applicationinsights.telemetry.EventTelemetry.getMetrics()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 58
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets a map of application-defined event metrics. </p>
  syntax:
    content: public ConcurrentMap<String, Double> getMetrics()
    return:
      type: 5f392589
      description: <p>The map of metrics </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.telemetry.EventTelemetry.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 66
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the name of the event. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>The name </p>
- uid: com.microsoft.applicationinsights.telemetry._event_telemetry.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.telemetry._event_telemetry
  href: com.microsoft.applicationinsights.telemetry._event_telemetry.yml
  langs:
  - java
  name: setName(String name)
  fullName: void com.microsoft.applicationinsights.telemetry.EventTelemetry.setName(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java
    startLine: 74
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the name of the event. </p>
  syntax:
    content: public void setName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>Name of the event </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 5f392589
  spec.java:
  - name: ConcurrentMap<String, Double>
    fullName: ConcurrentMap<String, Double>
- uid: 9310f39a
  spec.java:
  - name: EventData
    fullName: EventData
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.BaseTelemetry()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: BaseTelemetry()
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.BaseTelemetry()
  type: Constructor
  syntax:
    content: protected BaseTelemetry()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getContext()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getContext()
  fullName: TelemetryContext com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getContext()
  type: Method
  summary: <p>Gets the context associated with the current telemetry item. </p>
  syntax:
    content: public TelemetryContext getContext()
    return:
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>The context </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getProperties()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getProperties()
  fullName: Map<String, String> com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getProperties()
  type: Method
  summary: <p>Gets a dictionary of application-defined property names and values providing additional information about this event. </p>
  syntax:
    content: public Map<String, String> getProperties()
    return:
      type: 689c8cb5
      description: <p>The properties </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getSequence()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getSequence()
  fullName: String com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getSequence()
  type: Method
  summary: >-
    <p>Sequence field used to track absolute order of uploaded events. It is a two-part value that includes a stable identifier for the current boot session and an incrementing identifier for each event added to the upload queue</p>

    <p>The Sequence helps track how many events were fired and how many events were uploaded and enables identification of data lost during upload and de-duplication of events on the ingress server.</p>

    <p>Gets the value that defines absolute order of the telemetry item. </p>
  syntax:
    content: public String getSequence()
    return:
      type: "26831127"
      description: <p>The sequence of the <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>. </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.getTimestamp()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: getTimestamp()
  fullName: Date com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.getTimestamp()
  type: Method
  summary: <p>Gets date and time when event was recorded. </p>
  syntax:
    content: public Date getTimestamp()
    return:
      type: "12977444"
      description: <p>The timestamp as Date </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.initialize(ConcurrentMap<String, String>)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: initialize(ConcurrentMap<String, String> properties)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.initialize(ConcurrentMap<String, String> properties)
  type: Method
  summary: <p>Initializes the instance with the context properties </p>
  syntax:
    content: protected void initialize(ConcurrentMap<String, String> properties)
    parameters:
    - id: properties
      type: bc7a2f3a
      description: <p>The context properties </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.sanitize()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: sanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.sanitize()
  type: Method
  summary: <p>Makes sure the data to send is sanitized from bad chars, proper length etc. </p>
  syntax:
    content: public void sanitize()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  summary: <p>Serializes this object in JSON format. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer that helps with serializing into Json format </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.setSequence(String)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: setSequence(String sequence)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.setSequence(String sequence)
  type: Method
  summary: <p>Sets the value that defines absolute order of the telemetry item. </p>
  syntax:
    content: public void setSequence(String sequence)
    parameters:
    - id: sequence
      type: "26831127"
      description: <p>The sequence of the <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>. </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry.setTimestamp(Date)
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: setTimestamp(Date date)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetry<T extends SendableData>.setTimestamp(Date date)
  type: Method
  summary: <p>Sets date and time when event was recorded. </p>
  syntax:
    content: public void setTimestamp(Date date)
    parameters:
    - id: date
      type: "12977444"
      description: <p>The timestamp as Date. </p>
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_telemetry.yml
  name: BaseTelemetry<T>
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetry<T>
  type: Class
  summary: <p>Superclass for all telemetry data classes. </p>
  syntax:
    content: public class BaseTelemetry<T extends SendableData> implements Telemetry
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
