items:
- uid: com.microsoft.applicationinsights.internal.channel.inprocess
  id: inprocess
  children:
  - com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test
  href: com.microsoft.applicationinsights.internal.channel.inprocess.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.channel.inprocess
  fullName: com.microsoft.applicationinsights.internal.channel.inprocess
  type: Namespace
  source:
    remote:
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/inprocess/InProcessTelemetryChannelTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/inprocess/InProcessTelemetryChannelTest.java
    startLine: 21
  syntax:
    content: namespace inprocess
references:
- uid: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test
  parent: com.microsoft.applicationinsights.internal.channel.inprocess
  href: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.yml
  name: InProcessTelemetryChannelTest
  fullName: com.microsoft.applicationinsights.internal.channel.inprocess.InProcessTelemetryChannelTest
  type: Class
  syntax:
    content: public class InProcessTelemetryChannelTest
