items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  id: _windows_performance_counter_as_metric
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.getId()
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.report(TelemetryClient)
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.send(TelemetryClient,double,String)
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.WindowsPerformanceCounterAsMetric(Iterable<WindowsPerformanceCounterData>)
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  langs:
  - java
  name: WindowsPerformanceCounterAsMetric
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>Performance counters that are sent as <xref href="com.microsoft.applicationinsights.telemetry._metric_telemetry" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterAsMetric extends AbstractWindowsPerformanceCounter
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.AbstractWindowsPerformanceCounter()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.reportError(double,String)
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String getId()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.report(TelemetryClient)
  id: report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  langs:
  - java
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric.report(TelemetryClient telemetryClient)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
    startLine: 76
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Go through the data that we have and ask for each key its value, and then send using the requested display name. The method might throw an Error if the <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> is not able to properly connect to the native code. </p>
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref> to use for sending </p>
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.send(TelemetryClient,double,String)
  id: send(TelemetryClient,double,String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  langs:
  - java
  name: send(TelemetryClient telemetryClient, double value, String key)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric.send(TelemetryClient telemetryClient, double value, String key)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
    startLine: 108
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: protected void send(TelemetryClient telemetryClient, double value, String key)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
    - id: value
      type: a07dcde8
    - id: key
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.WindowsPerformanceCounterAsMetric(Iterable<WindowsPerformanceCounterData>)
  id: WindowsPerformanceCounterAsMetric(Iterable<WindowsPerformanceCounterData>)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  langs:
  - java
  name: WindowsPerformanceCounterAsMetric(Iterable<WindowsPerformanceCounterData> pcsData)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric.WindowsPerformanceCounterAsMetric(Iterable<WindowsPerformanceCounterData> pcsData)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Registers the argument's data into performance counters. </p>
  syntax:
    content: public WindowsPerformanceCounterAsMetric(Iterable<WindowsPerformanceCounterData> pcsData)
    parameters:
    - id: pcsData
      type: 2a13b5a5com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_dataa08ddfce
      description: <p>The performance counters to register for Windows OS. </p>
  exceptions:
  - type: b7c46b4b
    description: <p>The constructor might throw an Error if the <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> is not able to properly connect to the native code. or Exception if the constructor is not called under Windows OS. </p>
references:
- uid: b7c46b4b
  spec.java:
  - name: java.lang.Throwable
    fullName: java.lang.Throwable
- uid: 2a13b5a5com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_dataa08ddfce
  spec.java:
  - name: Iterable<
    fullName: Iterable<
  - uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
    name: WindowsPerformanceCounterData
    fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
    href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  - name: '>'
    fullName: '>'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: a07dcde8
  spec.java:
  - name: double
    fullName: double
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.AbstractWindowsPerformanceCounter()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: AbstractWindowsPerformanceCounter()
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter.AbstractWindowsPerformanceCounter()
  type: Constructor
  syntax:
    content: protected AbstractWindowsPerformanceCounter()
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.reportError(double,String)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: reportError(double value, String displayName)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter.reportError(double value, String displayName)
  type: Method
  syntax:
    content: protected void reportError(double value, String displayName)
    parameters:
    - id: value
      type: a07dcde8
    - id: displayName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: AbstractWindowsPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter
  type: Class
  summary: <p>Created by gupele on 4/29/2015. </p>
  syntax:
    content: public class AbstractWindowsPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry.yml
  name: MetricTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.MetricTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track metrics. </p>
  syntax:
    content: public class MetricTelemetry extends BaseTelemetry<MetricData>
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  name: WindowsPerformanceCounterData
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterData
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  name: JniPCConnector
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector
  type: Class
  summary: >-
    <p>This class serves as the connection to the native code that does the work with Windows.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class JniPCConnector
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
