items:
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_sku
  id: _with_sku
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_sku.withSku(ApplicationGatewaySkuName,int)
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_sku.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithSku
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithSku
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 338
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to specify the SKU. </p>
  syntax:
    content: public interface WithSku
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_sku.withSku(ApplicationGatewaySkuName,int)
  id: withSku(ApplicationGatewaySkuName,int)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_sku
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_sku.yml
  langs:
  - java
  name: withSku(ApplicationGatewaySkuName skuName, int capacity)
  fullName: WithContainingSubnet com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithSku.withSku(ApplicationGatewaySkuName skuName, int capacity)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 345
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the SKU of the application gateway to create. </p>
  syntax:
    content: public WithContainingSubnet withSku(ApplicationGatewaySkuName skuName, int capacity)
    parameters:
    - id: skuName
      type: com.microsoft.azure.management.network._application_gateway_sku_name
      description: <p>an application gateway SKU name </p>
    - id: capacity
      type: f75371fa
      description: <p>the capacity of the SKU, between 1 and 10 </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
      description: <p>the next stage of the definition </p>
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
- uid: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.yml
  name: ApplicationGateway.DefinitionStages.WithContainingSubnet
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithContainingSubnet
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to specify the subnet the app gateway is getting its private IP address from. </p>
  syntax:
    content: public interface WithContainingSubnet
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ApplicationGatewaySkuName
