items:
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  id: _sendable_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
  - com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  langs:
  - java
  name: SendableData
  fullName: com.microsoft.applicationinsights.internal.schemav2.SendableData
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/SendableData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/SendableData.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Defines the interface for data that might be sent to the Server. </p>
  syntax:
    content: public interface SendableData extends JsonSerializable
  inheritedMembers:
  - com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
  id: getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  langs:
  - java
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getBaseTypeName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/SendableData.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
  id: getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  langs:
  - java
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getEnvelopName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/SendableData.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.internal.schemav2._base
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  name: Base
  fullName: com.microsoft.applicationinsights.internal.schemav2.Base
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._base" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Base implements JsonSerializable,SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data_point.yml
  name: DataPoint
  fullName: com.microsoft.applicationinsights.internal.schemav2.DataPoint
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data_point" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class DataPoint implements JsonSerializable,SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._domain
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: Domain
  fullName: com.microsoft.applicationinsights.internal.schemav2.Domain
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._domain" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Domain implements SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._session_state_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._session_state_data
  href: com.microsoft.applicationinsights.internal.schemav2._session_state_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SessionStateData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Domain.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._data
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Data<TDomain extends SendableData>.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._page_view_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._page_view_data
  href: com.microsoft.applicationinsights.internal.schemav2._page_view_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.PageViewData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._metric_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._metric_data
  href: com.microsoft.applicationinsights.internal.schemav2._metric_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.MetricData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.EventData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._message_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._message_data
  href: com.microsoft.applicationinsights.internal.schemav2._message_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.MessageData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._page_view_perf_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._page_view_perf_data
  href: com.microsoft.applicationinsights.internal.schemav2._page_view_perf_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.PageViewPerfData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._exception_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._exception_data
  href: com.microsoft.applicationinsights.internal.schemav2._exception_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.ExceptionData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._data_point
  href: com.microsoft.applicationinsights.internal.schemav2._data_point.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.DataPoint.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._request_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._request_data
  href: com.microsoft.applicationinsights.internal.schemav2._request_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.RequestData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data
  href: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.RemoteDependencyData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._session_state_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._session_state_data
  href: com.microsoft.applicationinsights.internal.schemav2._session_state_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SessionStateData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._domain.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._domain
  href: com.microsoft.applicationinsights.internal.schemav2._domain.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Domain.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._page_view_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._page_view_data
  href: com.microsoft.applicationinsights.internal.schemav2._page_view_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.PageViewData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._data
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Data<TDomain extends SendableData>.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._metric_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._metric_data
  href: com.microsoft.applicationinsights.internal.schemav2._metric_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.MetricData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data
  href: com.microsoft.applicationinsights.internal.schemav2._performance_counter_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.PerformanceCounterData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._event_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._event_data
  href: com.microsoft.applicationinsights.internal.schemav2._event_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.EventData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._message_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._message_data
  href: com.microsoft.applicationinsights.internal.schemav2._message_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.MessageData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._page_view_perf_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._page_view_perf_data
  href: com.microsoft.applicationinsights.internal.schemav2._page_view_perf_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.PageViewPerfData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._exception_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._exception_data
  href: com.microsoft.applicationinsights.internal.schemav2._exception_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.ExceptionData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._data_point
  href: com.microsoft.applicationinsights.internal.schemav2._data_point.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.DataPoint.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._request_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._request_data
  href: com.microsoft.applicationinsights.internal.schemav2._request_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.RequestData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data
  href: com.microsoft.applicationinsights.internal.schemav2._remote_dependency_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.RemoteDependencyData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
