items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend._update
  id: _update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend._update.yml
  langs:
  - java
  name: ApplicationGatewayFrontend.Update
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.Update
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
    startLine: 144
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of an application gateway frontend update as part of an application gateway update. </p>
  syntax:
    content: public interface Update extends Settable<ApplicationGateway.Update>,ApplicationGatewayFrontend.UpdateStages.WithSubnet,ApplicationGatewayFrontend.UpdateStages.WithPublicIpAddress,ApplicationGatewayFrontend.UpdateStages.WithPrivateIp
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._settable.parent()
  - com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.withExistingPublicIpAddress(PublicIpAddress)
  - com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.withExistingPublicIpAddress(String)
  - com.microsoft.azure.management.network._application_gateway_frontend._update_stages._with_subnet.withExistingSubnet(Network,String)
  - com.microsoft.azure.management.resources.fluentcore.arm.models.c2f0776979e0cb50d2b104de3287f808.withExistingSubnet(String,String)
  - com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.withoutPublicIpAddress()
  - com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressStatic(String)
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable.parent()
  parent: com.microsoft.azure.management.resources.fluentcore.model._settable
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Settable<ParentT>.parent()
  type: Method
  summary: >-
    <p>Begins an update for a child resource. </p>

    <p>This is the beginning of the builder pattern used to update child resources The final method completing the update and continue the actual parent resource update process in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> is <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable.parent()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the stage of parent resource update </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.withExistingPublicIpAddress(PublicIpAddress)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2
  href: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.yml
  name: withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
    parameters:
    - id: publicIpAddress
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.withExistingPublicIpAddress(String)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2
  href: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.yml
  name: withExistingPublicIpAddress(String resourceId)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(String resourceId)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(String resourceId)
    parameters:
    - id: resourceId
      type: "26831127"
      description: <p>the resource ID of an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend._update_stages._with_subnet.withExistingSubnet(Network,String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend._update_stages._with_subnet
  href: com.microsoft.azure.management.network._application_gateway_frontend._update_stages._with_subnet.yml
  name: withExistingSubnet(Network network, String subnetName)
  fullName: Update com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateStages.WithSubnet.withExistingSubnet(Network network, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this private frontend. </p>
  syntax:
    content: public Update withExistingSubnet(Network network, String subnetName)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network the subnet exists in </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend._update
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.c2f0776979e0cb50d2b104de3287f808.withExistingSubnet(String,String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.c2f0776979e0cb50d2b104de3287f808
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.c2f0776979e0cb50d2b104de3287f808.yml
  name: withExistingSubnet(String parentNetworkResourceId, String subnetName)
  fullName: ReturnT com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.UpdateStages.WithSubnet<ReturnT>.withExistingSubnet(String parentNetworkResourceId, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this resource. </p>
  syntax:
    content: public ReturnT withExistingSubnet(String parentNetworkResourceId, String subnetName)
    parameters:
    - id: parentNetworkResourceId
      type: "26831127"
      description: <p>the resource ID of the virtual network the subnet is part of </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of the subnet </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.withoutPublicIpAddress()
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2
  href: com.microsoft.azure.management.network.model._has_public_ip_address_167b396c474e351c7d9b98c8ef6b247c2.yml
  name: withoutPublicIpAddress()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateStages.WithExistingPublicIpAddress<ReturnT>.withoutPublicIpAddress()
  type: Method
  summary: >-
    <p>Removes the existing reference to a public IP address.</p>

    <p></p>
  syntax:
    content: public ReturnT withoutPublicIpAddress()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update. </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: Settable<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Settable<ParentT>
  type: Interface
  summary: >-
    <p>The base interface for all template interfaces for child resources that support update operations.</p>

    <p></p>
  syntax:
    content: public interface Settable<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable.parent()" data-throw-if-not-resolved="false"></xref> returns to </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend._update_stages._with_subnet
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend._update_stages._with_subnet.yml
  name: ApplicationGatewayFrontend.UpdateStages.WithSubnet
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateStages.WithSubnet
  type: Interface
  summary: <p>The stage of an application gateway frontend update allowing to specify a subnet from the selected network to make this application gateway visible to. </p>
  syntax:
    content: public interface WithSubnet
- uid: com.microsoft.azure.management.network._application_gateway_frontend.bf942f1d4f5f7c3e79592eed938143e9
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.bf942f1d4f5f7c3e79592eed938143e9.yml
  name: ApplicationGatewayFrontend.UpdateStages.WithPublicIpAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateStages.WithPublicIpAddress
  type: Interface
  summary: <p>The stage of an application gateway frontend definition allowing to specify an existing public IP address to make the application gateway available at as Internet-facing. </p>
  syntax:
    content: public interface WithPublicIpAddress
- uid: com.microsoft.azure.management.network._application_gateway_frontend.b3d22ed01e7a007025c9d6f347f6ac89
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.b3d22ed01e7a007025c9d6f347f6ac89.yml
  name: ApplicationGatewayFrontend.UpdateStages.WithPrivateIp
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateStages.WithPrivateIp
  type: Interface
  summary: <p>The stage of an application gateway frontend update allowing to specify the private IP address this application gateway should be available at within the selected virtual network. </p>
  syntax:
    content: public interface WithPrivateIp
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_impl
