items:
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point_type
  id: _data_point_type
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._data_point_type.Aggregation()
  - com.microsoft.applicationinsights.internal.schemav2._data_point_type.DataPointType(int)
  - com.microsoft.applicationinsights.internal.schemav2._data_point_type.getValue()
  - com.microsoft.applicationinsights.internal.schemav2._data_point_type.Measurement()
  href: com.microsoft.applicationinsights.internal.schemav2._data_point_type.yml
  langs:
  - java
  name: DataPointType
  fullName: com.microsoft.applicationinsights.internal.schemav2.DataPointType
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DataPointType.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DataPointType.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.internal.schemav2._data_point_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum DataPointType
  inheritance:
  - java.lang.Object
  - java.lang.Enum<DataPointType>
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point_type.Aggregation()
  id: Aggregation()
  parent: com.microsoft.applicationinsights.internal.schemav2._data_point_type
  href: com.microsoft.applicationinsights.internal.schemav2._data_point_type.yml
  langs:
  - java
  name: Aggregation
  fullName: com.microsoft.applicationinsights.internal.schemav2.DataPointType.Aggregation
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DataPointType.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Aggregation=(1)
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point_type.DataPointType(int)
  id: DataPointType(int)
  parent: com.microsoft.applicationinsights.internal.schemav2._data_point_type
  href: com.microsoft.applicationinsights.internal.schemav2._data_point_type.yml
  langs:
  - java
  name: DataPointType(int id)
  fullName: com.microsoft.applicationinsights.internal.schemav2.DataPointType.DataPointType(int id)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DataPointType.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public DataPointType(int id)
    parameters:
    - id: id
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point_type.getValue()
  id: getValue()
  parent: com.microsoft.applicationinsights.internal.schemav2._data_point_type
  href: com.microsoft.applicationinsights.internal.schemav2._data_point_type.yml
  langs:
  - java
  name: getValue()
  fullName: int com.microsoft.applicationinsights.internal.schemav2.DataPointType.getValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DataPointType.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public int getValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point_type.Measurement()
  id: Measurement()
  parent: com.microsoft.applicationinsights.internal.schemav2._data_point_type
  href: com.microsoft.applicationinsights.internal.schemav2._data_point_type.yml
  langs:
  - java
  name: Measurement
  fullName: com.microsoft.applicationinsights.internal.schemav2.DataPointType.Measurement
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/DataPointType.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public Measurement=(0)
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.internal.schemav2._data_point_type
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data_point_type.yml
  name: DataPointType
  fullName: com.microsoft.applicationinsights.internal.schemav2.DataPointType
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.internal.schemav2._data_point_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
