items:
- uid: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
  id: _thread_local_cleaner
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._thread_local_cleaner.clean()
  href: com.microsoft.applicationinsights.internal.util._thread_local_cleaner.yml
  langs:
  - java
  name: ThreadLocalCleaner
  fullName: com.microsoft.applicationinsights.internal.util.ThreadLocalCleaner
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadLocalCleaner.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadLocalCleaner.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by gupele on 7/8/2015. </p>
  syntax:
    content: public interface ThreadLocalCleaner
- uid: com.microsoft.applicationinsights.internal.util._thread_local_cleaner.clean()
  id: clean()
  parent: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
  href: com.microsoft.applicationinsights.internal.util._thread_local_cleaner.yml
  langs:
  - java
  name: clean()
  fullName: void com.microsoft.applicationinsights.internal.util.ThreadLocalCleaner.clean()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadLocalCleaner.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void clean()
references: []
