items:
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer
  id: _sequence_property_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer
  children:
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.initialize(Telemetry)
  - com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.SequencePropertyInitializer()
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.yml
  langs:
  - java
  name: SequencePropertyInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializer.java
    startLine: 38
  package: com.microsoft.applicationinsights.extensibility.initializer
  summary: <p>An <xref href="com.microsoft.applicationinsights.extensibility._telemetry_initializer" data-throw-if-not-resolved="false"></xref> implementation that populates Sequence property for the Microsoft internal telemetry sent to the Vortex endpoint. </p>
  syntax:
    content: public class SequencePropertyInitializer implements TelemetryInitializer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_initializer
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.initialize(Telemetry)
  id: initialize(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.yml
  langs:
  - java
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializer.initialize(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializer.java
    startLine: 53
  package: com.microsoft.applicationinsights.extensibility.initializer
  summary: <p>Sets the Telemetry's sequence if there that sequence is null or empty. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_initializer.initialize(Telemetry)
- uid: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.SequencePropertyInitializer()
  id: SequencePropertyInitializer()
  parent: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer._sequence_property_initializer.yml
  langs:
  - java
  name: SequencePropertyInitializer()
  fullName: com.microsoft.applicationinsights.extensibility.initializer.SequencePropertyInitializer.SequencePropertyInitializer()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializer.java
    startLine: 44
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public SequencePropertyInitializer()
references:
- uid: com.microsoft.applicationinsights.extensibility._telemetry_initializer
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_initializer.yml
  name: TelemetryInitializer
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryInitializer
  type: Interface
  summary: <p>Created by gupele on 12/30/2014. </p>
  syntax:
    content: public interface TelemetryInitializer
- uid: com.microsoft.applicationinsights.extensibility._telemetry_initializer.initialize(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_initializer
  href: com.microsoft.applicationinsights.extensibility._telemetry_initializer.yml
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryInitializer.initialize(Telemetry telemetry)
  type: Method
  summary: <p>Initializes properties of the specified object. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
