items:
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  id: _user_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  children:
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie.COOKIE_NAME()
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie.getAcquisitionDate()
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie.getUserId()
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie.isNewUser()
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie.UserCookie()
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie.UserCookie(Cookie)
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: UserCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.UserCookie
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 31
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Created by yonisha on 2/7/2015. </p>
  syntax:
    content: public class UserCookie extends Cookie
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.web.internal.cookies._cookie
  inheritedMembers:
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.formatCookie(String[])
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.getCookie(Class<E>,HttpServletRequest,String)
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_DELIMITER()
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_SPLIT_DELIMITER()
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.COOKIE_NAME()
  id: COOKIE_NAME()
  parent: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: COOKIE_NAME
  fullName: final String com.microsoft.applicationinsights.web.internal.cookies.UserCookie.COOKIE_NAME
  type: Field
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 35
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public static final String COOKIE_NAME= "ai_user"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.getAcquisitionDate()
  id: getAcquisitionDate()
  parent: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: getAcquisitionDate()
  fullName: Date com.microsoft.applicationinsights.web.internal.cookies.UserCookie.getAcquisitionDate()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 81
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public Date getAcquisitionDate()
    return:
      type: "12977444"
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.getUserId()
  id: getUserId()
  parent: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: getUserId()
  fullName: String com.microsoft.applicationinsights.web.internal.cookies.UserCookie.getUserId()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 77
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public String getUserId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.isNewUser()
  id: isNewUser()
  parent: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: isNewUser()
  fullName: boolean com.microsoft.applicationinsights.web.internal.cookies.UserCookie.isNewUser()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 85
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public boolean isNewUser()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.UserCookie()
  id: UserCookie()
  parent: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: UserCookie()
  fullName: com.microsoft.applicationinsights.web.internal.cookies.UserCookie.UserCookie()
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 67
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public UserCookie()
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.UserCookie(Cookie)
  id: UserCookie(Cookie)
  parent: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  langs:
  - java
  name: UserCookie(Cookie cookie)
  fullName: com.microsoft.applicationinsights.web.internal.cookies.UserCookie.UserCookie(Cookie cookie)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/UserCookie.java
    startLine: 62
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public UserCookie(Cookie cookie)
    parameters:
    - id: cookie
      type: com.microsoft.applicationinsights.web.internal.cookies._cookie
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "12977444"
  spec.java:
  - name: Date
    fullName: Date
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.formatCookie(String[])
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: formatCookie(String[] values)
  fullName: static String com.microsoft.applicationinsights.web.internal.cookies.Cookie.formatCookie(String[] values)
  type: Method
  summary: <p>Formats the given values to a session cookie value. </p>
  syntax:
    content: public static String formatCookie(String[] values)
    parameters:
    - id: values
      type: 30d59cf1
      description: <p>The values to format. </p>
    return:
      type: "26831127"
      description: <p>Formatted session cookie. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.getCookie(Class<E>,HttpServletRequest,String)
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: getCookie(Class<E> eClass, HttpServletRequest request, String cookieName)
  fullName: static <E> E com.microsoft.applicationinsights.web.internal.cookies.Cookie.getCookie(Class<E> eClass, HttpServletRequest request, String cookieName)
  type: Method
  summary: <p>Gets the cookie from the given http request. </p>
  syntax:
    content: public static static<E> E getCookie(Class<E> eClass, HttpServletRequest request, String cookieName)
    parameters:
    - id: eClass
      type: df766fea
      description: <p>The required cookie type. </p>
    - id: request
      type: 81123e1c
      description: <p>THe http request to get the cookies from. </p>
    - id: cookieName
      type: "26831127"
      description: <p>The cookie name. </p>
    return:
      type: 678f8414
      description: >-
        <p>

          <xref href="com.microsoft.applicationinsights.web.internal.cookies._cookie" data-throw-if-not-resolved="false"></xref> from the required type. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_DELIMITER()
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: RAW_COOKIE_DELIMITER
  fullName: final String com.microsoft.applicationinsights.web.internal.cookies.Cookie.RAW_COOKIE_DELIMITER
  type: Field
  syntax:
    content: protected static final String RAW_COOKIE_DELIMITER= "|"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_SPLIT_DELIMITER()
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: RAW_COOKIE_SPLIT_DELIMITER
  fullName: final String com.microsoft.applicationinsights.web.internal.cookies.Cookie.RAW_COOKIE_SPLIT_DELIMITER
  type: Field
  syntax:
    content: protected static final String RAW_COOKIE_SPLIT_DELIMITER= "\\" + RAW_COOKIE_DELIMITER
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: Cookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.Cookie
  type: Class
  summary: >-
    <p>Created by yonisha on 2/9/2015.</p>

    <p>Used as a base class for AI cookies. </p>
  syntax:
    content: public class Cookie
