items:
- uid: com.microsoft.azure.management.network._application_gateway._update_stages._with_sku
  id: _with_sku
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._update_stages._with_sku.withSku(ApplicationGatewaySkuName,int)
  href: com.microsoft.azure.management.network._application_gateway._update_stages._with_sku.yml
  langs:
  - java
  name: ApplicationGateway.UpdateStages.WithSku
  fullName: com.microsoft.azure.management.network.ApplicationGateway.UpdateStages.WithSku
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 484
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway update allowing to modify the SKU. </p>
  syntax:
    content: public interface WithSku
- uid: com.microsoft.azure.management.network._application_gateway._update_stages._with_sku.withSku(ApplicationGatewaySkuName,int)
  id: withSku(ApplicationGatewaySkuName,int)
  parent: com.microsoft.azure.management.network._application_gateway._update_stages._with_sku
  href: com.microsoft.azure.management.network._application_gateway._update_stages._with_sku.yml
  langs:
  - java
  name: withSku(ApplicationGatewaySkuName skuName, int capacity)
  fullName: Update com.microsoft.azure.management.network.ApplicationGateway.UpdateStages.WithSku.withSku(ApplicationGatewaySkuName skuName, int capacity)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 491
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the SKU of the application gateway. </p>
  syntax:
    content: public Update withSku(ApplicationGatewaySkuName skuName, int capacity)
    parameters:
    - id: skuName
      type: com.microsoft.azure.management.network._application_gateway_sku_name
      description: <p>an application gateway SKU name </p>
    - id: capacity
      type: f75371fa
      description: <p>the capacity of the SKU, between 1 and 10 </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._update
      description: <p>the next stage of the update </p>
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.management.network._application_gateway._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._update.yml
  name: ApplicationGateway.Update
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Update
  type: Interface
  summary: >-
    <p>The template for an application gateway update operation, containing all the settings that can be modified. </p>

    <p>Call <xref href="com.microsoft.azure.management.resources.fluentcore.model._appliable.apply()" data-throw-if-not-resolved="false"></xref> to apply the changes to the resource in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update extends Appliable<ApplicationGateway>,Resource.UpdateWithTags<Update>,ApplicationGateway.UpdateStages.WithSku,ApplicationGateway.UpdateStages.WithBackend,ApplicationGateway.UpdateStages.WithBackendHttpConfig
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ApplicationGatewaySkuName
