items:
- uid: com.microsoft.applicationinsights.internal.util._device_info
  id: _device_info
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._device_info.getHostName()
  - com.microsoft.applicationinsights.internal.util._device_info.getLocale()
  - com.microsoft.applicationinsights.internal.util._device_info.getOperatingSystem()
  - com.microsoft.applicationinsights.internal.util._device_info.getOperatingSystemVersion()
  - com.microsoft.applicationinsights.internal.util._device_info.getOperatingVersionArchitecture()
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  langs:
  - java
  name: DeviceInfo
  fullName: com.microsoft.applicationinsights.internal.util.DeviceInfo
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>A view into the context information specific to device information. </p>
  syntax:
    content: public class DeviceInfo
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._device_info.getHostName()
  id: getHostName()
  parent: com.microsoft.applicationinsights.internal.util._device_info
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  langs:
  - java
  name: getHostName()
  fullName: static String com.microsoft.applicationinsights.internal.util.DeviceInfo.getHostName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String getHostName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._device_info.getLocale()
  id: getLocale()
  parent: com.microsoft.applicationinsights.internal.util._device_info
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  langs:
  - java
  name: getLocale()
  fullName: static String com.microsoft.applicationinsights.internal.util.DeviceInfo.getLocale()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String getLocale()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._device_info.getOperatingSystem()
  id: getOperatingSystem()
  parent: com.microsoft.applicationinsights.internal.util._device_info
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  langs:
  - java
  name: getOperatingSystem()
  fullName: static String com.microsoft.applicationinsights.internal.util.DeviceInfo.getOperatingSystem()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String getOperatingSystem()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._device_info.getOperatingSystemVersion()
  id: getOperatingSystemVersion()
  parent: com.microsoft.applicationinsights.internal.util._device_info
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  langs:
  - java
  name: getOperatingSystemVersion()
  fullName: static String com.microsoft.applicationinsights.internal.util.DeviceInfo.getOperatingSystemVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String getOperatingSystemVersion()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._device_info.getOperatingVersionArchitecture()
  id: getOperatingVersionArchitecture()
  parent: com.microsoft.applicationinsights.internal.util._device_info
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  langs:
  - java
  name: getOperatingVersionArchitecture()
  fullName: static String com.microsoft.applicationinsights.internal.util.DeviceInfo.getOperatingVersionArchitecture()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String getOperatingVersionArchitecture()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
