items:
- uid: com.microsoft.azure.management.network._application_gateway_public_front5d082c4bf8330c73f170ce100ce2cf6e
  id: _application_gateway_public_front5d082c4bf8330c73f170ce100ce2cf6e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_front5d082c4bf8330c73f170ce100ce2cf6e.yml
  langs:
  - java
  name: ApplicationGatewayPublicFrontend.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.DefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPublicFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPublicFrontend.java
    startLine: 28
  package: com.microsoft.azure.management.network
  summary: <p>The first stage of a public frontend definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayPublicFrontend.DefinitionStages.WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b.withExistingPublicIpAddress(PublicIpAddress)
  - com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b.withExistingPublicIpAddress(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b.withExistingPublicIpAddress(PublicIpAddress)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b
  href: com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b.yml
  name: withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.DefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
    parameters:
    - id: publicIpAddress
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b.withExistingPublicIpAddress(String)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b
  href: com.microsoft.azure.management.network.model._has_public_ip_address_197c6dfc0e1770c66b8269e7e79ac560b.yml
  name: withExistingPublicIpAddress(String resourceId)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.DefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(String resourceId)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(String resourceId)
    parameters:
    - id: resourceId
      type: "26831127"
      description: <p>the resource ID of an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_public_frontdcc49df5ce79cb06ffaa6d1c26765d35
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_frontdcc49df5ce79cb06ffaa6d1c26765d35.yml
  name: ApplicationGatewayPublicFrontend.DefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.DefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  summary: <p>The stage of a public frontend definition allowing to specify an existing public IP address. </p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_public_frontend._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_public_frontend._definition.yml
  name: ApplicationGatewayPublicFrontend.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPublicFrontend.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of a public frontend definition. </p>
  syntax:
    content: public interface Definition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
