items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  id: _advanced_advice_adapter
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.activateEnumMethod(Class<?>,String,String,Object...)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.AdvancedAdviceAdapter(boolean,int,MethodVisitor,int,String,String,String)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.byteCodeForMethodExit(int)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTop(Type)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTopStackToTempVariable(Type)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getMethodName()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getReturnType()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.onMethodExit(int)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.reportExecutionTime()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.translateExitCode(int)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitCode()
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitMaxs(int,int)
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: AdvancedAdviceAdapter
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 35
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: >-
    <p>A base class that lets its derived classes to enjoy utilities like creating temporary variables, managing methods points, method names etc.</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class AdvancedAdviceAdapter
  inheritance:
  - java.lang.Object
  - AdviceAdapter
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.activateEnumMethod(Class<?>,String,String,Object...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: activateEnumMethod(Class<?> clazz, String methodName, String methodSignature, Object...args)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.activateEnumMethod(Class<?> clazz, String methodName, String methodSignature, Object...args)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 129
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>This method calls a Java enum method with its expected argumentes </p>
  syntax:
    content: protected void activateEnumMethod(Class<?> clazz, String methodName, String methodSignature, Object...args)
    parameters:
    - id: clazz
      type: a19781f8
      description: <p>The enum class to activate </p>
    - id: methodName
      type: "26831127"
      description: <p>The method of the class to activate </p>
    - id: methodSignature
      type: "26831127"
      description: <p>The method signature </p>
    - id: args
      type: 1355eaf1
      description: <p>The arguments to pass to the method </p>
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.AdvancedAdviceAdapter(boolean,int,MethodVisitor,int,String,String,String)
  id: AdvancedAdviceAdapter(boolean,int,MethodVisitor,int,String,String,String)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: AdvancedAdviceAdapter(boolean reportExecutionTime, int api, MethodVisitor methodVisitor, int access, String owner, String methodName, String desc)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.AdvancedAdviceAdapter(boolean reportExecutionTime, int api, MethodVisitor methodVisitor, int access, String owner, String methodName, String desc)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 101
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected AdvancedAdviceAdapter(boolean reportExecutionTime, int api, MethodVisitor methodVisitor, int access, String owner, String methodName, String desc)
    parameters:
    - id: reportExecutionTime
      type: 4fc6e284
    - id: api
      type: f75371fa
    - id: methodVisitor
      type: dd525b3c
    - id: access
      type: f75371fa
    - id: owner
      type: "26831127"
    - id: methodName
      type: "26831127"
    - id: desc
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.byteCodeForMethodExit(int)
  id: byteCodeForMethodExit(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: byteCodeForMethodExit(int opcode)
  fullName: abstract void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.byteCodeForMethodExit(int opcode)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 180
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected abstract void byteCodeForMethodExit(int opcode)
    parameters:
    - id: opcode
      type: f75371fa
    return:
      type: 5beb11ad
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTop(Type)
  id: duplicateTop(Type)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: duplicateTop(Type type)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.duplicateTop(Type type)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 114
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected void duplicateTop(Type type)
    parameters:
    - id: type
      type: 7727faa1
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.duplicateTopStackToTempVariable(Type)
  id: duplicateTopStackToTempVariable(Type)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: duplicateTopStackToTempVariable(Type typeOfTopElementInStack)
  fullName: TempVar com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.duplicateTopStackToTempVariable(Type typeOfTopElementInStack)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 144
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected TempVar duplicateTopStackToTempVariable(Type typeOfTopElementInStack)
    parameters:
    - id: typeOfTopElementInStack
      type: 7727faa1
    return:
      type: b543022f
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getMethodName()
  id: getMethodName()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: getMethodName()
  fullName: String com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.getMethodName()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 152
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected String getMethodName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.getReturnType()
  id: getReturnType()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: getReturnType()
  fullName: Type com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.getReturnType()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 156
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected Type getReturnType()
    return:
      type: 7727faa1
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.onMethodExit(int)
  id: onMethodExit(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: onMethodExit(int opcode)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.onMethodExit(int opcode)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 86
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected void onMethodExit(int opcode)
    parameters:
    - id: opcode
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.reportExecutionTime()
  id: reportExecutionTime()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: reportExecutionTime
  fullName: final boolean com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.reportExecutionTime
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 66
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected final boolean reportExecutionTime
    return:
      type: 4dda0764
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.translateExitCode(int)
  id: translateExitCode(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: translateExitCode(int opcode)
  fullName: ExitStatus com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.translateExitCode(int opcode)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 160
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected ExitStatus translateExitCode(int opcode)
    parameters:
    - id: opcode
      type: f75371fa
    return:
      type: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitCode()
  id: visitCode()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: visitCode()
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.visitCode()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 69
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public void visitCode()
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.visitMaxs(int,int)
  id: visitMaxs(int,int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  langs:
  - java
  name: visitMaxs(int maxStack, int maxLocals)
  fullName: void com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.visitMaxs(int maxStack, int maxLocals)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 75
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public void visitMaxs(int maxStack, int maxLocals)
    parameters:
    - id: maxStack
      type: f75371fa
    - id: maxLocals
      type: f75371fa
references:
- uid: 4dda0764
  spec.java:
  - name: final boolean
    fullName: final boolean
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: dd525b3c
  spec.java:
  - name: MethodVisitor
    fullName: MethodVisitor
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 7727faa1
  spec.java:
  - name: Type
    fullName: Type
- uid: a19781f8
  spec.java:
  - name: Class<?>
    fullName: Class<?>
- uid: 1355eaf1
  spec.java:
  - name: Object...
    fullName: Object...
- uid: b543022f
  spec.java:
  - name: TempVar
    fullName: TempVar
- uid: 5beb11ad
  spec.java:
  - name: abstract void
    fullName: abstract void
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor.yml
  name: DefaultMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.DefaultMethodVisitor
  type: Class
  summary: >-
    <p>This class is responsible for finding where the method starts and ends.</p>

    <p>When the method starts, the class will inject byte code that will call our code with the class name method name and the arguments, and when the method ends will call again with the method name and the result or exception if there is one, the class will make sure that the original code's behavior is not changed</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class DefaultMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions._exception_method_visitor.yml
  name: ExceptionMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions.ExceptionMethodVisitor
  type: Class
  summary: <p>Created by gupele on 8/1/2016. </p>
  syntax:
    content: public class ExceptionMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  name: AdvancedAdviceAdapter.ExitStatus
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus
  type: Enum
  syntax:
    content: protected enum ExitStatus
