items:
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  id: _agent_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getBuiltInConfiguration()
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getExcludedPrefixes()
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getRequestedClassesToInstrument()
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getSdkPath()
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration.isSelfRegistrationMode()
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  langs:
  - java
  name: AgentConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration
  type: Interface
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
    startLine: 32
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Defines the interface for concrete classes that represent configuration data for the Agent Created by gupele on 5/17/2015. </p>
  syntax:
    content: public interface AgentConfiguration
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getBuiltInConfiguration()
  id: getBuiltInConfiguration()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  langs:
  - java
  name: getBuiltInConfiguration()
  fullName: AgentBuiltInConfiguration com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration.getBuiltInConfiguration()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
    startLine: 34
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentBuiltInConfiguration getBuiltInConfiguration()
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getExcludedPrefixes()
  id: getExcludedPrefixes()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  langs:
  - java
  name: getExcludedPrefixes()
  fullName: Set<String> com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration.getExcludedPrefixes()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
    startLine: 38
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public Set<String> getExcludedPrefixes()
    return:
      type: df32358c
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getRequestedClassesToInstrument()
  id: getRequestedClassesToInstrument()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  langs:
  - java
  name: getRequestedClassesToInstrument()
  fullName: Map<String, ClassInstrumentationData> com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration.getRequestedClassesToInstrument()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
    startLine: 36
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public Map<String, ClassInstrumentationData> getRequestedClassesToInstrument()
    return:
      type: 2108f1f4com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.getSdkPath()
  id: getSdkPath()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  langs:
  - java
  name: getSdkPath()
  fullName: String com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration.getSdkPath()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
    startLine: 42
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public String getSdkPath()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.isSelfRegistrationMode()
  id: isSelfRegistrationMode()
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  langs:
  - java
  name: isSelfRegistrationMode()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration.isSelfRegistrationMode()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java
    startLine: 40
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public boolean isSelfRegistrationMode()
    return:
      type: 4fc6e284
references:
- uid: 2108f1f4com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_dataa08ddfce
  spec.java:
  - name: 'Map<String, '
    fullName: 'Map<String, '
  - uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    name: ClassInstrumentationData
    fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
    href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  - name: '>'
    fullName: '>'
- uid: df32358c
  spec.java:
  - name: Set<String>
    fullName: Set<String>
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_default_impl
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_built_in_configuration.yml
  name: AgentBuiltInConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentBuiltInConfiguration
  type: Class
  summary: <p>Created by gupele on 6/5/2015. </p>
  syntax:
    content: public class AgentBuiltInConfiguration
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
