items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  id: _performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  langs:
  - java
  name: PerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounter.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.perfcounter._performance_counter" data-throw-if-not-resolved="false"></xref> interface.</p>

    <p>Every concrete class should have a unique id and it should be able to collect data send that data using a <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax: &o1
    content: public interface PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounter.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
  id: report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  langs:
  - java
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounter.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: AbstractJmxPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter
  type: Class
  summary: >-
    <p>The class is a base class for JMX performance counters. It knows how to fetch the needed information from JMX and then relies on its derived classes to send the data.</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class AbstractJmxPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_windows_performance_counter.yml
  name: AbstractWindowsPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractWindowsPerformanceCounter
  type: Class
  summary: <p>Created by gupele on 4/29/2015. </p>
  syntax:
    content: public class AbstractWindowsPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  name: JmxPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter
  type: Class
  summary: >-
    <p>A performance counter that sends <xref href="com.microsoft.applicationinsights.telemetry._performance_counter_telemetry" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  name: DeadLockDetectorPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter
  type: Class
  summary: >-
    <p>The class uses the JVM ThreadMXBean to detect threads dead locks A metric with value 0 is sent when there are no blocked threads, otherwise the number of detected blocked threads is sent with a dimension that holds information like thread id and minimal stack traces as trace telemetries</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class DeadLockDetectorPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter.yml
  name: GCPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.GCPerformanceCounter
  type: Class
  summary: >-
    <p>The class reports GC related data</p>

    <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class GCPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter.yml
  name: JvmHeapMemoryUsedPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.JvmHeapMemoryUsedPerformanceCounter
  type: Class
  summary: >-
    <p>The class will create a metric telemetry for capturing the Jvm's heap memory usage</p>

    <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class JvmHeapMemoryUsedPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.jvm.GCPerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.jvm.JvmHeapMemoryUsedPerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsPC.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.jvm.GCPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_jmx_performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: synchronized void com.microsoft.applicationinsights.internal.perfcounter.AbstractJmxPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  summary: <p>The main method. The method will fetch the data and send it. The method will not do anything if there was a major problem accessing the needed counter. </p>
  syntax:
    content: public synchronized void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The telemetry client to send events. </p>
    return:
      type: 5c0b90ca
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.jvm.JvmHeapMemoryUsedPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_p_c.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsPC.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._jmx_performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.JmxPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_as_metric.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterAsMetric.report(TelemetryClient telemetryClient)
  type: Method
  summary: <p>Go through the data that we have and ask for each key its value, and then send using the requested display name. The method might throw an Error if the <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> is not able to properly connect to the native code. </p>
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
      description: <p>The <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref> to use for sending </p>
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: PerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.perfcounter._performance_counter" data-throw-if-not-resolved="false"></xref> interface.</p>

    <p>Every concrete class should have a unique id and it should be able to collect data send that data using a <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax: *o1
