items:
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  id: _session_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  children:
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.COOKIE_NAME()
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.getSessionAcquisitionDate()
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.getSessionId()
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.getSessionRenewalDate()
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.isSessionCookieUpToDate()
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.isSessionExpired(int)
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.SESSION_DEFAULT_EXPIRATION_TIMEOUT_IN_MINUTES()
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.SessionCookie(Cookie)
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie.SessionCookie(String)
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: SessionCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.SessionCookie
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 32
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax: &o1
    content: public class SessionCookie extends Cookie
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.web.internal.cookies._cookie
  inheritedMembers:
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.formatCookie(String[])
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.getCookie(Class<E>,HttpServletRequest,String)
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_DELIMITER()
  - com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_SPLIT_DELIMITER()
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.COOKIE_NAME()
  id: COOKIE_NAME()
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: COOKIE_NAME
  fullName: final String com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.COOKIE_NAME
  type: Field
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 37
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public static final String COOKIE_NAME= "ai_session"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.getSessionAcquisitionDate()
  id: getSessionAcquisitionDate()
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: getSessionAcquisitionDate()
  fullName: Date com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.getSessionAcquisitionDate()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 109
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Gets the session acquisition date. </p>
  syntax:
    content: public Date getSessionAcquisitionDate()
    return:
      type: "12977444"
      description: <p>The session acquisition date. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.getSessionId()
  id: getSessionId()
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: getSessionId()
  fullName: String com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.getSessionId()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 101
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Gets the session id. </p>
  syntax:
    content: public String getSessionId()
    return:
      type: "26831127"
      description: <p>The session id. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.getSessionRenewalDate()
  id: getSessionRenewalDate()
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: getSessionRenewalDate()
  fullName: Date com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.getSessionRenewalDate()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 117
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Gets the session renewal date. </p>
  syntax:
    content: public Date getSessionRenewalDate()
    return:
      type: "12977444"
      description: <p>The session renewal date. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.isSessionCookieUpToDate()
  id: isSessionCookieUpToDate()
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: isSessionCookieUpToDate()
  fullName: boolean com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.isSessionCookieUpToDate()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 142
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Returns a value indicating whether the session cookie is up-to-date. Session cookie is considered up-to-date when the last renewal time is less than { UPDATE_TIMEOUT_IN_MINUTES} minutes. </p>
  syntax:
    content: public boolean isSessionCookieUpToDate()
    return:
      type: 4fc6e284
      description: <p>True if the session cookie up-to-date. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.isSessionExpired(int)
  id: isSessionExpired(int)
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: isSessionExpired(int sessionTimeoutInMinutes)
  fullName: boolean com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.isSessionExpired(int sessionTimeoutInMinutes)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 126
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Determines if the session has expired. </p>
  syntax:
    content: public boolean isSessionExpired(int sessionTimeoutInMinutes)
    parameters:
    - id: sessionTimeoutInMinutes
      type: f75371fa
      description: <p>The session timeout in minutes. </p>
    return:
      type: 4fc6e284
      description: <p>True if the session has expired, false otherwise. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.SESSION_DEFAULT_EXPIRATION_TIMEOUT_IN_MINUTES()
  id: SESSION_DEFAULT_EXPIRATION_TIMEOUT_IN_MINUTES()
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: SESSION_DEFAULT_EXPIRATION_TIMEOUT_IN_MINUTES
  fullName: final int com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.SESSION_DEFAULT_EXPIRATION_TIMEOUT_IN_MINUTES
  type: Field
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 38
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public static final int SESSION_DEFAULT_EXPIRATION_TIMEOUT_IN_MINUTES= 30
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.SessionCookie(Cookie)
  id: SessionCookie(Cookie)
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: SessionCookie(Cookie cookie)
  fullName: com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.SessionCookie(Cookie cookie)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 71
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Constructs new <xref href="com.microsoft.applicationinsights.web.internal.cookies._session_cookie" data-throw-if-not-resolved="false"></xref> object from the given cookie. </p>
  syntax:
    content: public SessionCookie(Cookie cookie)
    parameters:
    - id: cookie
      type: com.microsoft.applicationinsights.web.internal.cookies._cookie
      description: <p>The http servlet cookie. </p>
  exceptions:
  - type: 8a99d4b0
    description: <p>Thrown when the cookie information cannot be parsed. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.SessionCookie(String)
  id: SessionCookie(String)
  parent: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  langs:
  - java
  name: SessionCookie(String sessionId)
  fullName: com.microsoft.applicationinsights.web.internal.cookies.SessionCookie.SessionCookie(String sessionId)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookie.java
    startLine: 79
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Constructs new <xref href="com.microsoft.applicationinsights.web.internal.cookies._session_cookie" data-throw-if-not-resolved="false"></xref> with the given session ID. </p>
  syntax:
    content: public SessionCookie(String sessionId)
    parameters:
    - id: sessionId
      type: "26831127"
      description: <p>The session ID. </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: cd225469
  spec.java:
  - name: final int
    fullName: final int
- uid: 8a99d4b0
  spec.java:
  - name: Exception
    fullName: Exception
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "12977444"
  spec.java:
  - name: Date
    fullName: Date
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.formatCookie(String[])
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: formatCookie(String[] values)
  fullName: static String com.microsoft.applicationinsights.web.internal.cookies.Cookie.formatCookie(String[] values)
  type: Method
  summary: <p>Formats the given values to a session cookie value. </p>
  syntax:
    content: public static String formatCookie(String[] values)
    parameters:
    - id: values
      type: 30d59cf1
      description: <p>The values to format. </p>
    return:
      type: "26831127"
      description: <p>Formatted session cookie. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.getCookie(Class<E>,HttpServletRequest,String)
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: getCookie(Class<E> eClass, HttpServletRequest request, String cookieName)
  fullName: static <E> E com.microsoft.applicationinsights.web.internal.cookies.Cookie.getCookie(Class<E> eClass, HttpServletRequest request, String cookieName)
  type: Method
  summary: <p>Gets the cookie from the given http request. </p>
  syntax:
    content: public static static<E> E getCookie(Class<E> eClass, HttpServletRequest request, String cookieName)
    parameters:
    - id: eClass
      type: df766fea
      description: <p>The required cookie type. </p>
    - id: request
      type: 81123e1c
      description: <p>THe http request to get the cookies from. </p>
    - id: cookieName
      type: "26831127"
      description: <p>The cookie name. </p>
    return:
      type: 678f8414
      description: >-
        <p>

          <xref href="com.microsoft.applicationinsights.web.internal.cookies._cookie" data-throw-if-not-resolved="false"></xref> from the required type. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_DELIMITER()
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: RAW_COOKIE_DELIMITER
  fullName: final String com.microsoft.applicationinsights.web.internal.cookies.Cookie.RAW_COOKIE_DELIMITER
  type: Field
  syntax:
    content: protected static final String RAW_COOKIE_DELIMITER= "|"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie.RAW_COOKIE_SPLIT_DELIMITER()
  parent: com.microsoft.applicationinsights.web.internal.cookies._cookie
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: RAW_COOKIE_SPLIT_DELIMITER
  fullName: final String com.microsoft.applicationinsights.web.internal.cookies.Cookie.RAW_COOKIE_SPLIT_DELIMITER
  type: Field
  syntax:
    content: protected static final String RAW_COOKIE_SPLIT_DELIMITER= "\\" + RAW_COOKIE_DELIMITER
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: Cookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.Cookie
  type: Class
  summary: >-
    <p>Created by yonisha on 2/9/2015.</p>

    <p>Used as a base class for AI cookies. </p>
  syntax:
    content: public class Cookie
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  name: SessionCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.SessionCookie
  type: Class
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax: *o1
