items:
- uid: com.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6
  id: _definiti552d01008ad9ba2cf5a6833993b6adf6
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 313
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to continue adding more HTTP listeners, or start specifying backends. </p>
  syntax:
    content: public interface WithHttpListenerOrBackend extends ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithBackend
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.defineBackend(String)
  - com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.defineFrontendHttpListener(String)
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendFqdn(String)
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendFqdn(String,String)
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendIpAddress(String)
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendIpAddress(String,String)
references:
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.defineBackend(String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.yml
  name: defineBackend(String name)
  fullName: ApplicationGatewayBackend.DefinitionStages.Blank<WithBackendOrHttpConfig> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackend.defineBackend(String name)
  type: Method
  summary: <p>Begins the definition of a new application gateway backend to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayBackend.DefinitionStages.Blank<WithBackendOrHttpConfig> defineBackend(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the backend </p>
    return:
      type: 51cffc72com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333aa08ddfce
      description: <p>the first stage of the backend definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.defineFrontendHttpListener(String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
  href: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.yml
  name: defineFrontendHttpListener(String name)
  fullName: ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<WithHttpListenerOrBackend> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListener.defineFrontendHttpListener(String name)
  type: Method
  summary: <p>Begins the definition of a new application gateway HTTP listener to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<WithHttpListenerOrBackend> defineFrontendHttpListener(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the HTTP listener </p>
    return:
      type: 742b6bbecom.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6a08ddfce
      description: <p>the first stage of the HTTP listener definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendFqdn(String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.yml
  name: withBackendFqdn(String fqdn)
  fullName: WithBackendOrHttpConfig com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackend.withBackendFqdn(String fqdn)
  type: Method
  summary: >-
    <p>Adds an FQDN (fully qualified domain name) to the default backend. </p>

    <p>A backend with the name "default" will be created if needed. </p>
  syntax:
    content: public WithBackendOrHttpConfig withBackendFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>a fully qualified domain name </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333a
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendFqdn(String,String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.yml
  name: withBackendFqdn(String fqdn, String backendName)
  fullName: WithBackendOrHttpConfig com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackend.withBackendFqdn(String fqdn, String backendName)
  type: Method
  summary: <p>Adds an FQDN (fully qualified domain name) to a backend. </p>
  syntax:
    content: public WithBackendOrHttpConfig withBackendFqdn(String fqdn, String backendName)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>a fully qualified domain name </p>
    - id: backendName
      type: "26831127"
      description: <p>the name for the backend to add the FQDN to </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333a
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendIpAddress(String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.yml
  name: withBackendIpAddress(String ipAddress)
  fullName: WithBackendOrHttpConfig com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackend.withBackendIpAddress(String ipAddress)
  type: Method
  summary: >-
    <p>Adds an IP address to the default backend. </p>

    <p>A backend with the name "default" will be created if needed. </p>
  syntax:
    content: public WithBackendOrHttpConfig withBackendIpAddress(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>an IP address </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333a
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.withBackendIpAddress(String,String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.yml
  name: withBackendIpAddress(String ipAddress, String backendName)
  fullName: WithBackendOrHttpConfig com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackend.withBackendIpAddress(String ipAddress, String backendName)
  type: Method
  summary: <p>Adds an IP address to a backend. </p>
  syntax:
    content: public WithBackendOrHttpConfig withBackendIpAddress(String ipAddress, String backendName)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>an IP address </p>
    - id: backendName
      type: "26831127"
      description: <p>the name for the backend to add the address to </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definitif0af5b23c68232920e970c0392df333a
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.yml
  name: ApplicationGateway.DefinitionStages.WithHttpListener
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListener
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add an HTTP listener. </p>
  syntax:
    content: public interface WithHttpListener
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_backend.yml
  name: ApplicationGateway.DefinitionStages.WithBackend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithBackend
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add a backend. </p>
  syntax:
    content: public interface WithBackend
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
