items:
- uid: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
  id: _definiti3cd481bd079053018ee32855be0e1e53
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.defineFrontendHttpListener(String)
  href: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithHttpListener
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListener
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 196
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to add an HTTP listener. </p>
  syntax:
    content: public interface WithHttpListener
- uid: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.defineFrontendHttpListener(String)
  id: defineFrontendHttpListener(String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53
  href: com.microsoft.azure.management.network._application_gateway._definiti3cd481bd079053018ee32855be0e1e53.yml
  langs:
  - java
  name: defineFrontendHttpListener(String name)
  fullName: ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<WithHttpListenerOrBackend> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListener.defineFrontendHttpListener(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 202
  package: com.microsoft.azure.management.network
  summary: <p>Begins the definition of a new application gateway HTTP listener to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<WithHttpListenerOrBackend> defineFrontendHttpListener(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the HTTP listener </p>
    return:
      type: 742b6bbecom.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6a08ddfce
      description: <p>the first stage of the HTTP listener definition </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 742b6bbecom.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6a08ddfce
  spec.java:
  - name: ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<
    fullName: ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<
  - uid: com.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6
    name: ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend
    fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend
    href: com.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
- uid: com.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti552d01008ad9ba2cf5a6833993b6adf6.yml
  name: ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to continue adding more HTTP listeners, or start specifying backends. </p>
  syntax:
    content: public interface WithHttpListenerOrBackend
