items:
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry
  id: _exception_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.additionalSanitize()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.ExceptionTelemetry(Throwable)
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.ExceptionTelemetry(Throwable,int)
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getData()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getException()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getExceptionHandledAt()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getExceptions()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getMetrics()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getSamplingPercentage()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getSeverityLevel()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.getThrowable()
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.setException(Throwable)
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.setException(Throwable,int)
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.setExceptionHandledAt(ExceptionHandledAt)
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.setSamplingPercentage(Double)
  - com.microsoft.applicationinsights.telemetry._exception_telemetry.setSeverityLevel(SeverityLevel)
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: ExceptionTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionTelemetry
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 37
  package: com.microsoft.applicationinsights.telemetry
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track exceptions. </p>
  syntax:
    content: public class ExceptionTelemetry extends BaseSampleSourceTelemetry<ExceptionData>
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  inheritedMembers:
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.reset()
  - com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.setSampleRate(Envelope)
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.additionalSanitize()
  id: additionalSanitize()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: additionalSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.additionalSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 127
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected void additionalSanitize()
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.ExceptionTelemetry(Throwable)
  id: ExceptionTelemetry(Throwable)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: ExceptionTelemetry(Throwable exception)
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.ExceptionTelemetry(Throwable exception)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 63
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Initializes a new instance. </p>
  syntax:
    content: public ExceptionTelemetry(Throwable exception)
    parameters:
    - id: exception
      type: a04fafd7
      description: <p>The exception to track. </p>
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.ExceptionTelemetry(Throwable,int)
  id: ExceptionTelemetry(Throwable,int)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: ExceptionTelemetry(Throwable exception, int stackSize)
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.ExceptionTelemetry(Throwable exception, int stackSize)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 54
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Initializes a new instance. </p>
  syntax:
    content: public ExceptionTelemetry(Throwable exception, int stackSize)
    parameters:
    - id: exception
      type: a04fafd7
      description: <p>The exception to track. </p>
    - id: stackSize
      type: f75371fa
      description: <p>The max stack size to report. </p>
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getData()
  id: getData()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getData()
  fullName: ExceptionData com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getData()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 132
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected ExceptionData getData()
    return:
      type: a62d6bda
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getException()
  id: getException()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getException()
  fullName: Exception com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getException()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 67
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Exception getException()
    return:
      type: 8a99d4b0
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getExceptionHandledAt()
  id: getExceptionHandledAt()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getExceptionHandledAt()
  fullName: ExceptionHandledAt com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getExceptionHandledAt()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 88
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets the value indicated where the exception was handled. </p>
  syntax:
    content: public ExceptionHandledAt getExceptionHandledAt()
    return:
      type: com.microsoft.applicationinsights.telemetry._exception_handled_at
      description: <p>The value indicating the exception </p>
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getExceptions()
  id: getExceptions()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getExceptions()
  fullName: List<ExceptionDetails> com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getExceptions()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 136
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: protected List<ExceptionDetails> getExceptions()
    return:
      type: fa3a2db9
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getMetrics()
  id: getMetrics()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getMetrics()
  fullName: ConcurrentMap<String,Double> com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getMetrics()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 104
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Gets a map of application-defined exception metrics. </p>
  syntax:
    content: public ConcurrentMap<String, Double> getMetrics()
    return:
      type: 5f392589
      description: <p>The map of metrics </p>
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getSamplingPercentage()
  id: getSamplingPercentage()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getSamplingPercentage()
  fullName: Double com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getSamplingPercentage()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 117
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Double getSamplingPercentage()
    return:
      type: 8dd309d9
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getSeverityLevel()
  id: getSeverityLevel()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getSeverityLevel()
  fullName: SeverityLevel com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 112
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public SeverityLevel getSeverityLevel()
    return:
      type: com.microsoft.applicationinsights.telemetry._severity_level
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.getThrowable()
  id: getThrowable()
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: getThrowable()
  fullName: Throwable com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.getThrowable()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 71
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public Throwable getThrowable()
    return:
      type: a04fafd7
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.setException(Throwable)
  id: setException(Throwable)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: setException(Throwable throwable)
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.setException(Throwable throwable)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 75
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setException(Throwable throwable)
    parameters:
    - id: throwable
      type: a04fafd7
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.setException(Throwable,int)
  id: setException(Throwable,int)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: setException(Throwable throwable, int stackSize)
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.setException(Throwable throwable, int stackSize)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 79
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setException(Throwable throwable, int stackSize)
    parameters:
    - id: throwable
      type: a04fafd7
    - id: stackSize
      type: f75371fa
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.setExceptionHandledAt(ExceptionHandledAt)
  id: setExceptionHandledAt(ExceptionHandledAt)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: setExceptionHandledAt(ExceptionHandledAt value)
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.setExceptionHandledAt(ExceptionHandledAt value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 96
  package: com.microsoft.applicationinsights.telemetry
  summary: <p>Sets the value indicated where the exception was handled. </p>
  syntax:
    content: public void setExceptionHandledAt(ExceptionHandledAt value)
    parameters:
    - id: value
      type: com.microsoft.applicationinsights.telemetry._exception_handled_at
      description: <p>The value indicating the exception </p>
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.setSamplingPercentage(Double)
  id: setSamplingPercentage(Double)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: setSamplingPercentage(Double samplingPercentage)
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.setSamplingPercentage(Double samplingPercentage)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 122
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setSamplingPercentage(Double samplingPercentage)
    parameters:
    - id: samplingPercentage
      type: 8dd309d9
- uid: com.microsoft.applicationinsights.telemetry._exception_telemetry.setSeverityLevel(SeverityLevel)
  id: setSeverityLevel(SeverityLevel)
  parent: com.microsoft.applicationinsights.telemetry._exception_telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_telemetry.yml
  langs:
  - java
  name: setSeverityLevel(SeverityLevel severityLevel)
  fullName: void com.microsoft.applicationinsights.telemetry.ExceptionTelemetry.setSeverityLevel(SeverityLevel severityLevel)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java
    startLine: 108
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void setSeverityLevel(SeverityLevel severityLevel)
    parameters:
    - id: severityLevel
      type: com.microsoft.applicationinsights.telemetry._severity_level
references:
- uid: a04fafd7
  spec.java:
  - name: Throwable
    fullName: Throwable
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 8a99d4b0
  spec.java:
  - name: Exception
    fullName: Exception
- uid: 5f392589
  spec.java:
  - name: ConcurrentMap<String, Double>
    fullName: ConcurrentMap<String, Double>
- uid: 8dd309d9
  spec.java:
  - name: Double
    fullName: Double
- uid: a62d6bda
  spec.java:
  - name: ExceptionData
    fullName: ExceptionData
- uid: fa3a2db9
  spec.java:
  - name: List<ExceptionDetails>
    fullName: List<ExceptionDetails>
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.reset()
  parent: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: reset()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T extends SendableData>.reset()
  type: Method
  syntax:
    content: public void reset()
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.setSampleRate(Envelope)
  parent: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: setSampleRate(Envelope envelope)
  fullName: void com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T extends SendableData>.setSampleRate(Envelope envelope)
  type: Method
  syntax:
    content: protected void setSampleRate(Envelope envelope)
    parameters:
    - id: envelope
      type: ec5c4d5a
- uid: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._base_sample_source_telemetry.yml
  name: BaseSampleSourceTelemetry<T>
  fullName: com.microsoft.applicationinsights.telemetry.BaseSampleSourceTelemetry<T>
  type: Class
  summary: <p>Created by gupele on 12/4/2016. </p>
  syntax:
    content: public class BaseSampleSourceTelemetry<T extends SendableData> extends BaseTelemetry<T> implements SupportSampling
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.applicationinsights.telemetry._exception_handled_at
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._exception_handled_at.yml
  name: ExceptionHandledAt
  fullName: com.microsoft.applicationinsights.telemetry.ExceptionHandledAt
  type: Enum
  summary: <p>This enumeration is used by <xref href="com.microsoft.applicationinsights.telemetry._exception_telemetry" data-throw-if-not-resolved="false"></xref> to identify if and where exception was handled. </p>
  syntax:
    content: public enum ExceptionHandledAt
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
