items:
- uid: com.microsoft.applicationinsights.collectd
  id: collectd
  children:
  - com.microsoft.applicationinsights.collectd._application_insights_writer
  href: com.microsoft.applicationinsights.collectd.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.collectd
  fullName: com.microsoft.applicationinsights.collectd
  type: Namespace
  source:
    remote:
      path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
    startLine: 21
  syntax:
    content: namespace collectd
references:
- uid: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal.yml
  name: com.microsoft.applicationinsights.collectd.internal
  fullName: com.microsoft.applicationinsights.collectd.internal
  type: Namespace
  syntax:
    content: namespace internal
- uid: com.microsoft.applicationinsights.collectd._application_insights_writer
  parent: com.microsoft.applicationinsights.collectd
  href: com.microsoft.applicationinsights.collectd._application_insights_writer.yml
  name: ApplicationInsightsWriter
  fullName: com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter
  type: Class
  summary: <p>Created by yonisha on 4/26/2015. </p>
  syntax:
    content: public class ApplicationInsightsWriter
