items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_httpceb6ddd8ba7135b94add62a3c389433b
  id: _application_gateway_backend_httpceb6ddd8ba7135b94add62a3c389433b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_httpceb6ddd8ba7135b94add62a3c389433b.yml
  langs:
  - java
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendHttpConfiguration.java
    startLine: 235
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway backend HTTP configuration allowing to specify the protocol. </p>
  syntax:
    content: public interface WithProtocol<ParentT> extends HasProtocol<ProtocolT>.UpdateDefinitionStages.WithProtocol<WithAttach<ParentT>, ApplicationGatewayProtocol>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway stage to return to </p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.withProtocol(ProtocolT)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.withProtocol(ProtocolT)
  parent: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef
  href: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.yml
  name: withProtocol(ProtocolT protocol)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasProtocol<ProtocolT>.UpdateDefinitionStages.WithProtocol<ReturnT, ProtocolT>.withProtocol(ProtocolT protocol)
  type: Method
  summary: <p>Specifies the transport protocol. </p>
  syntax:
    content: public ReturnT withProtocol(ProtocolT protocol)
    parameters:
    - id: protocol
      type: b528dcf3
      description: <p>a transport protocol </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_protocol._update2d594d02f2d64b37d0cbf2d4701281ef.yml
  name: HasProtocol.UpdateDefinitionStages.WithProtocol<ReturnT,ProtocolT>
  fullName: com.microsoft.azure.management.network.model.HasProtocol.UpdateDefinitionStages.WithProtocol<ReturnT,ProtocolT>
  type: Interface
  summary: <p>The stage of a definition allowing to specify the protocol. </p>
  syntax:
    content: public interface WithProtocol<ReturnT,ProtocolT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
    - type: b528dcf3
      description: <p>the protocol type of the value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_http5bc3a0a2793d2e48d5bebe389a1d6b2b.yml
  name: ApplicationGatewayBackendHttpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendHttpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway backend HTTP configuration definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithPort<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithAffinity<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithProtocol<ParentT>,ApplicationGatewayBackendHttpConfiguration.UpdateDefinitionStages.WithRequestTimeout<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
