items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql
  id: sql
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_data_provider
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  - com.microsoft.applicationinsights.agent.internal.agent.sql._query_statf8bdcd6fd9c2c538ec6be684eeb659cd
  - com.microsoft.applicationinsights.agent.internal.agent.sql._statement_class_data_data_provider
  href: com.microsoft.applicationinsights.agent.internal.agent.sql.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.agent.sql
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementByteCodeTransformer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementByteCodeTransformer.java
    startLine: 21
  syntax:
    content: namespace sql
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.yml
  name: PreparedStatementByteCodeTransformer
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementByteCodeTransformer
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementByteCodeTransformer implements ByteCodeTransformer
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_data_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_data_provider.yml
  name: PreparedStatementClassDataProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassDataProvider
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementClassDataProvider
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.yml
  name: PreparedStatementClassVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassVisitor
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementClassVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  name: PreparedStatementMetaData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementMetaData implements ClassToMethodTransformationData
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._query_statf8bdcd6fd9c2c538ec6be684eeb659cd
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._query_statf8bdcd6fd9c2c538ec6be684eeb659cd.yml
  name: QueryStatementWithPossibleExplainMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.QueryStatementWithPossibleExplainMethodVisitor
  type: Class
  summary: <p>Created by gupele on 8/4/2015. </p>
  syntax:
    content: public class QueryStatementWithPossibleExplainMethodVisitor extends DefaultMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._statement_class_data_data_provider
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._statement_class_data_data_provider.yml
  name: StatementClassDataDataProvider
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.StatementClassDataDataProvider
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class StatementClassDataDataProvider
