items:
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  id: _git_build_info_context_initializer
  parent: com.microsoft.applicationinsights.sample.plugins
  children:
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GitBuildInfoContextInitializer()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.initialize(TelemetryContext)
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.yml
  langs:
  - java
  name: GitBuildInfoContextInitializer
  fullName: com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer
  type: Class
  source:
    remote: &o0
      path: samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
    startLine: 38
  package: com.microsoft.applicationinsights.sample.plugins
  summary: '<p>An initializer to fetch Git data from a properties file Note: the file with its full package name should appear in the ''ApplicationInsights.xml'': <programlisting><codeline><highlight class="normal">&lt;ContextInitializers&gt;</highlight></codeline><codeline><highlight class="normal"><sp></sp><sp></sp>&lt;Add<sp></sp>type="com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer"<sp></sp>/&gt;</highlight></codeline><codeline><highlight class="normal">&lt;/ContextInitializers&gt;</highlight></codeline></programlisting></p>'
  syntax:
    content: public class GitBuildInfoContextInitializer implements ContextInitializer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._context_initializer
  inheritedMembers:
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_BRANCH_KEY()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_COMMIT_KEY()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_COMMIT_URL_KEY()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_COMMIT_URL_PART()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_REPO_KEY()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_REPO_SUFFIX()
  - com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.UNKNOWN_SOURCE_VALUE()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GitBuildInfoContextInitializer()
  id: GitBuildInfoContextInitializer()
  parent: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.yml
  langs:
  - java
  name: GitBuildInfoContextInitializer()
  fullName: com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer.GitBuildInfoContextInitializer()
  type: Constructor
  source:
    remote: *o0
    path: samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
    startLine: 57
  package: com.microsoft.applicationinsights.sample.plugins
  syntax:
    content: public GitBuildInfoContextInitializer()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.initialize(TelemetryContext)
  id: initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer
  href: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.yml
  langs:
  - java
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.sample.plugins.GitBuildInfoContextInitializer.initialize(TelemetryContext context)
  type: Method
  source:
    remote: *o0
    path: samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
    startLine: 89
  package: com.microsoft.applicationinsights.sample.plugins
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
  overridden: com.microsoft.applicationinsights.extensibility._context_initializer.initialize(TelemetryContext)
references:
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_BRANCH_KEY()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_COMMIT_KEY()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_COMMIT_URL_KEY()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_COMMIT_URL_PART()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_REPO_KEY()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.GIT_REPO_SUFFIX()
- uid: com.microsoft.applicationinsights.sample.plugins._git_build_info_context_initializer.UNKNOWN_SOURCE_VALUE()
- uid: com.microsoft.applicationinsights.extensibility._context_initializer
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._context_initializer.yml
  name: ContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.ContextInitializer
  type: Interface
  summary: <p>Represents an object that implements supporting logic for TelemetryContext. <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public interface ContextInitializer
- uid: com.microsoft.applicationinsights.extensibility._context_initializer.initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility._context_initializer
  href: com.microsoft.applicationinsights.extensibility._context_initializer.yml
  name: initialize(TelemetryContext context)
  fullName: void com.microsoft.applicationinsights.extensibility.ContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: <p>Initializes the given TelemetryContext. </p>
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.telemetry._telemetry_context
      description: <p>A TelemetryContext to initialize. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry_context
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry_context.yml
  name: TelemetryContext
  fullName: com.microsoft.applicationinsights.telemetry.TelemetryContext
  type: Class
  summary: <p>Represents a context for sending telemetry to the Application Insights service. </p>
  syntax:
    content: public class TelemetryContext
