items:
- uid: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter
  id: _request_name_handler_interceptor_adapter
  parent: com.microsoft.applicationinsights.web.spring
  children:
  - com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter.preHandle(HttpServletRequest,HttpServletResponse,Object)
  href: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter.yml
  langs:
  - java
  name: RequestNameHandlerInterceptorAdapter
  fullName: com.microsoft.applicationinsights.web.spring.RequestNameHandlerInterceptorAdapter
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/spring/RequestNameHandlerInterceptorAdapter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/spring/RequestNameHandlerInterceptorAdapter.java
    startLine: 39
  package: com.microsoft.applicationinsights.web.spring
  summary: >-
    <p>Created by yonisha on 3/1/2015.</p>

    <p>This class intercepts all requests before forwarded to the relevant handler. It extracts the relevant controller and method names and updates the request telemetry name. This class should never throw exceptions to avoid blocking request processing. </p>
  syntax:
    content: public class RequestNameHandlerInterceptorAdapter
  inheritance:
  - java.lang.Object
  - HandlerInterceptorAdapter
- uid: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter.preHandle(HttpServletRequest,HttpServletResponse,Object)
  id: preHandle(HttpServletRequest,HttpServletResponse,Object)
  parent: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter
  href: com.microsoft.applicationinsights.web.spring._request_name_handler_interceptor_adapter.yml
  langs:
  - java
  name: preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
  fullName: boolean com.microsoft.applicationinsights.web.spring.RequestNameHandlerInterceptorAdapter.preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/spring/RequestNameHandlerInterceptorAdapter.java
    startLine: 48
  package: com.microsoft.applicationinsights.web.spring
  summary: <p>This method is being invoked just before the request is forwarded the the relevant controller. It should always return true, so the request will be processed in any case of failure. </p>
  syntax:
    content: public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
    parameters:
    - id: request
      type: 81123e1c
    - id: response
      type: 4fb6a380
    - id: handler
      type: "79317049"
    return:
      type: 4fc6e284
references:
- uid: 81123e1c
  spec.java:
  - name: HttpServletRequest
    fullName: HttpServletRequest
- uid: 4fb6a380
  spec.java:
  - name: HttpServletResponse
    fullName: HttpServletResponse
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
