items:
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  id: _windows_performance_counter_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getCategoryName()
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getCounterName()
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getDisplayName()
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getInstanceName()
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setCategoryName(String)
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setCounterName(String)
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setDisplayName(String)
  - com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setInstanceName(String)
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: WindowsPerformanceCounterXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getCategoryName()
  id: getCategoryName()
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: getCategoryName()
  fullName: String com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.getCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getCategoryName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getCounterName()
  id: getCounterName()
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: getCounterName()
  fullName: String com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.getCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getCounterName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getDisplayName()
  id: getDisplayName()
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: getDisplayName()
  fullName: String com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.getDisplayName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getDisplayName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.getInstanceName()
  id: getInstanceName()
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: getInstanceName()
  fullName: String com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.getInstanceName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getInstanceName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setCategoryName(String)
  id: setCategoryName(String)
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: setCategoryName(String categoryName)
  fullName: void com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.setCategoryName(String categoryName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setCategoryName(String categoryName)
    parameters:
    - id: categoryName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setCounterName(String)
  id: setCounterName(String)
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: setCounterName(String counterName)
  fullName: void com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.setCounterName(String counterName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setCounterName(String counterName)
    parameters:
    - id: counterName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setDisplayName(String)
  id: setDisplayName(String)
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: setDisplayName(String displayName)
  fullName: void com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.setDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.setInstanceName(String)
  id: setInstanceName(String)
  parent: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element
  href: com.microsoft.applicationinsights.internal.config._windows_performance_counter_xml_element.yml
  langs:
  - java
  name: setInstanceName(String instanceName)
  fullName: void com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement.setInstanceName(String instanceName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setInstanceName(String instanceName)
    parameters:
    - id: instanceName
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
