items:
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess
  id: inprocess
  children:
  - com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  href: com.microsoft.applicationinsights.channel.concrete.inprocess.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.channel.concrete.inprocess
  fullName: com.microsoft.applicationinsights.channel.concrete.inprocess
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/channel/concrete/inprocess/InProcessTelemetryChannel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/channel/concrete/inprocess/InProcessTelemetryChannel.java
    startLine: 21
  syntax:
    content: namespace inprocess
references:
- uid: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel
  parent: com.microsoft.applicationinsights.channel.concrete.inprocess
  href: com.microsoft.applicationinsights.channel.concrete.inprocess._in_process_telemetry_channel.yml
  name: InProcessTelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel
  type: Class
  summary: >-
    <p>An implementation of <xref href="com.microsoft.applicationinsights.channel._telemetry_channel" data-throw-if-not-resolved="false"></xref></p>

    <p>The channel holds two main entities:</p>

    <p>A buffer for incoming <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances A transmitter</p>

    <p>The buffer is stores incoming telemetry instances. Every new buffer starts a timer. When the timer expires, or when the buffer is 'full' (whichever happens first), the transmitter will pick up that buffer and will handle its sending to the server. For example, a transmitter will be responsible for compressing, sending and activate a policy in case of failures.</p>

    <p>The model here is:</p>

    <p>Use application threads to populate the buffer Use channel's threads to send buffers to the server</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class InProcessTelemetryChannel implements TelemetryChannel
