items:
- uid: com.microsoft.azure.management.network._application_gateway_private_frontend._update_stages
  id: _update_stages
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_frontend._update_stages.yml
  langs:
  - java
  name: ApplicationGatewayPrivateFrontend.UpdateStages
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.UpdateStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
    startLine: 72
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of private frontend update stages. </p>
  syntax:
    content: public interface UpdateStages
references: []
