items:
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  id: _page_view_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testCtor()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testEmptyCtor()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testSetDuration()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testSetName()
  - com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testSetUri()
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  langs:
  - java
  name: PageViewTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class PageViewTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testCtor()
  id: testCtor()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  langs:
  - java
  name: testCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest.testCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtor()
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testEmptyCtor()
  id: testEmptyCtor()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  langs:
  - java
  name: testEmptyCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest.testEmptyCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyCtor()
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testSetDuration()
  id: testSetDuration()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  langs:
  - java
  name: testSetDuration()
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest.testSetDuration()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
    startLine: 66
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetDuration()
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testSetName()
  id: testSetName()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  langs:
  - java
  name: testSetName()
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest.testSetName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
    startLine: 58
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetName()
- uid: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.testSetUri()
  id: testSetUri()
  parent: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._page_view_telemetry_test.yml
  langs:
  - java
  name: testSetUri()
  fullName: void com.microsoft.applicationinsights.telemetry.PageViewTelemetryTest.testSetUri()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetryTest.java
    startLine: 74
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetUri()
references: []
