items:
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer
  id: _limits_enforcer
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithClosestLimitOnError(int,int,int,String,String)
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithClosestLimitOnError(String,int,int,int,Integer)
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithDefaultOnError(int,int,int,String,String)
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithDefaultOnError(String,int,int,int,Integer)
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.getCurrentValue()
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.getDefaultValue()
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.getMaximum()
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.getMinimum()
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.getType()
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.normalizeStringValue(String)
  - com.microsoft.applicationinsights.internal.util._limits_enforcer.normalizeValue(Integer)
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: LimitsEnforcer
  fullName: com.microsoft.applicationinsights.internal.util.LimitsEnforcer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 9
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by gupele on 5/10/2015. </p>
  syntax: &o1
    content: public class LimitsEnforcer
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithClosestLimitOnError(int,int,int,String,String)
  id: createWithClosestLimitOnError(int,int,int,String,String)
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: createWithClosestLimitOnError(int minimum, int maximum, int defaultValue, String propertyName, String currentValue)
  fullName: static LimitsEnforcer com.microsoft.applicationinsights.internal.util.LimitsEnforcer.createWithClosestLimitOnError(int minimum, int maximum, int defaultValue, String propertyName, String currentValue)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 110
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static LimitsEnforcer createWithClosestLimitOnError(int minimum, int maximum, int defaultValue, String propertyName, String currentValue)
    parameters:
    - id: minimum
      type: f75371fa
    - id: maximum
      type: f75371fa
    - id: defaultValue
      type: f75371fa
    - id: propertyName
      type: "26831127"
    - id: currentValue
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.internal.util._limits_enforcer
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithClosestLimitOnError(String,int,int,int,Integer)
  id: createWithClosestLimitOnError(String,int,int,int,Integer)
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: createWithClosestLimitOnError(String propertyName, int minimum, int maximum, int defaultValue, Integer currentValue)
  fullName: static LimitsEnforcer com.microsoft.applicationinsights.internal.util.LimitsEnforcer.createWithClosestLimitOnError(String propertyName, int minimum, int maximum, int defaultValue, Integer currentValue)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 106
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static LimitsEnforcer createWithClosestLimitOnError(String propertyName, int minimum, int maximum, int defaultValue, Integer currentValue)
    parameters:
    - id: propertyName
      type: "26831127"
    - id: minimum
      type: f75371fa
    - id: maximum
      type: f75371fa
    - id: defaultValue
      type: f75371fa
    - id: currentValue
      type: 08effaa0
    return:
      type: com.microsoft.applicationinsights.internal.util._limits_enforcer
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithDefaultOnError(int,int,int,String,String)
  id: createWithDefaultOnError(int,int,int,String,String)
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: createWithDefaultOnError(int minimum, int maximum, int defaultValue, String propertyName, String currentValue)
  fullName: static LimitsEnforcer com.microsoft.applicationinsights.internal.util.LimitsEnforcer.createWithDefaultOnError(int minimum, int maximum, int defaultValue, String propertyName, String currentValue)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 102
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static LimitsEnforcer createWithDefaultOnError(int minimum, int maximum, int defaultValue, String propertyName, String currentValue)
    parameters:
    - id: minimum
      type: f75371fa
    - id: maximum
      type: f75371fa
    - id: defaultValue
      type: f75371fa
    - id: propertyName
      type: "26831127"
    - id: currentValue
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.internal.util._limits_enforcer
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.createWithDefaultOnError(String,int,int,int,Integer)
  id: createWithDefaultOnError(String,int,int,int,Integer)
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: createWithDefaultOnError(String propertyName, int minimum, int maximum, int defaultValue, Integer currentValue)
  fullName: static LimitsEnforcer com.microsoft.applicationinsights.internal.util.LimitsEnforcer.createWithDefaultOnError(String propertyName, int minimum, int maximum, int defaultValue, Integer currentValue)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 98
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static LimitsEnforcer createWithDefaultOnError(String propertyName, int minimum, int maximum, int defaultValue, Integer currentValue)
    parameters:
    - id: propertyName
      type: "26831127"
    - id: minimum
      type: f75371fa
    - id: maximum
      type: f75371fa
    - id: defaultValue
      type: f75371fa
    - id: currentValue
      type: 08effaa0
    return:
      type: com.microsoft.applicationinsights.internal.util._limits_enforcer
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.getCurrentValue()
  id: getCurrentValue()
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: getCurrentValue()
  fullName: int com.microsoft.applicationinsights.internal.util.LimitsEnforcer.getCurrentValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public int getCurrentValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.getDefaultValue()
  id: getDefaultValue()
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: getDefaultValue()
  fullName: int com.microsoft.applicationinsights.internal.util.LimitsEnforcer.getDefaultValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public int getDefaultValue()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.getMaximum()
  id: getMaximum()
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: getMaximum()
  fullName: int com.microsoft.applicationinsights.internal.util.LimitsEnforcer.getMaximum()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public int getMaximum()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.getMinimum()
  id: getMinimum()
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: getMinimum()
  fullName: int com.microsoft.applicationinsights.internal.util.LimitsEnforcer.getMinimum()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public int getMinimum()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: getType()
  fullName: Type com.microsoft.applicationinsights.internal.util.LimitsEnforcer.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public Type getType()
    return:
      type: 7727faa1
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.normalizeStringValue(String)
  id: normalizeStringValue(String)
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: normalizeStringValue(String value)
  fullName: int com.microsoft.applicationinsights.internal.util.LimitsEnforcer.normalizeStringValue(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 81
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public int normalizeStringValue(String value)
    parameters:
    - id: value
      type: "26831127"
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer.normalizeValue(Integer)
  id: normalizeValue(Integer)
  parent: com.microsoft.applicationinsights.internal.util._limits_enforcer
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  langs:
  - java
  name: normalizeValue(Integer value)
  fullName: int com.microsoft.applicationinsights.internal.util.LimitsEnforcer.normalizeValue(Integer value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public int normalizeValue(Integer value)
    parameters:
    - id: value
      type: 08effaa0
    return:
      type: f75371fa
references:
- uid: 7727faa1
  spec.java:
  - name: Type
    fullName: Type
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  name: LimitsEnforcer
  fullName: com.microsoft.applicationinsights.internal.util.LimitsEnforcer
  type: Class
  summary: <p>Created by gupele on 5/10/2015. </p>
  syntax: *o1
