items:
- uid: com.microsoft.applicationinsights.web.internal.cookies
  id: cookies
  children:
  - com.microsoft.applicationinsights.web.internal.cookies._cookie
  - com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory
  - com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  - com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  href: com.microsoft.applicationinsights.web.internal.cookies.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.internal.cookies
  fullName: com.microsoft.applicationinsights.web.internal.cookies
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/Cookie.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/Cookie.java
    startLine: 21
  syntax:
    content: namespace cookies
references:
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: Cookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.Cookie
  type: Class
  summary: >-
    <p>Created by yonisha on 2/9/2015.</p>

    <p>Used as a base class for AI cookies. </p>
  syntax:
    content: public class Cookie
- uid: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.yml
  name: HttpCookieFactory
  fullName: com.microsoft.applicationinsights.web.internal.cookies.HttpCookieFactory
  type: Class
  summary: <p>Created by yonisha on 2/26/2015. </p>
  syntax:
    content: public class HttpCookieFactory
- uid: com.microsoft.applicationinsights.web.internal.cookies._session_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._session_cookie.yml
  name: SessionCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.SessionCookie
  type: Class
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax:
    content: public class SessionCookie extends Cookie
- uid: com.microsoft.applicationinsights.web.internal.cookies._user_cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._user_cookie.yml
  name: UserCookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.UserCookie
  type: Class
  summary: <p>Created by yonisha on 2/7/2015. </p>
  syntax:
    content: public class UserCookie extends Cookie
