items:
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  id: _base_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._base_telemetry_test.testCtor()
  - com.microsoft.applicationinsights.telemetry._base_telemetry_test.testCtorWithInitialize()
  - com.microsoft.applicationinsights.telemetry._base_telemetry_test.testSanitize()
  - com.microsoft.applicationinsights.telemetry._base_telemetry_test.testSetSequence()
  - com.microsoft.applicationinsights.telemetry._base_telemetry_test.testSetTimestamp()
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  langs:
  - java
  name: BaseTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.BaseTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class BaseTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test.testCtor()
  id: testCtor()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  langs:
  - java
  name: testCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetryTest.testCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
    startLine: 75
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtor()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test.testCtorWithInitialize()
  id: testCtorWithInitialize()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  langs:
  - java
  name: testCtorWithInitialize()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetryTest.testCtorWithInitialize()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
    startLine: 84
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtorWithInitialize()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test.testSanitize()
  id: testSanitize()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  langs:
  - java
  name: testSanitize()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetryTest.testSanitize()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
    startLine: 116
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSanitize()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test.testSetSequence()
  id: testSetSequence()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  langs:
  - java
  name: testSetSequence()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetryTest.testSetSequence()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
    startLine: 96
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetSequence()
- uid: com.microsoft.applicationinsights.telemetry._base_telemetry_test.testSetTimestamp()
  id: testSetTimestamp()
  parent: com.microsoft.applicationinsights.telemetry._base_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._base_telemetry_test.yml
  langs:
  - java
  name: testSetTimestamp()
  fullName: void com.microsoft.applicationinsights.telemetry.BaseTelemetryTest.testSetTimestamp()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
    startLine: 106
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetTimestamp()
references: []
