items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630
  id: interneba8941f347af2daef29342ecf01c630
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.testDockerContextInitializedIfFileExists()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.testIfContextFileNotExistThenPollerTryAgain()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.testInit()
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.yml
  langs:
  - java
  name: DockerContextPollerTests
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPollerTests
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPollerTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPollerTests.java
    startLine: 38
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPollerTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.testDockerContextInitializedIfFileExists()
  id: testDockerContextInitializedIfFileExists()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.yml
  langs:
  - java
  name: testDockerContextInitializedIfFileExists()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPollerTests.testDockerContextInitializedIfFileExists()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPollerTests.java
    startLine: 54
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public void testDockerContextInitializedIfFileExists()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.testIfContextFileNotExistThenPollerTryAgain()
  id: testIfContextFileNotExistThenPollerTryAgain()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.yml
  langs:
  - java
  name: testIfContextFileNotExistThenPollerTryAgain()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPollerTests.testIfContextFileNotExistThenPollerTryAgain()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPollerTests.java
    startLine: 64
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public void testIfContextFileNotExistThenPollerTryAgain()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.testInit()
  id: testInit()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.interneba8941f347af2daef29342ecf01c630.yml
  langs:
  - java
  name: testInit()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPollerTests.testInit()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPollerTests.java
    startLine: 46
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public void testInit()
references:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.yml
  name: DockerContextFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextFactory
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextFactory
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  name: DockerContextPoller
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPoller
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  name: DockerContext
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>Represents the Docker context, which includes the host name, image name, container name and container ID. The Docker context file is written in the following structure: Docker host=host_name,Docker image=image_name,Docker container id=con_id,Docker container name=con_name </p>
  syntax:
    content: public class DockerContext
