items:
- uid: com.microsoft.applicationinsights.internal.schemav2._operation
  id: _operation
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._operation.addToHashMap(HashMap<String, String>)
  - com.microsoft.applicationinsights.internal.schemav2._operation.getId()
  - com.microsoft.applicationinsights.internal.schemav2._operation.getName()
  - com.microsoft.applicationinsights.internal.schemav2._operation.getParentId()
  - com.microsoft.applicationinsights.internal.schemav2._operation.getRootId()
  - com.microsoft.applicationinsights.internal.schemav2._operation.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._operation.Operation()
  - com.microsoft.applicationinsights.internal.schemav2._operation.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._operation.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._operation.setId(String)
  - com.microsoft.applicationinsights.internal.schemav2._operation.setName(String)
  - com.microsoft.applicationinsights.internal.schemav2._operation.setParentId(String)
  - com.microsoft.applicationinsights.internal.schemav2._operation.setRootId(String)
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: Operation
  fullName: com.microsoft.applicationinsights.internal.schemav2.Operation
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._operation" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class Operation implements JsonSerializable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.addToHashMap(HashMap<String, String>)
  id: addToHashMap(HashMap<String, String>)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: addToHashMap(HashMap<String, String> map)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.addToHashMap(HashMap<String, String> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 99
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Adds all members of this class to a hashmap </p>
  syntax:
    content: public void addToHashMap(HashMap<String, String> map)
    parameters:
    - id: map
      type: 3970a053
      description: <p>to which the members of this class will be added. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Operation.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Operation.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.getParentId()
  id: getParentId()
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: getParentId()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Operation.getParentId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getParentId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.getRootId()
  id: getRootId()
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: getRootId()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Operation.getRootId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 87
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getRootId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 129
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.Operation()
  id: Operation()
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: Operation()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Operation.Operation()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public Operation()
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 116
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  exceptions:
  - type: cbf33bbe
    description: <p>The exception that might be thrown during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 122
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.setId(String)
  id: setId(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: setId(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.setId(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 67
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setId(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: setName(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.setName(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setName(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.setParentId(String)
  id: setParentId(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: setParentId(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.setParentId(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setParentId(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation.setRootId(String)
  id: setRootId(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._operation
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  langs:
  - java
  name: setRootId(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Operation.setRootId(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Operation.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setRootId(String value)
    parameters:
    - id: value
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 3970a053
  spec.java:
  - name: HashMap<String, String>
    fullName: HashMap<String, String>
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._operation
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._operation.yml
  name: Operation
  fullName: com.microsoft.applicationinsights.internal.schemav2.Operation
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._operation" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
