items:
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test
  id: _transmission_policy_state_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.testSetCurrentState()
  - com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.testStateAfterCtor()
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.yml
  langs:
  - java
  name: TransmissionPolicyStateTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateTest.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class TransmissionPolicyStateTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.testSetCurrentState()
  id: testSetCurrentState()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.yml
  langs:
  - java
  name: testSetCurrentState()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateTest.testSetCurrentState()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateTest.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testSetCurrentState()
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.testStateAfterCtor()
  id: testStateAfterCtor()
  parent: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test
  href: com.microsoft.applicationinsights.internal.channel.common._transmission_policy_state_test.yml
  langs:
  - java
  name: testStateAfterCtor()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmissionPolicyStateTest.testStateAfterCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyStateTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStateAfterCtor()
references: []
