items:
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container
  id: _web_modules_container
  parent: com.microsoft.applicationinsights.web.internal
  children:
  - com.microsoft.applicationinsights.web.internal._web_modules_container.getModulesCount()
  - com.microsoft.applicationinsights.web.internal._web_modules_container.invokeOnBeginRequest(ServletRequest,ServletResponse)
  - com.microsoft.applicationinsights.web.internal._web_modules_container.invokeOnEndRequest(ServletRequest,ServletResponse)
  - com.microsoft.applicationinsights.web.internal._web_modules_container.WebModulesContainer(TelemetryConfiguration)
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  langs:
  - java
  name: WebModulesContainer
  fullName: com.microsoft.applicationinsights.web.internal.WebModulesContainer
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
    startLine: 36
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Created by yonisha on 2/3/2015. </p>
  syntax: &o1
    content: public class WebModulesContainer
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container.getModulesCount()
  id: getModulesCount()
  parent: com.microsoft.applicationinsights.web.internal._web_modules_container
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  langs:
  - java
  name: getModulesCount()
  fullName: int com.microsoft.applicationinsights.web.internal.WebModulesContainer.getModulesCount()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
    startLine: 85
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets the modules count </p>
  syntax:
    content: public int getModulesCount()
    return:
      type: f75371fa
      description: <p>The modules count </p>
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container.invokeOnBeginRequest(ServletRequest,ServletResponse)
  id: invokeOnBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.internal._web_modules_container
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  langs:
  - java
  name: invokeOnBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.internal.WebModulesContainer.invokeOnBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
    startLine: 54
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Invokes onBeginRequest on each of the telemetry modules </p>
  syntax:
    content: public void invokeOnBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to process </p>
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container.invokeOnEndRequest(ServletRequest,ServletResponse)
  id: invokeOnEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.internal._web_modules_container
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  langs:
  - java
  name: invokeOnEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.internal.WebModulesContainer.invokeOnEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
    startLine: 70
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Invokes onEndRequest on each of the telemetry modules </p>
  syntax:
    content: public void invokeOnEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to process </p>
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container.WebModulesContainer(TelemetryConfiguration)
  id: WebModulesContainer(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.web.internal._web_modules_container
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  langs:
  - java
  name: WebModulesContainer(TelemetryConfiguration configuration)
  fullName: com.microsoft.applicationinsights.web.internal.WebModulesContainer.WebModulesContainer(TelemetryConfiguration configuration)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
    startLine: 44
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Constructs new <xref href="com.microsoft.applicationinsights.web.internal._web_modules_container" data-throw-if-not-resolved="false"></xref> object from the given configuration. </p>
  syntax:
    content: public WebModulesContainer(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to take the web modules from. </p>
references:
- uid: b0deafe7
  spec.java:
  - name: ServletRequest
    fullName: ServletRequest
- uid: 0dcfeead
  spec.java:
  - name: ServletResponse
    fullName: ServletResponse
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  name: WebTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface WebTelemetryModule
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  name: WebModulesContainer
  fullName: com.microsoft.applicationinsights.web.internal.WebModulesContainer
  type: Class
  summary: <p>Created by yonisha on 2/3/2015. </p>
  syntax: *o1
