items:
- uid: com.microsoft.applicationinsights.internal.util._property_helper
  id: _property_helper
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._property_helper.getProperties(String)
  - com.microsoft.applicationinsights.internal.util._property_helper.getSdkVersionProperties()
  - com.microsoft.applicationinsights.internal.util._property_helper.SDK_VERSION_FILE_NAME()
  href: com.microsoft.applicationinsights.internal.util._property_helper.yml
  langs:
  - java
  name: PropertyHelper
  fullName: com.microsoft.applicationinsights.internal.util.PropertyHelper
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/PropertyHelper.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/PropertyHelper.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Helper class for reading data from a properties file found on the class path. </p>
  syntax:
    content: public class PropertyHelper
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._property_helper.getProperties(String)
  id: getProperties(String)
  parent: com.microsoft.applicationinsights.internal.util._property_helper
  href: com.microsoft.applicationinsights.internal.util._property_helper.yml
  langs:
  - java
  name: getProperties(String name)
  fullName: static Properties com.microsoft.applicationinsights.internal.util.PropertyHelper.getProperties(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/PropertyHelper.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Reads the properties from a properties file. </p>
  syntax:
    content: public static Properties getProperties(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>of the properties file. </p>
    return:
      type: 8cd2c29f
      description: <p>A <ref refid="" kindref="compound">Properties</ref> object containing the properties read from the provided file. </p>
  exceptions:
  - type: cbf33bbe
    description: <p>in case </p>
- uid: com.microsoft.applicationinsights.internal.util._property_helper.getSdkVersionProperties()
  id: getSdkVersionProperties()
  parent: com.microsoft.applicationinsights.internal.util._property_helper
  href: com.microsoft.applicationinsights.internal.util._property_helper.yml
  langs:
  - java
  name: getSdkVersionProperties()
  fullName: static Properties com.microsoft.applicationinsights.internal.util.PropertyHelper.getSdkVersionProperties()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/PropertyHelper.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>A method that loads the properties file that contains SDK-Version data. </p>
  syntax:
    content: public static Properties getSdkVersionProperties()
    return:
      type: 8cd2c29f
      description: <p>The properties or null if not found. </p>
- uid: com.microsoft.applicationinsights.internal.util._property_helper.SDK_VERSION_FILE_NAME()
  id: SDK_VERSION_FILE_NAME()
  parent: com.microsoft.applicationinsights.internal.util._property_helper
  href: com.microsoft.applicationinsights.internal.util._property_helper.yml
  langs:
  - java
  name: SDK_VERSION_FILE_NAME
  fullName: final String com.microsoft.applicationinsights.internal.util.PropertyHelper.SDK_VERSION_FILE_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/PropertyHelper.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static final String SDK_VERSION_FILE_NAME= "sdk-version.properties"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 8cd2c29f
  spec.java:
  - name: Properties
    fullName: Properties
