items:
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event
  id: _application_insights_event
  parent: com.microsoft.applicationinsights.internal.common
  children:
  - com.microsoft.applicationinsights.internal.common._application_insights_event.addLogEventProperty(String,String,Map<String, String>)
  - com.microsoft.applicationinsights.internal.common._application_insights_event.getCustomParameters()
  - com.microsoft.applicationinsights.internal.common._application_insights_event.getException()
  - com.microsoft.applicationinsights.internal.common._application_insights_event.getFormattedDate(long)
  - com.microsoft.applicationinsights.internal.common._application_insights_event.getMessage()
  - com.microsoft.applicationinsights.internal.common._application_insights_event.getNormalizedSeverityLevel()
  - com.microsoft.applicationinsights.internal.common._application_insights_event.isException()
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: ApplicationInsightsEvent
  fullName: com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent
  type: Class
  source:
    remote: &o0
      path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.common
  summary: <p>Interface for </p>
  syntax:
    content: public class ApplicationInsightsEvent
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.addLogEventProperty(String,String,Map<String, String>)
  id: addLogEventProperty(String,String,Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: addLogEventProperty(String key, String value, Map<String, String> metaData)
  fullName: static void com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.addLogEventProperty(String key, String value, Map<String, String> metaData)
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: protected static void addLogEventProperty(String key, String value, Map<String, String> metaData)
    parameters:
    - id: key
      type: "26831127"
    - id: value
      type: "26831127"
    - id: metaData
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.getCustomParameters()
  id: getCustomParameters()
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: getCustomParameters()
  fullName: abstract Map<String, String> com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.getCustomParameters()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: public abstract Map<String, String> getCustomParameters()
    return:
      type: 7193d977
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.getException()
  id: getException()
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: getException()
  fullName: abstract Exception com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.getException()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: public abstract Exception getException()
    return:
      type: bc380358
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.getFormattedDate(long)
  id: getFormattedDate(long)
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: getFormattedDate(long dateInMilliseconds)
  fullName: static String com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.getFormattedDate(long dateInMilliseconds)
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: protected static String getFormattedDate(long dateInMilliseconds)
    parameters:
    - id: dateInMilliseconds
      type: 0364520f
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.getMessage()
  id: getMessage()
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: getMessage()
  fullName: abstract String com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.getMessage()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: public abstract String getMessage()
    return:
      type: 9065866d
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.getNormalizedSeverityLevel()
  id: getNormalizedSeverityLevel()
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: getNormalizedSeverityLevel()
  fullName: abstract SeverityLevel com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.getNormalizedSeverityLevel()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: public abstract SeverityLevel getNormalizedSeverityLevel()
    return:
      type: 13c86962com.microsoft.applicationinsights.telemetry._severity_level
- uid: com.microsoft.applicationinsights.internal.common._application_insights_event.isException()
  id: isException()
  parent: com.microsoft.applicationinsights.internal.common._application_insights_event
  href: com.microsoft.applicationinsights.internal.common._application_insights_event.yml
  langs:
  - java
  name: isException()
  fullName: abstract boolean com.microsoft.applicationinsights.internal.common.ApplicationInsightsEvent.isException()
  type: Method
  source:
    remote: *o0
    path: logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/ApplicationInsightsEvent.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.common
  syntax:
    content: public abstract boolean isException()
    return:
      type: 352efe7b
references:
- uid: 9065866d
  spec.java:
  - name: abstract String
    fullName: abstract String
- uid: 352efe7b
  spec.java:
  - name: abstract boolean
    fullName: abstract boolean
- uid: bc380358
  spec.java:
  - name: abstract Exception
    fullName: abstract Exception
- uid: 7193d977
  spec.java:
  - name: abstract Map<String, String>
    fullName: abstract Map<String, String>
- uid: 13c86962com.microsoft.applicationinsights.telemetry._severity_level
  spec.java:
  - name: 'abstract '
    fullName: 'abstract '
  - uid: com.microsoft.applicationinsights.telemetry._severity_level
    name: SeverityLevel
    fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
    href: com.microsoft.applicationinsights.telemetry._severity_level.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: com.microsoft.applicationinsights.log4j.v1__2.internal._application_insights_log_event
  parent: com.microsoft.applicationinsights.log4j.v1__2.internal
  href: com.microsoft.applicationinsights.log4j.v1__2.internal._application_insights_log_event.yml
  name: ApplicationInsightsLogEvent
  fullName: com.microsoft.applicationinsights.log4j.v1_2.internal.ApplicationInsightsLogEvent
  type: Class
  syntax:
    content: public class ApplicationInsightsLogEvent
- uid: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event
  parent: com.microsoft.applicationinsights.log4j.v2.internal
  href: com.microsoft.applicationinsights.log4j.v2.internal._application_insights_log_event.yml
  name: ApplicationInsightsLogEvent
  fullName: com.microsoft.applicationinsights.log4j.v2.internal.ApplicationInsightsLogEvent
  type: Class
  syntax:
    content: public class ApplicationInsightsLogEvent
- uid: com.microsoft.applicationinsights.logback.internal._application_insights_log_event
  parent: com.microsoft.applicationinsights.logback.internal
  href: com.microsoft.applicationinsights.logback.internal._application_insights_log_event.yml
  name: ApplicationInsightsLogEvent
  fullName: com.microsoft.applicationinsights.logback.internal.ApplicationInsightsLogEvent
  type: Class
  syntax:
    content: public class ApplicationInsightsLogEvent
- uid: com.microsoft.applicationinsights.telemetry._severity_level
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._severity_level.yml
  name: SeverityLevel
  fullName: com.microsoft.applicationinsights.telemetry.SeverityLevel
  type: Enum
  summary: <p>Enum <xref href="com.microsoft.applicationinsights.telemetry._severity_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum SeverityLevel
