items:
- uid: com.microsoft.azure.management.network._application_gateway_private_frontend
  id: _application_gateway_private_frontend
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_frontend.yml
  langs:
  - java
  name: ApplicationGatewayPrivateFrontend
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>An immutable client-side representation of a private frontend of an internal application gateway. </p>
  syntax:
    content: public interface ApplicationGatewayPrivateFrontend extends ApplicationGatewayFrontend,HasPrivateIpAddress,HasSubnet
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  - com.microsoft.azure.management.network._application_gateway_frontend.isPublic()
  - com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.name()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.networkId()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.parent()
  - com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAddress()
  - com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAllocationMethod()
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
  - com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.subnetName()
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend.isPublic()
  parent: com.microsoft.azure.management.network._application_gateway_frontend
  href: com.microsoft.azure.management.network._application_gateway_frontend.yml
  name: isPublic()
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewayFrontend.isPublic()
  type: Method
  syntax:
    content: public boolean isPublic()
    return:
      type: 4fc6e284
      description: <p>true if the frontend is public, i.e. it has a public IP address associated with it </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.name()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_name.yml
  name: name()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasName.name()
  type: Method
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name of the resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.networkId()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.yml
  name: networkId()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.networkId()
  type: Method
  syntax:
    content: public String networkId()
    return:
      type: "26831127"
      description: <p>the resource ID of the virtual network whose subnet is associated with this resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.parent()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource<ParentT>.parent()
  type: Method
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the parent of this child object </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAddress()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: privateIpAddress()
  fullName: String com.microsoft.azure.management.network.model.HasPrivateIpAddress.privateIpAddress()
  type: Method
  syntax:
    content: public String privateIpAddress()
    return:
      type: "26831127"
      description: <p>the private IP address associated with this resource </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAllocationMethod()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: privateIpAllocationMethod()
  fullName: IPAllocationMethod com.microsoft.azure.management.network.model.HasPrivateIpAddress.privateIpAllocationMethod()
  type: Method
  syntax:
    content: public IPAllocationMethod privateIpAllocationMethod()
    return:
      type: com.microsoft.azure.management.network._i_p_allocation_method
      description: <p>the private IP address allocation method within the associated subnet </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.setInner(T)
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: setInner(T inner)
  fullName: void com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>.setInner(T inner)
  type: Method
  summary: >-
    <p>Set the wrapped inner model. (For internal use only)</p>

    <p></p>
  syntax:
    content: public void setInner(T inner)
    parameters:
    - id: inner
      type: 8ce1ecb9
      description: <p>the new inner model </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.subnetName()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.yml
  name: subnetName()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.subnetName()
  type: Method
  syntax:
    content: public String subnetName()
    return:
      type: "26831127"
      description: <p>the name of the subnet associated with this resource </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.yml
  name: ApplicationGatewayFrontend
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend
  type: Interface
  summary: <p>An immutable client-side representation of an application gateway frontend. </p>
  syntax:
    content: public interface ApplicationGatewayFrontend extends Wrapper<ApplicationGatewayFrontendIPConfigurationInner>,ChildResource<ApplicationGateway>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: HasPrivateIpAddress
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress
  type: Interface
  summary: <p>An interface representing a model's ability to reference a private IP address. </p>
  syntax:
    content: public interface HasPrivateIpAddress
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._has_subnet.yml
  name: HasSubnet
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet
  type: Interface
  summary: <p>An interface representing a model's ability to reference a subnet by its name and network's ID. </p>
  syntax:
    content: public interface HasSubnet
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_impl
