items:
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator
  id: _telemetry_processor_creator
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._telemetry_processor_creator.Create(TelemetryProcessorXmlElement)
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator.yml
  langs:
  - java
  name: TelemetryProcessorCreator
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreator
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreator.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreator.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>The class will try to create the <ref refid="" kindref="compound">TelemetryProcessor</ref> and will activate any 'setXXX' method based on the configuration</p>

    <p>Any exception thrown, or any setter method returns false will cause the processor to be ignored.</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class TelemetryProcessorCreator
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator.Create(TelemetryProcessorXmlElement)
  id: Create(TelemetryProcessorXmlElement)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_creator.yml
  langs:
  - java
  name: Create(TelemetryProcessorXmlElement confClass)
  fullName: TelemetryProcessor com.microsoft.applicationinsights.internal.config.TelemetryProcessorCreator.Create(TelemetryProcessorXmlElement confClass)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreator.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public TelemetryProcessor Create(TelemetryProcessorXmlElement confClass)
    parameters:
    - id: confClass
      type: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
    return:
      type: com.microsoft.applicationinsights.extensibility._telemetry_processor
references:
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: TelemetryProcessor
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryProcessor
  type: Interface
  summary: "<p>The method gets a <ref refid=\"\" kindref=\"compound\">Telemetry</ref> instance that is ready to be sent. This is your chance to approve or deny it. Returning 'false' means that the Telemetry will not be sent while 'true' means you approve it.</p>\r\n<p>The Telemetry might go through other filters though, that might deny its sending.</p>\r\n<p>To enable this processor you need to add it in the ApplicationInsights.xml like this:</p>\r\n<p>\r\n  <preformatted>\r\n    <programlisting>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Processor<sp></sp>type=\"full.path.to.Filter\"&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Add<sp></sp>name=\"Property\"<sp></sp>value=\"stringValue\"/&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/Processor&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;/TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n    </programlisting> \r\n*</preformatted>\r\n</p>\r\n<p>Note that the class defines a property named 'Property' which is configured too. Every property that you wish to configure needs to have a 'setX' public method like 'setProperty' in this example <bold>Exceptions thrown from the 'setX' methods will be caught by the framework that will ignore the filter</bold></p>\r\n<p>Created by gupele on 7/26/2016. </p>"
  syntax:
    content: public interface TelemetryProcessor
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  name: TelemetryProcessorXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorXmlElement
