items:
- uid: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test
  id: _in_process_telemetry_channel_test
  parent: com.microsoft.applicationinsights.internal.channel.inprocess
  children:
  - com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.testNotValidEndpointAddress()
  - com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.testNotValidEndpointAddressAsMapValue()
  href: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.yml
  langs:
  - java
  name: InProcessTelemetryChannelTest
  fullName: com.microsoft.applicationinsights.internal.channel.inprocess.InProcessTelemetryChannelTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/inprocess/InProcessTelemetryChannelTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/inprocess/InProcessTelemetryChannelTest.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.channel.inprocess
  syntax:
    content: public class InProcessTelemetryChannelTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.testNotValidEndpointAddress()
  id: testNotValidEndpointAddress()
  parent: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test
  href: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.yml
  langs:
  - java
  name: testNotValidEndpointAddress()
  fullName: void com.microsoft.applicationinsights.internal.channel.inprocess.InProcessTelemetryChannelTest.testNotValidEndpointAddress()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/inprocess/InProcessTelemetryChannelTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.channel.inprocess
  syntax:
    content: public void testNotValidEndpointAddress()
- uid: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.testNotValidEndpointAddressAsMapValue()
  id: testNotValidEndpointAddressAsMapValue()
  parent: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test
  href: com.microsoft.applicationinsights.internal.channel.inprocess._in_process_telemetry_channel_test.yml
  langs:
  - java
  name: testNotValidEndpointAddressAsMapValue()
  fullName: void com.microsoft.applicationinsights.internal.channel.inprocess.InProcessTelemetryChannelTest.testNotValidEndpointAddressAsMapValue()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/inprocess/InProcessTelemetryChannelTest.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.channel.inprocess
  syntax:
    content: public void testNotValidEndpointAddressAsMapValue()
references: []
