items:
- uid: com.microsoft.applicationinsights.web.internal
  id: internal
  children:
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  - com.microsoft.applicationinsights.web.internal._request_telemetry_context
  - com.microsoft.applicationinsights.web.internal._thread_context
  - com.microsoft.applicationinsights.web.internal._web_modules_container
  - com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  href: com.microsoft.applicationinsights.web.internal.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.internal
  fullName: com.microsoft.applicationinsights.web.internal
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 21
  syntax:
    content: namespace internal
references:
- uid: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies.yml
  name: com.microsoft.applicationinsights.web.internal.cookies
  fullName: com.microsoft.applicationinsights.web.internal.cookies
  type: Namespace
  syntax:
    content: namespace cookies
- uid: com.microsoft.applicationinsights.web.internal.perfcounter
  href: com.microsoft.applicationinsights.web.internal.perfcounter.yml
  name: com.microsoft.applicationinsights.web.internal.perfcounter
  fullName: com.microsoft.applicationinsights.web.internal.perfcounter
  type: Namespace
  syntax:
    content: namespace perfcounter
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  name: ApplicationInsightsHttpResponseWrapper
  fullName: com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper
  type: Class
  summary: <p>This class wraps the HTTP servlet response in order to store the response status code. This wrapper is used to support servlet API 2.5, which lacks the api to get response status. Created by yonisha on 5/27/2015. </p>
  syntax:
    content: public class ApplicationInsightsHttpResponseWrapper
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  name: RequestTelemetryContext
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class RequestTelemetryContext
- uid: com.microsoft.applicationinsights.web.internal._thread_context
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._thread_context.yml
  name: ThreadContext
  fullName: com.microsoft.applicationinsights.web.internal.ThreadContext
  type: Class
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class ThreadContext
- uid: com.microsoft.applicationinsights.web.internal._web_modules_container
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._web_modules_container.yml
  name: WebModulesContainer
  fullName: com.microsoft.applicationinsights.web.internal.WebModulesContainer
  type: Class
  summary: <p>Created by yonisha on 2/3/2015. </p>
  syntax:
    content: public class WebModulesContainer
- uid: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._web_request_tracking_filter.yml
  name: WebRequestTrackingFilter
  fullName: com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class WebRequestTrackingFilter
