items:
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test
  id: _session_state_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.testCtor()
  - com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.testEmptyCtor()
  - com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.testSetSessionState()
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.yml
  langs:
  - java
  name: SessionStateTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.SessionStateTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetryTest.java
    startLine: 28
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class SessionStateTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.testCtor()
  id: testCtor()
  parent: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.yml
  langs:
  - java
  name: testCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.SessionStateTelemetryTest.testCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetryTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtor()
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.testEmptyCtor()
  id: testEmptyCtor()
  parent: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.yml
  langs:
  - java
  name: testEmptyCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.SessionStateTelemetryTest.testEmptyCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetryTest.java
    startLine: 30
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyCtor()
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.testSetSessionState()
  id: testSetSessionState()
  parent: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry_test.yml
  langs:
  - java
  name: testSetSessionState()
  fullName: void com.microsoft.applicationinsights.telemetry.SessionStateTelemetryTest.testSetSessionState()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetryTest.java
    startLine: 42
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetSessionState()
references:
- uid: com.microsoft.applicationinsights.telemetry._session_state_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._session_state_telemetry.yml
  name: SessionStateTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.SessionStateTelemetry
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> type used to track user sessions. </p>
  syntax:
    content: public class SessionStateTelemetry extends BaseTelemetry<SessionStateData>
- uid: com.microsoft.applicationinsights.telemetry._session_state
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._session_state.yml
  name: SessionState
  fullName: com.microsoft.applicationinsights.telemetry.SessionState
  type: Enum
  summary: <p>Session states. </p>
  syntax:
    content: public enum SessionState
