items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  id: _prepared_statement_class_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.instrumentationData()
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.PreparedStatementClassVisitor(ClassInstrumentationData,ClassWriter,PreparedStatementMetaData)
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.visitField(int,String,String,String,Object)
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.visitMethod(int,String,String,String,String[])
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.yml
  langs:
  - java
  name: PreparedStatementClassVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassVisitor
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
    startLine: 37
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementClassVisitor
  inheritance:
  - java.lang.Object
  - ClassVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.instrumentationData()
  id: instrumentationData()
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.yml
  langs:
  - java
  name: instrumentationData
  fullName: final ClassInstrumentationData com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassVisitor.instrumentationData
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
    startLine: 41
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: protected final ClassInstrumentationData instrumentationData
    return:
      type: 93de0ef9com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.PreparedStatementClassVisitor(ClassInstrumentationData,ClassWriter,PreparedStatementMetaData)
  id: PreparedStatementClassVisitor(ClassInstrumentationData,ClassWriter,PreparedStatementMetaData)
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.yml
  langs:
  - java
  name: PreparedStatementClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter, PreparedStatementMetaData metaData)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassVisitor.PreparedStatementClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter, PreparedStatementMetaData metaData)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
    startLine: 45
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public PreparedStatementClassVisitor(ClassInstrumentationData instrumentationData, ClassWriter classWriter, PreparedStatementMetaData metaData)
    parameters:
    - id: instrumentationData
      type: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    - id: classWriter
      type: 80ad7f6d
    - id: metaData
      type: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.visitField(int,String,String,String,Object)
  id: visitField(int,String,String,String,Object)
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.yml
  langs:
  - java
  name: visitField(int access, String name, String desc, String signature, Object value)
  fullName: FieldVisitor com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassVisitor.visitField(int access, String name, String desc, String signature, Object value)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
    startLine: 72
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public FieldVisitor visitField(int access, String name, String desc, String signature, Object value)
    parameters:
    - id: access
      type: f75371fa
    - id: name
      type: "26831127"
    - id: desc
      type: "26831127"
    - id: signature
      type: "26831127"
    - id: value
      type: "79317049"
    return:
      type: a4b8ddb9
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.visitMethod(int,String,String,String,String[])
  id: visitMethod(int,String,String,String,String[])
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_class_visitor.yml
  langs:
  - java
  name: visitMethod(int access, String name, String desc, String signature, String[] exceptions)
  fullName: MethodVisitor com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementClassVisitor.visitMethod(int access, String name, String desc, String signature, String[] exceptions)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
    startLine: 94
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions)
    parameters:
    - id: access
      type: f75371fa
    - id: name
      type: "26831127"
    - id: desc
      type: "26831127"
    - id: signature
      type: "26831127"
    - id: exceptions
      type: 30d59cf1
    return:
      type: dd525b3c
references:
- uid: 93de0ef9com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
    name: ClassInstrumentationData
    fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
    href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
- uid: 80ad7f6d
  spec.java:
  - name: ClassWriter
    fullName: ClassWriter
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: a4b8ddb9
  spec.java:
  - name: FieldVisitor
    fullName: FieldVisitor
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
- uid: dd525b3c
  spec.java:
  - name: MethodVisitor
    fullName: MethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_meta_data.yml
  name: PreparedStatementMetaData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementMetaData
  type: Class
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementMetaData
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
