items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._code_injector
  id: _code_injector
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._code_injector.CodeInjector(AgentConfiguration)
  - com.microsoft.applicationinsights.agent.internal.agent._code_injector.transform(ClassLoader,String,Class,ProtectionDomain,byte[])
  href: com.microsoft.applicationinsights.agent.internal.agent._code_injector.yml
  langs:
  - java
  name: CodeInjector
  fullName: com.microsoft.applicationinsights.agent.internal.agent.CodeInjector
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CodeInjector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CodeInjector.java
    startLine: 39
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: >-
    <p>The class is responsible for finding needed classes</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class CodeInjector
  inheritance:
  - java.lang.Object
  - ClassFileTransformer
- uid: com.microsoft.applicationinsights.agent.internal.agent._code_injector.CodeInjector(AgentConfiguration)
  id: CodeInjector(AgentConfiguration)
  parent: com.microsoft.applicationinsights.agent.internal.agent._code_injector
  href: com.microsoft.applicationinsights.agent.internal.agent._code_injector.yml
  langs:
  - java
  name: CodeInjector(AgentConfiguration agentConfiguration)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.CodeInjector.CodeInjector(AgentConfiguration agentConfiguration)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CodeInjector.java
    startLine: 49
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: >-
    <p>The constructor will set all the data needed for the transformation</p>

    <p></p>
  syntax:
    content: public CodeInjector(AgentConfiguration agentConfiguration)
    parameters:
    - id: agentConfiguration
      type: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
      description: <p>The configuration </p>
- uid: com.microsoft.applicationinsights.agent.internal.agent._code_injector.transform(ClassLoader,String,Class,ProtectionDomain,byte[])
  id: transform(ClassLoader,String,Class,ProtectionDomain,byte[])
  parent: com.microsoft.applicationinsights.agent.internal.agent._code_injector
  href: com.microsoft.applicationinsights.agent.internal.agent._code_injector.yml
  langs:
  - java
  name: transform(ClassLoader loader, String className, Class classBeingRedefined, ProtectionDomain protectionDomain, byte[] originalBuffer)
  fullName: byte [] com.microsoft.applicationinsights.agent.internal.agent.CodeInjector.transform(ClassLoader loader, String className, Class classBeingRedefined, ProtectionDomain protectionDomain, byte[] originalBuffer)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CodeInjector.java
    startLine: 70
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: <p>Main method that transforms classes </p>
  syntax:
    content: public byte[] transform(ClassLoader loader, String className, Class classBeingRedefined, ProtectionDomain protectionDomain, byte[] originalBuffer)
    parameters:
    - id: loader
      type: 5d46207c
      description: <p>The class loader that loaded this class </p>
    - id: className
      type: "26831127"
      description: <p>The class name </p>
    - id: classBeingRedefined
      type: 2913d89b
      description: <p>The class that is being redefined </p>
    - id: protectionDomain
      type: 32893ddd
      description: <p>The protection domain </p>
    - id: originalBuffer
      type: bc819c2f
      description: <p>The class that was loaded before transforming it </p>
    return:
      type: bc819c2f
      description: <p>A byte array that contains the transformed original class or the original one if nothing was done. </p>
  exceptions:
  - type: 177e2d5f
    description: <p>Theoretical, since the following implementation won't throw. </p>
references:
- uid: 177e2d5f
  spec.java:
  - name: IllegalClassFormatException
    fullName: IllegalClassFormatException
- uid: 5d46207c
  spec.java:
  - name: ClassLoader
    fullName: ClassLoader
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 2913d89b
  spec.java:
  - name: Class
    fullName: Class
- uid: 32893ddd
  spec.java:
  - name: ProtectionDomain
    fullName: ProtectionDomain
- uid: bc819c2f
  spec.java:
  - name: byte[]
    fullName: byte[]
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.yml
  name: JmxConnectorLoader
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorLoader
  type: Class
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JmxConnectorLoader
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  name: AgentConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration
  type: Interface
  summary: <p>Defines the interface for concrete classes that represent configuration data for the Agent Created by gupele on 5/17/2015. </p>
  syntax:
    content: public interface AgentConfiguration
