items:
- uid: com.microsoft.applicationinsights.core.volume._throughput_test
  id: _throughput_test
  parent: com.microsoft.applicationinsights.core.volume
  children:
  - com.microsoft.applicationinsights.core.volume._throughput_test.main(String[])
  href: com.microsoft.applicationinsights.core.volume._throughput_test.yml
  langs:
  - java
  name: ThroughputTest
  fullName: com.microsoft.applicationinsights.core.volume.ThroughputTest
  type: Class
  source:
    remote: &o0
      path: test/performance/src/main/java/com/microsoft/applicationinsights/core/volume/ThroughputTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: test/performance/src/main/java/com/microsoft/applicationinsights/core/volume/ThroughputTest.java
    startLine: 39
  package: com.microsoft.applicationinsights.core.volume
  summary: <p>Created by gupele on 2/4/2015. </p>
  syntax:
    content: public class ThroughputTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.core.volume._throughput_test.main(String[])
  id: main(String[])
  parent: com.microsoft.applicationinsights.core.volume._throughput_test
  href: com.microsoft.applicationinsights.core.volume._throughput_test.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void com.microsoft.applicationinsights.core.volume.ThroughputTest.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: test/performance/src/main/java/com/microsoft/applicationinsights/core/volume/ThroughputTest.java
    startLine: 51
  package: com.microsoft.applicationinsights.core.volume
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
