items:
- uid: com.microsoft.azure.management.network._application_gateway_ip_configuration._definition
  id: _definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configuration._definition.yml
  langs:
  - java
  name: ApplicationGatewayIpConfiguration.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.Definition<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
    startLine: 76
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of an application gateway IP configuration definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends ApplicationGatewayIpConfiguration.DefinitionStages.Blank<ParentT>,ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>,ApplicationGatewayIpConfiguration.DefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  - com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.withContainingSubnet(Subnet)
  - com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.withContainingSubnet(Network,String)
  - com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.withContainingSubnet(String,String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.withContainingSubnet(Subnet)
  parent: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226
  href: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.yml
  name: withContainingSubnet(Subnet subnet)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>.withContainingSubnet(Subnet subnet)
  type: Method
  summary: <p>Specifies an existing subnet the application gateway should be part of and get its private IP address from. </p>
  syntax:
    content: public WithAttach<ParentT> withContainingSubnet(Subnet subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure.management.network._subnet
      description: <p>an existing subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ip_configura586ca6c8cb309fcc227a99309bfae1cbda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.withContainingSubnet(Network,String)
  parent: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226
  href: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.yml
  name: withContainingSubnet(Network network, String subnetName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>.withContainingSubnet(Network network, String subnetName)
  type: Method
  summary: <p>Specifies an existing subnet the application gateway should be part of and get its private IP address from. </p>
  syntax:
    content: public WithAttach<ParentT> withContainingSubnet(Network network, String subnetName)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>an existing virtual network </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet within the selected network </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ip_configura586ca6c8cb309fcc227a99309bfae1cbda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.withContainingSubnet(String,String)
  parent: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226
  href: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.yml
  name: withContainingSubnet(String networkId, String subnetName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>.withContainingSubnet(String networkId, String subnetName)
  type: Method
  summary: <p>Specifies an existing subnet the application gateway should be part of and get its private IP address from. </p>
  syntax:
    content: public WithAttach<ParentT> withContainingSubnet(String networkId, String subnetName)
    parameters:
    - id: networkId
      type: "26831127"
      description: <p>the resource ID of an existing virtual network </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subset within the selected network </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ip_configura586ca6c8cb309fcc227a99309bfae1cbda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura09f620ed7b13f3cf3368160d40b4d6df
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configura09f620ed7b13f3cf3368160d40b4d6df.yml
  name: ApplicationGatewayIpConfiguration.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.DefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of an application gateway IP configuration definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configura78012ba148638f620ae69470a3fa5226.yml
  name: ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.DefinitionStages.WithContainingSubnet<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway IP configuration definition allowing to specify the subnet the application gateway is on. </p>
  syntax:
    content: public interface WithContainingSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent type </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura586ca6c8cb309fcc227a99309bfae1cb
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configura586ca6c8cb309fcc227a99309bfae1cb.yml
  name: ApplicationGatewayIpConfiguration.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of the application gateway IP configuration definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
