items:
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
  id: _telemetries_transmitter
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.scheduleSend(TelemetriesFetcher,long,TimeUnit)
  - com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.sendNow(Collection<String>)
  - com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.yml
  langs:
  - java
  name: TelemetriesTransmitter
  fullName: com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.channel
  summary: >-
    <p>The class is responsible for getting containers of <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref>, transform them into <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and then initiate the sending process.</p>

    <p>Containers of Telemetry instances are populated by application threads. This class use the 'channel's' threads for the rest of the process. In other words, the de-coupling of user and channel threads happens here.</p>

    <p>The class lets its users to schedule a 'send', where a channel thread will be sent to 'pick up' the container of Telemetries. Or, it also lets the caller to initiate a 'send now' call where the caller passes the container and this class will continue, again, using a channel thread while releasing the calling thread.</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public interface TelemetriesTransmitter
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.scheduleSend(TelemetriesFetcher,long,TimeUnit)
  id: scheduleSend(TelemetriesFetcher,long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.yml
  langs:
  - java
  name: scheduleSend(TelemetriesFetcher telemetriesFetcher, long value, TimeUnit timeUnit)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter.scheduleSend(TelemetriesFetcher telemetriesFetcher, long value, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public boolean scheduleSend(TelemetriesFetcher telemetriesFetcher, long value, TimeUnit timeUnit)
    parameters:
    - id: telemetriesFetcher
      type: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher
    - id: value
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.sendNow(Collection<String>)
  id: sendNow(Collection<String>)
  parent: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.yml
  langs:
  - java
  name: sendNow(Collection<String> telemetries)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter.sendNow(Collection<String> telemetries)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public boolean sendNow(Collection<String> telemetries)
    parameters:
    - id: telemetries
      type: 0248867e
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TelemetriesTransmitter.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 0248867e
  spec.java:
  - name: Collection<String>
    fullName: Collection<String>
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.yml
  name: TransmitterImpl
  fullName: com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl
  type: Class
  summary: >-
    <p>The default implementation of the <xref href="com.microsoft.applicationinsights.internal.channel._telemetries_transmitter" data-throw-if-not-resolved="false"></xref></p>

    <p>The class is responsible holds the classes that do the actual sending to the server Telemetry instances buffered in a collection are sent through this class.</p>

    <p>The class makes sure that the container of telemetries is sent using internal threads and not the 'application' threads</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class TransmitterImpl
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.scheduleSend(TelemetriesFetcher,long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.yml
  name: scheduleSend(TelemetriesFetcher telemetriesFetcher, long value, TimeUnit timeUnit)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl.scheduleSend(TelemetriesFetcher telemetriesFetcher, long value, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public boolean scheduleSend(TelemetriesFetcher telemetriesFetcher, long value, TimeUnit timeUnit)
    parameters:
    - id: telemetriesFetcher
      type: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher
    - id: value
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._telemetries_transmitter._telemetries_fetcher.yml
  name: TelemetriesTransmitter.TelemetriesFetcher
  fullName: com.microsoft.applicationinsights.internal.channel.TelemetriesTransmitter.TelemetriesFetcher
  type: Interface
  syntax:
    content: public interface TelemetriesFetcher
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.sendNow(Collection<String>)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.yml
  name: sendNow(Collection<String> telemetries)
  fullName: boolean com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl.sendNow(Collection<String> telemetries)
  type: Method
  syntax:
    content: public boolean sendNow(Collection<String> telemetries)
    parameters:
    - id: telemetries
      type: 0248867e
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl
  href: com.microsoft.applicationinsights.internal.channel.common._transmitter_impl.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
