items:
- uid: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
  id: _performance_counters_collection_plugin
  parent: com.microsoft.applicationinsights.extensibility
  children:
  - com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.postCollection()
  - com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.preCollection()
  href: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.yml
  langs:
  - java
  name: PerformanceCountersCollectionPlugin
  fullName: com.microsoft.applicationinsights.extensibility.PerformanceCountersCollectionPlugin
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersCollectionPlugin.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersCollectionPlugin.java
    startLine: 26
  package: com.microsoft.applicationinsights.extensibility
  summary: <p>Created by gupele on 9/13/2016. </p>
  syntax:
    content: public interface PerformanceCountersCollectionPlugin
- uid: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.postCollection()
  id: postCollection()
  parent: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
  href: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.yml
  langs:
  - java
  name: postCollection()
  fullName: void com.microsoft.applicationinsights.extensibility.PerformanceCountersCollectionPlugin.postCollection()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersCollectionPlugin.java
    startLine: 29
  package: com.microsoft.applicationinsights.extensibility
  syntax:
    content: public void postCollection()
- uid: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.preCollection()
  id: preCollection()
  parent: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin
  href: com.microsoft.applicationinsights.extensibility._performance_counters_collection_plugin.yml
  langs:
  - java
  name: preCollection()
  fullName: void com.microsoft.applicationinsights.extensibility.PerformanceCountersCollectionPlugin.preCollection()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersCollectionPlugin.java
    startLine: 27
  package: com.microsoft.applicationinsights.extensibility
  syntax:
    content: public void preCollection()
references:
- uid: com.microsoft.applicationinsights.sample._sample_p_c_plugin
  parent: com.microsoft.applicationinsights.sample
  href: com.microsoft.applicationinsights.sample._sample_p_c_plugin.yml
  name: SamplePCPlugin
  fullName: com.microsoft.applicationinsights.sample.SamplePCPlugin
  type: Class
  summary: >-
    <p>A sample for creating a concrete plugin that will be called before and after Performance Counters are collected.</p>

    <p>To activate this class you need to add it to the ApplicationInsights.xml configuration file with the 'Plugin' tag:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Plugin&gt;full.path.to.your.Plugin&lt;/Plugin&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>Created by gupele on 9/13/2016. </p>
  syntax:
    content: public class SamplePCPlugin
- uid: com.microsoft.applicationinsights.sample._sample_p_c_plugin.preCollection()
  parent: com.microsoft.applicationinsights.sample._sample_p_c_plugin
  href: com.microsoft.applicationinsights.sample._sample_p_c_plugin.yml
  name: preCollection()
  fullName: void com.microsoft.applicationinsights.sample.SamplePCPlugin.preCollection()
  type: Method
  syntax:
    content: public void preCollection()
- uid: com.microsoft.applicationinsights.sample._sample_p_c_plugin.postCollection()
  parent: com.microsoft.applicationinsights.sample._sample_p_c_plugin
  href: com.microsoft.applicationinsights.sample._sample_p_c_plugin.yml
  name: postCollection()
  fullName: void com.microsoft.applicationinsights.sample.SamplePCPlugin.postCollection()
  type: Method
  syntax:
    content: public void postCollection()
