items:
- uid: com.microsoft.applicationinsights.internal.util._channel_fetcher
  id: _channel_fetcher
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._channel_fetcher.fetch()
  href: com.microsoft.applicationinsights.internal.util._channel_fetcher.yml
  langs:
  - java
  name: ChannelFetcher
  fullName: com.microsoft.applicationinsights.internal.util.ChannelFetcher
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ChannelFetcher.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ChannelFetcher.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by gupele on 2/2/2015. </p>
  syntax:
    content: public interface ChannelFetcher
- uid: com.microsoft.applicationinsights.internal.util._channel_fetcher.fetch()
  id: fetch()
  parent: com.microsoft.applicationinsights.internal.util._channel_fetcher
  href: com.microsoft.applicationinsights.internal.util._channel_fetcher.yml
  langs:
  - java
  name: fetch()
  fullName: TelemetryChannel com.microsoft.applicationinsights.internal.util.ChannelFetcher.fetch()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ChannelFetcher.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public TelemetryChannel fetch()
    return:
      type: com.microsoft.applicationinsights.channel._telemetry_channel
references:
- uid: com.microsoft.applicationinsights.channel._telemetry_channel
  parent: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel._telemetry_channel.yml
  name: TelemetryChannel
  fullName: com.microsoft.applicationinsights.channel.TelemetryChannel
  type: Interface
  summary: <p>Represents a communication channel for sending telemetry to application insights. </p>
  syntax:
    content: public interface TelemetryChannel
