items:
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  id: _non_blocking_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.dispatch(Transmission)
  - com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.NonBlockingDispatcher(TransmissionOutput[])
  - com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  langs:
  - java
  name: NonBlockingDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/NonBlockingDispatcher.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/NonBlockingDispatcher.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.channel.common
  summary: >-
    <p>The class implements <xref href="com.microsoft.applicationinsights.internal.channel._transmission_dispatcher" data-throw-if-not-resolved="false"></xref></p>

    <p>Basically, the class tries to find one <xref href="com.microsoft.applicationinsights.internal.channel._transmission_output" data-throw-if-not-resolved="false"></xref> that will accept the incoming <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref>.</p>

    <p>It is a non blocking behavior in the sense that if no one can accept it will drop the data</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class NonBlockingDispatcher implements TransmissionDispatcher
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.dispatch(Transmission)
  id: dispatch(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  langs:
  - java
  name: dispatch(Transmission transmission)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher.dispatch(Transmission transmission)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/NonBlockingDispatcher.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void dispatch(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.dispatch(Transmission)
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.NonBlockingDispatcher(TransmissionOutput[])
  id: NonBlockingDispatcher(TransmissionOutput[])
  parent: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  langs:
  - java
  name: NonBlockingDispatcher(TransmissionOutput[] transmissionOutputs)
  fullName: com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher.NonBlockingDispatcher(TransmissionOutput[] transmissionOutputs)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/NonBlockingDispatcher.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public NonBlockingDispatcher(TransmissionOutput[] transmissionOutputs)
    parameters:
    - id: transmissionOutputs
      type: com.microsoft.applicationinsights.internal.channel._transmission_output397151d7
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/NonBlockingDispatcher.java
    startLine: 61
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
  overridden: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.stop(long,TimeUnit)
references:
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output397151d7
  spec.java:
  - uid: com.microsoft.applicationinsights.internal.channel._transmission_output
    name: TransmissionOutput
    fullName: com.microsoft.applicationinsights.internal.channel.TransmissionOutput
    href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  - name: '[]'
    fullName: '[]'
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  name: TransmissionDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher
  type: Interface
  summary: >-
    <p>A dispatcher should know how and to whom to dispatch a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionDispatcher
- uid: com.microsoft.applicationinsights.internal.channel._transmission_output
  parent: com.microsoft.applicationinsights.internal.channel
  href: com.microsoft.applicationinsights.internal.channel._transmission_output.yml
  name: TransmissionOutput
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionOutput
  type: Interface
  summary: >-
    <p>Defines the interface of classes that get a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref> and can 'send' it.</p>

    <p>Concrete classes can 'send' the data to remote server, to disk, database etc.</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionOutput
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.dispatch(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  name: dispatch(Transmission transmission)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher.dispatch(Transmission transmission)
  type: Method
  syntax:
    content: public void dispatch(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
