items:
- uid: com.microsoft.applicationinsights.core.volume
  id: volume
  children:
  - com.microsoft.applicationinsights.core.volume._throughput_test
  href: com.microsoft.applicationinsights.core.volume.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.core.volume
  fullName: com.microsoft.applicationinsights.core.volume
  type: Namespace
  source:
    remote:
      path: test/performance/src/main/java/com/microsoft/applicationinsights/core/volume/FakeTransmissionOutput.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: test/performance/src/main/java/com/microsoft/applicationinsights/core/volume/FakeTransmissionOutput.java
    startLine: 21
  syntax:
    content: namespace volume
references:
- uid: com.microsoft.applicationinsights.core.volume._throughput_test
  parent: com.microsoft.applicationinsights.core.volume
  href: com.microsoft.applicationinsights.core.volume._throughput_test.yml
  name: ThroughputTest
  fullName: com.microsoft.applicationinsights.core.volume.ThroughputTest
  type: Class
  summary: <p>Created by gupele on 2/4/2015. </p>
  syntax:
    content: public class ThroughputTest
