items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader
  id: _jmx_connector_loader
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.initialize()
  - com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.JmxConnectorLoader()
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.yml
  langs:
  - java
  name: JmxConnectorLoader
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorLoader
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public class JmxConnectorLoader
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.initialize()
  id: initialize()
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.yml
  langs:
  - java
  name: initialize()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorLoader.initialize()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
    startLine: 39
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  syntax:
    content: public boolean initialize()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.JmxConnectorLoader()
  id: JmxConnectorLoader()
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_loader.yml
  langs:
  - java
  name: JmxConnectorLoader()
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorLoader.JmxConnectorLoader()
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
    startLine: 36
  package: com.microsoft.applicationinsights.agent.internal.agent.jmx
  syntax:
    content: public JmxConnectorLoader()
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean
  parent: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx._jmx_connector_m_x_bean.yml
  name: JmxConnectorMXBean
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx.JmxConnectorMXBean
  type: Interface
  summary: <p>Created by gupele on 8/6/2015. </p>
  syntax:
    content: public interface JmxConnectorMXBean
