items:
- uid: com.microsoft.applicationinsights.internal.reflect
  id: reflect
  children:
  - com.microsoft.applicationinsights.internal.reflect._class_data_utils
  - com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  href: com.microsoft.applicationinsights.internal.reflect.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.reflect
  fullName: com.microsoft.applicationinsights.internal.reflect
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtils.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/reflect/ClassDataUtils.java
    startLine: 21
  syntax:
    content: namespace reflect
references:
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils
  parent: com.microsoft.applicationinsights.internal.reflect
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils.yml
  name: ClassDataUtils
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataUtils
  type: Enum
  summary: <p>Created by gupele on 5/26/2015. </p>
  syntax:
    content: public enum ClassDataUtils implements ClassDataVerifier
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test
  parent: com.microsoft.applicationinsights.internal.reflect
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils_test.yml
  name: ClassDataUtilsTest
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataUtilsTest
  type: Class
  syntax:
    content: public class ClassDataUtilsTest
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier
  parent: com.microsoft.applicationinsights.internal.reflect
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier.yml
  name: ClassDataVerifier
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataVerifier
  type: Interface
  summary: <p>Created by gupele on 5/26/2015. </p>
  syntax:
    content: public interface ClassDataVerifier
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests
  parent: com.microsoft.applicationinsights.internal.reflect
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl_tests.yml
  name: ClassDataVerifierImplTests
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataVerifierImplTests
  type: Class
  syntax:
    content: public class ClassDataVerifierImplTests
