items:
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  id: _telemetry_processors_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.getBuiltInTelemetryProcessors()
  - com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.getCustomTelemetryProcessors()
  - com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.setBuiltInTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement>)
  - com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.setCustomTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement>)
  href: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.yml
  langs:
  - java
  name: TelemetryProcessorsXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorsXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorsXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.getBuiltInTelemetryProcessors()
  id: getBuiltInTelemetryProcessors()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.yml
  langs:
  - java
  name: getBuiltInTelemetryProcessors()
  fullName: ArrayList<TelemetryProcessorXmlElement> com.microsoft.applicationinsights.internal.config.TelemetryProcessorsXmlElement.getBuiltInTelemetryProcessors()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<TelemetryProcessorXmlElement> getBuiltInTelemetryProcessors()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._telemetry_processor_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.getCustomTelemetryProcessors()
  id: getCustomTelemetryProcessors()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.yml
  langs:
  - java
  name: getCustomTelemetryProcessors()
  fullName: ArrayList<TelemetryProcessorXmlElement> com.microsoft.applicationinsights.internal.config.TelemetryProcessorsXmlElement.getCustomTelemetryProcessors()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public ArrayList<TelemetryProcessorXmlElement> getCustomTelemetryProcessors()
    return:
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._telemetry_processor_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.setBuiltInTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement>)
  id: setBuiltInTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.yml
  langs:
  - java
  name: setBuiltInTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement> builtIn)
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorsXmlElement.setBuiltInTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement> builtIn)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setBuiltInTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement> builtIn)
    parameters:
    - id: builtIn
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._telemetry_processor_xml_elementa08ddfce
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.setCustomTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement>)
  id: setCustomTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement>)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element
  href: com.microsoft.applicationinsights.internal.config._telemetry_processors_xml_element.yml
  langs:
  - java
  name: setCustomTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement> custom)
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryProcessorsXmlElement.setCustomTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement> custom)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setCustomTelemetryProcessors(ArrayList<TelemetryProcessorXmlElement> custom)
    parameters:
    - id: custom
      type: 573b1e0bcom.microsoft.applicationinsights.internal.config._telemetry_processor_xml_elementa08ddfce
references:
- uid: 573b1e0bcom.microsoft.applicationinsights.internal.config._telemetry_processor_xml_elementa08ddfce
  spec.java:
  - name: ArrayList<
    fullName: ArrayList<
  - uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
    name: TelemetryProcessorXmlElement
    fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement
    href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  name: TelemetryProcessorXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorXmlElement
