items:
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test
  id: _device_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  children:
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetId()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetLanguage()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetModel()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetNetworkType()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetOemName()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetOperatingSystem()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetOperatingSystemVersion()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetRoleInstance()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetRoleName()
  - com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetScreenResolution()
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: DeviceContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.DeviceContextTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public class DeviceContextTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetId()
  id: testSetId()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetId()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetId()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetId()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetLanguage()
  id: testSetLanguage()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetLanguage()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetLanguage()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 42
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetLanguage()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetModel()
  id: testSetModel()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetModel()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetModel()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 53
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetModel()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetNetworkType()
  id: testSetNetworkType()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetNetworkType()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetNetworkType()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 64
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetNetworkType()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetOemName()
  id: testSetOemName()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetOemName()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetOemName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 75
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetOemName()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetOperatingSystem()
  id: testSetOperatingSystem()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetOperatingSystem()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetOperatingSystem()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 86
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetOperatingSystem()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetOperatingSystemVersion()
  id: testSetOperatingSystemVersion()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetOperatingSystemVersion()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetOperatingSystemVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 97
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetOperatingSystemVersion()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetRoleInstance()
  id: testSetRoleInstance()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetRoleInstance()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetRoleInstance()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 108
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetRoleInstance()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetRoleName()
  id: testSetRoleName()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetRoleName()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetRoleName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 119
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetRoleName()
- uid: com.microsoft.applicationinsights.extensibility.context._device_context_test.testSetScreenResolution()
  id: testSetScreenResolution()
  parent: com.microsoft.applicationinsights.extensibility.context._device_context_test
  href: com.microsoft.applicationinsights.extensibility.context._device_context_test.yml
  langs:
  - java
  name: testSetScreenResolution()
  fullName: void com.microsoft.applicationinsights.extensibility.context.DeviceContextTest.testSetScreenResolution()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/DeviceContextTest.java
    startLine: 130
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetScreenResolution()
references: []
