items:
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm
  id: jvm
  children:
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.perfcounter.jvm
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 21
  syntax:
    content: namespace jvm
references:
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  name: DeadLockDetectorPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter
  type: Class
  summary: >-
    <p>The class uses the JVM ThreadMXBean to detect threads dead locks A metric with value 0 is sent when there are no blocked threads, otherwise the number of detected blocked threads is sent with a dimension that holds information like thread id and minimal stack traces as trace telemetries</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class DeadLockDetectorPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._g_c_performance_counter.yml
  name: GCPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.GCPerformanceCounter
  type: Class
  summary: >-
    <p>The class reports GC related data</p>

    <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class GCPerformanceCounter implements PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._jvm_heap_memory_used_performance_counter.yml
  name: JvmHeapMemoryUsedPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.JvmHeapMemoryUsedPerformanceCounter
  type: Class
  summary: >-
    <p>The class will create a metric telemetry for capturing the Jvm's heap memory usage</p>

    <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class JvmHeapMemoryUsedPerformanceCounter implements PerformanceCounter
