items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend.b3d22ed01e7a007025c9d6f347f6ac89
  id: b3d22ed01e7a007025c9d6f347f6ac89
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.b3d22ed01e7a007025c9d6f347f6ac89.yml
  langs:
  - java
  name: ApplicationGatewayFrontend.UpdateStages.WithPrivateIp
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateStages.WithPrivateIp
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
    startLine: 130
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway frontend update allowing to specify the private IP address this application gateway should be available at within the selected virtual network. </p>
  syntax:
    content: public interface WithPrivateIp extends HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<Update>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressStatic(String)
references:
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address_79a968159178b1656309d6d666baddc7.yml
  name: HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateStages.WithPrivateIpAddress<ReturnT>
  type: Interface
  summary: <p>The stage of an update allowing to modify the private IP address. </p>
  syntax:
    content: public interface WithPrivateIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend._update.yml
  name: ApplicationGatewayFrontend.Update
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.Update
  type: Interface
  summary: <p>The entirety of an application gateway frontend update as part of an application gateway update. </p>
  syntax:
    content: public interface Update extends Settable<ApplicationGateway.Update>,ApplicationGatewayFrontend.UpdateStages.WithSubnet,ApplicationGatewayFrontend.UpdateStages.WithPublicIpAddress,ApplicationGatewayFrontend.UpdateStages.WithPrivateIp
