items:
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
  id: _agent_configuration_builder
  parent: com.microsoft.applicationinsights.agent.internal.config
  children:
  - com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder.parseConfigurationFile(String)
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder.yml
  langs:
  - java
  name: AgentConfigurationBuilder
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilder
  type: Interface
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilder.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilder.java
    startLine: 27
  package: com.microsoft.applicationinsights.agent.internal.config
  summary: <p>Defines the interface for builders that know how to create <xref href="com.microsoft.applicationinsights.agent.internal.config._agent_configuration" data-throw-if-not-resolved="false"></xref> Created by gupele on 5/19/2015. </p>
  syntax:
    content: public interface AgentConfigurationBuilder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder.parseConfigurationFile(String)
  id: parseConfigurationFile(String)
  parent: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration_builder.yml
  langs:
  - java
  name: parseConfigurationFile(String baseFolder)
  fullName: AgentConfiguration com.microsoft.applicationinsights.agent.internal.config.AgentConfigurationBuilder.parseConfigurationFile(String baseFolder)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilder.java
    startLine: 28
  package: com.microsoft.applicationinsights.agent.internal.config
  syntax:
    content: public AgentConfiguration parseConfigurationFile(String baseFolder)
    parameters:
    - id: baseFolder
      type: "26831127"
    return:
      type: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.agent.internal.config._xml_agent_configuration_builder
- uid: com.microsoft.applicationinsights.agent.internal.config._agent_configuration
  parent: com.microsoft.applicationinsights.agent.internal.config
  href: com.microsoft.applicationinsights.agent.internal.config._agent_configuration.yml
  name: AgentConfiguration
  fullName: com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration
  type: Interface
  summary: <p>Defines the interface for concrete classes that represent configuration data for the Agent Created by gupele on 5/17/2015. </p>
  syntax:
    content: public interface AgentConfiguration
