items:
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  id: _local_file_system_utils_test
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_InsideUserHome()
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_Linux()
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_PerUser()
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_WindowsForUser()
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_WindowsForUserWithSystemUserDefined()
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_WindowsForUserWithSystemUserUnknown()
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: LocalFileSystemUtilsTest
  fullName: com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public class LocalFileSystemUtilsTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_InsideUserHome()
  id: getTempDir_InsideUserHome()
  parent: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: getTempDir_InsideUserHome()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest.getTempDir_InsideUserHome()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 84
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void getTempDir_InsideUserHome()
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_Linux()
  id: getTempDir_Linux()
  parent: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: getTempDir_Linux()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest.getTempDir_Linux()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void getTempDir_Linux()
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_PerUser()
  id: getTempDir_PerUser()
  parent: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: getTempDir_PerUser()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest.getTempDir_PerUser()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 74
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void getTempDir_PerUser()
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_WindowsForUser()
  id: getTempDir_WindowsForUser()
  parent: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: getTempDir_WindowsForUser()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest.getTempDir_WindowsForUser()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void getTempDir_WindowsForUser()
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_WindowsForUserWithSystemUserDefined()
  id: getTempDir_WindowsForUserWithSystemUserDefined()
  parent: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: getTempDir_WindowsForUserWithSystemUserDefined()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest.getTempDir_WindowsForUserWithSystemUserDefined()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void getTempDir_WindowsForUserWithSystemUserDefined()
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.getTempDir_WindowsForUserWithSystemUserUnknown()
  id: getTempDir_WindowsForUserWithSystemUserUnknown()
  parent: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  langs:
  - java
  name: getTempDir_WindowsForUserWithSystemUserUnknown()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest.getTempDir_WindowsForUserWithSystemUserUnknown()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtilsTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void getTempDir_WindowsForUserWithSystemUserUnknown()
references: []
