items:
- uid: com.microsoft.applicationinsights.internal.config._remove_type_xml_element
  id: _remove_type_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._remove_type_xml_element.getType()
  - com.microsoft.applicationinsights.internal.config._remove_type_xml_element.setType(String)
  href: com.microsoft.applicationinsights.internal.config._remove_type_xml_element.yml
  langs:
  - java
  name: RemoveTypeXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.RemoveTypeXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/RemoveTypeXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/RemoveTypeXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/16/2015. </p>
  syntax:
    content: public class RemoveTypeXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._remove_type_xml_element.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.config._remove_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._remove_type_xml_element.yml
  langs:
  - java
  name: getType()
  fullName: String com.microsoft.applicationinsights.internal.config.RemoveTypeXmlElement.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/RemoveTypeXmlElement.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._remove_type_xml_element.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.internal.config._remove_type_xml_element
  href: com.microsoft.applicationinsights.internal.config._remove_type_xml_element.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.internal.config.RemoveTypeXmlElement.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/RemoveTypeXmlElement.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
