items:
- uid: com.microsoft.applicationinsights.web.javaee._request_name
  id: _request_name
  parent: com.microsoft.applicationinsights.web.javaee
  href: com.microsoft.applicationinsights.web.javaee._request_name.yml
  langs:
  - java
  name: RequestName
  fullName: com.microsoft.applicationinsights.web.javaee.RequestName
  type: Interface
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestName.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestName.java
    startLine: 38
  package: com.microsoft.applicationinsights.web.javaee
  syntax:
    content: public interface RequestName
references: []
