items:
- uid: com.microsoft.azure.management.trafficmanager._dns_config
  id: _dns_config
  parent: com.microsoft.azure.management.trafficmanager
  children:
  - com.microsoft.azure.management.trafficmanager._dns_config.fqdn()
  - com.microsoft.azure.management.trafficmanager._dns_config.relativeName()
  - com.microsoft.azure.management.trafficmanager._dns_config.ttl()
  - com.microsoft.azure.management.trafficmanager._dns_config.withFqdn(String)
  - com.microsoft.azure.management.trafficmanager._dns_config.withRelativeName(String)
  - com.microsoft.azure.management.trafficmanager._dns_config.withTtl(Long)
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: DnsConfig
  fullName: com.microsoft.azure.management.trafficmanager.DnsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.trafficmanager
  summary: <p>Class containing DNS settings in a Traffic Manager profile. </p>
  syntax: &o1
    content: public class DnsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.trafficmanager._dns_config.fqdn()
  id: fqdn()
  parent: com.microsoft.azure.management.trafficmanager._dns_config
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: fqdn()
  fullName: String com.microsoft.azure.management.trafficmanager.DnsConfig.fqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 62
  package: com.microsoft.azure.management.trafficmanager
  summary: >-
    <p>Get the fqdn value.</p>

    <p></p>
  syntax:
    content: public String fqdn()
    return:
      type: "26831127"
      description: <p>the fqdn value </p>
- uid: com.microsoft.azure.management.trafficmanager._dns_config.relativeName()
  id: relativeName()
  parent: com.microsoft.azure.management.trafficmanager._dns_config
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: relativeName()
  fullName: String com.microsoft.azure.management.trafficmanager.DnsConfig.relativeName()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 42
  package: com.microsoft.azure.management.trafficmanager
  summary: >-
    <p>Get the relativeName value.</p>

    <p></p>
  syntax:
    content: public String relativeName()
    return:
      type: "26831127"
      description: <p>the relativeName value </p>
- uid: com.microsoft.azure.management.trafficmanager._dns_config.ttl()
  id: ttl()
  parent: com.microsoft.azure.management.trafficmanager._dns_config
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: ttl()
  fullName: Long com.microsoft.azure.management.trafficmanager.DnsConfig.ttl()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 82
  package: com.microsoft.azure.management.trafficmanager
  summary: >-
    <p>Get the ttl value.</p>

    <p></p>
  syntax:
    content: public Long ttl()
    return:
      type: 34f09483
      description: <p>the ttl value </p>
- uid: com.microsoft.azure.management.trafficmanager._dns_config.withFqdn(String)
  id: withFqdn(String)
  parent: com.microsoft.azure.management.trafficmanager._dns_config
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: withFqdn(String fqdn)
  fullName: DnsConfig com.microsoft.azure.management.trafficmanager.DnsConfig.withFqdn(String fqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 72
  package: com.microsoft.azure.management.trafficmanager
  summary: >-
    <p>Set the fqdn value.</p>

    <p></p>
  syntax:
    content: public DnsConfig withFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>the fqdn value to set </p>
    return:
      type: com.microsoft.azure.management.trafficmanager._dns_config
      description: <p>the <xref href="com.microsoft.azure.management.trafficmanager._dns_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.trafficmanager._dns_config.withRelativeName(String)
  id: withRelativeName(String)
  parent: com.microsoft.azure.management.trafficmanager._dns_config
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: withRelativeName(String relativeName)
  fullName: DnsConfig com.microsoft.azure.management.trafficmanager.DnsConfig.withRelativeName(String relativeName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 52
  package: com.microsoft.azure.management.trafficmanager
  summary: >-
    <p>Set the relativeName value.</p>

    <p></p>
  syntax:
    content: public DnsConfig withRelativeName(String relativeName)
    parameters:
    - id: relativeName
      type: "26831127"
      description: <p>the relativeName value to set </p>
    return:
      type: com.microsoft.azure.management.trafficmanager._dns_config
      description: <p>the <xref href="com.microsoft.azure.management.trafficmanager._dns_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.trafficmanager._dns_config.withTtl(Long)
  id: withTtl(Long)
  parent: com.microsoft.azure.management.trafficmanager._dns_config
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  langs:
  - java
  name: withTtl(Long ttl)
  fullName: DnsConfig com.microsoft.azure.management.trafficmanager.DnsConfig.withTtl(Long ttl)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/DnsConfig.java
    startLine: 92
  package: com.microsoft.azure.management.trafficmanager
  summary: >-
    <p>Set the ttl value.</p>

    <p></p>
  syntax:
    content: public DnsConfig withTtl(Long ttl)
    parameters:
    - id: ttl
      type: 34f09483
      description: <p>the ttl value to set </p>
    return:
      type: com.microsoft.azure.management.trafficmanager._dns_config
      description: <p>the <xref href="com.microsoft.azure.management.trafficmanager._dns_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 34f09483
  spec.java:
  - name: Long
    fullName: Long
- uid: com.microsoft.azure.management._azure
  parent: com.microsoft.azure.management
  href: com.microsoft.azure.management._azure.yml
  name: Azure
  fullName: com.microsoft.azure.management.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.management.trafficmanager._dns_config
  parent: com.microsoft.azure.management.trafficmanager
  href: com.microsoft.azure.management.trafficmanager._dns_config.yml
  name: DnsConfig
  fullName: com.microsoft.azure.management.trafficmanager.DnsConfig
  type: Class
  summary: <p>Class containing DNS settings in a Traffic Manager profile. </p>
  syntax: *o1
