items:
- uid: com.microsoft.applicationinsights.web.javaee._request_name_interceptor
  id: _request_name_interceptor
  parent: com.microsoft.applicationinsights.web.javaee
  children:
  - com.microsoft.applicationinsights.web.javaee._request_name_interceptor.invoke(InvocationContext)
  href: com.microsoft.applicationinsights.web.javaee._request_name_interceptor.yml
  langs:
  - java
  name: RequestNameInterceptor
  fullName: com.microsoft.applicationinsights.web.javaee.RequestNameInterceptor
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestNameInterceptor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestNameInterceptor.java
    startLine: 35
  package: com.microsoft.applicationinsights.web.javaee
  syntax:
    content: public class RequestNameInterceptor
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.web.javaee._request_name_interceptor.invoke(InvocationContext)
  id: invoke(InvocationContext)
  parent: com.microsoft.applicationinsights.web.javaee._request_name_interceptor
  href: com.microsoft.applicationinsights.web.javaee._request_name_interceptor.yml
  langs:
  - java
  name: invoke(InvocationContext ic)
  fullName: Object com.microsoft.applicationinsights.web.javaee.RequestNameInterceptor.invoke(InvocationContext ic)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestNameInterceptor.java
    startLine: 38
  package: com.microsoft.applicationinsights.web.javaee
  syntax:
    content: public Object invoke(InvocationContext ic)
    parameters:
    - id: ic
      type: c1453322
    return:
      type: "79317049"
references:
- uid: c1453322
  spec.java:
  - name: InvocationContext
    fullName: InvocationContext
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
