items:
- uid: com.microsoft.applicationinsights.web.struts
  id: struts
  children:
  - com.microsoft.applicationinsights.web.struts._request_name_interceptor
  href: com.microsoft.applicationinsights.web.struts.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.struts
  fullName: com.microsoft.applicationinsights.web.struts
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/struts/RequestNameInterceptor.java
    startLine: 21
  syntax:
    content: namespace struts
references:
- uid: com.microsoft.applicationinsights.web.struts._request_name_interceptor
  parent: com.microsoft.applicationinsights.web.struts
  href: com.microsoft.applicationinsights.web.struts._request_name_interceptor.yml
  name: RequestNameInterceptor
  fullName: com.microsoft.applicationinsights.web.struts.RequestNameInterceptor
  type: Class
  summary: <p>Created by yonisha on 3/10/2015. </p>
  syntax:
    content: public class RequestNameInterceptor
