items:
- uid: com.microsoft.applicationinsights.logback
  id: logback
  children:
  - com.microsoft.applicationinsights.logback._application_insights_appender
  - com.microsoft.applicationinsights.logback._application_insights_appender_tests
  href: com.microsoft.applicationinsights.logback.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.logback
  fullName: com.microsoft.applicationinsights.logback
  type: Namespace
  source:
    remote:
      path: logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppender.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppender.java
    startLine: 21
  syntax:
    content: namespace logback
references:
- uid: com.microsoft.applicationinsights.logback.internal
  href: com.microsoft.applicationinsights.logback.internal.yml
  name: com.microsoft.applicationinsights.logback.internal
  fullName: com.microsoft.applicationinsights.logback.internal
  type: Namespace
  syntax:
    content: namespace internal
- uid: com.microsoft.applicationinsights.logback._application_insights_appender
  parent: com.microsoft.applicationinsights.logback
  href: com.microsoft.applicationinsights.logback._application_insights_appender.yml
  name: ApplicationInsightsAppender
  fullName: com.microsoft.applicationinsights.logback.ApplicationInsightsAppender
  type: Class
  summary: <p>LOGBack appender. </p>
  syntax:
    content: public class ApplicationInsightsAppender
- uid: com.microsoft.applicationinsights.logback._application_insights_appender_tests
  parent: com.microsoft.applicationinsights.logback
  href: com.microsoft.applicationinsights.logback._application_insights_appender_tests.yml
  name: ApplicationInsightsAppenderTests
  fullName: com.microsoft.applicationinsights.logback.ApplicationInsightsAppenderTests
  type: Class
  syntax:
    content: public class ApplicationInsightsAppenderTests
