items:
- uid: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test
  id: _timestamp_property_initializer_test
  parent: com.microsoft.applicationinsights.extensibility.initializer
  children:
  - com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.testSetTimestampWithNonNull()
  - com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.testSetTimestampWithNull()
  href: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.yml
  langs:
  - java
  name: TimestampPropertyInitializerTest
  fullName: com.microsoft.applicationinsights.extensibility.initializer.TimestampPropertyInitializerTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/TimestampPropertyInitializerTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/TimestampPropertyInitializerTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public class TimestampPropertyInitializerTest
  inheritance:
  - java.lang.Object
  - TestCase
- uid: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.testSetTimestampWithNonNull()
  id: testSetTimestampWithNonNull()
  parent: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.yml
  langs:
  - java
  name: testSetTimestampWithNonNull()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.TimestampPropertyInitializerTest.testSetTimestampWithNonNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/TimestampPropertyInitializerTest.java
    startLine: 40
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testSetTimestampWithNonNull()
- uid: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.testSetTimestampWithNull()
  id: testSetTimestampWithNull()
  parent: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test
  href: com.microsoft.applicationinsights.extensibility.initializer._timestamp_property_initializer_test.yml
  langs:
  - java
  name: testSetTimestampWithNull()
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.TimestampPropertyInitializerTest.testSetTimestampWithNull()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/TimestampPropertyInitializerTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.extensibility.initializer
  syntax:
    content: public void testSetTimestampWithNull()
references:
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
