items:
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  id: _registration_type
  parent: com.microsoft.applicationinsights.internal.agent
  children:
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.NONE()
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.SELF()
  - com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.WEB()
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.yml
  langs:
  - java
  name: AgentConnector.RegistrationType
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationType
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public enum RegistrationType
  inheritance:
  - java.lang.Object
  - java.lang.Enum<AgentConnector.RegistrationType>
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.NONE()
  id: NONE()
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.yml
  langs:
  - java
  name: NONE
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationType.NONE
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public NONE
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.SELF()
  id: SELF()
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.yml
  langs:
  - java
  name: SELF
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationType.SELF
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public SELF
- uid: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.WEB()
  id: WEB()
  parent: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type
  href: com.microsoft.applicationinsights.internal.agent._agent_connector._registration_type.yml
  langs:
  - java
  name: WEB
  fullName: com.microsoft.applicationinsights.internal.agent.AgentConnector.RegistrationType.WEB
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.agent
  syntax:
    content: public WEB
references: []
