items:
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  id: _application_insights_http_response_wrapper
  parent: com.microsoft.applicationinsights.web.internal
  children:
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.ApplicationInsightsHttpResponseWrapper(HttpServletResponse)
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.getStatus()
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.reset()
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.sendError(int)
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.sendError(int,String)
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.sendRedirect(String)
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.setStatus(int)
  - com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.setStatus(int,String)
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: ApplicationInsightsHttpResponseWrapper
  fullName: com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 32
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>This class wraps the HTTP servlet response in order to store the response status code. This wrapper is used to support servlet API 2.5, which lacks the api to get response status. Created by yonisha on 5/27/2015. </p>
  syntax:
    content: public class ApplicationInsightsHttpResponseWrapper
  inheritance:
  - java.lang.Object
  - HttpServletResponseWrapper
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.ApplicationInsightsHttpResponseWrapper(HttpServletResponse)
  id: ApplicationInsightsHttpResponseWrapper(HttpServletResponse)
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: ApplicationInsightsHttpResponseWrapper(HttpServletResponse response)
  fullName: com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.ApplicationInsightsHttpResponseWrapper(HttpServletResponse response)
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 36
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public ApplicationInsightsHttpResponseWrapper(HttpServletResponse response)
    parameters:
    - id: response
      type: 4fb6a380
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.getStatus()
  id: getStatus()
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: getStatus()
  fullName: int com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.getStatus()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 85
  package: com.microsoft.applicationinsights.web.internal
  summary: <p>Gets the response status. </p>
  syntax:
    content: public int getStatus()
    return:
      type: f75371fa
      description: <p>The response status. </p>
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.reset()
  id: reset()
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: reset()
  fullName: void com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.reset()
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 76
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public void reset()
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.sendError(int)
  id: sendError(int)
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: sendError(int sc)
  fullName: void com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.sendError(int sc)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 55
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public void sendError(int sc)
    parameters:
    - id: sc
      type: f75371fa
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.sendError(int,String)
  id: sendError(int,String)
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: sendError(int sc, String msg)
  fullName: void com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.sendError(int sc, String msg)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 62
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public void sendError(int sc, String msg)
    parameters:
    - id: sc
      type: f75371fa
    - id: msg
      type: "26831127"
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.sendRedirect(String)
  id: sendRedirect(String)
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: sendRedirect(String location)
  fullName: void com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.sendRedirect(String location)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 69
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public void sendRedirect(String location)
    parameters:
    - id: location
      type: "26831127"
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.setStatus(int)
  id: setStatus(int)
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: setStatus(int sc)
  fullName: void com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.setStatus(int sc)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 41
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public void setStatus(int sc)
    parameters:
    - id: sc
      type: f75371fa
- uid: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.setStatus(int,String)
  id: setStatus(int,String)
  parent: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper
  href: com.microsoft.applicationinsights.web.internal._application_insights_http_response_wrapper.yml
  langs:
  - java
  name: setStatus(int sc, String sm)
  fullName: void com.microsoft.applicationinsights.web.internal.ApplicationInsightsHttpResponseWrapper.setStatus(int sc, String sm)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java
    startLine: 48
  package: com.microsoft.applicationinsights.web.internal
  syntax:
    content: public void setStatus(int sc, String sm)
    parameters:
    - id: sc
      type: f75371fa
    - id: sm
      type: "26831127"
references:
- uid: 4fb6a380
  spec.java:
  - name: HttpServletResponse
    fullName: HttpServletResponse
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
