items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var
  id: _temp_array_var
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.TempArrayVar(int)
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.tempVarIndex()
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.yml
  langs:
  - java
  name: AdvancedAdviceAdapter.TempArrayVar
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempArrayVar
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 52
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: protected class TempArrayVar
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.TempArrayVar(int)
  id: TempArrayVar(int)
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.yml
  langs:
  - java
  name: TempArrayVar(int tempVarIndex)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempArrayVar.TempArrayVar(int tempVarIndex)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 55
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public TempArrayVar(int tempVarIndex)
    parameters:
    - id: tempVarIndex
      type: f75371fa
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.tempVarIndex()
  id: tempVarIndex()
  parent: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.yml
  langs:
  - java
  name: tempVarIndex
  fullName: final int com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempArrayVar.tempVarIndex
  type: Field
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AdvancedAdviceAdapter.java
    startLine: 53
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public final int tempVarIndex
    return:
      type: cd225469
references:
- uid: cd225469
  spec.java:
  - name: final int
    fullName: final int
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
