items:
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier
  id: _class_data_verifier
  parent: com.microsoft.applicationinsights.internal.reflect
  children:
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier.verifyClassExists(String)
  - com.microsoft.applicationinsights.internal.reflect._class_data_verifier.verifyMethodExists(Class<?>,String,Class<?>...)
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier.yml
  langs:
  - java
  name: ClassDataVerifier
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataVerifier
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifier.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifier.java
    startLine: 28
  package: com.microsoft.applicationinsights.internal.reflect
  summary: <p>Created by gupele on 5/26/2015. </p>
  syntax:
    content: public interface ClassDataVerifier
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier.verifyClassExists(String)
  id: verifyClassExists(String)
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_verifier
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier.yml
  langs:
  - java
  name: verifyClassExists(String className)
  fullName: boolean com.microsoft.applicationinsights.internal.reflect.ClassDataVerifier.verifyClassExists(String className)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifier.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public boolean verifyClassExists(String className)
    parameters:
    - id: className
      type: "26831127"
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier.verifyMethodExists(Class<?>,String,Class<?>...)
  id: )
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_verifier
  href: com.microsoft.applicationinsights.internal.reflect._class_data_verifier.yml
  langs:
  - java
  name: verifyMethodExists(Class<?> clazz, String methodName, Class<?>...parameterTypes)
  fullName: boolean com.microsoft.applicationinsights.internal.reflect.ClassDataVerifier.verifyMethodExists(Class<?> clazz, String methodName, Class<?>...parameterTypes)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/reflect/ClassDataVerifier.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.reflect
  syntax:
    content: public boolean verifyMethodExists(Class<?> clazz, String methodName, Class<?>...parameterTypes)
    parameters:
    - id: clazz
      type: a19781f8
    - id: methodName
      type: "26831127"
    - id: parameterTypes
      type: 0f2b04be
    return:
      type: 4fc6e284
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: a19781f8
  spec.java:
  - name: Class<?>
    fullName: Class<?>
- uid: 0f2b04be
  spec.java:
  - name: Class<?>...
    fullName: Class<?>...
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils
  parent: com.microsoft.applicationinsights.internal.reflect
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils.yml
  name: ClassDataUtils
  fullName: com.microsoft.applicationinsights.internal.reflect.ClassDataUtils
  type: Enum
  summary: <p>Created by gupele on 5/26/2015. </p>
  syntax:
    content: public enum ClassDataUtils implements ClassDataVerifier
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_verifier_impl
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils.verifyClassExists(String)
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_utils
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils.yml
  name: verifyClassExists(String className)
  fullName: boolean com.microsoft.applicationinsights.internal.reflect.ClassDataUtils.verifyClassExists(String className)
  type: Method
  syntax:
    content: public boolean verifyClassExists(String className)
    parameters:
    - id: className
      type: "26831127"
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.reflect._class_data_utils.verifyMethodExists(Class<?>,String,Class<?>...)
  parent: com.microsoft.applicationinsights.internal.reflect._class_data_utils
  href: com.microsoft.applicationinsights.internal.reflect._class_data_utils.yml
  name: verifyMethodExists(Class<?> clazz, String methodName, Class<?>...parameterTypes)
  fullName: boolean com.microsoft.applicationinsights.internal.reflect.ClassDataUtils.verifyMethodExists(Class<?> clazz, String methodName, Class<?>...parameterTypes)
  type: Method
  syntax:
    content: public boolean verifyMethodExists(Class<?> clazz, String methodName, Class<?>...parameterTypes)
    parameters:
    - id: clazz
      type: a19781f8
    - id: methodName
      type: "26831127"
    - id: parameterTypes
      type: 0f2b04be
    return:
      type: 4fc6e284
