items:
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element
  id: _param_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._param_xml_element.getName()
  - com.microsoft.applicationinsights.internal.config._param_xml_element.getValue()
  - com.microsoft.applicationinsights.internal.config._param_xml_element.setName(String)
  - com.microsoft.applicationinsights.internal.config._param_xml_element.setValue(String)
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  langs:
  - java
  name: ParamXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ParamXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by yonisha on 3/16/2015. </p>
  syntax:
    content: public class ParamXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.internal.config._param_xml_element
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.internal.config.ParamXmlElement.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element.getValue()
  id: getValue()
  parent: com.microsoft.applicationinsights.internal.config._param_xml_element
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  langs:
  - java
  name: getValue()
  fullName: String com.microsoft.applicationinsights.internal.config.ParamXmlElement.getValue()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getValue()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.internal.config._param_xml_element
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  langs:
  - java
  name: setName(String name)
  fullName: void com.microsoft.applicationinsights.internal.config.ParamXmlElement.setName(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setName(String name)
    parameters:
    - id: name
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._param_xml_element.setValue(String)
  id: setValue(String)
  parent: com.microsoft.applicationinsights.internal.config._param_xml_element
  href: com.microsoft.applicationinsights.internal.config._param_xml_element.yml
  langs:
  - java
  name: setValue(String value)
  fullName: void com.microsoft.applicationinsights.internal.config.ParamXmlElement.setValue(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setValue(String value)
    parameters:
    - id: value
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
