items:
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  id: _dead_lock_detector_performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm
  children:
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.DeadLockDetectorPerformanceCounter()
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.getId()
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.isSupported()
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.NAME()
  - com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.report(TelemetryClient)
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  langs:
  - java
  name: DeadLockDetectorPerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.perfcounter.jvm
  summary: >-
    <p>The class uses the JVM ThreadMXBean to detect threads dead locks A metric with value 0 is sent when there are no blocked threads, otherwise the number of detected blocked threads is sent with a dimension that holds information like thread id and minimal stack traces as trace telemetries</p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class DeadLockDetectorPerformanceCounter implements PerformanceCounter
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.DeadLockDetectorPerformanceCounter()
  id: DeadLockDetectorPerformanceCounter()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  langs:
  - java
  name: DeadLockDetectorPerformanceCounter()
  fullName: com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.DeadLockDetectorPerformanceCounter()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 56
  package: com.microsoft.applicationinsights.internal.perfcounter.jvm
  syntax:
    content: public DeadLockDetectorPerformanceCounter()
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 66
  package: com.microsoft.applicationinsights.internal.perfcounter.jvm
  syntax:
    content: public String getId()
    return:
      type: "26831127"
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.isSupported()
  id: isSupported()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  langs:
  - java
  name: isSupported()
  fullName: boolean com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.isSupported()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 60
  package: com.microsoft.applicationinsights.internal.perfcounter.jvm
  syntax:
    content: public boolean isSupported()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.NAME()
  id: NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  langs:
  - java
  name: NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.perfcounter.jvm
  syntax:
    content: public static final String NAME= "ThreadDeadLockDetector"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.report(TelemetryClient)
  id: report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter.jvm._dead_lock_detector_performance_counter.yml
  langs:
  - java
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.jvm.DeadLockDetectorPerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.perfcounter.jvm
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: PerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.perfcounter._performance_counter" data-throw-if-not-resolved="false"></xref> interface.</p>

    <p>Every concrete class should have a unique id and it should be able to collect data send that data using a <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface PerformanceCounter
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.getId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.getId()
  type: Method
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.report(TelemetryClient)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: report(TelemetryClient telemetryClient)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter.report(TelemetryClient telemetryClient)
  type: Method
  syntax:
    content: public void report(TelemetryClient telemetryClient)
    parameters:
    - id: telemetryClient
      type: com.microsoft.applicationinsights._telemetry_client
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
