items:
- uid: com.microsoft.applicationinsights.internal.util
  id: util
  children:
  - com.microsoft.applicationinsights.internal.util._channel_fetcher
  - com.microsoft.applicationinsights.internal.util._date_time_utils
  - com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  - com.microsoft.applicationinsights.internal.util._device_info
  - com.microsoft.applicationinsights.internal.util._device_info_test
  - com.microsoft.applicationinsights.internal.util._limits_enforcer
  - com.microsoft.applicationinsights.internal.util._limits_enforcer_test
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils
  - com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  - com.microsoft.applicationinsights.internal.util._local_strings_utils
  - com.microsoft.applicationinsights.internal.util._local_strings_utils_test
  - com.microsoft.applicationinsights.internal.util._map_util
  - com.microsoft.applicationinsights.internal.util._property_helper
  - com.microsoft.applicationinsights.internal.util._sanitizer
  - com.microsoft.applicationinsights.internal.util._thread_local_cleaner
  - com.microsoft.applicationinsights.internal.util._thread_pool_utils
  href: com.microsoft.applicationinsights.internal.util.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.util
  fullName: com.microsoft.applicationinsights.internal.util
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ChannelFetcher.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/ChannelFetcher.java
    startLine: 21
  syntax:
    content: namespace util
references:
- uid: com.microsoft.applicationinsights.internal.util._channel_fetcher
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._channel_fetcher.yml
  name: ChannelFetcher
  fullName: com.microsoft.applicationinsights.internal.util.ChannelFetcher
  type: Interface
  summary: <p>Created by gupele on 2/2/2015. </p>
  syntax:
    content: public interface ChannelFetcher
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._date_time_utils.yml
  name: DateTimeUtils
  fullName: com.microsoft.applicationinsights.internal.util.DateTimeUtils
  type: Class
  summary: <p>Created by yonisha on 2/5/2015. </p>
  syntax:
    content: public class DateTimeUtils
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  name: DateTimeUtilsTests
  fullName: com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests
  type: Class
  summary: <p>Created by yonisha on 5/26/2015. </p>
  syntax:
    content: public class DateTimeUtilsTests
- uid: com.microsoft.applicationinsights.internal.util._device_info
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._device_info.yml
  name: DeviceInfo
  fullName: com.microsoft.applicationinsights.internal.util.DeviceInfo
  type: Class
  summary: <p>A view into the context information specific to device information. </p>
  syntax:
    content: public class DeviceInfo
- uid: com.microsoft.applicationinsights.internal.util._device_info_test
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._device_info_test.yml
  name: DeviceInfoTest
  fullName: com.microsoft.applicationinsights.internal.util.DeviceInfoTest
  type: Class
  summary: <p>Created by amnonsh on 2/10/2015. </p>
  syntax:
    content: public class DeviceInfoTest
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer.yml
  name: LimitsEnforcer
  fullName: com.microsoft.applicationinsights.internal.util.LimitsEnforcer
  type: Class
  summary: <p>Created by gupele on 5/10/2015. </p>
  syntax:
    content: public class LimitsEnforcer
- uid: com.microsoft.applicationinsights.internal.util._limits_enforcer_test
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._limits_enforcer_test.yml
  name: LimitsEnforcerTest
  fullName: com.microsoft.applicationinsights.internal.util.LimitsEnforcerTest
  type: Class
  syntax:
    content: public class LimitsEnforcerTest
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils.yml
  name: LocalFileSystemUtils
  fullName: com.microsoft.applicationinsights.internal.util.LocalFileSystemUtils
  type: Class
  summary: <p>Helper methods for dealing with files and folders. </p>
  syntax:
    content: public class LocalFileSystemUtils
- uid: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._local_file_system_utils_test.yml
  name: LocalFileSystemUtilsTest
  fullName: com.microsoft.applicationinsights.internal.util.LocalFileSystemUtilsTest
  type: Class
  syntax:
    content: public class LocalFileSystemUtilsTest
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils.yml
  name: LocalStringsUtils
  fullName: com.microsoft.applicationinsights.internal.util.LocalStringsUtils
  type: Class
  syntax:
    content: public class LocalStringsUtils
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils_test
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils_test.yml
  name: LocalStringsUtilsTest
  fullName: com.microsoft.applicationinsights.internal.util.LocalStringsUtilsTest
  type: Class
  syntax:
    content: public class LocalStringsUtilsTest
- uid: com.microsoft.applicationinsights.internal.util._map_util
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._map_util.yml
  name: MapUtil
  fullName: com.microsoft.applicationinsights.internal.util.MapUtil
  type: Class
  summary: <p>Methods that would have been great to have on maps. </p>
  syntax:
    content: public class MapUtil
- uid: com.microsoft.applicationinsights.internal.util._property_helper
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._property_helper.yml
  name: PropertyHelper
  fullName: com.microsoft.applicationinsights.internal.util.PropertyHelper
  type: Class
  summary: <p>Helper class for reading data from a properties file found on the class path. </p>
  syntax:
    content: public class PropertyHelper
- uid: com.microsoft.applicationinsights.internal.util._sanitizer
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  name: Sanitizer
  fullName: com.microsoft.applicationinsights.internal.util.Sanitizer
  type: Class
  summary: <p>Created by gupele on 1/7/2015. </p>
  syntax:
    content: public class Sanitizer
- uid: com.microsoft.applicationinsights.internal.util._thread_local_cleaner
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._thread_local_cleaner.yml
  name: ThreadLocalCleaner
  fullName: com.microsoft.applicationinsights.internal.util.ThreadLocalCleaner
  type: Interface
  summary: <p>Created by gupele on 7/8/2015. </p>
  syntax:
    content: public interface ThreadLocalCleaner
- uid: com.microsoft.applicationinsights.internal.util._thread_pool_utils
  parent: com.microsoft.applicationinsights.internal.util
  href: com.microsoft.applicationinsights.internal.util._thread_pool_utils.yml
  name: ThreadPoolUtils
  fullName: com.microsoft.applicationinsights.internal.util.ThreadPoolUtils
  type: Class
  summary: <p>Created by gupele on 12/22/2014. </p>
  syntax:
    content: public class ThreadPoolUtils
