items:
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  id: _metric_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testCtor()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testEmptyCtor()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSanitizeLongName()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetCount()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetMax()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetMin()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetName()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetStandardDeviation()
  - com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetValue()
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: MetricTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.MetricTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 28
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class MetricTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testCtor()
  id: testCtor()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCtor()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testEmptyCtor()
  id: testEmptyCtor()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testEmptyCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testEmptyCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 30
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyCtor()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSanitizeLongName()
  id: testSanitizeLongName()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSanitizeLongName()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSanitizeLongName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 106
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSanitizeLongName()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetCount()
  id: testSetCount()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSetCount()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSetCount()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 74
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetCount()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetMax()
  id: testSetMax()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSetMax()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSetMax()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 90
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetMax()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetMin()
  id: testSetMin()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSetMin()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSetMin()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 82
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetMin()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetName()
  id: testSetName()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSetName()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSetName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 56
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetName()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetStandardDeviation()
  id: testSetStandardDeviation()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSetStandardDeviation()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSetStandardDeviation()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 98
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetStandardDeviation()
- uid: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.testSetValue()
  id: testSetValue()
  parent: com.microsoft.applicationinsights.telemetry._metric_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._metric_telemetry_test.yml
  langs:
  - java
  name: testSetValue()
  fullName: void com.microsoft.applicationinsights.telemetry.MetricTelemetryTest.testSetValue()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/MetricTelemetryTest.java
    startLine: 65
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testSetValue()
references: []
