items:
- uid: com.microsoft.azure.management.network._application_gateway_private_fron86d395e09e0da6800a1bdfb683097da8
  id: _application_gateway_private_fron86d395e09e0da6800a1bdfb683097da8
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_fron86d395e09e0da6800a1bdfb683097da8.yml
  langs:
  - java
  name: ApplicationGatewayPrivateFrontend.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
    startLine: 104
  package: com.microsoft.azure.management.network
  summary: <p>The first stage of a private frontend definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayPrivateFrontend.UpdateDefinitionStages.WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway_private_fron1656724520fd71d9ee722e9826936bc0.withExistingSubnet(Network,String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._application_gateway_private_fron1656724520fd71d9ee722e9826936bc0.withExistingSubnet(Network,String)
  parent: com.microsoft.azure.management.network._application_gateway_private_fron1656724520fd71d9ee722e9826936bc0
  href: com.microsoft.azure.management.network._application_gateway_private_fron1656724520fd71d9ee722e9826936bc0.yml
  name: withExistingSubnet(Network network, String subnetName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.UpdateDefinitionStages.WithSubnet<ParentT>.withExistingSubnet(Network network, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this private frontend. </p>
  syntax:
    content: public WithAttach<ParentT> withExistingSubnet(Network network, String subnetName)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network the subnet exists in </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_private_froncea4b0423dc27ef337aa24a324d54aebda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_private_fron1656724520fd71d9ee722e9826936bc0
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_fron1656724520fd71d9ee722e9826936bc0.yml
  name: ApplicationGatewayPrivateFrontend.UpdateDefinitionStages.WithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.UpdateDefinitionStages.WithSubnet<ParentT>
  type: Interface
  summary: <p>The stage of a private frontend definition allowing to specify a subnet from the selected network. </p>
  syntax:
    content: public interface WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_private_frontend._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_frontend._update_definition.yml
  name: ApplicationGatewayPrivateFrontend.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a private frontend definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdateAlt<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
