items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  id: _docker_context_initializer
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.DockerContextInitializer()
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.DockerContextInitializer(FileFactory,DockerContextPoller)
  - com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.initialize(Telemetry)
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.yml
  langs:
  - java
  name: DockerContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
    startLine: 43
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>This initializer is required for Docker awareness. The initializer has two goals: 1) Identify Docker context file injected by Application Insight for Docker container and initialize telemetries with Docker context. 2) Write SDK context file which enables the Application Insights for Docker container to discover containers with integrated SDK, and stop sending performance counters in that case (SDK provides OOB performance counters). </p>
  syntax:
    content: public class DockerContextInitializer implements TelemetryInitializer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_initializer
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.DockerContextInitializer()
  id: DockerContextInitializer()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.yml
  langs:
  - java
  name: DockerContextInitializer()
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer.DockerContextInitializer()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
    startLine: 60
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  summary: <p>Constructs new . The constructor start a dedicated thread that periodically checks if a context file exists, and if so, updates the docker context. </p>
  syntax:
    content: public DockerContextInitializer()
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.DockerContextInitializer(FileFactory,DockerContextPoller)
  id: DockerContextInitializer(FileFactory,DockerContextPoller)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.yml
  langs:
  - java
  name: DockerContextInitializer(FileFactory fileFactory, DockerContextPoller dockerContextPoller)
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer.DockerContextInitializer(FileFactory fileFactory, DockerContextPoller dockerContextPoller)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
    startLine: 49
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  syntax:
    content: protected DockerContextInitializer(FileFactory fileFactory, DockerContextPoller dockerContextPoller)
    parameters:
    - id: fileFactory
      type: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
    - id: dockerContextPoller
      type: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.initialize(Telemetry)
  id: initialize(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer
  href: com.microsoft.applicationinsights.extensibility.initializer.docker._docker_context_initializer.yml
  langs:
  - java
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer.initialize(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java
    startLine: 69
  package: com.microsoft.applicationinsights.extensibility.initializer.docker
  summary: <p>Initialize the given telemetry with the Docker context. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>A Telemetry to initialize. </p>
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_initializer.initialize(Telemetry)
references:
- uid: com.microsoft.applicationinsights.extensibility._telemetry_initializer
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_initializer.yml
  name: TelemetryInitializer
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryInitializer
  type: Interface
  summary: <p>Created by gupele on 12/30/2014. </p>
  syntax:
    content: public interface TelemetryInitializer
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._file_factory.yml
  name: FileFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.FileFactory
  type: Class
  summary: <p>Created by yonisha on 8/3/2015. </p>
  syntax:
    content: public class FileFactory
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_poller.yml
  name: DockerContextPoller
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextPoller
  type: Class
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextPoller
- uid: com.microsoft.applicationinsights.extensibility._telemetry_initializer.initialize(Telemetry)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_initializer
  href: com.microsoft.applicationinsights.extensibility._telemetry_initializer.yml
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryInitializer.initialize(Telemetry telemetry)
  type: Method
  summary: <p>Initializes properties of the specified object. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry
