items:
- uid: com.microsoft.applicationinsights.agent.internal.agent
  id: agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var
  - com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var
  - com.microsoft.applicationinsights.agent.internal.agent._agent_implementation
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  - com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  - com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
  - com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory
  - com.microsoft.applicationinsights.agent.internal.agent._code_injector
  - com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  - com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor
  - com.microsoft.applicationinsights.agent.internal.agent._http_client_method_visitor
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  - com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
  - com.microsoft.applicationinsights.agent.internal.agent._ok_http_async_call_method_visitor
  - com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor
  - com.microsoft.applicationinsights.agent.internal.agent._ok_http_method_visitor
  - com.microsoft.applicationinsights.agent.internal.agent._rest_template_method_visitor
  href: com.microsoft.applicationinsights.agent.internal.agent.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.agent
  fullName: com.microsoft.applicationinsights.agent.internal.agent
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AbstractHttpMethodVisitor.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AbstractHttpMethodVisitor.java
    startLine: 21
  syntax:
    content: namespace agent
references:
- uid: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  href: com.microsoft.applicationinsights.agent.internal.agent.exceptions.yml
  name: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  fullName: com.microsoft.applicationinsights.agent.internal.agent.exceptions
  type: Namespace
  syntax:
    content: namespace exceptions
- uid: com.microsoft.applicationinsights.agent.internal.agent.http
  href: com.microsoft.applicationinsights.agent.internal.agent.http.yml
  name: com.microsoft.applicationinsights.agent.internal.agent.http
  fullName: com.microsoft.applicationinsights.agent.internal.agent.http
  type: Namespace
  syntax:
    content: namespace http
- uid: com.microsoft.applicationinsights.agent.internal.agent.jmx
  href: com.microsoft.applicationinsights.agent.internal.agent.jmx.yml
  name: com.microsoft.applicationinsights.agent.internal.agent.jmx
  fullName: com.microsoft.applicationinsights.agent.internal.agent.jmx
  type: Namespace
  syntax:
    content: namespace jmx
- uid: com.microsoft.applicationinsights.agent.internal.agent.redis
  href: com.microsoft.applicationinsights.agent.internal.agent.redis.yml
  name: com.microsoft.applicationinsights.agent.internal.agent.redis
  fullName: com.microsoft.applicationinsights.agent.internal.agent.redis
  type: Namespace
  syntax:
    content: namespace redis
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql
  href: com.microsoft.applicationinsights.agent.internal.agent.sql.yml
  name: com.microsoft.applicationinsights.agent.internal.agent.sql
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql
  type: Namespace
  syntax:
    content: namespace sql
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter.yml
  name: AdvancedAdviceAdapter
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter
  type: Class
  summary: >-
    <p>A base class that lets its derived classes to enjoy utilities like creating temporary variables, managing methods points, method names etc.</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class AdvancedAdviceAdapter
- uid: com.microsoft.applicationinsights.agent.internal.agent._agent_implementation
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._agent_implementation.yml
  name: AgentImplementation
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AgentImplementation
  type: Class
  summary: <p>Created by gupele on 5/6/2015. </p>
  syntax:
    content: public class AgentImplementation
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.yml
  name: ByteCodeTransformer
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ByteCodeTransformer
  type: Interface
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public interface ByteCodeTransformer
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_utils.yml
  name: ByteCodeUtils
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ByteCodeUtils
  type: Class
  summary: <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class ByteCodeUtils
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_to_method_transformation_data.yml
  name: ClassToMethodTransformationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassToMethodTransformationData
  type: Interface
  summary: >-
    <p>A marker to allow Class Visitors to pass data to Method Visitors</p>

    <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface ClassToMethodTransformationData
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_visitor_factory.yml
  name: ClassVisitorFactory
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassVisitorFactory
  type: Interface
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface ClassVisitorFactory
- uid: com.microsoft.applicationinsights.agent.internal.agent._code_injector
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._code_injector.yml
  name: CodeInjector
  fullName: com.microsoft.applicationinsights.agent.internal.agent.CodeInjector
  type: Class
  summary: >-
    <p>The class is responsible for finding needed classes</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class CodeInjector
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._default_class_visitor.yml
  name: DefaultClassVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.DefaultClassVisitor
  type: Class
  summary: >-
    <p>The class is responsible for identifying public methods on non-interface classes. When a method is found the class will call the <xref href="com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class DefaultClassVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._default_method_visitor.yml
  name: DefaultMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.DefaultMethodVisitor
  type: Class
  summary: >-
    <p>This class is responsible for finding where the method starts and ends.</p>

    <p>When the method starts, the class will inject byte code that will call our code with the class name method name and the arguments, and when the method ends will call again with the method name and the result or exception if there is one, the class will make sure that the original code's behavior is not changed</p>

    <p>Created by gupele on 5/11/2015. </p>
  syntax:
    content: public class DefaultMethodVisitor extends AdvancedAdviceAdapter
- uid: com.microsoft.applicationinsights.agent.internal.agent._http_client_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._http_client_method_visitor.yml
  name: HttpClientMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.HttpClientMethodVisitor
  type: Class
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public class HttpClientMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  name: MethodInstrumentationDecision
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision
  type: Class
  summary: >-
    <p>The class holds the type of actions that should be done on an instrumented method The class is the 'decision' for the method after taking into consideration init/configuration data</p>

    <p>Note, it is recommended to build an instance with <ref refid="" kindref="compound">com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecisionBuilder</ref></p>

    <p>Created by gupele on 5/31/2015. </p>
  syntax:
    content: public class MethodInstrumentationDecision
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_info.yml
  name: MethodInstrumentationInfo
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationInfo
  type: Class
  summary: >-
    <p>The class holds the data for methods. The class should collect data for methods of one class.</p>

    <p>For each method the class holds a <xref href="com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision" data-throw-if-not-resolved="false"></xref> that will be used later on if the method of the class is found in runtime.</p>

    <p>The class knows how to 'merge' the information of methods so methods without signatures mean that all methods with that name qualify. to mark all the methods, set priority between methods</p>

    <p>Created by gupele on 5/29/2015. </p>
  syntax:
    content: public class MethodInstrumentationInfo
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.yml
  name: MethodVisitorFactory
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodVisitorFactory
  type: Interface
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface MethodVisitorFactory
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_async_call_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_async_call_method_visitor.yml
  name: OkHttpAsyncCallMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.OkHttpAsyncCallMethodVisitor
  type: Class
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public class OkHttpAsyncCallMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_class_visitor.yml
  name: OkHttpClassVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.OkHttpClassVisitor
  type: Class
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public class OkHttpClassVisitor extends DefaultClassVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._ok_http_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._ok_http_method_visitor.yml
  name: OkHttpMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.OkHttpMethodVisitor
  type: Class
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public class OkHttpMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._rest_template_method_visitor
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._rest_template_method_visitor.yml
  name: RestTemplateMethodVisitor
  fullName: com.microsoft.applicationinsights.agent.internal.agent.RestTemplateMethodVisitor
  type: Class
  summary: <p>Created by gupele on 8/2/2015. </p>
  syntax:
    content: public class RestTemplateMethodVisitor
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._exit_status.yml
  name: AdvancedAdviceAdapter.ExitStatus
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.ExitStatus
  type: Enum
  syntax:
    content: protected enum ExitStatus
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_array_var.yml
  name: AdvancedAdviceAdapter.TempArrayVar
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempArrayVar
  type: Class
  syntax:
    content: protected class TempArrayVar
- uid: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._advanced_advice_adapter._temp_var.yml
  name: AdvancedAdviceAdapter.TempVar
  fullName: com.microsoft.applicationinsights.agent.internal.agent.AdvancedAdviceAdapter.TempVar
  type: Class
  syntax:
    content: protected class TempVar
