items:
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils_test
  id: _local_strings_utils_test
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._local_strings_utils_test.test()
  - com.microsoft.applicationinsights.internal.util._local_strings_utils_test.testGenerateRandomIdWithNoDashes()
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils_test.yml
  langs:
  - java
  name: LocalStringsUtilsTest
  fullName: com.microsoft.applicationinsights.internal.util.LocalStringsUtilsTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtilsTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtilsTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public class LocalStringsUtilsTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils_test.test()
  id: test()
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils_test.yml
  langs:
  - java
  name: test()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalStringsUtilsTest.test()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtilsTest.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void test()
- uid: com.microsoft.applicationinsights.internal.util._local_strings_utils_test.testGenerateRandomIdWithNoDashes()
  id: testGenerateRandomIdWithNoDashes()
  parent: com.microsoft.applicationinsights.internal.util._local_strings_utils_test
  href: com.microsoft.applicationinsights.internal.util._local_strings_utils_test.yml
  langs:
  - java
  name: testGenerateRandomIdWithNoDashes()
  fullName: void com.microsoft.applicationinsights.internal.util.LocalStringsUtilsTest.testGenerateRandomIdWithNoDashes()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtilsTest.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testGenerateRandomIdWithNoDashes()
references: []
