items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
  id: _docker_context_factory
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.createDockerContext(File)
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.yml
  langs:
  - java
  name: DockerContextFactory
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextFactory
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextFactory.java
    startLine: 30
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  summary: <p>Created by yonisha on 7/29/2015. </p>
  syntax:
    content: public class DockerContextFactory
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.createDockerContext(File)
  id: createDockerContext(File)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context_factory.yml
  langs:
  - java
  name: createDockerContext(File contextFile)
  fullName: DockerContext com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContextFactory.createDockerContext(File contextFile)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextFactory.java
    startLine: 31
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public DockerContext createDockerContext(File contextFile)
    parameters:
    - id: contextFile
      type: 8291270b
    return:
      type: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
references:
- uid: 8291270b
  spec.java:
  - name: File
    fullName: File
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  name: DockerContext
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext
  type: Class
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>Represents the Docker context, which includes the host name, image name, container name and container ID. The Docker context file is written in the following structure: Docker host=host_name,Docker image=image_name,Docker container id=con_id,Docker container name=con_name </p>
  syntax:
    content: public class DockerContext
