items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware
  id: _performance_counter_configuration_aware
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.addConfigurationData(PerformanceCountersXmlElement)
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.yml
  langs:
  - java
  name: PerformanceCounterConfigurationAware
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterConfigurationAware
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterConfigurationAware.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterConfigurationAware.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>This class should by performance modules who wish to work with the configuration data.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public interface PerformanceCounterConfigurationAware
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.addConfigurationData(PerformanceCountersXmlElement)
  id: addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.yml
  langs:
  - java
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterConfigurationAware.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterConfigurationAware.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
references:
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_f3ddd60991bc37760f0025adbba6a6b8e
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  name: JvmPerformanceCountersModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule
  type: Class
  summary: >-
    <p>The class loads the relevant Jvm PCs</p>

    <p>By default the class will create all the JVM PC</p>

    <p>The class will not be activated if the enclosing XML tag will have the 'UseBuiltIn' tag set to false:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;UseBuiltIn&gt;false&lt;/UseBuiltIn&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>All Jvm PCs can be disabled like this, without disabling the other built in performance counters:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline></codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Jvm<sp></sp>enabled="false"/&gt;</highlight>

          </codeline>

          <codeline></codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>A specific Jvm counter can be disabled like this:</p>

    <p>

      <preformatted>

        <programlisting>

          <codeline>

            <highlight class="normal">&lt;PerformanceCounters&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;Jvm&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;JvmPC<sp></sp>name="ThreadDeadLockDetector"<sp></sp>enabled="false"/&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">

              <sp></sp>

              <sp></sp>

              <sp></sp>

              <sp></sp>&lt;/Jvm&gt;</highlight>

          </codeline>

          <codeline>

            <highlight class="normal">&lt;/PerformanceCounters&gt;</highlight>

          </codeline>

        </programlisting>

      </preformatted>

    </p>

    <p>Created by gupele on 8/7/2016. </p>
  syntax:
    content: public class JvmPerformanceCountersModule extends AbstractPerformanceCounterModule implements PerformanceCounterConfigurationAware
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  name: ProcessPerformanceCountersModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule
  type: Class
  summary: >-
    <p>The class will be used when the SDK needs to add the 'built-in' performance counters.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public class ProcessPerformanceCountersModule
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  summary: <p>This method checks for Windows performance counters from the configuration. The method will work only if the process is activated under Windows OS. The method will initialize the connection to the native code using <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> and then will go through the requested performance counters, normalize them, and will hand them to the factory. </p>
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
      description: <p>The configuration of that section </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._jvm_performance_counters_module.yml
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.JvmPerformanceCountersModule.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  name: PerformanceCountersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class PerformanceCountersXmlElement
