items:
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  id: _telemetry_configuration_factory
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.createInstance(String,Class<T>)
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.createInstance(String,Class<T>,Class<A>,A)
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.EXTERNAL_PROPERTY_IKEY_NAME()
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.initialize(TelemetryConfiguration)
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.setBuilder(AppInsightsConfigurationBuilder)
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.setPerformanceCountersSection(String)
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.TelemetryConfigurationFactory()
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: TelemetryConfigurationFactory
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory
  type: Enum
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Initializer class for configuration instances. </p>
  syntax:
    content: public enum TelemetryConfigurationFactory
  inheritance:
  - java.lang.Object
  - java.lang.Enum<TelemetryConfigurationFactory>
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory_1aef8ce53e57ce75dff82164445b4125f3
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.createInstance(String,Class<T>)
  id: createInstance(String,Class<T>)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: createInstance(String className, Class<T> interfaceClass)
  fullName: private<T> T com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.createInstance(String className, Class<T> interfaceClass)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 435
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Creates an instance from its name. We suppress Java compiler warnings for Generic casting</p>

    <p>Note that currently we 'swallow' all exceptions and simply return null if we fail</p>

    <p></p>
  syntax:
    content: public private<T> T createInstance(String className, Class<T> interfaceClass)
    parameters:
    - id: className
      type: "26831127"
      description: <p>The class we create an instance of </p>
    - id: interfaceClass
      type: ffb09d2d
      description: <p>The class' parent interface we wish to work with </p>
    return:
      type: ecd321b9
      description: <p>The instance or null if failed </p>
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.createInstance(String,Class<T>,Class<A>,A)
  id: createInstance(String,Class<T>,Class<A>,A)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: createInstance(String className, Class<T> interfaceClass, Class<A> argumentClass, A argument)
  fullName: private<T, A> T com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.createInstance(String className, Class<T> interfaceClass, Class<A> argumentClass, A argument)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 454
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Creates an instance from its name. We suppress Java compiler warnings for Generic casting The class is created by using a constructor that has one parameter which is sent to the method</p>

    <p>Note that currently we 'swallow' all exceptions and simply return null if we fail</p>

    <p></p>
  syntax:
    content: public private<T, A> T createInstance(String className, Class<T> interfaceClass, Class<A> argumentClass, A argument)
    parameters:
    - id: className
      type: "26831127"
      description: <p>The class we create an instance of </p>
    - id: interfaceClass
      type: ffb09d2d
      description: <p>The class' parent interface we wish to work with </p>
    - id: argumentClass
      type: 68184f3d
      description: <p>Type of class to use as argument for Ctor </p>
    - id: argument
      type: 7062c57f
      description: <p>The argument to pass the Ctor </p>
    return:
      type: 6999c32f
      description: <p>The instance or null if failed </p>
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.EXTERNAL_PROPERTY_IKEY_NAME()
  id: EXTERNAL_PROPERTY_IKEY_NAME()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: EXTERNAL_PROPERTY_IKEY_NAME
  fullName: " static  final String com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.EXTERNAL_PROPERTY_IKEY_NAME"
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 64
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public static final String EXTERNAL_PROPERTY_IKEY_NAME= "APPLICATION_INSIGHTS_IKEY"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.initialize(TelemetryConfiguration)
  id: initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: initialize(TelemetryConfiguration configuration)
  fullName: final void com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfiguration configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.config
  summary: >-
    <p>Currently we do the following:</p>

    <p>Set Instrumentation Key Set Developer Mode (default false) Set Channel (default <ref refid="" kindref="compound">InProcessTelemetryChannel</ref>) Set Tracking Disabled Mode (default false) Set Context Initializers where they should be written with full package name Set Telemetry Initializers where they should be written with full package name </p>
  syntax:
    content: public final void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration that will be populated </p>
    return:
      type: 3f6357ce
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.setBuilder(AppInsightsConfigurationBuilder)
  id: setBuilder(AppInsightsConfigurationBuilder)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: setBuilder(AppInsightsConfigurationBuilder builder)
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.setBuilder(AppInsightsConfigurationBuilder builder)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 476
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setBuilder(AppInsightsConfigurationBuilder builder)
    parameters:
    - id: builder
      type: 66faa47f
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.setPerformanceCountersSection(String)
  id: setPerformanceCountersSection(String)
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: setPerformanceCountersSection(String performanceCountersSection)
  fullName: void com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.setPerformanceCountersSection(String performanceCountersSection)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 472
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setPerformanceCountersSection(String performanceCountersSection)
    parameters:
    - id: performanceCountersSection
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.TelemetryConfigurationFactory()
  id: TelemetryConfigurationFactory()
  parent: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory
  href: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory.yml
  langs:
  - java
  name: TelemetryConfigurationFactory()
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.TelemetryConfigurationFactory()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public TelemetryConfigurationFactory()
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: 3f6357ce
  spec.java:
  - name: final void
    fullName: final void
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: ffb09d2d
  spec.java:
  - name: Class<T>
    fullName: Class<T>
- uid: ecd321b9
  spec.java:
  - name: private<T> T
    fullName: private<T> T
- uid: 68184f3d
  spec.java:
  - name: Class<A>
    fullName: Class<A>
- uid: 7062c57f
  spec.java:
  - name: A
    fullName: A
- uid: 6999c32f
  spec.java:
  - name: private<T, A> T
    fullName: private<T, A> T
- uid: 66faa47f
  spec.java:
  - name: AppInsightsConfigurationBuilder
    fullName: AppInsightsConfigurationBuilder
- uid: com.microsoft.applicationinsights.internal.config._telemetry_configuration_factory_1aef8ce53e57ce75dff82164445b4125f3
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
- uid: com.microsoft.applicationinsights.internal.config._application_insights_xml_configuration
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._application_insights_xml_configuration.yml
  name: ApplicationInsightsXmlConfiguration
  fullName: com.microsoft.applicationinsights.internal.config.ApplicationInsightsXmlConfiguration
  type: Class
  summary: <p>Created by gupele on 3/13/2015. </p>
  syntax:
    content: public class ApplicationInsightsXmlConfiguration
- uid: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._s_d_k_logger_xml_element.yml
  name: SDKLoggerXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.SDKLoggerXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class SDKLoggerXmlElement
- uid: com.microsoft.applicationinsights.internal.config._telemetry_initializers_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_initializers_xml_element.yml
  name: TelemetryInitializersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryInitializersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class TelemetryInitializersXmlElement
- uid: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._context_initializers_xml_element.yml
  name: ContextInitializersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ContextInitializersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class ContextInitializersXmlElement
- uid: com.microsoft.applicationinsights.extensibility._telemetry_processor
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_processor.yml
  name: TelemetryProcessor
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryProcessor
  type: Interface
  summary: "<p>The method gets a <ref refid=\"\" kindref=\"compound\">Telemetry</ref> instance that is ready to be sent. This is your chance to approve or deny it. Returning 'false' means that the Telemetry will not be sent while 'true' means you approve it.</p>\r\n<p>The Telemetry might go through other filters though, that might deny its sending.</p>\r\n<p>To enable this processor you need to add it in the ApplicationInsights.xml like this:</p>\r\n<p>\r\n  <preformatted>\r\n    <programlisting>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Processor<sp></sp>type=\"full.path.to.Filter\"&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;Add<sp></sp>name=\"Property\"<sp></sp>value=\"stringValue\"/&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/Processor&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>\r\n          <sp></sp>&lt;/CustomProcessors&gt;</highlight>\r\n      </codeline>\r\n      <codeline>\r\n        <highlight class=\"normal\">&lt;/TelemetryProcessors&gt;</highlight>\r\n      </codeline>\r\n    </programlisting> \r\n*</preformatted>\r\n</p>\r\n<p>Note that the class defines a property named 'Property' which is configured too. Every property that you wish to configure needs to have a 'setX' public method like 'setProperty' in this example <bold>Exceptions thrown from the 'setX' methods will be caught by the framework that will ignore the filter</bold></p>\r\n<p>Created by gupele on 7/26/2016. </p>"
  syntax:
    content: public interface TelemetryProcessor
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: TelemetryModule
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface TelemetryModule
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  name: PerformanceCountersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class PerformanceCountersXmlElement
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  name: JmxXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxXmlElement
- uid: com.microsoft.applicationinsights.internal.config._channel_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._channel_xml_element.yml
  name: ChannelXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.ChannelXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class ChannelXmlElement
- uid: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._telemetry_processor_xml_element.yml
  name: TelemetryProcessorXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.TelemetryProcessorXmlElement
  type: Class
  summary: <p>Created by gupele on 7/26/2016. </p>
  syntax:
    content: public class TelemetryProcessorXmlElement
