items:
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  id: _transmission_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel
  children:
  - com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.dispatch(Transmission)
  - com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.stop(long,TimeUnit)
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  langs:
  - java
  name: TransmissionDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionDispatcher.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionDispatcher.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.channel
  summary: >-
    <p>A dispatcher should know how and to whom to dispatch a <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public interface TransmissionDispatcher
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.dispatch(Transmission)
  id: dispatch(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  langs:
  - java
  name: dispatch(Transmission transmission)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher.dispatch(Transmission transmission)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionDispatcher.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public void dispatch(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
- uid: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.stop(long,TimeUnit)
  id: stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher
  href: com.microsoft.applicationinsights.internal.channel._transmission_dispatcher.yml
  langs:
  - java
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.TransmissionDispatcher.stop(long timeout, TimeUnit timeUnit)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionDispatcher.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.channel
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 02b8628b
  spec.java:
  - name: TimeUnit
    fullName: TimeUnit
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  name: NonBlockingDispatcher
  fullName: com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher
  type: Class
  summary: >-
    <p>The class implements <xref href="com.microsoft.applicationinsights.internal.channel._transmission_dispatcher" data-throw-if-not-resolved="false"></xref></p>

    <p>Basically, the class tries to find one <xref href="com.microsoft.applicationinsights.internal.channel._transmission_output" data-throw-if-not-resolved="false"></xref> that will accept the incoming <xref href="com.microsoft.applicationinsights.internal.channel.common._transmission" data-throw-if-not-resolved="false"></xref>.</p>

    <p>It is a non blocking behavior in the sense that if no one can accept it will drop the data</p>

    <p>Created by gupele on 12/18/2014. </p>
  syntax:
    content: public class NonBlockingDispatcher implements TransmissionDispatcher
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.dispatch(Transmission)
  parent: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  name: dispatch(Transmission transmission)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher.dispatch(Transmission transmission)
  type: Method
  syntax:
    content: public void dispatch(Transmission transmission)
    parameters:
    - id: transmission
      type: com.microsoft.applicationinsights.internal.channel.common._transmission
- uid: com.microsoft.applicationinsights.internal.channel.common._transmission
  parent: com.microsoft.applicationinsights.internal.channel.common
  href: com.microsoft.applicationinsights.internal.channel.common._transmission.yml
  name: Transmission
  fullName: com.microsoft.applicationinsights.internal.channel.common.Transmission
  type: Class
  summary: >-
    <p>Holds the stuff that defines a transmission of data to the server. It also holds the meta data that describes the content, for example encoding type</p>

    <p>Created by gupele on 12/17/2014. </p>
  syntax:
    content: public class Transmission
- uid: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.stop(long,TimeUnit)
  parent: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher
  href: com.microsoft.applicationinsights.internal.channel.common._non_blocking_dispatcher.yml
  name: stop(long timeout, TimeUnit timeUnit)
  fullName: void com.microsoft.applicationinsights.internal.channel.common.NonBlockingDispatcher.stop(long timeout, TimeUnit timeUnit)
  type: Method
  syntax:
    content: public void stop(long timeout, TimeUnit timeUnit)
    parameters:
    - id: timeout
      type: 0364520f
    - id: timeUnit
      type: 02b8628b
