items:
- uid: com.microsoft.azure.documentdb.internal._i_database_account_configuration_provider
  id: _i_database_account_configuration_provider
  parent: com.microsoft.azure.documentdb.internal
  href: com.microsoft.azure.documentdb.internal._i_database_account_configuration_provider.yml
  langs:
  - java
  name: IDatabaseAccountConfigurationProvider
  fullName: com.microsoft.azure.documentdb.internal.IDatabaseAccountConfigurationProvider
  type: Class
  source:
    remote:
      path: src/main/java/com/microsoft/azure/documentdb/internal/IDatabaseAccountConfigurationProvider.java
      branch: master
      repo: https://github.com/Azure/azure-documentdb-java
    path: src/main/java/com/microsoft/azure/documentdb/internal/IDatabaseAccountConfigurationProvider.java
    startLine: 2
  package: com.microsoft.azure.documentdb.internal
  syntax:
    content: public class IDatabaseAccountConfigurationProvider
  inheritance:
  - java.lang.Object
references: []
