items:
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  id: _jvm_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._jvm_xml_element.getName()
  - com.microsoft.applicationinsights.internal.config._jvm_xml_element.isEnabled()
  - com.microsoft.applicationinsights.internal.config._jvm_xml_element.setEnabled(boolean)
  - com.microsoft.applicationinsights.internal.config._jvm_xml_element.setName(String)
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  langs:
  - java
  name: JvmXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JvmXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 8/8/2016. </p>
  syntax:
    content: public class JvmXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element.getName()
  id: getName()
  parent: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  langs:
  - java
  name: getName()
  fullName: String com.microsoft.applicationinsights.internal.config.JvmXmlElement.getName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element.isEnabled()
  id: isEnabled()
  parent: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  langs:
  - java
  name: isEnabled()
  fullName: boolean com.microsoft.applicationinsights.internal.config.JvmXmlElement.isEnabled()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public boolean isEnabled()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element.setEnabled(boolean)
  id: setEnabled(boolean)
  parent: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  langs:
  - java
  name: setEnabled(boolean enabled)
  fullName: void com.microsoft.applicationinsights.internal.config.JvmXmlElement.setEnabled(boolean enabled)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
    startLine: 48
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setEnabled(boolean enabled)
    parameters:
    - id: enabled
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.config._jvm_xml_element.setName(String)
  id: setName(String)
  parent: com.microsoft.applicationinsights.internal.config._jvm_xml_element
  href: com.microsoft.applicationinsights.internal.config._jvm_xml_element.yml
  langs:
  - java
  name: setName(String name)
  fullName: void com.microsoft.applicationinsights.internal.config.JvmXmlElement.setName(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setName(String name)
    parameters:
    - id: name
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
