items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  id: _docker_context
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.DockerContext(String)
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.getHostName()
  - com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.getProperties()
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  langs:
  - java
  name: DockerContext
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContext.java
    startLine: 33
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  summary: >-
    <p>Created by yonisha on 7/29/2015.</p>

    <p>Represents the Docker context, which includes the host name, image name, container name and container ID. The Docker context file is written in the following structure: Docker host=host_name,Docker image=image_name,Docker container id=con_id,Docker container name=con_name </p>
  syntax:
    content: public class DockerContext
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.DockerContext(String)
  id: DockerContext(String)
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  langs:
  - java
  name: DockerContext(String json)
  fullName: com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext.DockerContext(String json)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContext.java
    startLine: 37
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public DockerContext(String json)
    parameters:
    - id: json
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.getHostName()
  id: getHostName()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  langs:
  - java
  name: getHostName()
  fullName: String com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext.getHostName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContext.java
    startLine: 41
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public String getHostName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.getProperties()
  id: getProperties()
  parent: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context
  href: com.microsoft.applicationinsights.extensibility.initializer.docker.internal._docker_context.yml
  langs:
  - java
  name: getProperties()
  fullName: Map<String, String> com.microsoft.applicationinsights.extensibility.initializer.docker.internal.DockerContext.getProperties()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContext.java
    startLine: 45
  package: com.microsoft.applicationinsights.extensibility.initializer.docker.internal
  syntax:
    content: public Map<String, String> getProperties()
    return:
      type: 689c8cb5
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
