items:
- uid: com.microsoft.azure.management.network._application_gateway_private_frontend._definition
  id: _definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_frontend._definition.yml
  langs:
  - java
  name: ApplicationGatewayPrivateFrontend.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.Definition<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPrivateFrontend.java
    startLine: 63
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of a private frontend definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends ApplicationGatewayPrivateFrontend.DefinitionStages.Blank<ParentT>,ApplicationGatewayPrivateFrontend.DefinitionStages.WithAttach<ParentT>,ApplicationGatewayPrivateFrontend.DefinitionStages.WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.attach()
  - com.microsoft.azure.management.network._application_gateway_private_fron48198a57ccf2650316dedaa246f26afc.withExistingSubnet(Network,String)
  - com.microsoft.azure.management.resources.fluentcore.arm.models.9c014e99091be50528513a9a81da5b2c.withExistingSubnet(String,String)
  - com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882.withPrivateIpAddressStatic(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinitionAlt<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_private_fron48198a57ccf2650316dedaa246f26afc.withExistingSubnet(Network,String)
  parent: com.microsoft.azure.management.network._application_gateway_private_fron48198a57ccf2650316dedaa246f26afc
  href: com.microsoft.azure.management.network._application_gateway_private_fron48198a57ccf2650316dedaa246f26afc.yml
  name: withExistingSubnet(Network network, String subnetName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.DefinitionStages.WithSubnet<ParentT>.withExistingSubnet(Network network, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this private frontend. </p>
  syntax:
    content: public WithAttach<ParentT> withExistingSubnet(Network network, String subnetName)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network the subnet exists in </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_private_fron66f8f6cf613eea9752868313fd48975dda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.9c014e99091be50528513a9a81da5b2c.withExistingSubnet(String,String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.9c014e99091be50528513a9a81da5b2c
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.9c014e99091be50528513a9a81da5b2c.yml
  name: withExistingSubnet(String parentNetworkResourceId, String subnetName)
  fullName: ReturnT com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.DefinitionStages.WithSubnet<ReturnT>.withExistingSubnet(String parentNetworkResourceId, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this resource. </p>
  syntax:
    content: public ReturnT withExistingSubnet(String parentNetworkResourceId, String subnetName)
    parameters:
    - id: parentNetworkResourceId
      type: "26831127"
      description: <p>the resource ID of the virtual network the subnet is part of </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of the subnet </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882
  href: com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.DefinitionStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882
  href: com.microsoft.azure.management.network.model._has_private_ip_address_740949466219797cb7bd140907274882.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.DefinitionStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_private_fron537c0f029fcf0626f19ff68b2c556c45
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_fron537c0f029fcf0626f19ff68b2c556c45.yml
  name: ApplicationGatewayPrivateFrontend.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.DefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of a private frontend definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayPrivateFrontend.DefinitionStages.WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_private_fron66f8f6cf613eea9752868313fd48975d
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_fron66f8f6cf613eea9752868313fd48975d.yml
  name: ApplicationGatewayPrivateFrontend.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of a private frontend definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the frontend definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_private_fron48198a57ccf2650316dedaa246f26afc
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_private_fron48198a57ccf2650316dedaa246f26afc.yml
  name: ApplicationGatewayPrivateFrontend.DefinitionStages.WithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPrivateFrontend.DefinitionStages.WithSubnet<ParentT>
  type: Interface
  summary: <p>The stage of a private frontend definition allowing to specify a subnet from the selected network. </p>
  syntax:
    content: public interface WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the next stage of the parent definition </p>
