items:
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  id: _method_instrumentation_decision
  parent: com.microsoft.applicationinsights.agent.internal.agent
  children:
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.getMethodVisitorFactory()
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.getThresholdInMS()
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.isReportCaughtExceptions()
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.isReportExecutionTime()
  - com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.MethodInstrumentationDecision(boolean,boolean,MethodVisitorFactory,long)
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  langs:
  - java
  name: MethodInstrumentationDecision
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.agent
  summary: >-
    <p>The class holds the type of actions that should be done on an instrumented method The class is the 'decision' for the method after taking into consideration init/configuration data</p>

    <p>Note, it is recommended to build an instance with <ref refid="" kindref="compound">com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecisionBuilder</ref></p>

    <p>Created by gupele on 5/31/2015. </p>
  syntax:
    content: public class MethodInstrumentationDecision
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.getMethodVisitorFactory()
  id: getMethodVisitorFactory()
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  langs:
  - java
  name: getMethodVisitorFactory()
  fullName: MethodVisitorFactory com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision.getMethodVisitorFactory()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
    startLine: 59
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public MethodVisitorFactory getMethodVisitorFactory()
    return:
      type: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.getThresholdInMS()
  id: getThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  langs:
  - java
  name: getThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision.getThresholdInMS()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
    startLine: 55
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public long getThresholdInMS()
    return:
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.isReportCaughtExceptions()
  id: isReportCaughtExceptions()
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  langs:
  - java
  name: isReportCaughtExceptions()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision.isReportCaughtExceptions()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
    startLine: 47
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public boolean isReportCaughtExceptions()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.isReportExecutionTime()
  id: isReportExecutionTime()
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  langs:
  - java
  name: isReportExecutionTime()
  fullName: boolean com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision.isReportExecutionTime()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
    startLine: 51
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public boolean isReportExecutionTime()
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.MethodInstrumentationDecision(boolean,boolean,MethodVisitorFactory,long)
  id: MethodInstrumentationDecision(boolean,boolean,MethodVisitorFactory,long)
  parent: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision
  href: com.microsoft.applicationinsights.agent.internal.agent._method_instrumentation_decision.yml
  langs:
  - java
  name: MethodInstrumentationDecision(boolean reportCaughtExceptions, boolean reportExecutionTime, MethodVisitorFactory methodVisitorFactory, long thresholdInMS)
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodInstrumentationDecision.MethodInstrumentationDecision(boolean reportCaughtExceptions, boolean reportExecutionTime, MethodVisitorFactory methodVisitorFactory, long thresholdInMS)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/MethodInstrumentationDecision.java
    startLine: 37
  package: com.microsoft.applicationinsights.agent.internal.agent
  syntax:
    content: public MethodInstrumentationDecision(boolean reportCaughtExceptions, boolean reportExecutionTime, MethodVisitorFactory methodVisitorFactory, long thresholdInMS)
    parameters:
    - id: reportCaughtExceptions
      type: 4fc6e284
    - id: reportExecutionTime
      type: 4fc6e284
    - id: methodVisitorFactory
      type: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
    - id: thresholdInMS
      type: 0364520f
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._method_visitor_factory.yml
  name: MethodVisitorFactory
  fullName: com.microsoft.applicationinsights.agent.internal.agent.MethodVisitorFactory
  type: Interface
  summary: <p>Created by gupele on 7/27/2015. </p>
  syntax:
    content: public interface MethodVisitorFactory
