items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants
  id: _constants
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._constants.CPU_PC_COUNTER_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.DEFAULT_DOUBLE_VALUE()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.INSTANCE_NAME_TOTAL()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PERFORMANCE_COUNTER_PREFIX()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_CATEGORY()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_CPU_PC_ID()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_IO_PC_COUNTER_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_IO_PC_ID()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_MEM_PC_COUNTER_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_MEM_PC_ID()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_CPU_PC_CATEGORY_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_CPU_PC_ID()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_MEMORY_PC_CATEGORY_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_MEMORY_PC_COUNTER_NAME()
  - com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_MEMORY_PC_ID()
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: Constants
  fullName: com.microsoft.applicationinsights.internal.perfcounter.Constants
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 26
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>Created by gupele on 3/8/2015. </p>
  syntax:
    content: public class Constants
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.CPU_PC_COUNTER_NAME()
  id: CPU_PC_COUNTER_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: CPU_PC_COUNTER_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.CPU_PC_COUNTER_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String CPU_PC_COUNTER_NAME= "% Processor Time"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.DEFAULT_DOUBLE_VALUE()
  id: DEFAULT_DOUBLE_VALUE()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: DEFAULT_DOUBLE_VALUE
  fullName: final double com.microsoft.applicationinsights.internal.perfcounter.Constants.DEFAULT_DOUBLE_VALUE
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 53
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final double DEFAULT_DOUBLE_VALUE= -1.0
    return:
      type: bc185a0c
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.INSTANCE_NAME_TOTAL()
  id: INSTANCE_NAME_TOTAL()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: INSTANCE_NAME_TOTAL
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.INSTANCE_NAME_TOTAL
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 49
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String INSTANCE_NAME_TOTAL= "_Total"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PERFORMANCE_COUNTER_PREFIX()
  id: PERFORMANCE_COUNTER_PREFIX()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PERFORMANCE_COUNTER_PREFIX
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PERFORMANCE_COUNTER_PREFIX
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PERFORMANCE_COUNTER_PREFIX= "JSDK_"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_CATEGORY()
  id: PROCESS_CATEGORY()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PROCESS_CATEGORY
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PROCESS_CATEGORY
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_CATEGORY= "Process"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_CPU_PC_ID()
  id: PROCESS_CPU_PC_ID()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PROCESS_CPU_PC_ID
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PROCESS_CPU_PC_ID
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_CPU_PC_ID= PERFORMANCE_COUNTER_PREFIX + "ProcessCpuPerformanceCounter"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_IO_PC_COUNTER_NAME()
  id: PROCESS_IO_PC_COUNTER_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PROCESS_IO_PC_COUNTER_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PROCESS_IO_PC_COUNTER_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_IO_PC_COUNTER_NAME= "IO Data Bytes/sec"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_IO_PC_ID()
  id: PROCESS_IO_PC_ID()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PROCESS_IO_PC_ID
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PROCESS_IO_PC_ID
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_IO_PC_ID= PERFORMANCE_COUNTER_PREFIX + "ProcessIOPerformanceCounter"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_MEM_PC_COUNTER_NAME()
  id: PROCESS_MEM_PC_COUNTER_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PROCESS_MEM_PC_COUNTER_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PROCESS_MEM_PC_COUNTER_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_MEM_PC_COUNTER_NAME= "Private Bytes"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.PROCESS_MEM_PC_ID()
  id: PROCESS_MEM_PC_ID()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: PROCESS_MEM_PC_ID
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.PROCESS_MEM_PC_ID
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String PROCESS_MEM_PC_ID= PERFORMANCE_COUNTER_PREFIX + "ProcessMemoryPerformanceCounter"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_CPU_PC_CATEGORY_NAME()
  id: TOTAL_CPU_PC_CATEGORY_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: TOTAL_CPU_PC_CATEGORY_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.TOTAL_CPU_PC_CATEGORY_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String TOTAL_CPU_PC_CATEGORY_NAME= "Processor"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_CPU_PC_ID()
  id: TOTAL_CPU_PC_ID()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: TOTAL_CPU_PC_ID
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.TOTAL_CPU_PC_ID
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String TOTAL_CPU_PC_ID= PERFORMANCE_COUNTER_PREFIX + "TotalCpuPerformanceCounter"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_MEMORY_PC_CATEGORY_NAME()
  id: TOTAL_MEMORY_PC_CATEGORY_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: TOTAL_MEMORY_PC_CATEGORY_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.TOTAL_MEMORY_PC_CATEGORY_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String TOTAL_MEMORY_PC_CATEGORY_NAME= "Memory"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_MEMORY_PC_COUNTER_NAME()
  id: TOTAL_MEMORY_PC_COUNTER_NAME()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: TOTAL_MEMORY_PC_COUNTER_NAME
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.TOTAL_MEMORY_PC_COUNTER_NAME
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 43
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String TOTAL_MEMORY_PC_COUNTER_NAME= "Available Bytes"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.perfcounter._constants.TOTAL_MEMORY_PC_ID()
  id: TOTAL_MEMORY_PC_ID()
  parent: com.microsoft.applicationinsights.internal.perfcounter._constants
  href: com.microsoft.applicationinsights.internal.perfcounter._constants.yml
  langs:
  - java
  name: TOTAL_MEMORY_PC_ID
  fullName: final String com.microsoft.applicationinsights.internal.perfcounter.Constants.TOTAL_MEMORY_PC_ID
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public static final String TOTAL_MEMORY_PC_ID= PERFORMANCE_COUNTER_PREFIX + "TotalMemoryPerformanceCounter"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: bc185a0c
  spec.java:
  - name: final double
    fullName: final double
