items:
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  id: _writer_configuration
  parent: com.microsoft.applicationinsights.collectd.internal
  children:
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.buildConfiguration(OConfigItem)
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.EXCLUDE_CONFIGURATION_KEY()
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.getInstrumentationKey()
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.getIsLoggerEnabled()
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.getPluginExclusions()
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.INSTRUMENTATION_KEY_CONFIGURATION_KEY()
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.SDK_LOGGER_CONFIGURATION_KEY()
  - com.microsoft.applicationinsights.collectd.internal._writer_configuration.setLogger(ApplicationInsightsWriterLogger)
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: WriterConfiguration
  fullName: com.microsoft.applicationinsights.collectd.internal.WriterConfiguration
  type: Class
  source:
    remote: &o0
      path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 37
  package: com.microsoft.applicationinsights.collectd.internal
  summary: >-
    <p>Created by yonisha on 5/5/2015.</p>

    <p>This class purpose is to parse configuration passed from CollectD framework. </p>
  syntax: &o1
    content: public class WriterConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.buildConfiguration(OConfigItem)
  id: buildConfiguration(OConfigItem)
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: buildConfiguration(OConfigItem configuration)
  fullName: static WriterConfiguration com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.buildConfiguration(OConfigItem configuration)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 86
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Builds  from the given CollectD configuration object. </p>
  syntax:
    content: public static WriterConfiguration buildConfiguration(OConfigItem configuration)
    parameters:
    - id: configuration
      type: 910efc2e
      description: <p>The CollectD configuration. </p>
    return:
      type: com.microsoft.applicationinsights.collectd.internal._writer_configuration
      description: <p>The configuration for Application Insights writer plugin. </p>
  exceptions:
  - type: b38cbb9b
    description: <p>Thrown if the configuration is invalid. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.EXCLUDE_CONFIGURATION_KEY()
  id: EXCLUDE_CONFIGURATION_KEY()
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: EXCLUDE_CONFIGURATION_KEY
  fullName: final String com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.EXCLUDE_CONFIGURATION_KEY
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 41
  package: com.microsoft.applicationinsights.collectd.internal
  syntax:
    content: public static final String EXCLUDE_CONFIGURATION_KEY= "Exclude"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.getInstrumentationKey()
  id: getInstrumentationKey()
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: getInstrumentationKey()
  fullName: String com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.getInstrumentationKey()
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 60
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Gets the instrumentation key. </p>
  syntax:
    content: public String getInstrumentationKey()
    return:
      type: "26831127"
      description: <p>The instrumentation key. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.getIsLoggerEnabled()
  id: getIsLoggerEnabled()
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: getIsLoggerEnabled()
  fullName: boolean com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.getIsLoggerEnabled()
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 68
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Gets a value indicating whether the logger is enabled or not. </p>
  syntax:
    content: public boolean getIsLoggerEnabled()
    return:
      type: 4fc6e284
      description: <p>True if the logger is enabled, false otherwise. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.getPluginExclusions()
  id: getPluginExclusions()
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: getPluginExclusions()
  fullName: Map<String, PluginExclusion> com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.getPluginExclusions()
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 76
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Gets a dictionary of excluded plugins and data sources. </p>
  syntax:
    content: public Map<String, PluginExclusion> getPluginExclusions()
    return:
      type: 2108f1f4com.microsoft.applicationinsights.collectd.internal._plugin_exclusiona08ddfce
      description: <p>Dictionary of excluded plugins and data sources. </p>
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.INSTRUMENTATION_KEY_CONFIGURATION_KEY()
  id: INSTRUMENTATION_KEY_CONFIGURATION_KEY()
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: INSTRUMENTATION_KEY_CONFIGURATION_KEY
  fullName: final String com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.INSTRUMENTATION_KEY_CONFIGURATION_KEY
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 42
  package: com.microsoft.applicationinsights.collectd.internal
  syntax:
    content: public static final String INSTRUMENTATION_KEY_CONFIGURATION_KEY= "InstrumentationKey"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.SDK_LOGGER_CONFIGURATION_KEY()
  id: SDK_LOGGER_CONFIGURATION_KEY()
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: SDK_LOGGER_CONFIGURATION_KEY
  fullName: final String com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.SDK_LOGGER_CONFIGURATION_KEY
  type: Field
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 43
  package: com.microsoft.applicationinsights.collectd.internal
  syntax:
    content: public static final String SDK_LOGGER_CONFIGURATION_KEY= "SDKLogger"
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration.setLogger(ApplicationInsightsWriterLogger)
  id: setLogger(ApplicationInsightsWriterLogger)
  parent: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  langs:
  - java
  name: setLogger(ApplicationInsightsWriterLogger newLogger)
  fullName: static void com.microsoft.applicationinsights.collectd.internal.WriterConfiguration.setLogger(ApplicationInsightsWriterLogger newLogger)
  type: Method
  source:
    remote: *o0
    path: collectd/src/main/java/com/microsoft/applicationinsights/collectd/internal/WriterConfiguration.java
    startLine: 148
  package: com.microsoft.applicationinsights.collectd.internal
  summary: <p>Sets the logger for this  </p>
  syntax:
    content: public static void setLogger(ApplicationInsightsWriterLogger newLogger)
    parameters:
    - id: newLogger
      type: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
      description: <p>The logger to use. </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: 2108f1f4com.microsoft.applicationinsights.collectd.internal._plugin_exclusiona08ddfce
  spec.java:
  - name: 'Map<String, '
    fullName: 'Map<String, '
  - uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
    name: PluginExclusion
    fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion
    href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  - name: '>'
    fullName: '>'
- uid: b38cbb9b
  spec.java:
  - name: ConfigurationException
    fullName: ConfigurationException
- uid: 910efc2e
  spec.java:
  - name: OConfigItem
    fullName: OConfigItem
- uid: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger
  parent: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal._application_insights_writer_logger.yml
  name: ApplicationInsightsWriterLogger
  fullName: com.microsoft.applicationinsights.collectd.internal.ApplicationInsightsWriterLogger
  type: Class
  summary: <p>Created by yonisha on 5/4/2015. </p>
  syntax:
    content: public class ApplicationInsightsWriterLogger
- uid: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion
  parent: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal._plugin_exclusion.yml
  name: PluginExclusion
  fullName: com.microsoft.applicationinsights.collectd.internal.PluginExclusion
  type: Class
  summary: >-
    <p>Created by yonisha on 5/5/2015.</p>

    <p>This class represents a plugin and its data source to be excluded. </p>
  syntax:
    content: public class PluginExclusion
- uid: com.microsoft.applicationinsights.collectd.internal._writer_configuration
  parent: com.microsoft.applicationinsights.collectd.internal
  href: com.microsoft.applicationinsights.collectd.internal._writer_configuration.yml
  name: WriterConfiguration
  fullName: com.microsoft.applicationinsights.collectd.internal.WriterConfiguration
  type: Class
  summary: >-
    <p>Created by yonisha on 5/5/2015.</p>

    <p>This class purpose is to parse configuration passed from CollectD framework. </p>
  syntax: *o1
