items:
- uid: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory
  id: _http_cookie_factory
  parent: com.microsoft.applicationinsights.web.internal.cookies
  children:
  - com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.COOKIE_PATH_ALL_URL()
  - com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.generateSessionHttpCookie(RequestTelemetryContext,SessionContext,int)
  - com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.generateUserHttpCookie(RequestTelemetryContext)
  href: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.yml
  langs:
  - java
  name: HttpCookieFactory
  fullName: com.microsoft.applicationinsights.web.internal.cookies.HttpCookieFactory
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/HttpCookieFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/HttpCookieFactory.java
    startLine: 32
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Created by yonisha on 2/26/2015. </p>
  syntax:
    content: public class HttpCookieFactory
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.COOKIE_PATH_ALL_URL()
  id: COOKIE_PATH_ALL_URL()
  parent: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory
  href: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.yml
  langs:
  - java
  name: COOKIE_PATH_ALL_URL
  fullName: String com.microsoft.applicationinsights.web.internal.cookies.HttpCookieFactory.COOKIE_PATH_ALL_URL
  type: Field
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/HttpCookieFactory.java
    startLine: 35
  package: com.microsoft.applicationinsights.web.internal.cookies
  syntax:
    content: public static String COOKIE_PATH_ALL_URL= "/"
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.generateSessionHttpCookie(RequestTelemetryContext,SessionContext,int)
  id: generateSessionHttpCookie(RequestTelemetryContext,SessionContext,int)
  parent: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory
  href: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.yml
  langs:
  - java
  name: generateSessionHttpCookie(RequestTelemetryContext context, SessionContext sessionContext, int sessionTimeoutInMinutes)
  fullName: static Cookie com.microsoft.applicationinsights.web.internal.cookies.HttpCookieFactory.generateSessionHttpCookie(RequestTelemetryContext context, SessionContext sessionContext, int sessionTimeoutInMinutes)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/HttpCookieFactory.java
    startLine: 46
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Generates session http cookie. </p>
  syntax:
    content: public static Cookie generateSessionHttpCookie(RequestTelemetryContext context, SessionContext sessionContext, int sessionTimeoutInMinutes)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.web.internal._request_telemetry_context
      description: <p>The context. </p>
    - id: sessionContext
      type: com.microsoft.applicationinsights.extensibility.context._session_context
      description: <p>The request session context. </p>
    - id: sessionTimeoutInMinutes
      type: f75371fa
      description: <p>The session timeout in minutes. </p>
    return:
      type: com.microsoft.applicationinsights.web.internal.cookies._cookie
      description: <p>Session http cookie. </p>
- uid: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.generateUserHttpCookie(RequestTelemetryContext)
  id: generateUserHttpCookie(RequestTelemetryContext)
  parent: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory
  href: com.microsoft.applicationinsights.web.internal.cookies._http_cookie_factory.yml
  langs:
  - java
  name: generateUserHttpCookie(RequestTelemetryContext context)
  fullName: static Cookie com.microsoft.applicationinsights.web.internal.cookies.HttpCookieFactory.generateUserHttpCookie(RequestTelemetryContext context)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/HttpCookieFactory.java
    startLine: 70
  package: com.microsoft.applicationinsights.web.internal.cookies
  summary: <p>Generates user http cookie. </p>
  syntax:
    content: public static Cookie generateUserHttpCookie(RequestTelemetryContext context)
    parameters:
    - id: context
      type: com.microsoft.applicationinsights.web.internal._request_telemetry_context
      description: <p>The context. </p>
    return:
      type: com.microsoft.applicationinsights.web.internal.cookies._cookie
      description: <p>User http cookie. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.applicationinsights.web.internal.cookies._cookie
  parent: com.microsoft.applicationinsights.web.internal.cookies
  href: com.microsoft.applicationinsights.web.internal.cookies._cookie.yml
  name: Cookie
  fullName: com.microsoft.applicationinsights.web.internal.cookies.Cookie
  type: Class
  summary: >-
    <p>Created by yonisha on 2/9/2015.</p>

    <p>Used as a base class for AI cookies. </p>
  syntax:
    content: public class Cookie
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  name: RequestTelemetryContext
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class RequestTelemetryContext
- uid: com.microsoft.applicationinsights.extensibility.context._session_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._session_context.yml
  name: SessionContext
  fullName: com.microsoft.applicationinsights.extensibility.context.SessionContext
  type: Class
  syntax:
    content: public class SessionContext
