items:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer
  id: _web_user_telemetry_initializer
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  children:
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer.onInitializeTelemetry(Telemetry)
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer.yml
  langs:
  - java
  name: WebUserTelemetryInitializer
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebUserTelemetryInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebUserTelemetryInitializer.java
    startLine: 33
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  summary: <p>Created by yonisha on 3/5/2015. </p>
  syntax:
    content: public class WebUserTelemetryInitializer extends WebTelemetryInitializerBase
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_initializer
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  inheritedMembers:
  - com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.initialize(Telemetry)
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer.onInitializeTelemetry(Telemetry)
  id: onInitializeTelemetry(Telemetry)
  parent: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_user_telemetry_initializer.yml
  langs:
  - java
  name: onInitializeTelemetry(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer.onInitializeTelemetry(Telemetry telemetry)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebUserTelemetryInitializer.java
    startLine: 41
  package: com.microsoft.applicationinsights.web.extensibility.initializers
  summary: >-
    <p>Initializes the properties of the given telemetry.</p>

    <p></p>
  syntax:
    content: protected void onInitializeTelemetry(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
references:
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.initialize(Telemetry)
  parent: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  name: initialize(Telemetry telemetry)
  fullName: void com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase.initialize(Telemetry telemetry)
  type: Method
  summary: <p>Initializes properties of the given telemetry. </p>
  syntax:
    content: public void initialize(Telemetry telemetry)
    parameters:
    - id: telemetry
      type: com.microsoft.applicationinsights.telemetry._telemetry
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> to initialize. </p>
- uid: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base
  parent: com.microsoft.applicationinsights.web.extensibility.initializers
  href: com.microsoft.applicationinsights.web.extensibility.initializers._web_telemetry_initializer_base.yml
  name: WebTelemetryInitializerBase
  fullName: com.microsoft.applicationinsights.web.extensibility.initializers.WebTelemetryInitializerBase
  type: Class
  summary: <p>Created by yonisha on 2/16/2015. </p>
  syntax:
    content: public class WebTelemetryInitializerBase implements TelemetryInitializer
- uid: com.microsoft.applicationinsights.telemetry._telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._telemetry.yml
  name: Telemetry
  fullName: com.microsoft.applicationinsights.telemetry.Telemetry
  type: Interface
  summary: <p>The base telemetry type interface for application insights. </p>
  syntax:
    content: public interface Telemetry extends JsonSerializable
