items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  id: _performance_counter_container_test
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.clear()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testMoreThanOneWithId()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testOnePerformanceCounterCalls()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testRegisterWithEmptyId()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testRegisterWithNullId()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetCollectingIntervalInMillisMillisNegativeNumber()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetCollectingIntervalInMillisZero()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetStartCollectingIntervalInMillisNegativeNumber()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetStartCollectingIntervalInMillisZero()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testTwoPerformanceCountersWhereTheSecondIsNotRegistered()
  - com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testTwoPerformanceCountersWhereTheSecondIsUnregistered()
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: PerformanceCounterContainerTest
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public class PerformanceCounterContainerTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.clear()
  id: clear()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: clear()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.clear()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void clear()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testMoreThanOneWithId()
  id: testMoreThanOneWithId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testMoreThanOneWithId()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testMoreThanOneWithId()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 161
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testMoreThanOneWithId()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testOnePerformanceCounterCalls()
  id: testOnePerformanceCounterCalls()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testOnePerformanceCounterCalls()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testOnePerformanceCounterCalls()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 135
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testOnePerformanceCounterCalls()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testRegisterWithEmptyId()
  id: testRegisterWithEmptyId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testRegisterWithEmptyId()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testRegisterWithEmptyId()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 130
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testRegisterWithEmptyId()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testRegisterWithNullId()
  id: testRegisterWithNullId()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testRegisterWithNullId()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testRegisterWithNullId()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 125
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testRegisterWithNullId()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetCollectingIntervalInMillisMillisNegativeNumber()
  id: testSetCollectingIntervalInMillisMillisNegativeNumber()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testSetCollectingIntervalInMillisMillisNegativeNumber()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testSetCollectingIntervalInMillisMillisNegativeNumber()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 113
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testSetCollectingIntervalInMillisMillisNegativeNumber()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetCollectingIntervalInMillisZero()
  id: testSetCollectingIntervalInMillisZero()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testSetCollectingIntervalInMillisZero()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testSetCollectingIntervalInMillisZero()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 119
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testSetCollectingIntervalInMillisZero()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetStartCollectingIntervalInMillisNegativeNumber()
  id: testSetStartCollectingIntervalInMillisNegativeNumber()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testSetStartCollectingIntervalInMillisNegativeNumber()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testSetStartCollectingIntervalInMillisNegativeNumber()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 100
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testSetStartCollectingIntervalInMillisNegativeNumber()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testSetStartCollectingIntervalInMillisZero()
  id: testSetStartCollectingIntervalInMillisZero()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testSetStartCollectingIntervalInMillisZero()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testSetStartCollectingIntervalInMillisZero()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 107
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testSetStartCollectingIntervalInMillisZero()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testTwoPerformanceCountersWhereTheSecondIsNotRegistered()
  id: testTwoPerformanceCountersWhereTheSecondIsNotRegistered()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testTwoPerformanceCountersWhereTheSecondIsNotRegistered()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testTwoPerformanceCountersWhereTheSecondIsNotRegistered()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 173
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testTwoPerformanceCountersWhereTheSecondIsNotRegistered()
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.testTwoPerformanceCountersWhereTheSecondIsUnregistered()
  id: testTwoPerformanceCountersWhereTheSecondIsUnregistered()
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_container_test.yml
  langs:
  - java
  name: testTwoPerformanceCountersWhereTheSecondIsUnregistered()
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainerTest.testTwoPerformanceCountersWhereTheSecondIsUnregistered()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java
    startLine: 187
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void testTwoPerformanceCountersWhereTheSecondIsUnregistered()
references:
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter.yml
  name: PerformanceCounter
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.perfcounter._performance_counter" data-throw-if-not-resolved="false"></xref> interface.</p>

    <p>Every concrete class should have a unique id and it should be able to collect data send that data using a <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface PerformanceCounter
