items:
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  id: _built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  children:
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String)
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String,long)
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String,long,String...)
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String,String...)
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.getClassName()
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.getMethods()
  - com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.getThresholdInMS()
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 108
  syntax:
    content: public class BuiltInInstrumentedClass
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String)
  id: BuiltInInstrumentedClass(String)
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: BuiltInInstrumentedClass(String className)
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.BuiltInInstrumentedClass(String className)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 113
  syntax:
    content: public BuiltInInstrumentedClass(String className)
    parameters:
    - id: className
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String,long)
  id: BuiltInInstrumentedClass(String,long)
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: BuiltInInstrumentedClass(String className, long thresholdInMS)
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.BuiltInInstrumentedClass(String className, long thresholdInMS)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 117
  syntax:
    content: public BuiltInInstrumentedClass(String className, long thresholdInMS)
    parameters:
    - id: className
      type: "26831127"
    - id: thresholdInMS
      type: 0364520f
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String,long,String...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: BuiltInInstrumentedClass(String className, long thresholdInMS, String...methods)
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.BuiltInInstrumentedClass(String className, long thresholdInMS, String...methods)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 125
  syntax:
    content: public BuiltInInstrumentedClass(String className, long thresholdInMS, String...methods)
    parameters:
    - id: className
      type: "26831127"
    - id: thresholdInMS
      type: 0364520f
    - id: methods
      type: 04d2b762
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.BuiltInInstrumentedClass(String,String...)
  id: )
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: BuiltInInstrumentedClass(String className, String...methods)
  fullName: com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.BuiltInInstrumentedClass(String className, String...methods)
  type: Constructor
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 121
  syntax:
    content: public BuiltInInstrumentedClass(String className, String...methods)
    parameters:
    - id: className
      type: "26831127"
    - id: methods
      type: 04d2b762
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.getClassName()
  id: getClassName()
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: getClassName()
  fullName: String com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.getClassName()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 136
  syntax:
    content: public String getClassName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.getMethods()
  id: getMethods()
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: getMethods()
  fullName: List<String> com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.getMethods()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 140
  syntax:
    content: public List<String> getMethods()
    return:
      type: 7d60c20e
- uid: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.getThresholdInMS()
  id: getThresholdInMS()
  parent: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33
  href: com.microsoft.applicationinsights.agent.internal.config._built_in_instrum00cd0f973357ca9e3f70cc80068e2f33.yml
  langs:
  - java
  name: getThresholdInMS()
  fullName: long com.microsoft.applicationinsights.agent.internal.config.BuiltInInstrumentedClasses.BuiltInInstrumentedClass.getThresholdInMS()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentedClasses.java
    startLine: 144
  syntax:
    content: public long getThresholdInMS()
    return:
      type: 0364520f
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 04d2b762
  spec.java:
  - name: String...
    fullName: String...
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
