items:
- uid: com.microsoft.applicationinsights.internal.util._device_info_test
  id: _device_info_test
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._device_info_test.testBadLocale()
  - com.microsoft.applicationinsights.internal.util._device_info_test.testSimpleLocale()
  - com.microsoft.applicationinsights.internal.util._device_info_test.testSpecialLocale()
  href: com.microsoft.applicationinsights.internal.util._device_info_test.yml
  langs:
  - java
  name: DeviceInfoTest
  fullName: com.microsoft.applicationinsights.internal.util.DeviceInfoTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DeviceInfoTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DeviceInfoTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by amnonsh on 2/10/2015. </p>
  syntax:
    content: public class DeviceInfoTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._device_info_test.testBadLocale()
  id: testBadLocale()
  parent: com.microsoft.applicationinsights.internal.util._device_info_test
  href: com.microsoft.applicationinsights.internal.util._device_info_test.yml
  langs:
  - java
  name: testBadLocale()
  fullName: void com.microsoft.applicationinsights.internal.util.DeviceInfoTest.testBadLocale()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DeviceInfoTest.java
    startLine: 52
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testBadLocale()
- uid: com.microsoft.applicationinsights.internal.util._device_info_test.testSimpleLocale()
  id: testSimpleLocale()
  parent: com.microsoft.applicationinsights.internal.util._device_info_test
  href: com.microsoft.applicationinsights.internal.util._device_info_test.yml
  langs:
  - java
  name: testSimpleLocale()
  fullName: void com.microsoft.applicationinsights.internal.util.DeviceInfoTest.testSimpleLocale()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DeviceInfoTest.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testSimpleLocale()
- uid: com.microsoft.applicationinsights.internal.util._device_info_test.testSpecialLocale()
  id: testSpecialLocale()
  parent: com.microsoft.applicationinsights.internal.util._device_info_test
  href: com.microsoft.applicationinsights.internal.util._device_info_test.yml
  langs:
  - java
  name: testSpecialLocale()
  fullName: void com.microsoft.applicationinsights.internal.util.DeviceInfoTest.testSpecialLocale()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DeviceInfoTest.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testSpecialLocale()
references: []
