items:
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b
  id: _application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b.withContainingSubnet(Subnet)
  href: com.microsoft.azure.management.network._application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b.yml
  langs:
  - java
  name: ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithContainingSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithContainingSubnet<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
    startLine: 110
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway IP configuration definition allowing to specify the subnet the application gateway is on. </p>
  syntax:
    content: public interface WithContainingSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent type </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b.withContainingSubnet(Subnet)
  id: withContainingSubnet(Subnet)
  parent: com.microsoft.azure.management.network._application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b
  href: com.microsoft.azure.management.network._application_gateway_ip_configura3db55e55c30983a565c3d4f6b7b4520b.yml
  langs:
  - java
  name: withContainingSubnet(Subnet subnet)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithContainingSubnet<ParentT>.withContainingSubnet(Subnet subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIpConfiguration.java
    startLine: 116
  package: com.microsoft.azure.management.network
  summary: <p>Specifies an existing subnet the application gateway should be part of and get its private IP address from. </p>
  syntax:
    content: public WithAttach<ParentT> withContainingSubnet(Subnet subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure.management.network._subnet
      description: <p>an existing subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181eda8a2936
      description: <p>the next stage of the subnet definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181eda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e
    name: ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configuration._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configuration._update_definition.yml
  name: ApplicationGatewayIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway IP configuration definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayIpConfiguration.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithContainingSubnet<ParentT>,ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent type </p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configura43d8f1d57f4fe691d1f0e88507452fbb
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configura43d8f1d57f4fe691d1f0e88507452fbb.yml
  name: ApplicationGatewayIpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  summary: <p>The first stage of an application gateway IP configuration definition. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithContainingSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ip_configurab11057f0b2dfc388a6a0579a19a1181e.yml
  name: ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway IP configuration definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._subnet
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._subnet.yml
  name: Subnet
  fullName: com.microsoft.azure.management.network.Subnet
  type: Interface
  summary: <p>An immutable client-side representation of a subnet of a virtual network. </p>
  syntax:
    content: public interface Subnet extends Wrapper<SubnetInner>,ChildResource<Network>
