items:
- uid: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
  id: _definiti88acb12f6701c2c3fa28abaef33404ff
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.defineIpConfiguration(String)
  - com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.withContainingSubnet(Network,String)
  - com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.withContainingSubnet(String,String)
  - com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.withContainingSubnet(Subnet)
  href: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithContainingSubnet
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithContainingSubnet
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 352
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to specify the subnet the app gateway is getting its private IP address from. </p>
  syntax:
    content: public interface WithContainingSubnet
- uid: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.defineIpConfiguration(String)
  id: defineIpConfiguration(String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
  href: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.yml
  langs:
  - java
  name: defineIpConfiguration(String name)
  fullName: ApplicationGatewayIpConfiguration.DefinitionStages.Blank<WithPublicFrontend> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithContainingSubnet.defineIpConfiguration(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 387
  package: com.microsoft.azure.management.network
  summary: <p>Begins the definition of a new IP configuration to add to this application gateway. </p>
  syntax:
    content: public ApplicationGatewayIpConfiguration.DefinitionStages.Blank<WithPublicFrontend> defineIpConfiguration(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a name to assign to the IP configuration </p>
    return:
      type: 549aefa7com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042ca08ddfce
      description: <p>the first stage of the IP configuration definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.withContainingSubnet(Network,String)
  id: withContainingSubnet(Network,String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
  href: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.yml
  langs:
  - java
  name: withContainingSubnet(Network network, String subnetName)
  fullName: WithPublicFrontend com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithContainingSubnet.withContainingSubnet(Network network, String subnetName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 370
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Specifies the default subnet the application gateway gets its private IP address from. </p>

    <p>This will create an IP configuration named "default". </p>
  syntax:
    content: public WithPublicFrontend withContainingSubnet(Network network, String subnetName)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network the subnet is part of </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet within the selected network </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.withContainingSubnet(String,String)
  id: withContainingSubnet(String,String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
  href: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.yml
  langs:
  - java
  name: withContainingSubnet(String networkResourceId, String subnetName)
  fullName: WithPublicFrontend com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithContainingSubnet.withContainingSubnet(String networkResourceId, String subnetName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 380
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Specifies the default subnet the application gateway gets its private IP address from. </p>

    <p>This will create an IP configuration named "default". </p>
  syntax:
    content: public WithPublicFrontend withContainingSubnet(String networkResourceId, String subnetName)
    parameters:
    - id: networkResourceId
      type: "26831127"
      description: <p>the resource ID of the virtual network the subnet is part of </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet within the selected network </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.withContainingSubnet(Subnet)
  id: withContainingSubnet(Subnet)
  parent: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff
  href: com.microsoft.azure.management.network._application_gateway._definiti88acb12f6701c2c3fa28abaef33404ff.yml
  langs:
  - java
  name: withContainingSubnet(Subnet subnet)
  fullName: WithPublicFrontend com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithContainingSubnet.withContainingSubnet(Subnet subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 360
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Specifies the default subnet the application gateway gets its private IP address from. </p>

    <p>This will create an IP configuration named "default". </p>
  syntax:
    content: public WithPublicFrontend withContainingSubnet(Subnet subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure.management.network._subnet
      description: <p>an existing subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
      description: <p>the next stage of the definition </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 549aefa7com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042ca08ddfce
  spec.java:
  - name: ApplicationGatewayIpConfiguration.DefinitionStages.Blank<
    fullName: ApplicationGatewayIpConfiguration.DefinitionStages.Blank<
  - uid: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
    name: ApplicationGateway.DefinitionStages.WithPublicFrontend
    fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPublicFrontend
    href: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
- uid: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti4c458a21f70dc3da33496a7511bf042c.yml
  name: ApplicationGateway.DefinitionStages.WithPublicFrontend
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithPublicFrontend
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to define one or more public, or Internet-facing, frontends. </p>
  syntax:
    content: public interface WithPublicFrontend
- uid: com.microsoft.azure.management.network._subnet
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._subnet.yml
  name: Subnet
  fullName: com.microsoft.azure.management.network.Subnet
  type: Interface
  summary: <p>An immutable client-side representation of a subnet of a virtual network. </p>
  syntax:
    content: public interface Subnet extends Wrapper<SubnetInner>,ChildResource<Network>
- uid: com.microsoft.azure.management.network._network
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network.yml
  name: Network
  fullName: com.microsoft.azure.management.network.Network
  type: Interface
  summary: <p>Entry point for Virtual <xref href="com.microsoft.azure.management.network._network" data-throw-if-not-resolved="false"></xref> management API in <xref href="com.microsoft.azure.management._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Network extends GroupableResource,Refreshable<Network>,Wrapper<VirtualNetworkInner>,Updatable<Network.Update>
