items:
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test
  id: _user_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  children:
  - com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetAccountId()
  - com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetAcquisitionDate()
  - com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetAcquisitionNullDate()
  - com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetId()
  - com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetUserAgent()
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  langs:
  - java
  name: UserContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.UserContextTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public class UserContextTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetAccountId()
  id: testSetAccountId()
  parent: com.microsoft.applicationinsights.extensibility.context._user_context_test
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  langs:
  - java
  name: testSetAccountId()
  fullName: void com.microsoft.applicationinsights.extensibility.context.UserContextTest.testSetAccountId()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
    startLine: 44
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetAccountId()
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetAcquisitionDate()
  id: testSetAcquisitionDate()
  parent: com.microsoft.applicationinsights.extensibility.context._user_context_test
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  langs:
  - java
  name: testSetAcquisitionDate()
  fullName: void com.microsoft.applicationinsights.extensibility.context.UserContextTest.testSetAcquisitionDate()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
    startLine: 55
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetAcquisitionDate()
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetAcquisitionNullDate()
  id: testSetAcquisitionNullDate()
  parent: com.microsoft.applicationinsights.extensibility.context._user_context_test
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  langs:
  - java
  name: testSetAcquisitionNullDate()
  fullName: void com.microsoft.applicationinsights.extensibility.context.UserContextTest.testSetAcquisitionNullDate()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
    startLine: 66
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetAcquisitionNullDate()
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetId()
  id: testSetId()
  parent: com.microsoft.applicationinsights.extensibility.context._user_context_test
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  langs:
  - java
  name: testSetId()
  fullName: void com.microsoft.applicationinsights.extensibility.context.UserContextTest.testSetId()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
    startLine: 33
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetId()
- uid: com.microsoft.applicationinsights.extensibility.context._user_context_test.testSetUserAgent()
  id: testSetUserAgent()
  parent: com.microsoft.applicationinsights.extensibility.context._user_context_test
  href: com.microsoft.applicationinsights.extensibility.context._user_context_test.yml
  langs:
  - java
  name: testSetUserAgent()
  fullName: void com.microsoft.applicationinsights.extensibility.context.UserContextTest.testSetUserAgent()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/UserContextTest.java
    startLine: 77
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetUserAgent()
references: []
