items:
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  id: _stack_frame
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.getAssembly()
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.getFileName()
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.getLevel()
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.getLine()
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.getMethod()
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.setAssembly(String)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.setFileName(String)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.setLevel(int)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.setLine(int)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.setMethod(String)
  - com.microsoft.applicationinsights.internal.schemav2._stack_frame.StackFrame()
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: StackFrame
  fullName: com.microsoft.applicationinsights.internal.schemav2.StackFrame
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._stack_frame" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class StackFrame implements JsonSerializable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.getAssembly()
  id: getAssembly()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: getAssembly()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.StackFrame.getAssembly()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getAssembly()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.getFileName()
  id: getFileName()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: getFileName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.StackFrame.getFileName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getFileName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.getLevel()
  id: getLevel()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: getLevel()
  fullName: int com.microsoft.applicationinsights.internal.schemav2.StackFrame.getLevel()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 67
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public int getLevel()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.getLine()
  id: getLine()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: getLine()
  fullName: int com.microsoft.applicationinsights.internal.schemav2.StackFrame.getLine()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 99
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public int getLine()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.getMethod()
  id: getMethod()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: getMethod()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.StackFrame.getMethod()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getMethod()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 127
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 113
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  exceptions:
  - type: cbf33bbe
    description: <p>Might be thrown during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 119
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.setAssembly(String)
  id: setAssembly(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: setAssembly(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.setAssembly(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 87
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setAssembly(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.setFileName(String)
  id: setFileName(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: setFileName(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.setFileName(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 95
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setFileName(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.setLevel(int)
  id: setLevel(int)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: setLevel(int value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.setLevel(int value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setLevel(int value)
    parameters:
    - id: value
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.setLine(int)
  id: setLine(int)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: setLine(int value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.setLine(int value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 103
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setLine(int value)
    parameters:
    - id: value
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.setMethod(String)
  id: setMethod(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: setMethod(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.StackFrame.setMethod(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setMethod(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame.StackFrame()
  id: StackFrame()
  parent: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  langs:
  - java
  name: StackFrame()
  fullName: com.microsoft.applicationinsights.internal.schemav2.StackFrame.StackFrame()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
    startLine: 62
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public StackFrame()
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._stack_frame
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._stack_frame.yml
  name: StackFrame
  fullName: com.microsoft.applicationinsights.internal.schemav2.StackFrame
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._stack_frame" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
