items:
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s
  id: _agent_t_l_s
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl
  children:
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.getTLSKey()
  - com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.setTLSKey(String)
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.yml
  langs:
  - java
  name: AgentTLS
  fullName: com.microsoft.applicationinsights.agent.internal.coresync.impl.AgentTLS
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/AgentTLS.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/AgentTLS.java
    startLine: 29
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  summary: >-
    <p>The class is used to set and get a name on application thread. The name can be used to fetch information on the part of the application, typically a WebApp, that owns that thread</p>

    <p>Created by gupele on 5/6/2015. </p>
  syntax:
    content: public class AgentTLS
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.getTLSKey()
  id: getTLSKey()
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.yml
  langs:
  - java
  name: getTLSKey()
  fullName: static String com.microsoft.applicationinsights.agent.internal.coresync.impl.AgentTLS.getTLSKey()
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/AgentTLS.java
    startLine: 33
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  syntax:
    content: public static String getTLSKey()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.setTLSKey(String)
  id: setTLSKey(String)
  parent: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s
  href: com.microsoft.applicationinsights.agent.internal.coresync.impl._agent_t_l_s.yml
  langs:
  - java
  name: setTLSKey(String value)
  fullName: static void com.microsoft.applicationinsights.agent.internal.coresync.impl.AgentTLS.setTLSKey(String value)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/AgentTLS.java
    startLine: 37
  package: com.microsoft.applicationinsights.agent.internal.coresync.impl
  syntax:
    content: public static void setTLSKey(String value)
    parameters:
    - id: value
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
