items:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  id: _stub_m_x_bean
  parent: com.microsoft.applicationinsights.internal.jmx
  children:
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.getDoubleSample()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.getIntSample()
  - com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.getLongSample()
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.yml
  langs:
  - java
  name: JmxDataFetcherTest.StubMXBean
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.StubMXBean
  type: Interface
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 14
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public interface StubMXBean
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.getDoubleSample()
  id: getDoubleSample()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.yml
  langs:
  - java
  name: getDoubleSample()
  fullName: double com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.StubMXBean.getDoubleSample()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 16
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public double getDoubleSample()
    return:
      type: a07dcde8
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.getIntSample()
  id: getIntSample()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.yml
  langs:
  - java
  name: getIntSample()
  fullName: int com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.StubMXBean.getIntSample()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 15
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public int getIntSample()
    return:
      type: f75371fa
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.getLongSample()
  id: getLongSample()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._stub_m_x_bean.yml
  langs:
  - java
  name: getLongSample()
  fullName: long com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.StubMXBean.getLongSample()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcherTest.java
    startLine: 17
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public long getLongSample()
    return:
      type: 0364520f
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: a07dcde8
  spec.java:
  - name: double
    fullName: double
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub
  parent: com.microsoft.applicationinsights.internal.jmx
  href: com.microsoft.applicationinsights.internal.jmx._jmx_data_fetcher_test._test_stub.yml
  name: JmxDataFetcherTest.TestStub
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxDataFetcherTest.TestStub
  type: Class
  syntax:
    content: public class TestStub
