items:
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  id: _sender_thread_local_data_test
  parent: com.microsoft.applicationinsights.internal.channel.common
  children:
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testDoneSendingAfterFailedSending()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testMultipleOnFailedSending()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testNotSupplyingBackOffTimesContainer()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testOnDoneSending()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testStateAfterCtor()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testStopWhileWaiting()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testWithEmptyBackOffTimesContainer()
  - com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testWithEmptyNegativeAddSeconds()
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: SenderThreadLocalDataTest
  fullName: com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 27
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public class SenderThreadLocalDataTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testDoneSendingAfterFailedSending()
  id: testDoneSendingAfterFailedSending()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testDoneSendingAfterFailedSending()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testDoneSendingAfterFailedSending()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testDoneSendingAfterFailedSending()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testMultipleOnFailedSending()
  id: testMultipleOnFailedSending()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testMultipleOnFailedSending()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testMultipleOnFailedSending()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 51
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testMultipleOnFailedSending()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testNotSupplyingBackOffTimesContainer()
  id: testNotSupplyingBackOffTimesContainer()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testNotSupplyingBackOffTimesContainer()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testNotSupplyingBackOffTimesContainer()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testNotSupplyingBackOffTimesContainer()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testOnDoneSending()
  id: testOnDoneSending()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testOnDoneSending()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testOnDoneSending()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testOnDoneSending()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testStateAfterCtor()
  id: testStateAfterCtor()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testStateAfterCtor()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testStateAfterCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 44
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStateAfterCtor()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testStopWhileWaiting()
  id: testStopWhileWaiting()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testStopWhileWaiting()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testStopWhileWaiting()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testStopWhileWaiting()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testWithEmptyBackOffTimesContainer()
  id: testWithEmptyBackOffTimesContainer()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testWithEmptyBackOffTimesContainer()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testWithEmptyBackOffTimesContainer()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testWithEmptyBackOffTimesContainer()
- uid: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.testWithEmptyNegativeAddSeconds()
  id: testWithEmptyNegativeAddSeconds()
  parent: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test
  href: com.microsoft.applicationinsights.internal.channel.common._sender_thread_local_data_test.yml
  langs:
  - java
  name: testWithEmptyNegativeAddSeconds()
  fullName: void com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalDataTest.testWithEmptyNegativeAddSeconds()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalDataTest.java
    startLine: 39
  package: com.microsoft.applicationinsights.internal.channel.common
  syntax:
    content: public void testWithEmptyNegativeAddSeconds()
references: []
