items:
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  id: _date_time_utils_tests
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testFormatAsRoundTripDate()
  - com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateString()
  - com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateStringFullUTC()
  - com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateStringShortFormat()
  - com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateStringWithoutOffset()
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  langs:
  - java
  name: DateTimeUtilsTests
  fullName: com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
    startLine: 11
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by yonisha on 5/26/2015. </p>
  syntax:
    content: public class DateTimeUtilsTests
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testFormatAsRoundTripDate()
  id: testFormatAsRoundTripDate()
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  langs:
  - java
  name: testFormatAsRoundTripDate()
  fullName: void com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests.testFormatAsRoundTripDate()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testFormatAsRoundTripDate()
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateString()
  id: testParseRoundTripDateString()
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  langs:
  - java
  name: testParseRoundTripDateString()
  fullName: void com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests.testParseRoundTripDateString()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
    startLine: 14
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testParseRoundTripDateString()
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateStringFullUTC()
  id: testParseRoundTripDateStringFullUTC()
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  langs:
  - java
  name: testParseRoundTripDateStringFullUTC()
  fullName: void com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests.testParseRoundTripDateStringFullUTC()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testParseRoundTripDateStringFullUTC()
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateStringShortFormat()
  id: testParseRoundTripDateStringShortFormat()
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  langs:
  - java
  name: testParseRoundTripDateStringShortFormat()
  fullName: void com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests.testParseRoundTripDateStringShortFormat()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testParseRoundTripDateStringShortFormat()
- uid: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.testParseRoundTripDateStringWithoutOffset()
  id: testParseRoundTripDateStringWithoutOffset()
  parent: com.microsoft.applicationinsights.internal.util._date_time_utils_tests
  href: com.microsoft.applicationinsights.internal.util._date_time_utils_tests.yml
  langs:
  - java
  name: testParseRoundTripDateStringWithoutOffset()
  fullName: void com.microsoft.applicationinsights.internal.util.DateTimeUtilsTests.testParseRoundTripDateStringWithoutOffset()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/util/DateTimeUtilsTests.java
    startLine: 22
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public void testParseRoundTripDateStringWithoutOffset()
references: []
