items:
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  id: _file_logger_output_test
  parent: com.microsoft.applicationinsights.internal.logger
  children:
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test.FileLoggerOutputTest()
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testChangeOfFiles()
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testFileOutputWithoutPrefix()
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testManyLines()
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testOneLine()
  - com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testTwoLines()
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: FileLoggerOutputTest
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 47
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public class FileLoggerOutputTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.FileLoggerOutputTest()
  id: FileLoggerOutputTest()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: FileLoggerOutputTest()
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest.FileLoggerOutputTest()
  type: Constructor
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 53
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public FileLoggerOutputTest()
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testChangeOfFiles()
  id: testChangeOfFiles()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: testChangeOfFiles()
  fullName: void com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest.testChangeOfFiles()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 82
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testChangeOfFiles()
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testFileOutputWithoutPrefix()
  id: testFileOutputWithoutPrefix()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: testFileOutputWithoutPrefix()
  fullName: void com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest.testFileOutputWithoutPrefix()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 77
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testFileOutputWithoutPrefix()
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testManyLines()
  id: testManyLines()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: testManyLines()
  fullName: void com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest.testManyLines()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testManyLines()
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testOneLine()
  id: testOneLine()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: testOneLine()
  fullName: void com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest.testOneLine()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testOneLine()
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.testTwoLines()
  id: testTwoLines()
  parent: com.microsoft.applicationinsights.internal.logger._file_logger_output_test
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output_test.yml
  langs:
  - java
  name: testTwoLines()
  fullName: void com.microsoft.applicationinsights.internal.logger.FileLoggerOutputTest.testTwoLines()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutputTest.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.logger
  syntax:
    content: public void testTwoLines()
references:
- uid: com.microsoft.applicationinsights.internal.logger._file_logger_output
  parent: com.microsoft.applicationinsights.internal.logger
  href: com.microsoft.applicationinsights.internal.logger._file_logger_output.yml
  name: FileLoggerOutput
  fullName: com.microsoft.applicationinsights.internal.logger.FileLoggerOutput
  type: Class
  summary: >-
    <p>The class is responsible for write log messages into log files. The class will write to a file until the file max size is reached.</p>

    <p>When that happens it will create close that file and open a new file.</p>

    <p>When the maximum amount of log files is reached, the oldest one will be deleted.</p>

    <p>The class does a 'best effort' to work with files, if there is a problem, the class will try to write into a <xref href="com.microsoft.applicationinsights.internal.logger._console_logger_output" data-throw-if-not-resolved="false"></xref> but will not fail the process under any scenario. </p>
  syntax:
    content: public class FileLoggerOutput implements LoggerOutput
