items:
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  id: _web_session_tracking_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  children:
  - com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.initialize(TelemetryConfiguration)
  - com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  - com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  langs:
  - java
  name: WebSessionTrackingTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
    startLine: 37
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: <p>Created by yonisha on 2/4/2015. </p>
  syntax:
    content: public class WebSessionTrackingTelemetryModule implements WebTelemetryModule,TelemetryModule
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.initialize(TelemetryConfiguration)
  id: initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  langs:
  - java
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
    startLine: 47
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: >-
    <p>Initializes the telemetry module.</p>

    <p></p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
  overridden: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  id: onBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  langs:
  - java
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
    startLine: 57
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: >-
    <p>Begin request processing.</p>

    <p></p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
  overridden: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  id: onEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_session_tracking_telemetry_module.yml
  langs:
  - java
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
    startLine: 84
  package: com.microsoft.applicationinsights.web.extensibility.modules
  summary: >-
    <p>End request processing. This method checks if the session cookie should be updated before sent back to the client. The session cookie is updated when the session is new or current session already expired.</p>

    <p></p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
  overridden: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
references:
- uid: b0deafe7
  spec.java:
  - name: ServletRequest
    fullName: ServletRequest
- uid: 0dcfeead
  spec.java:
  - name: ServletResponse
    fullName: ServletResponse
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  parent: com.microsoft.applicationinsights.web.extensibility.modules
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  name: WebTelemetryModule
  fullName: com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface WebTelemetryModule
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: TelemetryModule
  fullName: com.microsoft.applicationinsights.extensibility.TelemetryModule
  type: Interface
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public interface TelemetryModule
- uid: com.microsoft.applicationinsights.extensibility._telemetry_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.extensibility._telemetry_module
  href: com.microsoft.applicationinsights.extensibility._telemetry_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.extensibility.TelemetryModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>Initializes the telemetry module. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onBeginRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  name: onBeginRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule.onBeginRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: <p>Begin request processing. </p>
  syntax:
    content: public void onBeginRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.onEndRequest(ServletRequest,ServletResponse)
  parent: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module
  href: com.microsoft.applicationinsights.web.extensibility.modules._web_telemetry_module.yml
  name: onEndRequest(ServletRequest req, ServletResponse res)
  fullName: void com.microsoft.applicationinsights.web.extensibility.modules.WebTelemetryModule.onEndRequest(ServletRequest req, ServletResponse res)
  type: Method
  summary: <p>End request processing. </p>
  syntax:
    content: public void onEndRequest(ServletRequest req, ServletResponse res)
    parameters:
    - id: req
      type: b0deafe7
      description: <p>The request to process </p>
    - id: res
      type: 0dcfeead
      description: <p>The response to modify </p>
- uid: com.microsoft.applicationinsights.extensibility.context._session_context
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context._session_context.yml
  name: SessionContext
  fullName: com.microsoft.applicationinsights.extensibility.context.SessionContext
  type: Class
  syntax:
    content: public class SessionContext
- uid: com.microsoft.applicationinsights.web.internal._request_telemetry_context
  parent: com.microsoft.applicationinsights.web.internal
  href: com.microsoft.applicationinsights.web.internal._request_telemetry_context.yml
  name: RequestTelemetryContext
  fullName: com.microsoft.applicationinsights.web.internal.RequestTelemetryContext
  type: Class
  summary: <p>Created by yonisha on 2/2/2015. </p>
  syntax:
    content: public class RequestTelemetryContext
