items:
- uid: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module
  id: _web_performance_counter_module
  parent: com.microsoft.applicationinsights.web.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.WebPerformanceCounterModule()
  href: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.yml
  langs:
  - java
  name: WebPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
  type: Class
  source:
    remote: &o0
      path: web/src/main/java/com/microsoft/applicationinsights/web/internal/perfcounter/WebPerformanceCounterModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/perfcounter/WebPerformanceCounterModule.java
    startLine: 9
  package: com.microsoft.applicationinsights.web.internal.perfcounter
  summary: <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class WebPerformanceCounterModule extends AbstractPerformanceCounterModule
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_module
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  - com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.WebPerformanceCounterModule(WebPerformanceCountersFactory)
- uid: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.WebPerformanceCounterModule()
  id: WebPerformanceCounterModule()
  parent: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module
  href: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.yml
  langs:
  - java
  name: WebPerformanceCounterModule()
  fullName: com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule.WebPerformanceCounterModule()
  type: Constructor
  source:
    remote: *o0
    path: web/src/main/java/com/microsoft/applicationinsights/web/internal/perfcounter/WebPerformanceCounterModule.java
    startLine: 10
  package: com.microsoft.applicationinsights.web.internal.perfcounter
  syntax:
    content: public WebPerformanceCounterModule()
references:
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  type: Constructor
  syntax:
    content: protected AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
    parameters:
    - id: factory
      type: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: factory
  fullName: final PerformanceCountersFactory com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.factory
  type: Field
  syntax:
    content: protected final PerformanceCountersFactory factory
    return:
      type: 93de0ef9com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>The main method will use the factory to fetch the performance counters and register them for work. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.web.internal.perfcounter._web_performance_counter_module.WebPerformanceCounterModule(WebPerformanceCountersFactory)
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule
  type: Class
  summary: >-
    <p>A base class for performance modules.</p>

    <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class AbstractPerformanceCounterModule implements TelemetryModule
