items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific55ce21614b25fc6bc55fdded719b61d4
  id: _application_gateway_ssl_certific55ce21614b25fc6bc55fdded719b61d4
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific55ce21614b25fc6bc55fdded719b61d4.yml
  langs:
  - java
  name: ApplicationGatewaySslCertificate.DefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.Blank<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 37
  package: com.microsoft.azure.management.network
  summary: <p>The first stage of an application gateway SSL certificate. </p>
  syntax:
    content: public interface Blank<ParentT> extends ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent application gateway type </p>
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.withPfxContent(byte[])
  - com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.withPfxFile(File)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.withPfxContent(byte[])
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.yml
  name: withPfxContent(byte[] pfxData)
  fullName: WithPassword<ParentT> com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>.withPfxContent(byte[] pfxData)
  type: Method
  summary: <p>Specifies the contents of the private key in the PFX (PKCS#12) format, not base64-encoded. </p>
  syntax:
    content: public WithPassword<ParentT> withPfxContent(byte[] pfxData)
    parameters:
    - id: pfxData
      type: bc819c2f
      description: <p>the contents of the private key in the PFX format </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.withPfxFile(File)
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.yml
  name: withPfxFile(File pfxFile)
  fullName: WithPassword<ParentT> com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>.withPfxFile(File pfxFile)
  type: Method
  summary: <p>Specifies the PFX (PKCS#12) file to get the private key content from. </p>
  syntax:
    content: public WithPassword<ParentT> withPfxFile(File pfxFile)
    parameters:
    - id: pfxFile
      type: 8291270b
      description: <p>a file in the PFX format </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certifica2850f1f2881d403cede2ec678374e63da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certific549ffb46c25b6e2baa1c2389848eceb3.yml
  name: ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.DefinitionStages.WithData<ParentT>
  type: Interface
  summary: <p>The stage of an SSL certificate definition allowing to specify the contents of the SSL certificate. </p>
  syntax:
    content: public interface WithData<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate._definition.yml
  name: ApplicationGatewaySslCertificate.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway SSL certificate definition. </p>
  syntax:
    content: public interface Definition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
