items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  id: _process_performance_counters_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.addConfigurationData(PerformanceCountersXmlElement)
  - com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.ProcessPerformanceCountersModule()
  - com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.ProcessPerformanceCountersModule(PerformanceCountersFactory)
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  langs:
  - java
  name: ProcessPerformanceCountersModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>The class will be used when the SDK needs to add the 'built-in' performance counters.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public class ProcessPerformanceCountersModule extends AbstractPerformanceCounterModule implements PerformanceCounterConfigurationAware
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility._telemetry_module
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  - com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.addConfigurationData(PerformanceCountersXmlElement)
  id: addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  langs:
  - java
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: <p>This method checks for Windows performance counters from the configuration. The method will work only if the process is activated under Windows OS. The method will initialize the connection to the native code using <xref href="com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector" data-throw-if-not-resolved="false"></xref> and then will go through the requested performance counters, normalize them, and will hand them to the factory. </p>
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
      description: <p>The configuration of that section </p>
  overridden: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.addConfigurationData(PerformanceCountersXmlElement)
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.ProcessPerformanceCountersModule()
  id: ProcessPerformanceCountersModule()
  parent: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  langs:
  - java
  name: ProcessPerformanceCountersModule()
  fullName: com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule.ProcessPerformanceCountersModule()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public ProcessPerformanceCountersModule()
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.ProcessPerformanceCountersModule(PerformanceCountersFactory)
  id: ProcessPerformanceCountersModule(PerformanceCountersFactory)
  parent: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module
  href: com.microsoft.applicationinsights.internal.perfcounter._process_performance_counters_module.yml
  langs:
  - java
  name: ProcessPerformanceCountersModule(PerformanceCountersFactory factory)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.ProcessPerformanceCountersModule.ProcessPerformanceCountersModule(PerformanceCountersFactory factory)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public ProcessPerformanceCountersModule(PerformanceCountersFactory factory)
    parameters:
    - id: factory
      type: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
references:
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.AbstractPerformanceCounterModule(PerformanceCountersFactory)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
  type: Constructor
  syntax:
    content: protected AbstractPerformanceCounterModule(PerformanceCountersFactory factory)
    parameters:
    - id: factory
      type: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.factory()
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: factory
  fullName: final PerformanceCountersFactory com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.factory
  type: Field
  syntax:
    content: protected final PerformanceCountersFactory factory
    return:
      type: 93de0ef9com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.initialize(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: initialize(TelemetryConfiguration configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(TelemetryConfiguration configuration)
  type: Method
  summary: <p>The main method will use the factory to fetch the performance counters and register them for work. </p>
  syntax:
    content: public void initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights._telemetry_configuration
      description: <p>The configuration to used to initialize the module. </p>
- uid: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._abstract_performance_counter_module.yml
  name: AbstractPerformanceCounterModule
  fullName: com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule
  type: Class
  summary: >-
    <p>A base class for performance modules.</p>

    <p>Created by gupele on 3/12/2015. </p>
  syntax:
    content: public class AbstractPerformanceCounterModule implements TelemetryModule
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.yml
  name: PerformanceCounterConfigurationAware
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterConfigurationAware
  type: Interface
  summary: >-
    <p>This class should by performance modules who wish to work with the configuration data.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public interface PerformanceCounterConfigurationAware
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counters_factory.yml
  name: PerformanceCountersFactory
  fullName: com.microsoft.applicationinsights.internal.perfcounter.PerformanceCountersFactory
  type: Interface
  summary: >-
    <p>Defines the interface that concrete factories should follow. The major method is the one that will be able create the needed Performance Counters.</p>

    <p>Created by gupele on 3/3/2015. </p>
  syntax:
    content: public interface PerformanceCountersFactory
- uid: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.addConfigurationData(PerformanceCountersXmlElement)
  parent: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware
  href: com.microsoft.applicationinsights.internal.perfcounter._performance_counter_configuration_aware.yml
  name: addConfigurationData(PerformanceCountersXmlElement configuration)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterConfigurationAware.addConfigurationData(PerformanceCountersXmlElement configuration)
  type: Method
  syntax:
    content: public void addConfigurationData(PerformanceCountersXmlElement configuration)
    parameters:
    - id: configuration
      type: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
- uid: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  href: com.microsoft.applicationinsights.internal.config._performance_counters_xml_element.yml
  name: PerformanceCountersXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.PerformanceCountersXmlElement
  type: Class
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class PerformanceCountersXmlElement
- uid: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._jni_p_c_connector.yml
  name: JniPCConnector
  fullName: com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector
  type: Class
  summary: >-
    <p>This class serves as the connection to the native code that does the work with Windows.</p>

    <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class JniPCConnector
