items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend.de475454f5ff9cd6ae153a9776ed4043
  id: de475454f5ff9cd6ae153a9776ed4043
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.de475454f5ff9cd6ae153a9776ed4043.yml
  langs:
  - java
  name: ApplicationGatewayFrontend.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontend.java
    startLine: 199
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The final stage of an application gateway frontend definition. </p>

    <p>At this stage, any remaining optional settings can be specified, or the frontend definition can be attached to the parent application gateway definition. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdateAlt,ApplicationGatewayFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>,ApplicationGatewayFrontend.UpdateDefinitionStages.WithSubnet<ParentT>,ApplicationGatewayFrontend.UpdateDefinitionStages.WithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()
  - com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(PublicIpAddress)
  - com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(String)
  - com.microsoft.azure.management.network._application_gateway_frontend.f56b5172e8dca3f3d9c3d27aaf614fa2.withExistingSubnet(Network,String)
  - com.microsoft.azure.management.resources.fluentcore.arm.models.feec00187b44006d1134916f89c070c7.withExistingSubnet(String,String)
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdateAlt<ParentT>.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource update. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(PublicIpAddress)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(PublicIpAddress publicIpAddress)
    parameters:
    - id: publicIpAddress
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.withExistingPublicIpAddress(String)
  parent: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb
  href: com.microsoft.azure.management.network.model._has_public_ip_address_1ec03ba68940987ea785e42c4aaf28bfb.yml
  name: withExistingPublicIpAddress(String resourceId)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPublicIpAddress.UpdateDefinitionStages.WithExistingPublicIpAddress<ReturnT>.withExistingPublicIpAddress(String resourceId)
  type: Method
  summary: >-
    <p>Associates an existing public IP address with the resource.</p>

    <p></p>
  syntax:
    content: public ReturnT withExistingPublicIpAddress(String resourceId)
    parameters:
    - id: resourceId
      type: "26831127"
      description: <p>the resource ID of an existing public IP address </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend.f56b5172e8dca3f3d9c3d27aaf614fa2.withExistingSubnet(Network,String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend.f56b5172e8dca3f3d9c3d27aaf614fa2
  href: com.microsoft.azure.management.network._application_gateway_frontend.f56b5172e8dca3f3d9c3d27aaf614fa2.yml
  name: withExistingSubnet(Network network, String subnetName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithSubnet<ParentT>.withExistingSubnet(Network network, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this private frontend. </p>
  syntax:
    content: public WithAttach<ParentT> withExistingSubnet(Network network, String subnetName)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network the subnet exists in </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of a subnet </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend.de475454f5ff9cd6ae153a9776ed4043da8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.feec00187b44006d1134916f89c070c7.withExistingSubnet(String,String)
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.feec00187b44006d1134916f89c070c7
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.feec00187b44006d1134916f89c070c7.yml
  name: withExistingSubnet(String parentNetworkResourceId, String subnetName)
  fullName: ReturnT com.microsoft.azure.management.resources.fluentcore.arm.models.HasSubnet.UpdateDefinitionStages.WithSubnet<ReturnT>.withExistingSubnet(String parentNetworkResourceId, String subnetName)
  type: Method
  summary: <p>Assigns the specified subnet to this resource. </p>
  syntax:
    content: public ReturnT withExistingSubnet(String parentNetworkResourceId, String subnetName)
    parameters:
    - id: parentNetworkResourceId
      type: "26831127"
      description: <p>the resource ID of the virtual network the subnet is part of </p>
    - id: subnetName
      type: "26831127"
      description: <p>the name of the subnet </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress<ReturnT>.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.yml
  name: Attachable.InUpdateAlt<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdateAlt<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InUpdateAlt<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend.b92473a9f5988c07d773b703a40e2ac8
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.b92473a9f5988c07d773b703a40e2ac8.yml
  name: ApplicationGatewayFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway frontend definition allowing to specify an existing public IP address to make the application gateway available at as Internet-facing. </p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update_alt.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend.f56b5172e8dca3f3d9c3d27aaf614fa2
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.f56b5172e8dca3f3d9c3d27aaf614fa2.yml
  name: ApplicationGatewayFrontend.UpdateDefinitionStages.WithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithSubnet<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway frontend definition allowing to specify a subnet from the selected network to make this application gateway visible to. </p>
  syntax:
    content: public interface WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend.b6890b745c89bb53cccf7ff74997d4fe
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend.b6890b745c89bb53cccf7ff74997d4fe.yml
  name: ApplicationGatewayFrontend.UpdateDefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  summary: <p>The stage of an application gateway frontend definition allowing to specify the private IP address this application gateway should be available at within the selected virtual network. </p>
  syntax:
    content: public interface WithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend._update_definition.yml
  name: ApplicationGatewayFrontend.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontend.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway frontend definition as part of an application gateway update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends ApplicationGatewayFrontend.UpdateDefinitionStages.Blank<ParentT>,ApplicationGatewayFrontend.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching this definition </p>
