items:
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counters_factory
  id: _windows_performance_counters_factory
  parent: com.microsoft.applicationinsights.internal.perfcounter
  children:
  - com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counters_factory.setWindowsPCs(Iterable<WindowsPerformanceCounterData>)
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counters_factory.yml
  langs:
  - java
  name: WindowsPerformanceCountersFactory
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCountersFactory
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCountersFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCountersFactory.java
    startLine: 29
  package: com.microsoft.applicationinsights.internal.perfcounter
  summary: >-
    <p>An interface that is used by factories that know to create Windows based on data that is given in a container of <xref href="com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data" data-throw-if-not-resolved="false"></xref></p>

    <p>Created by gupele on 3/31/2015. </p>
  syntax:
    content: public interface WindowsPerformanceCountersFactory
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counters_factory.setWindowsPCs(Iterable<WindowsPerformanceCounterData>)
  id: setWindowsPCs(Iterable<WindowsPerformanceCounterData>)
  parent: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counters_factory
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counters_factory.yml
  langs:
  - java
  name: setWindowsPCs(Iterable<WindowsPerformanceCounterData> all)
  fullName: void com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCountersFactory.setWindowsPCs(Iterable<WindowsPerformanceCounterData> all)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCountersFactory.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.perfcounter
  syntax:
    content: public void setWindowsPCs(Iterable<WindowsPerformanceCounterData> all)
    parameters:
    - id: all
      type: 2a13b5a5com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_dataa08ddfce
references:
- uid: 2a13b5a5com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_dataa08ddfce
  spec.java:
  - name: Iterable<
    fullName: Iterable<
  - uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
    name: WindowsPerformanceCounterData
    fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
    href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.applicationinsights.internal.perfcounter._process_built_in_performance_counters_factory
- uid: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data
  parent: com.microsoft.applicationinsights.internal.perfcounter
  href: com.microsoft.applicationinsights.internal.perfcounter._windows_performance_counter_data.yml
  name: WindowsPerformanceCounterData
  fullName: com.microsoft.applicationinsights.internal.perfcounter.WindowsPerformanceCounterData
  type: Class
  summary: <p>Created by gupele on 3/30/2015. </p>
  syntax:
    content: public class WindowsPerformanceCounterData
