items:
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  id: _performance_counter_telemetry_test
  parent: com.microsoft.applicationinsights.telemetry
  children:
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testCategoryName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testCounterName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testEmptyCategoryName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testEmptyCounterName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testInstanceName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testNullCategoryName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testNullCounterName()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testStateAfterCtor()
  - com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testValue()
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: PerformanceCounterTelemetryTest
  fullName: com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public class PerformanceCounterTelemetryTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testCategoryName()
  id: testCategoryName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testCategoryName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 69
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCategoryName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testCounterName()
  id: testCounterName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testCounterName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 79
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testCounterName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testEmptyCategoryName()
  id: testEmptyCategoryName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testEmptyCategoryName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testEmptyCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 43
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyCategoryName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testEmptyCounterName()
  id: testEmptyCounterName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testEmptyCounterName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testEmptyCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 53
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testEmptyCounterName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testInstanceName()
  id: testInstanceName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testInstanceName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testInstanceName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 89
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testInstanceName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testNullCategoryName()
  id: testNullCategoryName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testNullCategoryName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testNullCategoryName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 38
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testNullCategoryName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testNullCounterName()
  id: testNullCounterName()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testNullCounterName()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testNullCounterName()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 48
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testNullCounterName()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testStateAfterCtor()
  id: testStateAfterCtor()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testStateAfterCtor()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testStateAfterCtor()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 58
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testStateAfterCtor()
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.testValue()
  id: testValue()
  parent: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry_test.yml
  langs:
  - java
  name: testValue()
  fullName: void com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetryTest.testValue()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetryTest.java
    startLine: 99
  package: com.microsoft.applicationinsights.telemetry
  syntax:
    content: public void testValue()
references:
- uid: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._performance_counter_telemetry.yml
  name: PerformanceCounterTelemetry
  fullName: com.microsoft.applicationinsights.telemetry.PerformanceCounterTelemetry
  type: Class
  summary: <p>The class that represents information about performance counters. </p>
  syntax:
    content: public class PerformanceCounterTelemetry extends BaseTelemetry<PerformanceCounterData>
