items:
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  id: _jmx_attribute_data
  parent: com.microsoft.applicationinsights.internal.jmx
  children:
  - com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.displayName()
  - com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.JmxAttributeData(String,String)
  - com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.JmxAttributeData(String,String,String)
  - com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.name()
  - com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.type()
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  langs:
  - java
  name: JmxAttributeData
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 31
  package: com.microsoft.applicationinsights.internal.jmx
  summary: >-
    <p>Represents JMX data of an Attribute The display name The name of the attribute The type of the attribute</p>

    <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxAttributeData
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.displayName()
  id: displayName()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  langs:
  - java
  name: displayName
  fullName: final String com.microsoft.applicationinsights.internal.jmx.JmxAttributeData.displayName
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 32
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public final String displayName
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.JmxAttributeData(String,String)
  id: JmxAttributeData(String,String)
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  langs:
  - java
  name: JmxAttributeData(String displayName, String name)
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData.JmxAttributeData(String displayName, String name)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public JmxAttributeData(String displayName, String name)
    parameters:
    - id: displayName
      type: "26831127"
    - id: name
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.JmxAttributeData(String,String,String)
  id: JmxAttributeData(String,String,String)
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  langs:
  - java
  name: JmxAttributeData(String displayName, String name, String type)
  fullName: com.microsoft.applicationinsights.internal.jmx.JmxAttributeData.JmxAttributeData(String displayName, String name, String type)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 40
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public JmxAttributeData(String displayName, String name, String type)
    parameters:
    - id: displayName
      type: "26831127"
    - id: name
      type: "26831127"
    - id: type
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.name()
  id: name()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  langs:
  - java
  name: name
  fullName: final String com.microsoft.applicationinsights.internal.jmx.JmxAttributeData.name
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public final String name
    return:
      type: 3d93591e
- uid: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.type()
  id: type()
  parent: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data
  href: com.microsoft.applicationinsights.internal.jmx._jmx_attribute_data.yml
  langs:
  - java
  name: type
  fullName: final String com.microsoft.applicationinsights.internal.jmx.JmxAttributeData.type
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxAttributeData.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.jmx
  syntax:
    content: public final String type
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
