items:
- uid: com.microsoft.applicationinsights.internal.schemav2._base
  id: _base
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._base.Base()
  - com.microsoft.applicationinsights.internal.schemav2._base.getBaseType()
  - com.microsoft.applicationinsights.internal.schemav2._base.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._base.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._base.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._base.setBaseType(String)
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: Base
  fullName: com.microsoft.applicationinsights.internal.schemav2.Base
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._base" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class Base implements JsonSerializable,SendableData
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
  inheritedMembers:
  - com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
  - com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
- uid: com.microsoft.applicationinsights.internal.schemav2._base.Base()
  id: Base()
  parent: com.microsoft.applicationinsights.internal.schemav2._base
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: Base()
  fullName: com.microsoft.applicationinsights.internal.schemav2.Base.Base()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public Base()
- uid: com.microsoft.applicationinsights.internal.schemav2._base.getBaseType()
  id: getBaseType()
  parent: com.microsoft.applicationinsights.internal.schemav2._base
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: getBaseType()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.Base.getBaseType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 46
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getBaseType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._base.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._base
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Base.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 77
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Optionally initializes fields for the current context. </p>
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._base.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._base
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Base.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
- uid: com.microsoft.applicationinsights.internal.schemav2._base.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._base
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Base.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 70
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  exceptions:
  - type: cbf33bbe
    description: <p>Might be throw during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._base.setBaseType(String)
  id: setBaseType(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._base
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  langs:
  - java
  name: setBaseType(String baseType)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.Base.setBaseType(String baseType)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/Base.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setBaseType(String baseType)
    parameters:
    - id: baseType
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getBaseTypeName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: getBaseTypeName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getBaseTypeName()
  type: Method
  syntax:
    content: public String getBaseTypeName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data.getEnvelopName()
  parent: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: getEnvelopName()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.SendableData.getEnvelopName()
  type: Method
  syntax:
    content: public String getEnvelopName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.internal.schemav2._sendable_data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._sendable_data.yml
  name: SendableData
  fullName: com.microsoft.applicationinsights.internal.schemav2.SendableData
  type: Interface
  summary: <p>Defines the interface for data that might be sent to the Server. </p>
  syntax:
    content: public interface SendableData
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData>
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._base
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._base.yml
  name: Base
  fullName: com.microsoft.applicationinsights.internal.schemav2.Base
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._base" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
