items:
- uid: com.microsoft.applicationinsights.internal.channel.stdout
  id: stdout
  children:
  - com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  href: com.microsoft.applicationinsights.internal.channel.stdout.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.internal.channel.stdout
  fullName: com.microsoft.applicationinsights.internal.channel.stdout
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/channel/stdout/StdOutChannel.java
    startLine: 21
  syntax:
    content: namespace stdout
references:
- uid: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel
  parent: com.microsoft.applicationinsights.internal.channel.stdout
  href: com.microsoft.applicationinsights.internal.channel.stdout._std_out_channel.yml
  name: StdOutChannel
  fullName: com.microsoft.applicationinsights.internal.channel.stdout.StdOutChannel
  type: Class
  summary: <p>A telemetry channel routing information to stdout. </p>
  syntax:
    content: public class StdOutChannel implements TelemetryChannel
