items:
- uid: com.microsoft.applicationinsights
  id: applicationinsights
  children:
  - com.microsoft.applicationinsights._telemetry_client
  - com.microsoft.applicationinsights._telemetry_client_tests
  - com.microsoft.applicationinsights._telemetry_configuration
  href: com.microsoft.applicationinsights.yml
  langs:
  - java
  name: com.microsoft.applicationinsights
  fullName: com.microsoft.applicationinsights
  type: Namespace
  source:
    remote:
      path: '[generated]'
    path: '[generated]'
  syntax:
    content: namespace applicationinsights
references:
- uid: com.microsoft.applicationinsights.agent
- uid: com.microsoft.applicationinsights.channel
  href: com.microsoft.applicationinsights.channel.yml
  name: com.microsoft.applicationinsights.channel
  fullName: com.microsoft.applicationinsights.channel
  type: Namespace
  syntax:
    content: namespace channel
- uid: com.microsoft.applicationinsights.collectd
  href: com.microsoft.applicationinsights.collectd.yml
  name: com.microsoft.applicationinsights.collectd
  fullName: com.microsoft.applicationinsights.collectd
  type: Namespace
  syntax:
    content: namespace collectd
- uid: com.microsoft.applicationinsights.common
  href: com.microsoft.applicationinsights.common.yml
  name: com.microsoft.applicationinsights.common
  fullName: com.microsoft.applicationinsights.common
  type: Namespace
  syntax:
    content: namespace common
- uid: com.microsoft.applicationinsights.core
- uid: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility.yml
  name: com.microsoft.applicationinsights.extensibility
  fullName: com.microsoft.applicationinsights.extensibility
  type: Namespace
  syntax:
    content: namespace extensibility
- uid: com.microsoft.applicationinsights.internal
- uid: com.microsoft.applicationinsights.log4j
- uid: com.microsoft.applicationinsights.logback
  href: com.microsoft.applicationinsights.logback.yml
  name: com.microsoft.applicationinsights.logback
  fullName: com.microsoft.applicationinsights.logback
  type: Namespace
  syntax:
    content: namespace logback
- uid: com.microsoft.applicationinsights.sample
  href: com.microsoft.applicationinsights.sample.yml
  name: com.microsoft.applicationinsights.sample
  fullName: com.microsoft.applicationinsights.sample
  type: Namespace
  syntax:
    content: namespace sample
- uid: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry.yml
  name: com.microsoft.applicationinsights.telemetry
  fullName: com.microsoft.applicationinsights.telemetry
  type: Namespace
  syntax:
    content: namespace telemetry
- uid: com.microsoft.applicationinsights.web
- uid: com.microsoft.applicationinsights._telemetry_client
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client.yml
  name: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  summary: <p>Created by gupele on 1/5/2015. </p>
  syntax:
    content: public class TelemetryClient
- uid: com.microsoft.applicationinsights._telemetry_client_tests
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_client_tests.yml
  name: TelemetryClientTests
  fullName: com.microsoft.applicationinsights.TelemetryClientTests
  type: Class
  summary: <p>Tests the interface of the telemetry client. </p>
  syntax:
    content: public class TelemetryClientTests
- uid: com.microsoft.applicationinsights._telemetry_configuration
  parent: com.microsoft.applicationinsights
  href: com.microsoft.applicationinsights._telemetry_configuration.yml
  name: TelemetryConfiguration
  fullName: com.microsoft.applicationinsights.TelemetryConfiguration
  type: Class
  summary: >-
    <p>Encapsulates the global telemetry configuration typically loaded from the ApplicationInsights.xml file.</p>

    <p>All <xref href="com.microsoft.applicationinsights.telemetry._telemetry_context" data-throw-if-not-resolved="false"></xref> objects are initialized using the 'Active' (returned by the 'getActive' static method) telemetry configuration provided by this class. </p>
  syntax:
    content: public class TelemetryConfiguration
