items:
- uid: com.microsoft.applicationinsights.internal.schemav2._user
  id: _user
  parent: com.microsoft.applicationinsights.internal.schemav2
  children:
  - com.microsoft.applicationinsights.internal.schemav2._user.addToHashMap(HashMap<String, String>)
  - com.microsoft.applicationinsights.internal.schemav2._user.getAccountAcquisitionDate()
  - com.microsoft.applicationinsights.internal.schemav2._user.getAccountId()
  - com.microsoft.applicationinsights.internal.schemav2._user.getId()
  - com.microsoft.applicationinsights.internal.schemav2._user.getUserAgent()
  - com.microsoft.applicationinsights.internal.schemav2._user.InitializeFields()
  - com.microsoft.applicationinsights.internal.schemav2._user.serialize(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._user.serializeContent(JsonTelemetryDataSerializer)
  - com.microsoft.applicationinsights.internal.schemav2._user.setAccountAcquisitionDate(String)
  - com.microsoft.applicationinsights.internal.schemav2._user.setAccountId(String)
  - com.microsoft.applicationinsights.internal.schemav2._user.setId(String)
  - com.microsoft.applicationinsights.internal.schemav2._user.setUserAgent(String)
  - com.microsoft.applicationinsights.internal.schemav2._user.User()
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: User
  fullName: com.microsoft.applicationinsights.internal.schemav2.User
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._user" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class User implements JsonSerializable
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.telemetry._json_serializable
- uid: com.microsoft.applicationinsights.internal.schemav2._user.addToHashMap(HashMap<String, String>)
  id: addToHashMap(HashMap<String, String>)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: addToHashMap(HashMap<String, String> map)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.addToHashMap(HashMap<String, String> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 99
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Adds all members of this class to a hashmap </p>
  syntax:
    content: public void addToHashMap(HashMap<String, String> map)
    parameters:
    - id: map
      type: 3970a053
      description: <p>to which the members of this class will be added. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._user.getAccountAcquisitionDate()
  id: getAccountAcquisitionDate()
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: getAccountAcquisitionDate()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.User.getAccountAcquisitionDate()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getAccountAcquisitionDate()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.getAccountId()
  id: getAccountId()
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: getAccountId()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.User.getAccountId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getAccountId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.getId()
  id: getId()
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: getId()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.User.getId()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 87
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getId()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.getUserAgent()
  id: getUserAgent()
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: getUserAgent()
  fullName: String com.microsoft.applicationinsights.internal.schemav2.User.getUserAgent()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 79
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public String getUserAgent()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.InitializeFields()
  id: InitializeFields()
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: InitializeFields()
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.InitializeFields()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 139
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: protected void InitializeFields()
- uid: com.microsoft.applicationinsights.internal.schemav2._user.serialize(JsonTelemetryDataSerializer)
  id: serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: serialize(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.serialize(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 121
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  overridden: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  exceptions:
  - type: cbf33bbe
    description: <p>Might be throw during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._user.serializeContent(JsonTelemetryDataSerializer)
  id: serializeContent(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: serializeContent(JsonTelemetryDataSerializer writer)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.serializeContent(JsonTelemetryDataSerializer writer)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 132
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Serializes the beginning of this object to the passed in writer. </p>
  syntax:
    content: protected void serializeContent(JsonTelemetryDataSerializer writer)
    parameters:
    - id: writer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The writer to serialize this object to. </p>
  exceptions:
  - type: cbf33bbe
    description: <p>Might be throw during serialization. </p>
- uid: com.microsoft.applicationinsights.internal.schemav2._user.setAccountAcquisitionDate(String)
  id: setAccountAcquisitionDate(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: setAccountAcquisitionDate(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.setAccountAcquisitionDate(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 67
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setAccountAcquisitionDate(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.setAccountId(String)
  id: setAccountId(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: setAccountId(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.setAccountId(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 75
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setAccountId(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.setId(String)
  id: setId(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: setId(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.setId(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 91
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setId(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.setUserAgent(String)
  id: setUserAgent(String)
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: setUserAgent(String value)
  fullName: void com.microsoft.applicationinsights.internal.schemav2.User.setUserAgent(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 83
  package: com.microsoft.applicationinsights.internal.schemav2
  syntax:
    content: public void setUserAgent(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.schemav2._user.User()
  id: User()
  parent: com.microsoft.applicationinsights.internal.schemav2._user
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  langs:
  - java
  name: User()
  fullName: com.microsoft.applicationinsights.internal.schemav2.User.User()
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/User.java
    startLine: 58
  package: com.microsoft.applicationinsights.internal.schemav2
  summary: <p>Initializes a new instance of the class. </p>
  syntax:
    content: public User()
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 3970a053
  spec.java:
  - name: HashMap<String, String>
    fullName: HashMap<String, String>
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.applicationinsights.telemetry._json_serializable
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: JsonSerializable
  fullName: com.microsoft.applicationinsights.telemetry.JsonSerializable
  type: Interface
  summary: <p>Represents objects that support serialization to JSON. </p>
  syntax:
    content: public interface JsonSerializable
- uid: com.microsoft.applicationinsights.telemetry._json_serializable.serialize(JsonTelemetryDataSerializer)
  parent: com.microsoft.applicationinsights.telemetry._json_serializable
  href: com.microsoft.applicationinsights.telemetry._json_serializable.yml
  name: serialize(JsonTelemetryDataSerializer serializer)
  fullName: void com.microsoft.applicationinsights.telemetry.JsonSerializable.serialize(JsonTelemetryDataSerializer serializer)
  type: Method
  summary: <p>Writes JSON representation of the object to the specified writer. </p>
  syntax:
    content: public void serialize(JsonTelemetryDataSerializer serializer)
    parameters:
    - id: serializer
      type: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
      description: <p>The <xref href="com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer" data-throw-if-not-resolved="false"></xref> that is used to serialized to JSON format </p>
- uid: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer
  parent: com.microsoft.applicationinsights.telemetry
  href: com.microsoft.applicationinsights.telemetry._json_telemetry_data_serializer.yml
  name: JsonTelemetryDataSerializer
  fullName: com.microsoft.applicationinsights.telemetry.JsonTelemetryDataSerializer
  type: Class
  summary: <p>This class knows how to transform data that is relevant to <xref href="com.microsoft.applicationinsights.telemetry._telemetry" data-throw-if-not-resolved="false"></xref> instances into JSON </p>
  syntax:
    content: public class JsonTelemetryDataSerializer
- uid: com.microsoft.applicationinsights.internal.schemav2._data
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._data.yml
  name: Data<TDomain>
  fullName: com.microsoft.applicationinsights.internal.schemav2.Data<TDomain>
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Data<TDomain extends SendableData> extends Base implements SendableData
    typeParameters:
    - type: "89379896"
- uid: com.microsoft.applicationinsights.internal.schemav2._user
  parent: com.microsoft.applicationinsights.internal.schemav2
  href: com.microsoft.applicationinsights.internal.schemav2._user.yml
  name: User
  fullName: com.microsoft.applicationinsights.internal.schemav2.User
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.applicationinsights.internal.schemav2._data" data-throw-if-not-resolved="false"></xref> contract class <xref href="com.microsoft.applicationinsights.internal.schemav2._user" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
