items:
- uid: com.microsoft.applicationinsights.sample._ai_core
  id: _ai_core
  parent: com.microsoft.applicationinsights.sample
  children:
  - com.microsoft.applicationinsights.sample._ai_core.main(String[])
  href: com.microsoft.applicationinsights.sample._ai_core.yml
  langs:
  - java
  name: AiCore
  fullName: com.microsoft.applicationinsights.sample.AiCore
  type: Class
  source:
    remote: &o0
      path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiCore.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiCore.java
    startLine: 36
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public class AiCore
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.sample._ai_core.main(String[])
  id: main(String[])
  parent: com.microsoft.applicationinsights.sample._ai_core
  href: com.microsoft.applicationinsights.sample._ai_core.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void com.microsoft.applicationinsights.sample.AiCore.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: samples/src/main/java/com/microsoft/applicationinsights/sample/AiCore.java
    startLine: 37
  package: com.microsoft.applicationinsights.sample
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
