items:
- uid: com.microsoft.applicationinsights.internal.util._sanitizer
  id: _sanitizer
  parent: com.microsoft.applicationinsights.internal.util
  children:
  - com.microsoft.applicationinsights.internal.util._sanitizer.isUUID(String)
  - com.microsoft.applicationinsights.internal.util._sanitizer.MAX_MAP_NAME_LENGTH()
  - com.microsoft.applicationinsights.internal.util._sanitizer.MAX_MESSAGE_LENGTH()
  - com.microsoft.applicationinsights.internal.util._sanitizer.MAX_NAME_LENGTH()
  - com.microsoft.applicationinsights.internal.util._sanitizer.MAX_URL_LENGTH()
  - com.microsoft.applicationinsights.internal.util._sanitizer.MAX_VALUE_LENGTH()
  - com.microsoft.applicationinsights.internal.util._sanitizer.safeStringToUri(String)
  - com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeMeasurements(Map<String, Double>)
  - com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeMessage(String)
  - com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeName(String)
  - com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeProperties(Map<String, String>)
  - com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeUri(String)
  - com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeValue(String)
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: Sanitizer
  fullName: com.microsoft.applicationinsights.internal.util.Sanitizer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 33
  package: com.microsoft.applicationinsights.internal.util
  summary: <p>Created by gupele on 1/7/2015. </p>
  syntax:
    content: public class Sanitizer
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.isUUID(String)
  id: isUUID(String)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: isUUID(String possibleUUID)
  fullName: static boolean com.microsoft.applicationinsights.internal.util.Sanitizer.isUUID(String possibleUUID)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 104
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static boolean isUUID(String possibleUUID)
    parameters:
    - id: possibleUUID
      type: "26831127"
    return:
      type: 4fc6e284
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.MAX_MAP_NAME_LENGTH()
  id: MAX_MAP_NAME_LENGTH()
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: MAX_MAP_NAME_LENGTH
  fullName: final int com.microsoft.applicationinsights.internal.util.Sanitizer.MAX_MAP_NAME_LENGTH
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 34
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static final int MAX_MAP_NAME_LENGTH= 150
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.MAX_MESSAGE_LENGTH()
  id: MAX_MESSAGE_LENGTH()
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: MAX_MESSAGE_LENGTH
  fullName: final int com.microsoft.applicationinsights.internal.util.Sanitizer.MAX_MESSAGE_LENGTH
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 37
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static final int MAX_MESSAGE_LENGTH= 32768
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.MAX_NAME_LENGTH()
  id: MAX_NAME_LENGTH()
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: MAX_NAME_LENGTH
  fullName: final int com.microsoft.applicationinsights.internal.util.Sanitizer.MAX_NAME_LENGTH
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static final int MAX_NAME_LENGTH= 1024
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.MAX_URL_LENGTH()
  id: MAX_URL_LENGTH()
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: MAX_URL_LENGTH
  fullName: final int com.microsoft.applicationinsights.internal.util.Sanitizer.MAX_URL_LENGTH
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 38
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static final int MAX_URL_LENGTH= 2048
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.MAX_VALUE_LENGTH()
  id: MAX_VALUE_LENGTH()
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: MAX_VALUE_LENGTH
  fullName: final int com.microsoft.applicationinsights.internal.util.Sanitizer.MAX_VALUE_LENGTH
  type: Field
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 35
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static final int MAX_VALUE_LENGTH= 1024
    return:
      type: cd225469
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.safeStringToUri(String)
  id: safeStringToUri(String)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: safeStringToUri(String url)
  fullName: static URI com.microsoft.applicationinsights.internal.util.Sanitizer.safeStringToUri(String url)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 114
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static URI safeStringToUri(String url)
    parameters:
    - id: url
      type: "26831127"
    return:
      type: "62304784"
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeMeasurements(Map<String, Double>)
  id: sanitizeMeasurements(Map<String, Double>)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: sanitizeMeasurements(Map<String, Double> map)
  fullName: static void com.microsoft.applicationinsights.internal.util.Sanitizer.sanitizeMeasurements(Map<String, Double> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 57
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static void sanitizeMeasurements(Map<String, Double> map)
    parameters:
    - id: map
      type: 2ed405bc
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeMessage(String)
  id: sanitizeMessage(String)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: sanitizeMessage(String message)
  fullName: static String com.microsoft.applicationinsights.internal.util.Sanitizer.sanitizeMessage(String message)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 100
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String sanitizeMessage(String message)
    parameters:
    - id: message
      type: "26831127"
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeName(String)
  id: sanitizeName(String)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: sanitizeName(String name)
  fullName: static String com.microsoft.applicationinsights.internal.util.Sanitizer.sanitizeName(String name)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 96
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String sanitizeName(String name)
    parameters:
    - id: name
      type: "26831127"
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeProperties(Map<String, String>)
  id: sanitizeProperties(Map<String, String>)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: sanitizeProperties(Map<String, String> map)
  fullName: static void com.microsoft.applicationinsights.internal.util.Sanitizer.sanitizeProperties(Map<String, String> map)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 42
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static void sanitizeProperties(Map<String, String> map)
    parameters:
    - id: map
      type: 689c8cb5
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeUri(String)
  id: sanitizeUri(String)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: sanitizeUri(String urlAsString)
  fullName: static URI com.microsoft.applicationinsights.internal.util.Sanitizer.sanitizeUri(String urlAsString)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 71
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static URI sanitizeUri(String urlAsString)
    parameters:
    - id: urlAsString
      type: "26831127"
    return:
      type: "62304784"
- uid: com.microsoft.applicationinsights.internal.util._sanitizer.sanitizeValue(String)
  id: sanitizeValue(String)
  parent: com.microsoft.applicationinsights.internal.util._sanitizer
  href: com.microsoft.applicationinsights.internal.util._sanitizer.yml
  langs:
  - java
  name: sanitizeValue(String value)
  fullName: static String com.microsoft.applicationinsights.internal.util.Sanitizer.sanitizeValue(String value)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/util/Sanitizer.java
    startLine: 92
  package: com.microsoft.applicationinsights.internal.util
  syntax:
    content: public static String sanitizeValue(String value)
    parameters:
    - id: value
      type: "26831127"
    return:
      type: "26831127"
references:
- uid: cd225469
  spec.java:
  - name: final int
    fullName: final int
- uid: 689c8cb5
  spec.java:
  - name: Map<String, String>
    fullName: Map<String, String>
- uid: 2ed405bc
  spec.java:
  - name: Map<String, Double>
    fullName: Map<String, Double>
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
