items:
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  id: _jmx_xml_element
  parent: com.microsoft.applicationinsights.internal.config
  children:
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.getAttribute()
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.getDisplayName()
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.getObjectName()
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.getType()
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.setAttribute(String)
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.setDisplayName(String)
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.setObjectName(String)
  - com.microsoft.applicationinsights.internal.config._jmx_xml_element.setType(String)
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: JmxXmlElement
  fullName: com.microsoft.applicationinsights.internal.config.JmxXmlElement
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 30
  package: com.microsoft.applicationinsights.internal.config
  summary: <p>Created by gupele on 3/15/2015. </p>
  syntax:
    content: public class JmxXmlElement
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.getAttribute()
  id: getAttribute()
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: getAttribute()
  fullName: String com.microsoft.applicationinsights.internal.config.JmxXmlElement.getAttribute()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 54
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getAttribute()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.getDisplayName()
  id: getDisplayName()
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: getDisplayName()
  fullName: String com.microsoft.applicationinsights.internal.config.JmxXmlElement.getDisplayName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 36
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getDisplayName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.getObjectName()
  id: getObjectName()
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: getObjectName()
  fullName: String com.microsoft.applicationinsights.internal.config.JmxXmlElement.getObjectName()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 45
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getObjectName()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.getType()
  id: getType()
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: getType()
  fullName: String com.microsoft.applicationinsights.internal.config.JmxXmlElement.getType()
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 63
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public String getType()
    return:
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.setAttribute(String)
  id: setAttribute(String)
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: setAttribute(String attribute)
  fullName: void com.microsoft.applicationinsights.internal.config.JmxXmlElement.setAttribute(String attribute)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 59
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setAttribute(String attribute)
    parameters:
    - id: attribute
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.setDisplayName(String)
  id: setDisplayName(String)
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: setDisplayName(String displayName)
  fullName: void com.microsoft.applicationinsights.internal.config.JmxXmlElement.setDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 41
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.setObjectName(String)
  id: setObjectName(String)
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: setObjectName(String objectName)
  fullName: void com.microsoft.applicationinsights.internal.config.JmxXmlElement.setObjectName(String objectName)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 50
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setObjectName(String objectName)
    parameters:
    - id: objectName
      type: "26831127"
- uid: com.microsoft.applicationinsights.internal.config._jmx_xml_element.setType(String)
  id: setType(String)
  parent: com.microsoft.applicationinsights.internal.config._jmx_xml_element
  href: com.microsoft.applicationinsights.internal.config._jmx_xml_element.yml
  langs:
  - java
  name: setType(String type)
  fullName: void com.microsoft.applicationinsights.internal.config.JmxXmlElement.setType(String type)
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
    startLine: 68
  package: com.microsoft.applicationinsights.internal.config
  syntax:
    content: public void setType(String type)
    parameters:
    - id: type
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
