items:
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context_test
  id: _internal_context_test
  parent: com.microsoft.applicationinsights.extensibility.context
  children:
  - com.microsoft.applicationinsights.extensibility.context._internal_context_test.testSetAgentVersion()
  - com.microsoft.applicationinsights.extensibility.context._internal_context_test.testSetSdkVersion()
  href: com.microsoft.applicationinsights.extensibility.context._internal_context_test.yml
  langs:
  - java
  name: InternalContextTest
  fullName: com.microsoft.applicationinsights.extensibility.context.InternalContextTest
  type: Class
  source:
    remote: &o0
      path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/InternalContextTest.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/InternalContextTest.java
    startLine: 29
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public class InternalContextTest
  inheritance:
  - java.lang.Object
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context_test.testSetAgentVersion()
  id: testSetAgentVersion()
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context_test
  href: com.microsoft.applicationinsights.extensibility.context._internal_context_test.yml
  langs:
  - java
  name: testSetAgentVersion()
  fullName: void com.microsoft.applicationinsights.extensibility.context.InternalContextTest.testSetAgentVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/InternalContextTest.java
    startLine: 31
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetAgentVersion()
- uid: com.microsoft.applicationinsights.extensibility.context._internal_context_test.testSetSdkVersion()
  id: testSetSdkVersion()
  parent: com.microsoft.applicationinsights.extensibility.context._internal_context_test
  href: com.microsoft.applicationinsights.extensibility.context._internal_context_test.yml
  langs:
  - java
  name: testSetSdkVersion()
  fullName: void com.microsoft.applicationinsights.extensibility.context.InternalContextTest.testSetSdkVersion()
  type: Method
  source:
    remote: *o0
    path: core/src/test/java/com/microsoft/applicationinsights/extensibility/context/InternalContextTest.java
    startLine: 42
  package: com.microsoft.applicationinsights.extensibility.context
  syntax:
    content: public void testSetSdkVersion()
references: []
