items:
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer
  id: _prepared_statement_byte_code_transformer
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql
  children:
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.transform(byte[])
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.yml
  langs:
  - java
  name: PreparedStatementByteCodeTransformer
  fullName: com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementByteCodeTransformer
  type: Class
  source:
    remote: &o0
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementByteCodeTransformer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementByteCodeTransformer.java
    startLine: 31
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public class PreparedStatementByteCodeTransformer implements ByteCodeTransformer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  inheritedMembers:
  - com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.PreparedStatementByteCodeTransformer(ClassInstrumentationData)
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.transform(byte[])
  id: transform(byte[])
  parent: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer
  href: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.yml
  langs:
  - java
  name: transform(byte[] originalBuffer)
  fullName: byte [] com.microsoft.applicationinsights.agent.internal.agent.sql.PreparedStatementByteCodeTransformer.transform(byte[] originalBuffer)
  type: Method
  source:
    remote: *o0
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementByteCodeTransformer.java
    startLine: 39
  package: com.microsoft.applicationinsights.agent.internal.agent.sql
  syntax:
    content: public byte[] transform(byte[] originalBuffer)
    parameters:
    - id: originalBuffer
      type: bc819c2f
    return:
      type: bc819c2f
  overridden: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.transform(byte[])
references:
- uid: bc819c2f
  spec.java:
  - name: byte[]
    fullName: byte[]
- uid: com.microsoft.applicationinsights.agent.internal.agent.sql._prepared_statement_byte_code_transformer.PreparedStatementByteCodeTransformer(ClassInstrumentationData)
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.yml
  name: ByteCodeTransformer
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ByteCodeTransformer
  type: Interface
  summary: <p>Created by gupele on 8/3/2015. </p>
  syntax:
    content: public interface ByteCodeTransformer
- uid: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data
  parent: com.microsoft.applicationinsights.agent.internal.agent
  href: com.microsoft.applicationinsights.agent.internal.agent._class_instrumentation_data.yml
  name: ClassInstrumentationData
  fullName: com.microsoft.applicationinsights.agent.internal.agent.ClassInstrumentationData
  type: Class
  summary: >-
    <p>An 'instrumented' class data</p>

    <p>Created by gupele on 5/19/2015. </p>
  syntax:
    content: public class ClassInstrumentationData
- uid: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.transform(byte[])
  parent: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer
  href: com.microsoft.applicationinsights.agent.internal.agent._byte_code_transformer.yml
  name: transform(byte[] originalBuffer)
  fullName: byte [] com.microsoft.applicationinsights.agent.internal.agent.ByteCodeTransformer.transform(byte[] originalBuffer)
  type: Method
  syntax:
    content: public byte[] transform(byte[] originalBuffer)
    parameters:
    - id: originalBuffer
      type: bc819c2f
    return:
      type: bc819c2f
