items:
- uid: com.microsoft.applicationinsights.agent.internal.logger
  id: logger
  children:
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  - com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger._logging_level
  href: com.microsoft.applicationinsights.agent.internal.logger.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.agent.internal.logger
  fullName: com.microsoft.applicationinsights.agent.internal.logger
  type: Namespace
  source:
    remote:
      path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
    startLine: 21
  syntax:
    content: namespace logger
references:
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger
  parent: com.microsoft.applicationinsights.agent.internal.logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger.yml
  name: InternalAgentLogger
  fullName: com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger
  type: Enum
  summary: <p>Created by gupele on 6/3/2015. </p>
  syntax:
    content: public enum InternalAgentLogger
- uid: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger._logging_level
  parent: com.microsoft.applicationinsights.agent.internal.logger
  href: com.microsoft.applicationinsights.agent.internal.logger._internal_agent_logger._logging_level.yml
  name: InternalAgentLogger.LoggingLevel
  fullName: com.microsoft.applicationinsights.agent.internal.logger.InternalAgentLogger.LoggingLevel
  type: Enum
  syntax:
    content: public enum LoggingLevel
