items:
- uid: com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06
  id: _definitie6be58c5b9a8abd084a014c594940a06
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06.yml
  langs:
  - java
  name: ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
    startLine: 306
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway definition allowing to continue adding more backend HTTP configurations or start adding request routing rules. </p>
  syntax:
    content: public interface WithHttpConfigOrRequestRoutingRule extends ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithRequestRoutingRule
  inheritedMembers:
  - com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.defineBackendHttpConfiguration(String)
  - com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.defineRequestRoutingRule(String)
references:
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.defineBackendHttpConfiguration(String)
  parent: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.yml
  name: defineBackendHttpConfiguration(String name)
  fullName: ApplicationGatewayBackendHttpConfiguration.DefinitionStages.Blank<WithHttpConfigOrRequestRoutingRule> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfig.defineBackendHttpConfiguration(String name)
  type: Method
  summary: <p>Begins the definition of a new application gateway backend HTTP configuration to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayBackendHttpConfiguration.DefinitionStages.Blank<WithHttpConfigOrRequestRoutingRule> defineBackendHttpConfiguration(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the backend HTTP configuration </p>
    return:
      type: 87765286com.microsoft.azure.management.network._application_gateway._definitie6be58c5b9a8abd084a014c594940a06a08ddfce
      description: <p>the first stage of the backend HTTP configuration definition </p>
- uid: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.defineRequestRoutingRule(String)
  parent: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2
  href: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.yml
  name: defineRequestRoutingRule(String name)
  fullName: ApplicationGatewayRequestRoutingRule.DefinitionStages.Blank<WithRequestRoutingRuleOrCreate> com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithRequestRoutingRule.defineRequestRoutingRule(String name)
  type: Method
  summary: <p>Begins the definition of a new application gateway request routing rule to be attached to the gateway. </p>
  syntax:
    content: public ApplicationGatewayRequestRoutingRule.DefinitionStages.Blank<WithRequestRoutingRuleOrCreate> defineRequestRoutingRule(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>a unique name for the request routing rule </p>
    return:
      type: 964ff059com.microsoft.azure.management.network._application_gateway._definiti71c4ae773f713c0a38df862000e61f64a08ddfce
      description: <p>the first stage of the request routing rule </p>
- uid: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition_stages._with_http_config.yml
  name: ApplicationGateway.DefinitionStages.WithHttpConfig
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithHttpConfig
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add a backend HTTP configuration. </p>
  syntax:
    content: public interface WithHttpConfig
- uid: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definiti18d9de02229fe648454f4596f54d6fd2.yml
  name: ApplicationGateway.DefinitionStages.WithRequestRoutingRule
  fullName: com.microsoft.azure.management.network.ApplicationGateway.DefinitionStages.WithRequestRoutingRule
  type: Interface
  summary: <p>The stage of an application gateway definition allowing to add a request routing rule. </p>
  syntax:
    content: public interface WithRequestRoutingRule
- uid: com.microsoft.azure.management.network._application_gateway._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway._definition.yml
  name: ApplicationGateway.Definition
  fullName: com.microsoft.azure.management.network.ApplicationGateway.Definition
  type: Interface
  summary: <p>The entirety of the application gateway definition. </p>
  syntax:
    content: public interface Definition extends ApplicationGateway.DefinitionStages.Blank,ApplicationGateway.DefinitionStages.WithGroup,ApplicationGateway.DefinitionStages.WithCreate,ApplicationGateway.DefinitionStages.WithSku,ApplicationGateway.DefinitionStages.WithContainingSubnet,ApplicationGateway.DefinitionStages.WithPrivateFrontend,ApplicationGateway.DefinitionStages.WithPrivateFrontendOptional,ApplicationGateway.DefinitionStages.WithPublicFrontend,ApplicationGateway.DefinitionStages.WithBackend,ApplicationGateway.DefinitionStages.WithBackendOrHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfig,ApplicationGateway.DefinitionStages.WithHttpConfigOrRequestRoutingRule,ApplicationGateway.DefinitionStages.WithHttpListener,ApplicationGateway.DefinitionStages.WithHttpListenerOrBackend,ApplicationGateway.DefinitionStages.WithRequestRoutingRule,ApplicationGateway.DefinitionStages.WithRequestRoutingRuleOrCreate
