items:
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39
  id: _application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.withSslCertificatePassword(String)
  href: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.yml
  langs:
  - java
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 142
  package: com.microsoft.azure.management.network
  summary: <p>The stage of an application gateway HTTP listener definition allowing to specify the password for the private key of the imported SSL certificate. </p>
  syntax:
    content: public interface WithSslPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.withSslCertificatePassword(String)
  id: withSslCertificatePassword(String)
  parent: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39
  href: com.microsoft.azure.management.network._application_gateway_frontend_httc0c3cf848fdcdbd04f85c06ece0f6a39.yml
  langs:
  - java
  name: withSslCertificatePassword(String password)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>.withSslCertificatePassword(String password)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFrontendHttpListener.java
    startLine: 148
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the password for the specified PFX file containing the private key of the imported SSL certificate. </p>
  syntax:
    content: public WithAttach<ParentT> withSslCertificatePassword(String password)
    parameters:
    - id: password
      type: "26831127"
      description: <p>the password of the imported PFX file </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20da8a2936
  spec.java:
  - uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20
    name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_http_listener._definition.yml
  name: ApplicationGatewayFrontendHttpListener.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of an application gateway HTTP listener definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends ApplicationGatewayFrontendHttpListener.DefinitionStages.Blank<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontend<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithFrontendPort<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslCertificate<ParentT>,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithSslPassword<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_frontend_htt14b30ac6fc7403e4061d797436204d20.yml
  name: ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.ApplicationGatewayFrontendHttpListener.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of an application gateway HTTP listener. </p>

    <p>At this stage, any remaining optional settings can be specified, or the definition can be attached to the parent application gateway definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition,ApplicationGatewayFrontendHttpListener.DefinitionStages.WithProtocol<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the stage of the parent application gateway definition to return to after attaching </p>
