items:
- uid: com.microsoft.applicationinsights.web.javaee
  id: javaee
  children:
  - com.microsoft.applicationinsights.web.javaee._request_name
  - com.microsoft.applicationinsights.web.javaee._request_name_interceptor
  href: com.microsoft.applicationinsights.web.javaee.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.web.javaee
  fullName: com.microsoft.applicationinsights.web.javaee
  type: Namespace
  source:
    remote:
      path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestName.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: web/src/main/java/com/microsoft/applicationinsights/web/javaee/RequestName.java
    startLine: 20
  syntax:
    content: namespace javaee
references:
- uid: com.microsoft.applicationinsights.web.javaee._request_name
  parent: com.microsoft.applicationinsights.web.javaee
  href: com.microsoft.applicationinsights.web.javaee._request_name.yml
  name: RequestName
  fullName: com.microsoft.applicationinsights.web.javaee.RequestName
  type: Interface
  syntax:
    content: public interface RequestName
- uid: com.microsoft.applicationinsights.web.javaee._request_name_interceptor
  parent: com.microsoft.applicationinsights.web.javaee
  href: com.microsoft.applicationinsights.web.javaee._request_name_interceptor.yml
  name: RequestNameInterceptor
  fullName: com.microsoft.applicationinsights.web.javaee.RequestNameInterceptor
  type: Class
  syntax:
    content: public class RequestNameInterceptor
