items:
- uid: jniinterop._replicator_settings_helper
  id: _replicator_settings_helper
  parent: jniinterop
  children:
  - jniinterop._replicator_settings_helper.FromNative(__in JNIEnv *,__in const FABRIC_REPLICATOR_SETTINGS *,__in const StringLiteral)
  href: jniinterop._replicator_settings_helper.yml
  langs:
  - java
  name: ReplicatorSettingsHelper
  fullName: jniinterop.ReplicatorSettingsHelper
  type: Struct
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/InteropHelper.h
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.h
    startLine: 55
  package: jniinterop
  syntax:
    content: public struct ReplicatorSettingsHelper
- uid: jniinterop._replicator_settings_helper.FromNative(__in JNIEnv *,__in const FABRIC_REPLICATOR_SETTINGS *,__in const StringLiteral)
  id: FromNative(__in JNIEnv *,__in const FABRIC_REPLICATOR_SETTINGS *,__in const StringLiteral)
  parent: jniinterop._replicator_settings_helper
  href: jniinterop._replicator_settings_helper.yml
  langs:
  - java
  name: FromNative(__in JNIEnv *env, __in const FABRIC_REPLICATOR_SETTINGS *replicatorSettings, __in const StringLiteral TraceComponent)
  fullName: jobject ReplicatorSettingsHelper.FromNative(__in JNIEnv *env, __in const FABRIC_REPLICATOR_SETTINGS *replicatorSettings, __in const StringLiteral TraceComponent)
  type: Method
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
    startLine: 477
  package: jniinterop
  syntax:
    content: public static jobject FromNative(__in JNIEnv *env, __in const FABRIC_REPLICATOR_SETTINGS *replicatorSettings, __in const StringLiteral TraceComponent)
    parameters:
    - id: env
      type: ca805266
    - id: replicatorSettings
      type: 0f65acb8
    - id: TraceComponent
      type: 402f4d53
    return:
      type: d7e11706
references:
- uid: ca805266
  spec.java:
  - name: __in JNIEnv *
    fullName: __in JNIEnv *
- uid: 0f65acb8
  spec.java:
  - name: __in const FABRIC_REPLICATOR_SETTINGS *
    fullName: __in const FABRIC_REPLICATOR_SETTINGS *
- uid: 402f4d53
  spec.java:
  - name: __in const StringLiteral
    fullName: __in const StringLiteral
- uid: d7e11706
  spec.java:
  - name: jobject
    fullName: jobject
