items:
- uid: jniinterop._application_parameter_list_helper
  id: _application_parameter_list_helper
  parent: jniinterop
  children:
  - jniinterop._application_parameter_list_helper.createApplicationParameterListObject(__in JNIEnv *,__in const FABRIC_APPLICATION_PARAMETER_LIST *,__in const StringLiteral)
  href: jniinterop._application_parameter_list_helper.yml
  langs:
  - java
  name: ApplicationParameterListHelper
  fullName: jniinterop.ApplicationParameterListHelper
  type: Struct
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/UpgradeHelper.h
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/UpgradeHelper.h
    startLine: 26
  package: jniinterop
  syntax:
    content: public struct ApplicationParameterListHelper
- uid: jniinterop._application_parameter_list_helper.createApplicationParameterListObject(__in JNIEnv *,__in const FABRIC_APPLICATION_PARAMETER_LIST *,__in const StringLiteral)
  id: createApplicationParameterListObject(__in JNIEnv *,__in const FABRIC_APPLICATION_PARAMETER_LIST *,__in const StringLiteral)
  parent: jniinterop._application_parameter_list_helper
  href: jniinterop._application_parameter_list_helper.yml
  langs:
  - java
  name: createApplicationParameterListObject(__in JNIEnv *env, __in const FABRIC_APPLICATION_PARAMETER_LIST *applicationParameterList, __in const StringLiteral TraceComponent)
  fullName: jobject ApplicationParameterListHelper.createApplicationParameterListObject(__in JNIEnv *env, __in const FABRIC_APPLICATION_PARAMETER_LIST *applicationParameterList, __in const StringLiteral TraceComponent)
  type: Method
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/UpgradeHelper.cpp
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/UpgradeHelper.cpp
    startLine: 58
  package: jniinterop
  syntax:
    content: public static jobject createApplicationParameterListObject(__in JNIEnv *env, __in const FABRIC_APPLICATION_PARAMETER_LIST *applicationParameterList, __in const StringLiteral TraceComponent)
    parameters:
    - id: env
      type: ca805266
    - id: applicationParameterList
      type: 92cec75d
    - id: TraceComponent
      type: 402f4d53
    return:
      type: d7e11706
references:
- uid: ca805266
  spec.java:
  - name: __in JNIEnv *
    fullName: __in JNIEnv *
- uid: 92cec75d
  spec.java:
  - name: __in const FABRIC_APPLICATION_PARAMETER_LIST *
    fullName: __in const FABRIC_APPLICATION_PARAMETER_LIST *
- uid: 402f4d53
  spec.java:
  - name: __in const StringLiteral
    fullName: __in const StringLiteral
- uid: d7e11706
  spec.java:
  - name: jobject
    fullName: jobject
