items:
- uid: jniinterop._configuration_package_change_handler_broker
  id: _configuration_package_change_handler_broker
  parent: jniinterop
  children:
  - jniinterop._configuration_package_change_handler_broker.~ConfigurationPackageChangeHandlerBroker()
  - jniinterop._configuration_package_change_handler_broker.ConfigurationPackageChangeHandlerBroker()
  - jniinterop._configuration_package_change_handler_broker.Initialize(JNIEnv *,jobject)
  - jniinterop._configuration_package_change_handler_broker.OnPackageAdded(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *)
  - jniinterop._configuration_package_change_handler_broker.OnPackageModified(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *,IFabricConfigurationPackage *)
  - jniinterop._configuration_package_change_handler_broker.OnPackageRemoved(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *)
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: ConfigurationPackageChangeHandlerBroker
  fullName: jniinterop.ConfigurationPackageChangeHandlerBroker
  type: Class
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.h
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.h
    startLine: 8
  package: jniinterop
  syntax:
    content: public class ConfigurationPackageChangeHandlerBroker
  inheritance:
  - java.lang.Object
  - IFabricConfigurationPackageChangeHandler
- uid: jniinterop._configuration_package_change_handler_broker.~ConfigurationPackageChangeHandlerBroker()
  id: ~ConfigurationPackageChangeHandlerBroker()
  parent: jniinterop._configuration_package_change_handler_broker
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: ~ConfigurationPackageChangeHandlerBroker()
  fullName: ConfigurationPackageChangeHandlerBroker.~ConfigurationPackageChangeHandlerBroker()
  type: Constructor
  source:
    remote: &o0
      path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
    startLine: 15
  package: jniinterop
  syntax:
    content: public ~ConfigurationPackageChangeHandlerBroker()
- uid: jniinterop._configuration_package_change_handler_broker.ConfigurationPackageChangeHandlerBroker()
  id: ConfigurationPackageChangeHandlerBroker()
  parent: jniinterop._configuration_package_change_handler_broker
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: ConfigurationPackageChangeHandlerBroker()
  fullName: ConfigurationPackageChangeHandlerBroker.ConfigurationPackageChangeHandlerBroker()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
    startLine: 10
  package: jniinterop
  syntax:
    content: public ConfigurationPackageChangeHandlerBroker()
- uid: jniinterop._configuration_package_change_handler_broker.Initialize(JNIEnv *,jobject)
  id: Initialize(JNIEnv *,jobject)
  parent: jniinterop._configuration_package_change_handler_broker
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: Initialize(JNIEnv *jenv, jobject instance)
  fullName: HRESULT ConfigurationPackageChangeHandlerBroker.Initialize(JNIEnv *jenv, jobject instance)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
    startLine: 26
  package: jniinterop
  syntax:
    content: public HRESULT STDMETHODCALLTYPE Initialize(JNIEnv *jenv, jobject instance)
    parameters:
    - id: jenv
      type: cd831cde
    - id: instance
      type: d7e11706
    return:
      type: 722eb900
- uid: jniinterop._configuration_package_change_handler_broker.OnPackageAdded(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *)
  id: OnPackageAdded(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *)
  parent: jniinterop._configuration_package_change_handler_broker
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: OnPackageAdded(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *codePackage)
  fullName: void STDMETHODCALLTYPE ConfigurationPackageChangeHandlerBroker.OnPackageAdded(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *codePackage)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
    startLine: 43
  package: jniinterop
  syntax:
    content: public void STDMETHODCALLTYPE OnPackageAdded(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *codePackage)
    parameters:
    - id: source
      type: a7e79ca9
    - id: codePackage
      type: 19f1352a
    return:
      type: 79a073f5
- uid: jniinterop._configuration_package_change_handler_broker.OnPackageModified(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *,IFabricConfigurationPackage *)
  id: OnPackageModified(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *,IFabricConfigurationPackage *)
  parent: jniinterop._configuration_package_change_handler_broker
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: OnPackageModified(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *previousCodePackage, IFabricConfigurationPackage *codePackage)
  fullName: void STDMETHODCALLTYPE ConfigurationPackageChangeHandlerBroker.OnPackageModified(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *previousCodePackage, IFabricConfigurationPackage *codePackage)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
    startLine: 77
  package: jniinterop
  syntax:
    content: public void STDMETHODCALLTYPE OnPackageModified(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *previousCodePackage, IFabricConfigurationPackage *codePackage)
    parameters:
    - id: source
      type: a7e79ca9
    - id: previousCodePackage
      type: 19f1352a
    - id: codePackage
      type: 19f1352a
    return:
      type: 79a073f5
- uid: jniinterop._configuration_package_change_handler_broker.OnPackageRemoved(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *)
  id: OnPackageRemoved(IFabricCodePackageActivationContext *,IFabricConfigurationPackage *)
  parent: jniinterop._configuration_package_change_handler_broker
  href: jniinterop._configuration_package_change_handler_broker.yml
  langs:
  - java
  name: OnPackageRemoved(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *codePackage)
  fullName: void STDMETHODCALLTYPE ConfigurationPackageChangeHandlerBroker.OnPackageRemoved(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *codePackage)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ConfigurationPackageChangeHandlerBroker.cpp
    startLine: 60
  package: jniinterop
  syntax:
    content: public void STDMETHODCALLTYPE OnPackageRemoved(IFabricCodePackageActivationContext *source, IFabricConfigurationPackage *codePackage)
    parameters:
    - id: source
      type: a7e79ca9
    - id: codePackage
      type: 19f1352a
    return:
      type: 79a073f5
references:
- uid: cd831cde
  spec.java:
  - name: JNIEnv *
    fullName: JNIEnv *
- uid: d7e11706
  spec.java:
  - name: jobject
    fullName: jobject
- uid: 722eb900
  spec.java:
  - name: HRESULT STDMETHODCALLTYPE
    fullName: HRESULT STDMETHODCALLTYPE
- uid: a7e79ca9
  spec.java:
  - name: IFabricCodePackageActivationContext *
    fullName: IFabricCodePackageActivationContext *
- uid: 19f1352a
  spec.java:
  - name: IFabricConfigurationPackage *
    fullName: IFabricConfigurationPackage *
- uid: 79a073f5
  spec.java:
  - name: void STDMETHODCALLTYPE
    fullName: void STDMETHODCALLTYPE
