items:
- uid: jniinterop._application_upgrade_progress_helper
  id: _application_upgrade_progress_helper
  parent: jniinterop
  children:
  - jniinterop._application_upgrade_progress_helper.FromNative(__in JNIEnv *,__in IFabricApplicationUpgradeProgressResult3 *,__in const StringLiteral)
  - jniinterop._application_upgrade_progress_helper.GetChangedUpgradeDomains(__in JNIEnv *,__in IFabricApplicationUpgradeProgressResult *,__in IFabricApplicationUpgradeProgressResult *,__in const StringLiteral)
  href: jniinterop._application_upgrade_progress_helper.yml
  langs:
  - java
  name: ApplicationUpgradeProgressHelper
  fullName: jniinterop.ApplicationUpgradeProgressHelper
  type: Struct
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/InteropHelper.h
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.h
    startLine: 32
  package: jniinterop
  syntax:
    content: public struct ApplicationUpgradeProgressHelper
- uid: jniinterop._application_upgrade_progress_helper.FromNative(__in JNIEnv *,__in IFabricApplicationUpgradeProgressResult3 *,__in const StringLiteral)
  id: FromNative(__in JNIEnv *,__in IFabricApplicationUpgradeProgressResult3 *,__in const StringLiteral)
  parent: jniinterop._application_upgrade_progress_helper
  href: jniinterop._application_upgrade_progress_helper.yml
  langs:
  - java
  name: FromNative(__in JNIEnv *env, __in IFabricApplicationUpgradeProgressResult3 *upgradeProgress, __in const StringLiteral TraceComponent)
  fullName: jobject ApplicationUpgradeProgressHelper.FromNative(__in JNIEnv *env, __in IFabricApplicationUpgradeProgressResult3 *upgradeProgress, __in const StringLiteral TraceComponent)
  type: Method
  source:
    remote: &o0
      path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
    startLine: 225
  package: jniinterop
  syntax:
    content: public static jobject FromNative(__in JNIEnv *env, __in IFabricApplicationUpgradeProgressResult3 *upgradeProgress, __in const StringLiteral TraceComponent)
    parameters:
    - id: env
      type: ca805266
    - id: upgradeProgress
      type: 30ba58cf
    - id: TraceComponent
      type: 402f4d53
    return:
      type: d7e11706
- uid: jniinterop._application_upgrade_progress_helper.GetChangedUpgradeDomains(__in JNIEnv *,__in IFabricApplicationUpgradeProgressResult *,__in IFabricApplicationUpgradeProgressResult *,__in const StringLiteral)
  id: GetChangedUpgradeDomains(__in JNIEnv *,__in IFabricApplicationUpgradeProgressResult *,__in IFabricApplicationUpgradeProgressResult *,__in const StringLiteral)
  parent: jniinterop._application_upgrade_progress_helper
  href: jniinterop._application_upgrade_progress_helper.yml
  langs:
  - java
  name: GetChangedUpgradeDomains(__in JNIEnv *env, __in IFabricApplicationUpgradeProgressResult *upgradeProgressPtr, __in IFabricApplicationUpgradeProgressResult *previousProgressPtr, __in const StringLiteral TraceComponent)
  fullName: jobjectArray ApplicationUpgradeProgressHelper.GetChangedUpgradeDomains(__in JNIEnv *env, __in IFabricApplicationUpgradeProgressResult *upgradeProgressPtr, __in IFabricApplicationUpgradeProgressResult *previousProgressPtr, __in const StringLiteral TraceComponent)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
    startLine: 399
  package: jniinterop
  syntax:
    content: public static jobjectArray GetChangedUpgradeDomains(__in JNIEnv *env, __in IFabricApplicationUpgradeProgressResult *upgradeProgressPtr, __in IFabricApplicationUpgradeProgressResult *previousProgressPtr, __in const StringLiteral TraceComponent)
    parameters:
    - id: env
      type: ca805266
    - id: upgradeProgressPtr
      type: f0acb53f
    - id: previousProgressPtr
      type: f0acb53f
    - id: TraceComponent
      type: 402f4d53
    return:
      type: 722fd341
references:
- uid: ca805266
  spec.java:
  - name: __in JNIEnv *
    fullName: __in JNIEnv *
- uid: 30ba58cf
  spec.java:
  - name: __in IFabricApplicationUpgradeProgressResult3 *
    fullName: __in IFabricApplicationUpgradeProgressResult3 *
- uid: 402f4d53
  spec.java:
  - name: __in const StringLiteral
    fullName: __in const StringLiteral
- uid: d7e11706
  spec.java:
  - name: jobject
    fullName: jobject
- uid: f0acb53f
  spec.java:
  - name: __in IFabricApplicationUpgradeProgressResult *
    fullName: __in IFabricApplicationUpgradeProgressResult *
- uid: 722fd341
  spec.java:
  - name: jobjectArray
    fullName: jobjectArray
