items:
- uid: jniinterop._fabric_client_settings_helper
  id: _fabric_client_settings_helper
  parent: jniinterop
  children:
  - jniinterop._fabric_client_settings_helper.FromNative(__in JNIEnv *,__in const FABRIC_CLIENT_SETTINGS *,__in const StringLiteral)
  href: jniinterop._fabric_client_settings_helper.yml
  langs:
  - java
  name: FabricClientSettingsHelper
  fullName: jniinterop.FabricClientSettingsHelper
  type: Struct
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/InteropHelper.h
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.h
    startLine: 47
  package: jniinterop
  syntax:
    content: public struct FabricClientSettingsHelper
- uid: jniinterop._fabric_client_settings_helper.FromNative(__in JNIEnv *,__in const FABRIC_CLIENT_SETTINGS *,__in const StringLiteral)
  id: FromNative(__in JNIEnv *,__in const FABRIC_CLIENT_SETTINGS *,__in const StringLiteral)
  parent: jniinterop._fabric_client_settings_helper
  href: jniinterop._fabric_client_settings_helper.yml
  langs:
  - java
  name: FromNative(__in JNIEnv *env, __in const FABRIC_CLIENT_SETTINGS *clientSettings, __in const StringLiteral TraceComponent)
  fullName: jobject FabricClientSettingsHelper.FromNative(__in JNIEnv *env, __in const FABRIC_CLIENT_SETTINGS *clientSettings, __in const StringLiteral TraceComponent)
  type: Method
  source:
    remote:
      path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/InteropHelper.cpp
    startLine: 419
  package: jniinterop
  syntax:
    content: public static jobject FromNative(__in JNIEnv *env, __in const FABRIC_CLIENT_SETTINGS *clientSettings, __in const StringLiteral TraceComponent)
    parameters:
    - id: env
      type: ca805266
    - id: clientSettings
      type: 11b2579c
    - id: TraceComponent
      type: 402f4d53
    return:
      type: d7e11706
references:
- uid: ca805266
  spec.java:
  - name: __in JNIEnv *
    fullName: __in JNIEnv *
- uid: 11b2579c
  spec.java:
  - name: __in const FABRIC_CLIENT_SETTINGS *
    fullName: __in const FABRIC_CLIENT_SETTINGS *
- uid: 402f4d53
  spec.java:
  - name: __in const StringLiteral
    fullName: __in const StringLiteral
- uid: d7e11706
  spec.java:
  - name: jobject
    fullName: jobject
