items:
- uid: jninterop._replicator_settings_proxy
  id: _replicator_settings_proxy
  parent: jninterop
  children:
  - jninterop._replicator_settings_proxy.~ReplicatorSettingsProxy()
  - jninterop._replicator_settings_proxy.getFabricReplicatorSettings()
  - jninterop._replicator_settings_proxy.ReplicatorSettingsProxy()
  - jninterop._replicator_settings_proxy.ReplicatorSettingsProxy(long,long,wstring,int,long,long,long,long,bool,long,bool,long,bool,long,long,long,long,long,long,long)
  - jninterop._replicator_settings_proxy.ReplicatorSettingsProxy(wstring)
  href: jninterop._replicator_settings_proxy.yml
  langs:
  - java
  name: ReplicatorSettingsProxy
  fullName: jninterop.ReplicatorSettingsProxy
  type: Class
  source:
    remote: &o1
      path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.h
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.h
    startLine: 8
  package: jninterop
  syntax:
    content: public class ReplicatorSettingsProxy
  inheritance:
  - java.lang.Object
- uid: jninterop._replicator_settings_proxy.~ReplicatorSettingsProxy()
  id: ~ReplicatorSettingsProxy()
  parent: jninterop._replicator_settings_proxy
  href: jninterop._replicator_settings_proxy.yml
  langs:
  - java
  name: ~ReplicatorSettingsProxy()
  fullName: ReplicatorSettingsProxy.~ReplicatorSettingsProxy()
  type: Constructor
  source:
    remote: &o0
      path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.cpp
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.cpp
    startLine: 73
  package: jninterop
  syntax:
    content: public ~ReplicatorSettingsProxy()
- uid: jninterop._replicator_settings_proxy.getFabricReplicatorSettings()
  id: getFabricReplicatorSettings()
  parent: jninterop._replicator_settings_proxy
  href: jninterop._replicator_settings_proxy.yml
  langs:
  - java
  name: getFabricReplicatorSettings()
  fullName: FABRIC_REPLICATOR_SETTINGS ReplicatorSettingsProxy.getFabricReplicatorSettings()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.cpp
    startLine: 67
  package: jninterop
  syntax:
    content: public FABRIC_REPLICATOR_SETTINGS getFabricReplicatorSettings()
    return:
      type: 95ac5a5f
- uid: jninterop._replicator_settings_proxy.ReplicatorSettingsProxy()
  id: ReplicatorSettingsProxy()
  parent: jninterop._replicator_settings_proxy
  href: jninterop._replicator_settings_proxy.yml
  langs:
  - java
  name: ReplicatorSettingsProxy()
  fullName: jninterop.ReplicatorSettingsProxy.ReplicatorSettingsProxy()
  type: Constructor
  source:
    remote: *o1
    path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.h
    startLine: 11
  package: jninterop
  syntax:
    content: public ReplicatorSettingsProxy()
- uid: jninterop._replicator_settings_proxy.ReplicatorSettingsProxy(long,long,wstring,int,long,long,long,long,bool,long,bool,long,bool,long,long,long,long,long,long,long)
  id: ReplicatorSettingsProxy(long,long,wstring,int,long,long,long,long,bool,long,bool,long,bool,long,long,long,long,long,long,long)
  parent: jninterop._replicator_settings_proxy
  href: jninterop._replicator_settings_proxy.yml
  langs:
  - java
  name: ReplicatorSettingsProxy(long retryInterval, long batchAcknowledgementInterval, wstring replicatorAddress, int securityCredentials, long initialReplicationQueueSize, long maxReplicationQueueSize, long initialCopyQueueSize, long maxCopyQueueSize, bool requireServiceAck, long maxReplicationQueueMemorySize, bool secondaryClearAcknowledgedOperations, long maxReplicationMessageSize, bool useStreamFaultsAndEndOfStreamOperationAck, long initialPrimaryReplicationQueueSize, long maxPrimaryReplicationQueueSize, long maxPrimaryReplicationQueueMemorySize, long initialSecondaryReplicationQueueSize, long maxSecondaryReplicationQueueSize, long maxSecondaryReplicationQueueMemorySize, long primaryWaitForPendingQuorumsTimeout)
  fullName: jninterop.ReplicatorSettingsProxy.ReplicatorSettingsProxy(long retryInterval, long batchAcknowledgementInterval, wstring replicatorAddress, int securityCredentials, long initialReplicationQueueSize, long maxReplicationQueueSize, long initialCopyQueueSize, long maxCopyQueueSize, bool requireServiceAck, long maxReplicationQueueMemorySize, bool secondaryClearAcknowledgedOperations, long maxReplicationMessageSize, bool useStreamFaultsAndEndOfStreamOperationAck, long initialPrimaryReplicationQueueSize, long maxPrimaryReplicationQueueSize, long maxPrimaryReplicationQueueMemorySize, long initialSecondaryReplicationQueueSize, long maxSecondaryReplicationQueueSize, long maxSecondaryReplicationQueueMemorySize, long primaryWaitForPendingQuorumsTimeout)
  type: Constructor
  source:
    remote: *o1
    path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.h
    startLine: 13
  package: jninterop
  syntax:
    content: public ReplicatorSettingsProxy(long retryInterval, long batchAcknowledgementInterval, wstring replicatorAddress, int securityCredentials, long initialReplicationQueueSize, long maxReplicationQueueSize, long initialCopyQueueSize, long maxCopyQueueSize, bool requireServiceAck, long maxReplicationQueueMemorySize, bool secondaryClearAcknowledgedOperations, long maxReplicationMessageSize, bool useStreamFaultsAndEndOfStreamOperationAck, long initialPrimaryReplicationQueueSize, long maxPrimaryReplicationQueueSize, long maxPrimaryReplicationQueueMemorySize, long initialSecondaryReplicationQueueSize, long maxSecondaryReplicationQueueSize, long maxSecondaryReplicationQueueMemorySize, long primaryWaitForPendingQuorumsTimeout)
    parameters:
    - id: retryInterval
      type: 0364520f
    - id: batchAcknowledgementInterval
      type: 0364520f
    - id: replicatorAddress
      type: 6f1647ce
    - id: securityCredentials
      type: f75371fa
    - id: initialReplicationQueueSize
      type: 0364520f
    - id: maxReplicationQueueSize
      type: 0364520f
    - id: initialCopyQueueSize
      type: 0364520f
    - id: maxCopyQueueSize
      type: 0364520f
    - id: requireServiceAck
      type: 13ff06c5
    - id: maxReplicationQueueMemorySize
      type: 0364520f
    - id: secondaryClearAcknowledgedOperations
      type: 13ff06c5
    - id: maxReplicationMessageSize
      type: 0364520f
    - id: useStreamFaultsAndEndOfStreamOperationAck
      type: 13ff06c5
    - id: initialPrimaryReplicationQueueSize
      type: 0364520f
    - id: maxPrimaryReplicationQueueSize
      type: 0364520f
    - id: maxPrimaryReplicationQueueMemorySize
      type: 0364520f
    - id: initialSecondaryReplicationQueueSize
      type: 0364520f
    - id: maxSecondaryReplicationQueueSize
      type: 0364520f
    - id: maxSecondaryReplicationQueueMemorySize
      type: 0364520f
    - id: primaryWaitForPendingQuorumsTimeout
      type: 0364520f
- uid: jninterop._replicator_settings_proxy.ReplicatorSettingsProxy(wstring)
  id: ReplicatorSettingsProxy(wstring)
  parent: jninterop._replicator_settings_proxy
  href: jninterop._replicator_settings_proxy.yml
  langs:
  - java
  name: ReplicatorSettingsProxy(wstring replicatorAddress)
  fullName: ReplicatorSettingsProxy.ReplicatorSettingsProxy(wstring replicatorAddress)
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/native/jFabricRuntime/ReplicatorSettingsProxy.cpp
    startLine: 10
  package: jninterop
  syntax:
    content: public ReplicatorSettingsProxy(wstring replicatorAddress)
    parameters:
    - id: replicatorAddress
      type: 6f1647ce
references:
- uid: 6f1647ce
  spec.java:
  - name: wstring
    fullName: wstring
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: 13ff06c5
  spec.java:
  - name: bool
    fullName: bool
- uid: 95ac5a5f
  spec.java:
  - name: FABRIC_REPLICATOR_SETTINGS
    fullName: FABRIC_REPLICATOR_SETTINGS
