items:
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings
  id: _operation_retry_settings
  parent: microsoft.servicefabric.services.communication.client
  children:
  - microsoft.servicefabric.services.communication.client._operation_retry_settings.defaultMaxRetryCount()
  - microsoft.servicefabric.services.communication.client._operation_retry_settings.maxRetryBackoffIntervalOnNonTransientErrors()
  - microsoft.servicefabric.services.communication.client._operation_retry_settings.maxRetryBackoffIntervalOnTransientErrors()
  - microsoft.servicefabric.services.communication.client._operation_retry_settings.OperationRetrySettings()
  - microsoft.servicefabric.services.communication.client._operation_retry_settings.OperationRetrySettings(Duration,Duration,int)
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  langs:
  - java
  name: OperationRetrySettings
  fullName: microsoft.servicefabric.services.communication.client.OperationRetrySettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
    startLine: 9
  package: microsoft.servicefabric.services.communication.client
  syntax: &o1
    content: public class OperationRetrySettings
  inheritance:
  - java.lang.Object
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings.defaultMaxRetryCount()
  id: defaultMaxRetryCount()
  parent: microsoft.servicefabric.services.communication.client._operation_retry_settings
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  langs:
  - java
  name: defaultMaxRetryCount()
  fullName: int microsoft.servicefabric.services.communication.client.OperationRetrySettings.defaultMaxRetryCount()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
    startLine: 62
  package: microsoft.servicefabric.services.communication.client
  summary: <p>Specifies the maximum number of times to retry. </p>
  syntax:
    content: public int defaultMaxRetryCount()
    return:
      type: f75371fa
      description: <p>Maximum number of times to retry a specific exception. </p>
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings.maxRetryBackoffIntervalOnNonTransientErrors()
  id: maxRetryBackoffIntervalOnNonTransientErrors()
  parent: microsoft.servicefabric.services.communication.client._operation_retry_settings
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  langs:
  - java
  name: maxRetryBackoffIntervalOnNonTransientErrors()
  fullName: Duration microsoft.servicefabric.services.communication.client.OperationRetrySettings.maxRetryBackoffIntervalOnNonTransientErrors()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
    startLine: 55
  package: microsoft.servicefabric.services.communication.client
  summary: <p>Specifies the maximum interval to back-off before retrying in-case of Non transient errors </p>
  syntax:
    content: public Duration maxRetryBackoffIntervalOnNonTransientErrors()
    return:
      type: e02a2de0
      description: <p>Maximum retry interval to back-off on non transient errors </p>
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings.maxRetryBackoffIntervalOnTransientErrors()
  id: maxRetryBackoffIntervalOnTransientErrors()
  parent: microsoft.servicefabric.services.communication.client._operation_retry_settings
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  langs:
  - java
  name: maxRetryBackoffIntervalOnTransientErrors()
  fullName: Duration microsoft.servicefabric.services.communication.client.OperationRetrySettings.maxRetryBackoffIntervalOnTransientErrors()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
    startLine: 47
  package: microsoft.servicefabric.services.communication.client
  summary: <p>Specifies the maximum interval to back-off before retrying in-case of Transient errors </p>
  syntax:
    content: public Duration maxRetryBackoffIntervalOnTransientErrors()
    return:
      type: e02a2de0
      description: <p>Maximum retry interval to back-off on transient errors </p>
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings.OperationRetrySettings()
  id: OperationRetrySettings()
  parent: microsoft.servicefabric.services.communication.client._operation_retry_settings
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  langs:
  - java
  name: OperationRetrySettings()
  fullName: microsoft.servicefabric.services.communication.client.OperationRetrySettings.OperationRetrySettings()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
    startLine: 20
  package: microsoft.servicefabric.services.communication.client
  summary: <p>Instantiates <xref href="microsoft.servicefabric.services.communication.client._operation_retry_settings" data-throw-if-not-resolved="false"></xref> with default values for the retry settings. The default values for MaxRetryBackoffIntervalOnTransientErrors, NonTransientErrors are 2 seconds. The default value for MaxRetryCount is 10. </p>
  syntax:
    content: public OperationRetrySettings()
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings.OperationRetrySettings(Duration,Duration,int)
  id: OperationRetrySettings(Duration,Duration,int)
  parent: microsoft.servicefabric.services.communication.client._operation_retry_settings
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  langs:
  - java
  name: OperationRetrySettings(Duration maxRetryBackoffIntervalOnTransientErrors, Duration maxRetryBackoffIntervalOnNonTransientErrors, int defaultMaxRetryCount)
  fullName: microsoft.servicefabric.services.communication.client.OperationRetrySettings.OperationRetrySettings(Duration maxRetryBackoffIntervalOnTransientErrors, Duration maxRetryBackoffIntervalOnNonTransientErrors, int defaultMaxRetryCount)
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/communication/client/OperationRetrySettings.java
    startLine: 35
  package: microsoft.servicefabric.services.communication.client
  summary: <p>Instantiates <xref href="microsoft.servicefabric.services.communication.client._operation_retry_settings" data-throw-if-not-resolved="false"></xref> with default values for the retry settings. The default values for MaxRetryBackoffIntervalOnTransientErrors, NonTransientErrors are 2 seconds. The default value for MaxRetryCount is 10. Instantiates <xref href="microsoft.servicefabric.services.communication.client._operation_retry_settings" data-throw-if-not-resolved="false"></xref> with the supplied settings. </p>
  syntax:
    content: public OperationRetrySettings(Duration maxRetryBackoffIntervalOnTransientErrors, Duration maxRetryBackoffIntervalOnNonTransientErrors, int defaultMaxRetryCount)
    parameters:
    - id: maxRetryBackoffIntervalOnTransientErrors
      type: e02a2de0
      description: <p>Specifies the maximum interval to back-off before retrying incase of Transient errors </p>
    - id: maxRetryBackoffIntervalOnNonTransientErrors
      type: e02a2de0
      description: <p>Specifies the maximum interval to back-off before retrying incase of Non transient errors </p>
    - id: defaultMaxRetryCount
      type: f75371fa
      description: <p>Specifies the maximum number of times to retry. </p>
references:
- uid: e02a2de0
  spec.java:
  - name: Duration
    fullName: Duration
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: microsoft.servicefabric.services.communication.client._operation_retry_settings
  parent: microsoft.servicefabric.services.communication.client
  href: microsoft.servicefabric.services.communication.client._operation_retry_settings.yml
  name: OperationRetrySettings
  fullName: microsoft.servicefabric.services.communication.client.OperationRetrySettings
  type: Class
  syntax: *o1
