items:
- uid: microsoft.servicefabric.actors._actor_service_settings
  id: _actor_service_settings
  parent: microsoft.servicefabric.actors
  children:
  - microsoft.servicefabric.actors._actor_service_settings.actorConcurrencySettings()
  - microsoft.servicefabric.actors._actor_service_settings.actorGarbageCollectionSettings()
  - microsoft.servicefabric.actors._actor_service_settings.ActorServiceSettings()
  - microsoft.servicefabric.actors._actor_service_settings.withActorConcurrencySettings(ActorConcurrencySettings)
  - microsoft.servicefabric.actors._actor_service_settings.withActorGarbageCollectionSettings(ActorGarbageCollectionSettings)
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  langs:
  - java
  name: ActorServiceSettings
  fullName: microsoft.servicefabric.actors.ActorServiceSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
    startLine: 5
  package: microsoft.servicefabric.actors
  summary: <p>Settings to configures behavior of <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
  syntax: &o1
    content: public class ActorServiceSettings
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - microsoft.servicefabric.actors._actor_service_settings.ActorServiceSettings(ActorServiceSettings)
- uid: microsoft.servicefabric.actors._actor_service_settings.actorConcurrencySettings()
  id: actorConcurrencySettings()
  parent: microsoft.servicefabric.actors._actor_service_settings
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  langs:
  - java
  name: actorConcurrencySettings()
  fullName: ActorConcurrencySettings microsoft.servicefabric.actors.ActorServiceSettings.actorConcurrencySettings()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
    startLine: 34
  package: microsoft.servicefabric.actors
  summary: >-
    <p>Gets settings to configure the turn based concurrency lock for actors.</p>

    <p></p>
  syntax:
    content: public ActorConcurrencySettings actorConcurrencySettings()
    return:
      type: microsoft.servicefabric.actors._actor_concurrency_settings
      description: >-
        <p>

          <xref href="microsoft.servicefabric.actors._actor_concurrency_settings" data-throw-if-not-resolved="false"></xref> for the <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
- uid: microsoft.servicefabric.actors._actor_service_settings.actorGarbageCollectionSettings()
  id: actorGarbageCollectionSettings()
  parent: microsoft.servicefabric.actors._actor_service_settings
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  langs:
  - java
  name: actorGarbageCollectionSettings()
  fullName: ActorGarbageCollectionSettings microsoft.servicefabric.actors.ActorServiceSettings.actorGarbageCollectionSettings()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
    startLine: 25
  package: microsoft.servicefabric.actors
  summary: >-
    <p>Gets settings to configure the turn based Garbage Collection settings for actors.</p>

    <p></p>
  syntax:
    content: public ActorGarbageCollectionSettings actorGarbageCollectionSettings()
    return:
      type: microsoft.servicefabric.actors._actor_garbage_collection_settings
      description: >-
        <p>

          <xref href="microsoft.servicefabric.actors._actor_garbage_collection_settings" data-throw-if-not-resolved="false"></xref> for the <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
- uid: microsoft.servicefabric.actors._actor_service_settings.ActorServiceSettings()
  id: ActorServiceSettings()
  parent: microsoft.servicefabric.actors._actor_service_settings
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  langs:
  - java
  name: ActorServiceSettings()
  fullName: microsoft.servicefabric.actors.ActorServiceSettings.ActorServiceSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
    startLine: 13
  package: microsoft.servicefabric.actors
  summary: <p>Initializes a new instance of the <xref href="microsoft.servicefabric.actors._actor_service_settings" data-throw-if-not-resolved="false"></xref> class. </p>
  syntax:
    content: public ActorServiceSettings()
- uid: microsoft.servicefabric.actors._actor_service_settings.withActorConcurrencySettings(ActorConcurrencySettings)
  id: withActorConcurrencySettings(ActorConcurrencySettings)
  parent: microsoft.servicefabric.actors._actor_service_settings
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  langs:
  - java
  name: withActorConcurrencySettings(ActorConcurrencySettings concurrencySettings)
  fullName: ActorServiceSettings microsoft.servicefabric.actors.ActorServiceSettings.withActorConcurrencySettings(ActorConcurrencySettings concurrencySettings)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
    startLine: 60
  package: microsoft.servicefabric.actors
  summary: >-
    <p>Sets and Gets settings to configure the turn based concurrency lock for actors.</p>

    <p></p>
  syntax:
    content: public ActorServiceSettings withActorConcurrencySettings(ActorConcurrencySettings concurrencySettings)
    parameters:
    - id: concurrencySettings
      type: microsoft.servicefabric.actors._actor_concurrency_settings
      description: >-
        <p>

          <xref href="microsoft.servicefabric.actors._actor_concurrency_settings" data-throw-if-not-resolved="false"></xref>

        </p>
    return:
      type: microsoft.servicefabric.actors._actor_service_settings
      description: >-
        <p>

          <xref href="microsoft.servicefabric.actors._actor_service_settings" data-throw-if-not-resolved="false"></xref> for the <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
- uid: microsoft.servicefabric.actors._actor_service_settings.withActorGarbageCollectionSettings(ActorGarbageCollectionSettings)
  id: withActorGarbageCollectionSettings(ActorGarbageCollectionSettings)
  parent: microsoft.servicefabric.actors._actor_service_settings
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  langs:
  - java
  name: withActorGarbageCollectionSettings(ActorGarbageCollectionSettings gcsettings)
  fullName: ActorServiceSettings microsoft.servicefabric.actors.ActorServiceSettings.withActorGarbageCollectionSettings(ActorGarbageCollectionSettings gcsettings)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorServiceSettings.java
    startLine: 45
  package: microsoft.servicefabric.actors
  summary: >-
    <p>Sets and Gets settings to configure the turn based concurrency lock for actors.</p>

    <p></p>
  syntax:
    content: public ActorServiceSettings withActorGarbageCollectionSettings(ActorGarbageCollectionSettings gcsettings)
    parameters:
    - id: gcsettings
      type: microsoft.servicefabric.actors._actor_garbage_collection_settings
      description: >-
        <p>

          <xref href="microsoft.servicefabric.actors._actor_garbage_collection_settings" data-throw-if-not-resolved="false"></xref>

        </p>
    return:
      type: microsoft.servicefabric.actors._actor_service_settings
      description: >-
        <p>

          <xref href="microsoft.servicefabric.actors._actor_service_settings" data-throw-if-not-resolved="false"></xref> for the <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
references:
- uid: microsoft.servicefabric.actors._actor_service_settings.ActorServiceSettings(ActorServiceSettings)
- uid: microsoft.servicefabric.actors._actor_concurrency_settings
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor_concurrency_settings.yml
  name: ActorConcurrencySettings
  fullName: microsoft.servicefabric.actors.ActorConcurrencySettings
  type: Class
  summary: <p>The method calls on an actor dispatched via in turn with support for logical call context based reentrancy. This class provides the settings to configure the turn based concurrency lock for actors. </p>
  syntax:
    content: public class ActorConcurrencySettings
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  name: ActorGarbageCollectionSettings
  fullName: microsoft.servicefabric.actors.ActorGarbageCollectionSettings
  type: Class
  summary: <p>Settings to configures Garbage Collection behavior of <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
  syntax:
    content: public class ActorGarbageCollectionSettings
- uid: microsoft.servicefabric.actors._actor_service_settings
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor_service_settings.yml
  name: ActorServiceSettings
  fullName: microsoft.servicefabric.actors.ActorServiceSettings
  type: Class
  summary: <p>Settings to configures behavior of <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
  syntax: *o1
- uid: microsoft.servicefabric.actors._actor
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor.yml
  name: Actor
  fullName: microsoft.servicefabric.actors.Actor
  type: Interface
  summary: <p>Base interface for inheriting reliable actor interfaces. </p>
  syntax:
    content: public interface Actor
