items:
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings_annotation
  id: _service_remoting_settings_annotation
  parent: microsoft.servicefabric.services.remoting
  children:
  - microsoft.servicefabric.services.remoting._service_remoting_settings_annotation.maxMessageSize()
  href: microsoft.servicefabric.services.remoting._service_remoting_settings_annotation.yml
  langs:
  - java
  name: ServiceRemotingSettingsAnnotation
  fullName: microsoft.servicefabric.services.remoting.ServiceRemotingSettingsAnnotation
  type: Interface
  source:
    remote: &o0
      path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettingsAnnotation.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettingsAnnotation.java
    startLine: 9
  package: microsoft.servicefabric.services.remoting
  syntax:
    content: public interface ServiceRemotingSettingsAnnotation
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings_annotation.maxMessageSize()
  id: maxMessageSize()
  parent: microsoft.servicefabric.services.remoting._service_remoting_settings_annotation
  href: microsoft.servicefabric.services.remoting._service_remoting_settings_annotation.yml
  langs:
  - java
  name: maxMessageSize()
  fullName: int microsoft.servicefabric.services.remoting.ServiceRemotingSettingsAnnotation.maxMessageSize()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettingsAnnotation.java
    startLine: 11
  package: microsoft.servicefabric.services.remoting
  syntax:
    content: public int maxMessageSize()
    return:
      type: f75371fa
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
