items:
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings
  id: _service_remoting_settings
  parent: microsoft.servicefabric.services.remoting
  children:
  - microsoft.servicefabric.services.remoting._service_remoting_settings.get(Package)
  - microsoft.servicefabric.services.remoting._service_remoting_settings.getMaxMessageSize()
  - microsoft.servicefabric.services.remoting._service_remoting_settings.ServiceRemotingSettings()
  - microsoft.servicefabric.services.remoting._service_remoting_settings.setMaxMessageSize(int)
  href: microsoft.servicefabric.services.remoting._service_remoting_settings.yml
  langs:
  - java
  name: ServiceRemotingSettings
  fullName: microsoft.servicefabric.services.remoting.ServiceRemotingSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettings.java
    startLine: 2
  package: microsoft.servicefabric.services.remoting
  syntax: &o1
    content: public class ServiceRemotingSettings
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - microsoft.servicefabric.services.remoting._service_remoting_settings.DefaultMaxReceivedMessageSize()
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings.get(Package)
  id: get(Package)
  parent: microsoft.servicefabric.services.remoting._service_remoting_settings
  href: microsoft.servicefabric.services.remoting._service_remoting_settings.yml
  langs:
  - java
  name: get(Package p)
  fullName: static ServiceRemotingSettings microsoft.servicefabric.services.remoting.ServiceRemotingSettings.get(Package p)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettings.java
    startLine: 20
  package: microsoft.servicefabric.services.remoting
  syntax:
    content: public static ServiceRemotingSettings get(Package p)
    parameters:
    - id: p
      type: fb029820
    return:
      type: microsoft.servicefabric.services.remoting._service_remoting_settings
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings.getMaxMessageSize()
  id: getMaxMessageSize()
  parent: microsoft.servicefabric.services.remoting._service_remoting_settings
  href: microsoft.servicefabric.services.remoting._service_remoting_settings.yml
  langs:
  - java
  name: getMaxMessageSize()
  fullName: int microsoft.servicefabric.services.remoting.ServiceRemotingSettings.getMaxMessageSize()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettings.java
    startLine: 8
  package: microsoft.servicefabric.services.remoting
  syntax:
    content: public int getMaxMessageSize()
    return:
      type: f75371fa
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings.ServiceRemotingSettings()
  id: ServiceRemotingSettings()
  parent: microsoft.servicefabric.services.remoting._service_remoting_settings
  href: microsoft.servicefabric.services.remoting._service_remoting_settings.yml
  langs:
  - java
  name: ServiceRemotingSettings()
  fullName: microsoft.servicefabric.services.remoting.ServiceRemotingSettings.ServiceRemotingSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettings.java
    startLine: 16
  package: microsoft.servicefabric.services.remoting
  syntax:
    content: public ServiceRemotingSettings()
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings.setMaxMessageSize(int)
  id: setMaxMessageSize(int)
  parent: microsoft.servicefabric.services.remoting._service_remoting_settings
  href: microsoft.servicefabric.services.remoting._service_remoting_settings.yml
  langs:
  - java
  name: setMaxMessageSize(int maxMessageSize)
  fullName: void microsoft.servicefabric.services.remoting.ServiceRemotingSettings.setMaxMessageSize(int maxMessageSize)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.services/src/microsoft/servicefabric/services/remoting/ServiceRemotingSettings.java
    startLine: 12
  package: microsoft.servicefabric.services.remoting
  syntax:
    content: public void setMaxMessageSize(int maxMessageSize)
    parameters:
    - id: maxMessageSize
      type: f75371fa
references:
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: fb029820
  spec.java:
  - name: Package
    fullName: Package
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings.DefaultMaxReceivedMessageSize()
- uid: microsoft.servicefabric.services.remoting._service_remoting_settings
  parent: microsoft.servicefabric.services.remoting
  href: microsoft.servicefabric.services.remoting._service_remoting_settings.yml
  name: ServiceRemotingSettings
  fullName: microsoft.servicefabric.services.remoting.ServiceRemotingSettings
  type: Class
  syntax: *o1
