items:
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings
  id: _actor_garbage_collection_settings
  parent: microsoft.servicefabric.actors
  children:
  - microsoft.servicefabric.actors._actor_garbage_collection_settings.ActorGarbageCollectionSettings()
  - microsoft.servicefabric.actors._actor_garbage_collection_settings.ActorGarbageCollectionSettings(long,long)
  - microsoft.servicefabric.actors._actor_garbage_collection_settings.idleTimeoutInSeconds()
  - microsoft.servicefabric.actors._actor_garbage_collection_settings.scanIntervalInSeconds()
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  langs:
  - java
  name: ActorGarbageCollectionSettings
  fullName: microsoft.servicefabric.actors.ActorGarbageCollectionSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorGarbageCollectionSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorGarbageCollectionSettings.java
    startLine: 5
  package: microsoft.servicefabric.actors
  summary: <p>Settings to configures Garbage Collection behavior of <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
  syntax: &o1
    content: public class ActorGarbageCollectionSettings
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - microsoft.servicefabric.actors._actor_garbage_collection_settings.ActorGarbageCollectionSettings(ActorGarbageCollectionSettings)
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings.ActorGarbageCollectionSettings()
  id: ActorGarbageCollectionSettings()
  parent: microsoft.servicefabric.actors._actor_garbage_collection_settings
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  langs:
  - java
  name: ActorGarbageCollectionSettings()
  fullName: microsoft.servicefabric.actors.ActorGarbageCollectionSettings.ActorGarbageCollectionSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorGarbageCollectionSettings.java
    startLine: 13
  package: microsoft.servicefabric.actors
  summary: <p>Initializes a new instance of the <xref href="microsoft.servicefabric.actors._actor_garbage_collection_settings" data-throw-if-not-resolved="false"></xref> class. </p>
  syntax:
    content: public ActorGarbageCollectionSettings()
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings.ActorGarbageCollectionSettings(long,long)
  id: ActorGarbageCollectionSettings(long,long)
  parent: microsoft.servicefabric.actors._actor_garbage_collection_settings
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  langs:
  - java
  name: ActorGarbageCollectionSettings(long idleTimeoutInSeconds, long scanIntervalInSeconds)
  fullName: microsoft.servicefabric.actors.ActorGarbageCollectionSettings.ActorGarbageCollectionSettings(long idleTimeoutInSeconds, long scanIntervalInSeconds)
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorGarbageCollectionSettings.java
    startLine: 33
  package: microsoft.servicefabric.actors
  summary: <p>Initializes a new instance of the <xref href="microsoft.servicefabric.actors._actor_garbage_collection_settings" data-throw-if-not-resolved="false"></xref> class. </p>
  syntax:
    content: public ActorGarbageCollectionSettings(long idleTimeoutInSeconds, long scanIntervalInSeconds)
    parameters:
    - id: idleTimeoutInSeconds
      type: 0364520f
      description: <p>Time interval to wait before garbage collecting an actor which is not in use. </p>
    - id: scanIntervalInSeconds
      type: 0364520f
      description: <p>Time interval to run <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Garbage Collection scan. </p>
  exceptions:
  - type: 6bd89211
    description: <p>When idleTimeoutInSeconds is less than or equal to 0. When scanIntervalInSeconds is less than or equal to 0. When idleTimeoutInSeconds is less than scanIntervalInSeconds. </p>
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings.idleTimeoutInSeconds()
  id: idleTimeoutInSeconds()
  parent: microsoft.servicefabric.actors._actor_garbage_collection_settings
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  langs:
  - java
  name: idleTimeoutInSeconds()
  fullName: long microsoft.servicefabric.actors.ActorGarbageCollectionSettings.idleTimeoutInSeconds()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorGarbageCollectionSettings.java
    startLine: 62
  package: microsoft.servicefabric.actors
  summary: <p>Gets time interval to wait before garbage collecting an actor which is not in use. </p>
  syntax:
    content: public long idleTimeoutInSeconds()
    return:
      type: 0364520f
      description: <p>Time interval in Long to wait before garbage collecting an actor which is not in use. </p>
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings.scanIntervalInSeconds()
  id: scanIntervalInSeconds()
  parent: microsoft.servicefabric.actors._actor_garbage_collection_settings
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  langs:
  - java
  name: scanIntervalInSeconds()
  fullName: long microsoft.servicefabric.actors.ActorGarbageCollectionSettings.scanIntervalInSeconds()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ActorGarbageCollectionSettings.java
    startLine: 54
  package: microsoft.servicefabric.actors
  summary: <p>Gets time interval to run <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Garbage Collection scan. </p>
  syntax:
    content: public long scanIntervalInSeconds()
    return:
      type: 0364520f
      description: <p>Time interval in Long to run <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Garbage Collection scan. </p>
references:
- uid: 6bd89211
  spec.java:
  - name: java.lang.IllegalArgumentException
    fullName: java.lang.IllegalArgumentException
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings.ActorGarbageCollectionSettings(ActorGarbageCollectionSettings)
- uid: microsoft.servicefabric.actors._actor_garbage_collection_settings
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor_garbage_collection_settings.yml
  name: ActorGarbageCollectionSettings
  fullName: microsoft.servicefabric.actors.ActorGarbageCollectionSettings
  type: Class
  summary: <p>Settings to configures Garbage Collection behavior of <xref href="microsoft.servicefabric.actors._actor" data-throw-if-not-resolved="false"></xref> Service. </p>
  syntax: *o1
- uid: microsoft.servicefabric.actors._actor
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor.yml
  name: Actor
  fullName: microsoft.servicefabric.actors.Actor
  type: Interface
  summary: <p>Base interface for inheriting reliable actor interfaces. </p>
  syntax:
    content: public interface Actor
