items:
- uid: replicator_settings._replicator_settings
  id: _replicator_settings
  parent: replicator_settings
  children:
  - replicator_settings._replicator_settings.main(String[])
  href: replicator_settings._replicator_settings.yml
  langs:
  - java
  name: ReplicatorSettings
  fullName: replicatorSettings.ReplicatorSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/sample/ManagedAPIs/ReplicatorSettings/src/replicatorSettings/ReplicatorSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/sample/ManagedAPIs/ReplicatorSettings/src/replicatorSettings/ReplicatorSettings.java
    startLine: 11
  package: replicator_settings
  syntax:
    content: public class ReplicatorSettings
  inheritance:
  - java.lang.Object
- uid: replicator_settings._replicator_settings.main(String[])
  id: main(String[])
  parent: replicator_settings._replicator_settings
  href: replicator_settings._replicator_settings.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void replicatorSettings.ReplicatorSettings.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/sample/ManagedAPIs/ReplicatorSettings/src/replicatorSettings/ReplicatorSettings.java
    startLine: 15
  package: replicator_settings
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
