items:
- uid: replicator_settings
  id: replicator_settings
  children:
  - replicator_settings._replicator_settings
  - replicator_settings._settings_replica
  href: replicator_settings.yml
  langs:
  - java
  name: replicatorSettings
  fullName: replicatorSettings
  type: Namespace
  source:
    remote:
      path: src/prod/src/java/sample/ManagedAPIs/ReplicatorSettings/src/replicatorSettings/ReplicatorSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/sample/ManagedAPIs/ReplicatorSettings/src/replicatorSettings/ReplicatorSettings.java
  syntax:
    content: namespace replicatorSettings
references:
- uid: replicator_settings._replicator_settings
  parent: replicator_settings
  href: replicator_settings._replicator_settings.yml
  name: ReplicatorSettings
  fullName: replicatorSettings.ReplicatorSettings
  type: Class
  syntax:
    content: public class ReplicatorSettings
- uid: replicator_settings._settings_replica
  parent: replicator_settings
  href: replicator_settings._settings_replica.yml
  name: SettingsReplica
  fullName: replicatorSettings.SettingsReplica
  type: Class
  syntax:
    content: public class SettingsReplica extends KeyValueStoreReplica
