items:
- uid: system.fabric.health._deployed_application_health_state
  id: _deployed_application_health_state
  parent: system.fabric.health
  children:
  - system.fabric.health._deployed_application_health_state.getApplicationName()
  - system.fabric.health._deployed_application_health_state.getNodeName()
  href: system.fabric.health._deployed_application_health_state.yml
  langs:
  - java
  name: DeployedApplicationHealthState
  fullName: system.fabric.health.DeployedApplicationHealthState
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/health/DeployedApplicationHealthState.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/health/DeployedApplicationHealthState.java
    startLine: 4
  package: system.fabric.health
  summary: <p>Represents the health state of a deployed application, which contains the entity identifier and the aggregated health state. </p>
  syntax:
    content: public class DeployedApplicationHealthState extends EntityHealthState
  inheritance:
  - java.lang.Object
  - system.fabric.health._entity_health_state
  inheritedMembers:
  - system.fabric.health._deployed_application_health_state.DeployedApplicationHealthState(String,String,int)
  - system.fabric.health._entity_health_state.EntityHealthState(HealthState)
  - system.fabric.health._entity_health_state.getAggregatedHealthState()
- uid: system.fabric.health._deployed_application_health_state.getApplicationName()
  id: getApplicationName()
  parent: system.fabric.health._deployed_application_health_state
  href: system.fabric.health._deployed_application_health_state.yml
  langs:
  - java
  name: getApplicationName()
  fullName: URI system.fabric.health.DeployedApplicationHealthState.getApplicationName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/health/DeployedApplicationHealthState.java
    startLine: 18
  package: system.fabric.health
  summary: <p>Get deployed application name. </p>
  syntax:
    content: public URI getApplicationName()
    return:
      type: "62304784"
      description: <p>The <ref refid="" kindref="compound">java.net.URI</ref> of deployed application </p>
- uid: system.fabric.health._deployed_application_health_state.getNodeName()
  id: getNodeName()
  parent: system.fabric.health._deployed_application_health_state
  href: system.fabric.health._deployed_application_health_state.yml
  langs:
  - java
  name: getNodeName()
  fullName: String system.fabric.health.DeployedApplicationHealthState.getNodeName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/health/DeployedApplicationHealthState.java
    startLine: 24
  package: system.fabric.health
  summary: <p>Gets the node name of the deployed application. </p>
  syntax:
    content: public String getNodeName()
    return:
      type: "26831127"
      description: <p>The <ref refid="" kindref="compound">java.lang.String</ref> representing the node name. </p>
references:
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric.health._deployed_application_health_state.DeployedApplicationHealthState(String,String,int)
- uid: system.fabric.health._entity_health_state.EntityHealthState(HealthState)
  parent: system.fabric.health._entity_health_state
  href: system.fabric.health._entity_health_state.yml
  name: EntityHealthState(HealthState aggregatedHealthState)
  fullName: system.fabric.health.EntityHealthState.EntityHealthState(HealthState aggregatedHealthState)
  type: Constructor
  syntax:
    content: protected EntityHealthState(HealthState aggregatedHealthState)
    parameters:
    - id: aggregatedHealthState
      type: system.fabric.health._health_state
- uid: system.fabric.health._entity_health_state.getAggregatedHealthState()
  parent: system.fabric.health._entity_health_state
  href: system.fabric.health._entity_health_state.yml
  name: getAggregatedHealthState()
  fullName: HealthState system.fabric.health.EntityHealthState.getAggregatedHealthState()
  type: Method
  summary: <p>Gets the aggregated health state computed by Health Manager based on all reported events and the desired policy. </p>
  syntax:
    content: public HealthState getAggregatedHealthState()
    return:
      type: system.fabric.health._health_state
      description: <p>The aggregated health state computed by Health Manager. </p>
- uid: system.fabric.health._entity_health_state
  parent: system.fabric.health
  href: system.fabric.health._entity_health_state.yml
  name: EntityHealthState
  fullName: system.fabric.health.EntityHealthState
  type: Class
  summary: >-
    <p>Represents the base class for all entity health state classes. </p>

    <p>

      <bold>Remarks:</bold>An entity health state contains entity identifier and entity aggregated health state.</p>
  syntax:
    content: public class EntityHealthState
