items:
- uid: system.fabric._configuration_package
  id: _configuration_package
  parent: system.fabric
  children:
  - system.fabric._configuration_package.ConfigurationPackage(ConfigurationPackageDescription,String,ConfigurationSettings)
  - system.fabric._configuration_package.getDescription()
  - system.fabric._configuration_package.getPath()
  - system.fabric._configuration_package.getSettings()
  href: system.fabric._configuration_package.yml
  langs:
  - java
  name: ConfigurationPackage
  fullName: system.fabric.ConfigurationPackage
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackage.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackage.java
    startLine: 2
  package: system.fabric
  summary: <p>Represents a configuration package. </p>
  syntax:
    content: public class ConfigurationPackage
  inheritance:
  - java.lang.Object
- uid: system.fabric._configuration_package.ConfigurationPackage(ConfigurationPackageDescription,String,ConfigurationSettings)
  id: ConfigurationPackage(ConfigurationPackageDescription,String,ConfigurationSettings)
  parent: system.fabric._configuration_package
  href: system.fabric._configuration_package.yml
  langs:
  - java
  name: ConfigurationPackage(ConfigurationPackageDescription description, String path, ConfigurationSettings settings)
  fullName: system.fabric.ConfigurationPackage.ConfigurationPackage(ConfigurationPackageDescription description, String path, ConfigurationSettings settings)
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackage.java
    startLine: 8
  package: system.fabric
  syntax:
    content: public ConfigurationPackage(ConfigurationPackageDescription description, String path, ConfigurationSettings settings)
    parameters:
    - id: description
      type: system.fabric._configuration_package_description
    - id: path
      type: "26831127"
    - id: settings
      type: system.fabric._configuration_settings
- uid: system.fabric._configuration_package.getDescription()
  id: getDescription()
  parent: system.fabric._configuration_package
  href: system.fabric._configuration_package.yml
  langs:
  - java
  name: getDescription()
  fullName: ConfigurationPackageDescription system.fabric.ConfigurationPackage.getDescription()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackage.java
    startLine: 19
  package: system.fabric
  summary: <p>Gets the <xref href="system.fabric._configuration_package_description" data-throw-if-not-resolved="false"></xref> associated with the <ref refid="" kindref="compound">system.fabric.ConfigurationPackage</ref></p>
  syntax:
    content: public ConfigurationPackageDescription getDescription()
    return:
      type: system.fabric._configuration_package_description
      description: <p>the <xref href="system.fabric._configuration_package_description" data-throw-if-not-resolved="false"></xref> associated with the <ref refid="" kindref="compound">system.fabric.ConfigurationPackage</ref></p>
- uid: system.fabric._configuration_package.getPath()
  id: getPath()
  parent: system.fabric._configuration_package
  href: system.fabric._configuration_package.yml
  langs:
  - java
  name: getPath()
  fullName: String system.fabric.ConfigurationPackage.getPath()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackage.java
    startLine: 26
  package: system.fabric
  summary: <p>Gets the local path for the <ref refid="" kindref="compound">system.fabric.ConfigurationPackage</ref></p>
  syntax:
    content: public String getPath()
    return:
      type: "26831127"
      description: <p>the local path for the <ref refid="" kindref="compound">system.fabric.ConfigurationPackage</ref></p>
- uid: system.fabric._configuration_package.getSettings()
  id: getSettings()
  parent: system.fabric._configuration_package
  href: system.fabric._configuration_package.yml
  langs:
  - java
  name: getSettings()
  fullName: ConfigurationSettings system.fabric.ConfigurationPackage.getSettings()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackage.java
    startLine: 33
  package: system.fabric
  summary: <p>Gets the <xref href="system.fabric._configuration_settings" data-throw-if-not-resolved="false"></xref> associated with the <ref refid="" kindref="compound">system.fabric.ConfigurationPackage</ref></p>
  syntax:
    content: public ConfigurationSettings getSettings()
    return:
      type: system.fabric._configuration_settings
      description: <p>the <xref href="system.fabric._configuration_settings" data-throw-if-not-resolved="false"></xref> associated with the <ref refid="" kindref="compound">system.fabric.ConfigurationPackage</ref></p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric._configuration_package_description
  parent: system.fabric
  href: system.fabric._configuration_package_description.yml
  name: ConfigurationPackageDescription
  fullName: system.fabric.ConfigurationPackageDescription
  type: Class
  summary: <p>Describes a configuration package. </p>
  syntax:
    content: public class ConfigurationPackageDescription
- uid: system.fabric._configuration_settings
  parent: system.fabric
  href: system.fabric._configuration_settings.yml
  name: ConfigurationSettings
  fullName: system.fabric.ConfigurationSettings
  type: Class
  syntax:
    content: public class ConfigurationSettings
