items:
- uid: system.fabric._application_health_state_filter
  id: _application_health_state_filter
  parent: system.fabric
  children:
  - system.fabric._application_health_state_filter.ApplicationHealthStateFilter()
  - system.fabric._application_health_state_filter.getApplicationNameFilter()
  - system.fabric._application_health_state_filter.getApplicationTypeNameFilter()
  - system.fabric._application_health_state_filter.getDeployedApplicationFilters()
  - system.fabric._application_health_state_filter.getHealthStateFilter()
  - system.fabric._application_health_state_filter.getServiceFilters()
  - system.fabric._application_health_state_filter.setApplicationNameFilter(URI)
  - system.fabric._application_health_state_filter.setApplicationTypeNameFilter(String)
  - system.fabric._application_health_state_filter.setHealthStateFilter(HealthStateFilter)
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: ApplicationHealthStateFilter
  fullName: system.fabric.ApplicationHealthStateFilter
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 18
  package: system.fabric
  summary: >-
    <p>Filter for <xref href="system.fabric.health._application_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The entity health state chunk queries can specify a list of application filters to fine-grain select the applications that should be included in the query result. Note that all the applications are used to evaluate cluster aggregated health state, regardless of the filter passed in. </p>
  syntax: &o1
    content: public class ApplicationHealthStateFilter
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._application_health_state_filter.toNative(PinCollection)
  - system.fabric._application_health_state_filter.toNativeList(PinCollection,List<ApplicationHealthStateFilter>)
- uid: system.fabric._application_health_state_filter.ApplicationHealthStateFilter()
  id: ApplicationHealthStateFilter()
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: ApplicationHealthStateFilter()
  fullName: system.fabric.ApplicationHealthStateFilter.ApplicationHealthStateFilter()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 38
  package: system.fabric
  syntax:
    content: public ApplicationHealthStateFilter()
- uid: system.fabric._application_health_state_filter.getApplicationNameFilter()
  id: getApplicationNameFilter()
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: getApplicationNameFilter()
  fullName: URI system.fabric.ApplicationHealthStateFilter.getApplicationNameFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 93
  package: system.fabric
  summary: >-
    <p>Gets the application name filter.</p>

    <p>

      <bold>Remarks:</bold>If specified, the filter applies only to the desired application. For the application to match the filter, its aggregated health state must match the specified health state filter. </p>
  syntax:
    content: public URI getApplicationNameFilter()
    return:
      type: "62304784"
      description: <p>The application name filter. </p>
- uid: system.fabric._application_health_state_filter.getApplicationTypeNameFilter()
  id: getApplicationTypeNameFilter()
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: getApplicationTypeNameFilter()
  fullName: String system.fabric.ApplicationHealthStateFilter.getApplicationTypeNameFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 123
  package: system.fabric
  summary: >-
    <p>Gets the application type name filter.</p>

    <p>

      <bold>Remarks:</bold>If specified, the filter applies to all applications of specified application type that don't have a more specific filter (for a specific application name). For an application to match the filter, its aggregated health state must match the specified health state filter. </p>
  syntax:
    content: public String getApplicationTypeNameFilter()
    return:
      type: "26831127"
      description: <p>The application type name filter. </p>
- uid: system.fabric._application_health_state_filter.getDeployedApplicationFilters()
  id: getDeployedApplicationFilters()
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: getDeployedApplicationFilters()
  fullName: List<DeployedApplicationHealthStateFilter> system.fabric.ApplicationHealthStateFilter.getDeployedApplicationFilters()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 174
  package: system.fabric
  summary: >-
    <p>Gets the list of <xref href="system.fabric._deployed_application_health_state_filter" data-throw-if-not-resolved="false"></xref> to be applied to the deployed application children health states.</p>

    <p>

      <bold>Remarks:</bold>The list can contain one default deployed application filter or deployed application filters for specific deployed applications to fine-grain entities returned by the query. All deployed application children that match the filter will be returned as children of the application. If empty, the children are not returned by default. </p>
  syntax:
    content: public List<DeployedApplicationHealthStateFilter> getDeployedApplicationFilters()
    return:
      type: 5618da2dsystem.fabric._deployed_application_health_state_filtera08ddfce
      description: <p>The list of <xref href="system.fabric._deployed_application_health_state_filter" data-throw-if-not-resolved="false"></xref> to be applied to the deployed application children health states. </p>
- uid: system.fabric._application_health_state_filter.getHealthStateFilter()
  id: getHealthStateFilter()
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: getHealthStateFilter()
  fullName: HealthStateFilter system.fabric.ApplicationHealthStateFilter.getHealthStateFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 59
  package: system.fabric
  summary: >-
    <p>Gets filter for the aggregated health state of the <xref href="system.fabric.health._application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection.</p>

    <p>

      <bold>Remarks:</bold>The health state filter value comes from members or bitwise combination of members of <ref refid="" kindref="compound">HealthStateFilter</ref>. For an application to match the filter, its aggregated health state must match the specified health state filter. If the health state filter is Default, the health state filter defaults to None if there are no specific filters (application name or application type name). Otherwise, the Default filter is considered to apply to All. </p>
  syntax:
    content: public HealthStateFilter getHealthStateFilter()
    return:
      type: system.fabric.health._health_state_filter
      description: <p>The filter for the aggregated health state of the <xref href="system.fabric.health._application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection. </p>
- uid: system.fabric._application_health_state_filter.getServiceFilters()
  id: getServiceFilters()
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: getServiceFilters()
  fullName: List<ServiceHealthStateFilter> system.fabric.ApplicationHealthStateFilter.getServiceFilters()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 156
  package: system.fabric
  summary: >-
    <p>Gets the list of <xref href="system.fabric._service_health_state_filter" data-throw-if-not-resolved="false"></xref> to be applied to the service children health states.</p>

    <p>

      <bold>Remarks:</bold>The list can contain one default service filter or service filters for specific services to fine-grain entities returned by the query. All service children that match the filter will be returned as children of the application. If empty, the children are not returned by default. </p>
  syntax:
    content: public List<ServiceHealthStateFilter> getServiceFilters()
    return:
      type: 5618da2dsystem.fabric._service_health_state_filtera08ddfce
      description: <p>The list of <xref href="system.fabric._service_health_state_filter" data-throw-if-not-resolved="false"></xref> to be applied to the service children health states. </p>
- uid: system.fabric._application_health_state_filter.setApplicationNameFilter(URI)
  id: setApplicationNameFilter(URI)
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: setApplicationNameFilter(URI applicationNameFilter)
  fullName: void system.fabric.ApplicationHealthStateFilter.setApplicationNameFilter(URI applicationNameFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 108
  package: system.fabric
  summary: >-
    <p>Sets the application name filter.</p>

    <p>

      <bold>Remarks:</bold>If specified, the filter applies only to the desired application. For the application to match the filter, its aggregated health state must match the specified health state filter. </p>
  syntax:
    content: public void setApplicationNameFilter(URI applicationNameFilter)
    parameters:
    - id: applicationNameFilter
      type: "62304784"
      description: <p>The application name filter. </p>
- uid: system.fabric._application_health_state_filter.setApplicationTypeNameFilter(String)
  id: setApplicationTypeNameFilter(String)
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: setApplicationTypeNameFilter(String applicationTypeNameFilter)
  fullName: void system.fabric.ApplicationHealthStateFilter.setApplicationTypeNameFilter(String applicationTypeNameFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 139
  package: system.fabric
  summary: >-
    <p>Sets the application type name filter.</p>

    <p>

      <bold>Remarks:</bold>If specified, the filter applies to all applications of specified application type that don't have a more specific filter (for a specific application name). For an application to match the filter, its aggregated health state must match the specified health state filter. </p>
  syntax:
    content: public void setApplicationTypeNameFilter(String applicationTypeNameFilter)
    parameters:
    - id: applicationTypeNameFilter
      type: "26831127"
      description: <p>The application type name filter. </p>
- uid: system.fabric._application_health_state_filter.setHealthStateFilter(HealthStateFilter)
  id: setHealthStateFilter(HealthStateFilter)
  parent: system.fabric._application_health_state_filter
  href: system.fabric._application_health_state_filter.yml
  langs:
  - java
  name: setHealthStateFilter(HealthStateFilter healthStateFilter)
  fullName: void system.fabric.ApplicationHealthStateFilter.setHealthStateFilter(HealthStateFilter healthStateFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ApplicationHealthStateFilter.java
    startLine: 79
  package: system.fabric
  summary: >-
    <p>Sets filter for the aggregated health state of the <xref href="system.fabric.health._application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection.</p>

    <p>

      <bold>Remarks:</bold>The health state filter value comes from members or bitwise combination of members of <ref refid="" kindref="compound">HealthStateFilter</ref>. For an application to match the filter, its aggregated health state must match the specified health state filter. If the health state filter is Default, the health state filter defaults to None if there are no specific filters (application name or application type name). Otherwise, the Default filter is considered to apply to All. </p>
  syntax:
    content: public void setHealthStateFilter(HealthStateFilter healthStateFilter)
    parameters:
    - id: healthStateFilter
      type: system.fabric.health._health_state_filter
      description: <p>The filter for the aggregated health state of the <xref href="system.fabric.health._application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection. </p>
references:
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 5618da2dsystem.fabric._service_health_state_filtera08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: system.fabric._service_health_state_filter
    name: ServiceHealthStateFilter
    fullName: system.fabric.ServiceHealthStateFilter
    href: system.fabric._service_health_state_filter.yml
  - name: '>'
    fullName: '>'
- uid: 5618da2dsystem.fabric._deployed_application_health_state_filtera08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: system.fabric._deployed_application_health_state_filter
    name: DeployedApplicationHealthStateFilter
    fullName: system.fabric.DeployedApplicationHealthStateFilter
    href: system.fabric._deployed_application_health_state_filter.yml
  - name: '>'
    fullName: '>'
- uid: system.fabric._application_health_state_filter.toNative(PinCollection)
- uid: system.fabric._application_health_state_filter.toNativeList(PinCollection,List<ApplicationHealthStateFilter>)
- uid: system.fabric._deployed_application_health_state_filter
  parent: system.fabric
  href: system.fabric._deployed_application_health_state_filter.yml
  name: DeployedApplicationHealthStateFilter
  fullName: system.fabric.DeployedApplicationHealthStateFilter
  type: Class
  summary: >-
    <p>Filter for <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The health state chunk queries can specify a list of deployed application filters to fine-grain select the deployed applications that should be included in the query result. Note that all the deployed applications are used to evaluate parents' aggregated health state, regardless of the filter passed in. </p>
  syntax:
    content: public class DeployedApplicationHealthStateFilter
- uid: system.fabric._service_health_state_filter
  parent: system.fabric
  href: system.fabric._service_health_state_filter.yml
  name: ServiceHealthStateFilter
  fullName: system.fabric.ServiceHealthStateFilter
  type: Class
  summary: >-
    <p>Filter for <xref href="system.fabric.health._service_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The entity health state chunk queries can specify a list of service filters to fine-grain select the services that should be included in the query result. Note that all the services are used to evaluate parents aggregated health state, regardless of the filter passed in. </p>
  syntax:
    content: public class ServiceHealthStateFilter
- uid: system.fabric.health._health_state_filter
  parent: system.fabric.health
  href: system.fabric.health._health_state_filter.yml
  name: HealthStateFilter
  fullName: system.fabric.health.HealthStateFilter
  type: Enum
  syntax:
    content: public enum HealthStateFilter
- uid: system.fabric.health._application_health_state
  parent: system.fabric.health
  href: system.fabric.health._application_health_state.yml
  name: ApplicationHealthState
  fullName: system.fabric.health.ApplicationHealthState
  type: Class
  summary: <p>Represents the health state of an application, which contains the application identifier and the aggregated health state. </p>
  syntax:
    content: public class ApplicationHealthState extends EntityHealthState
- uid: system.fabric._pin_collection
  parent: system.fabric
  href: system.fabric._pin_collection.yml
  name: PinCollection
  fullName: system.fabric.PinCollection
  type: Class
  syntax:
    content: public class PinCollection
- uid: system.fabric._application_health_state_filter
  parent: system.fabric
  href: system.fabric._application_health_state_filter.yml
  name: ApplicationHealthStateFilter
  fullName: system.fabric.ApplicationHealthStateFilter
  type: Class
  summary: >-
    <p>Filter for <xref href="system.fabric.health._application_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The entity health state chunk queries can specify a list of application filters to fine-grain select the applications that should be included in the query result. Note that all the applications are used to evaluate cluster aggregated health state, regardless of the filter passed in. </p>
  syntax: *o1
