items:
- uid: system.fabric.query._application
  id: _application
  parent: system.fabric.query
  children:
  - system.fabric.query._application.Application(String,String,String,int,int,ApplicationParameter[],String,ApplicationParameter[])
  - system.fabric.query._application.getApplicationName()
  - system.fabric.query._application.getApplicationParameterList()
  - system.fabric.query._application.getApplicationStatus()
  - system.fabric.query._application.getApplicationTypeName()
  - system.fabric.query._application.getApplicationTypeVersion()
  - system.fabric.query._application.getHealthState()
  - system.fabric.query._application.getUpgradeParameterList()
  - system.fabric.query._application.getUpgradeTypeVersion()
  - system.fabric.query._application.toString()
  href: system.fabric.query._application.yml
  langs:
  - java
  name: Application
  fullName: system.fabric.query.Application
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 16
  package: system.fabric.query
  summary: >-
    <p>This class contains the details of an <xref href="system.fabric.query._application" data-throw-if-not-resolved="false"></xref>. These details include application-name, type, version, application status, health-state, application-parameter list, upgrade parameter list, upgrade-type version.</p>

    <p></p>
  syntax: &o1
    content: public class Application
  inheritance:
  - java.lang.Object
- uid: system.fabric.query._application.Application(String,String,String,int,int,ApplicationParameter[],String,ApplicationParameter[])
  id: Application(String,String,String,int,int,ApplicationParameter[],String,ApplicationParameter[])
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: Application(String applicationName, String applicationTypeName, String applicationTypeVersion, int applicationStatus, int healthState, ApplicationParameter[] applicationParameterList, String upgradeTypeVersion, ApplicationParameter[] upgradeParameterList)
  fullName: system.fabric.query.Application.Application(String applicationName, String applicationTypeName, String applicationTypeVersion, int applicationStatus, int healthState, ApplicationParameter[] applicationParameterList, String upgradeTypeVersion, ApplicationParameter[] upgradeParameterList)
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 47
  package: system.fabric.query
  summary: >-
    <p>Constructor</p>

    <p></p>
  syntax:
    content: public Application(String applicationName, String applicationTypeName, String applicationTypeVersion, int applicationStatus, int healthState, ApplicationParameter[] applicationParameterList, String upgradeTypeVersion, ApplicationParameter[] upgradeParameterList)
    parameters:
    - id: applicationName
      type: "26831127"
      description: <p>applicationName </p>
    - id: applicationTypeName
      type: "26831127"
      description: <p>applicationTypeName </p>
    - id: applicationTypeVersion
      type: "26831127"
      description: <p>applicationTypeVersion </p>
    - id: applicationStatus
      type: f75371fa
      description: <p>applicationStatus - enum </p>
    - id: healthState
      type: f75371fa
      description: <p>healthState - enum </p>
    - id: applicationParameterList
      type: system.fabric.description._application_parameter397151d7
      description: <p>applicationParameterList </p>
    - id: upgradeTypeVersion
      type: "26831127"
      description: <p>upgradeTypeVersion </p>
    - id: upgradeParameterList
      type: system.fabric.description._application_parameter397151d7
      description: <p>upgradeParameterList </p>
- uid: system.fabric.query._application.getApplicationName()
  id: getApplicationName()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getApplicationName()
  fullName: URI system.fabric.query.Application.getApplicationName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 78
  package: system.fabric.query
  summary: >-
    <p>Gets the name of the application.</p>

    <p></p>
  syntax:
    content: public URI getApplicationName()
    return:
      type: "62304784"
      description: <p>The name of the application. </p>
- uid: system.fabric.query._application.getApplicationParameterList()
  id: getApplicationParameterList()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getApplicationParameterList()
  fullName: ApplicationParameter [] system.fabric.query.Application.getApplicationParameterList()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 118
  package: system.fabric.query
  summary: >-
    <p>Gets the parameters of the application.</p>

    <p></p>
  syntax:
    content: public ApplicationParameter[] getApplicationParameterList()
    return:
      type: system.fabric.description._application_parameter397151d7
      description: <p>The parameters of the application. </p>
- uid: system.fabric.query._application.getApplicationStatus()
  id: getApplicationStatus()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getApplicationStatus()
  fullName: ApplicationStatus system.fabric.query.Application.getApplicationStatus()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 102
  package: system.fabric.query
  summary: >-
    <p>Gets the status of the application.</p>

    <p></p>
  syntax:
    content: public ApplicationStatus getApplicationStatus()
    return:
      type: system.fabric.query._application_status
      description: <p>The status of the application. </p>
- uid: system.fabric.query._application.getApplicationTypeName()
  id: getApplicationTypeName()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getApplicationTypeName()
  fullName: String system.fabric.query.Application.getApplicationTypeName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 86
  package: system.fabric.query
  summary: >-
    <p>Gets the application type name as specified in the <xref href="system.fabric.query._application" data-throw-if-not-resolved="false"></xref> Manifest.</p>

    <p></p>
  syntax:
    content: public String getApplicationTypeName()
    return:
      type: "26831127"
      description: <p>The application type name. </p>
- uid: system.fabric.query._application.getApplicationTypeVersion()
  id: getApplicationTypeVersion()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getApplicationTypeVersion()
  fullName: String system.fabric.query.Application.getApplicationTypeVersion()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 94
  package: system.fabric.query
  summary: >-
    <p>Gets the application type version as specified in the <xref href="system.fabric.query._application" data-throw-if-not-resolved="false"></xref> Manifest.</p>

    <p></p>
  syntax:
    content: public String getApplicationTypeVersion()
    return:
      type: "26831127"
      description: <p>The application type version. </p>
- uid: system.fabric.query._application.getHealthState()
  id: getHealthState()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getHealthState()
  fullName: HealthState system.fabric.query.Application.getHealthState()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 110
  package: system.fabric.query
  summary: >-
    <p>Gets the aggregated health state of the application.</p>

    <p></p>
  syntax:
    content: public HealthState getHealthState()
    return:
      type: system.fabric.health._health_state
      description: <p>The aggregated health of the application. </p>
- uid: system.fabric.query._application.getUpgradeParameterList()
  id: getUpgradeParameterList()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getUpgradeParameterList()
  fullName: ApplicationParameter [] system.fabric.query.Application.getUpgradeParameterList()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 70
  package: system.fabric.query
  syntax:
    content: public ApplicationParameter[] getUpgradeParameterList()
    return:
      type: system.fabric.description._application_parameter397151d7
- uid: system.fabric.query._application.getUpgradeTypeVersion()
  id: getUpgradeTypeVersion()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: getUpgradeTypeVersion()
  fullName: String system.fabric.query.Application.getUpgradeTypeVersion()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 66
  package: system.fabric.query
  syntax:
    content: public String getUpgradeTypeVersion()
    return:
      type: "26831127"
- uid: system.fabric.query._application.toString()
  id: toString()
  parent: system.fabric.query._application
  href: system.fabric.query._application.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.query.Application.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/Application.java
    startLine: 123
  package: system.fabric.query
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: system.fabric.description._application_parameter397151d7
  spec.java:
  - uid: system.fabric.description._application_parameter
    name: ApplicationParameter
    fullName: system.fabric.description.ApplicationParameter
    href: system.fabric.description._application_parameter.yml
  - name: '[]'
    fullName: '[]'
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: system.fabric.query._application_status
  parent: system.fabric.query
  href: system.fabric.query._application_status.yml
  name: ApplicationStatus
  fullName: system.fabric.query.ApplicationStatus
  type: Enum
  summary: >-
    <p>Enum stating the possible application-status.</p>

    <p></p>
  syntax:
    content: public enum ApplicationStatus
- uid: system.fabric.health._health_state
  parent: system.fabric.health
  href: system.fabric.health._health_state.yml
  name: HealthState
  fullName: system.fabric.health.HealthState
  type: Enum
  syntax:
    content: public enum HealthState
- uid: system.fabric.description._application_parameter
  parent: system.fabric.description
  href: system.fabric.description._application_parameter.yml
  name: ApplicationParameter
  fullName: system.fabric.description.ApplicationParameter
  type: Class
  summary: >-
    <p>This class contains the detail of application-parameter - a name and a corresponding value.</p>

    <p></p>
  syntax:
    content: public class ApplicationParameter
- uid: system.fabric.query._application
  parent: system.fabric.query
  href: system.fabric.query._application.yml
  name: Application
  fullName: system.fabric.query.Application
  type: Class
  summary: >-
    <p>This class contains the details of an <xref href="system.fabric.query._application" data-throw-if-not-resolved="false"></xref>. These details include application-name, type, version, application status, health-state, application-parameter list, upgrade parameter list, upgrade-type version.</p>

    <p></p>
  syntax: *o1
