items:
- uid: system.fabric._stateful_service_failover_settings
  id: _stateful_service_failover_settings
  parent: system.fabric
  children:
  - system.fabric._stateful_service_failover_settings.getFlags()
  - system.fabric._stateful_service_failover_settings.getQuorumLossWaitDurationSeconds()
  - system.fabric._stateful_service_failover_settings.getReplicaRestartWaitDurationSeconds()
  - system.fabric._stateful_service_failover_settings.getStandByReplicaKeepDurationSeconds()
  - system.fabric._stateful_service_failover_settings.StatefulServiceFailoverSettings()
  - system.fabric._stateful_service_failover_settings.toString()
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: StatefulServiceFailoverSettings
  fullName: system.fabric.StatefulServiceFailoverSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 3
  package: system.fabric
  syntax:
    content: public class StatefulServiceFailoverSettings
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._stateful_service_failover_settings.flags()
  - system.fabric._stateful_service_failover_settings.quorumLossWaitDurationSeconds()
  - system.fabric._stateful_service_failover_settings.replicaRestartWaitDurationSeconds()
  - system.fabric._stateful_service_failover_settings.standByReplicaKeepDurationSeconds()
  - system.fabric._stateful_service_failover_settings.toNative(PinCollection)
- uid: system.fabric._stateful_service_failover_settings.getFlags()
  id: getFlags()
  parent: system.fabric._stateful_service_failover_settings
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: getFlags()
  fullName: long system.fabric.StatefulServiceFailoverSettings.getFlags()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 35
  package: system.fabric
  syntax:
    content: public long getFlags()
    return:
      type: 0364520f
- uid: system.fabric._stateful_service_failover_settings.getQuorumLossWaitDurationSeconds()
  id: getQuorumLossWaitDurationSeconds()
  parent: system.fabric._stateful_service_failover_settings
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: getQuorumLossWaitDurationSeconds()
  fullName: long system.fabric.StatefulServiceFailoverSettings.getQuorumLossWaitDurationSeconds()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 43
  package: system.fabric
  syntax:
    content: public long getQuorumLossWaitDurationSeconds()
    return:
      type: 0364520f
- uid: system.fabric._stateful_service_failover_settings.getReplicaRestartWaitDurationSeconds()
  id: getReplicaRestartWaitDurationSeconds()
  parent: system.fabric._stateful_service_failover_settings
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: getReplicaRestartWaitDurationSeconds()
  fullName: long system.fabric.StatefulServiceFailoverSettings.getReplicaRestartWaitDurationSeconds()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 39
  package: system.fabric
  syntax:
    content: public long getReplicaRestartWaitDurationSeconds()
    return:
      type: 0364520f
- uid: system.fabric._stateful_service_failover_settings.getStandByReplicaKeepDurationSeconds()
  id: getStandByReplicaKeepDurationSeconds()
  parent: system.fabric._stateful_service_failover_settings
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: getStandByReplicaKeepDurationSeconds()
  fullName: long system.fabric.StatefulServiceFailoverSettings.getStandByReplicaKeepDurationSeconds()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 47
  package: system.fabric
  syntax:
    content: public long getStandByReplicaKeepDurationSeconds()
    return:
      type: 0364520f
- uid: system.fabric._stateful_service_failover_settings.StatefulServiceFailoverSettings()
  id: StatefulServiceFailoverSettings()
  parent: system.fabric._stateful_service_failover_settings
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: StatefulServiceFailoverSettings()
  fullName: system.fabric.StatefulServiceFailoverSettings.StatefulServiceFailoverSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 28
  package: system.fabric
  syntax:
    content: public StatefulServiceFailoverSettings()
- uid: system.fabric._stateful_service_failover_settings.toString()
  id: toString()
  parent: system.fabric._stateful_service_failover_settings
  href: system.fabric._stateful_service_failover_settings.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.StatefulServiceFailoverSettings.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/StatefulServiceFailoverSettings.java
    startLine: 52
  package: system.fabric
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric._stateful_service_failover_settings.flags()
- uid: system.fabric._stateful_service_failover_settings.quorumLossWaitDurationSeconds()
- uid: system.fabric._stateful_service_failover_settings.replicaRestartWaitDurationSeconds()
- uid: system.fabric._stateful_service_failover_settings.standByReplicaKeepDurationSeconds()
- uid: system.fabric._stateful_service_failover_settings.toNative(PinCollection)
- uid: system.fabric._pin_collection
  parent: system.fabric
  href: system.fabric._pin_collection.yml
  name: PinCollection
  fullName: system.fabric.PinCollection
  type: Class
  syntax:
    content: public class PinCollection
