items:
- uid: system.fabric.query._deployed_application
  id: _deployed_application
  parent: system.fabric.query
  children:
  - system.fabric.query._deployed_application.getApplicationName()
  - system.fabric.query._deployed_application.getApplicationTypeName()
  - system.fabric.query._deployed_application.getDeploymentStatus()
  - system.fabric.query._deployed_application.getLogDir()
  - system.fabric.query._deployed_application.getTmpDir()
  - system.fabric.query._deployed_application.getWorkDir()
  - system.fabric.query._deployed_application.toString()
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: DeployedApplication
  fullName: system.fabric.query.DeployedApplication
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 11
  package: system.fabric.query
  summary: "<p>Describes an instance of an application’s service host running on a <xref href=\"system.fabric.query._service\" data-throw-if-not-resolved=\"false\"></xref> Fabric <xref href=\"system.fabric.query._node\" data-throw-if-not-resolved=\"false\"></xref>. </p>"
  syntax:
    content: public class DeployedApplication
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric.query._deployed_application.applicationName()
  - system.fabric.query._deployed_application.applicationTypeName()
  - system.fabric.query._deployed_application.deploymentStatus()
  - system.fabric.query._deployed_application.logDir()
  - system.fabric.query._deployed_application.tmpDir()
  - system.fabric.query._deployed_application.workDir()
- uid: system.fabric.query._deployed_application.getApplicationName()
  id: getApplicationName()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: getApplicationName()
  fullName: URI system.fabric.query.DeployedApplication.getApplicationName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 44
  package: system.fabric.query
  summary: >-
    <p>Gets the application name.</p>

    <p></p>
  syntax:
    content: public URI getApplicationName()
    return:
      type: "62304784"
      description: <p>The application name. </p>
- uid: system.fabric.query._deployed_application.getApplicationTypeName()
  id: getApplicationTypeName()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: getApplicationTypeName()
  fullName: String system.fabric.query.DeployedApplication.getApplicationTypeName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 51
  package: system.fabric.query
  summary: <p>Gets the application type name. </p>
  syntax:
    content: public String getApplicationTypeName()
    return:
      type: "26831127"
      description: <p>The application type name. </p>
- uid: system.fabric.query._deployed_application.getDeploymentStatus()
  id: getDeploymentStatus()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: getDeploymentStatus()
  fullName: DeploymentStatus system.fabric.query.DeployedApplication.getDeploymentStatus()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 58
  package: system.fabric.query
  summary: <p>Gets the status of the deployed application instance. </p>
  syntax:
    content: public DeploymentStatus getDeploymentStatus()
    return:
      type: system.fabric._deployment_status
      description: <p>The status of the deployed application instance. </p>
- uid: system.fabric.query._deployed_application.getLogDir()
  id: getLogDir()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: getLogDir()
  fullName: String system.fabric.query.DeployedApplication.getLogDir()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 72
  package: system.fabric.query
  summary: <p>Gets the log directory path used by the deployed application instance. </p>
  syntax:
    content: public String getLogDir()
    return:
      type: "26831127"
      description: <p>The log directory path used by the deployed application instance. </p>
- uid: system.fabric.query._deployed_application.getTmpDir()
  id: getTmpDir()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: getTmpDir()
  fullName: String system.fabric.query.DeployedApplication.getTmpDir()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 79
  package: system.fabric.query
  summary: <p>Gets the temp directory path used by the deployed application instance. </p>
  syntax:
    content: public String getTmpDir()
    return:
      type: "26831127"
      description: <p>The temp directory path used by the deployed application instance. </p>
- uid: system.fabric.query._deployed_application.getWorkDir()
  id: getWorkDir()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: getWorkDir()
  fullName: String system.fabric.query.DeployedApplication.getWorkDir()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 65
  package: system.fabric.query
  summary: <p>Gets the work directory path used by the deployed application instance. </p>
  syntax:
    content: public String getWorkDir()
    return:
      type: "26831127"
      description: <p>The work directory path used by the deployed application instance. </p>
- uid: system.fabric.query._deployed_application.toString()
  id: toString()
  parent: system.fabric.query._deployed_application
  href: system.fabric.query._deployed_application.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.query.DeployedApplication.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/DeployedApplication.java
    startLine: 83
  package: system.fabric.query
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric.query._deployed_application.applicationName()
- uid: system.fabric.query._deployed_application.applicationTypeName()
- uid: system.fabric.query._deployed_application.deploymentStatus()
- uid: system.fabric.query._deployed_application.logDir()
- uid: system.fabric.query._deployed_application.tmpDir()
- uid: system.fabric.query._deployed_application.workDir()
- uid: system.fabric._deployment_status
  parent: system.fabric
  href: system.fabric._deployment_status.yml
  name: DeploymentStatus
  fullName: system.fabric.DeploymentStatus
  type: Enum
  summary: <p>Specifies the status of the package on the node </p>
  syntax:
    content: public enum DeploymentStatus
- uid: system.fabric.query._service
  parent: system.fabric.query
  href: system.fabric.query._service.yml
  name: Service
  fullName: system.fabric.query.Service
  type: Class
  summary: <p>Represents a service. </p>
  syntax:
    content: public class Service
- uid: system.fabric.query._node
  parent: system.fabric.query
  href: system.fabric.query._node.yml
  name: Node
  fullName: system.fabric.query.Node
  type: Class
  summary: >-
    <p>This class contains the details of a <xref href="system.fabric.query._node" data-throw-if-not-resolved="false"></xref>. These details include - name, ip, node-type, code-version, config-version, node-status, node uptime, health-state, if it is a seed-node, upgrade domain, fault domain, nodeId, node instance-id and node de-activation result.</p>

    <p></p>
  syntax:
    content: public class Node
