items:
- uid: system.fabric._configuration_package_change_handler
  id: _configuration_package_change_handler
  parent: system.fabric
  children:
  - system.fabric._configuration_package_change_handler.onPackageAdded(CodePackageActivationContext,ConfigurationPackage)
  - system.fabric._configuration_package_change_handler.onPackageModified(CodePackageActivationContext,ConfigurationPackage,ConfigurationPackage)
  - system.fabric._configuration_package_change_handler.onPackageRemoved(CodePackageActivationContext,ConfigurationPackage)
  href: system.fabric._configuration_package_change_handler.yml
  langs:
  - java
  name: ConfigurationPackageChangeHandler
  fullName: system.fabric.ConfigurationPackageChangeHandler
  type: Interface
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageChangeHandler.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageChangeHandler.java
    startLine: 7
  package: system.fabric
  syntax:
    content: public interface ConfigurationPackageChangeHandler
- uid: system.fabric._configuration_package_change_handler.onPackageAdded(CodePackageActivationContext,ConfigurationPackage)
  id: onPackageAdded(CodePackageActivationContext,ConfigurationPackage)
  parent: system.fabric._configuration_package_change_handler
  href: system.fabric._configuration_package_change_handler.yml
  langs:
  - java
  name: onPackageAdded(CodePackageActivationContext source, ConfigurationPackage newPackage)
  fullName: void system.fabric.ConfigurationPackageChangeHandler.onPackageAdded(CodePackageActivationContext source, ConfigurationPackage newPackage)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageChangeHandler.java
    startLine: 9
  package: system.fabric
  syntax:
    content: public void onPackageAdded(CodePackageActivationContext source, ConfigurationPackage newPackage)
    parameters:
    - id: source
      type: system.fabric._code_package_activation_context
    - id: newPackage
      type: system.fabric._configuration_package
- uid: system.fabric._configuration_package_change_handler.onPackageModified(CodePackageActivationContext,ConfigurationPackage,ConfigurationPackage)
  id: onPackageModified(CodePackageActivationContext,ConfigurationPackage,ConfigurationPackage)
  parent: system.fabric._configuration_package_change_handler
  href: system.fabric._configuration_package_change_handler.yml
  langs:
  - java
  name: onPackageModified(CodePackageActivationContext source, ConfigurationPackage oldPackage, ConfigurationPackage newPackage)
  fullName: void system.fabric.ConfigurationPackageChangeHandler.onPackageModified(CodePackageActivationContext source, ConfigurationPackage oldPackage, ConfigurationPackage newPackage)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageChangeHandler.java
    startLine: 13
  package: system.fabric
  syntax:
    content: public void onPackageModified(CodePackageActivationContext source, ConfigurationPackage oldPackage, ConfigurationPackage newPackage)
    parameters:
    - id: source
      type: system.fabric._code_package_activation_context
    - id: oldPackage
      type: system.fabric._configuration_package
    - id: newPackage
      type: system.fabric._configuration_package
- uid: system.fabric._configuration_package_change_handler.onPackageRemoved(CodePackageActivationContext,ConfigurationPackage)
  id: onPackageRemoved(CodePackageActivationContext,ConfigurationPackage)
  parent: system.fabric._configuration_package_change_handler
  href: system.fabric._configuration_package_change_handler.yml
  langs:
  - java
  name: onPackageRemoved(CodePackageActivationContext source, ConfigurationPackage oldPackage)
  fullName: void system.fabric.ConfigurationPackageChangeHandler.onPackageRemoved(CodePackageActivationContext source, ConfigurationPackage oldPackage)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationPackageChangeHandler.java
    startLine: 11
  package: system.fabric
  syntax:
    content: public void onPackageRemoved(CodePackageActivationContext source, ConfigurationPackage oldPackage)
    parameters:
    - id: source
      type: system.fabric._code_package_activation_context
    - id: oldPackage
      type: system.fabric._configuration_package
references:
- uid: system.fabric._code_package_activation_context
  parent: system.fabric
  href: system.fabric._code_package_activation_context.yml
  name: CodePackageActivationContext
  fullName: system.fabric.CodePackageActivationContext
  type: Class
  summary: <p>Represents activation context for the Service Fabric service. This is valid for fabric activated service only. </p>
  syntax:
    content: public class CodePackageActivationContext
- uid: system.fabric._configuration_package
  parent: system.fabric
  href: system.fabric._configuration_package.yml
  name: ConfigurationPackage
  fullName: system.fabric.ConfigurationPackage
  type: Class
  summary: <p>Represents a configuration package. </p>
  syntax:
    content: public class ConfigurationPackage
