items:
- uid: system.fabric._key_value_store_transaction_settings
  id: _key_value_store_transaction_settings
  parent: system.fabric
  children:
  - system.fabric._key_value_store_transaction_settings.getSerializationBlockSize()
  - system.fabric._key_value_store_transaction_settings.setSerializationBlockSize(long)
  href: system.fabric._key_value_store_transaction_settings.yml
  langs:
  - java
  name: KeyValueStoreTransactionSettings
  fullName: system.fabric.KeyValueStoreTransactionSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/KeyValueStoreTransactionSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/KeyValueStoreTransactionSettings.java
    startLine: 8
  package: system.fabric
  summary: <p>Specifies the optional settings to describe the behavior of transactions supported by <xref href="system.fabric._key_value_store_replica" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class KeyValueStoreTransactionSettings
  inheritance:
  - java.lang.Object
- uid: system.fabric._key_value_store_transaction_settings.getSerializationBlockSize()
  id: getSerializationBlockSize()
  parent: system.fabric._key_value_store_transaction_settings
  href: system.fabric._key_value_store_transaction_settings.yml
  langs:
  - java
  name: getSerializationBlockSize()
  fullName: long system.fabric.KeyValueStoreTransactionSettings.getSerializationBlockSize()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/KeyValueStoreTransactionSettings.java
    startLine: 16
  package: system.fabric
  summary: <p>Specifies the block size (in bytes) to use when allocating memory for replication operations. </p>
  syntax:
    content: public long getSerializationBlockSize()
    return:
      type: 0364520f
      description: <p>The block size (in bytes) to use when allocating memory for replication operations. </p>
- uid: system.fabric._key_value_store_transaction_settings.setSerializationBlockSize(long)
  id: setSerializationBlockSize(long)
  parent: system.fabric._key_value_store_transaction_settings
  href: system.fabric._key_value_store_transaction_settings.yml
  langs:
  - java
  name: setSerializationBlockSize(long serializationBlockSize)
  fullName: void system.fabric.KeyValueStoreTransactionSettings.setSerializationBlockSize(long serializationBlockSize)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/KeyValueStoreTransactionSettings.java
    startLine: 23
  package: system.fabric
  summary: <p>Specifies the block size (in bytes) to use when allocating memory for replication operations. </p>
  syntax:
    content: public void setSerializationBlockSize(long serializationBlockSize)
    parameters:
    - id: serializationBlockSize
      type: 0364520f
      description: <p>The block size (in bytes) to use when allocating memory for replication operations. </p>
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: system.fabric._key_value_store_replica
  parent: system.fabric
  href: system.fabric._key_value_store_replica.yml
  name: KeyValueStoreReplica
  fullName: system.fabric.KeyValueStoreReplica
  type: Class
  summary: "<p>Provides a transactional, replicated, associative data storage to service writers – ready for integration into any Service Fabric service. </p>"
  syntax:
    content: public class KeyValueStoreReplica implements StatefulServiceReplica
