items:
- uid: system.fabric._replica_set_configuration
  id: _replica_set_configuration
  parent: system.fabric
  children:
  - system.fabric._replica_set_configuration.getReplicas()
  - system.fabric._replica_set_configuration.getWriteQuorum()
  href: system.fabric._replica_set_configuration.yml
  langs:
  - java
  name: ReplicaSetConfiguration
  fullName: system.fabric.ReplicaSetConfiguration
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ReplicaSetConfiguration.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ReplicaSetConfiguration.java
    startLine: 9
  package: system.fabric
  summary: <p>This supports the Service Fabric infrastructure and is not meant to be used directly from your code. </p>
  syntax:
    content: public class ReplicaSetConfiguration
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._replica_set_configuration.ReplicaSetConfiguration(long,ReplicaInformation [])
- uid: system.fabric._replica_set_configuration.getReplicas()
  id: getReplicas()
  parent: system.fabric._replica_set_configuration
  href: system.fabric._replica_set_configuration.yml
  langs:
  - java
  name: getReplicas()
  fullName: List<ReplicaInformation> system.fabric.ReplicaSetConfiguration.getReplicas()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ReplicaSetConfiguration.java
    startLine: 32
  package: system.fabric
  summary: >-
    <p>This supports the Service Fabric infrastructure and is not meant to be used directly from your code.</p>

    <p></p>
  syntax:
    content: public List<ReplicaInformation> getReplicas()
    return:
      type: 5618da2dsystem.fabric._replica_informationa08ddfce
      description: <p>This supports the Service Fabric infrastructure and is not meant to be used directly from your code. </p>
- uid: system.fabric._replica_set_configuration.getWriteQuorum()
  id: getWriteQuorum()
  parent: system.fabric._replica_set_configuration
  href: system.fabric._replica_set_configuration.yml
  langs:
  - java
  name: getWriteQuorum()
  fullName: long system.fabric.ReplicaSetConfiguration.getWriteQuorum()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ReplicaSetConfiguration.java
    startLine: 21
  package: system.fabric
  summary: >-
    <p>This supports the Service Fabric infrastructure and is not meant to be used directly from your code.</p>

    <p></p>
  syntax:
    content: public long getWriteQuorum()
    return:
      type: 0364520f
      description: <p>This supports the Service Fabric infrastructure and is not meant to be used directly from your code. </p>
references:
- uid: 0364520f
  spec.java:
  - name: long
    fullName: long
- uid: 5618da2dsystem.fabric._replica_informationa08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: system.fabric._replica_information
    name: ReplicaInformation
    fullName: system.fabric.ReplicaInformation
    href: system.fabric._replica_information.yml
  - name: '>'
    fullName: '>'
- uid: system.fabric._replica_set_configuration.ReplicaSetConfiguration(long,ReplicaInformation [])
- uid: system.fabric._replica_information
  parent: system.fabric
  href: system.fabric._replica_information.yml
  name: ReplicaInformation
  fullName: system.fabric.ReplicaInformation
  type: Class
  summary: >-
    <p>FOR INTERNAL USE ONLY. Represents information about a replica.</p>

    <p></p>
  syntax:
    content: public class ReplicaInformation
