items:
- uid: system.fabric._configuration_section
  id: _configuration_section
  parent: system.fabric
  children:
  - system.fabric._configuration_section.getName()
  - system.fabric._configuration_section.getParameters()
  href: system.fabric._configuration_section.yml
  langs:
  - java
  name: ConfigurationSection
  fullName: system.fabric.ConfigurationSection
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSection.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSection.java
    startLine: 4
  package: system.fabric
  summary: <p>Defines any configuration that can be written and read from a configuration store </p>
  syntax:
    content: public class ConfigurationSection
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._configuration_section.ConfigurationSection(String,ConfigurationProperty[])
- uid: system.fabric._configuration_section.getName()
  id: getName()
  parent: system.fabric._configuration_section
  href: system.fabric._configuration_section.yml
  langs:
  - java
  name: getName()
  fullName: String system.fabric.ConfigurationSection.getName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSection.java
    startLine: 21
  package: system.fabric
  summary: <p>The name of the section. </p>
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>the name. </p>
- uid: system.fabric._configuration_section.getParameters()
  id: getParameters()
  parent: system.fabric._configuration_section
  href: system.fabric._configuration_section.yml
  langs:
  - java
  name: getParameters()
  fullName: HashMap<String, ConfigurationProperty> system.fabric.ConfigurationSection.getParameters()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/ConfigurationSection.java
    startLine: 28
  package: system.fabric
  summary: <p>The key/value pair of a configuration property. </p>
  syntax:
    content: public HashMap<String, ConfigurationProperty> getParameters()
    return:
      type: 292b5718system.fabric._configuration_propertya08ddfce
      description: >-
        <p>

          <ref refid="" kindref="compound">java.util.HashMap</ref> of String key and <xref href="system.fabric._configuration_property" data-throw-if-not-resolved="false"></xref> value. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 292b5718system.fabric._configuration_propertya08ddfce
  spec.java:
  - name: 'HashMap<String, '
    fullName: 'HashMap<String, '
  - uid: system.fabric._configuration_property
    name: ConfigurationProperty
    fullName: system.fabric.ConfigurationProperty
    href: system.fabric._configuration_property.yml
  - name: '>'
    fullName: '>'
- uid: system.fabric._configuration_section.ConfigurationSection(String,ConfigurationProperty[])
- uid: system.fabric._configuration_property
  parent: system.fabric
  href: system.fabric._configuration_property.yml
  name: ConfigurationProperty
  fullName: system.fabric.ConfigurationProperty
  type: Class
  summary: <p>Specifies a name-value pair that is used to configure a service or application. </p>
  syntax:
    content: public class ConfigurationProperty
