items:
- uid: system.fabric._get_application_list_test
  id: _get_application_list_test
  parent: system.fabric
  children:
  - system.fabric._get_application_list_test.cleanup()
  - system.fabric._get_application_list_test.setup()
  - system.fabric._get_application_list_test.testGetApplicationListWithApplicationName()
  - system.fabric._get_application_list_test.testGetApplicationListWithNoArgument()
  href: system.fabric._get_application_list_test.yml
  langs:
  - java
  name: GetApplicationListTest
  fullName: system.fabric.GetApplicationListTest
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/test/system/fabric/GetApplicationListTest.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/test/system/fabric/GetApplicationListTest.java
    startLine: 17
  package: system.fabric
  syntax:
    content: public class GetApplicationListTest
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._get_application_list_test.app()
  - system.fabric._get_application_list_test.client()
- uid: system.fabric._get_application_list_test.cleanup()
  id: cleanup()
  parent: system.fabric._get_application_list_test
  href: system.fabric._get_application_list_test.yml
  langs:
  - java
  name: cleanup()
  fullName: void system.fabric.GetApplicationListTest.cleanup()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/test/system/fabric/GetApplicationListTest.java
    startLine: 38
  package: system.fabric
  syntax:
    content: public void cleanup()
- uid: system.fabric._get_application_list_test.setup()
  id: setup()
  parent: system.fabric._get_application_list_test
  href: system.fabric._get_application_list_test.yml
  langs:
  - java
  name: setup()
  fullName: void system.fabric.GetApplicationListTest.setup()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/test/system/fabric/GetApplicationListTest.java
    startLine: 22
  package: system.fabric
  syntax:
    content: public void setup()
- uid: system.fabric._get_application_list_test.testGetApplicationListWithApplicationName()
  id: testGetApplicationListWithApplicationName()
  parent: system.fabric._get_application_list_test
  href: system.fabric._get_application_list_test.yml
  langs:
  - java
  name: testGetApplicationListWithApplicationName()
  fullName: void system.fabric.GetApplicationListTest.testGetApplicationListWithApplicationName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/test/system/fabric/GetApplicationListTest.java
    startLine: 33
  package: system.fabric
  syntax:
    content: public void testGetApplicationListWithApplicationName()
- uid: system.fabric._get_application_list_test.testGetApplicationListWithNoArgument()
  id: testGetApplicationListWithNoArgument()
  parent: system.fabric._get_application_list_test
  href: system.fabric._get_application_list_test.yml
  langs:
  - java
  name: testGetApplicationListWithNoArgument()
  fullName: void system.fabric.GetApplicationListTest.testGetApplicationListWithNoArgument()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/test/system/fabric/GetApplicationListTest.java
    startLine: 28
  package: system.fabric
  syntax:
    content: public void testGetApplicationListWithNoArgument()
references:
- uid: system.fabric._get_application_list_test.app()
- uid: system.fabric._get_application_list_test.client()
- uid: system.fabric.query._application
  parent: system.fabric.query
  href: system.fabric.query._application.yml
  name: Application
  fullName: system.fabric.query.Application
  type: Class
  summary: >-
    <p>This class contains the details of an <xref href="system.fabric.query._application" data-throw-if-not-resolved="false"></xref>. These details include application-name, type, version, application status, health-state, application-parameter list, upgrade parameter list, upgrade-type version.</p>

    <p></p>
  syntax:
    content: public class Application
- uid: system.fabric._fabric_client
  parent: system.fabric
  href: system.fabric._fabric_client.yml
  name: FabricClient
  fullName: system.fabric.FabricClient
  type: Class
  summary: >-
    <p>Creates and manages Service Fabric services and other entities. </p>

    <p>

      <bold>Remarks:</bold>It is highly recommended that you share FabricClients as much as possible. This is because the <xref href="system.fabric._fabric_client" data-throw-if-not-resolved="false"></xref> has multiple optimizations such as caching and batching that you would not be able to fully utilize otherwise. </p>
  syntax:
    content: public class FabricClient
