items:
- uid: system.fabric.query._application_type
  id: _application_type
  parent: system.fabric.query
  children:
  - system.fabric.query._application_type.getApplicationParameters()
  - system.fabric.query._application_type.getApplicationTypeName()
  - system.fabric.query._application_type.getApplicationTypeVersion()
  - system.fabric.query._application_type.toString()
  href: system.fabric.query._application_type.yml
  langs:
  - java
  name: ApplicationType
  fullName: system.fabric.query.ApplicationType
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/query/ApplicationType.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ApplicationType.java
    startLine: 13
  package: system.fabric.query
  summary: >-
    <p>Contains details of an application-type. Namely ApplicationTypeName, ApplicationTypeVersion and set of default application parameters.</p>

    <p></p>
  syntax:
    content: public class ApplicationType
  inheritance:
  - java.lang.Object
- uid: system.fabric.query._application_type.getApplicationParameters()
  id: getApplicationParameters()
  parent: system.fabric.query._application_type
  href: system.fabric.query._application_type.yml
  langs:
  - java
  name: getApplicationParameters()
  fullName: ApplicationParameter [] system.fabric.query.ApplicationType.getApplicationParameters()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ApplicationType.java
    startLine: 55
  package: system.fabric.query
  summary: >-
    <p>Gets the default application parameters applied to this instance of the application.</p>

    <p></p>
  syntax:
    content: public ApplicationParameter [] getApplicationParameters()
    return:
      type: system.fabric.description._application_parametere5b41c5f
      description: <p>The default application parameters applied to this instance of the application. </p>
- uid: system.fabric.query._application_type.getApplicationTypeName()
  id: getApplicationTypeName()
  parent: system.fabric.query._application_type
  href: system.fabric.query._application_type.yml
  langs:
  - java
  name: getApplicationTypeName()
  fullName: String system.fabric.query.ApplicationType.getApplicationTypeName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ApplicationType.java
    startLine: 37
  package: system.fabric.query
  summary: >-
    <p>Gets the application type name.</p>

    <p></p>
  syntax:
    content: public String getApplicationTypeName()
    return:
      type: "26831127"
      description: <p>The application type name. </p>
- uid: system.fabric.query._application_type.getApplicationTypeVersion()
  id: getApplicationTypeVersion()
  parent: system.fabric.query._application_type
  href: system.fabric.query._application_type.yml
  langs:
  - java
  name: getApplicationTypeVersion()
  fullName: String system.fabric.query.ApplicationType.getApplicationTypeVersion()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ApplicationType.java
    startLine: 46
  package: system.fabric.query
  summary: >-
    <p>Gets the application type version.</p>

    <p></p>
  syntax:
    content: public String getApplicationTypeVersion()
    return:
      type: "26831127"
      description: <p>The application type version. </p>
- uid: system.fabric.query._application_type.toString()
  id: toString()
  parent: system.fabric.query._application_type
  href: system.fabric.query._application_type.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.query.ApplicationType.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/query/ApplicationType.java
    startLine: 60
  package: system.fabric.query
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric.description._application_parametere5b41c5f
  spec.java:
  - uid: system.fabric.description._application_parameter
    name: ApplicationParameter
    fullName: system.fabric.description.ApplicationParameter
    href: system.fabric.description._application_parameter.yml
  - name: " []"
    fullName: " []"
- uid: system.fabric.description._application_parameter
  parent: system.fabric.description
  href: system.fabric.description._application_parameter.yml
  name: ApplicationParameter
  fullName: system.fabric.description.ApplicationParameter
  type: Class
  summary: >-
    <p>This class contains the detail of application-parameter - a name and a corresponding value.</p>

    <p></p>
  syntax:
    content: public class ApplicationParameter
