items:
- uid: system.fabric._local_store_settings
  id: _local_store_settings
  parent: system.fabric
  children:
  - system.fabric._local_store_settings.getStoreKind()
  - system.fabric._local_store_settings.setStoreKind(LocalStoreKind)
  href: system.fabric._local_store_settings.yml
  langs:
  - java
  name: LocalStoreSettings
  fullName: system.fabric.LocalStoreSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/LocalStoreSettings.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/LocalStoreSettings.java
    startLine: 2
  package: system.fabric
  summary: <p>Represents the option settings for a local store. </p>
  syntax:
    content: public class LocalStoreSettings
  inheritance:
  - java.lang.Object
- uid: system.fabric._local_store_settings.getStoreKind()
  id: getStoreKind()
  parent: system.fabric._local_store_settings
  href: system.fabric._local_store_settings.yml
  langs:
  - java
  name: getStoreKind()
  fullName: LocalStoreKind system.fabric.LocalStoreSettings.getStoreKind()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/LocalStoreSettings.java
    startLine: 9
  package: system.fabric
  summary: <p>Gets the store provider type. </p>
  syntax:
    content: public LocalStoreKind getStoreKind()
    return:
      type: system.fabric._local_store_kind
      description: <p>The store provider type as a <xref href="system.fabric._local_store_kind" data-throw-if-not-resolved="false"></xref> object. </p>
- uid: system.fabric._local_store_settings.setStoreKind(LocalStoreKind)
  id: setStoreKind(LocalStoreKind)
  parent: system.fabric._local_store_settings
  href: system.fabric._local_store_settings.yml
  langs:
  - java
  name: setStoreKind(LocalStoreKind storeKind)
  fullName: void system.fabric.LocalStoreSettings.setStoreKind(LocalStoreKind storeKind)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/LocalStoreSettings.java
    startLine: 13
  package: system.fabric
  syntax:
    content: protected void setStoreKind(LocalStoreKind storeKind)
    parameters:
    - id: storeKind
      type: system.fabric._local_store_kind
references:
- uid: system.fabric._local_ese_store_settings
  parent: system.fabric
  href: system.fabric._local_ese_store_settings.yml
  name: LocalEseStoreSettings
  fullName: system.fabric.LocalEseStoreSettings
  type: Class
  summary: <p>Initializes a new instance of the <xref href="system.fabric._local_ese_store_settings" data-throw-if-not-resolved="false"></xref> class. </p>
  syntax:
    content: public class LocalEseStoreSettings extends LocalStoreSettings
- uid: system.fabric._local_store_kind
  parent: system.fabric
  href: system.fabric._local_store_kind.yml
  name: LocalStoreKind
  fullName: system.fabric.LocalStoreKind
  type: Enum
  syntax:
    content: public enum LocalStoreKind
