items:
- uid: system.fabric._deployed_application_health_query_description
  id: _deployed_application_health_query_description
  parent: system.fabric
  children:
  - system.fabric._deployed_application_health_query_description.DeployedApplicationHealthQueryDescription(URI,String)
  - system.fabric._deployed_application_health_query_description.getApplicationHealthPolicy()
  - system.fabric._deployed_application_health_query_description.getApplicationName()
  - system.fabric._deployed_application_health_query_description.getDeployedServicePackageHealthStatesFilter()
  - system.fabric._deployed_application_health_query_description.getHealthEventsFilter()
  - system.fabric._deployed_application_health_query_description.getNodeName()
  - system.fabric._deployed_application_health_query_description.setApplicationHealthPolicy(ApplicationHealthPolicy)
  - system.fabric._deployed_application_health_query_description.setDeployedServicePackageHealthStatesFilter(DeployedServicePackageHealthStatesFilter)
  - system.fabric._deployed_application_health_query_description.setHealthEventsFilter(HealthEventsFilter)
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: DeployedApplicationHealthQueryDescription
  fullName: system.fabric.DeployedApplicationHealthQueryDescription
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 6
  package: system.fabric
  summary: <p>Describes query input for getting <xref href="system.fabric.health._deployed_application_health" data-throw-if-not-resolved="false"></xref>. Used by <xref href="system.fabric._health_client.getDeployedApplicationHealthAsync(DeployedApplicationHealthQueryDescription)" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class DeployedApplicationHealthQueryDescription
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._deployed_application_health_query_description.toNative(PinCollection)
  - system.fabric._deployed_application_health_query_description.ToNative(long,long,long,long,long)
- uid: system.fabric._deployed_application_health_query_description.DeployedApplicationHealthQueryDescription(URI,String)
  id: DeployedApplicationHealthQueryDescription(URI,String)
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: DeployedApplicationHealthQueryDescription(URI applicationName, String nodeName)
  fullName: system.fabric.DeployedApplicationHealthQueryDescription.DeployedApplicationHealthQueryDescription(URI applicationName, String nodeName)
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 24
  package: system.fabric
  summary: <p>Initializes a new instance of the <ref refid="" kindref="compound">system.fabric.DeployedApplicationHealthQueryDescription</ref> class. </p>
  syntax:
    content: public DeployedApplicationHealthQueryDescription(URI applicationName, String nodeName)
    parameters:
    - id: applicationName
      type: "62304784"
      description: <p>The application name. Cannot be null. </p>
    - id: nodeName
      type: "26831127"
      description: <p>The node name. Cannot be null or empty. </p>
- uid: system.fabric._deployed_application_health_query_description.getApplicationHealthPolicy()
  id: getApplicationHealthPolicy()
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: getApplicationHealthPolicy()
  fullName: ApplicationHealthPolicy system.fabric.DeployedApplicationHealthQueryDescription.getApplicationHealthPolicy()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 68
  package: system.fabric
  summary: <p>Gets the <xref href="system.fabric._application_health_policy" data-throw-if-not-resolved="false"></xref> used to evaluate the deployed application health. </p>
  syntax:
    content: public ApplicationHealthPolicy getApplicationHealthPolicy()
    return:
      type: system.fabric._application_health_policy
      description: <p>the <xref href="system.fabric._application_health_policy" data-throw-if-not-resolved="false"></xref> used to evaluate the deployed application health. </p>
- uid: system.fabric._deployed_application_health_query_description.getApplicationName()
  id: getApplicationName()
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: getApplicationName()
  fullName: URI system.fabric.DeployedApplicationHealthQueryDescription.getApplicationName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 54
  package: system.fabric
  summary: <p>Gets the name of the application. </p>
  syntax:
    content: public URI getApplicationName()
    return:
      type: "62304784"
      description: <p>The name of the application. </p>
- uid: system.fabric._deployed_application_health_query_description.getDeployedServicePackageHealthStatesFilter()
  id: getDeployedServicePackageHealthStatesFilter()
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: getDeployedServicePackageHealthStatesFilter()
  fullName: DeployedServicePackageHealthStatesFilter system.fabric.DeployedApplicationHealthQueryDescription.getDeployedServicePackageHealthStatesFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 99
  package: system.fabric
  summary: <p>Gets the filter for <xref href="system.fabric.health._deployed_service_package_health_state" data-throw-if-not-resolved="false"></xref> children. Only children that match the filter will be returned. <bold>Remarks:</bold>Only children that match the filter will be returned. All children will be used to evaluate the deployed application aggregated health state. If the filter is not specified, all deployed service package children of the deployed application are returned.</p>
  syntax:
    content: public DeployedServicePackageHealthStatesFilter getDeployedServicePackageHealthStatesFilter()
    return:
      type: system.fabric._deployed_service_package_health_states_filter
      description: >-
        <p>

          <xref href="system.fabric._deployed_service_package_health_states_filter" data-throw-if-not-resolved="false"></xref> used to filter returned deployed service packages. </p>
- uid: system.fabric._deployed_application_health_query_description.getHealthEventsFilter()
  id: getHealthEventsFilter()
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: getHealthEventsFilter()
  fullName: HealthEventsFilter system.fabric.DeployedApplicationHealthQueryDescription.getHealthEventsFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 83
  package: system.fabric
  summary: <p>Gets the filter for the collection of <xref href="system.fabric.health._health_event" data-throw-if-not-resolved="false"></xref> reported on the deployed application. Only events that match the filter will be returned. <bold>Remarks:</bold>Only events that match the filter will be returned. All events will be used to evaluate the application aggregated health state. If the filter is not specified, all events are returned.</p>
  syntax:
    content: public HealthEventsFilter getHealthEventsFilter()
    return:
      type: system.fabric._health_events_filter
      description: >-
        <p>

          <xref href="system.fabric._health_events_filter" data-throw-if-not-resolved="false"></xref> used to filter returned events. </p>
- uid: system.fabric._deployed_application_health_query_description.getNodeName()
  id: getNodeName()
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: getNodeName()
  fullName: String system.fabric.DeployedApplicationHealthQueryDescription.getNodeName()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 61
  package: system.fabric
  summary: <p>Gets the node name. </p>
  syntax:
    content: public String getNodeName()
    return:
      type: "26831127"
      description: <p>The node name. </p>
- uid: system.fabric._deployed_application_health_query_description.setApplicationHealthPolicy(ApplicationHealthPolicy)
  id: setApplicationHealthPolicy(ApplicationHealthPolicy)
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: setApplicationHealthPolicy(ApplicationHealthPolicy applicationHealthPolicy)
  fullName: void system.fabric.DeployedApplicationHealthQueryDescription.setApplicationHealthPolicy(ApplicationHealthPolicy applicationHealthPolicy)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 75
  package: system.fabric
  summary: <p>Sets the <xref href="system.fabric._application_health_policy" data-throw-if-not-resolved="false"></xref> used to evaluate the deployed application health. </p>
  syntax:
    content: public void setApplicationHealthPolicy(ApplicationHealthPolicy applicationHealthPolicy)
    parameters:
    - id: applicationHealthPolicy
      type: system.fabric._application_health_policy
      description: <p>the <xref href="system.fabric._application_health_policy" data-throw-if-not-resolved="false"></xref> used to evaluate the deployed application health. </p>
- uid: system.fabric._deployed_application_health_query_description.setDeployedServicePackageHealthStatesFilter(DeployedServicePackageHealthStatesFilter)
  id: setDeployedServicePackageHealthStatesFilter(DeployedServicePackageHealthStatesFilter)
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: setDeployedServicePackageHealthStatesFilter(DeployedServicePackageHealthStatesFilter deployedServicePackageHealthStatesFilter)
  fullName: void system.fabric.DeployedApplicationHealthQueryDescription.setDeployedServicePackageHealthStatesFilter(DeployedServicePackageHealthStatesFilter deployedServicePackageHealthStatesFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 107
  package: system.fabric
  summary: <p>Sets the filter for <xref href="system.fabric.health._deployed_service_package_health_state" data-throw-if-not-resolved="false"></xref> children. Only children that match the filter will be returned. <bold>Remarks:</bold>Only events that match the filter will be returned. All events will be used to evaluate the application aggregated health state. If the filter is not specified, all events are returned.</p>
  syntax:
    content: public void setDeployedServicePackageHealthStatesFilter(DeployedServicePackageHealthStatesFilter deployedServicePackageHealthStatesFilter)
    parameters:
    - id: deployedServicePackageHealthStatesFilter
      type: system.fabric._deployed_service_package_health_states_filter
      description: >-
        <p>

          <xref href="system.fabric._deployed_service_package_health_states_filter" data-throw-if-not-resolved="false"></xref> used to filter returned deployed service packages. </p>
- uid: system.fabric._deployed_application_health_query_description.setHealthEventsFilter(HealthEventsFilter)
  id: setHealthEventsFilter(HealthEventsFilter)
  parent: system.fabric._deployed_application_health_query_description
  href: system.fabric._deployed_application_health_query_description.yml
  langs:
  - java
  name: setHealthEventsFilter(HealthEventsFilter healthEventsFilter)
  fullName: void system.fabric.DeployedApplicationHealthQueryDescription.setHealthEventsFilter(HealthEventsFilter healthEventsFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthQueryDescription.java
    startLine: 91
  package: system.fabric
  summary: <p>Sets the filter for the collection of <xref href="system.fabric.health._health_event" data-throw-if-not-resolved="false"></xref> reported on the deployed application. Only events that match the filter will be returned. <bold>Remarks:</bold>Only events that match the filter will be returned. All events will be used to evaluate the application aggregated health state. If the filter is not specified, all events are returned.</p>
  syntax:
    content: public void setHealthEventsFilter(HealthEventsFilter healthEventsFilter)
    parameters:
    - id: healthEventsFilter
      type: system.fabric._health_events_filter
      description: >-
        <p>

          <xref href="system.fabric._health_events_filter" data-throw-if-not-resolved="false"></xref> used to filter returned events. </p>
references:
- uid: "62304784"
  spec.java:
  - name: URI
    fullName: URI
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric._deployed_application_health_query_description.toNative(PinCollection)
- uid: system.fabric._deployed_application_health_query_description.ToNative(long,long,long,long,long)
- uid: system.fabric._application_health_policy
  parent: system.fabric
  href: system.fabric._application_health_policy.yml
  name: ApplicationHealthPolicy
  fullName: system.fabric.ApplicationHealthPolicy
  type: Class
  summary: <p>Defines a health policy used to evaluate the health of an application or one of its children entities. </p>
  syntax:
    content: public class ApplicationHealthPolicy
- uid: system.fabric._health_events_filter
  parent: system.fabric
  href: system.fabric._health_events_filter.yml
  name: HealthEventsFilter
  fullName: system.fabric.HealthEventsFilter
  type: Class
  syntax:
    content: public class HealthEventsFilter
- uid: system.fabric._deployed_service_package_health_states_filter
  parent: system.fabric
  href: system.fabric._deployed_service_package_health_states_filter.yml
  name: DeployedServicePackageHealthStatesFilter
  fullName: system.fabric.DeployedServicePackageHealthStatesFilter
  type: Class
  syntax:
    content: public class DeployedServicePackageHealthStatesFilter
- uid: system.fabric._pin_collection
  parent: system.fabric
  href: system.fabric._pin_collection.yml
  name: PinCollection
  fullName: system.fabric.PinCollection
  type: Class
  syntax:
    content: public class PinCollection
- uid: system.fabric.health._health_event
  parent: system.fabric.health
  href: system.fabric.health._health_event.yml
  name: HealthEvent
  fullName: system.fabric.health.HealthEvent
  type: Class
  summary: <p>A <xref href="system.fabric.health._health_event" data-throw-if-not-resolved="false"></xref> object is a structure which contains the health information that is used while reporting health on an entity via ReportHealth API </p>
  syntax:
    content: public class HealthEvent
- uid: system.fabric.health._deployed_service_package_health_state
  parent: system.fabric.health
  href: system.fabric.health._deployed_service_package_health_state.yml
  name: DeployedServicePackageHealthState
  fullName: system.fabric.health.DeployedServicePackageHealthState
  type: Class
  summary: <p>Represents the health state of a deployed service package, containing the entity identifier and the aggregated health state. </p>
  syntax:
    content: public class DeployedServicePackageHealthState
- uid: system.fabric.health._deployed_application_health
  parent: system.fabric.health
  href: system.fabric.health._deployed_application_health.yml
  name: DeployedApplicationHealth
  fullName: system.fabric.health.DeployedApplicationHealth
  type: Class
  summary: <p>Describes the health of an application deployed on a node as returned by <xref href="system.fabric._health_client.getDeployedApplicationHealthAsync(DeployedApplicationHealthQueryDescription)" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class DeployedApplicationHealth extends EntityHealth
- uid: system.fabric._health_client.getDeployedApplicationHealthAsync(DeployedApplicationHealthQueryDescription)
  parent: system.fabric._health_client
  href: system.fabric._health_client.yml
  name: getDeployedApplicationHealthAsync(DeployedApplicationHealthQueryDescription queryDescription)
  fullName: CompletableFuture<DeployedApplicationHealth> system.fabric.HealthClient.getDeployedApplicationHealthAsync(DeployedApplicationHealthQueryDescription queryDescription)
  type: Method
  summary: >-
    <p>Asynchronously gets the health of a deployed Service Fabric application on the specified node.</p>

    <p></p>
  syntax:
    content: public CompletableFuture<DeployedApplicationHealth> getDeployedApplicationHealthAsync(DeployedApplicationHealthQueryDescription queryDescription)
    parameters:
    - id: queryDescription
      type: system.fabric._deployed_application_health_query_description
      description: <p>The query description </p>
    return:
      type: 9cdf14d0system.fabric.health._deployed_application_healtha08ddfce
      description: <p>The health of a deployed Service Fabric application. </p>
