items:
- uid: system.fabric._deployed_application_health_state_filter
  id: _deployed_application_health_state_filter
  parent: system.fabric
  children:
  - system.fabric._deployed_application_health_state_filter.DeployedApplicationHealthStateFilter()
  - system.fabric._deployed_application_health_state_filter.getDeployedServicePackageFilters()
  - system.fabric._deployed_application_health_state_filter.getHealthStateFilter()
  - system.fabric._deployed_application_health_state_filter.getNodeNameFilter()
  - system.fabric._deployed_application_health_state_filter.setHealthStateFilter(HealthStateFilter)
  - system.fabric._deployed_application_health_state_filter.setNodeNameFilter(String)
  - system.fabric._deployed_application_health_state_filter.toString()
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: DeployedApplicationHealthStateFilter
  fullName: system.fabric.DeployedApplicationHealthStateFilter
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 17
  package: system.fabric
  summary: >-
    <p>Filter for <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The health state chunk queries can specify a list of deployed application filters to fine-grain select the deployed applications that should be included in the query result. Note that all the deployed applications are used to evaluate parents' aggregated health state, regardless of the filter passed in. </p>
  syntax: &o1
    content: public class DeployedApplicationHealthStateFilter
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - system.fabric._deployed_application_health_state_filter.toNative(PinCollection)
  - system.fabric._deployed_application_health_state_filter.toNativeList(PinCollection,List<DeployedApplicationHealthStateFilter>)
- uid: system.fabric._deployed_application_health_state_filter.DeployedApplicationHealthStateFilter()
  id: DeployedApplicationHealthStateFilter()
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: DeployedApplicationHealthStateFilter()
  fullName: system.fabric.DeployedApplicationHealthStateFilter.DeployedApplicationHealthStateFilter()
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 28
  package: system.fabric
  syntax:
    content: public DeployedApplicationHealthStateFilter()
- uid: system.fabric._deployed_application_health_state_filter.getDeployedServicePackageFilters()
  id: getDeployedServicePackageFilters()
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: getDeployedServicePackageFilters()
  fullName: List<DeployedServicePackageHealthStateFilter> system.fabric.DeployedApplicationHealthStateFilter.getDeployedServicePackageFilters()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 33
  package: system.fabric
  syntax:
    content: public List<DeployedServicePackageHealthStateFilter> getDeployedServicePackageFilters()
    return:
      type: 5618da2dsystem.fabric._deployed_service_package_health_state_filtera08ddfce
- uid: system.fabric._deployed_application_health_state_filter.getHealthStateFilter()
  id: getHealthStateFilter()
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: getHealthStateFilter()
  fullName: HealthStateFilter system.fabric.DeployedApplicationHealthStateFilter.getHealthStateFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 51
  package: system.fabric
  summary: >-
    <p>Gets filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection.</p>

    <p>

      <bold>Remarks:</bold>The health state filter value comes from members or bitwise combination of members of <ref refid="" kindref="compound">HealthStateFilter</ref>. For a deployed application to match the filter, its aggregated health state must match the specified health state filter. </p>
  syntax:
    content: public HealthStateFilter getHealthStateFilter()
    return:
      type: system.fabric.health._health_state_filter
      description: <p>The filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection. </p>
- uid: system.fabric._deployed_application_health_state_filter.getNodeNameFilter()
  id: getNodeNameFilter()
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: getNodeNameFilter()
  fullName: String system.fabric.DeployedApplicationHealthStateFilter.getNodeNameFilter()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 83
  package: system.fabric
  summary: >-
    <p>Gets the node name filter.</p>

    <p>

      <bold>Remarks:</bold>If not specified, all deployed applications that match the parent filters (if any) are taken into consideration and matched against the other filter members, like health state filter. Otherwise, the filter only applies to applications deployed on the specified node. </p>
  syntax:
    content: public String getNodeNameFilter()
    return:
      type: "26831127"
      description: <p>The node name filter. </p>
- uid: system.fabric._deployed_application_health_state_filter.setHealthStateFilter(HealthStateFilter)
  id: setHealthStateFilter(HealthStateFilter)
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: setHealthStateFilter(HealthStateFilter healthStateFilter)
  fullName: void system.fabric.DeployedApplicationHealthStateFilter.setHealthStateFilter(HealthStateFilter healthStateFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 68
  package: system.fabric
  summary: >-
    <p>Sets filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection.</p>

    <p>

      <bold>Remarks:</bold>The health state filter value comes from members or bitwise combination of members of <ref refid="" kindref="compound">HealthStateFilter</ref>. For a deployed application to match the filter, its aggregated health state must match the specified health state filter. </p>
  syntax:
    content: public void setHealthStateFilter(HealthStateFilter healthStateFilter)
    parameters:
    - id: healthStateFilter
      type: system.fabric.health._health_state_filter
      description: <p>The filter for the aggregated health state of the <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> entries in the collection. </p>
- uid: system.fabric._deployed_application_health_state_filter.setNodeNameFilter(String)
  id: setNodeNameFilter(String)
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: setNodeNameFilter(String nodeNameFilter)
  fullName: void system.fabric.DeployedApplicationHealthStateFilter.setNodeNameFilter(String nodeNameFilter)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 99
  package: system.fabric
  summary: >-
    <p>Sets the node name filter.</p>

    <p>

      <bold>Remarks:</bold>If not specified, all deployed applications that match the parent filters (if any) are taken into consideration and matched against the other filter members, like health state filter. Otherwise, the filter only applies to applications deployed on the specified node. </p>
  syntax:
    content: public void setNodeNameFilter(String nodeNameFilter)
    parameters:
    - id: nodeNameFilter
      type: "26831127"
      description: <p>The node name filter. </p>
- uid: system.fabric._deployed_application_health_state_filter.toString()
  id: toString()
  parent: system.fabric._deployed_application_health_state_filter
  href: system.fabric._deployed_application_health_state_filter.yml
  langs:
  - java
  name: toString()
  fullName: String system.fabric.DeployedApplicationHealthStateFilter.toString()
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/DeployedApplicationHealthStateFilter.java
    startLine: 106
  package: system.fabric
  summary: <p>Returns a string representation of the filter. </p>
  syntax:
    content: public String toString()
    return:
      type: "26831127"
      description: <p>A string representation of the filter. </p>
references:
- uid: 5618da2dsystem.fabric._deployed_service_package_health_state_filtera08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: system.fabric._deployed_service_package_health_state_filter
    name: DeployedServicePackageHealthStateFilter
    fullName: system.fabric.DeployedServicePackageHealthStateFilter
    href: system.fabric._deployed_service_package_health_state_filter.yml
  - name: '>'
    fullName: '>'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric._deployed_application_health_state_filter.toNative(PinCollection)
- uid: system.fabric._deployed_application_health_state_filter.toNativeList(PinCollection,List<DeployedApplicationHealthStateFilter>)
- uid: system.fabric._deployed_service_package_health_state_filter
  parent: system.fabric
  href: system.fabric._deployed_service_package_health_state_filter.yml
  name: DeployedServicePackageHealthStateFilter
  fullName: system.fabric.DeployedServicePackageHealthStateFilter
  type: Class
  summary: >-
    <p>Filter for <xref href="system.fabric.health._deployed_service_package_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The health state chunk queries can specify a list of deployed service package filters to fine-grain select the deployed service packages that should be included in the query result. Note that all the deployed service packages are used to evaluate parents aggregated health state, regardless of the filter passed in. </p>
  syntax:
    content: public class DeployedServicePackageHealthStateFilter
- uid: system.fabric.health._health_state_filter
  parent: system.fabric.health
  href: system.fabric.health._health_state_filter.yml
  name: HealthStateFilter
  fullName: system.fabric.health.HealthStateFilter
  type: Enum
  syntax:
    content: public enum HealthStateFilter
- uid: system.fabric.health._deployed_application_health_state
  parent: system.fabric.health
  href: system.fabric.health._deployed_application_health_state.yml
  name: DeployedApplicationHealthState
  fullName: system.fabric.health.DeployedApplicationHealthState
  type: Class
  summary: <p>Represents the health state of a deployed application, which contains the entity identifier and the aggregated health state. </p>
  syntax:
    content: public class DeployedApplicationHealthState extends EntityHealthState
- uid: system.fabric._pin_collection
  parent: system.fabric
  href: system.fabric._pin_collection.yml
  name: PinCollection
  fullName: system.fabric.PinCollection
  type: Class
  syntax:
    content: public class PinCollection
- uid: system.fabric._deployed_application_health_state_filter
  parent: system.fabric
  href: system.fabric._deployed_application_health_state_filter.yml
  name: DeployedApplicationHealthStateFilter
  fullName: system.fabric.DeployedApplicationHealthStateFilter
  type: Class
  summary: >-
    <p>Filter for <xref href="system.fabric.health._deployed_application_health_state" data-throw-if-not-resolved="false"></xref> objects. </p>

    <p>

      <bold>Remarks:</bold>The health state chunk queries can specify a list of deployed application filters to fine-grain select the deployed applications that should be included in the query result. Note that all the deployed applications are used to evaluate parents' aggregated health state, regardless of the filter passed in. </p>
  syntax: *o1
