items:
- uid: test._application_management
  id: _application_management
  parent: test
  children:
  - test._application_management.main(String[])
  href: test._application_management.yml
  langs:
  - java
  name: ApplicationManagement
  fullName: test.ApplicationManagement
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/sample/ManagedAPIs/ApplicationManagement/src/test/ApplicationManagement.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/sample/ManagedAPIs/ApplicationManagement/src/test/ApplicationManagement.java
    startLine: 44
  package: test
  syntax:
    content: public class ApplicationManagement
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - test._application_management.[static initializer]()
  - test._application_management.apClient()
  - test._application_management.fabricClient()
- uid: test._application_management.main(String[])
  id: main(String[])
  parent: test._application_management
  href: test._application_management.yml
  langs:
  - java
  name: main(String[] args)
  fullName: static void test.ApplicationManagement.main(String[] args)
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/sample/ManagedAPIs/ApplicationManagement/src/test/ApplicationManagement.java
    startLine: 48
  package: test
  syntax:
    content: public static void main(String[] args)
    parameters:
    - id: args
      type: 30d59cf1
references:
- uid: 30d59cf1
  spec.java:
  - name: String[]
    fullName: String[]
- uid: test._application_management.[static initializer]()
- uid: test._application_management.apClient()
- uid: test._application_management.fabricClient()
- uid: system.fabric._fabric_client
  parent: system.fabric
  href: system.fabric._fabric_client.yml
  name: FabricClient
  fullName: system.fabric.FabricClient
  type: Class
  summary: >-
    <p>Creates and manages Service Fabric services and other entities. </p>

    <p>

      <bold>Remarks:</bold>It is highly recommended that you share FabricClients as much as possible. This is because the <xref href="system.fabric._fabric_client" data-throw-if-not-resolved="false"></xref> has multiple optimizations such as caching and batching that you would not be able to fully utilize otherwise. </p>
  syntax:
    content: public class FabricClient
- uid: system.fabric._application_management_client
  parent: system.fabric
  href: system.fabric._application_management_client.yml
  name: ApplicationManagementClient
  fullName: system.fabric.ApplicationManagementClient
  type: Class
  summary: <p>Provides the ability to deploy/un-deploy/create/delete applications and services </p>
  syntax:
    content: public class ApplicationManagementClient
- uid: system.fabric._package_sharing_policy_list
  parent: system.fabric
  href: system.fabric._package_sharing_policy_list.yml
  name: PackageSharingPolicyList
  fullName: system.fabric.PackageSharingPolicyList
  type: Class
  summary: <p>Represents a list of <xref href="system.fabric._package_sharing_policy" data-throw-if-not-resolved="false"></xref> objects. </p>
  syntax:
    content: public class PackageSharingPolicyList
- uid: system.fabric.health._health_evaluation
  parent: system.fabric.health
  href: system.fabric.health._health_evaluation.yml
  name: HealthEvaluation
  fullName: system.fabric.health.HealthEvaluation
  type: Class
  summary: <p>Represents a health evaluation which describes the data and the algorithm used by health store to evaluate the health of an entity. </p>
  syntax:
    content: public class HealthEvaluation
- uid: system.fabric._application_description
  parent: system.fabric
  href: system.fabric._application_description.yml
  name: ApplicationDescription
  fullName: system.fabric.ApplicationDescription
  type: Class
  summary: <p>Describes an application to be created by using <xref href="system.fabric._application_management_client.createApplicationAsync(ApplicationDescription)" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ApplicationDescription
- uid: system.fabric._application_upgrade_description
  parent: system.fabric
  href: system.fabric._application_upgrade_description.yml
  name: ApplicationUpgradeDescription
  fullName: system.fabric.ApplicationUpgradeDescription
  type: Class
  summary: <p>Describes the upgrade policy and the application to be upgraded. </p>
  syntax:
    content: public class ApplicationUpgradeDescription
- uid: system.fabric._application_upgrade_update_description
  parent: system.fabric
  href: system.fabric._application_upgrade_update_description.yml
  name: ApplicationUpgradeUpdateDescription
  fullName: system.fabric.ApplicationUpgradeUpdateDescription
  type: Class
  summary: <p>Used to modify the upgrade parameters describing the behavior of application upgrades. </p>
  syntax:
    content: public class ApplicationUpgradeUpdateDescription
- uid: system.fabric._application_update_description
  parent: system.fabric
  href: system.fabric._application_update_description.yml
  name: ApplicationUpdateDescription
  fullName: system.fabric.ApplicationUpdateDescription
  type: Class
  summary: <p>Describes an update of application capacity that will be updated using <xref href="system.fabric._application_management_client.updateApplicationAsync(ApplicationUpdateDescription)" data-throw-if-not-resolved="false"></xref></p>
  syntax:
    content: public class ApplicationUpdateDescription
