items:
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  id: _add_application_package_result_inner
  parent: com.microsoft.azure.management.batch.implementation
  children:
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.id()
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.storageUrl()
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.storageUrlExpiry()
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.version()
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withId(String)
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withStorageUrl(String)
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withStorageUrlExpiry(DateTime)
  - com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withVersion(String)
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: AddApplicationPackageResultInner
  fullName: com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 15
  package: com.microsoft.azure.management.batch.implementation
  summary: <p>Response to an ApplicationOperations.AddApplicationPackage request. </p>
  syntax: &o1
    content: public class AddApplicationPackageResultInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.id()
  id: id()
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: id()
  fullName: String com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.id()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 41
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.storageUrl()
  id: storageUrl()
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: storageUrl()
  fullName: String com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.storageUrl()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 81
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the storageUrl value.</p>

    <p></p>
  syntax:
    content: public String storageUrl()
    return:
      type: "26831127"
      description: <p>the storageUrl value </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.storageUrlExpiry()
  id: storageUrlExpiry()
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: storageUrlExpiry()
  fullName: DateTime com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.storageUrlExpiry()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 101
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the storageUrlExpiry value.</p>

    <p></p>
  syntax:
    content: public DateTime storageUrlExpiry()
    return:
      type: 230df18c
      description: <p>the storageUrlExpiry value </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.version()
  id: version()
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: version()
  fullName: String com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.version()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 61
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the version value.</p>

    <p></p>
  syntax:
    content: public String version()
    return:
      type: "26831127"
      description: <p>the version value </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withId(String)
  id: withId(String)
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: withId(String id)
  fullName: AddApplicationPackageResultInner com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.withId(String id)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 51
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public AddApplicationPackageResultInner withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._add_application_package_result_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withStorageUrl(String)
  id: withStorageUrl(String)
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: withStorageUrl(String storageUrl)
  fullName: AddApplicationPackageResultInner com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.withStorageUrl(String storageUrl)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 91
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the storageUrl value.</p>

    <p></p>
  syntax:
    content: public AddApplicationPackageResultInner withStorageUrl(String storageUrl)
    parameters:
    - id: storageUrl
      type: "26831127"
      description: <p>the storageUrl value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._add_application_package_result_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withStorageUrlExpiry(DateTime)
  id: withStorageUrlExpiry(DateTime)
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: withStorageUrlExpiry(DateTime storageUrlExpiry)
  fullName: AddApplicationPackageResultInner com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.withStorageUrlExpiry(DateTime storageUrlExpiry)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 111
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the storageUrlExpiry value.</p>

    <p></p>
  syntax:
    content: public AddApplicationPackageResultInner withStorageUrlExpiry(DateTime storageUrlExpiry)
    parameters:
    - id: storageUrlExpiry
      type: 230df18c
      description: <p>the storageUrlExpiry value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._add_application_package_result_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.withVersion(String)
  id: withVersion(String)
  parent: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  langs:
  - java
  name: withVersion(String version)
  fullName: AddApplicationPackageResultInner com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner.withVersion(String version)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/AddApplicationPackageResultInner.java
    startLine: 71
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the version value.</p>

    <p></p>
  syntax:
    content: public AddApplicationPackageResultInner withVersion(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._add_application_package_result_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner
  parent: com.microsoft.azure.management.batch.implementation
  href: com.microsoft.azure.management.batch.implementation._add_application_package_result_inner.yml
  name: AddApplicationPackageResultInner
  fullName: com.microsoft.azure.management.batch.implementation.AddApplicationPackageResultInner
  type: Class
  summary: <p>Response to an ApplicationOperations.AddApplicationPackage request. </p>
  syntax: *o1
