items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
  id: _update_ac39f7ab2f23f0c3db8049ad3667081e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 302
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface WithPrivateIp<ParentT> extends HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< WithAttach< ParentT > >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress<ReturnT>
  type: Interface
  summary: <p>The stage of a definition allowing to specify the private IP address. </p>
  syntax:
    content: public interface WithPrivateIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition.yml
  name: NicIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a network interface IP configuration definition as part of a network interface update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.Blank< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithAttach< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
