items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration
  id: _nic_ip_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration.network()
  - com.microsoft.azure.management.network._nic_ip_configuration.publicIpAddress()
  - com.microsoft.azure.management.network._nic_ip_configuration.publicIpAddressId()
  - com.microsoft.azure.management.network._nic_ip_configuration.subnetId()
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: NicIpConfiguration
  fullName: com.microsoft.azure.management.network.NicIpConfiguration
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 16
  package: com.microsoft.azure.management.network
  summary: <p>An IP configuration in a network interface. </p>
  syntax:
    content: public interface NicIpConfiguration extends Wrapper< NetworkInterfaceIPConfigurationInner >,ChildResource,HasPrivateIpAddress
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  - com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  - com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.name()
  - com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAddress()
  - com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAllocationMethod()
- uid: com.microsoft.azure.management.network._nic_ip_configuration.network()
  id: network()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: network()
  fullName: Network com.microsoft.azure.management.network.NicIpConfiguration.network()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 54
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the virtual network associated with this IP configuration. </p>

    <p>This method makes a rest API call to fetch the public IP.</p>

    <p></p>
  syntax:
    content: public Network network()
    return:
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network associated with this this IP configuration. </p>
  exceptions:
  - type: com.microsoft.azure._cloud_exception
    description: <p>exceptions thrown from the cloud. </p>
  - type: cbf33bbe
    description: <p>exceptions thrown from serialization/deserialization. </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration.publicIpAddress()
  id: publicIpAddress()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: publicIpAddress()
  fullName: PublicIpAddress com.microsoft.azure.management.network.NicIpConfiguration.publicIpAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 38
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the public IP address associated with this IP configuration. </p>

    <p>This method makes a rest API call to fetch the public IP.</p>

    <p></p>
  syntax:
    content: public PublicIpAddress publicIpAddress()
    return:
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>the public IP associated with this IP configuration or null if there is no public IP associated </p>
  exceptions:
  - type: com.microsoft.azure._cloud_exception
    description: <p>exceptions thrown from the cloud. </p>
  - type: cbf33bbe
    description: <p>exceptions thrown from serialization/deserialization. </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration.publicIpAddressId()
  id: publicIpAddressId()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: publicIpAddressId()
  fullName: String com.microsoft.azure.management.network.NicIpConfiguration.publicIpAddressId()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 27
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the resource id of the public IP address associated with this IP configuration.</p>

    <p></p>
  syntax:
    content: public String publicIpAddressId()
    return:
      type: "26831127"
      description: <p>public IP resource ID or null if there is no public IP associated </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration.subnetId()
  id: subnetId()
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: subnetId()
  fullName: String com.microsoft.azure.management.network.NicIpConfiguration.subnetId()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 43
  package: com.microsoft.azure.management.network
  syntax:
    content: public String subnetId()
    return:
      type: "26831127"
      description: <p>the resource id of the virtual network subnet associated with this IP configuration. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper.inner()
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable.key()
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.name()
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: name()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource.name()
  type: Method
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name of the child resource </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAddress()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: privateIpAddress()
  fullName: String com.microsoft.azure.management.network.model.HasPrivateIpAddress.privateIpAddress()
  type: Method
  syntax:
    content: public String privateIpAddress()
    return:
      type: "26831127"
      description: <p>the protocol </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address.privateIpAllocationMethod()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: privateIpAllocationMethod()
  fullName: IPAllocationMethod com.microsoft.azure.management.network.model.HasPrivateIpAddress.privateIpAllocationMethod()
  type: Method
  syntax:
    content: public IPAllocationMethod privateIpAllocationMethod()
    return:
      type: com.microsoft.azure.management.network._i_p_allocation_method
      description: <p>the private IP address allocation method within the associated subnet </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: Wrapper<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>
  type: Interface
  summary: >-
    <p>The wrapper around an inner object providing extended functionalities.</p>

    <p></p>
  syntax:
    content: public interface Wrapper<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the inner object. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: ChildResource
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource
  type: Interface
  summary: <p>Base interface used by child resources. </p>
  syntax:
    content: public interface ChildResource extends Indexable
- uid: com.microsoft.azure.management.network.model._has_private_ip_address
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address.yml
  name: HasPrivateIpAddress
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress
  type: Interface
  summary: <p>An interface representing a model's ability to reference a private IP address. </p>
  syntax:
    content: public interface HasPrivateIpAddress
- uid: com.microsoft.azure.management.network.implementation._nic_ip_configuration_impl
- uid: com.microsoft.azure.management.network._public_ip_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._public_ip_address.yml
  name: PublicIpAddress
  fullName: com.microsoft.azure.management.network.PublicIpAddress
  type: Interface
  summary: <p>Public IP address. </p>
  syntax:
    content: public interface PublicIpAddress
- uid: com.microsoft.azure._cloud_exception
  parent: com.microsoft.azure
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException
  fullName: com.microsoft.azure.CloudException
  type: Class
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class CloudException extends RestException
- uid: com.microsoft.azure.management.network._network
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network.yml
  name: Network
  fullName: com.microsoft.azure.management.network.Network
  type: Interface
  summary: <p>Entry point for Virtual <xref href="com.microsoft.azure.management.network._network" data-throw-if-not-resolved="false"></xref> management API in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Network extends GroupableResource,Refreshable< Network >,Wrapper< VirtualNetworkInner >,Updatable< Network.Update >
