items:
- uid: com.microsoft.azure._azure_environment
  id: _azure_environment
  parent: com.microsoft.azure
  children:
  - com.microsoft.azure._azure_environment.AZURE()
  - com.microsoft.azure._azure_environment.AZURE_CHINA()
  - com.microsoft.azure._azure_environment.AZURE_GERMANY()
  - com.microsoft.azure._azure_environment.AZURE_US_GOVERNMENT()
  - com.microsoft.azure._azure_environment.AzureEnvironment(String,String,String,String)
  - com.microsoft.azure._azure_environment.getAuthenticationEndpoint()
  - com.microsoft.azure._azure_environment.getBaseUrl()
  - com.microsoft.azure._azure_environment.getGraphEndpoint()
  - com.microsoft.azure._azure_environment.getManagementEndpoint()
  - com.microsoft.azure._azure_environment.isValidateAuthority()
  - com.microsoft.azure._azure_environment.newRestClientBuilder()
  - com.microsoft.azure._azure_environment.setValidateAuthority(boolean)
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AzureEnvironment
  fullName: com.microsoft.azure.AzureEnvironment
  type: Class
  source:
    remote: &o0
      path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 12
  package: com.microsoft.azure
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class AzureEnvironment
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure._azure_environment.AZURE()
  id: AZURE()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 62
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE= new AzureEnvironment(
                  "https://login.microsoftonline.com/",
                  "https://management.core.windows.net/",
                  "https://management.azure.com/",
                  "https://graph.windows.net/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment.AZURE_CHINA()
  id: AZURE_CHINA()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE_CHINA
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE_CHINA
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 71
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> China. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_CHINA= new AzureEnvironment(
                  "https://login.chinacloudapi.cn/",
                  "https://management.core.chinacloudapi.cn/",
                  "https://management.chinacloudapi.cn/",
                  "https://graph.chinacloudapi.cn/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment.AZURE_GERMANY()
  id: AZURE_GERMANY()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE_GERMANY
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE_GERMANY
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 89
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Germany. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_GERMANY= new AzureEnvironment(
                  "https://login.microsoftonline.de/",
                  "https://management.core.cloudapi.de/",
                  "https://management.microsoftazure.de/",
                  "https://graph.cloudapi.de/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment.AZURE_US_GOVERNMENT()
  id: AZURE_US_GOVERNMENT()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AZURE_US_GOVERNMENT
  fullName: final AzureEnvironment com.microsoft.azure.AzureEnvironment.AZURE_US_GOVERNMENT
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 80
  package: com.microsoft.azure
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> US Government. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_US_GOVERNMENT= new AzureEnvironment(
                  "https://login.microsoftonline.com/",
                  "https://management.core.usgovcloudapi.net/",
                  "https://management.usgovcloudapi.net/",
                  "https://graph.windows.net/")
    return:
      type: 93de0ef9com.microsoft.azure._azure_environment
- uid: com.microsoft.azure._azure_environment.AzureEnvironment(String,String,String,String)
  id: AzureEnvironment(String,String,String,String)
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: AzureEnvironment(String authenticationEndpoint, String managementEndpoint, String resourceManagerEndpoint, String graphEndpoint)
  fullName: com.microsoft.azure.AzureEnvironment.AzureEnvironment(String authenticationEndpoint, String managementEndpoint, String resourceManagerEndpoint, String graphEndpoint)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 47
  package: com.microsoft.azure
  summary: >-
    <p>Initializes an instance of <xref href="com.microsoft.azure._azure_environment" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public AzureEnvironment(String authenticationEndpoint, String managementEndpoint, String resourceManagerEndpoint, String graphEndpoint)
    parameters:
    - id: authenticationEndpoint
      type: "26831127"
      description: <p>ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment. </p>
    - id: managementEndpoint
      type: "26831127"
      description: <p>token audience for an endpoint. </p>
    - id: resourceManagerEndpoint
      type: "26831127"
      description: <p>the base URL for the current environment. </p>
    - id: graphEndpoint
      type: "26831127"
      description: <p>the base URL for graph API. </p>
- uid: com.microsoft.azure._azure_environment.getAuthenticationEndpoint()
  id: getAuthenticationEndpoint()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getAuthenticationEndpoint()
  fullName: String com.microsoft.azure.AzureEnvironment.getAuthenticationEndpoint()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 116
  package: com.microsoft.azure
  syntax:
    content: public String getAuthenticationEndpoint()
    return:
      type: "26831127"
      description: <p>the ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment. </p>
- uid: com.microsoft.azure._azure_environment.getBaseUrl()
  id: getBaseUrl()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getBaseUrl()
  fullName: String com.microsoft.azure.AzureEnvironment.getBaseUrl()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 100
  package: com.microsoft.azure
  summary: >-
    <p>Gets the base URL of the management service.</p>

    <p></p>
  syntax:
    content: public String getBaseUrl()
    return:
      type: "26831127"
      description: <p>the Base URL for the management service. </p>
- uid: com.microsoft.azure._azure_environment.getGraphEndpoint()
  id: getGraphEndpoint()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getGraphEndpoint()
  fullName: String com.microsoft.azure.AzureEnvironment.getGraphEndpoint()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 130
  package: com.microsoft.azure
  syntax:
    content: public String getGraphEndpoint()
    return:
      type: "26831127"
      description: <p>the <xref href="com.microsoft.azure._graph" data-throw-if-not-resolved="false"></xref> API endpoint. </p>
- uid: com.microsoft.azure._azure_environment.getManagementEndpoint()
  id: getManagementEndpoint()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: getManagementEndpoint()
  fullName: String com.microsoft.azure.AzureEnvironment.getManagementEndpoint()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 123
  package: com.microsoft.azure
  syntax:
    content: public String getManagementEndpoint()
    return:
      type: "26831127"
      description: <p>the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref><xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> Manager endpoint for the environment. </p>
- uid: com.microsoft.azure._azure_environment.isValidateAuthority()
  id: isValidateAuthority()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: isValidateAuthority()
  fullName: boolean com.microsoft.azure.AzureEnvironment.isValidateAuthority()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 141
  package: com.microsoft.azure
  summary: >-
    <p>Gets whether the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD.</p>

    <p></p>
  syntax:
    content: public boolean isValidateAuthority()
    return:
      type: 4fc6e284
      description: <p>true if the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD, false otherwise. </p>
- uid: com.microsoft.azure._azure_environment.newRestClientBuilder()
  id: newRestClientBuilder()
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: newRestClientBuilder()
  fullName: RestClient.Builder.Buildable com.microsoft.azure.AzureEnvironment.newRestClientBuilder()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 107
  package: com.microsoft.azure
  syntax:
    content: public RestClient.Builder.Buildable newRestClientBuilder()
    return:
      type: 9ab08eaf
      description: <p>a builder for the rest client. </p>
- uid: com.microsoft.azure._azure_environment.setValidateAuthority(boolean)
  id: setValidateAuthority(boolean)
  parent: com.microsoft.azure._azure_environment
  href: com.microsoft.azure._azure_environment.yml
  langs:
  - java
  name: setValidateAuthority(boolean validateAuthority)
  fullName: void com.microsoft.azure.AzureEnvironment.setValidateAuthority(boolean validateAuthority)
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
    startLine: 152
  package: com.microsoft.azure
  summary: >-
    <p>Sets whether the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD.</p>

    <p></p>
  syntax:
    content: public void setValidateAuthority(boolean validateAuthority)
    parameters:
    - id: validateAuthority
      type: 4fc6e284
      description: <p>true if the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD, false otherwise. </p>
references:
- uid: 93de0ef9com.microsoft.azure._azure_environment
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure._azure_environment
    name: AzureEnvironment
    fullName: com.microsoft.azure.AzureEnvironment
    href: com.microsoft.azure._azure_environment.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 9ab08eaf
  spec.java:
  - name: RestClient.Builder.Buildable
    fullName: RestClient.Builder.Buildable
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure._azure_environment
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure_environment.yml
  name: AzureEnvironment
  fullName: com.microsoft.azure.AzureEnvironment
  type: Class
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
- uid: com.microsoft.azure._graph
  parent: com.microsoft.azure
  href: com.microsoft.azure._graph.yml
  name: Graph<T,U>
  fullName: com.microsoft.azure.Graph<T,U>
  type: Class
  summary: >-
    <p>Type representing a directed graph data structure. </p>

    <p>Each node in a graph is represented by <xref href="com.microsoft.azure._node" data-throw-if-not-resolved="false"></xref></p>

    <p></p>
  syntax:
    content: public class Graph<T,U extends Node< T>>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the data stored in the graph's nodes </p>
    - type: 6043614c
      description: <p>the type of the nodes in the graph </p>
