items:
- uid: com.microsoft.azure.management.batch._application_package
  id: _application_package
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._application_package.format()
  - com.microsoft.azure.management.batch._application_package.lastActivationTime()
  - com.microsoft.azure.management.batch._application_package.state()
  - com.microsoft.azure.management.batch._application_package.version()
  - com.microsoft.azure.management.batch._application_package.withFormat(String)
  - com.microsoft.azure.management.batch._application_package.withLastActivationTime(DateTime)
  - com.microsoft.azure.management.batch._application_package.withState(PackageState)
  - com.microsoft.azure.management.batch._application_package.withVersion(String)
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: ApplicationPackage
  fullName: com.microsoft.azure.management.batch.ApplicationPackage
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 15
  package: com.microsoft.azure.management.batch
  summary: <p>Contains information about an application package. </p>
  syntax: &o1
    content: public class ApplicationPackage
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.batch._application_package.format()
  id: format()
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: format()
  fullName: String com.microsoft.azure.management.batch.ApplicationPackage.format()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 84
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Get the format value.</p>

    <p></p>
  syntax:
    content: public String format()
    return:
      type: "26831127"
      description: <p>the format value </p>
- uid: com.microsoft.azure.management.batch._application_package.lastActivationTime()
  id: lastActivationTime()
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: lastActivationTime()
  fullName: DateTime com.microsoft.azure.management.batch.ApplicationPackage.lastActivationTime()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 104
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Get the lastActivationTime value.</p>

    <p></p>
  syntax:
    content: public DateTime lastActivationTime()
    return:
      type: 230df18c
      description: <p>the lastActivationTime value </p>
- uid: com.microsoft.azure.management.batch._application_package.state()
  id: state()
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: state()
  fullName: PackageState com.microsoft.azure.management.batch.ApplicationPackage.state()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 64
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Get the state value.</p>

    <p></p>
  syntax:
    content: public PackageState state()
    return:
      type: com.microsoft.azure.management.batch._package_state
      description: <p>the state value </p>
- uid: com.microsoft.azure.management.batch._application_package.version()
  id: version()
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: version()
  fullName: String com.microsoft.azure.management.batch.ApplicationPackage.version()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 44
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Get the version value.</p>

    <p></p>
  syntax:
    content: public String version()
    return:
      type: "26831127"
      description: <p>the version value </p>
- uid: com.microsoft.azure.management.batch._application_package.withFormat(String)
  id: withFormat(String)
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: withFormat(String format)
  fullName: ApplicationPackage com.microsoft.azure.management.batch.ApplicationPackage.withFormat(String format)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 94
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Set the format value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackage withFormat(String format)
    parameters:
    - id: format
      type: "26831127"
      description: <p>the format value to set </p>
    return:
      type: com.microsoft.azure.management.batch._application_package
      description: <p>the <xref href="com.microsoft.azure.management.batch._application_package" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch._application_package.withLastActivationTime(DateTime)
  id: withLastActivationTime(DateTime)
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: withLastActivationTime(DateTime lastActivationTime)
  fullName: ApplicationPackage com.microsoft.azure.management.batch.ApplicationPackage.withLastActivationTime(DateTime lastActivationTime)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 114
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Set the lastActivationTime value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackage withLastActivationTime(DateTime lastActivationTime)
    parameters:
    - id: lastActivationTime
      type: 230df18c
      description: <p>the lastActivationTime value to set </p>
    return:
      type: com.microsoft.azure.management.batch._application_package
      description: <p>the <xref href="com.microsoft.azure.management.batch._application_package" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch._application_package.withState(PackageState)
  id: withState(PackageState)
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: withState(PackageState state)
  fullName: ApplicationPackage com.microsoft.azure.management.batch.ApplicationPackage.withState(PackageState state)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 74
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Set the state value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackage withState(PackageState state)
    parameters:
    - id: state
      type: com.microsoft.azure.management.batch._package_state
      description: <p>the state value to set </p>
    return:
      type: com.microsoft.azure.management.batch._application_package
      description: <p>the <xref href="com.microsoft.azure.management.batch._application_package" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch._application_package.withVersion(String)
  id: withVersion(String)
  parent: com.microsoft.azure.management.batch._application_package
  href: com.microsoft.azure.management.batch._application_package.yml
  langs:
  - java
  name: withVersion(String version)
  fullName: ApplicationPackage com.microsoft.azure.management.batch.ApplicationPackage.withVersion(String version)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/ApplicationPackage.java
    startLine: 54
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Set the version value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackage withVersion(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version value to set </p>
    return:
      type: com.microsoft.azure.management.batch._application_package
      description: <p>the <xref href="com.microsoft.azure.management.batch._application_package" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.azure.management.batch._package_state
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._package_state.yml
  name: PackageState
  fullName: com.microsoft.azure.management.batch.PackageState
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.batch._package_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum PackageState
- uid: com.microsoft.azure.management.batch._application_package
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application_package.yml
  name: ApplicationPackage
  fullName: com.microsoft.azure.management.batch.ApplicationPackage
  type: Class
  summary: <p>Contains information about an application package. </p>
  syntax: *o1
